# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    pass
    #obj = bld.create_ns3_program('roff-example', ['roff'])
    #obj.source = 'roff-example.cc'

