SUMO - Simulation of Urban MObility: TraCI_VehicleType Class Reference
TraCI_VehicleType Class Reference
#include <TraCI_VehicleType.h>
Static Public Member Functions
static void addParameter (const std::string &id, const std::string &name, const std::string &value)
static double getAccel (const std::string &typeID)
static TraCIColor getColor (const std::string &typeID)
static double getDecel (const std::string &typeID)
static std::string getEmissionClass (const std::string &typeID)
static double getHeight (const std::string &typeID)
static std::vector< std::string > getIDList ()
static double getImperfection (const std::string &typeID)
static std::string getLateralAlignment (const std::string &typeID)
static double getLength (const std::string &typeID)
static double getMaxSpeed (const std::string &typeID)
static double getMaxSpeedLat (const std::string &typeID)
static double getMinGap (const std::string &typeID)
static double getMinGapLat (const std::string &typeID)
static std::string getParameter (const std::string &typeID, const std::string &key)
static std::string getShapeClass (const std::string &typeID)
static double getSpeedDeviation (const std::string &typeID)
static double getSpeedFactor (const std::string &typeID)
static double getTau (const std::string &typeID)
static std::string getVehicleClass (const std::string &typeID)
static MSVehicleType * getVType (std::string id)
static double getWidth (const std::string &typeID)
static void setAccel (const std::string &typeID, double accel)
static void setColor (const std::string &typeID, const TraCIColor &c)
static void setDecel (const std::string &typeID, double decel)
static void setEmissionClass (const std::string &typeID, const std::string &clazz)
static void setHeight (const std::string &typeID, double height)
static void setImperfection (const std::string &typeID, double imperfection)
static void setLateralAlignment (const std::string &typeID, const std::string &latAlignment)
static void setLength (const std::string &typeID, double length)
static void setMaxSpeed (const std::string &typeID, double speed)
static void setMaxSpeedLat (const std::string &typeID, double speed)
static void setMinGap (const std::string &typeID, double minGap)
static void setMinGapLat (const std::string &typeID, double minGapLat)
static void setShapeClass (const std::string &typeID, const std::string &shapeClass)
static void setSpeedDeviation (const std::string &typeID, double deviation)
static void setSpeedFactor (const std::string &typeID, double factor)
static void setTau (const std::string &typeID, double tau)
static void setVehicleClass (const std::string &typeID, const std::string &clazz)
static void setWidth (const std::string &typeID, double width)
Private Member Functions
TraCI_VehicleType & operator= (const TraCI_VehicleType &src)
invalidated assignment operator
TraCI_VehicleType ()
invalidated standard constructor
TraCI_VehicleType (const TraCI_VehicleType &src)
invalidated copy constructor
Detailed Description
Definition at line 28 of file TraCI_VehicleType.h.
Constructor & Destructor Documentation
TraCI_VehicleType::TraCI_VehicleType () private
invalidated standard constructor
TraCI_VehicleType::TraCI_VehicleType (const TraCI_VehicleType & src) private
invalidated copy constructor
Member Function Documentation
void TraCI_VehicleType::addParameter (const std::string & id, const std::string & name, const std::string & value) static
Definition at line 185 of file TraCI_VehicleType.cpp.
References MSVehicleType::getParameter(), and getVType().
Referenced by TraCIServerAPI_VehicleType::setVariable().
double TraCI_VehicleType::getAccel (const std::string & typeID) static
Definition at line 46 of file TraCI_VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getMaxAccel(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
TraCIColor TraCI_VehicleType::getColor (const std::string & typeID) static
Definition at line 86 of file TraCI_VehicleType.cpp.
References MSVehicleType::getColor(), getVType(), and TraCI::makeTraCIColor().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getDecel (const std::string & typeID) static
Definition at line 50 of file TraCI_VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getMaxDecel(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
std::string TraCI_VehicleType::getEmissionClass (const std::string & typeID) static
Definition at line 66 of file TraCI_VehicleType.cpp.
References MSVehicleType::getEmissionClass(), PollutantsInterface::getName(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getHeight (const std::string & typeID) static
Definition at line 82 of file TraCI_VehicleType.cpp.
References MSVehicleType::getHeight(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
std::vector< std::string > TraCI_VehicleType::getIDList () static
Definition at line 25 of file TraCI_VehicleType.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), and MSVehicleControl::insertVTypeIDs().
Referenced by TraCIServerAPI_VehicleType::processGet().
double TraCI_VehicleType::getImperfection (const std::string & typeID) static
Definition at line 54 of file TraCI_VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getImperfection(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
std::string TraCI_VehicleType::getLateralAlignment (const std::string & typeID) static
Definition at line 98 of file TraCI_VehicleType.cpp.
References MSVehicleType::getPreferredLateralAlignment(), getVType(), and toString().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getLength (const std::string & typeID) static
Definition at line 30 of file TraCI_VehicleType.cpp.
References MSVehicleType::getLength(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getMaxSpeed (const std::string & typeID) static
Definition at line 34 of file TraCI_VehicleType.cpp.
References MSVehicleType::getMaxSpeed(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getMaxSpeedLat (const std::string & typeID) static
Definition at line 94 of file TraCI_VehicleType.cpp.
References MSVehicleType::getMaxSpeedLat(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getMinGap (const std::string & typeID) static
Definition at line 74 of file TraCI_VehicleType.cpp.
References MSVehicleType::getMinGap(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getMinGapLat (const std::string & typeID) static
Definition at line 90 of file TraCI_VehicleType.cpp.
References MSVehicleType::getMinGapLat(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
std::string TraCI_VehicleType::getParameter (const std::string & typeID, const std::string & key) static
Definition at line 105 of file TraCI_VehicleType.cpp.
References Parameterised::getParameter(), MSVehicleType::getParameter(), and getVType().
Referenced by TraCIServerAPI_VehicleType::processGet().
std::string TraCI_VehicleType::getShapeClass (const std::string & typeID) static
Definition at line 70 of file TraCI_VehicleType.cpp.
References MSVehicleType::getGuiShape(), getVehicleShapeName(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getSpeedDeviation (const std::string & typeID) static
Definition at line 42 of file TraCI_VehicleType.cpp.
References Distribution_Parameterized::getParameter(), MSVehicleType::getSpeedFactor(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getSpeedFactor (const std::string & typeID) static
Definition at line 38 of file TraCI_VehicleType.cpp.
References Distribution_Parameterized::getParameter(), MSVehicleType::getSpeedFactor(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
double TraCI_VehicleType::getTau (const std::string & typeID) static
Definition at line 58 of file TraCI_VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getHeadwayTime(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
std::string TraCI_VehicleType::getVehicleClass (const std::string & typeID) static
Definition at line 62 of file TraCI_VehicleType.cpp.
References MSVehicleType::getVehicleClass(), getVType(), and toString().
Referenced by TraCIServerAPI_VehicleType::getVariable().
MSVehicleType * TraCI_VehicleType::getVType (std::string id) static
Definition at line 189 of file TraCI_VehicleType.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), and MSVehicleControl::getVType().
Referenced by addParameter(), getAccel(), getColor(), getDecel(), getEmissionClass(), getHeight(), getImperfection(), getLateralAlignment(), getLength(), getMaxSpeed(), getMaxSpeedLat(), getMinGap(), getMinGapLat(), getParameter(), getShapeClass(), getSpeedDeviation(), getSpeedFactor(), getTau(), getVehicleClass(), getWidth(), setAccel(), setColor(), setDecel(), setEmissionClass(), setHeight(), setImperfection(), setLateralAlignment(), setLength(), setMaxSpeed(), setMaxSpeedLat(), setMinGap(), setMinGapLat(), setShapeClass(), setSpeedDeviation(), setSpeedFactor(), setTau(), setVehicleClass(), and setWidth().
double TraCI_VehicleType::getWidth (const std::string & typeID) static
Definition at line 78 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::getWidth().
Referenced by TraCIServerAPI_VehicleType::getVariable().
TraCI_VehicleType& TraCI_VehicleType::operator= (const TraCI_VehicleType & src) private
invalidated assignment operator
void TraCI_VehicleType::setAccel (const std::string & typeID, double accel) static
Definition at line 151 of file TraCI_VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setMaxAccel().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setColor (const std::string & typeID, const TraCIColor & c) static
Definition at line 167 of file TraCI_VehicleType.cpp.
References getVType(), TraCI::makeRGBColor(), and MSVehicleType::setColor().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setDecel (const std::string & typeID, double decel) static
Definition at line 155 of file TraCI_VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setMaxDecel().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setEmissionClass (const std::string & typeID, const std::string & clazz) static
Definition at line 131 of file TraCI_VehicleType.cpp.
References PollutantsInterface::getClassByName(), getVType(), and MSVehicleType::setEmissionClass().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setHeight (const std::string & typeID, double height) static
Definition at line 143 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setHeight().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setImperfection (const std::string & typeID, double imperfection) static
Definition at line 159 of file TraCI_VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setImperfection().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setLateralAlignment (const std::string & typeID, const std::string & latAlignment) static
Definition at line 180 of file TraCI_VehicleType.cpp.
References getVType(), SUMOXMLDefinitions::LateralAlignments, and MSVehicleType::setPreferredLateralAlignment().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setLength (const std::string & typeID, double length) static
Definition at line 111 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setLength().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setMaxSpeed (const std::string & typeID, double speed) static
Definition at line 115 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setMaxSpeed().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setMaxSpeedLat (const std::string & typeID, double speed) static
Definition at line 176 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setMaxSpeedLat().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setMinGap (const std::string & typeID, double minGap) static
Definition at line 147 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setMinGap().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setMinGapLat (const std::string & typeID, double minGapLat) static
Definition at line 172 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setMinGapLat().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setShapeClass (const std::string & typeID, const std::string & shapeClass) static
Definition at line 135 of file TraCI_VehicleType.cpp.
References getVehicleShapeID(), getVType(), and MSVehicleType::setShape().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setSpeedDeviation (const std::string & typeID, double deviation) static
Definition at line 127 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setSpeedDeviation().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setSpeedFactor (const std::string & typeID, double factor) static
Definition at line 123 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setSpeedFactor().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setTau (const std::string & typeID, double tau) static
Definition at line 163 of file TraCI_VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setHeadwayTime().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setVehicleClass (const std::string & typeID, const std::string & clazz) static
Definition at line 119 of file TraCI_VehicleType.cpp.
References getVehicleClassID(), getVType(), and MSVehicleType::setVClass().
Referenced by TraCIServerAPI_VehicleType::setVariable().
void TraCI_VehicleType::setWidth (const std::string & typeID, double width) static
Definition at line 139 of file TraCI_VehicleType.cpp.
References getVType(), and MSVehicleType::setWidth().
Referenced by TraCIServerAPI_VehicleType::setVariable().
The documentation for this class was generated from the following files:
TraCI_VehicleType.h
TraCI_VehicleType.cpp