SUMO - Simulation of Urban MObility: StdDefs.h File Reference
StdDefs.h File Reference
#include <config.h>
#include <string>
Macros
#define SUMO_MAX_CONNECTIONS 256
the maximum number of connections across an intersection
#define UNUSED_PARAMETER(x) ((void)(x))
Functions
template<typename T >
T ISNAN (T a)
template<typename T >
T MAX2 (T a, T b)
template<typename T >
T MAX3 (T a, T b, T c)
template<typename T >
T MAX4 (T a, T b, T c, T d)
template<typename T >
T MIN2 (T a, T b)
template<typename T >
T MIN3 (T a, T b, T c)
template<typename T >
T MIN4 (T a, T b, T c, T d)
Variables
bool gDebugFlag1
global utility flags for debugging
bool gDebugFlag2
bool gDebugFlag3
bool gDebugFlag4
std::string gDebugSelectedVehicle
int gPrecision
the precision for floating point outputs
int gPrecisionGeo
const double SUMO_const_halfLaneAndOffset = (double)(3.2 / 2. + .1)
const double SUMO_const_halfLaneWidth = (double) 1.6
const double SUMO_const_haltingSpeed = (double) 0.1
the speed threshold at which vehicles are considered as halting
const double SUMO_const_laneOffset = (double) .1
const double SUMO_const_laneWidth = (double) 3.2
const double SUMO_const_laneWidthAndOffset = (double) 3.3
const double SUMO_const_quarterLaneWidth = (double) 0.8
Detailed Description
Author
Daniel Krajzewicz
Laura Bieker
Michael Behrisch
Jakob Erdmann
Date
Fri, 29.04.2005
Version
Id
StdDefs.h 23150 2017-02-27 12:08:30Z behrisch
Definition in file StdDefs.h.
Macro Definition Documentation
#define SUMO_MAX_CONNECTIONS 256
the maximum number of connections across an intersection
Definition at line 41 of file StdDefs.h.
Referenced by NLJunctionControlBuilder::addLogicItem(), NBNode::computeLogic(), and MSRailCrossing::MSRailCrossing().
#define UNUSED_PARAMETER (x) ((void)(x))
Definition at line 38 of file StdDefs.h.
Referenced by MSLeaderDistanceInfo::addLeader(), MSCriticalFollowerDistanceInfo::addLeader(), MSRailCrossing::changeStepAndDuration(), MSOffTrafficLightLogic::changeStepAndDuration(), MSRailSignal::changeStepAndDuration(), SUMOVehicleParserHelper::closeVTypeParsing(), combCallback(), combineCallback(), HelpersHBEFA::compute(), HelpersHBEFA3::compute(), RODFNet::computeRoutesFor(), MSAbstractLaneChangeModel::decideDirection(), GNEReferenceCounter::decRef(), MSDetectorFileOutput::detectorUpdate(), GUIVehicle::drawAction_drawLinkItems(), GUIBaseVehicle::drawAction_drawVehicleBrakeLight(), GUITriggeredRerouter::drawGL(), GUIGlObject::drawGLAdditional(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), FXSingleEventThread::FXSingleEventThread(), FXEX::FXThreadEvent::FXThreadEvent(), NIImporter_OpenDrive::geomFromArc(), NIImporter_OpenDrive::geomFromLine(), NIImporter_OpenDrive::geomFromParamPoly(), NIImporter_OpenDrive::geomFromPoly(), NIImporter_OpenDrive::geomFromSpiral(), RODFDetectorCon::getAggFlowFor(), PollutantsInterface::Helper::getAmitranVehicleClass(), PollutantsInterface::Helper::getClass(), PollutantsInterface::Helper::getClassByName(), PollutantsInterface::Helper::getEuroClass(), MSInternalJunction::getFoeInternalLanes(), MSInternalJunction::getFoeLinks(), MSJunctionLogic::getFoesFor(), PollutantsInterface::Helper::getFuel(), MSJunctionLogic::getIsCont(), PHEMCEP::GetMaxAccel(), GNEEdge::getParameterWindow(), GNEConnection::getParameterWindow(), GNEAdditional::getParameterWindow(), MSJunctionLogic::getResponseFor(), GUIGlObject::getTypeParameterWindow(), PollutantsInterface::Helper::getWeight(), NBHeightMapper::getZ(), GNEReferenceCounter::incRef(), MSLCM_LC2013::inform(), MSCFModel_Wiedemann::interactionGap(), GNEAttributeCarrier::isValid(), GNEDetector::moveAdditionalGeometry(), GNEStoppingPlace::moveAdditionalGeometry(), MSPModel_NonInteracting::MSPModel_NonInteracting(), NBLoadedSUMOTLDef::myCompute(), NIImporter_DlrNavteq::NamesHandler::NamesHandler(), NIImporter_ArcView::NIImporter_ArcView(), NIImporter_Vissim::NIImporter_Vissim(), NIImporter_DlrNavteq::NodesHandler::NodesHandler(), MSMeanData::MeanDataValues::notifyEnter(), MSMoveReminder::notifyEnter(), MSMoveReminder::notifyLeave(), MSMoveReminder::notifyMove(), MSMoveReminder::notifyMoveInternal(), NBNode::edge_by_direction_sorter::operator()(), RGBColor::parseColorReporting(), MSLaneSpeedTrigger::processCommand(), NBTrafficLightDefinition::removeConnection(), GNEJunction::removeFromCrossings(), NBNodeCont::removeIsolatedRoads(), MEVehicle::replaceRoute(), MSMeanData::resetOnly(), MSAbstractLaneChangeModel::saveBlockerLength(), GUIViewTraffic::saveFrame(), GUISUMOAbstractView::saveFrame(), GUIMainWindow::sendBlockingEvent(), MSCFModel::setImperfection(), MSDevice::setParameter(), MSAbstractLaneChangeModel::setParameter(), GUIDialog_EditViewport::setValues(), NBTrafficLightDefinition::shiftTLConnectionLaneIndex(), FXSingleEventThread::signal(), FXEX::FXThreadEvent::signal(), toString(), toString< LaneChangeAction >(), toString< LaneChangeModel >(), toString< LaneSpreadFunction >(), toString< LateralAlignment >(), toString< LinkDirection >(), toString< LinkState >(), toString< Position >(), toString< SUMOVehicleClass >(), toString< SumoXMLAttr >(), toString< SumoXMLEdgeFunc >(), toString< SumoXMLNodeType >(), toString< SumoXMLTag >(), toString< TrafficLightType >(), NIImporter_DlrNavteq::TrafficlightsHandler::TrafficlightsHandler(), MSDevice_SSM::updateEncounter(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition(), MSLCM_DK2008::wantsChange(), MSAbstractLaneChangeModel::wantsChange(), MSAbstractLaneChangeModel::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), and MSInstantInductLoop::writeXMLOutput().
Function Documentation
template<typename T > T ISNAN (T a) inline
Definition at line 105 of file StdDefs.h.
References gDebugFlag1, gDebugFlag2, gDebugFlag3, gDebugFlag4, gDebugSelectedVehicle, gPrecision, and gPrecisionGeo.
Referenced by bezier(), GawronCalculator< R, E, V >::calculateProbabilities(), and MSCFModel::maximumSafeFollowSpeed().
template<typename T > T MAX2 (T a, T b) inline
Definition at line 70 of file StdDefs.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSRouteHandler::addStop(), MSE2Collector::aggregateOutputValues(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::AStarRouter(), IDSupplier::avoid(), NBNode::bezierControlPoints(), NIVisumTL::build(), RODFNet::buildEdgeFlowMap(), GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), GawronCalculator< R, E, V >::calculateProbabilities(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), RGBColor::changedBrightness(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MELoop::checkCar(), MSLaneChanger::checkChange(), NBEdgeCont::checkGrade(), MSVehicle::checkLinkLeader(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSVehicle::collisionStopTime(), NBNodeShapeComputer::compute(), Bresenham::compute(), HelpersHBEFA::compute(), HelpersHBEFA3::compute(), HelpersPHEMlight::compute(), NBNetBuilder::compute(), MSVehicleType::computeChosenSpeedDeviation(), NBNode::computeLanes2Lanes(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeTypeComputer::computeNodeTypes(), NBNetBuilder::computeSingleNode(), NBNodeTypeComputer::computeSingleNodeType(), CState::computeTranshipTime(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSSOTLTrafficLightLogic::countVehicles(), MSCFModel_Krauss::dawdle(), MSCFModel_Daniel1::dawdle(), MSCFModel_SmartSK::dawdle(), MSCFModel_KraussOrig1::dawdle(), MSCFModel_KraussX::dawdleX(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawBestLanes(), GUIPolygon::drawGL(), GUILane::drawGL(), MSCFModel::estimateSpeedAfterDistance(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSVehicle::executeMove(), NBEdge::expandableBy(), MSCFModel_SmartSK::followSpeed(), MSCFModel_PWag2009::followSpeed(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel_Rail::freeSpeed(), MSCFModel::freeSpeed(), MSCFModel::gapExtrapolation(), NBEdgeCont::generateStreetSigns(), NBNode::geometryLike(), GUIMessageWindow::getActiveStringObject(), GUIPerson::getCenteringBoundary(), MEVehicle::getConservativeSpeed(), MSLane::getCriticalLeader(), MSInductLoop::getCurrentOccupancy(), MSEdge::getCurrentTravelTime(), MSVehicle::getDeltaPos(), ROVehicle::getDepartureTime(), MSDevice_Routing::getEffort(), GUIVisualizationSizeSettings::getExaggeration(), MSLane::getFollowersOnConsecutive(), GNEAttributeCarrier::getHigherNumberOfAttributes(), MSBaseVehicle::getImpatience(), MSPModel_Striping::PState::getImpatience(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLeaveTime(), ROEdge::getLengthGeometryFactor(), PositionVector::getMaxGrade(), MESegment::getMaxPenaltySeconds(), MSCFModel::getMinimalArrivalTime(), NIImporter_OpenStreetMap::getNeighboringNodes(), MESegment::getNextInsertionTime(), MSLane::getOppositePos(), PositionVector::getOverlapWith(), MSVehicle::getSafeFollowSpeed(), MSCFModel::getSecureGap(), MSCFModel::getSpeedAfterMaxDecel(), MSLeaderInfo::getSubLanes(), PublicTransportEdge< E, L, N, V >::getTravelTime(), PedestrianEdge< E, L, N, V >::getTravelTime(), ROEdge::getTravelTime(), MEVehicle::getWaitingTime(), MSLink::getZipperSpeed(), GUIDialog_ViewSettings::GUIDialog_ViewSettings(), GUIJunctionWrapper::GUIJunctionWrapper(), MSLane::handleCollisionBetween(), MSVehicle::Influencer::influenceSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSTrafficLightLogic::initMesoTLSPenalties(), NIImporter_OpenStreetMap::insertEdge(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), NBEdgeCont::joinSameNodeConnectingEdges(), MSLCM_SL2015::keepLatGap(), SUMORouteLoaderControl::loadNext(), MSE2Collector::makeMoveNotification(), MAX3(), MAX4(), MSCFModel::maximumSafeFollowSpeed(), MSCFModel::maximumSafeStopSpeedBallistic(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::minNextSpeed(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel::moveHelper(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIImporter_OpenDrive::myStartElement(), MESegment::newArrival(), MSMeanData::MeanDataValues::notifyMove(), GNETLSEditorFrame::onCmdPhaseCreate(), GNETLSEditorFrame::onCmdPhaseDelete(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::straightness_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), MSPModel_Striping::PState::otherStripe(), MSLCM_LC2013::overtakeDistance(), MSCFModel::passingTime(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MESegment::prepareDetectorForWriting(), MSLCM_SL2015::prepareStep(), MSE2Collector::processJams(), MSVehicle::processNextStop(), MSDelayBasedTrafficLightLogic::proposeProlongation(), GUIDialog_ViewSettings::rebuildList(), MSEdge::recalcCache(), MESegment::receive(), MESegment::recomputeJamThreshold(), NIImporter_OpenStreetMap::reconstructLayerElevation(), MSCalibrator::remainingVehicleCapacity(), MESegment::removeCar(), NIImporter_DlrNavteq::TimeRestrictionsHandler::report(), NBEdgeCont::retrievePossiblySplit(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSE2Collector::selectLanes(), MESegment::send(), GNELane::setMultiColor(), GUILane::setMultiColor(), MESegment::setSpeedForQueue(), GUIMainWindow::setWindowSizeAndPos(), NBEdgeCont::splitAt(), MSLaneChangerSublane::startChangeSublane(), MSCFModel_SmartSK::stopSpeed(), MSCFModel_PWag2009::stopSpeed(), MSCFModel_Wiedemann::stopSpeed(), MSPModel_Striping::PState::stripe(), MSDelayBasedTrafficLightLogic::trySwitch(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), AGFreeTime::typeFromHomeNight(), MSVehicle::updateBestLanes(), MSRailCrossing::updateCurrentPhase(), MSLCM_SL2015::updateGaps(), GNEJunction::updateGeometry(), CHBuilder< E, V >::CHInfo::updateLevel(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSVehicle::updateState(), MSVehicleControl::vehicleDeparted(), TraCIServerAPI_Vehicle::vtdMap(), TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition(), MSPModel_Striping::PState::walk(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSVehicle::workOnMoveReminders(), ODMatrix::write(), RODFDetectorCon::writeEmitters(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), NWWriter_OpenDrive::writeGeomSmooth(), NWWriter_SUMO::writeInternalEdges(), MSQueueExport::writeLane(), NWWriter_OpenDrive::writeNetwork(), RODFDetector::writeSingleSpeedTrigger(), MSInductLoop::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
template<typename T > T MAX3 (T a, T b, T c) inline
Definition at line 84 of file StdDefs.h.
References MAX2().
Referenced by MELoop::checkCar(), MSActuatedTrafficLightLogic::duration(), NBRampsComputer::fulfillsRampConstraints(), MSCFModel::getMinimalArrivalTime(), MESegment::getNextInsertionTime(), MSTransportable::Stage_Waiting::proceed(), and MSDelayBasedTrafficLightLogic::trySwitch().
template<typename T > T MAX4 (T a, T b, T c, T d) inline
Definition at line 98 of file StdDefs.h.
References MAX2().
template<typename T > T MIN2 (T a, T b) inline
Definition at line 64 of file StdDefs.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::DriveProcessItem::adaptLeaveSpeed(), MSVehicle::adaptToLeader(), MSVehicle::addStop(), NBEdge::addStraightConnections(), MSLane::basePos(), NBNode::bezierControlPoints(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MSBaseVehicle::calculateArrivalParams(), GawronCalculator< R, E, V >::calculateProbabilities(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), RGBColor::changedBrightness(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MELoop::checkCar(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), MSE2Collector::checkPositioning(), Bresenham::compute(), NBNetBuilder::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), EulerSpiral::compute_es_params(), NBEdge::computeAngle(), NBNode::computeLanes2Lanes(), NBOwnTLDef::computeLogicAndConts(), computeRoutes(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), GLHelper::drawBoxLines(), GUILane::drawDirectionIndicators(), GNELane::drawDirectionIndicators(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUILane::drawMarkings(), GNELane::drawMarkings(), GUIBaseVehicle::drawOnPos(), MSActuatedTrafficLightLogic::duration(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSCFModel::estimateSpeedAfterDistance(), MSVehicle::executeMove(), NBEdge::firstIntersection(), MSCFModel_Kerner::followSpeed(), MSCFModel_Daniel1::followSpeed(), MSCFModel_SmartSK::followSpeed(), MSCFModel_PWag2009::followSpeed(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), MSLane::freeInsertion(), MSCFModel_Wiedemann::fullspeed(), MSActuatedTrafficLightLogic::gapControl(), MSCFModel::gapExtrapolation(), MSInductLoop::getCurrentOccupancy(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSTransportable::Stage_Driving::getEdgePos(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), MSE2Collector::getEstimateQueueLength(), MSBaseVehicle::getImpatience(), MSPModel_Striping::PState::getImpatience(), MSLane::getLeadersOnConsecutive(), TraCI_Lane::getLinks(), GeomHelper::getMinAngleDiff(), ROEdge::getMinimumTravelTime(), NBNodesEdgesSorter::crossing_by_junction_angle_sorter::getMinRank(), NIImporter_OpenStreetMap::getNeighboringNodes(), ROEdge::getNoiseEffort(), CState::getPosition(), GUIBaseVehicle::getSeatPosition(), MSCFModel::getSecureGap(), NBEdge::getShapeEndAngle(), NBEdge::getShapeStartAngle(), MSLeaderInfo::getSublaneBorders(), MSLeaderInfo::getSubLanes(), PublicTransportEdge< E, L, N, V >::getTravelTime(), ROEdge::getTravelTime(), MSLane::getVehicleMaxSpeed(), MSLink::getZipperSpeed(), GUIDialog_ViewSettings::GUIDialog_ViewSettings(), MSLane::handleCollisionBetween(), MSVehicle::Influencer::influenceSpeed(), MSLCM_LC2013::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSPModel_Striping::initWalkingAreaPaths(), MSCFModel::insertionStopSpeed(), MSCFModel::interactionGap(), NBNodeCont::joinJunctions(), MSLCM_SL2015::keepLatGap(), MSLane::lastInsertion(), SUMORouteLoaderControl::loadNext(), MESegment::loadState(), MSE2Collector::makeMoveNotification(), MSCFModel::maximumSafeStopSpeedEuler(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::maxNextSpeed(), MIN3(), MIN4(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel::moveHelper(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBEdge::NBEdge(), MESegment::newArrival(), MSE2Collector::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBContHelper::straightness_sorter::operator()(), operator>>(), MSPModel_Striping::PState::otherStripe(), MSCFModel::passingTime(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_Lane::processGet(), ROLoader::processRoutes(), TraCIServerAPI_Vehicle::processSet(), MSEdge::recalcCache(), MESegment::receive(), NBEdge::reinit(), NIImporter_DlrNavteq::TimeRestrictionsHandler::report(), ROMAAssignments::resetFlows(), MSLane::safeInsertionSpeed(), RONet::saveAndRemoveRoutesUntil(), GUIMainWindow::setWindowSizeAndPos(), NBEdge::shiftPositionAtNode(), NBEdge::shortenGeometryAtNode(), PositionVector::smoothedZFront(), NBEdgeCont::splitAt(), NBEdge::startShapeAt(), MSCFModel_Krauss::stopSpeed(), MSCFModel_Rail::stopSpeed(), MSCFModel_Kerner::stopSpeed(), MSCFModel_Daniel1::stopSpeed(), MSCFModel_SmartSK::stopSpeed(), MSCFModel_PWag2009::stopSpeed(), MSCFModel_KraussOrig1::stopSpeed(), MSCFModel_Wiedemann::stopSpeed(), MSPModel_Striping::PState::stripe(), MSDelayBasedTrafficLightLogic::trySwitch(), AGFreeTime::typeFromHomeNight(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSVehicleControl::vehicleDeparted(), MSCFModel_KraussOrig1::vsafe(), TraCIServerAPI_Vehicle::vtdMap(), TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition(), MSPModel_Striping::PState::walk(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Net::MSLaneMeanDataValues::write(), NWWriter_OpenDrive::writeGeomSmooth(), MSInductLoop::writeXMLOutput(), MSE3Collector::writeXMLOutput(), and MSMeanData::writeXMLOutput().
template<typename T > T MIN3 (T a, T b, T c) inline
Definition at line 77 of file StdDefs.h.
References MIN2().
Referenced by MSCFModel_Kerner::_v(), NBNodeShapeComputer::badIntersection(), MSTrafficLightLogic::init(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel::moveHelper(), and MSPModel_Striping::PState::walk().
template<typename T > T MIN4 (T a, T b, T c, T d) inline
Definition at line 91 of file StdDefs.h.
References MIN2().
Referenced by MSCFModel_Kerner::_v(), and GLHelper::drawBoxLines().
Variable Documentation
bool gDebugFlag1
global utility flags for debugging
Definition at line 33 of file StdDefs.cpp.
Referenced by NBNode::buildCrossings(), NBNode::buildWalkingAreas(), MSLaneChangerSublane::checkChangeSublane(), NBNode::checkCrossing(), NBEdge::getCrossingAngle(), NBNode::getEdgesSortedByAngleAtNodeCenter(), MSLink::getLeaderInfo(), MSLaneChangerSublane::getLeaders(), NBNode::guessCrossings(), ISNAN(), MSPModel_Striping::PState::mergeObstacles(), MSPModel_Striping::moveInDirectionOnLane(), MSVehicle::planMoveInternal(), and NBEdge::setNodeBorder().
bool gDebugFlag2
Definition at line 34 of file StdDefs.cpp.
Referenced by MSLCM_SL2015::_patchSpeed(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MSLCM_SL2015::checkStrategicChange(), MSLCM_SL2015::inform(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), ISNAN(), MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::patchSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateGaps(), and MSLCM_SL2015::wantsChangeSublane().
bool gDebugFlag3
Definition at line 35 of file StdDefs.cpp.
Referenced by ISNAN().
bool gDebugFlag4
Definition at line 36 of file StdDefs.cpp.
Referenced by ISNAN().
std::string gDebugSelectedVehicle
Definition at line 37 of file StdDefs.cpp.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), ISNAN(), GUIGLObjectPopupMenu::onCmdAddSelected(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::updateBestLanes(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
int gPrecision
the precision for floating point outputs
Definition at line 30 of file StdDefs.cpp.
Referenced by SystemFrame::checkOptions(), ISNAN(), MSNet::postSimStepOutput(), MSDevice_Tripinfo::printStatistics(), time2string(), MSLCM_SL2015::wantsChangeSublane(), MSEmissionExport::write(), MSXMLRawOut::write(), and NWWriter_OpenDrive::writeNetwork().
int gPrecisionGeo
Definition at line 31 of file StdDefs.cpp.
Referenced by SystemFrame::checkOptions(), MSVTypeProbe::execute(), ISNAN(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PCPolyContainer::save(), GUISUMOAbstractView::updatePositionInformation(), MSFCDExport::write(), NWWriter_XML::writeEdgesAndConnections(), GeoConvHelper::writeLocation(), NWWriter_XML::writeNodes(), and MSFCDExport::writeTransportable().
const double SUMO_const_halfLaneAndOffset = (double)(3.2 / 2. + .1)
Definition at line 53 of file StdDefs.h.
Referenced by NIXMLEdgesHandler::myEndElement().
const double SUMO_const_halfLaneWidth = (double) 1.6
Definition at line 49 of file StdDefs.h.
const double SUMO_const_haltingSpeed = (double) 0.1
the speed threshold at which vehicles are considered as halting
Definition at line 56 of file StdDefs.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkBlockingVehicles(), GUIApplicationWindow::checkGamingEvents(), MSLCM_SL2015::checkStrategicChange(), MSVehicle::executeMove(), TraCI_Lane::getLastStepHaltingNumber(), MSCFModel::getMinimalArrivalTime(), MSVehicle::getSpaceTillLastStanding(), MSLane::isInsertionSuccess(), MSDevice_Tripinfo::notifyMove(), TraCIServerAPI_Edge::processGet(), MSVehicle::processNextStop(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateGaps(), MSPModel_Striping::PState::walk(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
const double SUMO_const_laneOffset = (double) .1
Definition at line 51 of file StdDefs.h.
Referenced by NBEdge::computeLaneShapes(), GUILane::drawBikeMarkings(), GUILane::drawMarkings(), GNELane::drawMarkings(), NIImporter_SUMO::reconstructEdgeShape(), and NBEdge::shiftPositionAtNode().
const double SUMO_const_laneWidth = (double) 3.2
Definition at line 48 of file StdDefs.h.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), NLHandler::addLane(), NBNode::buildCrossings(), NBNode::buildWalkingAreas(), MSLCM_SL2015::checkStrategicChange(), NBEdge::computeLaneShapes(), NBNodeShapeComputer::computeNodeShapeDefault(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), GUILane::drawArrows(), GUIBusStop::getCenteringBoundary(), NBEdge::getLaneWidth(), MSVehicle::getPosition(), NIImporter_OpenStreetMap::insertEdge(), GUISUMOAbstractView::makeSnapshot(), NBRampsComputer::moveRampRight(), MSParkingArea::MSParkingArea(), NIImporter_SUMO::reconstructEdgeShape(), and TraCIServerAPI_Vehicle::vtdMap().
const double SUMO_const_laneWidthAndOffset = (double) 3.3
Definition at line 52 of file StdDefs.h.
Referenced by NBEdge::getMaxLaneOffset(), and NIXMLEdgesHandler::myEndElement().
const double SUMO_const_quarterLaneWidth = (double) 0.8
Definition at line 50 of file StdDefs.h.