SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq::ConnectedLanesHandler Class Reference
NIImporter_DlrNavteq::ConnectedLanesHandler Class Reference
Imports prohibitions regarding connectivity.
#include <NIImporter_DlrNavteq.h>
Public Member Functions
ConnectedLanesHandler (NBEdgeCont &ne)
Constructor.
bool report (const std::string &result)
Parsing method.
~ConnectedLanesHandler ()
Destructor.
Protected Attributes
NBEdgeCont & myEdgeCont
The edge container to store loaded edges into.
Private Member Functions
ConnectedLanesHandler (const ConnectedLanesHandler &)
Invalidated copy constructor.
ConnectedLanesHandler & operator= (const ConnectedLanesHandler &)
Invalidated assignment operator.
Detailed Description
Imports prohibitions regarding connectivity.
Being a LineHandler, this class retrieves each line from a LineReader and parses these information assuming they contain prohibited manoeuver definitions in DLRNavteq's format.
Definition at line 479 of file NIImporter_DlrNavteq.h.
Constructor & Destructor Documentation
NIImporter_DlrNavteq::ConnectedLanesHandler::ConnectedLanesHandler (NBEdgeCont & ne)
Constructor.
Parameters
[in] file The name of the parsed file
Definition at line 767 of file NIImporter_DlrNavteq.cpp.
NIImporter_DlrNavteq::ConnectedLanesHandler::~ConnectedLanesHandler ()
Destructor.
Definition at line 773 of file NIImporter_DlrNavteq.cpp.
NIImporter_DlrNavteq::ConnectedLanesHandler::ConnectedLanesHandler (const ConnectedLanesHandler &) private
Invalidated copy constructor.
Member Function Documentation
ConnectedLanesHandler& NIImporter_DlrNavteq::ConnectedLanesHandler::operator= (const ConnectedLanesHandler &) private
Invalidated assignment operator.
bool NIImporter_DlrNavteq::ConnectedLanesHandler::report (const std::string & result) virtual
Parsing method.
Implementation of the LineHandler-interface called by a LineReader; interprets the retrieved information and stores the streetNames
Parameters
[in] result The read line
Returns
Whether the parsing shall continue
Exceptions
ProcessError if something fails
See also
LineHandler::report
Implements LineHandler.
Definition at line 777 of file NIImporter_DlrNavteq.cpp.
References TplConvert::_2int(), NBEdge::addLane2LaneConnection(), NBEdgeCont::addPostProcessConnection(), NBEdge::Lane::connectionsDone, NBEdge::declareConnectionsAsLoaded(), StringTokenizer::get(), OptionsCont::getBool(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneStruct(), NBEdge::getNumLanes(), OptionsCont::getOptions(), NBEdge::INIT, NBEdge::L2L_USER, myEdgeCont, StringTokenizer::next(), NBEdgeCont::retrieve(), StringTokenizer::size(), StringTokenizer::TAB, toString(), NBEdge::UNSPECIFIED_CONTPOS, NBEdge::UNSPECIFIED_VISIBILITY_DISTANCE, and WRITE_WARNING.
Field Documentation
NBEdgeCont& NIImporter_DlrNavteq::ConnectedLanesHandler::myEdgeCont protected
The edge container to store loaded edges into.
Definition at line 506 of file NIImporter_DlrNavteq.h.
Referenced by report().
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp