SUMO - Simulation of Urban MObility: GUINet Class Reference
GUINet Class Reference
A MSNet extended by some values for usage within the gui.
#include <GUINet.h>
Public Types
typedef PedestrianRouterDijkstra< MSEdge, MSLane, MSJunction, MSVehicle > MSPedestrianRouterDijkstra
enum SimulationState {
SIMSTATE_LOADING, SIMSTATE_RUNNING, SIMSTATE_END_STEP_REACHED, SIMSTATE_NO_FURTHER_VEHICLES,
SIMSTATE_CONNECTION_CLOSED, SIMSTATE_ERROR_IN_SIM, SIMSTATE_TOO_MANY_TELEPORTS
}
Possible states of a simulation - running or stopped with different reasons.
Public Member Functions
void addRestriction (const std::string &id, const SUMOVehicleClass svc, const double speed)
Adds a restriction for an edge type.
void closeBuilding (const OptionsCont &oc, MSEdgeControl *edges, MSJunctionControl *junctions, SUMORouteLoaderControl *routeLoaders, MSTLLogicControl *tlc, std::vector< SUMOTime > stateDumpTimes, std::vector< std::string > stateDumpFiles, bool hasInternalLinks, bool hasNeighs, bool lefthand, double version)
Closes the network's building process.
void closeSimulation (SUMOTime start)
Closes the simulation (all files, connections, etc.)
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
const Boundary & getBoundary () const
returns the bounder of the network
SUMOTime getCurrentTimeStep () const
Returns the current simulation step.
GUIMEVehicleControl * getGUIMEVehicleControl ()
Returns the vehicle control.
GUIVehicleControl * getGUIVehicleControl ()
Returns the vehicle control.
Position getJunctionPosition (const std::string &name) const
returns the position of a junction
const NamedRTree & getLanesRTree () const
Returns an RTree that contains lane IDs.
MSPedestrianRouterDijkstra & getPedestrianRouter (const MSEdgeVector &prohibited=MSEdgeVector()) const
const std::map< SUMOVehicleClass, double > * getRestrictions (const std::string &id) const
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
SUMOAbstractRouter< MSEdge, SUMOVehicle > & getRouterEffort (const MSEdgeVector &prohibited=MSEdgeVector()) const
SUMOAbstractRouter< MSEdge, SUMOVehicle > & getRouterTT (const MSEdgeVector &prohibited=MSEdgeVector()) const
SUMORTree & getVisualisationSpeedUp ()
Returns the RTree used for visualisation speed-up.
const SUMORTree & getVisualisationSpeedUp () const
Returns the RTree used for visualisation speed-up.
GUINet (MSVehicleControl *vc, MSEventControl *beginOfTimestepEvents, MSEventControl *endOfTimestepEvents, MSEventControl *insertionEvents)
Constructor.
void guiSimulationStep ()
Some further steps needed for gui processing.
bool hasElevation () const
return whether the network contains elevation data
bool hasInternalLinks () const
return whether the network contains internal links
bool hasNeighs () const
return whether the network contains explicit neighbor lanes
bool hasPermissions () const
Returns whether the network has specific vehicle class permissions.
void initGUIStructures ()
Initialises gui wrappers.
bool lefthand () const
return whether the network was built for lefthand traffic
void loadRoutes ()
loads routes for the next few steps
void lock ()
grant exclusive access to the simulation state
bool logSimulationDuration () const
Returns whether duration shall be logged.
void setCurrentTimeStep (const SUMOTime step)
Sets the current simulation step (used by state loading)
void setPermissionsFound ()
Labels the network to contain vehicle class permissions.
SimulationState simulate (SUMOTime start, SUMOTime stop)
Simulates from timestep start to stop.
SimulationState simulationState (SUMOTime stopTime) const
Called after a simulation step, this method returns the current simulation state.
void simulationStep ()
Performs a single simulation step (locking the simulation)
void unlock ()
release exclusive access to the simulation state
bool vehicleExists (const std::string &name) const
returns the information whether the vehicle still exists
double version () const
return the network version
void writeOutput ()
Write netstate, summary and detector output.
~GUINet ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
functions for performance measurements
int getWholeDuration () const
Returns the duration of the last step (sim+visualisation+idle) (in ms)
int getSimDuration () const
Returns the duration of the last step's simulation part (in ms)
double getRTFactor () const
Returns the simulation speed as a factor to real time.
double getUPS () const
Returns the update per seconds rate.
double getMeanRTFactor (int duration) const
Returns the simulation speed as a factor to real time.
double getMeanUPS () const
Returns the update per seconds rate.
int getIdleDuration () const
Returns the duration of the last step's idle part (in ms)
void setSimDuration (int val)
Sets the duration of the last step's simulation part.
void setIdleDuration (int val)
Sets the duration of the last step's idle part.
double getAvgRouteLength () const
double getAvgDuration () const
double getAvgWaitingTime () const
double getAvgTimeLoss () const
double getAvgDepartDelay () const
double getAvgTripSpeed () const
MSTransportableControl & getPersonControl ()
Returns the person control.
MSTransportableControl & getContainerControl ()
Returns the container control.
int getLinkTLID (MSLink *link) const
int getLinkTLIndex (MSLink *link) const
locator-methods
std::vector< GUIGlID > getJunctionIDs (bool includeInternal) const
std::vector< GUIGlID > getTLSIDs () const
Returns the gl-ids of all traffic light logics within the net.
Output during the simulation
void preSimStepOutput () const
Prints the current step number.
void postSimStepOutput () const
Prints the statistics of the step at its end.
Retrieval of references to substructures
MSVehicleControl & getVehicleControl ()
Returns the vehicle control.
bool hasPersons () const
Returns whether persons are simulated.
bool hasContainers () const
Returns whether containers are simulated.
MSEdgeControl & getEdgeControl ()
Returns the edge control.
MSInsertionControl & getInsertionControl ()
Returns the insertion control.
MSDetectorControl & getDetectorControl ()
Returns the detector control.
MSTLLogicControl & getTLSControl ()
Returns the tls logics control.
MSJunctionControl & getJunctionControl ()
Returns the junctions control.
MSEventControl * getBeginOfTimestepEvents ()
Returns the event control for events executed at the begin of a time step.
MSEventControl * getEndOfTimestepEvents ()
Returns the event control for events executed at the end of a time step.
MSEventControl * getInsertionEvents ()
Returns the event control for insertion events.
ShapeContainer & getShapeContainer ()
Returns the shapes container.
MSEdgeWeightsStorage & getWeightsStorage ()
Returns the net's internal edge travel times/efforts container.
Insertion and retrieval of bus stops
bool addBusStop (MSStoppingPlace *busStop)
Adds a bus stop.
MSStoppingPlace * getBusStop (const std::string &id) const
Returns the named bus stop.
std::string getBusStopID (const MSLane *lane, const double pos) const
Returns the bus stop close to the given position.
Insertion and retrieval of container stops
bool addContainerStop (MSStoppingPlace *containerStop)
Adds a container stop.
MSStoppingPlace * getContainerStop (const std::string &id) const
Returns the named container stop.
std::string getContainerStopID (const MSLane *lane, const double pos) const
Returns the container stop close to the given position.
Insertion and retrieval of parking areas
bool addParkingArea (MSParkingArea *parkingArea)
Adds a parking area.
MSParkingArea * getParkingArea (const std::string &id) const
Returns the named parking area.
std::string getParkingAreaID (const MSLane *lane, const double pos) const
Returns the parking area close to the given position.
Insertion and retrieval of charging stations
bool addChargingStation (MSChargingStation *chargingStation)
Adds a chargingg station.
MSChargingStation * getChargingStation (const std::string &id) const
Returns the named charging station.
std::string getChargingStationID (const MSLane *lane, const double pos) const
Returns the charging station close to the given position.
void writeChargingStationOutput () const
write charging station output
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clearAll ()
Clears all dictionaries.
static double getEffort (const MSEdge *const e, const SUMOVehicle *const v, double t)
Returns the effort to pass an edge.
static GUINet * getGUIInstance ()
Returns the pointer to the unique instance of GUINet (singleton).
static MSNet * getInstance ()
Returns the pointer to the unique instance of MSNet (singleton).
static std::string getStateMessage (SimulationState state)
Returns the message to show if a certain state occurs.
static double getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, double t)
Returns the travel time to pass an edge.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Types
typedef std::map< MSLink *, std::string > Links2LogicMap
Definition of a link-to-logic-id map.
typedef std::map< MSTrafficLightLogic *, GUITrafficLightLogicWrapper * > Logics2WrapperMap
Definition of a traffic light-to-wrapper map.
Protected Member Functions
bool checkElevation ()
check all lanes for elevation data
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
Boundary myBoundary
The networks boundary.
NamedObjectCont< MSStoppingPlace * > myBusStopDict
Dictionary of bus stops.
NamedObjectCont< MSChargingStation * > myChargingStationDict
Dictionary of charging Stations.
NamedObjectCont< MSStoppingPlace * > myContainerStopDict
Dictionary of container stops.
std::vector< GUIDetectorWrapper * > myDetectorDict
A detector dictionary.
std::vector< GUIEdge * > myEdgeWrapper
Wrapped MS-edges.
LayeredRTree myGrid
The visualization speed-up.
bool myHasElevation
Whether the network contains elevation data.
bool myHasInternalLinks
Whether the network contains internal links/lanes/edges.
bool myHasNeighs
Whether the network contains explicit neighbor lanes.
bool myHavePermissions
Whether the network contains edges which not all vehicles may pass.
std::vector< GUIJunctionWrapper * > myJunctionWrapper
Wrapped MS-junctions.
std::pair< bool, NamedRTree > myLanesRTree
An RTree structure holding lane IDs.
int myLastIdleDuration
int myLastSimDuration
The step durations (simulation, /*visualisation, */idle)
long myLastVehicleMovementCount
bool myLefthand
Whether the network was built for left-hand traffic.
Links2LogicMap myLinks2Logic
The link-to-logic-id map.
Logics2WrapperMap myLogics2Wrapper
The traffic light-to-wrapper map.
int myMaxTeleports
Maximum number of teleports.
long myOverallSimDuration
long myOverallVehicleCount
NamedObjectCont< MSParkingArea * > myParkingAreaDict
Dictionary of parking areas.
MSPedestrianRouterDijkstra * myPedestrianRouter
std::map< std::string, std::map< SUMOVehicleClass, double > > myRestrictions
The vehicle class specific speed restrictions.
SUMORouteLoaderControl * myRouteLoaders
Route loader for dynamic loading of routes.
DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > > * myRouterEffort
AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > > * myRouterTTAStar
DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > > * myRouterTTDijkstra
bool myRouterTTInitialized
SUMOTime myStep
Current time step.
std::vector< MSTrafficLightLogic * > myTLLogicWrappers
Wrapped TL-Logics.
std::vector< VehicleStateListener * > myVehicleStateListeners
Container for vehicle state listener.
double myVersion
the network version
Substructures
MSVehicleControl * myVehicleControl
Controls vehicle building and deletion;.
MSTransportableControl * myPersonControl
Controls person building and deletion;.
MSTransportableControl * myContainerControl
Controls container building and deletion;.
MSEdgeControl * myEdges
Controls edges, performs vehicle movement;.
MSJunctionControl * myJunctions
Controls junctions, realizes right-of-way rules;.
MSTLLogicControl * myLogics
Controls tls logics, realizes waiting on tls rules;.
MSInsertionControl * myInserter
Controls vehicle insertion;.
MSDetectorControl * myDetectorControl
Controls detectors;.
MSEventControl * myBeginOfTimestepEvents
Controls events executed at the begin of a time step;.
MSEventControl * myEndOfTimestepEvents
Controls events executed at the end of a time step;.
MSEventControl * myInsertionEvents
Controls insertion events;.
ShapeContainer * myShapeContainer
A container for geometrical shapes;.
MSEdgeWeightsStorage * myEdgeWeights
The net's knowledge about edge efforts/travel times;.
data needed for computing performance values
bool myLogExecutionTime
Information whether the simulation duration shall be logged.
bool myLogStepNumber
Information whether the number of the simulation step shall be logged.
long myTraCIStepDuration
The last simulation step duration.
long mySimStepDuration
long mySimBeginMillis
The overall simulation duration.
long long int myVehiclesMoved
The overall number of vehicle movements.
State output variables
std::vector< SUMOTime > myStateDumpTimes
Times at which a state shall be written.
std::vector< std::string > myStateDumpFiles
The names for the state files.
SUMOTime myStateDumpPeriod
The period for writing state.
std::string myStateDumpPrefix
name components for periodic state
std::string myStateDumpSuffix
Static Protected Attributes
static MSNet * myInstance = 0
Unique instance of MSNet.
static const std::string STAGE_EVENTS
string constants for simstep stages
static const std::string STAGE_INSERTIONS
static const std::string STAGE_LANECHANGE
static const std::string STAGE_MOVEMENTS
Private Member Functions
GUIGlID createTLWrapper (MSTrafficLightLogic *tll)
creates a wrapper for the given logic and returns the GlID
void initTLMap ()
Initialises the tl-logic map and wrappers.
Private Attributes
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
Friends
class GUIOSGBuilder
class GUITrafficLightLogicWrapper
Notification about vehicle state changes
void addVehicleStateListener (VehicleStateListener *listener)
Adds a vehicle states listener.
void removeVehicleStateListener (VehicleStateListener *listener)
Removes a vehicle states listener.
void informVehicleStateListener (const SUMOVehicle *const vehicle, VehicleState to)
Informs all added listeners about a vehicle's state change.
enum VehicleState {
VEHICLE_STATE_BUILT, VEHICLE_STATE_DEPARTED, VEHICLE_STATE_STARTING_TELEPORT, VEHICLE_STATE_ENDING_TELEPORT,
VEHICLE_STATE_ARRIVED, VEHICLE_STATE_NEWROUTE, VEHICLE_STATE_STARTING_PARKING, VEHICLE_STATE_ENDING_PARKING,
VEHICLE_STATE_STARTING_STOP, VEHICLE_STATE_ENDING_STOP
}
Definition of a vehicle state.
Detailed Description
A MSNet extended by some values for usage within the gui.
This gui version of the network allows the retrieval of some more information than the normal network version does. Due to this, not only these retrieval, but also some further initialisation methods must have been implemented. Nonethenless, this class has almost the same functions as the MSNet-class.
Some microsimulation items are wrapped in certain classes to allow their drawing and their enumerated access. This enumeration is realised by inserting the wrapped items into vectors and is needed to fasten the network's drawing as only visible items are being drawn.
Definition at line 89 of file GUINet.h.
Member Typedef Documentation
typedef std::map<MSLink*, std::string> GUINet::Links2LogicMap protected
Definition of a link-to-logic-id map.
Definition at line 353 of file GUINet.h.
typedef std::map<MSTrafficLightLogic*, GUITrafficLightLogicWrapper*> GUINet::Logics2WrapperMap protected
Definition of a traffic light-to-wrapper map.
Definition at line 359 of file GUINet.h.
typedef PedestrianRouterDijkstra<MSEdge, MSLane, MSJunction, MSVehicle> MSNet::MSPedestrianRouterDijkstra inherited
Definition at line 117 of file MSNet.h.
Member Enumeration Documentation
enum MSNet::SimulationState inherited
Possible states of a simulation - running or stopped with different reasons.
Enumerator
SIMSTATE_LOADING
The simulation is loading.
SIMSTATE_RUNNING
The simulation is running.
SIMSTATE_END_STEP_REACHED
The final simulation step has been performed.
SIMSTATE_NO_FURTHER_VEHICLES
The simulation does not contain further vehicles.
SIMSTATE_CONNECTION_CLOSED
The connection to a client was closed by the client.
SIMSTATE_ERROR_IN_SIM
An error occured during the simulation step.
SIMSTATE_TOO_MANY_TELEPORTS
The simulation had too many teleports.
Definition at line 99 of file MSNet.h.
enum MSNet::VehicleState inherited
Definition of a vehicle state.
Enumerator
VEHICLE_STATE_BUILT
The vehicle was built, but has not yet departed.
VEHICLE_STATE_DEPARTED
The vehicle has departed (was inserted into the network)
VEHICLE_STATE_STARTING_TELEPORT
The vehicle started to teleport.
VEHICLE_STATE_ENDING_TELEPORT
The vehicle ended being teleported.
VEHICLE_STATE_ARRIVED
The vehicle arrived at his destination (is deleted)
VEHICLE_STATE_NEWROUTE
The vehicle got a new route.
VEHICLE_STATE_STARTING_PARKING
The vehicles starts to park.
VEHICLE_STATE_ENDING_PARKING
The vehicle ends to park.
VEHICLE_STATE_STARTING_STOP
The vehicles starts to stop.
VEHICLE_STATE_ENDING_STOP
The vehicle ends to stop.
Definition at line 576 of file MSNet.h.
Constructor & Destructor Documentation
GUINet::GUINet (MSVehicleControl * vc, MSEventControl * beginOfTimestepEvents, MSEventControl * endOfTimestepEvents, MSEventControl * insertionEvents)
Constructor.
Parameters
[in] vc The vehicle control to use
[in] beginOfTimestepEvents The event control to use for simulation step begin events
[in] endOfTimestepEvents The event control to use for simulation step end events
[in] insertionEvents The event control to use for insertion events
Exceptions
ProcessError If a network was already constructed
Definition at line 81 of file GUINet.cpp.
References GUIGlObjectStorage::gIDStorage, and GUIGlObjectStorage::setNetObject().
GUINet::~GUINet ()
Destructor.
Definition at line 91 of file GUINet.cpp.
References GUIGlObject_AbstractAdd::clearDictionary(), MFXMutex::locked(), myDetectorDict, myJunctionWrapper, myLock, myLogics2Wrapper, and MFXMutex::unlock().
Member Function Documentation
bool MSNet::addBusStop (MSStoppingPlace * busStop) inherited
Adds a bus stop.
If another bus stop with the same id exists, false is returned. Otherwise, the bus stop is added to the internal bus stop container "myBusStopDict".
This control gets responsible for deletion of the added bus stop.
Parameters
[in] busStop The bus stop to add
Returns
Whether the bus stop could be added
Definition at line 821 of file MSNet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and MSNet::myBusStopDict.
Referenced by GUITriggerBuilder::buildStoppingPlace(), NLTriggerBuilder::buildStoppingPlace(), and MSNet::getShapeContainer().
bool MSNet::addChargingStation (MSChargingStation * chargingStation) inherited
Adds a chargingg station.
If another charging station with the same id exists, false is returned. Otherwise, the charging station is added to the internal bus stop container "myChargingStationDict".
This control gets responsible for deletion of the added charging station.
Parameters
[in] chargingStation The charging station add
Returns
Whether the charging station could be added
Definition at line 891 of file MSNet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and MSNet::myChargingStationDict.
Referenced by GUITriggerBuilder::buildChargingStation(), NLTriggerBuilder::buildChargingStation(), and MSNet::getShapeContainer().
bool MSNet::addContainerStop (MSStoppingPlace * containerStop) inherited
Adds a container stop.
If another container stop with the same id exists, false is returned. Otherwise, the container stop is added to the internal container stop container "myContainerStopDict".
This control gets responsible for deletion of the added container stop.
Parameters
[in] containerStop The container stop to add
Returns
Whether the container stop could be added
Definition at line 846 of file MSNet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and MSNet::myContainerStopDict.
Referenced by GUITriggerBuilder::buildStoppingPlace(), NLTriggerBuilder::buildStoppingPlace(), and MSNet::getShapeContainer().
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 256 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
bool MSNet::addParkingArea (MSParkingArea * parkingArea) inherited
Adds a parking area.
If another parking area with the same id exists, false is returned. Otherwise, the parking area is added to the internal parking area container "myParkingAreaDict".
This control gets responsible for deletion of the added parking area.
Parameters
[in] parkingArea The parking area to add
Returns
Whether the parking area could be added
Definition at line 869 of file MSNet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and MSNet::myParkingAreaDict.
Referenced by GUITriggerBuilder::beginParkingArea(), NLTriggerBuilder::beginParkingArea(), and MSNet::getShapeContainer().
void MSNet::addRestriction (const std::string & id, const SUMOVehicleClass svc, const double speed) inherited
Adds a restriction for an edge type.
Parameters
[in] id The id of the type
[in] svc The vehicle class the restriction refers to
[in] speed The restricted speed
Definition at line 288 of file MSNet.cpp.
References MSNet::myRestrictions.
Referenced by NLHandler::myStartElement(), and MSNet::setPermissionsFound().
void MSNet::addVehicleStateListener (VehicleStateListener * listener) inherited
Adds a vehicle states listener.
Parameters
[in] listener The listener to add
Definition at line 794 of file MSNet.cpp.
References MSNet::myVehicleStateListeners.
Referenced by MSDevice_Vehroutes::init(), TraCIServer::TraCIServer(), and MSNet::VehicleStateListener::~VehicleStateListener().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 185 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 194 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 175 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 235 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 204 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 247 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 217 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GUIEdge::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 226 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
bool MSNet::checkElevation () protected inherited
check all lanes for elevation data
Definition at line 983 of file MSNet.cpp.
References MSEdgeControl::getEdges(), and MSNet::myEdges.
Referenced by MSNet::closeBuilding(), and MSNet::version().
void MSNet::clearAll () static inherited
Clears all dictionaries.
Todo:
Try to move all this to the destructor
Definition at line 593 of file MSNet.cpp.
References MSTrigger::cleanup(), MSPModel::cleanup(), MSCModel_NonInteracting::cleanup(), MSCalibrator::cleanup(), MSDevice_BTsender::cleanup(), MSDevice_Routing::cleanup(), TraCIServer::cleanup(), MSDevice_SSM::cleanup(), MSRoute::clear(), MSLane::clear(), MSEdge::clear(), TraCIServer::getInstance(), and MSVehicleTransfer::getInstance().
Referenced by GUILoadThread::run(), MSNet::setPermissionsFound(), and MSNet::~MSNet().
void MSNet::closeBuilding (const OptionsCont & oc, MSEdgeControl * edges, MSJunctionControl * junctions, SUMORouteLoaderControl * routeLoaders, MSTLLogicControl * tlc, std::vector< SUMOTime > stateDumpTimes, std::vector< std::string > stateDumpFiles, bool hasInternalLinks, bool hasNeighs, bool lefthand, double version) inherited
Closes the network's building process.
Assigns the structures built while loading to this network.
Parameters
[in] oc The options to use
[in] edges The control of edges which belong to this network
[in] junctions The control of junctions which belong to this network
[in] routeLoaders The route loaders used
[in] tlc The control of traffic lights which belong to this network
[in] stateDumpTimes List of time steps at which state shall be written
[in] stateDumpFiles Filenames for states
[in] hasInternalLinks Whether the network actually contains internal links
[in] lefthand Whether the network was built for left-hand traffic
[in] version The network version
Todo:
Try to move all this to the constructor?
Definition at line 211 of file MSNet.cpp.
References MSNet::checkElevation(), SysUtils::getCurrentMillis(), OptionsCont::getString(), MSNet::hasInternalLinks(), MSNet::hasNeighs(), MSNet::lefthand(), MSNet::myEdges, MSNet::myHasElevation, MSNet::myHasInternalLinks, MSNet::myHasNeighs, MSNet::myJunctions, MSNet::myLefthand, MSNet::myLogExecutionTime, MSNet::myLogics, MSNet::myRouteLoaders, MSNet::mySimBeginMillis, MSNet::myStateDumpFiles, MSNet::myStateDumpPeriod, MSNet::myStateDumpPrefix, MSNet::myStateDumpSuffix, MSNet::myStateDumpTimes, MSNet::myVersion, MSJunctionControl::postloadInitContainer(), string2time(), and MSNet::version().
Referenced by NLBuilder::buildNet().
void MSNet::closeSimulation (SUMOTime start) inherited
Closes the simulation (all files, connections, etc.)
Writes also performance output
Parameters
[in] start The step the simulation was started with
Todo:
What exceptions may occure?
Definition at line 358 of file MSNet.cpp.
References MSDetectorControl::close(), MSDevice_Tripinfo::generateOutputForUnfinished(), MSDevice_Vehroutes::generateOutputForUnfinished(), MSVehicleControl::getCollisionCount(), SysUtils::getCurrentMillis(), MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getEmergencyStops(), MSTransportableControl::getJammedNumber(), MSTransportableControl::getLoadedNumber(), MSVehicleControl::getLoadedVehicleNo(), OptionsCont::getOptions(), MSTransportableControl::getRunningNumber(), MSVehicleControl::getRunningVehicleNo(), MSVehicleControl::getTeleportCount(), MSVehicleControl::getTeleportsJam(), MSVehicleControl::getTeleportsWrongLane(), MSVehicleControl::getTeleportsYield(), MSInsertionControl::getWaitingVehicleNo(), joinToString(), MSNet::myDetectorControl, MSNet::myInserter, MSNet::myLogExecutionTime, MSNet::myPersonControl, MSNet::mySimBeginMillis, MSNet::myStep, MSNet::myVehicleControl, MSNet::myVehiclesMoved, MSDevice_Tripinfo::printStatistics(), STEPS2TIME, toString(), WRITE_MESSAGE, and MSNet::writeChargingStationOutput().
Referenced by GUIRunThread::deleteSim(), MSNet::setPermissionsFound(), and MSNet::simulate().
GUIGlID GUINet::createTLWrapper (MSTrafficLightLogic * tll) private
creates a wrapper for the given logic and returns the GlID
Definition at line 151 of file GUINet.cpp.
References SUMORTree::addAdditionalGLObject(), GUIGlObject::getGlID(), Named::getID(), MSTrafficLightLogic::getLinks(), GUITrafficLightLogicWrapper, myGrid, myLinks2Logic, MSNet::myLogics, and myLogics2Wrapper.
Referenced by getVisualisationSpeedUp(), initTLMap(), and GUITrafficLightLogicWrapper::switchTLSLogic().
void GUINet::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 481 of file GUINet.cpp.
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 154 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 284 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), GNEEdge::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
double GUINet::getAvgDepartDelay () const inline
Definition at line 222 of file GUINet.h.
References MSDevice_Tripinfo::getAvgDepartDelay().
Referenced by getParameterWindow().
double GUINet::getAvgDuration () const inline
Definition at line 213 of file GUINet.h.
References MSDevice_Tripinfo::getAvgDuration().
Referenced by getParameterWindow().
double GUINet::getAvgRouteLength () const inline
Definition at line 210 of file GUINet.h.
References MSDevice_Tripinfo::getAvgRouteLength().
Referenced by getParameterWindow().
double GUINet::getAvgTimeLoss () const inline
Definition at line 219 of file GUINet.h.
References MSDevice_Tripinfo::getAvgTimeLoss().
Referenced by getParameterWindow().
double GUINet::getAvgTripSpeed () const inline
Definition at line 225 of file GUINet.h.
References MSDevice_Tripinfo::getAvgDuration(), MSDevice_Tripinfo::getAvgRouteLength(), getContainerControl(), getJunctionIDs(), getLinkTLID(), getLinkTLIndex(), getPersonControl(), getTLSIDs(), and initGUIStructures().
Referenced by getParameterWindow().
double GUINet::getAvgWaitingTime () const inline
Definition at line 216 of file GUINet.h.
References MSDevice_Tripinfo::getAvgWaitingTime().
Referenced by getParameterWindow().
MSEventControl* MSNet::getBeginOfTimestepEvents () inline inherited
Returns the event control for events executed at the begin of a time step.
Returns
The control responsible for events that are executed at the begin of a time step
See also
MSEventControl
myBeginOfTimestepEvents
Definition at line 403 of file MSNet.h.
References MSNet::myBeginOfTimestepEvents.
Referenced by MSPModel_NonInteracting::add(), MSCModel_NonInteracting::add(), NLTriggerBuilder::buildVaporizer(), MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTLLogicControl::closeWAUT(), MSLaneSpeedTrigger::init(), MSPModel_Striping::MSPModel_Striping(), MSTrafficLightLogic::MSTrafficLightLogic(), MSTriggeredRerouter::myEndElement(), MSDevice_Routing::notifyEnter(), and MSTriggeredRerouter::setPermissions().
const Boundary & GUINet::getBoundary () const
returns the bounder of the network
Definition at line 114 of file GUINet.cpp.
References myBoundary.
Referenced by getCenteringBoundary().
MSStoppingPlace * MSNet::getBusStop (const std::string & id) const inherited
Returns the named bus stop.
Parameters
[in] id The id of the bus stop to return.
Returns
The named bus stop, or 0 if no such stop exists
Definition at line 827 of file MSNet.cpp.
References NamedObjectCont< T >::get(), and MSNet::myBusStopDict.
Referenced by MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getShapeContainer(), MSRouteHandler::myStartElement(), MSRouteHandler::parseWalkPositions(), TraCIServerAPI_Simulation::processGet(), and TraCIServerAPI_Person::processSet().
std::string MSNet::getBusStopID (const MSLane * lane, const double pos) const inherited
Returns the bus stop close to the given position.
Parameters
[in] lane the lane of the bus stop to return.
[in] pos the position of the bus stop to return.
Returns
The bus stop id on the location, or "" if no such stop exists
Definition at line 833 of file MSNet.cpp.
References MSStoppingPlace::getEndLanePosition(), Named::getID(), MSStoppingPlace::getLane(), NamedObjectCont< T >::getMyMap(), MSNet::myBusStopDict, and POSITION_EPS.
Referenced by MSNet::getShapeContainer().
Boundary GUINet::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 485 of file GUINet.cpp.
References getBoundary().
MSChargingStation * MSNet::getChargingStation (const std::string & id) const inherited
Returns the named charging station.
Parameters
[in] id The id of the charging station to return.
Returns
The named charging station, or 0 if no such stop exists
Definition at line 897 of file MSNet.cpp.
References NamedObjectCont< T >::get(), and MSNet::myChargingStationDict.
Referenced by MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getShapeContainer(), and MSDevice_Battery::notifyMove().
std::string MSNet::getChargingStationID (const MSLane * lane, const double pos) const inherited
Returns the charging station close to the given position.
Parameters
[in] lane the lane of the charging station to return.
[in] pos the position of the bus stop to return.
Returns
The charging station id on the location, or "" if no such stop exists
Definition at line 903 of file MSNet.cpp.
References MSStoppingPlace::getBeginLanePosition(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSStoppingPlace::getLane(), NamedObjectCont< T >::getMyMap(), and MSNet::myChargingStationDict.
Referenced by MSNet::getShapeContainer(), and MSDevice_Battery::notifyMove().
MSTransportableControl & GUINet::getContainerControl () virtual
Returns the container control.
If the container control does not exist, yet, it is created.
Returns
The container control
See also
MSContainerControl
myContainerControl
Reimplemented from MSNet.
Definition at line 129 of file GUINet.cpp.
References MSNet::myContainerControl.
Referenced by getAvgTripSpeed(), and GUIApplicationWindow::handleEvent_SimulationStep().
MSStoppingPlace * MSNet::getContainerStop (const std::string & id) const inherited
Returns the named container stop.
Parameters
[in] id The id of the container stop to return.
Returns
The named container stop, or 0 if no such stop exists
Definition at line 851 of file MSNet.cpp.
References NamedObjectCont< T >::get(), and MSNet::myContainerStopDict.
Referenced by MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getShapeContainer(), and MSRouteHandler::myStartElement().
std::string MSNet::getContainerStopID (const MSLane * lane, const double pos) const inherited
Returns the container stop close to the given position.
Parameters
[in] lane the lane of the container stop to return.
[in] pos the position of the container stop to return.
Returns
The container stop id on the location, or "" if no such stop exists
Definition at line 856 of file MSNet.cpp.
References MSStoppingPlace::getEndLanePosition(), Named::getID(), MSStoppingPlace::getLane(), NamedObjectCont< T >::getMyMap(), MSNet::myContainerStopDict, and POSITION_EPS.
Referenced by MSNet::getShapeContainer().
SUMOTime MSNet::getCurrentTimeStep () const inline inherited
Returns the current simulation step.
Returns
the current simulation step
Definition at line 257 of file MSNet.h.
References MSNet::myStep.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), GUIEdge::addRerouter(), MSDevice_Vehroutes::addRoute(), MSTLLogicControl::addWAUTJunction(), MSTransportableControl::boardAnyWaiting(), NLDetectorBuilder::buildE2Detector(), MSDevice_Routing::buildVehicleDevices(), NLJunctionControlBuilder::closeTrafficLightLogic(), MSTLLogicControl::closeWAUT(), TraCIServerAPI_Simulation::commandDistanceRequest(), MSDevice_Tripinfo::computeLengthAndDuration(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSActuatedTrafficLightLogic::duration(), Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), MSVehicle::executeMove(), MSActuatedTrafficLightLogic::gapControl(), MSTransportable::getAngle(), MSLane::getCriticalLeader(), MSInductLoop::getCurrentOccupancy(), MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), GUIApplicationWindow::getCurrentSimTime(), MSLaneSpeedTrigger::getCurrentSpeed(), GUIViewTraffic::getCurrentTimeStep(), MSEventControl::getCurrentTimeStep(), MSTransportable::getEdgePos(), MSLane::getFirstVehicleInformation(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), TraCI_Lane::getLinks(), MESegment::getMeanSpeed(), MSInsertionControl::getPendingEmits(), MSTransportable::getPosition(), MSVehicle::getPosition(), MSTransportable::getWaitingSeconds(), MSLink::getZipperSpeed(), GUIApplicationWindow::handleEvent_SimulationStep(), MSSwarmTrafficLightLogic::init(), MSLaneSpeedTrigger::init(), TraCIServer::initialiseSubscription(), MSTLLogicControl::initWautSwitch(), MSLane::isInsertionSuccess(), MSVehicle::Influencer::isVTDControlled(), MSTransportableControl::loadAnyWaiting(), GUIRunThread::makeStep(), MSPModel_Striping::MSPModel_Striping(), MSDevice_Vehroutes::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Transportable::notifyMove(), GUIApplicationWindow::onCmdTimeToggle(), MSBaseVehicle::onDepart(), TraCIServer::postProcessSimulationStep2(), MESegment::prepareDetectorForWriting(), MSVehicle::processNextStop(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Person::processSet(), MSTriggeredRerouter::rerouteParkingZone(), MSSOTLTrafficLightLogic::resetCTS(), MSTrafficLightLogic::resetLinkStates(), GUIRunThread::run(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSPhasedTrafficLightLogic::setStep(), MSSOTLTrafficLightLogic::setupCTS(), MSNet::simulate(), MSSimpleTrafficLightLogic::trySwitch(), MSDelayBasedTrafficLightLogic::trySwitch(), MSActuatedTrafficLightLogic::trySwitch(), MSSOTLTrafficLightLogic::trySwitch(), MSSOTLTrafficLightLogic::updateCTS(), MSRailCrossing::updateCurrentPhase(), MSSwarmTrafficLightLogic::updateSensitivities(), and MSVehicle::wasRemoteControlled().
MSDetectorControl& MSNet::getDetectorControl () inline inherited
Returns the detector control.
Returns
The detector control
See also
MSDetectorControl
myDetectorControl
Definition at line 373 of file MSNet.h.
References MSNet::myDetectorControl.
Referenced by MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NLDetectorBuilder::buildE2Detector(), NLDetectorBuilder::buildInductLoop(), NLDetectorBuilder::buildInstantInductLoop(), NLDetectorBuilder::buildRouteProbe(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NLDetectorBuilder::createEdgeLaneMeanData(), NLDetectorBuilder::endE3Detector(), TraCI_MultiEntryExit::getDetector(), TraCI_InductionLoop::getDetector(), TraCI_LaneArea::getDetector(), TraCI_MultiEntryExit::getIDCount(), TraCI_LaneArea::getIDCount(), TraCI_InductionLoop::getIDCount(), TraCI_MultiEntryExit::getIDList(), TraCI_LaneArea::getIDList(), TraCI_InductionLoop::getIDList(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), and NLTriggerBuilder::parseAndBuildCalibrator().
MSEdgeControl& MSNet::getEdgeControl () inline inherited
Returns the edge control.
Returns
The edge control
See also
MSEdgeControl
myEdges
Definition at line 353 of file MSNet.h.
References MSNet::myEdges.
Referenced by MSDevice_Routing::adaptEdgeEfforts(), NLBuilder::build(), MSDevice_Routing::buildVehicleDevices(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), TraCI::convertCartesianToRoadMap(), MSLane::incorporateVehicle(), MSMeanData::init(), MSFCDExport::write(), MSQueueExport::writeEdge(), and MSFullExport::writeEdge().
double MSNet::getEffort (const MSEdge *const e, const SUMOVehicle *const v, double t) static inherited
Returns the effort to pass an edge.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the effort shall be returned [s]
Returns
The effort (abstract) for an edge
See also
DijkstraRouterTT_ByProxi
Definition at line 127 of file MSNet.cpp.
References MSNet::getInstance(), MSVehicle::getWeightsStorage(), MSNet::getWeightsStorage(), and MSEdgeWeightsStorage::retrieveExistingEffort().
Referenced by MSNet::getRouterEffort(), and MSNet::VehicleStateListener::~VehicleStateListener().
MSEventControl* MSNet::getEndOfTimestepEvents () inline inherited
Returns the event control for events executed at the end of a time step.
Returns
The control responsible for events that are executed at the end of a time step
See also
MSEventControl
myEndOfTimestepEvents
Definition at line 413 of file MSNet.h.
References MSNet::myEndOfTimestepEvents.
Referenced by MSDevice_BTreceiver::BTreceiverUpdate::BTreceiverUpdate(), MSDevice_Routing::buildVehicleDevices(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), MSCalibrator::init(), and MSVTypeProbe::MSVTypeProbe().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 121 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEInternalLane::drawGL(), GNEJunction::drawGL(), GNECrossing::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdRevertRestriction(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
GUINet * GUINet::getGUIInstance () static
Returns the pointer to the unique instance of GUINet (singleton).
Returns
Pointer to the unique GUINet-instance
Exceptions
ProcessError If a network was not yet constructed
Definition at line 491 of file GUINet.cpp.
References MSNet::getInstance().
Referenced by GUIEdge::addRerouter(), GUIViewTraffic::doPaintGL(), GUIEdge::drawMesoVehicles(), getVisualisationSpeedUp(), GUIApplicationWindow::onCmdShowStats(), and GUITrafficLightLogicWrapper::switchTLSLogic().
GUIMEVehicleControl * GUINet::getGUIMEVehicleControl ()
Returns the vehicle control.
Returns
The vehicle control
See also
MSVehicleControl
myVehicleControl
Definition at line 518 of file GUINet.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, myEdgeWrapper, myJunctionWrapper, and MSNet::myVehicleControl.
Referenced by GUIEdge::drawMesoVehicles(), and getVisualisationSpeedUp().
GUIVehicleControl * GUINet::getGUIVehicleControl ()
Returns the vehicle control.
Returns
The vehicle control
See also
MSVehicleControl
myVehicleControl
Definition at line 501 of file GUINet.cpp.
References MSNet::myVehicleControl.
Referenced by getVisualisationSpeedUp().
int GUINet::getIdleDuration () const
Returns the duration of the last step's idle part (in ms)
Definition at line 372 of file GUINet.cpp.
References myLastIdleDuration.
Referenced by getParameterWindow().
MSInsertionControl& MSNet::getInsertionControl () inline inherited
Returns the insertion control.
Returns
The insertion control
See also
MSInsertionControl
myInserter
Definition at line 363 of file MSNet.h.
References MSNet::myInserter.
Referenced by MSLane::checkFailure(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), GUIEdge::getColorValue(), GUILane::getColorValue(), getParameterWindow(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GUIApplicationWindow::handleEvent_SimulationStep(), MSLane::isInsertionSuccess(), MSVehicleTransfer::loadState(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), and MSBaseVehicle::reroute().
MSEventControl* MSNet::getInsertionEvents () inline inherited
Returns the event control for insertion events.
Returns
The control responsible for insertion events
See also
MSEventControl
myInsertionEvents
Definition at line 423 of file MSNet.h.
References MSNet::myInsertionEvents.
Referenced by MSDevice_Routing::MSDevice_Routing().
MSNet * MSNet::getInstance (void) static inherited
Returns the pointer to the unique instance of MSNet (singleton).
Returns
Pointer to the unique MSNet-instance
Exceptions
ProcessError If a network was not yet constructed
Definition at line 158 of file MSNet.cpp.
References MSNet::myInstance.
Referenced by MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSDevice_Routing::adaptEdgeEfforts(), TraCI_Polygon::add(), TraCI_POI::add(), MSVehicleTransfer::add(), MSChargingStation::addChargeValueForOutput(), MSTrafficLightLogic::addLink(), MSTLLogicControl::TLSLogicVariants::addLogic(), GUIEdge::addRerouter(), MSDevice_Vehroutes::addRoute(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSTLLogicControl::addWAUTJunction(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportableControl::boardAnyWaiting(), MSDevice_BTreceiver::BTreceiverUpdate::BTreceiverUpdate(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), MSVehicleType::buildSingularType(), NLTriggerBuilder::buildVaporizer(), MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSDevice_Routing::buildVehicleDevices(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MELoop::changeSegment(), MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSTLLogicControl::closeWAUT(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), TraCIServerAPI_Simulation::commandDistanceRequest(), MSDevice_Tripinfo::computeLengthAndDuration(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), TraCI::convertCartesianToRoadMap(), NLDetectorBuilder::createEdgeLaneMeanData(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisions(), MSInsertionControl::determineCandidates(), TraCIServer::dispatchCommand(), GUITrafficLightLogicWrapper::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawMarkings(), GUILane::drawTLSLinkNo(), MSActuatedTrafficLightLogic::duration(), MSDevice::equippedByDefaultAssignmentOptions(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSActuatedTrafficLightLogic::gapControl(), MSTransportable::getAngle(), MSVehicle::getBackPositionOnLane(), GUIEdge::getColorValue(), GUILane::getColorValue(), MSLane::getCriticalLeader(), MSInductLoop::getCurrentLength(), MSInductLoop::getCurrentOccupancy(), MSInductLoop::getCurrentPassedNumber(), MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), MSLaneSpeedTrigger::getCurrentSpeed(), MSInductLoop::getCurrentSpeed(), GUIViewTraffic::getCurrentTimeStep(), MSEventControl::getCurrentTimeStep(), MSInductLoop::getCurrentVehicleIDs(), TraCI_MultiEntryExit::getDetector(), TraCI_InductionLoop::getDetector(), TraCI_LaneArea::getDetector(), MSTransportable::getEdgePos(), MSNet::getEffort(), MSLane::getFirstVehicleInformation(), getGUIInstance(), TraCI_LaneArea::getIDCount(), TraCI_MultiEntryExit::getIDCount(), TraCI_InductionLoop::getIDCount(), TraCI_VehicleType::getIDList(), TraCI_Polygon::getIDList(), TraCI_LaneArea::getIDList(), TraCI_MultiEntryExit::getIDList(), TraCI_InductionLoop::getIDList(), TraCI_POI::getIDList(), TraCI_Junction::getIDList(), TraCI_Vehicle::getIDList(), TraCI_Junction::getJunction(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), TraCI_Lane::getLinks(), GUILane::getLoadedEdgeWeight(), MSLane::getMaximumBrakeDist(), MESegment::getMeanSpeed(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), MSPModel::getModel(), MSCModel_NonInteracting::getModel(), MSPModel_Striping::getNextLane(), MSInsertionControl::getPendingEmits(), MSTLLogicControl::getPhaseDef(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), TraCI_POI::getPoI(), TraCIServerAPI_POI::getPoI(), TraCI_Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_Vehicle::getPosition(), TraCIServerAPI_Person::getPosition(), MSTransportable::getPosition(), MSVehicle::getPosition(), MSVTKExport::getPositions(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), MSVTKExport::getSpeed(), GUILane::getStoredEdgeTravelTime(), MSEdge::getSuccessors(), MSNet::getTravelTime(), MSEdge::getTravelTimeStatic(), TraCIServerAPI_InductionLoop::getTree(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_POI::getTree(), TraCIServerAPI_Polygon::getTree(), TraCI_Vehicle::getVehicle(), TraCI_InductionLoop::getVehicleData(), TraCI_VehicleType::getVType(), MSTransportable::getWaitingSeconds(), MSLink::getZipperSpeed(), GUIBusStop::GUIBusStop(), MSLane::handleCollisionBetween(), MSLane::incorporateVehicle(), MSVehicle::influenceChangeDecision(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSDevice_Vehroutes::init(), MSRailCrossing::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSLaneSpeedTrigger::init(), MSCalibrator::init(), MSMeanData::init(), TraCIServer::initialiseSubscription(), MSLane::initRestrictions(), MSTLLogicControl::initWautSwitch(), MSEdge::insertVehicle(), MSLane::isInsertionSuccess(), MSSOTLTrafficLightLogic::isThresholdPassed(), MSVehicle::Influencer::isVTDControlled(), MSVehicle::leaveLane(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSTransportableControl::loadAnyWaiting(), MSVehicleTransfer::loadState(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), MSDevice_Routing::MSDevice_Routing(), MSTrafficLightLogic::MSTrafficLightLogic(), MSVTypeProbe::MSVTypeProbe(), GUITriggeredRerouter::myEndElement(), MSRouteHandler::myEndElement(), MSTriggeredRerouter::myEndElement(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), MSTriggeredRerouter::myStartElement(), MSDevice_Transportable::notifyEnter(), MSDevice_Vehroutes::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Transportable::notifyMove(), MSDevice_Battery::notifyMove(), MSE3Collector::MSE3EntryReminder::notifyMove(), GUISUMOViewParent::onCmdLocate(), MSBaseVehicle::onDepart(), GUIViewTraffic::onGamingClick(), TraCI_Vehicle::onInit(), MSRouteHandler::openVehicleTypeDistribution(), MSRouteHandler::parseWalkPositions(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMoveInternal(), TraCIServer::postProcessSimulationStep2(), TraCIServer::postProcessVTD(), MESegment::prepareDetectorForWriting(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSPerson::MSPersonStage_Walking::proceed(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Simulation::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_Person::processSet(), MSPModel_Striping::PState::PState(), MESegment::receive(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), TraCI_Polygon::remove(), TraCI_POI::remove(), MSCalibrator::removePending(), MSTransportable::removeStage(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSDevice_Routing::reroute(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingZone(), MSSOTLTrafficLightLogic::resetCTS(), MSTrafficLightLogic::resetLinkStates(), MSVehicle::resumeFromStopping(), MSContainer::routeOutput(), MSPerson::routeOutput(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSStateHandler::saveState(), MSVehicleControl::scheduleVehicleRemoval(), MSBaseVehicle::setDeviceParameter(), GUIBaseVehicle::setFunctionalColor(), MSLaneSpeedTrigger::setOverriding(), MSLaneSpeedTrigger::setOverridingValue(), MSTriggeredRerouter::setPermissions(), TraCI_Polygon::setShape(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSPhasedTrafficLightLogic::setStep(), MSSOTLTrafficLightLogic::setupCTS(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSStopOut::stopEnded(), MSStopOut::stopStarted(), MSLane::succLinkSec(), MSTLLogicControl::TLSLogicVariants::switchTo(), MELoop::teleportVehicle(), TraCIServer::TraCIServer(), METriggeredCalibrator::tryEmit(), MSInsertionControl::tryInsert(), MSSimpleTrafficLightLogic::trySwitch(), MSDelayBasedTrafficLightLogic::trySwitch(), MSRailCrossing::trySwitch(), MSActuatedTrafficLightLogic::trySwitch(), MSRailSignal::trySwitch(), MSSOTLTrafficLightLogic::trySwitch(), MSSOTLTrafficLightLogic::updateCTS(), MSRailCrossing::updateCurrentPhase(), MSSOTLTrafficLightLogic::updateDecayThreshold(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateShadowLane(), MSVehicleControl::vehicleDeparted(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSVehicle::wasRemoteControlled(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSQueueExport::writeEdge(), MSFullExport::writeEdge(), MSDevice_Vehroutes::writeOutput(), MSNet::writeOutput(), MSFullExport::writeTLS(), MSFullExport::writeVehicles(), MSDevice_BTreceiver::BTreceiverUpdate::~BTreceiverUpdate(), and MSDevice_Routing::~MSDevice_Routing().
MSJunctionControl& MSNet::getJunctionControl () inline inherited
Returns the junctions control.
Returns
The junctions control
See also
MSJunctionControl
myJunctions
Definition at line 393 of file MSNet.h.
References MSNet::myJunctions.
Referenced by TraCI_Junction::getIDList(), TraCI_Junction::getJunction(), and TraCIServerAPI_Junction::getTree().
std::vector< GUIGlID > GUINet::getJunctionIDs (bool includeInternal) const
Definition at line 233 of file GUINet.cpp.
References myJunctionWrapper.
Referenced by getAvgTripSpeed().
Position GUINet::getJunctionPosition (const std::string & name) const
returns the position of a junction
Definition at line 178 of file GUINet.cpp.
References NamedObjectCont< T >::get(), MSJunction::getPosition(), and MSNet::myJunctions.
const NamedRTree & MSNet::getLanesRTree () const inherited
Returns an RTree that contains lane IDs.
Returns
An Rtree containing lane IDs
Definition at line 973 of file MSNet.cpp.
References MSLane::fill(), and MSNet::myLanesRTree.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
int GUINet::getLinkTLID (MSLink * link) const
Returns the gl-id of the traffic light that controls the given link valid only if the link is controlled by a tls
Definition at line 191 of file GUINet.cpp.
References MSTLLogicControl::getActive(), myLinks2Logic, MSNet::myLogics, and myLogics2Wrapper.
Referenced by GUILane::drawLinkRule(), and getAvgTripSpeed().
int GUINet::getLinkTLIndex (MSLink * link) const
Returns the index of the link within the junction that controls the given link; Returns -1 if the link is not controlled by a tls
Definition at line 206 of file GUINet.cpp.
References MSTLLogicControl::getActive(), myLinks2Logic, MSNet::myLogics, and myLogics2Wrapper.
Referenced by GUILane::drawGL(), GUILane::drawTLSLinkNo(), and getAvgTripSpeed().
double GUINet::getMeanRTFactor (int duration) const
Returns the simulation speed as a factor to real time.
Definition at line 354 of file GUINet.cpp.
References myOverallSimDuration.
double GUINet::getMeanUPS () const
Returns the update per seconds rate.
Definition at line 363 of file GUINet.cpp.
References myOverallSimDuration, and MSNet::myVehiclesMoved.
Referenced by getParameterWindow().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 135 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNEJunction::getAttribute(), GNELane::getAttribute(), GNENetElement::getParentName(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSign::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNERerouter::getParentName(), GNEDetector::getParentName(), GNEDetectorE3::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEPoly::moveGeometry(), GNEEdge::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
GUIParameterTableWindow * GUINet::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 412 of file GUINet.cpp.
References GUIParameterTableWindow::closeBuilding(), getAvgDepartDelay(), getAvgDuration(), getAvgRouteLength(), getAvgTimeLoss(), getAvgTripSpeed(), getAvgWaitingTime(), MSVehicleControl::getCollisionCount(), MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getEndedVehicleNo(), getIdleDuration(), GUIEdge::getIDs(), MSNet::getInsertionControl(), MSTransportableControl::getJammedNumber(), MSTransportableControl::getLoadedNumber(), MSVehicleControl::getLoadedVehicleNo(), getMeanUPS(), OptionsCont::getOptions(), getPersonControl(), getRTFactor(), MSTransportableControl::getRunningNumber(), MSVehicleControl::getRunningVehicleNo(), getSimDuration(), MSVehicleControl::getTeleportCount(), GUIEdge::getTotalLength(), getUPS(), MSNet::getVehicleControl(), MSInsertionControl::getWaitingVehicleNo(), getWholeDuration(), MSNet::logSimulationDuration(), GUIParameterTableWindow::mkItem(), MSNet::myJunctions, MSNet::myPersonControl, MSNet::myVersion, NamedObjectCont< T >::size(), and toString().
Referenced by GUIApplicationWindow::onCmdShowStats().
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEDetectorE3, GNEDetector, GNERerouter, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSign, GNEVaporizer, GUILane, GNELane, and GNENetElement.
Definition at line 115 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
MSParkingArea * MSNet::getParkingArea (const std::string & id) const inherited
Returns the named parking area.
Parameters
[in] id The id of the parking area to return.
Returns
The named parking area, or 0 if no such stop exists
Definition at line 874 of file MSNet.cpp.
References NamedObjectCont< T >::get(), and MSNet::myParkingAreaDict.
Referenced by MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getShapeContainer(), and MSTriggeredRerouter::myStartElement().
std::string MSNet::getParkingAreaID (const MSLane * lane, const double pos) const inherited
Returns the parking area close to the given position.
Parameters
[in] lane the lane of the parking area to return.
[in] pos the position of the parking area to return.
Returns
The parking area id on the location, or "" if no such stop exists
Definition at line 879 of file MSNet.cpp.
References MSStoppingPlace::getEndLanePosition(), Named::getID(), MSStoppingPlace::getLane(), NamedObjectCont< T >::getMyMap(), MSNet::myParkingAreaDict, and POSITION_EPS.
Referenced by MSNet::getShapeContainer().
MSNet::MSPedestrianRouterDijkstra & MSNet::getPedestrianRouter (const MSEdgeVector & prohibited = MSEdgeVector()) const inherited
Definition at line 963 of file MSNet.cpp.
References MSNet::myPedestrianRouter, and PedestrianRouter< E, L, N, V, INTERNALROUTER >::prohibit().
Referenced by MSPModel_Striping::getNextLane(), MSRouteHandler::myStartElement(), MSPModel_Striping::PState::PState(), and MSNet::VehicleStateListener::~VehicleStateListener().
MSTransportableControl & GUINet::getPersonControl () virtual
Returns the person control.
If the person control does not exist, yet, it is created.
Returns
The person control
See also
MSPersonControl
myPersonControl
Reimplemented from MSNet.
Definition at line 120 of file GUINet.cpp.
References MSNet::myPersonControl.
Referenced by getAvgTripSpeed(), getParameterWindow(), and GUIApplicationWindow::handleEvent_SimulationStep().
GUIGLObjectPopupMenu * GUINet::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 400 of file GUINet.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), and GUIGlObject::buildShowParamsPopupEntry().
const std::map< SUMOVehicleClass, double > * MSNet::getRestrictions (const std::string & id) const inherited
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
Parameters
[in] id The id of the type
Returns
The mapping of vehicle classes to maximum speeds
Definition at line 294 of file MSNet.cpp.
References MSNet::myRestrictions.
Referenced by MSLane::initRestrictions(), and MSNet::setPermissionsFound().
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSNet::getRouterEffort (const MSEdgeVector & prohibited = MSEdgeVector()) const inherited
Definition at line 952 of file MSNet.cpp.
References MSEdge::getAllEdges(), MSNet::getEffort(), MSNet::getTravelTime(), MSNet::myRouterEffort, and prohibited_withPermissions< E, V >::prohibit().
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSNet::getRouterTT (const MSEdgeVector & prohibited = MSEdgeVector()) const inherited
Definition at line 925 of file MSNet.cpp.
References MSEdge::getAllEdges(), OptionsCont::getOptions(), OptionsCont::getString(), MSNet::getTravelTime(), MSNet::myRouterTTAStar, MSNet::myRouterTTDijkstra, MSNet::myRouterTTInitialized, prohibited_withPermissions< E, V >::prohibit(), and WRITE_WARNING.
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), MSTriggeredRerouter::notifyEnter(), TraCIServerAPI_Vehicle::processSet(), MSTriggeredRerouter::rerouteParkingZone(), and MSNet::VehicleStateListener::~VehicleStateListener().
double GUINet::getRTFactor () const
Returns the simulation speed as a factor to real time.
Definition at line 336 of file GUINet.cpp.
References myLastSimDuration.
Referenced by getParameterWindow().
ShapeContainer& MSNet::getShapeContainer () inline inherited
Returns the shapes container.
Returns
The shapes container
See also
ShapeContainer
myShapeContainer
Definition at line 433 of file MSNet.h.
References MSNet::addBusStop(), MSNet::addChargingStation(), MSNet::addContainerStop(), MSNet::addParkingArea(), MSNet::getBusStop(), MSNet::getBusStopID(), MSNet::getChargingStation(), MSNet::getChargingStationID(), MSNet::getContainerStop(), MSNet::getContainerStopID(), MSNet::getParkingArea(), MSNet::getParkingAreaID(), MSNet::getWeightsStorage(), MSNet::myShapeContainer, and MSNet::writeChargingStationOutput().
Referenced by TraCI_Polygon::add(), TraCI_POI::add(), NLHandler::addDistrict(), NLBuilder::build(), TraCI_Polygon::getIDList(), TraCI_POI::getIDList(), TraCI_POI::getPoI(), TraCIServerAPI_POI::getPoI(), TraCI_Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), TraCIServerAPI_POI::getTree(), TraCIServerAPI_Polygon::getTree(), GUISUMOViewParent::onCmdLocate(), GUIApplicationWindow::onCmdOpenShapes(), TraCI_Polygon::remove(), TraCI_POI::remove(), and TraCI_Polygon::setShape().
int GUINet::getSimDuration () const
Returns the duration of the last step's simulation part (in ms)
Returns
How long it took to compute the last step
Definition at line 322 of file GUINet.cpp.
References myLastSimDuration.
Referenced by getParameterWindow().
std::string MSNet::getStateMessage (MSNet::SimulationState state) static inherited
Returns the message to show if a certain state occurs.
Returns
Readable description of the state
Definition at line 572 of file MSNet.cpp.
References MSNet::SIMSTATE_CONNECTION_CLOSED, MSNet::SIMSTATE_END_STEP_REACHED, MSNet::SIMSTATE_ERROR_IN_SIM, MSNet::SIMSTATE_NO_FURTHER_VEHICLES, MSNet::SIMSTATE_RUNNING, and MSNet::SIMSTATE_TOO_MANY_TELEPORTS.
Referenced by GUIApplicationWindow::handleEvent_SimulationEnded(), GUIRunThread::makeStep(), MSNet::setPermissionsFound(), and MSNet::simulate().
MSTLLogicControl& MSNet::getTLSControl () inline inherited
Returns the tls logics control.
Returns
The tls logics control
See also
MSTLLogicControl
myLogics
Definition at line 383 of file MSNet.h.
References MSNet::myLogics.
Referenced by NLBuilder::build(), NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), NLJunctionControlBuilder::getTLLogicControlToUse(), initTLMap(), GUIViewTraffic::onGamingClick(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_TLS::processSet(), and MSFullExport::writeTLS().
std::vector< GUIGlID > GUINet::getTLSIDs () const
Returns the gl-ids of all traffic light logics within the net.
Definition at line 245 of file GUINet.cpp.
References myLogics2Wrapper.
Referenced by getAvgTripSpeed().
double MSNet::getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, double t) static inherited
Returns the travel time to pass an edge.
Parameters
[in] e The edge for which the travel time to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the travel time shall be returned [s]
Returns
The travel time for an edge
See also
DijkstraRouterTT_ByProxi
Definition at line 141 of file MSNet.cpp.
References MSNet::getInstance(), MSEdge::getMinimumTravelTime(), MSVehicle::getWeightsStorage(), MSNet::getWeightsStorage(), and MSEdgeWeightsStorage::retrieveExistingTravelTime().
Referenced by MSDevice_Routing::buildVehicleDevices(), MSNet::getRouterEffort(), MSNet::getRouterTT(), MSEdge::getTravelTimeStatic(), and MSNet::VehicleStateListener::~VehicleStateListener().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 148 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEDetector::drawDetectorIcon(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNECrossing::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEAdditional::drawParentAndChildrenConnections(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, and GUIPerson.
Definition at line 127 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
double GUINet::getUPS () const
Returns the update per seconds rate.
Definition at line 345 of file GUINet.cpp.
References myLastSimDuration, and myLastVehicleMovementCount.
Referenced by getParameterWindow().
MSVehicleControl& MSNet::getVehicleControl () inline inherited
Returns the vehicle control.
Returns
The vehicle control
See also
MSVehicleControl
myVehicleControl
Definition at line 310 of file MSNet.h.
References MSNet::getPersonControl(), and MSNet::myVehicleControl.
Referenced by MSVehicleTransfer::add(), MSVehicleType::buildSingularType(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), MSLane::detectCollisions(), MSInsertionControl::determineCandidates(), MSDevice::equippedByDefaultAssignmentOptions(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), TraCI_VehicleType::getIDList(), TraCI_Vehicle::getIDList(), MSLane::getMaximumBrakeDist(), getParameterWindow(), TraCIServerAPI_Vehicle::getPosition(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), TraCI_Vehicle::getVehicle(), TraCI_VehicleType::getVType(), MSLane::handleCollisionBetween(), GUIApplicationWindow::handleEvent_SimulationStep(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), GUISUMOViewParent::onCmdLocate(), MSBaseVehicle::onDepart(), TraCI_Vehicle::onInit(), MSRouteHandler::openVehicleTypeDistribution(), TraCIServer::postProcessVTD(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSVehicle::processNextStop(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Person::processSet(), MESegment::receive(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), MSCalibrator::removePending(), MSVehicle::resumeFromStopping(), MSStateHandler::saveState(), setSimDuration(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSNet::writeOutput(), and MSFullExport::writeVehicles().
SUMORTree& GUINet::getVisualisationSpeedUp () inline
Returns the RTree used for visualisation speed-up.
Returns
The visualisation speed-up
Definition at line 280 of file GUINet.h.
References myGrid.
const SUMORTree& GUINet::getVisualisationSpeedUp () const inline
Returns the RTree used for visualisation speed-up.
Returns
The visualisation speed-up
Definition at line 288 of file GUINet.h.
References createTLWrapper(), getGUIInstance(), getGUIMEVehicleControl(), getGUIVehicleControl(), initTLMap(), lock(), myGrid, and unlock().
MSEdgeWeightsStorage & MSNet::getWeightsStorage () inherited
Returns the net's internal edge travel times/efforts container.
If the net does not have such a container, it is built.
Returns
The net's knowledge about edge weights
Definition at line 747 of file MSNet.cpp.
References MSNet::myEdgeWeights.
Referenced by NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), GUILane::getColorValue(), MSNet::getEffort(), GUILane::getLoadedEdgeWeight(), GUILane::getScaleValue(), MSNet::getShapeContainer(), GUILane::getStoredEdgeTravelTime(), MSNet::getTravelTime(), and TraCIServerAPI_Edge::processSet().
int GUINet::getWholeDuration () const
Returns the duration of the last step (sim+visualisation+idle) (in ms)
Returns
How long it took to compute and display the last step
Definition at line 316 of file GUINet.cpp.
References myLastIdleDuration, and myLastSimDuration.
Referenced by getParameterWindow().
void GUINet::guiSimulationStep ()
Some further steps needed for gui processing.
Definition at line 219 of file GUINet.cpp.
References GLObjectValuePassConnector< T >::updateAll().
Referenced by GUIRunThread::makeStep().
bool MSNet::hasContainers () const inline inherited
Returns whether containers are simulated.
Definition at line 343 of file MSNet.h.
References MSNet::myContainerControl.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), and MSVehicle::processNextStop().
bool MSNet::hasElevation () const inline inherited
return whether the network contains elevation data
Definition at line 688 of file MSNet.h.
References MSNet::myHasElevation.
Referenced by MSVTypeProbe::execute().
bool MSNet::hasInternalLinks () const inline inherited
return whether the network contains internal links
Definition at line 678 of file MSNet.h.
References MSNet::myHasInternalLinks.
Referenced by MSNet::closeBuilding(), MSDevice_Tripinfo::computeLengthAndDuration(), MSTriggeredRerouter::rerouteParkingZone(), and MSDevice_Vehroutes::writeOutput().
bool MSNet::hasNeighs () const inline inherited
return whether the network contains explicit neighbor lanes
Definition at line 683 of file MSNet.h.
References MSNet::myHasNeighs.
Referenced by MSNet::closeBuilding().
bool MSNet::hasPermissions () const inline inherited
Returns whether the network has specific vehicle class permissions.
Returns
whether permissions are present
Definition at line 177 of file MSNet.h.
References MSNet::myHavePermissions.
Referenced by MSDevice_Routing::reroute().
bool MSNet::hasPersons () const inline inherited
Returns whether persons are simulated.
Definition at line 327 of file MSNet.h.
References MSNet::getContainerControl(), and MSNet::myPersonControl.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), and MSVehicle::processNextStop().
void MSNet::informVehicleStateListener (const SUMOVehicle *const vehicle, VehicleState to) inherited
Informs all added listeners about a vehicle's state change.
Parameters
[in] vehicle The vehicle which changed its state
[in] to The state the vehicle has changed to
See also
VehicleStateListener:vehicleStateChanged
Definition at line 811 of file MSNet.cpp.
References MSNet::myVehicleStateListeners.
Referenced by MSVehicleTransfer::add(), MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleTransfer::checkInsertions(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSVehicle::resumeFromStopping(), MSVehicleControl::scheduleVehicleRemoval(), MSVehicleControl::vehicleDeparted(), and MSNet::VehicleStateListener::~VehicleStateListener().
void GUINet::initGUIStructures ()
Initialises gui wrappers.
Definition at line 260 of file GUINet.cpp.
References Boundary::add(), SUMORTree::addAdditionalGLObject(), GUIEdge::fill(), MSDetectorControl::getAvailableTypes(), GUIJunctionWrapper::getBoundary(), Boundary::getHeight(), MSEdge::getLanes(), NamedObjectCont< T >::getMyMap(), MSDetectorControl::getTypedDetectors(), Boundary::getWidth(), Boundary::grow(), initTLMap(), LayeredRTree::Insert(), myBoundary, MSNet::myDetectorControl, myDetectorDict, myEdgeWrapper, myGrid, MSNet::myJunctions, myJunctionWrapper, MSPModel::SIDEWALK_OFFSET, NamedObjectCont< T >::size(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by getAvgTripSpeed(), and GUILoadThread::run().
void GUINet::initTLMap () private
Initialises the tl-logic map and wrappers.
Definition at line 138 of file GUINet.cpp.
References createTLWrapper(), MSTLLogicControl::getAllLogics(), MSNet::getTLSControl(), and myTLLogicWrappers.
Referenced by getVisualisationSpeedUp(), and initGUIStructures().
bool MSNet::lefthand () const inline inherited
return whether the network was built for lefthand traffic
Definition at line 693 of file MSNet.h.
References MSNet::myLefthand.
Referenced by MSNet::closeBuilding(), GUIBusStop::drawGL(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawMarkings(), GUILane::drawTLSLinkNo(), and GUIBusStop::GUIBusStop().
void MSNet::loadRoutes () inherited
loads routes for the next few steps
Definition at line 352 of file MSNet.cpp.
References SUMORouteLoaderControl::loadNext(), MSNet::myRouteLoaders, and MSNet::myStep.
Referenced by GUIRunThread::init(), MSNet::setPermissionsFound(), MSNet::simulate(), and MSNet::simulationStep().
void GUINet::lock ()
grant exclusive access to the simulation state
Definition at line 507 of file GUINet.cpp.
References MFXMutex::lock(), and myLock.
Referenced by GUIViewTraffic::doPaintGL(), and getVisualisationSpeedUp().
bool MSNet::logSimulationDuration () const inherited
Returns whether duration shall be logged.
Returns
Whether duration shall be logged
Definition at line 724 of file MSNet.cpp.
References MSNet::myLogExecutionTime.
Referenced by getParameterWindow(), and MSNet::setCurrentTimeStep().
void MSNet::postSimStepOutput () const inherited
Prints the statistics of the step at its end.
Called on the end of a simulation step
Definition at line 762 of file MSNet.cpp.
References DELTA_T, MSVehicleControl::getDepartedVehicleNo(), TraCIServer::getInstance(), MSVehicleControl::getRunningVehicleNo(), MSInsertionControl::getWaitingVehicleNo(), gPrecision, MSNet::myInserter, MSNet::myLogExecutionTime, MSNet::mySimStepDuration, MSNet::myStep, MSNet::myTraCIStepDuration, MSNet::myVehicleControl, time2string(), and TS.
Referenced by MSNet::setCurrentTimeStep(), and MSNet::simulate().
void MSNet::preSimStepOutput () const inherited
Prints the current step number.
Called on the begin of a simulation step
Definition at line 756 of file MSNet.cpp.
References MSNet::myStep, and time2string().
Referenced by MSNet::setCurrentTimeStep(), and MSNet::simulate().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 262 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void MSNet::removeVehicleStateListener (VehicleStateListener * listener) inherited
Removes a vehicle states listener.
Parameters
[in] listener The listener to remove
Definition at line 802 of file MSNet.cpp.
References MSNet::myVehicleStateListeners.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
void MSNet::setCurrentTimeStep (const SUMOTime step) inline inherited
Sets the current simulation step (used by state loading)
Parameters
step the current simulation step
Definition at line 265 of file MSNet.h.
References MSNet::logSimulationDuration(), MSNet::myStep, MSNet::postSimStepOutput(), MSNet::preSimStepOutput(), and MSNet::writeOutput().
Referenced by GUIRunThread::init().
void GUINet::setIdleDuration (int val)
Sets the duration of the last step's idle part.
Definition at line 394 of file GUINet.cpp.
References myLastIdleDuration.
Referenced by GUIRunThread::run().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 141 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
void MSNet::setPermissionsFound () inline inherited
Labels the network to contain vehicle class permissions.
Definition at line 183 of file MSNet.h.
References MSNet::addRestriction(), MSNet::clearAll(), MSNet::closeSimulation(), MSNet::getRestrictions(), MSNet::getStateMessage(), MSNet::loadRoutes(), MSNet::myHavePermissions, MSNet::simulate(), MSNet::simulationState(), and MSNet::simulationStep().
Referenced by NLHandler::addLane().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 271 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
void GUINet::setSimDuration (int val)
Sets the duration of the last step's simulation part.
Definition at line 378 of file GUINet.cpp.
References MSVehicleControl::getRunningVehicleNo(), MSNet::getVehicleControl(), myLastSimDuration, myLastVehicleMovementCount, myOverallSimDuration, and myOverallVehicleCount.
Referenced by GUIRunThread::run().
MSNet::SimulationState MSNet::simulate (SUMOTime start, SUMOTime stop) inherited
Simulates from timestep start to stop.
Parameters
[in] start The begin time step of the simulation
[in] stop The end time step of the simulation
Returns
Returns always 0
Todo:
Recheck return value
What exceptions may occure?
Definition at line 304 of file MSNet.cpp.
References MSNet::closeSimulation(), MSNet::getCurrentTimeStep(), TraCI::getLoadArgs(), OptionsCont::getOptions(), MSNet::getStateMessage(), MSNet::loadRoutes(), MSNet::myLogStepNumber, MSNet::myStep, MSNet::postSimStepOutput(), MSNet::preSimStepOutput(), OptionsIO::setArgs(), MSNet::SIMSTATE_LOADING, MSNet::SIMSTATE_RUNNING, MSNet::simulationState(), MSNet::simulationStep(), time2string(), TraCIServer::wasClosed(), and WRITE_MESSAGE.
Referenced by NLBuilder::loadAndRun(), and MSNet::setPermissionsFound().
MSNet::SimulationState MSNet::simulationState (SUMOTime stopTime) const inherited
Called after a simulation step, this method returns the current simulation state.
Parameters
[in] stopTime The time the simulation shall stop at
Returns
The current simulation state
See also
SimulationState
Definition at line 534 of file MSNet.cpp.
References MSTransportableControl::abortWaiting(), MSVehicleControl::abortWaiting(), MSVehicleControl::getActiveVehicleCount(), TraCI::getLoadArgs(), OptionsCont::getOptions(), MSInsertionControl::getPendingFlowCount(), MSVehicleControl::getTeleportCount(), MSTransportableControl::hasNonWaiting(), MSEventControl::isEmpty(), MSNet::myContainerControl, MSNet::myInserter, MSNet::myInsertionEvents, MSNet::myMaxTeleports, MSNet::myPersonControl, MSNet::myStep, MSNet::myVehicleControl, MSNet::SIMSTATE_CONNECTION_CLOSED, MSNet::SIMSTATE_END_STEP_REACHED, MSNet::SIMSTATE_LOADING, MSNet::SIMSTATE_NO_FURTHER_VEHICLES, MSNet::SIMSTATE_RUNNING, MSNet::SIMSTATE_TOO_MANY_TELEPORTS, and TraCIServer::wasClosed().
Referenced by GUIRunThread::makeStep(), MSNet::setPermissionsFound(), and MSNet::simulate().
void GUINet::simulationStep ()
Performs a single simulation step (locking the simulation)
Definition at line 226 of file GUINet.cpp.
References myLock, and MSNet::simulationStep().
Referenced by GUIRunThread::makeStep().
void GUINet::unlock ()
release exclusive access to the simulation state
Definition at line 513 of file GUINet.cpp.
References myLock, and MFXMutex::unlock().
Referenced by GUIViewTraffic::doPaintGL(), and getVisualisationSpeedUp().
bool GUINet::vehicleExists (const std::string & name) const
returns the information whether the vehicle still exists
Definition at line 185 of file GUINet.cpp.
References MSVehicleControl::getVehicle(), and MSNet::myVehicleControl.
double MSNet::version () const inline inherited
return the network version
Definition at line 698 of file MSNet.h.
References MSNet::checkElevation(), and MSNet::myVersion.
Referenced by MSNet::closeBuilding().
void MSNet::writeChargingStationOutput () const inherited
write charging station output
Definition at line 916 of file MSNet.cpp.
References OutputDevice::getDeviceByOption(), NamedObjectCont< T >::getMyMap(), and MSNet::myChargingStationDict.
Referenced by MSNet::closeSimulation(), and MSNet::getShapeContainer().
void MSNet::writeOutput () inherited
Write netstate, summary and detector output.
Todo:
Which exceptions may occur?
Definition at line 616 of file MSNet.cpp.
References OutputDevice::closeTag(), DELTA_T, MSVehicleControl::getDepartedVehicleNo(), OutputDevice::getDeviceByOption(), MSEdgeControl::getEdges(), MSVehicleControl::getEndedVehicleNo(), MSNet::getInstance(), MSDevice_SSM::getInstances(), OptionsCont::getInt(), MSVehicleControl::getLoadedVehicleNo(), OptionsCont::getOptions(), MSVehicleControl::getRunningVehicleNo(), OptionsCont::getString(), MSVehicleControl::getTotalDepartureDelay(), MSVehicleControl::getTotalTravelTime(), MSNet::getVehicleControl(), MSInsertionControl::getWaitingVehicleNo(), OptionsCont::isSet(), MSNet::myDetectorControl, MSNet::myEdges, MSNet::myHasElevation, MSNet::myInserter, MSNet::myLogExecutionTime, MSNet::mySimStepDuration, MSNet::myStep, MSNet::myVehicleControl, OutputDevice::openTag(), STEPS2TIME, SUMO_ATTR_ID, time2string(), MSDevice_SSM::updateAndWriteOutput(), MSDetectorControl::updateDetectors(), MSVTKExport::write(), MSEmissionExport::write(), MSBatteryExport::write(), MSQueueExport::write(), MSFCDExport::write(), MSFullExport::write(), MSAmitranTrajectories::write(), MSXMLRawOut::write(), OutputDevice::writeAttr(), and MSDetectorControl::writeOutput().
Referenced by MSNet::setCurrentTimeStep(), and MSNet::simulationStep().
Friends And Related Function Documentation
friend class GUIOSGBuilder friend
Definition at line 330 of file GUINet.h.
friend class GUITrafficLightLogicWrapper friend
Definition at line 91 of file GUINet.h.
Referenced by createTLWrapper().
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
MSEventControl* MSNet::myBeginOfTimestepEvents protected inherited
Controls events executed at the begin of a time step;.
See also
MSEventControl
Definition at line 741 of file MSNet.h.
Referenced by MSNet::getBeginOfTimestepEvents(), MSNet::MSNet(), MSNet::simulationStep(), and MSNet::~MSNet().
Boundary GUINet::myBoundary protected
The networks boundary.
Definition at line 337 of file GUINet.h.
Referenced by getBoundary(), and initGUIStructures().
NamedObjectCont<MSStoppingPlace*> MSNet::myBusStopDict protected inherited
Dictionary of bus stops.
Definition at line 813 of file MSNet.h.
Referenced by MSNet::addBusStop(), MSNet::getBusStop(), and MSNet::getBusStopID().
NamedObjectCont<MSChargingStation*> MSNet::myChargingStationDict protected inherited
Dictionary of charging Stations.
Definition at line 822 of file MSNet.h.
Referenced by MSNet::addChargingStation(), MSNet::getChargingStation(), MSNet::getChargingStationID(), and MSNet::writeChargingStationOutput().
MSTransportableControl* MSNet::myContainerControl protected inherited
Controls container building and deletion;.
See also
MSTransportableControl
Definition at line 729 of file MSNet.h.
Referenced by getContainerControl(), MSNet::getContainerControl(), MSNet::hasContainers(), MSNet::MSNet(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::~MSNet().
NamedObjectCont<MSStoppingPlace*> MSNet::myContainerStopDict protected inherited
Dictionary of container stops.
Definition at line 816 of file MSNet.h.
Referenced by MSNet::addContainerStop(), MSNet::getContainerStop(), and MSNet::getContainerStopID().
MSDetectorControl* MSNet::myDetectorControl protected inherited
Controls detectors;.
See also
MSDetectorControl
Definition at line 739 of file MSNet.h.
Referenced by MSNet::closeSimulation(), MSNet::getDetectorControl(), initGUIStructures(), MSNet::MSNet(), MSNet::writeOutput(), and MSNet::~MSNet().
std::vector<GUIDetectorWrapper*> GUINet::myDetectorDict protected
A detector dictionary.
Definition at line 349 of file GUINet.h.
Referenced by initGUIStructures(), and ~GUINet().
MSEdgeControl* MSNet::myEdges protected inherited
Controls edges, performs vehicle movement;.
See also
MSEdgeControl
Definition at line 731 of file MSNet.h.
Referenced by MSNet::checkElevation(), MSNet::closeBuilding(), MSNet::getEdgeControl(), MSNet::MSNet(), MSNet::simulationStep(), MSNet::writeOutput(), and MSNet::~MSNet().
MSEdgeWeightsStorage* MSNet::myEdgeWeights protected inherited
The net's knowledge about edge efforts/travel times;.
See also
MSEdgeWeightsStorage
Definition at line 749 of file MSNet.h.
Referenced by MSNet::getWeightsStorage(), MSNet::MSNet(), and MSNet::~MSNet().
std::vector<GUIEdge*> GUINet::myEdgeWrapper protected
Wrapped MS-edges.
Definition at line 340 of file GUINet.h.
Referenced by getGUIMEVehicleControl(), and initGUIStructures().
MSEventControl* MSNet::myEndOfTimestepEvents protected inherited
Controls events executed at the end of a time step;.
See also
MSEventControl
Definition at line 743 of file MSNet.h.
Referenced by MSNet::getEndOfTimestepEvents(), MSNet::MSNet(), MSNet::simulationStep(), and MSNet::~MSNet().
LayeredRTree GUINet::myGrid protected
The visualization speed-up.
Definition at line 334 of file GUINet.h.
Referenced by createTLWrapper(), getVisualisationSpeedUp(), and initGUIStructures().
bool MSNet::myHasElevation protected inherited
Whether the network contains elevation data.
Definition at line 804 of file MSNet.h.
Referenced by MSNet::closeBuilding(), MSNet::hasElevation(), and MSNet::writeOutput().
bool MSNet::myHasInternalLinks protected inherited
Whether the network contains internal links/lanes/edges.
Definition at line 798 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::hasInternalLinks().
bool MSNet::myHasNeighs protected inherited
Whether the network contains explicit neighbor lanes.
Definition at line 801 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::hasNeighs().
bool MSNet::myHavePermissions protected inherited
Whether the network contains edges which not all vehicles may pass.
Definition at line 792 of file MSNet.h.
Referenced by MSNet::hasPermissions(), and MSNet::setPermissionsFound().
MSInsertionControl* MSNet::myInserter protected inherited
Controls vehicle insertion;.
See also
MSInsertionControl
Definition at line 737 of file MSNet.h.
Referenced by MSNet::closeSimulation(), MSNet::getInsertionControl(), MSNet::MSNet(), MSNet::postSimStepOutput(), MSNet::simulationState(), MSNet::simulationStep(), MSNet::writeOutput(), and MSNet::~MSNet().
MSEventControl* MSNet::myInsertionEvents protected inherited
Controls insertion events;.
See also
MSEventControl
Definition at line 745 of file MSNet.h.
Referenced by MSNet::getInsertionEvents(), MSNet::MSNet(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::~MSNet().
MSNet * MSNet::myInstance = 0 static protected inherited
Unique instance of MSNet.
Definition at line 708 of file MSNet.h.
Referenced by MSNet::getInstance(), MSNet::MSNet(), and MSNet::~MSNet().
MSJunctionControl* MSNet::myJunctions protected inherited
Controls junctions, realizes right-of-way rules;.
See also
MSJunctionControl
Definition at line 733 of file MSNet.h.
Referenced by MSNet::closeBuilding(), MSNet::getJunctionControl(), getJunctionPosition(), getParameterWindow(), initGUIStructures(), MSNet::MSNet(), and MSNet::~MSNet().
std::vector<GUIJunctionWrapper*> GUINet::myJunctionWrapper protected
Wrapped MS-junctions.
Definition at line 343 of file GUINet.h.
Referenced by getGUIMEVehicleControl(), getJunctionIDs(), initGUIStructures(), and ~GUINet().
std::pair<bool, NamedRTree> MSNet::myLanesRTree mutable protected inherited
An RTree structure holding lane IDs.
Definition at line 840 of file MSNet.h.
Referenced by MSNet::getLanesRTree(), MSNet::MSNet(), and MSNet::~MSNet().
int GUINet::myLastIdleDuration protected
Definition at line 365 of file GUINet.h.
Referenced by getIdleDuration(), getWholeDuration(), and setIdleDuration().
int GUINet::myLastSimDuration protected
The step durations (simulation, /*visualisation, */idle)
Definition at line 365 of file GUINet.h.
Referenced by getRTFactor(), getSimDuration(), getUPS(), getWholeDuration(), and setSimDuration().
long GUINet::myLastVehicleMovementCount protected
Definition at line 367 of file GUINet.h.
Referenced by getUPS(), and setSimDuration().
bool MSNet::myLefthand protected inherited
Whether the network was built for left-hand traffic.
Definition at line 807 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::lefthand().
Links2LogicMap GUINet::myLinks2Logic protected
The link-to-logic-id map.
Definition at line 355 of file GUINet.h.
Referenced by createTLWrapper(), getLinkTLID(), and getLinkTLIndex().
MFXMutex GUINet::myLock mutable private
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 372 of file GUINet.h.
Referenced by lock(), simulationStep(), unlock(), and ~GUINet().
bool MSNet::myLogExecutionTime protected inherited
Information whether the simulation duration shall be logged.
Definition at line 758 of file MSNet.h.
Referenced by MSNet::closeBuilding(), MSNet::closeSimulation(), MSNet::logSimulationDuration(), MSNet::MSNet(), MSNet::postSimStepOutput(), MSNet::simulationStep(), and MSNet::writeOutput().
MSTLLogicControl* MSNet::myLogics protected inherited
Controls tls logics, realizes waiting on tls rules;.
See also
MSJunctionControl
Definition at line 735 of file MSNet.h.
Referenced by MSNet::closeBuilding(), createTLWrapper(), getLinkTLID(), getLinkTLIndex(), MSNet::getTLSControl(), MSNet::MSNet(), MSNet::simulationStep(), and MSNet::~MSNet().
Logics2WrapperMap GUINet::myLogics2Wrapper protected
The traffic light-to-wrapper map.
Definition at line 361 of file GUINet.h.
Referenced by createTLWrapper(), getLinkTLID(), getLinkTLIndex(), getTLSIDs(), and ~GUINet().
bool MSNet::myLogStepNumber protected inherited
Information whether the number of the simulation step shall be logged.
Definition at line 761 of file MSNet.h.
Referenced by MSNet::MSNet(), and MSNet::simulate().
int MSNet::myMaxTeleports protected inherited
Maximum number of teleports.
Definition at line 717 of file MSNet.h.
Referenced by MSNet::MSNet(), and MSNet::simulationState().
long GUINet::myOverallSimDuration protected
Definition at line 368 of file GUINet.h.
Referenced by getMeanRTFactor(), getMeanUPS(), and setSimDuration().
long GUINet::myOverallVehicleCount protected
Definition at line 367 of file GUINet.h.
Referenced by setSimDuration().
NamedObjectCont<MSParkingArea*> MSNet::myParkingAreaDict protected inherited
Dictionary of parking areas.
Definition at line 819 of file MSNet.h.
Referenced by MSNet::addParkingArea(), MSNet::getParkingArea(), and MSNet::getParkingAreaID().
MSPedestrianRouterDijkstra* MSNet::myPedestrianRouter mutable protected inherited
Definition at line 836 of file MSNet.h.
Referenced by MSNet::getPedestrianRouter(), and MSNet::~MSNet().
MSTransportableControl* MSNet::myPersonControl protected inherited
Controls person building and deletion;.
See also
MSTransportableControl
Definition at line 727 of file MSNet.h.
Referenced by MSNet::closeSimulation(), getParameterWindow(), getPersonControl(), MSNet::getPersonControl(), MSNet::hasPersons(), MSNet::MSNet(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::~MSNet().
std::map<std::string, std::map<SUMOVehicleClass, double> > MSNet::myRestrictions protected inherited
The vehicle class specific speed restrictions.
Definition at line 795 of file MSNet.h.
Referenced by MSNet::addRestriction(), and MSNet::getRestrictions().
SUMORouteLoaderControl* MSNet::myRouteLoaders protected inherited
Route loader for dynamic loading of routes.
Definition at line 711 of file MSNet.h.
Referenced by MSNet::closeBuilding(), MSNet::loadRoutes(), MSNet::MSNet(), and MSNet::~MSNet().
DijkstraRouterEffort<MSEdge, SUMOVehicle, prohibited_withPermissions<MSEdge, SUMOVehicle> >* MSNet::myRouterEffort mutable protected inherited
Definition at line 835 of file MSNet.h.
Referenced by MSNet::getRouterEffort(), and MSNet::~MSNet().
AStarRouter<MSEdge, SUMOVehicle, prohibited_withPermissions<MSEdge, SUMOVehicle> >* MSNet::myRouterTTAStar mutable protected inherited
Definition at line 834 of file MSNet.h.
Referenced by MSNet::getRouterTT(), and MSNet::~MSNet().
DijkstraRouterTT<MSEdge, SUMOVehicle, prohibited_withPermissions<MSEdge, SUMOVehicle> >* MSNet::myRouterTTDijkstra mutable protected inherited
Definition at line 833 of file MSNet.h.
Referenced by MSNet::getRouterTT(), and MSNet::~MSNet().
bool MSNet::myRouterTTInitialized mutable protected inherited
Definition at line 832 of file MSNet.h.
Referenced by MSNet::getRouterTT().
ShapeContainer* MSNet::myShapeContainer protected inherited
A container for geometrical shapes;.
See also
ShapeContainer
Definition at line 747 of file MSNet.h.
Referenced by MSNet::getShapeContainer(), MSNet::MSNet(), and MSNet::~MSNet().
long MSNet::mySimBeginMillis protected inherited
The overall simulation duration.
Definition at line 767 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::closeSimulation().
long MSNet::mySimStepDuration protected inherited
Definition at line 764 of file MSNet.h.
Referenced by MSNet::postSimStepOutput(), MSNet::simulationStep(), and MSNet::writeOutput().
std::vector<std::string> MSNet::myStateDumpFiles protected inherited
The names for the state files.
Definition at line 781 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
SUMOTime MSNet::myStateDumpPeriod protected inherited
The period for writing state.
Definition at line 783 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
std::string MSNet::myStateDumpPrefix protected inherited
name components for periodic state
Definition at line 785 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
std::string MSNet::myStateDumpSuffix protected inherited
Definition at line 786 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
std::vector<SUMOTime> MSNet::myStateDumpTimes protected inherited
Times at which a state shall be written.
Definition at line 779 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
SUMOTime MSNet::myStep protected inherited
Current time step.
Definition at line 714 of file MSNet.h.
Referenced by MSNet::closeSimulation(), MSNet::getCurrentTimeStep(), MSNet::loadRoutes(), MSNet::MSNet(), MSNet::postSimStepOutput(), MSNet::preSimStepOutput(), MSNet::setCurrentTimeStep(), MSNet::simulate(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::writeOutput().
std::vector<MSTrafficLightLogic*> GUINet::myTLLogicWrappers protected
Wrapped TL-Logics.
Definition at line 346 of file GUINet.h.
Referenced by initTLMap().
long MSNet::myTraCIStepDuration protected inherited
The last simulation step duration.
Definition at line 764 of file MSNet.h.
Referenced by MSNet::postSimStepOutput(), and MSNet::simulationStep().
MSVehicleControl* MSNet::myVehicleControl protected inherited
Controls vehicle building and deletion;.
See also
MSVehicleControl
Definition at line 725 of file MSNet.h.
Referenced by MSNet::closeSimulation(), getGUIMEVehicleControl(), getGUIVehicleControl(), MSNet::getVehicleControl(), MSNet::MSNet(), MSNet::postSimStepOutput(), MSNet::simulationState(), MSNet::simulationStep(), vehicleExists(), MSNet::writeOutput(), and MSNet::~MSNet().
long long int MSNet::myVehiclesMoved protected inherited
The overall number of vehicle movements.
Definition at line 770 of file MSNet.h.
Referenced by MSNet::closeSimulation(), getMeanUPS(), and MSNet::simulationStep().
std::vector<VehicleStateListener*> MSNet::myVehicleStateListeners protected inherited
Container for vehicle state listener.
Definition at line 825 of file MSNet.h.
Referenced by MSNet::addVehicleStateListener(), MSNet::informVehicleStateListener(), and MSNet::removeVehicleStateListener().
double MSNet::myVersion protected inherited
the network version
Definition at line 810 of file MSNet.h.
Referenced by MSNet::closeBuilding(), getParameterWindow(), and MSNet::version().
const std::string MSNet::STAGE_EVENTS static protected inherited
string constants for simstep stages
Definition at line 844 of file MSNet.h.
Referenced by MSNet::simulationStep().
const std::string MSNet::STAGE_INSERTIONS static protected inherited
Definition at line 847 of file MSNet.h.
Referenced by MSNet::simulationStep().
const std::string MSNet::STAGE_LANECHANGE static protected inherited
Definition at line 846 of file MSNet.h.
Referenced by MSNet::simulationStep().
const std::string MSNet::STAGE_MOVEMENTS static protected inherited
Definition at line 845 of file MSNet.h.
Referenced by MSNet::simulationStep().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUINet.h
GUINet.cpp