SUMO - Simulation of Urban MObility: TraCI_LaneArea Class Reference
TraCI_LaneArea Class Reference
C++ TraCI client API implementation.
#include <TraCI_LaneArea.h>
Static Public Member Functions
static int getIDCount ()
static std::vector< std::string > getIDList ()
static double getJamLengthMeters (const std::string &detID)
static int getJamLengthVehicle (const std::string &detID)
static std::string getLaneID (const std::string &detID)
static int getLastStepHaltingNumber (const std::string &detID)
static double getLastStepMeanSpeed (const std::string &detID)
static double getLastStepOccupancy (const std::string &detID)
static std::vector< std::string > getLastStepVehicleIDs (const std::string &detID)
static int getLastStepVehicleNumber (const std::string &detID)
static double getLength (const std::string &detID)
static double getPosition (const std::string &detID)
Private Member Functions
TraCI_LaneArea & operator= (const TraCI_LaneArea &src)
invalidated assignment operator
TraCI_LaneArea ()
invalidated standard constructor
TraCI_LaneArea (const TraCI_LaneArea &src)
invalidated copy constructor
Static Private Member Functions
static MSE2Collector * getDetector (const std::string &detID)
Detailed Description
C++ TraCI client API implementation.
Definition at line 49 of file TraCI_LaneArea.h.
Constructor & Destructor Documentation
TraCI_LaneArea::TraCI_LaneArea () private
invalidated standard constructor
TraCI_LaneArea::TraCI_LaneArea (const TraCI_LaneArea & src) private
invalidated copy constructor
Member Function Documentation
MSE2Collector * TraCI_LaneArea::getDetector (const std::string & detID) static private
Definition at line 121 of file TraCI_LaneArea.cpp.
References NamedObjectCont< T >::get(), MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), and SUMO_TAG_LANE_AREA_DETECTOR.
Referenced by getJamLengthMeters(), getJamLengthVehicle(), getLaneID(), getLastStepHaltingNumber(), getLastStepMeanSpeed(), getLastStepOccupancy(), getLastStepVehicleIDs(), getLastStepVehicleNumber(), getLength(), and getPosition().
int TraCI_LaneArea::getIDCount () static
Definition at line 53 of file TraCI_LaneArea.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::size(), and SUMO_TAG_LANE_AREA_DETECTOR.
Referenced by TraCIServerAPI_LaneArea::processGet().
std::vector< std::string > TraCI_LaneArea::getIDList () static
Definition at line 45 of file TraCI_LaneArea.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::insertIDs(), and SUMO_TAG_LANE_AREA_DETECTOR.
Referenced by TraCIServerAPI_LaneArea::processGet().
double TraCI_LaneArea::getJamLengthMeters (const std::string & detID) static
Definition at line 66 of file TraCI_LaneArea.cpp.
References MSE2Collector::getCurrentJamLengthInMeters(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
int TraCI_LaneArea::getJamLengthVehicle (const std::string & detID) static
Definition at line 60 of file TraCI_LaneArea.cpp.
References MSE2Collector::getCurrentJamLengthInVehicles(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
std::string TraCI_LaneArea::getLaneID (const std::string & detID) static
Definition at line 96 of file TraCI_LaneArea.cpp.
References getDetector(), Named::getID(), and MSMoveReminder::getLane().
Referenced by TraCIServerAPI_LaneArea::processGet().
int TraCI_LaneArea::getLastStepHaltingNumber (const std::string & detID) static
Definition at line 115 of file TraCI_LaneArea.cpp.
References MSE2Collector::getCurrentHaltingNumber(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
double TraCI_LaneArea::getLastStepMeanSpeed (const std::string & detID) static
Definition at line 72 of file TraCI_LaneArea.cpp.
References MSE2Collector::getCurrentMeanSpeed(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
double TraCI_LaneArea::getLastStepOccupancy (const std::string & detID) static
Definition at line 84 of file TraCI_LaneArea.cpp.
References MSE2Collector::getCurrentOccupancy(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
std::vector< std::string > TraCI_LaneArea::getLastStepVehicleIDs (const std::string & detID) static
Definition at line 78 of file TraCI_LaneArea.cpp.
References MSE2Collector::getCurrentVehicleIDs(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
int TraCI_LaneArea::getLastStepVehicleNumber (const std::string & detID) static
Definition at line 109 of file TraCI_LaneArea.cpp.
References MSE2Collector::getCurrentVehicleNumber(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
double TraCI_LaneArea::getLength (const std::string & detID) static
Definition at line 102 of file TraCI_LaneArea.cpp.
References getDetector(), MSE2Collector::getEndPos(), and MSE2Collector::getStartPos().
Referenced by TraCIServerAPI_LaneArea::processGet().
double TraCI_LaneArea::getPosition (const std::string & detID) static
Definition at line 90 of file TraCI_LaneArea.cpp.
References getDetector(), and MSE2Collector::getStartPos().
Referenced by TraCIServerAPI_LaneArea::processGet().
TraCI_LaneArea& TraCI_LaneArea::operator= (const TraCI_LaneArea & src) private
invalidated assignment operator
The documentation for this class was generated from the following files:
TraCI_LaneArea.h
TraCI_LaneArea.cpp