SUMO - Simulation of Urban MObility: NIXMLEdgesHandler Class Reference
NIXMLEdgesHandler Class Reference
Importer for network edges stored in XML.
#include <NIXMLEdgesHandler.h>
Data Structures
struct Split
A structure which describes changes of lane number or speed along the road.
class split_by_pos_finder
Finds a split at the given position.
class split_sorter
Sorts splits by their position (increasing)
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
NIXMLEdgesHandler (NBNodeCont &nc, NBEdgeCont &ec, NBTypeCont &tc, NBDistrictCont &dc, NBTrafficLightLogicCont &tlc, OptionsCont &options)
Constructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~NIXMLEdgesHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
void myEndElement (int element)
Called when a closing tag occurs.
Private Member Functions
void addEdge (const SUMOSAXAttributes &attrs)
Parses an edge and stores the values in "myCurrentEdge".
void addLane (const SUMOSAXAttributes &attrs)
Parses a lane and modifies myCurrentEdge according to the given attribures.
void addRoundabout (const SUMOSAXAttributes &attrs)
Parses a roundabout and stores it in myEdgeCont.
void addSplit (const SUMOSAXAttributes &attrs)
Parses a split and stores it in mySplits. Splits are executed Upon reading the end tag of an edge.
void deleteEdge (const SUMOSAXAttributes &attrs)
parses delete tag and deletes the specified edge or lane
NIXMLEdgesHandler (const NIXMLEdgesHandler &s)
invalid copy constructor
NIXMLEdgesHandler & operator= (const NIXMLEdgesHandler &s)
invalid assignment operator
bool setNodes (const SUMOSAXAttributes &attrs)
Sets from/to node information of the currently parsed edge.
LaneSpreadFunction tryGetLaneSpread (const SUMOSAXAttributes &attrs)
Tries to parse the spread type.
PositionVector tryGetShape (const SUMOSAXAttributes &attrs)
Tries to parse the shape definition.
Private Attributes
NBEdge * myCurrentEdge
The currently processed edge.
bool myHaveReportedAboutOverwriting
Information whether at least one edge's attributes were overwritten.
bool myHaveReportedAboutTypeOverride
Information whether at least one edge's type was changed.
bool myHaveWarnedAboutDeprecatedLaneId
bool myIsUpdate
Whether this edge definition is an update of a previously inserted edge.
const bool myKeepEdgeShape
Whether the edge shape shall be kept generally.
OptionsCont & myOptions
A reference to the program's options.
std::vector< Split > mySplits
The list of this edge's splits.
Currently parsed edge's values
std::string myCurrentID
The current edge's id.
double myCurrentSpeed
The current edge's maximum speed.
int myCurrentPriority
The current edge's priority.
int myCurrentLaneNo
The current edge's number of lanes.
double myCurrentWidth
The current edge's lane width.
double myCurrentEndOffset
The current edge's offset till the destination node.
std::string myCurrentStreetName
The current edge's street name.
std::string myCurrentType
The current edge's type.
NBNode * myFromNode
The nodes the edge starts and ends at.
NBNode * myToNode
double myLength
The current edge's length.
PositionVector myShape
The shape of the edge.
LaneSpreadFunction myLanesSpread
Information about how to spread the lanes.
SVCPermissions myPermissions
Information about lane permissions.
bool myReinitKeepEdgeShape
Whether the edge shape shall be kept at reinitilization.
double mySidewalkWidth
The width of the sidewalk that shall be added to the current edge.
double myBikeLaneWidth
The width of the bike lane that shall be added to the current edge.
Used instance containers (access to nodes, edges, types, etc.)
NBNodeCont & myNodeCont
The nodes container (for retrieval of referenced nodes)
NBEdgeCont & myEdgeCont
The edges container (for insertion of build edges)
NBTypeCont & myTypeCont
The types container (for retrieval of type defaults)
NBDistrictCont & myDistrictCont
The districts container (needed if an edge must be split)
NBTrafficLightLogicCont & myTLLogicCont
The traffic lights container to add built tls to (when invalidating tls because of splits)
Detailed Description
Importer for network edges stored in XML.
This SAX-handler parses edge information and stores it in the given container.
Todo:
revalidate node retrieval
One day, one should rethink the order of parsing. Now, the handler is able to load edges, using information from the types, first, and extending them by given information. In addition, if the read edge is already known, it's values are also used. Then, defining vehicles allowed per lane, and additional edge split definitions add some further complexity. This all works somehow for most of our use cases, but it's definitely not as consistent that everything what seems to be possible would also work appropriately.
Definition at line 71 of file NIXMLEdgesHandler.h.
Constructor & Destructor Documentation
NIXMLEdgesHandler::NIXMLEdgesHandler (NBNodeCont & nc, NBEdgeCont & ec, NBTypeCont & tc, NBDistrictCont & dc, NBTrafficLightLogicCont & tlc, OptionsCont & options)
Constructor.
Parameters
[in] nc The nodes container (for retrieval of referenced nodes)
[in] ec The edges container (for insertion of build edges)
[in] tc The types container (for retrieval of type defaults)
[in] dc The districts container (needed if an edge must be split)
[in] options The options to use while building edges
Definition at line 62 of file NIXMLEdgesHandler.cpp.
NIXMLEdgesHandler::~NIXMLEdgesHandler ()
Destructor.
Definition at line 82 of file NIXMLEdgesHandler.cpp.
NIXMLEdgesHandler::NIXMLEdgesHandler (const NIXMLEdgesHandler & s) private
invalid copy constructor
Member Function Documentation
void NIXMLEdgesHandler::addEdge (const SUMOSAXAttributes & attrs) private
Parses an edge and stores the values in "myCurrentEdge".
Parameters
[in] attrs The attributes to get the edge's values from
Definition at line 114 of file NIXMLEdgesHandler.cpp.
References NBEdgeCont::erase(), SUMOSAXAttributes::get(), NBTypeCont::getBikeLaneWidth(), OptionsCont::getBool(), NBEdge::getGeometry(), NBEdge::getLaneSpreadFunction(), NBEdge::getLoadedLength(), NBTypeCont::getNumLanes(), NBEdge::getNumLanes(), SUMOSAXAttributes::getOpt(), NBTypeCont::getPermissions(), NBTypeCont::getPriority(), NBEdge::getPriority(), NBTypeCont::getSidewalkWidth(), NBTypeCont::getSpeed(), NBEdge::getStreetName(), SUMOSAXAttributes::getStringSecure(), NBEdge::getTypeID(), NBTypeCont::getWidth(), SUMOSAXAttributes::hasAttribute(), NBEdge::hasDefaultGeometry(), NBEdge::hasLoadedLength(), OptionsCont::isDefault(), NBTypeCont::knows(), LANESPREAD_RIGHT, myBikeLaneWidth, myCurrentEdge, myCurrentEndOffset, myCurrentID, myCurrentLaneNo, myCurrentPriority, myCurrentSpeed, myCurrentStreetName, myCurrentType, myCurrentWidth, myDistrictCont, myEdgeCont, myFromNode, myHaveReportedAboutOverwriting, myHaveReportedAboutTypeOverride, myIsUpdate, myKeepEdgeShape, myLanesSpread, myLength, myOptions, myPermissions, myReinitKeepEdgeShape, myShape, mySidewalkWidth, mySplits, myToNode, myTypeCont, parseVehicleClasses(), NBEdge::reinit(), NBEdgeCont::retrieve(), OptionsCont::set(), NBEdge::setLoadedLength(), setNodes(), NBEdge::setPermissions(), SUMO_ATTR_ALLOW, SUMO_ATTR_BIKELANEWIDTH, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, SUMO_ATTR_REMOVE, SUMO_ATTR_SIDEWALKWIDTH, SUMO_ATTR_SPEED, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, SVC_UNSPECIFIED, tryGetLaneSpread(), tryGetShape(), NBEdge::UNSPECIFIED_LOADED_LENGTH, NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_SPEED, NBEdge::UNSPECIFIED_WIDTH, WRITE_ERROR, and WRITE_MESSAGE.
Referenced by myStartElement().
void NIXMLEdgesHandler::addLane (const SUMOSAXAttributes & attrs) private
Parses a lane and modifies myCurrentEdge according to the given attribures.
Parameters
[in] attrs The attributes to get the lanes's values from
Definition at line 284 of file NIXMLEdgesHandler.cpp.
References SUMOSAXAttributes::get(), NBEdge::getNumLanes(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), SUMOSAXAttributes::hasAttribute(), myCurrentEdge, myCurrentID, myHaveWarnedAboutDeprecatedLaneId, parseVehicleClasses(), NBEdge::setAcceleration(), NBEdge::setEndOffset(), NBEdge::setLaneWidth(), NBEdge::setPermissions(), NBEdge::setPreferredVehicleClass(), NBEdge::setSpeed(), SUMO_ATTR_ACCELERATION, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_PREFER, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NIXMLEdgesHandler::addRoundabout (const SUMOSAXAttributes & attrs) private
Parses a roundabout and stores it in myEdgeCont.
Parameters
[in] attrs The attributes to get the roundabouts values from
Definition at line 656 of file NIXMLEdgesHandler.cpp.
References NBEdgeCont::addRoundabout(), SUMOSAXAttributes::getStringVector(), SUMOSAXAttributes::hasAttribute(), myEdgeCont, NBEdgeCont::retrieve(), SUMO_ATTR_EDGES, NBEdgeCont::wasIgnored(), and WRITE_ERROR.
Referenced by myStartElement().
void NIXMLEdgesHandler::addSplit (const SUMOSAXAttributes & attrs) private
Parses a split and stores it in mySplits. Splits are executed Upon reading the end tag of an edge.
Parameters
[in] attrs The attributes to get the splits's values from
Definition at line 339 of file NIXMLEdgesHandler.cpp.
References TplConvert::_2int(), SUMOSAXAttributes::get(), OptionsCont::getBool(), NBEdge::getGeometry(), Named::getID(), NBEdge::getNumLanes(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), NBNode::getPosition(), NBEdge::getSpeed(), SUMOSAXAttributes::hasAttribute(), NIXMLEdgesHandler::Split::idAfter, NIXMLEdgesHandler::Split::idBefore, NIXMLEdgesHandler::Split::lanes, PositionVector::length(), myCurrentEdge, myCurrentID, myNodeCont, myOptions, mySplits, myTLLogicCont, NIXMLEdgesHandler::Split::node, SUMOSAXAttributes::parseStringVector(), NIXMLEdgesHandler::Split::pos, PositionVector::positionAtOffset(), NIXMLNodesHandler::processNodeType(), NIXMLEdgesHandler::Split::speed, SUMO_ATTR_ID_AFTER, SUMO_ATTR_ID_BEFORE, SUMO_ATTR_LANES, SUMO_ATTR_POSITION, SUMO_ATTR_SPEED, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 188 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 171 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void NIXMLEdgesHandler::deleteEdge (const SUMOSAXAttributes & attrs) private
parses delete tag and deletes the specified edge or lane
Parameters
[in] attrs The attributes to get the edge id and the optional lane index from
Definition at line 475 of file NIXMLEdgesHandler.cpp.
References NBEdge::deleteLane(), NBEdgeCont::extract(), SUMOSAXAttributes::get(), NBEdge::getIncomingEdges(), SUMOSAXAttributes::getOpt(), myCurrentID, myDistrictCont, myEdgeCont, NBEdge::removeFromConnections(), NBEdgeCont::retrieve(), SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_TAG_DELETE, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 122 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 207 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 213 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 82 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 223 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void NIXMLEdgesHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 502 of file NIXMLEdgesHandler.cpp.
References NBEdge::addBikeLane(), NBEdge::addLane2LaneConnection(), NBEdge::addSidewalk(), NBEdge::decLaneNo(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), NBEdge::getLaneSpreadFunction(), NBEdge::getNumLanes(), NBNode::getOutgoingEdges(), NBEdge::getToNode(), NIXMLEdgesHandler::Split::idAfter, NIXMLEdgesHandler::Split::idBefore, NBEdge::incLaneNo(), NBNodeCont::insert(), NBEdgeCont::insert(), NBEdge::invalidateConnections(), NBNode::invalidateTLS(), NBEdge::L2L_VALIDATED, NIXMLEdgesHandler::Split::lanes, LANESPREAD_CENTER, LANESPREAD_RIGHT, PositionVector::length(), NBNodeCont::markAsSplit(), MAX2(), PositionVector::move2side(), myBikeLaneWidth, myCurrentEdge, myCurrentID, myDistrictCont, myEdgeCont, myIsUpdate, myNodeCont, mySidewalkWidth, mySplits, myTLLogicCont, NIXMLEdgesHandler::Split::node, NIXMLEdgesHandler::Split::pos, NBEdgeCont::retrieve(), NBEdge::setGeometry(), NIXMLEdgesHandler::Split::speed, NBEdgeCont::splitAt(), SUMO_const_halfLaneAndOffset, SUMO_const_laneWidthAndOffset, SUMO_TAG_EDGE, toString(), NBEdge::UNSPECIFIED_WIDTH, WRITE_ERROR, and WRITE_WARNING.
void NIXMLEdgesHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 86 of file NIXMLEdgesHandler.cpp.
References addEdge(), addLane(), addRoundabout(), addSplit(), deleteEdge(), NBEdge::getLaneStruct(), NBEdge::getNumLanes(), SUMOSAXAttributes::getString(), myCurrentEdge, SUMO_ATTR_LANE, SUMO_TAG_DELETE, SUMO_TAG_EDGE, SUMO_TAG_LANE, SUMO_TAG_NEIGH, SUMO_TAG_ROUNDABOUT, and SUMO_TAG_SPLIT.
NIXMLEdgesHandler& NIXMLEdgesHandler::operator= (const NIXMLEdgesHandler & s) private
invalid assignment operator
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 163 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 76 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
bool NIXMLEdgesHandler::setNodes (const SUMOSAXAttributes & attrs) private
Sets from/to node information of the currently parsed edge.
If the nodes could be retrieved/built, they are set in myFromNode/myToNode, respectively, and true is returned. If not, false is returned.
Parameters
[in] attrs The SAX-attributes to parse the nodes from
Returns
Whether valid nodes exist
Definition at line 399 of file NIXMLEdgesHandler.cpp.
References SUMOSAXAttributes::get(), NBEdge::getFromNode(), Named::getID(), NBEdge::getToNode(), SUMOSAXAttributes::hasAttribute(), myCurrentEdge, myCurrentID, myFromNode, myIsUpdate, myNodeCont, myShape, myToNode, NBNodeCont::retrieve(), SUMO_ATTR_FROM, SUMO_ATTR_TO, and WRITE_ERROR.
Referenced by addEdge().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 101 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
LaneSpreadFunction NIXMLEdgesHandler::tryGetLaneSpread (const SUMOSAXAttributes & attrs) private
Tries to parse the spread type.
Definition at line 460 of file NIXMLEdgesHandler.cpp.
References StringBijection< T >::get(), SUMOSAXAttributes::getOpt(), SUMOXMLDefinitions::LaneSpreadFunctions, myCurrentID, myLanesSpread, SUMO_ATTR_SPREADTYPE, toString(), and WRITE_WARNING.
Referenced by addEdge().
PositionVector NIXMLEdgesHandler::tryGetShape (const SUMOSAXAttributes & attrs) private
Tries to parse the shape definition.
Returns the edge's geometry (may be empty if no one was defined). Writes an error message if an error occured.
Parameters
[in] attrs The attributes to read the shape from
Returns
The edge's shape
Definition at line 440 of file NIXMLEdgesHandler.cpp.
References SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::hasAttribute(), myCurrentID, myKeepEdgeShape, myReinitKeepEdgeShape, myShape, SUMO_ATTR_SHAPE, NBNetBuilder::transformCoordinates(), and WRITE_ERROR.
Referenced by addEdge().
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 201 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
double NIXMLEdgesHandler::myBikeLaneWidth private
The width of the bike lane that shall be added to the current edge.
Definition at line 194 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), and myEndElement().
NBEdge* NIXMLEdgesHandler::myCurrentEdge private
The currently processed edge.
Definition at line 225 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), addLane(), addSplit(), myEndElement(), myStartElement(), and setNodes().
double NIXMLEdgesHandler::myCurrentEndOffset private
The current edge's offset till the destination node.
Definition at line 164 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
std::string NIXMLEdgesHandler::myCurrentID private
The current edge's id.
Definition at line 149 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), addLane(), addSplit(), deleteEdge(), myEndElement(), setNodes(), tryGetLaneSpread(), and tryGetShape().
int NIXMLEdgesHandler::myCurrentLaneNo private
The current edge's number of lanes.
Definition at line 158 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
int NIXMLEdgesHandler::myCurrentPriority private
The current edge's priority.
Definition at line 155 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
double NIXMLEdgesHandler::myCurrentSpeed private
The current edge's maximum speed.
Definition at line 152 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
std::string NIXMLEdgesHandler::myCurrentStreetName private
The current edge's street name.
Definition at line 167 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
std::string NIXMLEdgesHandler::myCurrentType private
The current edge's type.
Definition at line 170 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
double NIXMLEdgesHandler::myCurrentWidth private
The current edge's lane width.
Definition at line 161 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
NBDistrictCont& NIXMLEdgesHandler::myDistrictCont private
The districts container (needed if an edge must be split)
Definition at line 216 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), deleteEdge(), and myEndElement().
NBEdgeCont& NIXMLEdgesHandler::myEdgeCont private
The edges container (for insertion of build edges)
Definition at line 210 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), addRoundabout(), deleteEdge(), and myEndElement().
NBNode* NIXMLEdgesHandler::myFromNode private
The nodes the edge starts and ends at.
Definition at line 173 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), and setNodes().
bool NIXMLEdgesHandler::myHaveReportedAboutOverwriting private
Information whether at least one edge's attributes were overwritten.
Definition at line 286 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
bool NIXMLEdgesHandler::myHaveReportedAboutTypeOverride private
Information whether at least one edge's type was changed.
Definition at line 289 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
bool NIXMLEdgesHandler::myHaveWarnedAboutDeprecatedLaneId private
Definition at line 291 of file NIXMLEdgesHandler.h.
Referenced by addLane().
bool NIXMLEdgesHandler::myIsUpdate private
Whether this edge definition is an update of a previously inserted edge.
Definition at line 200 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), myEndElement(), and setNodes().
const bool NIXMLEdgesHandler::myKeepEdgeShape private
Whether the edge shape shall be kept generally.
Definition at line 294 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), and tryGetShape().
LaneSpreadFunction NIXMLEdgesHandler::myLanesSpread private
Information about how to spread the lanes.
Definition at line 182 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), and tryGetLaneSpread().
double NIXMLEdgesHandler::myLength private
The current edge's length.
Definition at line 176 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
NBNodeCont& NIXMLEdgesHandler::myNodeCont private
The nodes container (for retrieval of referenced nodes)
Definition at line 207 of file NIXMLEdgesHandler.h.
Referenced by addSplit(), myEndElement(), and setNodes().
OptionsCont& NIXMLEdgesHandler::myOptions private
A reference to the program's options.
Definition at line 142 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), and addSplit().
SVCPermissions NIXMLEdgesHandler::myPermissions private
Information about lane permissions.
Definition at line 185 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
bool NIXMLEdgesHandler::myReinitKeepEdgeShape private
Whether the edge shape shall be kept at reinitilization.
Definition at line 188 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), and tryGetShape().
PositionVector NIXMLEdgesHandler::myShape private
The shape of the edge.
Definition at line 179 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), setNodes(), and tryGetShape().
double NIXMLEdgesHandler::mySidewalkWidth private
The width of the sidewalk that shall be added to the current edge.
Definition at line 191 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), and myEndElement().
std::vector<Split> NIXMLEdgesHandler::mySplits private
The list of this edge's splits.
Definition at line 246 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), addSplit(), and myEndElement().
NBTrafficLightLogicCont& NIXMLEdgesHandler::myTLLogicCont private
The traffic lights container to add built tls to (when invalidating tls because of splits)
Definition at line 220 of file NIXMLEdgesHandler.h.
Referenced by addSplit(), and myEndElement().
NBNode * NIXMLEdgesHandler::myToNode private
Definition at line 173 of file NIXMLEdgesHandler.h.
Referenced by addEdge(), and setNodes().
NBTypeCont& NIXMLEdgesHandler::myTypeCont private
The types container (for retrieval of type defaults)
Definition at line 213 of file NIXMLEdgesHandler.h.
Referenced by addEdge().
The documentation for this class was generated from the following files:
NIXMLEdgesHandler.h
NIXMLEdgesHandler.cpp