SUMO - Simulation of Urban MObility: SUMOVehicleClass.cpp File Reference
SUMOVehicleClass.cpp File Reference
#include <config.h>
#include <string>
#include <map>
#include "SUMOVehicleClass.h"
#include <utils/common/TplConvert.h>
#include <utils/common/ToString.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/StringTokenizer.h>
#include <utils/iodevices/OutputDevice.h>
Functions
bool canParseVehicleClasses (const std::string &classes)
Checks whether the given string contains only known vehicle classes.
bool canParseVehicleShape (const std::string &shape)
Checks whether the given string contains only known vehicle shape.
const double DEFAULT_CONTAINER_TRANSHIP_SPEED (5./3.6)
const double DEFAULT_PEDESTRIAN_SPEED (5./3.6)
const std::string DEFAULT_PEDTYPE_ID ("DEFAULT_PEDTYPE")
const double DEFAULT_VEH_PROB (1.)
const std::string DEFAULT_VTYPE_ID ("DEFAULT_VEHTYPE")
int getVehicleClassCompoundID (const std::string &name)
Returns the OR'ed id of the compound class given by its name.
SUMOVehicleClass getVehicleClassID (const std::string &name)
Returns the class id of the abstract class given by its name.
std::string getVehicleClassNames (SVCPermissions permissions, bool expand)
Returns the ids of the given classes, divided using a ' '.
std::vector< std::string > getVehicleClassNamesList (SVCPermissions permissions)
Returns the ids of the given classes, divided using a ' '.
SUMOVehicleShape getVehicleShapeID (const std::string &name)
Returns the class id of the shape class given by its name.
std::string getVehicleShapeName (SUMOVehicleShape id)
Returns the class name of the shape class given by its id.
bool isForbidden (SVCPermissions permissions)
Returns whether an edge with the given permission is a forbidden edge.
bool isRailway (SVCPermissions permissions)
Returns whether an edge with the given permission is a railway edge.
bool isWaterway (SVCPermissions permissions)
Returns whether an edge with the given permission is a waterway edge.
SVCPermissions parseVehicleClasses (const std::string &allowedS)
Parses the given definition of allowed vehicle classes into the given containers Deprecated classes go into a separate container.
SVCPermissions parseVehicleClasses (const std::string &allowedS, const std::string &disallowedS)
Encodes the given vector of allowed and disallowed classes into a bitset.
SVCPermissions parseVehicleClasses (const std::vector< std::string > &allowedS)
Encodes the given vector of allowed classs into a bitset Unlike the methods which parse a string it gives immediately a warning output on deprecated vehicle classes.
void writePermissions (OutputDevice &into, SVCPermissions permissions)
writes allowed disallowed attributes if needed;
void writePreferences (OutputDevice &into, SVCPermissions preferred)
writes allowed disallowed attributes if needed;
Variables
std::set< std::string > deprecatedVehicleClassesSeen
const int SUMOVehicleClass_MAX = SVC_CUSTOM2
StringBijection< SUMOVehicleClass >::Entry sumoVehicleClassStringInitializer []
StringBijection< SUMOVehicleClass > SumoVehicleClassStrings (sumoVehicleClassStringInitializer, SVC_CUSTOM2, false)
StringBijection< SUMOVehicleShape >::Entry sumoVehicleShapeStringInitializer []
StringBijection< SUMOVehicleShape > SumoVehicleShapeStrings (sumoVehicleShapeStringInitializer, SVS_UNKNOWN, false)
const SVCPermissions SVC_UNSPECIFIED = -1
permissions not specified
const SVCPermissions SVCAll = 2 * SUMOVehicleClass_MAX - 1
all VClasses are allowed
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Walter Bamberger
Date
2006-01-24
Version
Id
SUMOVehicleClass.cpp 23559 2017-03-20 14:43:57Z bieker
Definition in file SUMOVehicleClass.cpp.
Function Documentation
bool canParseVehicleClasses (const std::string & classes)
Checks whether the given string contains only known vehicle classes.
Definition at line 222 of file SUMOVehicleClass.cpp.
References StringTokenizer::hasNext(), StringBijection< T >::hasString(), and StringTokenizer::next().
Referenced by GNEEdge::isValid(), GNELane::isValid(), GNERerouterIntervalDialog::onCmdEditClosingLaneReroute(), GNERerouterIntervalDialog::onCmdEditClosingReroute(), and GNECalibratorVehicleType::setVClass().
bool canParseVehicleShape (const std::string & shape)
Checks whether the given string contains only known vehicle shape.
Definition at line 308 of file SUMOVehicleClass.cpp.
References StringBijection< T >::hasString().
Referenced by GNECalibratorVehicleType::setShape().
const double DEFAULT_CONTAINER_TRANSHIP_SPEED (5./3. 6)
Referenced by isForbidden().
const double DEFAULT_PEDESTRIAN_SPEED (5./3. 6)
Referenced by isForbidden().
const std::string DEFAULT_PEDTYPE_ID ("DEFAULT_PEDTYPE")
Referenced by isForbidden().
const double DEFAULT_VEH_PROB (1.)
Referenced by isForbidden().
const std::string DEFAULT_VTYPE_ID ("DEFAULT_VEHTYPE")
Referenced by isForbidden().
int getVehicleClassCompoundID (const std::string & name)
Returns the OR'ed id of the compound class given by its name.
Parameters
[in] name The name of the abstract vehicle class
Returns
The OR'ed combination of base enum values
Definition at line 185 of file SUMOVehicleClass.cpp.
References StringBijection< T >::get(), StringBijection< T >::getStrings(), and SVC_IGNORING.
SUMOVehicleClass getVehicleClassID (const std::string & name)
Returns the class id of the abstract class given by its name.
Parameters
[in] name The name of the abstract vehicle class
Returns
The internal representation of this class. Name must not be a compound name
Definition at line 176 of file SUMOVehicleClass.cpp.
References StringBijection< T >::get(), and StringBijection< T >::hasString().
Referenced by NIXMLTypesHandler::myStartElement(), RONetHandler::myStartElement(), NLHandler::myStartElement(), SUMOVehicleParserHelper::parseVehicleClass(), parseVehicleClasses(), GNECalibratorVehicleType::setVClass(), and TraCI_VehicleType::setVehicleClass().
std::string getVehicleClassNames (SVCPermissions permissions, bool expand = false)
Returns the ids of the given classes, divided using a ' '.
Parameters
[in] the permissions to encode
[in] expand whether 'all' should be used
Returns
The string representation of these classes
Definition at line 152 of file SUMOVehicleClass.cpp.
References getVehicleClassNamesList(), joinToString(), and SVCAll.
Referenced by GNEEdge::getAttribute(), GNELane::getAttribute(), GNELane::getColorValue(), GUILane::getParameterWindow(), GNEDialog_AllowDisallow::onCmdAccept(), GNEInspectorFrame::AttributeInput::onCmdOpenAllowDisallowEditor(), GNEDialog_AllowDisallow::onCmdReset(), GNENet::restrictLane(), GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues(), GNERerouterIntervalDialog::updateClosingLaneReroutesTable(), GNERerouterIntervalDialog::updateClosingReroutesTable(), GNERerouter::writeAdditional(), writePermissions(), writePreferences(), and NBTypeCont::writeTypes().
std::vector<std::string> getVehicleClassNamesList (SVCPermissions permissions)
Returns the ids of the given classes, divided using a ' '.
Parameters
[in] the permissions to encode
Returns
The string representation of these classes as a vector
Todo:
cache values?
Definition at line 161 of file SUMOVehicleClass.cpp.
References StringBijection< T >::get(), StringBijection< T >::getStrings(), and SVC_IGNORING.
Referenced by TraCI_Lane::getAllowed(), TraCI_Lane::getDisallowed(), and getVehicleClassNames().
SUMOVehicleShape getVehicleShapeID (const std::string & name)
Returns the class id of the shape class given by its name.
Parameters
[in] name The name of the shape class
Returns
The internal representation of this class
Definition at line 299 of file SUMOVehicleClass.cpp.
References StringBijection< T >::get(), and StringBijection< T >::hasString().
Referenced by GNECalibratorVehicleType::setShape(), and TraCI_VehicleType::setShapeClass().
std::string getVehicleShapeName (SUMOVehicleShape id)
Returns the class name of the shape class given by its id.
Parameters
[in] id The id of the shape class
Returns
The string representation of this class
Definition at line 314 of file SUMOVehicleClass.cpp.
References StringBijection< T >::getString().
Referenced by TraCI_VehicleType::getShapeClass(), GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues(), and SUMOVTypeParameter::write().
bool isForbidden (SVCPermissions permissions)
Returns whether an edge with the given permission is a forbidden edge.
Parameters
[in] permissions The permissions of the edge
Returns
Whether the edge is forbidden
Definition at line 329 of file SUMOVehicleClass.cpp.
References DEFAULT_CONTAINER_TRANSHIP_SPEED(), DEFAULT_PEDESTRIAN_SPEED(), DEFAULT_PEDTYPE_ID(), DEFAULT_VEH_PROB(), DEFAULT_VTYPE_ID(), and SVCAll.
Referenced by NBNode::ApproachingDivider::ApproachingDivider(), NBOwnTLDef::computeLogicAndConts(), NBEdge::divideOnEdges(), NBOwnTLDef::patchStateForCrossings(), and NBEdge::recheckLanes().
bool isRailway (SVCPermissions permissions)
Returns whether an edge with the given permission is a railway edge.
Parameters
[in] permissions The permissions of the edge
Returns
Whether the edge is a railway edge
Definition at line 319 of file SUMOVehicleClass.cpp.
References SVC_PASSENGER, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, and SVC_TRAM.
Referenced by GNENet::addReversedEdge(), NBTrafficLightDefinition::collectAllLinks(), GNELane::drawAsRailway(), GUILane::drawAsRailway(), GNELane::getColorValue(), GUILane::getColorValue(), NWWriter_OpenDrive::getLaneType(), NBNode::getLinkState(), NBEdge::recheckLanes(), and NBEdge::shiftPositionAtNode().
bool isWaterway (SVCPermissions permissions)
Returns whether an edge with the given permission is a waterway edge.
Parameters
[in] permissions The permissions of the edge
Returns
Whether the edge is a waterway edge
Definition at line 324 of file SUMOVehicleClass.cpp.
References SVC_SHIP.
Referenced by NBNodeTypeComputer::computeNodeTypes(), NBNodeTypeComputer::computeSingleNodeType(), GNELane::drawAsWaterway(), GUILane::drawAsWaterway(), GUILane::drawGL(), and GUIJunctionWrapper::GUIJunctionWrapper().
SVCPermissions parseVehicleClasses (const std::string & allowedS)
Parses the given definition of allowed vehicle classes into the given containers Deprecated classes go into a separate container.
Parameters
[in] classNames Space separated class names
[out] container The set of vehicle classes to fill throws ProcessError if parsing fails
Definition at line 198 of file SUMOVehicleClass.cpp.
References deprecatedVehicleClassesSeen, StringBijection< T >::getString(), getVehicleClassID(), StringTokenizer::hasNext(), StringBijection< T >::hasString(), StringTokenizer::next(), SVCAll, and WRITE_ERROR.
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLEdgesHandler::addEdge(), NLHandler::addLane(), NIXMLEdgesHandler::addLane(), NBEdgeCont::applyOptions(), NBNetBuilder::applyOptions(), NIXMLTypesHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), GNERerouterIntervalDialog::onCmdEditClosingLaneReroute(), GNERerouterIntervalDialog::onCmdEditClosingReroute(), GNEInspectorFrame::AttributeInput::onCmdOpenAllowDisallowEditor(), RONetHandler::parseLane(), parseVehicleClasses(), TraCIServerAPI_Edge::processSet(), TraCI_Lane::setAllowed(), GNELane::setAttribute(), and TraCI_Lane::setDisallowed().
SVCPermissions parseVehicleClasses (const std::string & allowedS, const std::string & disallowedS)
Encodes the given vector of allowed and disallowed classes into a bitset.
Parameters
[in] allowedS Definition which classes are allowed
[in] disallowedS Definition which classes are not allowed
Definition at line 236 of file SUMOVehicleClass.cpp.
References parseVehicleClasses(), SVCAll, and WRITE_WARNING.
SVCPermissions parseVehicleClasses (const std::vector< std::string > & allowedS)
Encodes the given vector of allowed classs into a bitset Unlike the methods which parse a string it gives immediately a warning output on deprecated vehicle classes.
Parameters
[in] classesS The names vector to parse
Definition at line 251 of file SUMOVehicleClass.cpp.
References StringBijection< T >::getString(), getVehicleClassID(), and WRITE_WARNING.
void writePermissions (OutputDevice & into, SVCPermissions permissions)
writes allowed disallowed attributes if needed;
Definition at line 266 of file SUMOVehicleClass.cpp.
References getVehicleClassNames(), StringBijection< T >::size(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMOVehicleClass_MAX, SVCAll, and OutputDevice::writeAttr().
Referenced by NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeLane(), and NBTypeCont::writeTypes().
void writePreferences (OutputDevice & into, SVCPermissions preferred)
writes allowed disallowed attributes if needed;
Definition at line 289 of file SUMOVehicleClass.cpp.
References getVehicleClassNames(), SUMO_ATTR_PREFER, SVCAll, and OutputDevice::writeAttr().
Referenced by NWWriter_XML::writeEdgesAndConnections(), and NWWriter_SUMO::writeLane().
Variable Documentation
std::set<std::string> deprecatedVehicleClassesSeen
Definition at line 90 of file SUMOVehicleClass.cpp.
Referenced by NIImporter_SUMO::_loadNetwork(), NLEdgeControlBuilder::build(), loadNet(), ROLoader::loadNet(), NILoader::loadXML(), and parseVehicleClasses().
const int SUMOVehicleClass_MAX = SVC_CUSTOM2
Definition at line 141 of file SUMOVehicleClass.cpp.
Referenced by writePermissions().
StringBijection<SUMOVehicleClass>::Entry sumoVehicleClassStringInitializer[]
Definition at line 48 of file SUMOVehicleClass.cpp.
StringBijection<SUMOVehicleClass> SumoVehicleClassStrings(sumoVehicleClassStringInitializer, SVC_CUSTOM2, false)
Referenced by CHBuilder< E, V >::buildContractionHierarchy(), CHRouter< E, V, PF >::clone(), GNEAttributeCarrier::discreteChoices(), GUIApplicationWindow::fillMenuBar(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), GNECalibratorVehicleTypeDialog::GNECalibratorVehicleTypeDialog(), GUIApplicationWindow::onCmdEditChosen(), GNEAttributeCarrier::parse(), SUMOVehicleParserHelper::parseVehicleClass(), GNENet::revertLaneRestriction(), and toString< SUMOVehicleClass >().
StringBijection<SUMOVehicleShape>::Entry sumoVehicleShapeStringInitializer[]
Definition at line 93 of file SUMOVehicleClass.cpp.
StringBijection<SUMOVehicleShape> SumoVehicleShapeStrings(sumoVehicleShapeStringInitializer, SVS_UNKNOWN, false)
Referenced by GNEAttributeCarrier::discreteChoices(), GNECalibratorVehicleTypeDialog::GNECalibratorVehicleTypeDialog(), GNEAttributeCarrier::parse(), and SUMOVehicleParserHelper::parseGuiShape().
const SVCPermissions SVC_UNSPECIFIED = -1
permissions not specified
Definition at line 143 of file SUMOVehicleClass.cpp.
Referenced by NIXMLEdgesHandler::addEdge(), and NWWriter_SUMO::writeLane().
const SVCPermissions SVCAll = 2 * SUMOVehicleClass_MAX - 1
all VClasses are allowed
Definition at line 142 of file SUMOVehicleClass.cpp.
Referenced by NLHandler::addLane(), NINavTeqHelper::addVehicleClasses(), NINavTeqHelper::addVehicleClassesV6(), NBEdge::dismissVehicleClassInformation(), TraCI_Lane::getAllowed(), NWWriter_DlrNavteq::getAllowedTypes(), NBEdge::getFirstNonPedestrianLaneIndex(), NWWriter_OpenDrive::getLaneType(), getVehicleClassNames(), GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), NBEdge::hasPermissions(), MSEdge::initialize(), isForbidden(), MSTriggeredRerouter::myEndElement(), MSTriggeredRerouter::notifyEnter(), GNEInspectorFrame::AttributeInput::onCmdOpenAllowDisallowEditor(), NIImporter_VISUM::parse_Types(), RONetHandler::parseLane(), parseVehicleClasses(), MSEdge::rebuildAllowedLanes(), NIImporter_DlrNavteq::EdgesHandler::report(), MSLane::resetPermissions(), ROEdge::ROEdge(), MSTriggeredRerouter::setPermissions(), NWWriter_SUMO::writeInternalEdges(), writePermissions(), writePreferences(), and NWWriter_DlrNavteq::writeProhibitedManoeuvres().