SUMO - Simulation of Urban MObility: emissionsDrivingCycle_main.cpp File Reference
emissionsDrivingCycle_main.cpp File Reference
#include <config.h>
#include <utils/common/TplConvert.h>
#include <iostream>
#include <string>
#include <ctime>
#include <utils/common/MsgHandler.h>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/ToString.h>
#include <utils/xml/XMLSubSys.h>
#include <utils/common/FileHelpers.h>
#include <utils/common/StringTokenizer.h>
#include <utils/common/StringUtils.h>
#include <utils/emissions/PollutantsInterface.h>
#include <utils/iodevices/OutputDevice.h>
#include <utils/importio/LineReader.h>
#include "TrajectoriesHandler.h"
Functions
int main (int argc, char **argv)
Detailed Description
Author
Daniel Krajzewicz
Michael Behrisch
Date
Wed, 21.08.2013
Version
Id
emissionsDrivingCycle_main.cpp 23529 2017-03-18 10:22:36Z behrisch
Definition in file emissionsDrivingCycle_main.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 67 of file emissionsDrivingCycle_main.cpp.
References SystemFrame::addConfigurationOptions(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), SystemFrame::close(), OutputDevice::createDeviceByOption(), OptionsCont::doRegister(), OptionsCont::getBool(), PollutantsInterface::getClassByName(), OutputDevice::getDeviceByOption(), MsgHandler::getErrorInstance(), OptionsCont::getFloat(), OptionsCont::getInt(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), StringTokenizer::hasNext(), MsgHandler::inform(), XMLSubSys::init(), TrajectoriesHandler::INVALID_VALUE, OptionsCont::isSet(), OptionsCont::processMetaOptions(), StringUtils::prune(), LineReader::readLine(), XMLSubSys::runParser(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), and VERSION_STRING.