SUMO - Simulation of Urban MObility: TraCIServerAPI_TLS Class Reference
TraCIServerAPI_TLS Class Reference
APIs for getting/setting traffic light values via TraCI.
#include <TraCIServerAPI_TLS.h>
Static Public Member Functions
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa2: Get Traffic Lights Variable)
static bool processSet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xc2: Change Traffic Lights State)
Private Member Functions
TraCIServerAPI_TLS & operator= (const TraCIServerAPI_TLS &s)
invalidated assignment operator
TraCIServerAPI_TLS (const TraCIServerAPI_TLS &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting traffic light values via TraCI.
Definition at line 48 of file TraCIServerAPI_TLS.h.
Constructor & Destructor Documentation
TraCIServerAPI_TLS::TraCIServerAPI_TLS (const TraCIServerAPI_TLS & s) private
invalidated copy constructor
Member Function Documentation
TraCIServerAPI_TLS& TraCIServerAPI_TLS::operator= (const TraCIServerAPI_TLS & s) private
invalidated assignment operator
bool TraCIServerAPI_TLS::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa2: Get Traffic Lights Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 48 of file TraCIServerAPI_TLS.cpp.
References CMD_GET_TL_VARIABLE, MSPhaseDefinition::duration, MSTLLogicControl::get(), MSTLLogicControl::TLSLogicVariants::getActive(), MSTLLogicControl::TLSLogicVariants::getAllLogics(), MSTLLogicControl::getAllTLIds(), MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), Named::getID(), MSNet::getInstance(), MSLink::getLane(), MSTrafficLightLogic::getLaneVectors(), MSTrafficLightLogic::getLinks(), Parameterised::getMap(), MSTrafficLightLogic::getNextSwitchTime(), Parameterised::getParameter(), MSTrafficLightLogic::getPhase(), MSTrafficLightLogic::getPhaseNumber(), MSTrafficLightLogic::getProgramID(), MSPhaseDefinition::getState(), MSNet::getTLSControl(), MSLink::getViaLane(), ID_COUNT, ID_LIST, MSTLLogicControl::knows(), MSPhaseDefinition::maxDuration, MSPhaseDefinition::minDuration, tcpip::Storage::readString(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_TL_VARIABLE, RTYPE_OK, TL_COMPLETE_DEFINITION_RYG, TL_CONTROLLED_JUNCTIONS, TL_CONTROLLED_LANES, TL_CONTROLLED_LINKS, TL_CURRENT_PHASE, TL_CURRENT_PROGRAM, TL_EXTERNAL_STATE, TL_NEXT_SWITCH, TL_PHASE_DURATION, TL_RED_YELLOW_GREEN_STATE, toHex(), TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, TYPE_UBYTE, VAR_PARAMETER, TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
bool TraCIServerAPI_TLS::processSet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xc2: Change Traffic Lights State)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 286 of file TraCIServerAPI_TLS.cpp.
References MSTLLogicControl::TLSLogicVariants::addLogic(), Parameterised::addParameter(), MSTrafficLightLogic::changeStepAndDuration(), CMD_SET_TL_VARIABLE, MSPhaseDefinition::duration, MSTLLogicControl::get(), MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSTLLogicControl::TLSLogicVariants::getLogic(), MSTrafficLightLogic::getPhase(), MSTrafficLightLogic::getPhaseNumber(), MSNet::getTLSControl(), tcpip::Storage::readInt(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingInt(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RTYPE_OK, MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSTLLogicControl::TLSLogicVariants::switchTo(), TL_COMPLETE_PROGRAM_RYG, TL_PHASE_DURATION, TL_PHASE_INDEX, TL_PROGRAM, TL_RED_YELLOW_GREEN_STATE, toHex(), toString(), TYPE_COMPOUND, VAR_PARAMETER, TraCIServer::writeErrorStatusCmd(), and TraCIServer::writeStatusCmd().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_TLS.h
TraCIServerAPI_TLS.cpp