SUMO - Simulation of Urban MObility: TraCIAPI::LaneScope Class Reference
TraCIAPI::LaneScope Class Reference
Scope for interaction with lanes.
#include <TraCIAPI.h>
Public Member Functions
std::vector< std::string > getAllowed (const std::string &laneID) const
double getCO2Emission (const std::string &laneID) const
double getCOEmission (const std::string &laneID) const
std::vector< std::string > getDisallowed (const std::string &laneID) const
std::string getEdgeID (const std::string &laneID) const
double getElectricityConsumption (const std::string &laneID) const
double getFuelConsumption (const std::string &laneID) const
double getHCEmission (const std::string &laneID) const
std::vector< std::string > getIDList () const
int getLastStepHaltingNumber (const std::string &laneID) const
double getLastStepLength (const std::string &laneID) const
double getLastStepMeanSpeed (const std::string &laneID) const
double getLastStepOccupancy (const std::string &laneID) const
std::vector< std::string > getLastStepVehicleIDs (const std::string &laneID) const
int getLastStepVehicleNumber (const std::string &laneID) const
double getLength (const std::string &laneID) const
int getLinkNumber (const std::string &laneID) const
double getMaxSpeed (const std::string &laneID) const
double getNoiseEmission (const std::string &laneID) const
double getNOxEmission (const std::string &laneID) const
double getPMxEmission (const std::string &laneID) const
TraCIPositionVector getShape (const std::string &laneID) const
double getTraveltime (const std::string &laneID) const
double getWidth (const std::string &laneID) const
LaneScope (TraCIAPI &parent)
void setAllowed (const std::string &laneID, const std::vector< std::string > &allowedClasses) const
void setDisallowed (const std::string &laneID, const std::vector< std::string > &disallowedClasses) const
void setLength (const std::string &laneID, double length) const
void setMaxSpeed (const std::string &laneID, double speed) const
virtual ~LaneScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
LaneScope (const LaneScope &src)
invalidated copy constructor
LaneScope & operator= (const LaneScope &src)
invalidated assignment operator
Detailed Description
Scope for interaction with lanes.
Definition at line 285 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::LaneScope::LaneScope (TraCIAPI & parent) inline
Definition at line 287 of file TraCIAPI.h.
virtual TraCIAPI::LaneScope::~LaneScope () inline virtual
Definition at line 288 of file TraCIAPI.h.
References TraCIAPI::TraCIScopeWrapper::operator=().
TraCIAPI::LaneScope::LaneScope (const LaneScope & src) private
invalidated copy constructor
Member Function Documentation
std::vector< std::string > TraCIAPI::LaneScope::getAllowed (const std::string & laneID) const
Definition at line 948 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LANE_ALLOWED.
double TraCIAPI::LaneScope::getCO2Emission (const std::string & laneID) const
Definition at line 973 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_CO2EMISSION.
double TraCIAPI::LaneScope::getCOEmission (const std::string & laneID) const
Definition at line 978 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_COEMISSION.
std::vector< std::string > TraCIAPI::LaneScope::getDisallowed (const std::string & laneID) const
Definition at line 953 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LANE_DISALLOWED.
std::string TraCIAPI::LaneScope::getEdgeID (const std::string & laneID) const
Definition at line 968 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LANE_EDGE_ID.
double TraCIAPI::LaneScope::getElectricityConsumption (const std::string & laneID) const
Definition at line 1008 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_ELECTRICITYCONSUMPTION.
double TraCIAPI::LaneScope::getFuelConsumption (const std::string & laneID) const
Definition at line 998 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_FUELCONSUMPTION.
double TraCIAPI::LaneScope::getHCEmission (const std::string & laneID) const
Definition at line 983 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_HCEMISSION.
std::vector< std::string > TraCIAPI::LaneScope::getIDList () const
Definition at line 928 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and ID_LIST.
int TraCIAPI::LaneScope::getLastStepHaltingNumber (const std::string & laneID) const
Definition at line 1038 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_VEHICLE_HALTING_NUMBER.
double TraCIAPI::LaneScope::getLastStepLength (const std::string & laneID) const
Definition at line 1023 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_LENGTH.
double TraCIAPI::LaneScope::getLastStepMeanSpeed (const std::string & laneID) const
Definition at line 1013 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_MEAN_SPEED.
double TraCIAPI::LaneScope::getLastStepOccupancy (const std::string & laneID) const
Definition at line 1018 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_OCCUPANCY.
std::vector< std::string > TraCIAPI::LaneScope::getLastStepVehicleIDs (const std::string & laneID) const
Definition at line 1043 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_VEHICLE_ID_LIST.
int TraCIAPI::LaneScope::getLastStepVehicleNumber (const std::string & laneID) const
Definition at line 1033 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_VEHICLE_NUMBER.
double TraCIAPI::LaneScope::getLength (const std::string & laneID) const
Definition at line 933 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_LENGTH.
int TraCIAPI::LaneScope::getLinkNumber (const std::string & laneID) const
Definition at line 958 of file TraCIAPI.cpp.
double TraCIAPI::LaneScope::getMaxSpeed (const std::string & laneID) const
Definition at line 938 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_MAXSPEED.
double TraCIAPI::LaneScope::getNoiseEmission (const std::string & laneID) const
Definition at line 1003 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_NOISEEMISSION.
double TraCIAPI::LaneScope::getNOxEmission (const std::string & laneID) const
Definition at line 993 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_NOXEMISSION.
double TraCIAPI::LaneScope::getPMxEmission (const std::string & laneID) const
Definition at line 988 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_PMXEMISSION.
TraCIPositionVector TraCIAPI::LaneScope::getShape (const std::string & laneID) const
Definition at line 963 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_SHAPE.
double TraCIAPI::LaneScope::getTraveltime (const std::string & laneID) const
Definition at line 1028 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_CURRENT_TRAVELTIME.
double TraCIAPI::LaneScope::getWidth (const std::string & laneID) const
Definition at line 943 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_WIDTH.
LaneScope& TraCIAPI::LaneScope::operator= (const LaneScope & src) private
invalidated assignment operator
void TraCIAPI::LaneScope::setAllowed (const std::string & laneID, const std::vector< std::string > & allowedClasses) const
Definition at line 1049 of file TraCIAPI.cpp.
References CMD_SET_LANE_VARIABLE, LANE_ALLOWED, TYPE_STRINGLIST, tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::LaneScope::setDisallowed (const std::string & laneID, const std::vector< std::string > & disallowedClasses) const
Definition at line 1062 of file TraCIAPI.cpp.
References CMD_SET_LANE_VARIABLE, LANE_DISALLOWED, TYPE_STRINGLIST, tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::LaneScope::setLength (const std::string & laneID, double length) const
Definition at line 1085 of file TraCIAPI.cpp.
References CMD_SET_LANE_VARIABLE, TYPE_DOUBLE, VAR_LENGTH, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::LaneScope::setMaxSpeed (const std::string & laneID, double speed) const
Definition at line 1075 of file TraCIAPI.cpp.
References CMD_SET_LANE_VARIABLE, TYPE_DOUBLE, VAR_MAXSPEED, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 131 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp