SUMO - Simulation of Urban MObility: TraCI_Polygon Class Reference
TraCI_Polygon Class Reference
#include <TraCI_Polygon.h>
Static Public Member Functions
static void add (const std::string &polygonID, const TraCIPositionVector &shape, const TraCIColor &c, bool fill, const std::string &type, int layer)
static TraCIColor getColor (const std::string &polygonID)
static bool getFilled (const std::string &polygonID)
static std::vector< std::string > getIDList ()
static std::string getParameter (const std::string &polygonID, const std::string &paramName)
static TraCIPositionVector getShape (const std::string &polygonID)
static std::string getType (const std::string &polygonID)
static void remove (const std::string &polygonID, int layer=0)
static void setColor (const std::string &polygonID, const TraCIColor &c)
static void setFilled (std::string polygonID, bool filled)
static void setParameter (std::string &name, std::string &value, std::string &string)
static void setShape (const std::string &polygonID, const TraCIPositionVector &shape)
static void setType (const std::string &polygonID, const std::string &setType)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
TraCI_Polygon & operator= (const TraCI_Polygon &src)
invalidated assignment operator
TraCI_Polygon ()
invalidated standard constructor
TraCI_Polygon (const TraCI_Polygon &src)
invalidated copy constructor
Static Private Member Functions
static SUMO::Polygon * getPolygon (const std::string &id)
Detailed Description
Definition at line 29 of file TraCI_Polygon.h.
Constructor & Destructor Documentation
TraCI_Polygon::TraCI_Polygon () private
invalidated standard constructor
TraCI_Polygon::TraCI_Polygon (const TraCI_Polygon & src) private
invalidated copy constructor
Member Function Documentation
void TraCI_Polygon::add (const std::string & polygonID, const TraCIPositionVector & shape, const TraCIColor & c, bool fill, const std::string & type, int layer) static
Definition at line 67 of file TraCI_Polygon.cpp.
References ShapeContainer::addPolygon(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, MSNet::getInstance(), MSNet::getShapeContainer(), TraCI::makePositionVector(), and TraCI::makeRGBColor().
Referenced by TraCIServerAPI_Polygon::processSet().
TraCIColor TraCI_Polygon::getColor (const std::string & polygonID) static
Definition at line 46 of file TraCI_Polygon.cpp.
References Shape::getColor(), getPolygon(), and TraCI::makeTraCIColor().
Referenced by TraCIServerAPI_Polygon::processGet().
bool TraCI_Polygon::getFilled (const std::string & polygonID) static
Definition at line 43 of file TraCI_Polygon.cpp.
References SUMO::Polygon::getFill(), and getPolygon().
Referenced by TraCIServerAPI_Polygon::processGet().
std::vector< std::string > TraCI_Polygon::getIDList () static
Definition at line 30 of file TraCI_Polygon.cpp.
References MSNet::getInstance(), ShapeContainer::getPolygons(), MSNet::getShapeContainer(), and NamedObjectCont< T >::insertIDs().
Referenced by TraCIServerAPI_Polygon::processGet().
std::string TraCI_Polygon::getParameter (const std::string & polygonID, const std::string & paramName) static
Definition at line 50 of file TraCI_Polygon.cpp.
References Parameterised::getParameter(), and getPolygon().
Referenced by TraCIServerAPI_Polygon::processGet().
SUMO::Polygon * TraCI_Polygon::getPolygon (const std::string & id) static private
Definition at line 88 of file TraCI_Polygon.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), ShapeContainer::getPolygons(), and MSNet::getShapeContainer().
Referenced by getColor(), getFilled(), getParameter(), getShape(), getType(), setColor(), setFilled(), setParameter(), setShape(), and setType().
TraCIPositionVector TraCI_Polygon::getShape (const std::string & polygonID) static
Definition at line 39 of file TraCI_Polygon.cpp.
References getPolygon(), SUMO::Polygon::getShape(), and TraCI::makeTraCIPositionVector().
Referenced by TraCIServerAPI_Polygon::processGet().
std::string TraCI_Polygon::getType (const std::string & polygonID) static
Definition at line 36 of file TraCI_Polygon.cpp.
References getPolygon(), and Shape::getType().
Referenced by TraCIServerAPI_Polygon::processGet().
TraCI_Polygon& TraCI_Polygon::operator= (const TraCI_Polygon & src) private
invalidated assignment operator
void TraCI_Polygon::remove (const std::string & polygonID, int layer = 0) static
Definition at line 75 of file TraCI_Polygon.cpp.
References MSNet::getInstance(), MSNet::getShapeContainer(), and ShapeContainer::removePolygon().
Referenced by TraCIServerAPI_Polygon::processSet().
void TraCI_Polygon::setColor (const std::string & polygonID, const TraCIColor & c) static
Definition at line 63 of file TraCI_Polygon.cpp.
References getPolygon(), TraCI::makeRGBColor(), and Shape::setColor().
Referenced by TraCIServerAPI_Polygon::processSet().
void TraCI_Polygon::setFilled (std::string polygonID, bool filled) static
Definition at line 83 of file TraCI_Polygon.cpp.
References getPolygon(), and SUMO::Polygon::setFill().
Referenced by TraCIServerAPI_Polygon::processSet().
void TraCI_Polygon::setParameter (std::string & name, std::string & value, std::string & string) static
Definition at line 95 of file TraCI_Polygon.cpp.
References Parameterised::addParameter(), and getPolygon().
Referenced by TraCIServerAPI_Polygon::processSet().
void TraCI_Polygon::setShape (const std::string & polygonID, const TraCIPositionVector & shape) static
Definition at line 57 of file TraCI_Polygon.cpp.
References MSNet::getInstance(), getPolygon(), MSNet::getShapeContainer(), TraCI::makePositionVector(), and ShapeContainer::reshapePolygon().
Referenced by TraCIServerAPI_Polygon::processSet().
void TraCI_Polygon::setType (const std::string & polygonID, const std::string & setType) static
Definition at line 53 of file TraCI_Polygon.cpp.
References getPolygon(), and Shape::setType().
Referenced by TraCIServerAPI_Polygon::processSet().
static void TraCI_Polygon::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
static void TraCI_Polygon::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
TraCI_Polygon.h
TraCI_Polygon.cpp