SUMO - Simulation of Urban MObility: MSAbstractLaneChangeModel Class Reference
MSAbstractLaneChangeModel Class Reference abstract
Interface for lane-change models.
#include <MSAbstractLaneChangeModel.h>
Data Structures
class MSLCMessager
A class responsible for exchanging messages between cars involved in lane-change interaction.
struct StateAndDist
Public Member Functions
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
virtual void changed ()=0
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void cleanupShadowLane ()
virtual bool debugVehicle () const
whether the current vehicles shall be debugged
virtual StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
double getAngleOffset () const
return the angle offset during a continuous change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
double getLateralSpeed () const
return the lateral speed of the current lane change maneuver
int getOwnState () const
virtual std::string getParameter (const std::string &key) const
try to retrieve the given parameter from this laneChangeModel. Throw exception for unsupported key
const std::pair< int, int > & getSavedState (const int dir) const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< double > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
virtual void * inform (void *info, MSVehicle *sender)=0
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
MSAbstractLaneChangeModel (MSVehicle &v, const LaneChangeModel model)
Constructor.
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
virtual double patchSpeed (const double min, const double wanted, const double max, const MSCFModel &cfModel)=0
Called to adapt the speed in order to allow a lane change.
virtual void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
virtual void saveBlockerLength (double length)
reserve space at the end of the lane to avoid dead locks
void saveState (const int dir, const int stateWithoutTraCI, const int state)
void setNoShadowPartialOccupator (MSLane *lane)
virtual void setOwnState (const int state)
virtual void setParameter (const std::string &key, const std::string &value)
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
bool updateCompletion ()
virtual void updateExpectedSublaneSpeeds (const MSLeaderInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
void updateShadowLane ()
virtual int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, double > &leader, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, double &latDist, int &blocked)
virtual ~MSAbstractLaneChangeModel ()
Destructor.
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
Protected Member Functions
bool cancelRequest (int state)
whether the influencer cancels the given request
virtual bool congested (const MSVehicle *const neighLeader)
void initLastLaneChangeOffset (int dir)
virtual bool predInteraction (const std::pair< MSVehicle *, double > &leader)
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
double myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
double myLastLateralGapLeft
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
double myLastLateralGapRight
double myLateralspeed
The lateral offset during a continuous LaneChangeManeuver.
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
std::map< int, std::pair< int, int > > mySavedStates
std::vector< MSLane * > myShadowFurtherLanes
std::vector< double > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCOutput
whether to record lane-changing
static const double NO_LATERAL_NEIGHBOR
Private Member Functions
MSAbstractLaneChangeModel & operator= (const MSAbstractLaneChangeModel &s)
Invalidated assignment operator.
Private Attributes
bool myAmOpposite
whether the vehicle is driving in the opposite direction
std::vector< MSLink * > myApproachedByShadow
links which are approached by the shadow vehicle
SUMOTime myLastLaneChangeOffset
Detailed Description
Interface for lane-change models.
Definition at line 51 of file MSAbstractLaneChangeModel.h.
Constructor & Destructor Documentation
MSAbstractLaneChangeModel::MSAbstractLaneChangeModel (MSVehicle & v, const LaneChangeModel model)
Constructor.
Parameters
[in] v The vehicle this lane-changer belongs to
[in] model The type of lane change model
Definition at line 86 of file MSAbstractLaneChangeModel.cpp.
Referenced by MSAbstractLaneChangeModel::StateAndDist::sameDirection().
MSAbstractLaneChangeModel::~MSAbstractLaneChangeModel () virtual
Destructor.
Definition at line 101 of file MSAbstractLaneChangeModel.cpp.
Referenced by MSAbstractLaneChangeModel::StateAndDist::sameDirection().
Member Function Documentation
bool MSAbstractLaneChangeModel::alreadyChanged () const inline
reset the flag whether a vehicle already moved to false
Definition at line 338 of file MSAbstractLaneChangeModel.h.
References myAlreadyChanged.
Referenced by MSLaneChanger::change().
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 63 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::sameDirection().
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected
whether the influencer cancels the given request
Definition at line 257 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and myVehicle.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), and setParameter().
virtual void MSAbstractLaneChangeModel::changed () pure virtual
Implemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Referenced by decideDirection(), and primaryLaneChanged().
void MSAbstractLaneChangeModel::changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
Definition at line 364 of file MSAbstractLaneChangeModel.cpp.
References myAlreadyChanged, and myAmOpposite.
Referenced by debugVehicle(), endLaneChangeManeuver(), MSVehicle::executeMove(), and startLaneChangeManeuver().
void MSAbstractLaneChangeModel::cleanupShadowLane ()
Definition at line 237 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), myNoPartiallyOccupatedByShadow, myShadowFurtherLanes, myShadowLane, myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by endLaneChangeManeuver(), resetChanged(), and MSVehicle::~MSVehicle().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual
Definition at line 114 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and myVehicle.
Referenced by setParameter(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
virtual bool MSAbstractLaneChangeModel::debugVehicle () const inline virtual
whether the current vehicles shall be debugged
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 265 of file MSAbstractLaneChangeModel.h.
References changedToOpposite().
Referenced by MSLaneChangerSublane::change(), MSLaneChangerSublane::startChangeSublane(), and updateShadowLane().
virtual StateAndDist MSAbstractLaneChangeModel::decideDirection (StateAndDist sd1, StateAndDist sd2) const inline virtual
decide in which direction to move in case both directions are desirable
Reimplemented in MSLCM_SL2015.
Definition at line 237 of file MSAbstractLaneChangeModel.h.
References changed(), inform(), max, min, myModel, patchSpeed(), toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE)
Definition at line 201 of file MSAbstractLaneChangeModel.cpp.
References changedToOpposite(), cleanupShadowLane(), MSVehicle::fixPosition(), myAmOpposite, myLaneChangeCompletion, myNoPartiallyOccupatedByShadow, myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::executeMove(), resetChanged(), and updateShadowLane().
double MSAbstractLaneChangeModel::getAngleOffset () const
return the angle offset during a continuous change maneuver
Definition at line 335 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, myLaneChangeDirection, pastMidpoint(), and STEPS2TIME.
Referenced by getLaneChangeDirection().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline
return the direction of the current lane change maneuver
Definition at line 322 of file MSAbstractLaneChangeModel.h.
References getAngleOffset(), getShadowDirection(), and myLaneChangeDirection.
Referenced by MSLaneChanger::continueChange().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline
Definition at line 303 of file MSAbstractLaneChangeModel.h.
References myLastLaneChangeOffset.
double MSAbstractLaneChangeModel::getLateralSpeed () const inline
return the lateral speed of the current lane change maneuver
Definition at line 333 of file MSAbstractLaneChangeModel.h.
References myLateralspeed.
Referenced by MSLaneChanger::continueChange().
int MSAbstractLaneChangeModel::getOwnState () const inline
Definition at line 152 of file MSAbstractLaneChangeModel.h.
References myOwnState, and setOwnState().
Referenced by MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), and MSVehicle::setBlinkerInformation().
virtual std::string MSAbstractLaneChangeModel::getParameter (const std::string & key) const inline virtual
try to retrieve the given parameter from this laneChangeModel. Throw exception for unsupported key
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 391 of file MSAbstractLaneChangeModel.h.
References myModel, and toString().
Referenced by TraCI_Vehicle::getParameter().
const std::pair<int, int>& MSAbstractLaneChangeModel::getSavedState (const int dir) const inline
Definition at line 158 of file MSAbstractLaneChangeModel.h.
References mySavedStates.
Referenced by TraCI_Vehicle::getLaneChangeState().
int MSAbstractLaneChangeModel::getShadowDirection () const
return the direction in which the current shadow lane lies
Definition at line 318 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), isChangingLanes(), myLaneChangeDirection, myShadowLane, myVehicle, and pastMidpoint().
Referenced by MSLaneChanger::continueChange(), MSVehicle::executeMove(), getLaneChangeDirection(), and GUIVehicle::selectBlockingFoes().
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline
Definition at line 295 of file MSAbstractLaneChangeModel.h.
References myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
const std::vector<double>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline
Definition at line 299 of file MSAbstractLaneChangeModel.h.
References myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 283 of file MSAbstractLaneChangeModel.h.
References myShadowLane.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), MSVehicle::isFrontOnLane(), MSVehicle::planMoveInternal(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and updateShadowLane().
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const
return the shadow lane for the given lane
Definition at line 215 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), isChangingLanes(), myLaneChangeCompletion, myNoPartiallyOccupatedByShadow, myVehicle, NUMERICAL_EPS, and SIMTIME.
virtual void* MSAbstractLaneChangeModel::inform (void * info, MSVehicle * sender) pure virtual
Implemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Referenced by decideDirection(), MSAbstractLaneChangeModel::MSLCMessager::informLeader(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), and MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader().
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static
init global model parameters
Definition at line 56 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), myAllowOvertakingRight, and myLCOutput.
Referenced by MSAbstractLaneChangeModel::StateAndDist::sameDirection(), and MSFrame::setMSGlobals().
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected
Definition at line 264 of file MSAbstractLaneChangeModel.cpp.
References myLastLaneChangeOffset.
Referenced by primaryLaneChanged().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline
return true if the vehicle currently performs a lane change maneuver
Definition at line 317 of file MSAbstractLaneChangeModel.h.
References myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), getShadowDirection(), getShadowLane(), and updateShadowLane().
bool MSAbstractLaneChangeModel::isOpposite () const inline
Definition at line 386 of file MSAbstractLaneChangeModel.h.
References myAmOpposite.
Referenced by MSLCM_LC2013::_wantsChange(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtInsertion(), MSLink::getLeaderInfo(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSLCM_LC2013::informLeader(), and MSVehicle::planMoveInternal().
MSAbstractLaneChangeModel& MSAbstractLaneChangeModel::operator= (const MSAbstractLaneChangeModel & s) private
Invalidated assignment operator.
bool MSAbstractLaneChangeModel::pastMidpoint () const inline
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 309 of file MSAbstractLaneChangeModel.h.
References myLaneChangeCompletion, and remainingTime().
Referenced by getAngleOffset(), getShadowDirection(), and updateCompletion().
virtual double MSAbstractLaneChangeModel::patchSpeed (const double min, const double wanted, const double max, const MSCFModel & cfModel) pure virtual
Called to adapt the speed in order to allow a lane change.
It is guaranteed that min<=wanted<=max, but the implementation needs to make sure that the return value is between min and max.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Referenced by decideDirection(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), and MSCFModel::moveHelper().
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, double > & leader) protected virtual
Definition at line 134 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), myCarFollowModel, and myVehicle.
Referenced by setParameter(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
virtual void MSAbstractLaneChangeModel::prepareStep () inline virtual
Reimplemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Definition at line 166 of file MSAbstractLaneChangeModel.h.
References LCA_UNKNOWN, and saveState().
Referenced by MSVehicle::executeMove(), MSLCM_DK2008::prepareStep(), MSLCM_LC2013::prepareStep(), and MSLCM_SL2015::prepareStep().
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction)
called once when the vehicles primary lane changes
Definition at line 166 of file MSAbstractLaneChangeModel.cpp.
References changed(), OutputDevice::closeTag(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getSpeed(), MSGlobals::gLateralResolution, initLastLaneChangeOffset(), LCA_LEFT, LCA_RIGHT, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), myLastLateralGapLeft, myLastLateralGapRight, myLCOutput, myOwnState, myVehicle, NO_LATERAL_NEIGHBOR, MSMoveReminder::NOTIFICATION_LANE_CHANGE, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, time2string(), toString(), and OutputDevice::writeAttr().
Referenced by MSLaneChanger::continueChange(), setNoShadowPartialOccupator(), and startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 342 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and myLaneChangeCompletion.
Referenced by pastMidpoint().
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const
Definition at line 354 of file MSAbstractLaneChangeModel.cpp.
References myApproachedByShadow, and myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::resetChanged () inline
reset the flag whether a vehicle already moved to false
Definition at line 343 of file MSAbstractLaneChangeModel.h.
References cleanupShadowLane(), endLaneChangeManeuver(), myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, startLaneChangeManeuver(), updateCompletion(), and updateShadowLane().
Referenced by MSVehicle::planMove().
virtual void MSAbstractLaneChangeModel::saveBlockerLength (double length) inline virtual
reserve space at the end of the lane to avoid dead locks
Reimplemented in MSLCM_LC2013, and MSLCM_SL2015.
Definition at line 367 of file MSAbstractLaneChangeModel.h.
References UNUSED_PARAMETER.
Referenced by MSLCM_LC2013::saveBlockerLength().
void MSAbstractLaneChangeModel::saveState (const int dir, const int stateWithoutTraCI, const int state) inline
Definition at line 162 of file MSAbstractLaneChangeModel.h.
References mySavedStates.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), and prepareStep().
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline
Definition at line 375 of file MSAbstractLaneChangeModel.h.
References myNoPartiallyOccupatedByShadow, primaryLaneChanged(), removeShadowApproachingInformation(), and setShadowApproachingInformation().
Referenced by MSVehicle::enterLaneAtLaneChange().
void MSAbstractLaneChangeModel::setOwnState (const int state) virtual
Reimplemented in MSLCM_SL2015.
Definition at line 105 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getInfluencer(), MSVehicle::hasInfluencer(), myOwnState, myVehicle, and MSVehicle::Influencer::setSublaneChange().
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), getOwnState(), and MSLCM_SL2015::setOwnState().
virtual void MSAbstractLaneChangeModel::setParameter (const std::string & key, const std::string & value) inline virtual
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 396 of file MSAbstractLaneChangeModel.h.
References cancelRequest(), congested(), myModel, predInteraction(), toString(), and UNUSED_PARAMETER.
Referenced by TraCI_Vehicle::setParameter().
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const
set approach information for the shadow vehicle
Definition at line 348 of file MSAbstractLaneChangeModel.cpp.
References myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline
set the shadow lane
Definition at line 291 of file MSAbstractLaneChangeModel.h.
References myShadowLane.
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline
Definition at line 371 of file MSAbstractLaneChangeModel.h.
References myPartiallyOccupatedByShadow.
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction)
start the lane change maneuver and return whether it continues
Definition at line 147 of file MSAbstractLaneChangeModel.cpp.
References changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, myLaneChangeDirection, myLateralspeed, myVehicle, primaryLaneChanged(), MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::changeOpposite(), resetChanged(), MSLaneChanger::startChange(), and MSLaneChangerSublane::startChangeSublane().
void MSAbstractLaneChangeModel::unchanged () inline
Definition at line 272 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
bool MSAbstractLaneChangeModel::updateCompletion ()
Definition at line 193 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, and pastMidpoint().
Referenced by MSLaneChanger::continueChange(), and resetChanged().
virtual void MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds (const MSLeaderInfo & ahead, int sublaneOffset, int laneIndex) inline virtual
update expected speeds for each sublane of the current edge
Reimplemented in MSLCM_SL2015.
Definition at line 229 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::updateShadowLane ()
Definition at line 273 of file MSAbstractLaneChangeModel.cpp.
References debugVehicle(), endLaneChangeManeuver(), MSLinkContHelper::getConnectingLink(), MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), getShadowLane(), isChangingLanes(), myShadowFurtherLanes, myShadowFurtherLanesPosLat, myShadowLane, myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), resetChanged(), and MSLaneChangerSublane::startChangeSublane().
virtual int MSAbstractLaneChangeModel::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, double > & leader, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) inline virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Definition at line 176 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChanger::checkChange().
virtual int MSAbstractLaneChangeModel::wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, double & latDist, int & blocked) inline virtual
Reimplemented in MSLCM_SL2015.
Definition at line 199 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::checkChangeSublane().
Field Documentation
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected
whether overtaking on the right is permitted
Definition at line 461 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), and initGlobalOptions().
bool MSAbstractLaneChangeModel::myAlreadyChanged protected
whether the vehicle has already moved this step
Definition at line 428 of file MSAbstractLaneChangeModel.h.
Referenced by alreadyChanged(), changedToOpposite(), and resetChanged().
bool MSAbstractLaneChangeModel::myAmOpposite private
whether the vehicle is driving in the opposite direction
Definition at line 478 of file MSAbstractLaneChangeModel.h.
Referenced by changedToOpposite(), endLaneChangeManeuver(), and isOpposite().
std::vector<MSLink*> MSAbstractLaneChangeModel::myApproachedByShadow mutable private
links which are approached by the shadow vehicle
Definition at line 475 of file MSAbstractLaneChangeModel.h.
Referenced by removeShadowApproachingInformation(), and setShadowApproachingInformation().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected
The vehicle's car following model.
Definition at line 439 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), predInteraction(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
double MSAbstractLaneChangeModel::myLaneChangeCompletion protected
progress of the lane change maneuver 0:started, 1:complete
Definition at line 419 of file MSAbstractLaneChangeModel.h.
Referenced by endLaneChangeManeuver(), getAngleOffset(), getShadowLane(), isChangingLanes(), pastMidpoint(), remainingTime(), startLaneChangeManeuver(), and updateCompletion().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 422 of file MSAbstractLaneChangeModel.h.
Referenced by getAngleOffset(), getLaneChangeDirection(), getShadowDirection(), and startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::myLastLaneChangeOffset private
Definition at line 472 of file MSAbstractLaneChangeModel.h.
Referenced by getLastLaneChangeOffset(), initLastLaneChangeOffset(), and unchanged().
double MSAbstractLaneChangeModel::myLastLateralGapLeft protected
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
Definition at line 452 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::prepareStep(), primaryLaneChanged(), and MSLCM_SL2015::updateGaps().
double MSAbstractLaneChangeModel::myLastLateralGapRight protected
Definition at line 453 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::prepareStep(), primaryLaneChanged(), and MSLCM_SL2015::updateGaps().
double MSAbstractLaneChangeModel::myLateralspeed protected
The lateral offset during a continuous LaneChangeManeuver.
Definition at line 425 of file MSAbstractLaneChangeModel.h.
Referenced by getLateralSpeed(), and startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLCOutput static protected
whether to record lane-changing
Definition at line 464 of file MSAbstractLaneChangeModel.h.
Referenced by initGlobalOptions(), and primaryLaneChanged().
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected
the type of this model
Definition at line 442 of file MSAbstractLaneChangeModel.h.
Referenced by decideDirection(), MSLCM_LC2013::getParameter(), MSLCM_SL2015::getParameter(), getParameter(), MSLCM_LC2013::setParameter(), MSLCM_SL2015::setParameter(), setParameter(), updateExpectedSublaneSpeeds(), wantsChange(), and wantsChangeSublane().
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected
Definition at line 449 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), endLaneChangeManeuver(), getShadowLane(), and setNoShadowPartialOccupator().
int MSAbstractLaneChangeModel::myOwnState protected
The current state of the vehicle.
Definition at line 415 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_DK2008::amBlockingFollower(), MSLCM_SL2015::amBlockingFollower(), MSLCM_LC2013::amBlockingFollower(), MSLCM_DK2008::amBlockingFollowerNB(), MSLCM_SL2015::amBlockingFollowerNB(), MSLCM_LC2013::amBlockingFollowerNB(), MSLCM_DK2008::amBlockingFollowerPlusNB(), MSLCM_SL2015::amBlockingFollowerPlusNB(), MSLCM_LC2013::amBlockingFollowerPlusNB(), MSLCM_DK2008::amBlockingLeader(), MSLCM_SL2015::amBlockingLeader(), MSLCM_LC2013::amBlockingLeader(), MSLCM_DK2008::changed(), MSLCM_LC2013::changed(), MSLCM_SL2015::changed(), getOwnState(), MSLCM_DK2008::inform(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_DK2008::patchSpeed(), MSLCM_DK2008::prepareStep(), MSLCM_LC2013::prepareStep(), MSLCM_SL2015::prepareStep(), primaryLaneChanged(), setOwnState(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected
list of lanes where the shadow vehicle is partial occupator
Definition at line 445 of file MSAbstractLaneChangeModel.h.
Referenced by setShadowPartialOccupator().
std::map<int, std::pair<int, int> > MSAbstractLaneChangeModel::mySavedStates protected
Definition at line 416 of file MSAbstractLaneChangeModel.h.
Referenced by getSavedState(), and saveState().
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected
Definition at line 435 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), getShadowFurtherLanes(), and updateShadowLane().
std::vector<double> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected
Definition at line 436 of file MSAbstractLaneChangeModel.h.
Referenced by getShadowFurtherLanesPosLat(), and updateShadowLane().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 431 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), getShadowDirection(), getShadowLane(), setShadowLane(), and updateShadowLane().
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected
The vehicle this lane-changer belongs to.
Definition at line 412 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), cancelRequest(), MSLCM_LC2013::changed(), MSLCM_SL2015::changed(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkStrategicChange(), cleanupShadowLane(), congested(), MSLCM_SL2015::decideDirection(), endLaneChangeManeuver(), MSLCM_LC2013::getRoundaboutAheadInfo(), getShadowDirection(), getShadowLane(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::msg(), MSLCM_LC2013::MSLCM_LC2013(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), predInteraction(), MSLCM_SL2015::prepareStep(), primaryLaneChanged(), removeShadowApproachingInformation(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::setOwnState(), setOwnState(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), startLaneChangeManeuver(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), updateShadowLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
const double MSAbstractLaneChangeModel::NO_LATERAL_NEIGHBOR static protected
Definition at line 466 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::prepareStep(), and primaryLaneChanged().
The documentation for this class was generated from the following files:
MSAbstractLaneChangeModel.h
MSAbstractLaneChangeModel.cpp