SUMO - Simulation of Urban MObility: netedit_main.cpp File Reference
netedit_main.cpp File Reference
#include <config.h>
#include <ctime>
#include <signal.h>
#include <iostream>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/FileHelpers.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/RandHelper.h>
#include <utils/xml/XMLSubSys.h>
#include <utils/gui/windows/GUIAppEnum.h>
#include <utils/gui/images/GUITexturesHelper.h>
#include <utils/gui/settings/GUICompleteSchemeStorage.h>
#include <utils/geom/GeoConvHelper.h>
#include <netimport/NIFrame.h>
#include <netbuild/NBFrame.h>
#include <netwrite/NWFrame.h>
#include "GNEApplicationWindow.h"
#include "GNELoadThread.h"
Functions
int main (int argc, char **argv)
Detailed Description
Author
Jakob Erdmann
Date
Feb 2011
Version
Id
netedit_main.cpp 23529 2017-03-18 10:22:36Z behrisch
Definition in file netedit_main.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 63 of file netedit_main.cpp.
References MsgHandler::assignLock(), SystemFrame::close(), GNEApplicationWindow::dependentBuild(), GNELoadThread::fillOptions(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), gSchemeStorage, MsgHandler::inform(), XMLSubSys::init(), GUICompleteSchemeStorage::init(), GNEApplicationWindow::loadOptionOnStartup(), MID_QUIT, OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), VERSION_STRING, and WRITE_ERROR.