SUMO - Simulation of Urban MObility: duarouter_main.cpp File Reference
duarouter_main.cpp File Reference
#include <config.h>
#include <xercesc/sax/SAXException.hpp>
#include <xercesc/sax/SAXParseException.hpp>
#include <utils/common/TplConvert.h>
#include <iostream>
#include <string>
#include <limits.h>
#include <ctime>
#include <router/ROLoader.h>
#include <router/RONet.h>
#include <router/ROEdge.h>
#include <utils/vehicle/DijkstraRouterTT.h>
#include <utils/vehicle/DijkstraRouterEffort.h>
#include <utils/vehicle/AStarRouter.h>
#include <utils/vehicle/CHRouter.h>
#include <utils/vehicle/CHRouterWrapper.h>
#include "RODUAEdgeBuilder.h"
#include <router/ROFrame.h>
#include <utils/common/MsgHandler.h>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/RandHelper.h>
#include <utils/common/ToString.h>
#include <utils/xml/XMLSubSys.h>
#include "RODUAFrame.h"
#include <utils/iodevices/OutputDevice.h>
Functions
void computeRoutes (RONet &net, ROLoader &loader, OptionsCont &oc)
void initNet (RONet &net, ROLoader &loader, OptionsCont &oc)
int main (int argc, char **argv)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Thu, 06 Jun 2002
Version
Id
duarouter_main.cpp 23529 2017-03-18 10:22:36Z behrisch
Definition in file duarouter_main.cpp.
Function Documentation
void computeRoutes (RONet & net, ROLoader & loader, OptionsCont & oc)
Computes the routes saving them
Definition at line 99 of file duarouter_main.cpp.
References RONet::adaptIntermodalRouter(), RONet::cleanup(), ROEdge::getAllEdges(), OptionsCont::getBool(), OptionsCont::getInt(), ROEdge::getNoiseEffort(), OptionsCont::getString(), ROEdge::getTravelTimeStatic(), RONet::hasPermissions(), OptionsCont::isSet(), max, RONet::openOutput(), ROLoader::openRoutes(), ROLoader::processRoutes(), string2time(), and SVC_IGNORING.
Referenced by main().
void initNet (RONet & net, ROLoader & loader, OptionsCont & oc)
loads the net The net is in this meaning made up by the net itself and the dynamic weights which may be supplied in a separate file
Definition at line 79 of file duarouter_main.cpp.
References OptionsCont::getBool(), OptionsCont::getString(), OptionsCont::isSet(), ROLoader::loadNet(), ROLoader::loadWeights(), and ROEdge::setGlobalOptions().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 203 of file duarouter_main.cpp.
References TplConvert::_2str(), RODUAFrame::checkOptions(), SystemFrame::close(), computeRoutes(), RODUAFrame::fillOptions(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), MsgHandler::inform(), XMLSubSys::init(), initNet(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), XMLSubSys::setValidation(), toString(), VERSION_STRING, and WRITE_ERROR.