SUMO - Simulation of Urban MObility: GNEChange_Lane Class Reference
GNEChange_Lane Class Reference
#include <GNEChange_Lane.h>
Public Member Functions
GNEChange_Lane (GNEEdge *edge, GNELane *lane, const NBEdge::Lane &laneAttrs, bool forward)
Constructor for creating/deleting an edge.
virtual FXuint size () const
return actual size
~GNEChange_Lane ()
Destructor.
inherited from GNEChange
get undo Name
FXString undoName () const
return undoName
FXString redoName () const
get Redo name
void undo ()
undo action
void redo ()
redo action
Protected Attributes
bool myForward
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
GNENet * myNet
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Private Attributes
std::vector< GNEAdditional * > myAdditionalChilds
we need to preserve the list of additionals vinculated with this lane
std::vector< GNEAdditional * > myAdditionalParents
we need to preserve the list of additional sets in which this lane is a child
GNEEdge * myEdge
we need the edge because it is the target of our change commands
GNELane * myLane
we need to preserve the lane because it maybe the target of GNEChange_Attribute commands
const NBEdge::Lane myLaneAttrs
we need to preserve the attributes explicitly because they are not contained withing GNELane itself
Detailed Description
A network change in which a single lane is created or deleted
Definition at line 52 of file GNEChange_Lane.h.
Constructor & Destructor Documentation
GNEChange_Lane::GNEChange_Lane (GNEEdge * edge, GNELane * lane, const NBEdge::Lane & laneAttrs, bool forward)
Constructor for creating/deleting an edge.
constructor for creating an edge
Parameters
[in] edge The edge on which to apply changes
[in] lane The lane to be deleted or 0 if a lane should be created
[in] laneAttrs The attributes of the lane to be created/deleted
[in] forward Whether to create/delete (true/false)
Definition at line 50 of file GNEChange_Lane.cpp.
GNEChange_Lane::~GNEChange_Lane ()
Destructor.
Definition at line 68 of file GNEChange_Lane.cpp.
References GNEReferenceCounter::decRef(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNEViewNet::isTestingModeEnabled(), myEdge, myLane, GNEChange::myNet, toString(), GNEReferenceCounter::unreferenced(), and WRITE_WARNING.
Member Function Documentation
void GNEChange_Lane::redo () virtual
redo action
Reimplemented from GNEChange.
Definition at line 128 of file GNEChange_Lane.cpp.
References GNEEdge::addLane(), GNENet::deleteAdditional(), GNEAttributeCarrier::getID(), GNENetElement::getNet(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNENet::insertAdditional(), GNEViewNet::isTestingModeEnabled(), myAdditionalChilds, myEdge, GNEChange::myForward, myLane, myLaneAttrs, GNEChange::myNet, GNEEdge::removeLane(), SUMO_TAG_LANE, toString(), and WRITE_WARNING.
FXString GNEChange_Lane::redoName () const virtual
get Redo name
Reimplemented from GNEChange.
Definition at line 174 of file GNEChange_Lane.cpp.
References GNEChange::myForward, SUMO_TAG_LANE, and toString().
FXuint GNEChange::size () const virtual inherited
return actual size
Definition at line 53 of file GNEChange.cpp.
void GNEChange_Lane::undo () virtual
undo action
Reimplemented from GNEChange.
Definition at line 92 of file GNEChange_Lane.cpp.
References GNEEdge::addLane(), GNENet::deleteAdditional(), GNEAttributeCarrier::getID(), GNENetElement::getNet(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNENet::insertAdditional(), GNEViewNet::isTestingModeEnabled(), myAdditionalChilds, myEdge, GNEChange::myForward, myLane, myLaneAttrs, GNEChange::myNet, GNEEdge::removeLane(), SUMO_TAG_LANE, toString(), and WRITE_WARNING.
FXString GNEChange_Lane::undoName () const virtual
return undoName
Reimplemented from GNEChange.
Definition at line 164 of file GNEChange_Lane.cpp.
References GNEChange::myForward, SUMO_TAG_LANE, and toString().
Field Documentation
std::vector<GNEAdditional*> GNEChange_Lane::myAdditionalChilds private
we need to preserve the list of additionals vinculated with this lane
Definition at line 94 of file GNEChange_Lane.h.
Referenced by redo(), and undo().
std::vector<GNEAdditional*> GNEChange_Lane::myAdditionalParents private
we need to preserve the list of additional sets in which this lane is a child
Definition at line 97 of file GNEChange_Lane.h.
GNEEdge* GNEChange_Lane::myEdge private
we need the edge because it is the target of our change commands
Definition at line 85 of file GNEChange_Lane.h.
Referenced by redo(), undo(), and ~GNEChange_Lane().
bool GNEChange::myForward protected inherited
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
Definition at line 87 of file GNEChange.h.
Referenced by GNEChange_Junction::redo(), GNEChange_Selection::redo(), GNEChange_TLS::redo(), GNEChange_Connection::redo(), redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), GNEChange_Junction::redoName(), GNEChange_Selection::redoName(), GNEChange_TLS::redoName(), GNEChange_Connection::redoName(), redoName(), GNEChange_Additional::redoName(), GNEChange_Edge::redoName(), GNEChange_Crossing::redoName(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), GNEChange_TLS::undo(), GNEChange_Connection::undo(), undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), GNEChange_Junction::undoName(), GNEChange_Selection::undoName(), GNEChange_TLS::undoName(), GNEChange_Connection::undoName(), undoName(), GNEChange_Additional::undoName(), GNEChange_Edge::undoName(), and GNEChange_Crossing::undoName().
GNELane* GNEChange_Lane::myLane private
we need to preserve the lane because it maybe the target of GNEChange_Attribute commands
Definition at line 88 of file GNEChange_Lane.h.
Referenced by redo(), undo(), and ~GNEChange_Lane().
const NBEdge::Lane GNEChange_Lane::myLaneAttrs private
we need to preserve the attributes explicitly because they are not contained withing GNELane itself
Definition at line 91 of file GNEChange_Lane.h.
Referenced by redo(), and undo().
GNENet* GNEChange::myNet protected inherited
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Definition at line 82 of file GNEChange.h.
Referenced by GNEChange_Junction::redo(), GNEChange_Selection::redo(), redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), GNEChange_Additional::~GNEChange_Additional(), ~GNEChange_Lane(), and GNEChange_TLS::~GNEChange_TLS().
The documentation for this class was generated from the following files:
GNEChange_Lane.h
GNEChange_Lane.cpp