SUMO - Simulation of Urban MObility: NIImporter_OpenStreetMap::Edge Struct Reference
NIImporter_OpenStreetMap::Edge Struct Reference
An internal definition of a loaded edge.
#include <NIImporter_OpenStreetMap.h>
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void clearParameter ()
Clears the parameter map.
Edge (long long int _id)
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void writeParams (OutputDevice &out) const
Data Fields
const long long int id
The edge's id.
WayType myBuswayType
Information about the kind of busway along this road.
bool myCurrentIsRoad
Information whether this is a road.
std::vector< long long int > myCurrentNodes
The list of nodes this edge is made of.
WayType myCyclewayType
Information about the kind of cycleway along this road.
std::string myHighWayType
The type, stored in "highway" key.
std::string myIsOneWay
Information whether this is an one-way road.
int myLayer
Information about the relative z-ordering of ways.
double myMaxSpeed
maximum speed in km/h, or MAXSPEED_UNGIVEN
int myNoLanes
number of lanes, or -1 if unknown
int myNoLanesForward
number of lanes in forward direction or 0 if unknown, negative if backwards lanes are meant
std::string streetName
The edge's street name.
Private Member Functions
Edge & operator= (const Edge &s)
invalidated assignment operator
Detailed Description
An internal definition of a loaded edge.
Definition at line 129 of file NIImporter_OpenStreetMap.h.
Constructor & Destructor Documentation
NIImporter_OpenStreetMap::Edge::Edge (long long int _id) inline
Definition at line 131 of file NIImporter_OpenStreetMap.h.
Member Function Documentation
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), TraCI_POI::addParameter(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenDrive::loadNetwork(), MSStateHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCI_Polygon::setParameter(), TraCI_Route::setParameter(), and TraCI_Lane::setParameter().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 65 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 99 of file Parameterised.cpp.
References Parameterised::myMap.
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 89 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 119 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NBTrafficLightDefinition::compute(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROPerson::saveAsXML(), and PointOfInterest::writeXML().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 79 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getLoggingFrequency(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), TraCI_Polygon::getParameter(), TraCI_VehicleType::getParameter(), TraCI_Route::getParameter(), TraCI_POI::getParameter(), TraCI_Lane::getParameter(), TraCI_Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), TraCIServerAPI_Vehicle::vtdMap(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 73 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getLoggingFrequency(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), and MSDevice_SSM::requestsTrajectories().
Edge& NIImporter_OpenStreetMap::Edge::operator= (const Edge & s) private
invalidated assignment operator
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 104 of file Parameterised.cpp.
References OutputDevice::closeTag(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MSVehicle::saveState(), SUMOVTypeParameter::write(), MSDevice_Vehroutes::writeOutput(), and SUMO::Polygon::writeXML().
Field Documentation
const long long int NIImporter_OpenStreetMap::Edge::id
The edge's id.
Definition at line 139 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::load(), NIImporter_OpenStreetMap::EdgesHandler::myEndElement(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
WayType NIImporter_OpenStreetMap::Edge::myBuswayType
Information about the kind of busway along this road.
Definition at line 155 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
bool NIImporter_OpenStreetMap::Edge::myCurrentIsRoad
Information whether this is a road.
Definition at line 161 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::load(), NIImporter_OpenStreetMap::EdgesHandler::myEndElement(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
std::vector<long long int> NIImporter_OpenStreetMap::Edge::myCurrentNodes
The list of nodes this edge is made of.
Definition at line 159 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::load(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::CompareEdges::operator()(), and NIImporter_OpenStreetMap::reconstructLayerElevation().
WayType NIImporter_OpenStreetMap::Edge::myCyclewayType
Information about the kind of cycleway along this road.
Definition at line 153 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
std::string NIImporter_OpenStreetMap::Edge::myHighWayType
The type, stored in "highway" key.
Definition at line 149 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
std::string NIImporter_OpenStreetMap::Edge::myIsOneWay
Information whether this is an one-way road.
Definition at line 151 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
int NIImporter_OpenStreetMap::Edge::myLayer
Information about the relative z-ordering of ways.
Definition at line 157 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::reconstructLayerElevation().
double NIImporter_OpenStreetMap::Edge::myMaxSpeed
maximum speed in km/h, or MAXSPEED_UNGIVEN
Definition at line 147 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
int NIImporter_OpenStreetMap::Edge::myNoLanes
number of lanes, or -1 if unknown
Definition at line 143 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
int NIImporter_OpenStreetMap::Edge::myNoLanesForward
number of lanes in forward direction or 0 if unknown, negative if backwards lanes are meant
Definition at line 145 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
std::string NIImporter_OpenStreetMap::Edge::streetName
The edge's street name.
Definition at line 141 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
The documentation for this struct was generated from the following file:
NIImporter_OpenStreetMap.h