SUMO - Simulation of Urban MObility: GNEVariableSpeedSignDialog Class Reference
GNEVariableSpeedSignDialog Class Reference
#include <GNEVariableSpeedSignDialog.h>
Public Member Functions
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNEVariableSpeedSignDialog (GNEVariableSpeedSign *variableSpeedSignParent)
FOX-declaration.
~GNEVariableSpeedSignDialog ()
destructor
FOX-callbacks
event called after press add row button
long onCmdAddRow (FXObject *, FXSelector, void *)
long onCmdRemoveRow (FXObject *, FXSelector, void *)
event called after press remove row
long onCmdAccept (FXObject *, FXSelector, void *)
event called after press accept button
long onCmdCancel (FXObject *, FXSelector, void *)
event called after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event called after press cancel button
Protected Member Functions
GNEVariableSpeedSignDialog ()
FOX needs this.
Protected Attributes
FXButton * myAcceptButton
accept button
FXButton * myAddRow
Button for insert row.
FXButton * myCancelButton
cancel button
FXVerticalFrame * myContentFrame
frame for contents
FXTable * myDataList
Table with the data.
FXButton * myResetButton
cancel button
FXHorizontalFrame * myRowFrame
Horizontal frame for row elements.
FXTextField * myRowSpeed
Text field with speed.
FXTextField * myRowStep
Text field with step
std::vector< GNEVariableSpeedSignStep > mySteps
Map with the temporal VSSValues.
GNEVariableSpeedSign * myVariableSpeedSignParent
Pointer to Variable Speed Signal.
Private Member Functions
GNEVariableSpeedSignDialog (const GNEVariableSpeedSignDialog &)
Invalidated copy constructor.
GNEVariableSpeedSignDialog & operator= (const GNEVariableSpeedSignDialog &)
Invalidated assignment operator.
void updateTable ()
update data table
Detailed Description
Definition at line 52 of file GNEVariableSpeedSignDialog.h.
Constructor & Destructor Documentation
GNEVariableSpeedSignDialog::GNEVariableSpeedSignDialog (GNEVariableSpeedSign * variableSpeedSignParent)
FOX-declaration.
constructor
Definition at line 58 of file GNEVariableSpeedSignDialog.cpp.
References GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonIcon, GUIDesignTableLimitedHeight, GUIDesignTextField, MID_GNE_VARIABLESPEEDSIGN_ADDROW, MID_GNE_VARIABLESPEEDSIGN_CHANGEVALUE, and MID_GNE_VARIABLESPEEDSIGN_REMOVEROW.
GNEVariableSpeedSignDialog::~GNEVariableSpeedSignDialog ()
destructor
Definition at line 88 of file GNEVariableSpeedSignDialog.cpp.
GNEVariableSpeedSignDialog::GNEVariableSpeedSignDialog () inline protected
FOX needs this.
Definition at line 83 of file GNEVariableSpeedSignDialog.h.
GNEVariableSpeedSignDialog::GNEVariableSpeedSignDialog (const GNEVariableSpeedSignDialog &) private
Invalidated copy constructor.
Member Function Documentation
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) inherited
change additional dialog header
Definition at line 81 of file GNEAdditionalDialog.cpp.
long GNEVariableSpeedSignDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
event called after press accept button
Implements GNEAdditionalDialog.
Definition at line 142 of file GNEVariableSpeedSignDialog.cpp.
References mySteps, myVariableSpeedSignParent, and GNEVariableSpeedSign::setVariableSpeedSignSteps().
long GNEVariableSpeedSignDialog::onCmdAddRow (FXObject * , FXSelector , void *)
Definition at line 93 of file GNEVariableSpeedSignDialog.cpp.
References myRowSpeed, myRowStep, mySteps, myVariableSpeedSignParent, GNEVariableSpeedSignStep::setSpeed(), GNEVariableSpeedSignStep::setTime(), and updateTable().
long GNEVariableSpeedSignDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event called after press cancel button
Implements GNEAdditionalDialog.
Definition at line 152 of file GNEVariableSpeedSignDialog.cpp.
long GNEVariableSpeedSignDialog::onCmdRemoveRow (FXObject * , FXSelector , void *)
event called after press remove row
Definition at line 125 of file GNEVariableSpeedSignDialog.cpp.
References myDataList, mySteps, and updateTable().
long GNEVariableSpeedSignDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event called after press cancel button
Implements GNEAdditionalDialog.
Definition at line 160 of file GNEVariableSpeedSignDialog.cpp.
References GNEVariableSpeedSign::getSteps(), mySteps, myVariableSpeedSignParent, and updateTable().
GNEVariableSpeedSignDialog& GNEVariableSpeedSignDialog::operator= (const GNEVariableSpeedSignDialog &) private
Invalidated assignment operator.
void GNEVariableSpeedSignDialog::updateTable () private
update data table
Definition at line 169 of file GNEVariableSpeedSignDialog.cpp.
References GUIIconSubSys::getIcon(), ICON_REMOVE, myDataList, mySteps, and toString().
Referenced by onCmdAddRow(), onCmdRemoveRow(), and onCmdReset().
Field Documentation
FXButton* GNEAdditionalDialog::myAcceptButton protected inherited
accept button
Definition at line 85 of file GNEAdditionalDialog.h.
FXButton* GNEVariableSpeedSignDialog::myAddRow protected
Button for insert row.
Definition at line 104 of file GNEVariableSpeedSignDialog.h.
FXButton* GNEAdditionalDialog::myCancelButton protected inherited
cancel button
Definition at line 88 of file GNEAdditionalDialog.h.
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 82 of file GNEAdditionalDialog.h.
FXTable* GNEVariableSpeedSignDialog::myDataList protected
Table with the data.
Definition at line 92 of file GNEVariableSpeedSignDialog.h.
Referenced by onCmdRemoveRow(), and updateTable().
FXButton* GNEAdditionalDialog::myResetButton protected inherited
cancel button
Definition at line 91 of file GNEAdditionalDialog.h.
FXHorizontalFrame* GNEVariableSpeedSignDialog::myRowFrame protected
Horizontal frame for row elements.
Definition at line 95 of file GNEVariableSpeedSignDialog.h.
FXTextField* GNEVariableSpeedSignDialog::myRowSpeed protected
Text field with speed.
Definition at line 101 of file GNEVariableSpeedSignDialog.h.
Referenced by onCmdAddRow().
FXTextField* GNEVariableSpeedSignDialog::myRowStep protected
Text field with step
Definition at line 98 of file GNEVariableSpeedSignDialog.h.
Referenced by onCmdAddRow().
std::vector<GNEVariableSpeedSignStep> GNEVariableSpeedSignDialog::mySteps protected
Map with the temporal VSSValues.
Definition at line 89 of file GNEVariableSpeedSignDialog.h.
Referenced by onCmdAccept(), onCmdAddRow(), onCmdRemoveRow(), onCmdReset(), and updateTable().
GNEVariableSpeedSign* GNEVariableSpeedSignDialog::myVariableSpeedSignParent protected
Pointer to Variable Speed Signal.
Definition at line 86 of file GNEVariableSpeedSignDialog.h.
Referenced by onCmdAccept(), onCmdAddRow(), and onCmdReset().
The documentation for this class was generated from the following files:
GNEVariableSpeedSignDialog.h
GNEVariableSpeedSignDialog.cpp