SUMO - Simulation of Urban MObility: MSRoute Class Reference
MSRoute Class Reference
#include <MSRoute.h>
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addReference () const
increments the reference counter for the route
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
MSRouteIterator begin () const
Returns the begin of the list of edges to pass.
void clearParameter ()
Clears the parameter map.
bool contains (const MSEdge *const edge) const
bool containsAnyOf (const MSEdgeVector &edgelist) const
MSRouteIterator end () const
Returns the end of the list of edges to pass.
const RGBColor & getColor () const
Returns the color.
double getCosts () const
Returns the costs of the route.
double getDistanceBetween (double fromPos, double toPos, const MSEdge *fromEdge, const MSEdge *toEdge, bool includeInternal=true) const
Compute the distance between 2 given edges on this route, including the length of internal lanes. Note, that for edges which contain loops:
double getDistanceBetween (double fromPos, double toPos, const MSRouteIterator &fromEdge, const MSRouteIterator &toEdge, bool includeInternal=true) const
Compute the distance between 2 given edges on this route, including the length of internal lanes. This has the same semantics as above but uses iterators instead of edge points so looping routes are not an issue.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const ConstMSEdgeVector & getEdges () const
const std::string & getID () const
Returns the id.
const MSEdge * getLastEdge () const
returns the destination edge
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
const std::vector< SUMOVehicleParameter::Stop > & getStops () const
Returns the stops.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSRoute (const std::string &id, const ConstMSEdgeVector &edges, const bool isPermanent, const RGBColor *const c, const std::vector< SUMOVehicleParameter::Stop > &stops)
Constructor.
const MSEdge * operator[] (int index) const
void release () const
deletes the route if there are no further references to it
void setCosts (double costs)
Sets the costs of the route.
void setID (const std::string &newID)
resets the id
int size () const
Returns the number of edges to pass.
int writeEdgeIDs (OutputDevice &os, const MSEdge *const from, const MSEdge *const upTo=0) const
Output the edge ids up to but not including the id of the given edge.
void writeParams (OutputDevice &out) const
virtual ~MSRoute ()
Destructor.
Static Public Member Functions
static void checkDist (const std::string &id)
Checks the distribution whether it is permanent and deletes it if not.
static void clear ()
Clears the dictionary (delete all known routes, too)
static bool dictionary (const std::string &id, const MSRoute *route)
Adds a route to the dictionary.
static bool dictionary (const std::string &id, RandomDistributor< const MSRoute * > *const routeDist, const bool permanent=true)
Adds a route distribution to the dictionary.
static const MSRoute * dictionary (const std::string &id, MTRand *rng=0)
Returns the named route or a sample from the named distribution.
static RandomDistributor< const MSRoute * > * distDictionary (const std::string &id)
Returns the named route distribution.
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static void insertIDs (std::vector< std::string > &into)
State I/O (mesosim only)
static void dict_saveState (OutputDevice &out)
Saves all known routes into the given stream.
Protected Attributes
std::string myID
The name of the object.
Private Types
typedef std::map< std::string, const MSRoute * > RouteDict
Definition of the dictionary container.
typedef std::map< std::string, std::pair< RandomDistributor< const MSRoute * > *, bool > > RouteDistDict
Definition of the dictionary container.
Private Member Functions
MSRoute & operator= (const MSRoute &s)
Private Attributes
const bool myAmPermanent
whether the route may be deleted after the last vehicle abandoned it
const RGBColor *const myColor
The color.
double myCosts
The assigned or calculated costs.
ConstMSEdgeVector myEdges
The list of edges to pass.
int myReferenceCounter
Information by how many vehicles the route is used.
std::vector< SUMOVehicleParameter::Stop > myStops
List of the stops on the parsed route.
Static Private Attributes
static RouteDict myDict
The dictionary container.
static RouteDistDict myDistDict
The dictionary container.
Detailed Description
Definition at line 74 of file MSRoute.h.
Member Typedef Documentation
typedef std::map<std::string, const MSRoute*> MSRoute::RouteDict private
Definition of the dictionary container.
Definition at line 253 of file MSRoute.h.
typedef std::map<std::string, std::pair<RandomDistributor<const MSRoute*>*, bool> > MSRoute::RouteDistDict private
Definition of the dictionary container.
Definition at line 259 of file MSRoute.h.
Constructor & Destructor Documentation
MSRoute::MSRoute (const std::string & id, const ConstMSEdgeVector & edges, const bool isPermanent, const RGBColor *const c, const std::vector< SUMOVehicleParameter::Stop > & stops)
Constructor.
Definition at line 59 of file MSRoute.cpp.
MSRoute::~MSRoute () virtual
Destructor.
Definition at line 68 of file MSRoute.cpp.
References myColor.
Member Function Documentation
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), TraCI_POI::addParameter(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenDrive::loadNetwork(), MSStateHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCI_Polygon::setParameter(), TraCI_Route::setParameter(), and TraCI_Lane::setParameter().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 65 of file Parameterised.cpp.
References Parameterised::myMap.
void MSRoute::addReference () const
increments the reference counter for the route
Definition at line 99 of file MSRoute.cpp.
References myReferenceCounter.
Referenced by MSDevice_Vehroutes::addRoute(), MSRouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSBaseVehicle::MSBaseVehicle(), MSDevice_Vehroutes::MSDevice_Vehroutes(), MSRouteProbe::notifyEnter(), MSRouteHandler::openRouteDistribution(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), and MSBaseVehicle::replaceRouteEdges().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
MSRouteIterator MSRoute::begin () const
Returns the begin of the list of edges to pass.
Definition at line 74 of file MSRoute.cpp.
References myEdges.
Referenced by MSRouteHandler::closeVehicle(), MSDevice_Tripinfo::computeLengthAndDuration(), GUIVehicle::drawRouteHelper(), GUIMEVehicle::drawRouteHelper(), MSCalibrator::execute(), MSEdge::getDepartLane(), TraCI_Vehicle::getEdges(), MSVehicle::getRoutePosition(), MSBaseVehicle::hasValidRoute(), MSLane::isInsertionSuccess(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::Influencer::postProcessVTD(), MSDevice_Routing::preInsertionReroute(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSDevice_Vehroutes::writeOutput(), MSRouteProbe::writeXMLOutput(), and MSDevice_Vehroutes::writeXMLRoute().
void MSRoute::checkDist (const std::string & id) static
Checks the distribution whether it is permanent and deletes it if not.
Definition at line 190 of file MSRoute.cpp.
References myDistDict.
Referenced by MSInsertionControl::determineCandidates(), setCosts(), MSRouteProbe::writeXMLOutput(), and MSBaseVehicle::~MSBaseVehicle().
void MSRoute::clear () static
Clears the dictionary (delete all known routes, too)
Definition at line 174 of file MSRoute.cpp.
References myDict, and myDistDict.
Referenced by MSNet::clearAll(), and setCosts().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 99 of file Parameterised.cpp.
References Parameterised::myMap.
bool MSRoute::contains (const MSEdge *const edge) const inline
Definition at line 110 of file MSRoute.h.
References containsAnyOf(), dict_saveState(), myEdges, and operator[]().
Referenced by containsAnyOf(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSVehicle::replaceRoute(), and MEVehicle::replaceRoute().
bool MSRoute::containsAnyOf (const MSEdgeVector & edgelist) const
Definition at line 243 of file MSRoute.cpp.
References contains().
Referenced by contains(), MSTriggeredRerouter::getCurrentReroute(), and MSTriggeredRerouter::notifyEnter().
void MSRoute::dict_saveState (OutputDevice & out) static
Saves all known routes into the given stream.
Parameters
[in] os The stream to write the routes into (binary)
Definition at line 261 of file MSRoute.cpp.
References OutputDevice::closeTag(), myDict, myDistDict, OutputDevice::openTag(), SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROBS, SUMO_ATTR_ROUTES, SUMO_ATTR_STATE, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, and OutputDevice::writeAttr().
Referenced by contains(), and MSStateHandler::saveState().
bool MSRoute::dictionary (const std::string & id, const MSRoute * route) static
Adds a route to the dictionary.
Returns true if the route could be added, false if a route (distribution) with the same name already exists.
Parameters
[in] id the id for the new route
[in] route pointer to the route object
Returns
whether adding was successful
Definition at line 118 of file MSRoute.cpp.
References myDict, and myDistDict.
Referenced by TraCI_Route::add(), MSRouteHandler::closeFlow(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), TraCI_Route::getRoute(), MSDevice_Vehroutes::loadState(), MSRouteProbe::MSRouteProbe(), MSTriggeredRerouter::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::replaceRouteEdges(), setCosts(), and MSRouteProbe::writeXMLOutput().
bool MSRoute::dictionary (const std::string & id, RandomDistributor< const MSRoute * > *const routeDist, const bool permanent = true) static
Adds a route distribution to the dictionary.
Returns true if the distribution could be added, false if a route (distribution) with the same name already exists.
Parameters
[in] id the id for the new route distribution
[in] routeDist pointer to the distribution object
[in] permanent whether the new route distribution survives more than one vehicle / flow
Returns
whether adding was successful
Definition at line 131 of file MSRoute.cpp.
References myDict, and myDistDict.
const MSRoute * MSRoute::dictionary (const std::string & id, MTRand * rng = 0) static
Returns the named route or a sample from the named distribution.
Returns 0 if no route and no distribution with the given name exists or if the distribution exists and is empty.
Parameters
[in] id the id of the route or the distribution
Returns
the route (sample)
Definition at line 144 of file MSRoute.cpp.
References myDict, and myDistDict.
RandomDistributor< const MSRoute * > * MSRoute::distDictionary (const std::string & id) static
Returns the named route distribution.
Returns 0 if no route distribution with the given name exists.
Parameters
[in] id the id of the route distribution
Returns
the route distribution
Definition at line 161 of file MSRoute.cpp.
References myDistDict.
Referenced by MSRouteProbe::MSRouteProbe(), setCosts(), and MSDevice_Vehroutes::writeOutput().
MSRouteIterator MSRoute::end () const
Returns the end of the list of edges to pass.
Definition at line 80 of file MSRoute.cpp.
References myEdges.
Referenced by MSVehicle::addStop(), GUIVehicle::drawRouteHelper(), GUIMEVehicle::drawRouteHelper(), MSCalibrator::execute(), MSVehicle::executeMove(), MSDevice_Tripinfo::generateOutput(), getDistanceBetween(), TraCI_Vehicle::getEdges(), MSVehicle::getRerouteOrigin(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::resetRoutePosition(), MSVehicle::updateBestLanes(), MSVehicle::willPass(), and MSRouteProbe::writeXMLOutput().
const RGBColor & MSRoute::getColor () const
Returns the color.
Definition at line 341 of file MSRoute.cpp.
References RGBColor::DEFAULT_COLOR, and myColor.
Referenced by getEdges(), MSBaseVehicle::replaceRouteEdges(), MSTriggeredRerouter::rerouteParkingZone(), and GUIBaseVehicle::setFunctionalColor().
double MSRoute::getCosts () const inline
Returns the costs of the route.
Returns
The route's costs (normally the time needed to pass it)
Definition at line 166 of file MSRoute.h.
References myCosts.
double MSRoute::getDistanceBetween (double fromPos, double toPos, const MSEdge * fromEdge, const MSEdge * toEdge, bool includeInternal = true) const
Compute the distance between 2 given edges on this route, including the length of internal lanes. Note, that for edges which contain loops:
the first occurance of fromEdge will be used
the first occurance of toEdge after the first occurance of fromEdge will be used
Parameters
[in] fromPos position on the first edge, at wich the computed distance begins
[in] toPos position on the last edge, at which the coumputed distance endsance
[in] fromEdge edge at wich computation begins
[in] toEdge edge at which distance computation shall stop
[in] includeInternal Whether the lengths of internal edges shall be counted
Returns
distance between the position fromPos on fromEdge and toPos on toEdge
Definition at line 281 of file MSRoute.cpp.
References max, and myEdges.
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), MSDevice_Tripinfo::computeLengthAndDuration(), TraCI_Vehicle::getDistance(), MSVehicle::getDistanceToPosition(), TraCI_Vehicle::getDrivingDistance(), TraCI_Vehicle::getDrivingDistance2D(), getEdges(), MSTriggeredRerouter::rerouteParkingZone(), and MSDevice_Vehroutes::writeOutput().
double MSRoute::getDistanceBetween (double fromPos, double toPos, const MSRouteIterator & fromEdge, const MSRouteIterator & toEdge, bool includeInternal = true) const
Compute the distance between 2 given edges on this route, including the length of internal lanes. This has the same semantics as above but uses iterators instead of edge points so looping routes are not an issue.
Parameters
[in] fromPos position on the first edge, at wich the computed distance begins
[in] toPos position on the last edge, at which the coumputed distance endsance
[in] fromEdge edge at wich computation begins
[in] toEdge edge at which distance computation shall stop
[in] includeInternal Whether the lengths of internal edges shall be counted
Returns
distance between the position fromPos on fromEdge and toPos on toEdge
Definition at line 303 of file MSRoute.cpp.
References end(), MSEdge::getInternalFollowingEdge(), MSEdge::getLength(), and max.
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 89 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
const ConstMSEdgeVector& MSRoute::getEdges () const inline
Definition at line 128 of file MSRoute.h.
References getColor(), getDistanceBetween(), and myEdges.
Referenced by MSRouteHandler::closeVehicle(), TraCI_Vehicle::getDistance(), TraCI_Route::getEdges(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), GUIBaseVehicle::setFunctionalColor(), TraCIServerAPI_Vehicle::vtdMap(), and TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), MSNet::addParkingArea(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), TraCI_Vehicle::getBestLanes(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), TraCI_Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), TraCI_Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), TraCI_Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSNet::getParkingAreaID(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), TraCI_Vehicle::getRoadID(), TraCI_Vehicle::getRouteID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_SSM::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSDevice_SSM::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_SSM::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingZone(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), toString(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSDevice_SSM::updateEncounter(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSPModel_Striping::PState::moveToNextLane(), operator<<(), TraCIServerAPI_Vehicle::processSet(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), MSAbstractLaneChangeModel::updateShadowLane(), and TraCIServerAPI_Vehicle::vtdMap().
const MSEdge * MSRoute::getLastEdge () const
returns the destination edge
Definition at line 92 of file MSRoute.cpp.
References myEdges.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSBaseVehicle::calculateArrivalParams(), MSLane::isInsertionSuccess(), MSBaseVehicle::MSBaseVehicle(), MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::preInsertionReroute(), MSBaseVehicle::reroute(), and MSTriggeredRerouter::rerouteParkingZone().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 119 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NBTrafficLightDefinition::compute(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROPerson::saveAsXML(), and PointOfInterest::writeXML().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 79 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getLoggingFrequency(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), TraCI_Polygon::getParameter(), TraCI_VehicleType::getParameter(), TraCI_Route::getParameter(), TraCI_POI::getParameter(), TraCI_Lane::getParameter(), TraCI_Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), TraCIServerAPI_Vehicle::vtdMap(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
const std::vector< SUMOVehicleParameter::Stop > & MSRoute::getStops () const
Returns the stops.
Definition at line 350 of file MSRoute.cpp.
References myStops.
Referenced by MSBaseVehicle::addStops(), MSVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSTriggeredRerouter::rerouteParkingZone(), setCosts(), and MSDevice_Vehroutes::writeOutput().
void MSRoute::insertIDs (std::vector< std::string > & into) static
Definition at line 207 of file MSRoute.cpp.
References myDict, and myDistDict.
Referenced by TraCI_Route::getIDList(), and setCosts().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 73 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getLoggingFrequency(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), and MSDevice_SSM::requestsTrajectories().
MSRoute& MSRoute::operator= (const MSRoute & s) private
invalid assignment operator
const MSEdge * MSRoute::operator[] (int index) const
Definition at line 255 of file MSRoute.cpp.
References myEdges.
Referenced by contains().
void MSRoute::release () const
deletes the route if there are no further references to it
Definition at line 105 of file MSRoute.cpp.
References myDict, Named::myID, and myReferenceCounter.
Referenced by MSDevice_Vehroutes::addRoute(), MSRouteHandler::closeVehicle(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::~MSBaseVehicle(), and MSDevice_Vehroutes::~MSDevice_Vehroutes().
void MSRoute::setCosts (double costs) inline
Sets the costs of the route.
Parameters
[in] costs The new route costs
Definition at line 174 of file MSRoute.h.
References checkDist(), clear(), dictionary(), distDictionary(), getStops(), insertIDs(), and myCosts.
Referenced by MSRouteHandler::closeRoute().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::Distribution_Parameterized(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
int MSRoute::size () const
Returns the number of edges to pass.
Definition at line 86 of file MSRoute.cpp.
References myEdges.
Referenced by GUIVehicle::drawRouteHelper(), MSEdge::getDepartLane(), MSBaseVehicle::replaceRouteEdges(), and MSDevice_Vehroutes::writeXMLRoute().
int MSRoute::writeEdgeIDs (OutputDevice & os, const MSEdge *const from, const MSEdge *const upTo = 0) const
Output the edge ids up to but not including the id of the given edge.
Parameters
[in] os The stream to write the routes into (binary)
[in] from The first edge to be written
[in] upTo The first edge that shall not be written
Returns
The number of edges written
Definition at line 222 of file MSRoute.cpp.
References myEdges.
Referenced by MSDevice_Vehroutes::writeXMLRoute().
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 104 of file Parameterised.cpp.
References OutputDevice::closeTag(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MSVehicle::saveState(), SUMOVTypeParameter::write(), MSDevice_Vehroutes::writeOutput(), and SUMO::Polygon::writeXML().
Field Documentation
const bool MSRoute::myAmPermanent private
whether the route may be deleted after the last vehicle abandoned it
Definition at line 237 of file MSRoute.h.
const RGBColor* const MSRoute::myColor private
The color.
Definition at line 243 of file MSRoute.h.
Referenced by getColor(), and ~MSRoute().
double MSRoute::myCosts private
The assigned or calculated costs.
Definition at line 246 of file MSRoute.h.
Referenced by getCosts(), and setCosts().
MSRoute::RouteDict MSRoute::myDict static private
The dictionary container.
Definition at line 256 of file MSRoute.h.
Referenced by clear(), dict_saveState(), dictionary(), insertIDs(), and release().
MSRoute::RouteDistDict MSRoute::myDistDict static private
The dictionary container.
Definition at line 262 of file MSRoute.h.
Referenced by checkDist(), clear(), dict_saveState(), dictionary(), distDictionary(), and insertIDs().
ConstMSEdgeVector MSRoute::myEdges private
The list of edges to pass.
Definition at line 234 of file MSRoute.h.
Referenced by begin(), contains(), end(), getDistanceBetween(), getEdges(), getLastEdge(), operator[](), size(), and writeEdgeIDs().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
int MSRoute::myReferenceCounter mutable private
Information by how many vehicles the route is used.
Definition at line 240 of file MSRoute.h.
Referenced by addReference(), and release().
std::vector<SUMOVehicleParameter::Stop> MSRoute::myStops private
List of the stops on the parsed route.
Definition at line 249 of file MSRoute.h.
Referenced by getStops().
The documentation for this class was generated from the following files:
MSRoute.h
MSRoute.cpp