SUMO - Simulation of Urban MObility: TraCIAPI Class Reference
TraCIAPI Class Reference
C++ TraCI client API implementation.
#include <TraCIAPI.h>
Data Structures
class EdgeScope
Scope for interaction with edges.
class GUIScope
Scope for interaction with the gui.
class InductionLoopScope
Scope for interaction with inductive loops.
class JunctionScope
Scope for interaction with junctions.
class LaneAreaScope
Scope for interaction with lane area detectors.
class LaneScope
Scope for interaction with lanes.
class MeMeScope
Scope for interaction with multi entry/-exit detectors.
class PersonScope
Scope for interaction with vehicles.
class POIScope
Scope for interaction with POIs.
class PolygonScope
Scope for interaction with polygons.
class RouteScope
Scope for interaction with routes.
class SimulationScope
Scope for interaction with the simulation.
class TraCIScopeWrapper
An abstract interface for accessing type-dependent values.
class TrafficLightScope
Scope for interaction with traffic lights.
class VehicleScope
Scope for interaction with vehicles.
class VehicleTypeScope
Scope for interaction with vehicle types.
Public Types
typedef std::map< std::string, SubscribedValues > SubscribedContextValues
typedef std::map< std::string, TraCIValues > SubscribedValues
typedef std::map< int, TraCIValue > TraCIValues
{object->{variable->value}}
Public Member Functions
void load (const std::vector< std::string > &args)
Let sumo load a simulation using the given command line like options.
void simulationStep (SUMOTime time=0)
Advances by one step (or up to the given time)
TraCIAPI ()
Constructor.
~TraCIAPI ()
Destructor.
Connection handling
void connect (const std::string &host, int port)
Connects to the specified SUMO server.
void close ()
ends the simulation and closes the connection
Atomar getter
SUMOTime getSUMOTime (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
int getUnsignedByte (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
int getByte (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
int getInt (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
double getFloat (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
double getDouble (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
TraCIBoundary getBoundingBox (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
TraCIPositionVector getPolygon (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
TraCIPosition getPosition (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
std::string getString (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
std::vector< std::string > getStringVector (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
TraCIColor getColor (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
Data Fields
EdgeScope edge
Scope for interaction with edges.
GUIScope gui
Scope for interaction with the gui.
InductionLoopScope inductionloop
Scope for interaction with inductive loops.
JunctionScope junction
Scope for interaction with junctions.
LaneScope lane
Scope for interaction with lanes.
LaneAreaScope lanearea
Scope for interaction with lanes.
MeMeScope multientryexit
Scope for interaction with multi-entry/-exit detectors.
PersonScope person
Scope for interaction with persons.
POIScope poi
Scope for interaction with POIs.
PolygonScope polygon
Scope for interaction with polygons.
RouteScope route
Scope for interaction with routes.
SimulationScope simulation
Scope for interaction with the simulation.
TrafficLightScope trafficlights
Scope for interaction with traffic lights.
VehicleScope vehicle
Scope for interaction with vehicles.
VehicleTypeScope vehicletype
Scope for interaction with vehicle types.
Protected Member Functions
void closeSocket ()
Closes the connection.
void readContextSubscription (tcpip::Storage &inMsg)
void readVariables (tcpip::Storage &inMsg, const std::string &objectID, int variableCount, SubscribedValues &into)
void readVariableSubscription (tcpip::Storage &inMsg)
void send_commandMoveToXY (const std::string &vehicleID, const std::string &edgeID, const int lane, const double x, const double y, const double angle, const int keepRoute) const
Command sending methods
void send_commandSimulationStep (SUMOTime time) const
Sends a SimulationStep command.
void send_commandClose () const
Sends a Close command.
void send_commandGetVariable (int domID, int varID, const std::string &objID, tcpip::Storage *add=0) const
Sends a GetVariable request.
void send_commandSetValue (int domID, int varID, const std::string &objID, tcpip::Storage &content) const
Sends a SetVariable request.
void send_commandSubscribeObjectVariable (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars) const
Sends a SubscribeVariable request.
void send_commandSubscribeObjectContext (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars) const
Sends a SubscribeContext request.
void check_resultState (tcpip::Storage &inMsg, int command, bool ignoreCommandId=false, std::string *acknowledgement=0) const
Validates the result state of a command.
int check_commandGetResult (tcpip::Storage &inMsg, int command, int expectedType=-1, bool ignoreCommandId=false) const
Validates the result state of a command.
void processGET (tcpip::Storage &inMsg, int command, int expectedType, bool ignoreCommandId=false) const
Static Protected Member Functions
template<class T >
static std::string toString (const T &t, std::streamsize accuracy=PRECISION)
Protected Attributes
tcpip::Socket * mySocket
The socket.
SubscribedContextValues mySubscribedContextValues
SubscribedValues mySubscribedValues
Detailed Description
C++ TraCI client API implementation.
Definition at line 63 of file TraCIAPI.h.
Member Typedef Documentation
typedef std::map<std::string, SubscribedValues> TraCIAPI::SubscribedContextValues
Definition at line 467 of file TraCIAPI.h.
typedef std::map<std::string, TraCIValues> TraCIAPI::SubscribedValues
Definition at line 466 of file TraCIAPI.h.
typedef std::map<int, TraCIValue> TraCIAPI::TraCIValues
{object->{variable->value}}
Definition at line 465 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::TraCIAPI ()
Constructor.
Definition at line 48 of file TraCIAPI.cpp.
TraCIAPI::~TraCIAPI ()
Destructor.
Definition at line 60 of file TraCIAPI.cpp.
References mySocket.
Member Function Documentation
int TraCIAPI::check_commandGetResult (tcpip::Storage & inMsg, int command, int expectedType = -1, bool ignoreCommandId = false) const protected
Validates the result state of a command.
Returns
The command Id
Definition at line 289 of file TraCIAPI.cpp.
References tcpip::Storage::position(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), and toString().
Referenced by TraCITestClient::commandGetVariable(), processGET(), and simulationStep().
void TraCIAPI::check_resultState (tcpip::Storage & inMsg, int command, bool ignoreCommandId = false, std::string * acknowledgement = 0) const protected
Validates the result state of a command.
Parameters
[in] inMsg The buffer to read the message from
[in] command The original command id
[in] ignoreCommandId Whether the returning command id shall be validated
[in] acknowledgement Pointer to an existing string into which the acknowledgement message shall be inserted
Definition at line 250 of file TraCIAPI.cpp.
References mySocket, tcpip::Storage::position(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), tcpip::Socket::receiveExact(), RTYPE_ERR, RTYPE_NOTIMPLEMENTED, RTYPE_OK, and toString().
Referenced by close(), TraCITestClient::commandClose(), TraCITestClient::commandGetVariable(), TraCITestClient::commandSetValue(), TraCITestClient::commandSimulationStep(), TraCITestClient::commandSubscribeContextVariable(), TraCITestClient::commandSubscribeObjectVariable(), load(), processGET(), and simulationStep().
void TraCIAPI::close ()
ends the simulation and closes the connection
Definition at line 79 of file TraCIAPI.cpp.
References check_resultState(), closeSocket(), CMD_CLOSE, and send_commandClose().
void TraCIAPI::closeSocket () protected
Closes the connection.
Definition at line 89 of file TraCIAPI.cpp.
References tcpip::Socket::close(), and mySocket.
Referenced by close(), TraCITestClient::run(), and toString().
void TraCIAPI::connect (const std::string & host, int port)
Connects to the specified SUMO server.
Parameters
[in] host The name of the host to connect to
[in] port The port to connect to
Exceptions
tcpip::SocketException if the connection fails
Definition at line 66 of file TraCIAPI.cpp.
References tcpip::Socket::connect(), and mySocket.
Referenced by TraCITestClient::run().
TraCIBoundary TraCIAPI::getBoundingBox (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 376 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readDouble(), send_commandGetVariable(), TYPE_BOUNDINGBOX, TraCIBoundary::xMax, TraCIBoundary::xMin, TraCIBoundary::yMax, TraCIBoundary::yMin, TraCIBoundary::zMax, and TraCIBoundary::zMin.
int TraCIAPI::getByte (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 340 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readByte(), send_commandGetVariable(), and TYPE_BYTE.
TraCIColor TraCIAPI::getColor (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 446 of file TraCIAPI.cpp.
References TraCIColor::a, TraCIColor::b, TraCIColor::g, processGET(), TraCIColor::r, tcpip::Storage::readUnsignedByte(), send_commandGetVariable(), and TYPE_COLOR.
Referenced by TraCIAPI::POIScope::~POIScope(), TraCIAPI::PolygonScope::~PolygonScope(), and TraCIAPI::VehicleTypeScope::~VehicleTypeScope().
double TraCIAPI::getDouble (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 367 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readDouble(), send_commandGetVariable(), and TYPE_DOUBLE.
double TraCIAPI::getFloat (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 358 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readFloat(), send_commandGetVariable(), and TYPE_FLOAT.
int TraCIAPI::getInt (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 349 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readInt(), send_commandGetVariable(), and TYPE_INTEGER.
TraCIPositionVector TraCIAPI::getPolygon (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 392 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readByte(), tcpip::Storage::readDouble(), send_commandGetVariable(), TYPE_POLYGON, TraCIPosition::x, TraCIPosition::y, and TraCIPosition::z.
TraCIPosition TraCIAPI::getPosition (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 410 of file TraCIAPI.cpp.
References POSITION_2D, processGET(), tcpip::Storage::readDouble(), send_commandGetVariable(), TraCIPosition::x, TraCIPosition::y, and TraCIPosition::z.
Referenced by TraCIAPI::InductionLoopScope::~InductionLoopScope(), TraCIAPI::JunctionScope::~JunctionScope(), TraCIAPI::PersonScope::~PersonScope(), and TraCIAPI::POIScope::~POIScope().
std::string TraCIAPI::getString (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 423 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readString(), send_commandGetVariable(), and TYPE_STRING.
std::vector< std::string > TraCIAPI::getStringVector (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 432 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readInt(), tcpip::Storage::readString(), send_commandGetVariable(), and TYPE_STRINGLIST.
SUMOTime TraCIAPI::getSUMOTime (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 322 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readInt(), send_commandGetVariable(), and TYPE_INTEGER.
int TraCIAPI::getUnsignedByte (int cmd, int var, const std::string & id, tcpip::Storage * add = 0)
Definition at line 331 of file TraCIAPI.cpp.
References processGET(), tcpip::Storage::readUnsignedByte(), send_commandGetVariable(), and TYPE_UBYTE.
void TraCIAPI::load (const std::vector< std::string > & args)
Let sumo load a simulation using the given command line like options.
Definition at line 562 of file TraCIAPI.cpp.
References check_resultState(), CMD_LOAD, mySocket, tcpip::Socket::sendExact(), TYPE_STRINGLIST, tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
void TraCIAPI::processGET (tcpip::Storage & inMsg, int command, int expectedType, bool ignoreCommandId = false) const protected
Definition at line 313 of file TraCIAPI.cpp.
References check_commandGetResult(), and check_resultState().
Referenced by getBoundingBox(), getByte(), getColor(), getDouble(), getFloat(), getInt(), getPolygon(), getPosition(), getString(), getStringVector(), getSUMOTime(), and getUnsignedByte().
void TraCIAPI::readContextSubscription (tcpip::Storage & inMsg) protected
Definition at line 527 of file TraCIAPI.cpp.
References mySubscribedContextValues, tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), and readVariables().
Referenced by simulationStep().
void TraCIAPI::readVariables (tcpip::Storage & inMsg, const std::string & objectID, int variableCount, SubscribedValues & into) protected
Definition at line 459 of file TraCIAPI.cpp.
References TraCIColor::a, TraCIColor::b, TraCIValue::color, TraCIColor::g, TraCIValue::position, POSITION_2D, POSITION_3D, TraCIColor::r, tcpip::Storage::readDouble(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RTYPE_OK, TraCIValue::scalar, TraCIValue::string, TraCIValue::stringList, toString(), TYPE_COLOR, TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, TraCIPosition::x, TraCIPosition::y, and TraCIPosition::z.
Referenced by readContextSubscription(), and readVariableSubscription().
void TraCIAPI::readVariableSubscription (tcpip::Storage & inMsg) protected
Definition at line 520 of file TraCIAPI.cpp.
References mySubscribedValues, tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), and readVariables().
Referenced by simulationStep().
void TraCIAPI::send_commandClose () const protected
Sends a Close command.
Definition at line 113 of file TraCIAPI.cpp.
References CMD_CLOSE, mySocket, tcpip::Socket::sendExact(), and tcpip::Storage::writeUnsignedByte().
Referenced by close(), and TraCITestClient::commandClose().
void TraCIAPI::send_commandGetVariable (int domID, int varID, const std::string & objID, tcpip::Storage * add = 0) const protected
Sends a GetVariable request.
Parameters
[in] domID The domain of the variable
[in] varID The variable to retrieve
[in] objID The object to retrieve the variable from
[in] add Optional additional parameter
Definition at line 124 of file TraCIAPI.cpp.
References mySocket, tcpip::Socket::sendExact(), tcpip::Storage::size(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::commandGetVariable(), getBoundingBox(), getByte(), getColor(), getDouble(), getFloat(), getInt(), getPolygon(), getPosition(), getString(), getStringVector(), getSUMOTime(), and getUnsignedByte().
void TraCIAPI::send_commandMoveToXY (const std::string & vehicleID, const std::string & edgeID, const int lane, const double x, const double y, const double angle, const int keepRoute) const protected
Definition at line 230 of file TraCIAPI.cpp.
References CMD_SET_VEHICLE_VARIABLE, MOVE_TO_XY, send_commandSetValue(), TYPE_BYTE, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, tcpip::Storage::writeByte(), tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::send_commandSetValue (int domID, int varID, const std::string & objID, tcpip::Storage & content) const protected
Sends a SetVariable request.
Parameters
[in] domID The domain of the variable
[in] varID The variable to set
[in] objID The object to change
[in] content The value of the variable
Definition at line 151 of file TraCIAPI.cpp.
References mySocket, tcpip::Socket::sendExact(), tcpip::Storage::size(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::commandSetValue(), and send_commandMoveToXY().
void TraCIAPI::send_commandSimulationStep (SUMOTime time) const protected
Sends a SimulationStep command.
Definition at line 100 of file TraCIAPI.cpp.
References CMD_SIMSTEP, mySocket, tcpip::Socket::sendExact(), tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::commandSimulationStep(), and simulationStep().
void TraCIAPI::send_commandSubscribeObjectContext (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) const protected
Sends a SubscribeContext request.
Parameters
[in] domID The domain of the variable
[in] objID The object to subscribe the variables from
[in] beginTime The begin time step of subscriptions
[in] endTime The end time step of subscriptions
[in] domain The domain of the objects which values shall be returned
[in] range The range around the obj to investigate
[in] vars The variables to subscribe
Definition at line 200 of file TraCIAPI.cpp.
References mySocket, tcpip::Socket::sendExact(), tcpip::Storage::size(), tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::commandSubscribeContextVariable().
void TraCIAPI::send_commandSubscribeObjectVariable (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) const protected
Sends a SubscribeVariable request.
Parameters
[in] domID The domain of the variable
[in] objID The object to subscribe the variables from
[in] beginTime The begin time step of subscriptions
[in] endTime The end time step of subscriptions
[in] vars The variables to subscribe
Definition at line 172 of file TraCIAPI.cpp.
References mySocket, tcpip::Socket::sendExact(), tcpip::Storage::size(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::commandSubscribeObjectVariable().
void TraCIAPI::simulationStep (SUMOTime time = 0)
Advances by one step (or up to the given time)
Definition at line 541 of file TraCIAPI.cpp.
References check_commandGetResult(), check_resultState(), CMD_SIMSTEP, mySubscribedContextValues, mySubscribedValues, readContextSubscription(), tcpip::Storage::readInt(), readVariableSubscription(), RESPONSE_SUBSCRIBE_INDUCTIONLOOP_VARIABLE, RESPONSE_SUBSCRIBE_PERSON_VARIABLE, and send_commandSimulationStep().
Referenced by TraCITestClient::testAPI().
template<class T > static std::string TraCIAPI::toString (const T & t, std::streamsize accuracy = PRECISION) inline static protected
Definition at line 883 of file TraCIAPI.h.
References closeSocket().
Referenced by TraCIAPI::VehicleScope::add(), check_commandGetResult(), check_resultState(), and readVariables().
Field Documentation
EdgeScope TraCIAPI::edge
Scope for interaction with edges.
Definition at line 768 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
GUIScope TraCIAPI::gui
Scope for interaction with the gui.
Definition at line 770 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
InductionLoopScope TraCIAPI::inductionloop
Scope for interaction with inductive loops.
Definition at line 772 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
JunctionScope TraCIAPI::junction
Scope for interaction with junctions.
Definition at line 774 of file TraCIAPI.h.
LaneScope TraCIAPI::lane
Scope for interaction with lanes.
Definition at line 776 of file TraCIAPI.h.
LaneAreaScope TraCIAPI::lanearea
Scope for interaction with lanes.
Definition at line 778 of file TraCIAPI.h.
MeMeScope TraCIAPI::multientryexit
Scope for interaction with multi-entry/-exit detectors.
Definition at line 780 of file TraCIAPI.h.
tcpip::Socket* TraCIAPI::mySocket protected
The socket.
Definition at line 896 of file TraCIAPI.h.
Referenced by check_resultState(), closeSocket(), connect(), load(), send_commandClose(), send_commandGetVariable(), send_commandSetValue(), send_commandSimulationStep(), send_commandSubscribeObjectContext(), send_commandSubscribeObjectVariable(), and ~TraCIAPI().
SubscribedContextValues TraCIAPI::mySubscribedContextValues protected
Definition at line 899 of file TraCIAPI.h.
Referenced by readContextSubscription(), and simulationStep().
SubscribedValues TraCIAPI::mySubscribedValues protected
Definition at line 898 of file TraCIAPI.h.
Referenced by readVariableSubscription(), and simulationStep().
PersonScope TraCIAPI::person
Scope for interaction with persons.
Definition at line 782 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
POIScope TraCIAPI::poi
Scope for interaction with POIs.
Definition at line 784 of file TraCIAPI.h.
PolygonScope TraCIAPI::polygon
Scope for interaction with polygons.
Definition at line 786 of file TraCIAPI.h.
RouteScope TraCIAPI::route
Scope for interaction with routes.
Definition at line 788 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
SimulationScope TraCIAPI::simulation
Scope for interaction with the simulation.
Definition at line 790 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
TrafficLightScope TraCIAPI::trafficlights
Scope for interaction with traffic lights.
Definition at line 792 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
VehicleScope TraCIAPI::vehicle
Scope for interaction with vehicles.
Definition at line 794 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
VehicleTypeScope TraCIAPI::vehicletype
Scope for interaction with vehicle types.
Definition at line 796 of file TraCIAPI.h.
Referenced by TraCITestClient::testAPI().
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp