SUMO - Simulation of Urban MObility: GUIPerson Class Reference
GUIPerson Class Reference
#include <GUIPerson.h>
Data Structures
class GUIPersonPopupMenu
Public Types
typedef std::vector< MSTransportable::Stage * > MSTransportablePlan
the structure holding the plan of a transportable
enum StageType { WAITING_FOR_DEPART = 0, WAITING = 1, MOVING_WITHOUT_VEHICLE = 2, DRIVING = 3 }
enum VisualisationFeatures { VO_SHOW_WALKINGAREA_PATH = 1, VO_SHOW_ROUTE = 2, VO_TRACKED = 8 }
Additional visualisation feature ids.
Public Member Functions
void appendStage (Stage *stage)
Appends the given stage to the current plan.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
virtual double getAngle () const
return the current angle of the transportable
const MSEdge * getArrivalEdge () const
returns the final arrival edge
double getArrivalPos () const
returns the final arrival pos
MSTransportable::Stage * getCurrentStage () const
Return the current stage.
std::string getCurrentStageDescription () const
Returns the current stage description as a string.
StageType getCurrentStageType () const
the current stage type of the transportable
SUMOTime getDesiredDepart () const
Returns the desired departure time.
const MSEdge & getDestination () const
Returns the current destination.
const MSEdge * getEdge () const
Returns the current edge.
ConstMSEdgeVector getEdges (int next) const
Return the edges of the nth next stage.
const MSEdge * getFromEdge () const
Returns the departure edge.
const std::string & getID () const
returns the id of the transportable
const MSEdge & getNextDestination () const
Returns the destination after the current destination.
const std::string & getNextEdge () const
return the list of internal edges if this person is walking and the pedestrian model allows it
const MSEdge * getNextEdgePtr () const
returns the next edge ptr if this person is walking and the pedestrian model allows it
int getNumRemainingStages () const
Return the number of remaining stages (including the current)
int getNumStages () const
Return the total number stages in this persons plan.
const SUMOVehicleParameter & getParameter () const
StageType getStageType (int next) const
the stage type for the nth next stage
SUMOVehicle * getVehicle () const
The vehicle associated with this transportable.
const MSVehicleType & getVehicleType () const
GUIPerson (const SUMOVehicleParameter *pars, const MSVehicleType *vtype, MSTransportable::MSTransportablePlan *plan)
Constructor.
bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
bool proceed (MSNet *net, SUMOTime time)
void removeStage (int next)
removes the nth next stage
void replaceVehicleType (MSVehicleType *type)
replace myVType
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setDeparted (SUMOTime now)
logs depart time of the current stage
void setPositionInVehicle (const Position &pos)
void setSpeed (double speed)
sets the walking speed (ignored in other stages)
virtual void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
~GUIPerson ()
destructor
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additionally triggered visualisations.
inherited from MSPerson with added locking
double getEdgePos () const
return the offset from the start of the current edge
Position getPosition () const
return the Network coordinate of the person
double getNaviDegree () const
return the current angle of the person
double getWaitingSeconds () const
the time this person spent waiting in seconds
double getSpeed () const
the current speed of the person
Additional visualisations
bool hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const
Returns whether the named feature is enabled in the given view.
void addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Data Fields
std::map< GUISUMOAbstractView *, int > myAdditionalVisualizations
Enabled visualisations, per view.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
const SUMOVehicleParameter * myParameter
the plan of the transportable
MSTransportablePlan * myPlan
the plan of the transportable
MSTransportablePlan::iterator myStep
the iterator over the route
const MSVehicleType * myVType
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
bool myWriteEvents
Whether events shall be written.
Static Protected Attributes
static const double ROADSIDE_OFFSET
the offset for computing positions when standing at an edge
Private Member Functions
double getColorValue (int activeScheme) const
gets the color value according to the current scheme index
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
bool setFunctionalColor (int activeScheme) const
sets the color according to the current scheme index and some vehicle function
drawing helper methods
void drawAction_drawAsTriangle (const GUIVisualizationSettings &s) const
void drawAction_drawAsPoly (const GUIVisualizationSettings &s) const
void drawAction_drawAsImage (const GUIVisualizationSettings &s) const
void drawAction_drawWalkingareaPath (const GUIVisualizationSettings &s) const
Private Attributes
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
Position myPositionInVehicle
The position of a person while riding a vehicle.
Detailed Description
Definition at line 61 of file GUIPerson.h.
Member Typedef Documentation
typedef std::vector<MSTransportable::Stage*> MSTransportable::MSTransportablePlan inherited
the structure holding the plan of a transportable
Definition at line 377 of file MSTransportable.h.
Member Enumeration Documentation
enum MSTransportable::StageType inherited
Enumerator
WAITING_FOR_DEPART
WAITING
MOVING_WITHOUT_VEHICLE
DRIVING
Definition at line 62 of file MSTransportable.h.
enum GUIPerson::VisualisationFeatures
Additional visualisation feature ids.
Enumerator
VO_SHOW_WALKINGAREA_PATH
show the current walkingarea path
VO_SHOW_ROUTE
show persons's current route
VO_TRACKED
track person
Definition at line 202 of file GUIPerson.h.
Constructor & Destructor Documentation
GUIPerson::GUIPerson (const SUMOVehicleParameter * pars, const MSVehicleType * vtype, MSTransportable::MSTransportablePlan * plan)
Constructor.
Definition at line 154 of file GUIPerson.cpp.
GUIPerson::~GUIPerson ()
destructor
Definition at line 161 of file GUIPerson.cpp.
References GUIGlObject::getGlID(), MFXMutex::lock(), myAdditionalVisualizations, myLock, and MFXMutex::unlock().
Member Function Documentation
void GUIPerson::addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::addAdditionalGLVisualisation
Definition at line 531 of file GUIPerson.cpp.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), and myAdditionalVisualizations.
Referenced by GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), and GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath().
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 256 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void MSTransportable::appendStage (Stage * stage) inherited
Appends the given stage to the current plan.
Definition at line 412 of file MSTransportable.cpp.
References MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by MSTransportable::getVehicle(), TraCIServerAPI_Person::processSet(), and MSTransportable::removeStage().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 185 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 194 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 175 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPolygon::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 235 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 204 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 247 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 217 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 226 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
void GUIPerson::drawAction_drawAsImage (const GUIVisualizationSettings & s) const private
Definition at line 503 of file GUIPerson.cpp.
References drawAction_drawAsPoly(), GUITexturesHelper::drawTexturedBox(), MSTransportable::getAngle(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getImgFile(), MSVehicleType::getLength(), GUITexturesHelper::getTextureID(), MSTransportable::getVehicleType(), MSVehicleType::getWidth(), GUIVisualizationSettings::personSize, PI, RAD2DEG, and SVS_PEDESTRIAN.
Referenced by drawGL().
void GUIPerson::drawAction_drawAsPoly (const GUIVisualizationSettings & s) const private
Definition at line 477 of file GUIPerson.cpp.
References RGBColor::changedBrightness(), GLHelper::drawFilledCircle(), MSTransportable::getAngle(), GLHelper::getColor(), MSTransportable::getVehicleType(), GeomHelper::naviDegree(), and GLHelper::setColor().
Referenced by drawAction_drawAsImage(), and drawGL().
void GUIPerson::drawAction_drawAsTriangle (const GUIVisualizationSettings & s) const private
Definition at line 455 of file GUIPerson.cpp.
References MSTransportable::getAngle(), GLHelper::getColor(), MSTransportable::getVehicleType(), PI, RAD2DEG, and GLHelper::setColor().
Referenced by drawGL().
void GUIPerson::drawAction_drawWalkingareaPath (const GUIVisualizationSettings & s) const private
Definition at line 297 of file GUIPerson.cpp.
References GLHelper::drawBoxLines(), MSTransportable::getCurrentStage(), MSPerson::MSPersonStage_Walking::getPedestrianState(), GUIGlObject::getType(), MSPModel_Striping::PState::myWalkingAreaPath, setColor(), and MSPModel_Striping::WalkingAreaPath::shape.
Referenced by drawGL(), and drawGLAdditional().
void GUIPerson::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 261 of file GUIPerson.cpp.
References drawAction_drawAsImage(), drawAction_drawAsPoly(), drawAction_drawAsTriangle(), drawAction_drawWalkingareaPath(), GUIGlObject::drawName(), MSTransportable::DRIVING, MSTransportable::getCurrentStageType(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), getPosition(), GUIGlObject::getType(), MSTransportable::isWaiting4Vehicle(), myPositionInVehicle, GUIVisualizationSettings::personName, GUIVisualizationSettings::personQuality, GUIVisualizationSettings::personSize, GUIVisualizationSettings::scale, setColor(), Position::x(), and Position::y().
Referenced by GUIVehicle::drawAction_drawPersonsAndContainers(), and GUIEdge::drawGL().
void GUIPerson::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual
Draws additionally triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented from GUIGlObject.
Definition at line 315 of file GUIPerson.cpp.
References RGBColor::changedBrightness(), drawAction_drawWalkingareaPath(), GLHelper::drawBoxLines(), GLHelper::getColor(), MSTransportable::getCurrentStage(), MSTransportable::getCurrentStageType(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), MSPerson::MSPersonStage_Walking::getRoute(), GUILane::getShape(), GUILane::getShapeLengths(), GUILane::getShapeRotations(), GUIGlObject::getType(), hasActiveAddVisualisation(), MSTransportable::MOVING_WITHOUT_VEHICLE, GUIVisualizationSettings::personSize, setColor(), GLHelper::setColor(), VO_SHOW_ROUTE, and VO_SHOW_WALKINGAREA_PATH.
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 284 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), GNEEdge::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
double MSTransportable::getAngle () const virtual inherited
return the current angle of the transportable
Reimplemented in GUIContainer.
Definition at line 386 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by drawAction_drawAsImage(), drawAction_drawAsPoly(), drawAction_drawAsTriangle(), GUIContainer::getAngle(), getNaviDegree(), TraCIServerAPI_Person::processGet(), setFunctionalColor(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
const MSEdge* MSTransportable::getArrivalEdge () const inline inherited
returns the final arrival edge
Definition at line 520 of file MSTransportable.h.
References MSTransportable::myPlan, and MSTransportable::replaceVehicleType().
Referenced by TraCIServerAPI_Person::processSet().
double MSTransportable::getArrivalPos () const inline inherited
returns the final arrival pos
Definition at line 515 of file MSTransportable.h.
References MSTransportable::myPlan.
Referenced by TraCIServerAPI_Person::processSet().
Boundary GUIPerson::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 251 of file GUIPerson.cpp.
References Boundary::add(), getPosition(), MSTransportable::getVehicleType(), Boundary::grow(), and MAX2().
double GUIPerson::getColorValue (int activeScheme) const private
gets the color value according to the current scheme index
Definition at line 400 of file GUIPerson.cpp.
References MSTransportable::getCurrentStageType(), GUIGlObject::getGlID(), getSpeed(), getWaitingSeconds(), GLO_PERSON, gSelected, GUISelectedStorage::isSelected(), and MSTransportable::isWaiting4Vehicle().
Referenced by setColor().
MSTransportable::Stage* MSTransportable::getCurrentStage () const inline inherited
Return the current stage.
Definition at line 459 of file MSTransportable.h.
References MSTransportable::myStep.
Referenced by drawAction_drawWalkingareaPath(), drawGLAdditional(), and MSEdge::transportable_by_position_sorter::operator()().
std::string MSTransportable::getCurrentStageDescription () const inline inherited
Returns the current stage description as a string.
Definition at line 454 of file MSTransportable.h.
Referenced by GUIContainer::getParameterWindow(), getParameterWindow(), and MSXMLRawOut::writeTransportable().
StageType MSTransportable::getCurrentStageType () const inline inherited
the current stage type of the transportable
Definition at line 442 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), GUIContainer::drawGL(), drawGL(), drawGLAdditional(), GUIContainer::getColorValue(), getColorValue(), MSPerson::getNextEdgePtr(), and GUIContainer::getPosition().
SUMOTime MSTransportable::getDesiredDepart () const inherited
Returns the desired departure time.
Definition at line 366 of file MSTransportable.cpp.
References SUMOVehicleParameter::depart, and MSTransportable::myParameter.
Referenced by MSTransportable::getVehicleType(), MSContainer::routeOutput(), MSPerson::routeOutput(), MSContainer::tripInfoOutput(), and MSPerson::tripInfoOutput().
const MSEdge& MSTransportable::getDestination () const inline inherited
Returns the current destination.
Definition at line 407 of file MSTransportable.h.
Referenced by GUIContainer::getParameterWindow(), getParameterWindow(), MSDevice_Transportable::notifyLeave(), and MSDevice_Transportable::notifyMove().
const MSEdge* MSTransportable::getEdge () const inline inherited
Returns the current edge.
Definition at line 417 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), GUIContainer::getParameterWindow(), getParameterWindow(), GUIContainer::getPosition(), TraCIServerAPI_Person::processGet(), and MSTransportable::removeStage().
double GUIPerson::getEdgePos () const virtual
return the offset from the start of the current edge
Reimplemented from MSTransportable.
Definition at line 420 of file GUIPerson.cpp.
References MSTransportable::getEdgePos(), and myLock.
Referenced by getParameterWindow(), and setPositionInVehicle().
ConstMSEdgeVector MSTransportable::getEdges (int next) const inline inherited
Return the edges of the nth next stage.
Definition at line 464 of file MSTransportable.h.
References MSTransportable::Stage::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), MSTransportable::myPlan, MSTransportable::myStep, MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
Referenced by TraCIServerAPI_Person::processGet().
const MSEdge* MSTransportable::getFromEdge () const inline inherited
Returns the departure edge.
Definition at line 422 of file MSTransportable.h.
References MSTransportable::Stage::getAngle(), MSTransportable::Stage::getEdgePos(), MSTransportable::Stage::getPosition(), MSTransportable::Stage::getSpeed(), and MSTransportable::getWaitingSeconds().
Referenced by GUIContainer::getParameterWindow(), and getParameterWindow().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 121 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEInternalLane::drawGL(), GNEJunction::drawGL(), GNECrossing::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdRevertRestriction(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and ~GUIPerson().
const std::string & MSTransportable::getID () const inherited
returns the id of the transportable
Definition at line 361 of file MSTransportable.cpp.
References SUMOVehicleParameter::id, and MSTransportable::myParameter.
Referenced by MSTransportableControl::abortWaiting(), MSVehicle::addContainer(), MSVehicle::addPerson(), MSPerson::MSPersonStage_Walking::beginEventOutput(), MSContainer::MSContainerStage_Tranship::beginEventOutput(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Walking::endEventOutput(), MSContainer::MSContainerStage_Tranship::endEventOutput(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSTransportableControl::erase(), MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), GUIContainer::getParameterWindow(), getParameterWindow(), TraCIServerAPI_Person::getSingularType(), MSPedestrianPushButton::isActiveForEdge(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), MSDevice_Transportable::notifyLeave(), MSPModel_Striping::by_xpos_sorter::operator()(), MSEdge::transportable_by_position_sorter::operator()(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSPModel_Striping::PState::PState(), MSContainer::MSContainerStage_Driving::routeOutput(), MSContainer::routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), MSPerson::routeOutput(), MSContainer::tripInfoOutput(), MSPerson::tripInfoOutput(), MSPModel_Striping::PState::walk(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 135 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNEJunction::getAttribute(), GNELane::getAttribute(), GNENetElement::getParentName(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSign::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNERerouter::getParentName(), GNEDetector::getParentName(), GNEDetectorE3::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEPoly::moveGeometry(), GNEEdge::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
double GUIPerson::getNaviDegree () const
return the current angle of the person
Definition at line 434 of file GUIPerson.cpp.
References MSTransportable::getAngle(), myLock, and GeomHelper::naviDegree().
Referenced by getParameterWindow(), and setPositionInVehicle().
const MSEdge& MSTransportable::getNextDestination () const inline inherited
Returns the destination after the current destination.
Definition at line 412 of file MSTransportable.h.
References MSTransportable::myStep.
const std::string & MSPerson::getNextEdge () const inherited
return the list of internal edges if this person is walking and the pedestrian model allows it
Definition at line 329 of file MSPerson.cpp.
References StringUtils::emptyString, Named::getID(), and MSPerson::getNextEdgePtr().
const MSEdge * MSPerson::getNextEdgePtr () const inherited
returns the next edge ptr if this person is walking and the pedestrian model allows it
Definition at line 348 of file MSPerson.cpp.
References MSTransportable::getCurrentStageType(), PedestrianState::getNextEdge(), MSPerson::MSPersonStage_Walking::getPedestrianState(), and MSTransportable::MOVING_WITHOUT_VEHICLE.
Referenced by MSPerson::getNextEdge(), and MSPedestrianPushButton::isActiveForEdge().
int MSTransportable::getNumRemainingStages () const inherited
Return the number of remaining stages (including the current)
Definition at line 402 of file MSTransportable.cpp.
References MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by MSTransportable::getEdges(), TraCIServerAPI_Person::processGet(), and TraCIServerAPI_Person::processSet().
int MSTransportable::getNumStages () const inherited
Return the total number stages in this persons plan.
Definition at line 407 of file MSTransportable.cpp.
References MSTransportable::myPlan.
Referenced by MSTransportable::getEdges(), and TraCIServerAPI_Person::processGet().
const SUMOVehicleParameter& MSTransportable::getParameter () const inline inherited
Definition at line 392 of file MSTransportable.h.
References MSTransportable::myParameter.
Referenced by MSTransportableControl::add(), getParameterWindow(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Person::processSet(), GUIContainer::setFunctionalColor(), and setFunctionalColor().
GUIParameterTableWindow * GUIPerson::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 207 of file GUIPerson.cpp.
References GUIParameterTableWindow::closeBuilding(), MSTransportable::getCurrentStageDescription(), MSTransportable::getDestination(), MSTransportable::getEdge(), getEdgePos(), MSTransportable::getFromEdge(), MSTransportable::getID(), getNaviDegree(), MSTransportable::getParameter(), getSpeed(), getWaitingSeconds(), GUIParameterTableWindow::mkItem(), and toString().
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEDetectorE3, GNEDetector, GNERerouter, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSign, GNEVaporizer, GUILane, GNELane, and GNENetElement.
Definition at line 115 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
GUIGLObjectPopupMenu * GUIPerson::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 174 of file GUIPerson.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUIGlObject::buildShowTypeParamsPopupEntry(), GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), hasActiveAddVisualisation(), MID_HIDE_CURRENTROUTE, MID_HIDE_WALKINGAREA_PATH, MID_SHOW_CURRENTROUTE, MID_SHOW_WALKINGAREA_PATH, MID_START_TRACK, MID_STOP_TRACK, myAdditionalVisualizations, VO_SHOW_ROUTE, and VO_SHOW_WALKINGAREA_PATH.
Position GUIPerson::getPosition () const virtual
return the Network coordinate of the person
Reimplemented from MSTransportable.
Definition at line 427 of file GUIPerson.cpp.
References MSTransportable::getPosition(), and myLock.
Referenced by drawGL(), getCenteringBoundary(), and setPositionInVehicle().
double GUIPerson::getSpeed () const virtual
the current speed of the person
Reimplemented from MSTransportable.
Definition at line 448 of file GUIPerson.cpp.
References MSTransportable::getSpeed(), and myLock.
Referenced by getColorValue(), getParameterWindow(), and setPositionInVehicle().
StageType MSTransportable::getStageType (int next) const inline inherited
the stage type for the nth next stage
Definition at line 447 of file MSTransportable.h.
References MSTransportable::Stage::getStageType(), MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by TraCIServerAPI_Person::processGet().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 148 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), drawAction_drawWalkingareaPath(), GNEDetector::drawDetectorIcon(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNECrossing::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEAdditional::drawParentAndChildrenConnections(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIPerson::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own type parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented from GUIGlObject.
Definition at line 229 of file GUIPerson.cpp.
References GUIParameterTableWindow::closeBuilding(), MSVehicleType::getHeight(), MSVehicleType::getID(), MSVehicleType::getLength(), Parameterised::getMap(), MSVehicleType::getMaxSpeed(), MSVehicleType::getMinGap(), MSVehicleType::getParameter(), MSVehicleType::getWidth(), GUIParameterTableWindow::mkItem(), MSTransportable::myVType, and toString().
SUMOVehicle* MSTransportable::getVehicle () const inline inherited
The vehicle associated with this transportable.
Definition at line 501 of file MSTransportable.h.
References MSTransportable::appendStage(), MSTransportable::removeStage(), and MSTransportable::Stage::setSpeed().
Referenced by TraCIServerAPI_Person::processGet().
const MSVehicleType& MSTransportable::getVehicleType () const inline inherited
Definition at line 396 of file MSTransportable.h.
References MSTransportable::getDesiredDepart(), MSTransportable::myVType, and MSTransportable::Stage::setDeparted().
Referenced by MSStoppingPlace::addTransportable(), GUIContainer::drawAction_drawAsImage(), drawAction_drawAsImage(), GUIContainer::drawAction_drawAsPoly(), drawAction_drawAsPoly(), drawAction_drawAsTriangle(), getCenteringBoundary(), MSPModel_Striping::PState::getImpatience(), MSPModel_Striping::PState::getLength(), MSPModel_Striping::PState::getMinGap(), MSPModel_Striping::getNextLaneObstacles(), TraCIServerAPI_Person::getSingularType(), MSPModel_Striping::PState::otherStripe(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Person::processSet(), MSStoppingPlace::removeTransportable(), GUIContainer::setFunctionalColor(), and setFunctionalColor().
double GUIPerson::getWaitingSeconds () const virtual
the time this person spent waiting in seconds
Reimplemented from MSTransportable.
Definition at line 441 of file GUIPerson.cpp.
References MSTransportable::getWaitingSeconds(), and myLock.
Referenced by getColorValue(), getParameterWindow(), and setPositionInVehicle().
bool GUIPerson::hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const
Returns whether the named feature is enabled in the given view.
Parameters
[in] parent The view for which the feature may be enabled
[in] which The visualisation feature
Returns
see comment
Definition at line 525 of file GUIPerson.cpp.
References myAdditionalVisualizations.
Referenced by drawGLAdditional(), and getPopUpMenu().
bool MSTransportable::isWaiting4Vehicle () const inline inherited
Whether the transportable waits for a vehicle.
Definition at line 496 of file MSTransportable.h.
Referenced by GUIContainer::drawGL(), drawGL(), GUIContainer::getColorValue(), and getColorValue().
bool MSTransportable::isWaitingFor (const std::string & line) const inline inherited
Whether the transportable waits for a vehicle of the line specified.
Definition at line 491 of file MSTransportable.h.
bool MSPerson::proceed (MSNet * net, SUMOTime time) virtual inherited
Implements MSTransportable.
Definition at line 304 of file MSPerson.cpp.
References MSTransportable::Stage::getEdge(), MSTransportable::myPlan, MSTransportable::myStep, MSEdge::removePerson(), and MSTransportable::Stage::setArrived().
Referenced by MSPerson::MSPersonStage_Walking::moveToNextEdge().
void GUIPerson::removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::removeAdditionalGLVisualisation
Definition at line 541 of file GUIPerson.cpp.
References myAdditionalVisualizations, and GUISUMOAbstractView::removeAdditionalGLVisualisation().
Referenced by GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), and GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 262 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void MSTransportable::removeStage (int next) inherited
removes the nth next stage
Definition at line 421 of file MSTransportable.cpp.
References MSTransportable::appendStage(), MSTransportable::getEdge(), MSTransportable::getEdgePos(), MSNet::getInstance(), MSTransportable::myPlan, MSTransportable::myStep, and MSTransportable::proceed().
Referenced by MSTransportable::getVehicle(), and TraCIServerAPI_Person::processSet().
void MSTransportable::replaceVehicleType (MSVehicleType * type) inherited
replace myVType
Definition at line 450 of file MSTransportable.cpp.
References MSTransportable::myVType.
Referenced by MSTransportable::getArrivalEdge(), TraCIServerAPI_Person::getSingularType(), and TraCIServerAPI_Person::processSet().
void MSPerson::routeOutput (OutputDevice & os) const virtual inherited
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 370 of file MSPerson.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSNet::getInstance(), OutputDevice::lf(), MSTransportable::myPlan, MSTransportable::myStep, OutputDevice::openTag(), SUMO_ATTR_DEPART, SUMO_ATTR_ID, SUMO_TAG_PERSON, time2string(), and OutputDevice::writeAttr().
void GUIPerson::setColor (const GUIVisualizationSettings & s) const private
sets the color according to the currente settings
Definition at line 346 of file GUIPerson.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIVisualizationSettings::personColorer, GLHelper::setColor(), and setFunctionalColor().
Referenced by drawAction_drawWalkingareaPath(), drawGL(), and drawGLAdditional().
void MSTransportable::setDeparted (SUMOTime now) inherited
logs depart time of the current stage
Definition at line 371 of file MSTransportable.cpp.
bool GUIPerson::setFunctionalColor (int activeScheme) const private
sets the color according to the current scheme index and some vehicle function
Definition at line 355 of file GUIPerson.cpp.
References RGBColor::fromHSV(), MSTransportable::getAngle(), MSTransportable::getParameter(), MSTransportable::getVehicleType(), GeomHelper::naviDegree(), GLHelper::setColor(), VEHPARS_COLOR_SET, and VTYPEPARS_COLOR_SET.
Referenced by setColor().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 141 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
void GUIPerson::setPositionInVehicle (const Position & pos) inline
Definition at line 126 of file GUIPerson.h.
References getEdgePos(), getNaviDegree(), getPosition(), getSpeed(), getWaitingSeconds(), and myPositionInVehicle.
Referenced by GUIVehicle::drawAction_drawPersonsAndContainers().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 271 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
void MSTransportable::setSpeed (double speed) inherited
sets the walking speed (ignored in other stages)
Definition at line 442 of file MSTransportable.cpp.
References MSTransportable::myPlan.
Referenced by TraCIServerAPI_Person::processSet().
void MSPerson::tripInfoOutput (OutputDevice & os) const virtual inherited
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 360 of file MSPerson.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::myPlan, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
std::map<GUISUMOAbstractView*, int> GUIPerson::myAdditionalVisualizations
Enabled visualisations, per view.
Definition at line 212 of file GUIPerson.h.
Referenced by addActiveAddVisualisation(), getPopUpMenu(), hasActiveAddVisualisation(), removeActiveAddVisualisation(), and ~GUIPerson().
MFXMutex GUIPerson::myLock mutable private
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 245 of file GUIPerson.h.
Referenced by getEdgePos(), getNaviDegree(), getPosition(), getSpeed(), getWaitingSeconds(), and ~GUIPerson().
const SUMOVehicleParameter* MSTransportable::myParameter protected inherited
the plan of the transportable
Definition at line 532 of file MSTransportable.h.
Referenced by MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::getParameter(), and MSTransportable::~MSTransportable().
MSTransportablePlan* MSTransportable::myPlan protected inherited
the plan of the transportable
Definition at line 542 of file MSTransportable.h.
Referenced by MSTransportable::appendStage(), MSTransportable::getArrivalEdge(), MSTransportable::getArrivalPos(), MSTransportable::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), MSTransportable::getStageType(), MSTransportable::MSTransportable(), MSContainer::proceed(), MSPerson::proceed(), MSTransportable::removeStage(), MSContainer::routeOutput(), MSPerson::routeOutput(), MSTransportable::setSpeed(), MSContainer::tripInfoOutput(), MSPerson::tripInfoOutput(), and MSTransportable::~MSTransportable().
Position GUIPerson::myPositionInVehicle private
The position of a person while riding a vehicle.
Definition at line 248 of file GUIPerson.h.
Referenced by drawGL(), and setPositionInVehicle().
MSTransportablePlan::iterator MSTransportable::myStep protected inherited
the iterator over the route
Definition at line 545 of file MSTransportable.h.
Referenced by MSTransportable::appendStage(), MSTransportable::getCurrentStage(), MSTransportable::getEdges(), MSTransportable::getNextDestination(), MSTransportable::getNumRemainingStages(), MSTransportable::getStageType(), MSTransportable::MSTransportable(), MSContainer::proceed(), MSPerson::proceed(), MSTransportable::removeStage(), MSContainer::routeOutput(), and MSPerson::routeOutput().
const MSVehicleType* MSTransportable::myVType protected inherited
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
Definition at line 536 of file MSTransportable.h.
Referenced by getTypeParameterWindow(), MSTransportable::getVehicleType(), and MSTransportable::replaceVehicleType().
bool MSTransportable::myWriteEvents protected inherited
Whether events shall be written.
Definition at line 539 of file MSTransportable.h.
const double MSTransportable::ROADSIDE_OFFSET static protected inherited
the offset for computing positions when standing at an edge
Definition at line 529 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getPosition(), and MSTransportable::Stage_Driving::getPosition().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIPerson.h
GUIPerson.cpp