SUMO - Simulation of Urban MObility: GNECalibratorDialog Class Reference
GNECalibratorDialog Class Reference
Dialog for edit calibrators.
#include <GNECalibratorDialog.h>
Public Member Functions
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNECalibrator * getCalibratorParent () const
get calibrator parent
GNECalibratorDialog (GNECalibrator *calibratorParent)
FOX-declaration.
~GNECalibratorDialog ()
destructor
FOX-callbacks
event after press accept button
long onCmdAccept (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
long onCmdAddRoute (FXObject *, FXSelector, void *)
add new route
long onCmdClickedRoute (FXObject *, FXSelector, void *)
remove or edit route
long onCmdAddFlow (FXObject *, FXSelector, void *)
add new flow
long onCmdClickedFlow (FXObject *, FXSelector, void *)
remove or edit flow
long onCmdAddVehicleType (FXObject *, FXSelector, void *)
add new vehicle type
long onCmdClickedVehicleType (FXObject *, FXSelector, void *)
remove or edit vehicle type
Protected Member Functions
GNECalibratorDialog ()
FOX needs this.
void updateFlowAndLabelButton ()
update flow and label button
void updateFlowTable ()
update data table with flows
void updateRouteTable ()
update data table with routes
void updateVehicleTypeTable ()
update data table with vehicle types
Protected Attributes
FXButton * myAcceptButton
accept button
FXButton * myAddFlow
button for add new flow
FXButton * myAddRoute
button for add new route
FXButton * myAddVehicleType
button for add new vehicle type
GNECalibrator * myCalibratorParent
pointer to calibrator parent
FXButton * myCancelButton
cancel button
FXVerticalFrame * myContentFrame
frame for contents
std::vector< GNECalibratorFlow > myCopyOfCalibratorFlows
vector with a copy of calibrator flows (used by reset)
std::vector< GNECalibratorRoute > myCopyOfCalibratorRoutes
vector with a copy of calibrator routes (used by reset)
std::vector< GNECalibratorVehicleType > myCopyOfCalibratorVehicleTypes
vector with a copy of calibrator vehicle types (used by reset)
FXTable * myFlowList
list with flows
FXLabel * myLabelFlow
label for flows
FXButton * myResetButton
cancel button
FXTable * myRouteList
list with routes
FXTable * myVehicleTypeList
list with vehicle types
Private Member Functions
GNECalibratorDialog (const GNECalibratorDialog &)
Invalidated copy constructor.
GNECalibratorDialog & operator= (const GNECalibratorDialog &)
Invalidated assignment operator.
Detailed Description
Dialog for edit calibrators.
Definition at line 53 of file GNECalibratorDialog.h.
Constructor & Destructor Documentation
GNECalibratorDialog::GNECalibratorDialog (GNECalibrator * calibratorParent)
FOX-declaration.
Constructor
Definition at line 67 of file GNECalibratorDialog.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarFrame, GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonIcon, GUIDesignLabelThick, GUIDesignTableAdditionals, GUIDesignUniformHorizontalFrame, ICON_ADD, MID_GNE_CALIBRATORDIALOG_ADD_FLOW, MID_GNE_CALIBRATORDIALOG_ADD_ROUTE, MID_GNE_CALIBRATORDIALOG_ADD_VEHICLETYPE, MID_GNE_CALIBRATORDIALOG_TABLE_FLOW, MID_GNE_CALIBRATORDIALOG_TABLE_ROUTE, MID_GNE_CALIBRATORDIALOG_TABLE_VEHICLETYPE, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, SUMO_TAG_VTYPE, and toString().
GNECalibratorDialog::~GNECalibratorDialog ()
destructor
Definition at line 124 of file GNECalibratorDialog.cpp.
GNECalibratorDialog::GNECalibratorDialog () inline protected
FOX needs this.
Definition at line 99 of file GNECalibratorDialog.h.
GNECalibratorDialog::GNECalibratorDialog (const GNECalibratorDialog &) private
Invalidated copy constructor.
Member Function Documentation
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) inherited
change additional dialog header
Definition at line 81 of file GNEAdditionalDialog.cpp.
GNECalibrator * GNECalibratorDialog::getCalibratorParent () const
get calibrator parent
Definition at line 129 of file GNECalibratorDialog.cpp.
References myCalibratorParent.
Referenced by GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), and GNECalibratorRouteDialog::onCmdAccept().
long GNECalibratorDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
Implements GNEAdditionalDialog.
Definition at line 135 of file GNECalibratorDialog.cpp.
long GNECalibratorDialog::onCmdAddFlow (FXObject * , FXSelector , void *)
add new flow
Definition at line 264 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorFlows(), myCalibratorParent, GNECalibrator::setCalibratorFlows(), and updateFlowTable().
long GNECalibratorDialog::onCmdAddRoute (FXObject * , FXSelector , void *)
add new route
Definition at line 169 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorRoutes(), myCalibratorParent, GNECalibrator::setCalibratorRoutes(), and updateRouteTable().
long GNECalibratorDialog::onCmdAddVehicleType (FXObject * , FXSelector , void *)
add new vehicle type
Definition at line 314 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorVehicleTypes(), myCalibratorParent, GNECalibrator::setCalibratorVehicleTypes(), and updateVehicleTypeTable().
long GNECalibratorDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event after press cancel button
Implements GNEAdditionalDialog.
Definition at line 143 of file GNECalibratorDialog.cpp.
References myCalibratorParent, myCopyOfCalibratorFlows, myCopyOfCalibratorRoutes, myCopyOfCalibratorVehicleTypes, GNECalibrator::setCalibratorFlows(), GNECalibrator::setCalibratorRoutes(), and GNECalibrator::setCalibratorVehicleTypes().
long GNECalibratorDialog::onCmdClickedFlow (FXObject * , FXSelector , void *)
remove or edit flow
Definition at line 282 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorFlows(), myCalibratorParent, myFlowList, GNECalibrator::setCalibratorFlows(), and updateFlowTable().
long GNECalibratorDialog::onCmdClickedRoute (FXObject * , FXSelector , void *)
remove or edit route
Definition at line 187 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorFlows(), GNECalibrator::getCalibratorRoutes(), GNEAdditional::getViewNet(), GNEViewNet::isTestingModeEnabled(), myCalibratorParent, myRouteList, GNECalibrator::setCalibratorFlows(), GNECalibrator::setCalibratorRoutes(), SUMO_TAG_FLOW, SUMO_TAG_ROUTE, toString(), updateFlowTable(), updateRouteTable(), and WRITE_WARNING.
long GNECalibratorDialog::onCmdClickedVehicleType (FXObject * , FXSelector , void *)
remove or edit vehicle type
Definition at line 332 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorFlows(), GNECalibrator::getCalibratorVehicleTypes(), GNEAdditional::getViewNet(), GNEViewNet::isTestingModeEnabled(), myCalibratorParent, myRouteList, myVehicleTypeList, GNECalibrator::setCalibratorFlows(), GNECalibrator::setCalibratorVehicleTypes(), SUMO_TAG_FLOW, SUMO_TAG_ROUTE, toString(), updateFlowTable(), updateVehicleTypeTable(), and WRITE_WARNING.
long GNECalibratorDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event after press reset button
Implements GNEAdditionalDialog.
Definition at line 155 of file GNECalibratorDialog.cpp.
References myCalibratorParent, myCopyOfCalibratorFlows, myCopyOfCalibratorRoutes, myCopyOfCalibratorVehicleTypes, GNECalibrator::setCalibratorFlows(), GNECalibrator::setCalibratorRoutes(), GNECalibrator::setCalibratorVehicleTypes(), updateFlowTable(), updateRouteTable(), and updateVehicleTypeTable().
GNECalibratorDialog& GNECalibratorDialog::operator= (const GNECalibratorDialog &) private
Invalidated assignment operator.
void GNECalibratorDialog::updateFlowAndLabelButton () protected
update flow and label button
Definition at line 525 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorRoutes(), GNECalibrator::getCalibratorVehicleTypes(), myAddFlow, myCalibratorParent, myFlowList, myLabelFlow, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, SUMO_TAG_VTYPE, and toString().
Referenced by updateFlowTable(), updateRouteTable(), and updateVehicleTypeTable().
void GNECalibratorDialog::updateFlowTable () protected
update data table with flows
Definition at line 443 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorFlows(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_REMOVE, myCalibratorParent, myFlowList, SUMO_ATTR_ID, SUMO_ATTR_ROUTE, SUMO_ATTR_VCLASS, toString(), and updateFlowAndLabelButton().
Referenced by onCmdAddFlow(), onCmdClickedFlow(), onCmdClickedRoute(), onCmdClickedVehicleType(), and onCmdReset().
void GNECalibratorDialog::updateRouteTable () protected
update data table with routes
Definition at line 404 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorRoutes(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_REMOVE, myCalibratorParent, myRouteList, SUMO_ATTR_EDGES, SUMO_ATTR_ID, toString(), and updateFlowAndLabelButton().
Referenced by onCmdAddRoute(), onCmdClickedRoute(), and onCmdReset().
void GNECalibratorDialog::updateVehicleTypeTable () protected
update data table with vehicle types
Definition at line 487 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorVehicleTypes(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_REMOVE, myCalibratorParent, myVehicleTypeList, SUMO_ATTR_ID, SUMO_ATTR_VCLASS, toString(), and updateFlowAndLabelButton().
Referenced by onCmdAddVehicleType(), onCmdClickedVehicleType(), and onCmdReset().
Field Documentation
FXButton* GNEAdditionalDialog::myAcceptButton protected inherited
accept button
Definition at line 85 of file GNEAdditionalDialog.h.
FXButton* GNECalibratorDialog::myAddFlow protected
button for add new flow
Definition at line 114 of file GNECalibratorDialog.h.
Referenced by updateFlowAndLabelButton().
FXButton* GNECalibratorDialog::myAddRoute protected
button for add new route
Definition at line 105 of file GNECalibratorDialog.h.
FXButton* GNECalibratorDialog::myAddVehicleType protected
button for add new vehicle type
Definition at line 120 of file GNECalibratorDialog.h.
GNECalibrator* GNECalibratorDialog::myCalibratorParent protected
pointer to calibrator parent
Definition at line 102 of file GNECalibratorDialog.h.
Referenced by getCalibratorParent(), onCmdAddFlow(), onCmdAddRoute(), onCmdAddVehicleType(), onCmdCancel(), onCmdClickedFlow(), onCmdClickedRoute(), onCmdClickedVehicleType(), onCmdReset(), updateFlowAndLabelButton(), updateFlowTable(), updateRouteTable(), and updateVehicleTypeTable().
FXButton* GNEAdditionalDialog::myCancelButton protected inherited
cancel button
Definition at line 88 of file GNEAdditionalDialog.h.
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 82 of file GNEAdditionalDialog.h.
std::vector<GNECalibratorFlow> GNECalibratorDialog::myCopyOfCalibratorFlows protected
vector with a copy of calibrator flows (used by reset)
Definition at line 129 of file GNECalibratorDialog.h.
Referenced by onCmdCancel(), and onCmdReset().
std::vector<GNECalibratorRoute> GNECalibratorDialog::myCopyOfCalibratorRoutes protected
vector with a copy of calibrator routes (used by reset)
Definition at line 126 of file GNECalibratorDialog.h.
Referenced by onCmdCancel(), and onCmdReset().
std::vector<GNECalibratorVehicleType> GNECalibratorDialog::myCopyOfCalibratorVehicleTypes protected
vector with a copy of calibrator vehicle types (used by reset)
Definition at line 132 of file GNECalibratorDialog.h.
Referenced by onCmdCancel(), and onCmdReset().
FXTable* GNECalibratorDialog::myFlowList protected
list with flows
Definition at line 117 of file GNECalibratorDialog.h.
Referenced by onCmdClickedFlow(), updateFlowAndLabelButton(), and updateFlowTable().
FXLabel* GNECalibratorDialog::myLabelFlow protected
label for flows
Definition at line 111 of file GNECalibratorDialog.h.
Referenced by updateFlowAndLabelButton().
FXButton* GNEAdditionalDialog::myResetButton protected inherited
cancel button
Definition at line 91 of file GNEAdditionalDialog.h.
FXTable* GNECalibratorDialog::myRouteList protected
list with routes
Definition at line 108 of file GNECalibratorDialog.h.
Referenced by onCmdClickedRoute(), onCmdClickedVehicleType(), and updateRouteTable().
FXTable* GNECalibratorDialog::myVehicleTypeList protected
list with vehicle types
Definition at line 123 of file GNECalibratorDialog.h.
Referenced by onCmdClickedVehicleType(), and updateVehicleTypeTable().
The documentation for this class was generated from the following files:
GNECalibratorDialog.h
GNECalibratorDialog.cpp