SUMO - Simulation of Urban MObility: GNEDetectorE1 Class Reference
GNEDetectorE1 Class Reference
#include <GNEDetectorE1.h>
Public Member Functions
void commmitAdditionalGeometryMoved (double oldPosx, double, GNEUndoList *undoList)
updated geometry changes in the attributes of additional
void commmitAdditionalGeometryMoved (const Position &oldPos, GNEUndoList *undoList)
updated geometry changes in the attributes of additional
void decRef (const std::string &debugMsg="")
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
const std::string & getAdditionalID () const
returns the ID of additional
std::vector< SumoXMLAttr > getAttrs () const
get vector of attributes
template<>
int getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
double getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
bool getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::string getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleClass getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleShape getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< int > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< double > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< bool > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< std::string > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
virtual std::string getDescription ()
how should this attribute carrier be called
GNEEdge * getEdge () const
get edge of additional, or NULL if additional isn't placed over an edge
std::string getFilename () const
returns the path to the output file
double getFrequency () const
returns the aggregation period the values the detector collects shall be summed up.
GUIIcon getGUIIcon () const
get GUI icon assigned to this object
FXIcon * getIcon () const
get FXIcon assigned to this object
const std::string getID () const
function to support debugging
GNELane * getLane () const
get lane of additional, or NULL if additional isn't placed over a Lane
Position getPositionInView () const
Returns position of detector E1 in view.
double getPositionOverLane () const
Returns the position of the detector over lane.
PositionVector getShape () const
Returns additional element's shape.
SumoXMLTag getTag () const
get XML Tag assigned to this object
GNEViewNet * getViewNet () const
Returns a pointer to GNEViewNet in which additional element is located.
GNEDetectorE1 (const std::string &id, GNELane *lane, GNEViewNet *viewNet, double pos, double freq, const std::string &filename, bool splitByType)
Constructor.
void incRef (const std::string &debugMsg="")
bool isAdditionalBlocked () const
Check if additional item is currently blocked (i.e. cannot be moved with mouse)
bool isAdditionalInspectionable () const
check if additional element is inspectionable (With GNEInspectorFrame)
bool isAdditionalMovable () const
check if additional element is movable
bool isAdditionalSelectable () const
check if additional element is selectable (With GNESelectorFrame)
bool isAdditionalSelected () const
void moveAdditionalGeometry (double offsetx, double offsety)
change the position of the additional geometry
void moveAdditionalGeometry (const Position &offset)
change the position of the additional geometry
virtual void openAdditionalDialog ()
open Additional Dialog
template<>
int parse (const std::string &string)
template<>
double parse (const std::string &string)
template<>
bool parse (const std::string &string)
template<>
std::string parse (const std::string &string)
template<>
SUMOVehicleClass parse (const std::string &string)
template<>
SUMOVehicleShape parse (const std::string &string)
template<>
std::vector< std::string > parse (const std::string &string)
template<>
std::vector< int > parse (const std::string &string)
template<>
std::vector< double > parse (const std::string &string)
template<>
std::vector< bool > parse (const std::string &string)
void setAdditionalID (const std::string &id)
set the ID of additional
void setFilename (std::string filename)
Set a new filename in detector.
void setFrequency (const double freq)
Set a new frequency in detector.
void setPositionInView (const Position &pos)
set new position in the view
void setPositionOverLane (double pos)
Set a new position of detector over lane.
bool unreferenced ()
void updateGeometry ()
update pre-computed geometry information
void writeAdditional (OutputDevice &device) const
writte additional element into a xml file
~GNEDetectorE1 ()
Destructor.
inherited from GUIGlObject
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from GNEAttributeCarrier
std::string getAttribute (SumoXMLAttr key) const
void setAttribute (SumoXMLAttr key, const std::string &value, GNEUndoList *undoList)
method for setting the attribute and letting the object perform additional changes
bool isValid (SumoXMLAttr key, const std::string &value)
method for checking if the key and their conrrespond attribute are valids
inherited from GNEAdditional
Returns the name of the parent object
Returns
This object's parent id
const std::string & getParentName () const
Returns the name of the parent object (if any)
inherited from GUIGlObject
Returns the name (ID) of the parent object
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static const std::vector< std::pair< SumoXMLAttr, std::string > > & allowedAttributes (SumoXMLTag tag)
get all editable attributes for tag and their default values.
static const std::vector< SumoXMLTag > & allowedTags (bool net)
get all editable for tag (net or additional).
template<typename T >
static bool canParse (const std::string &string)
true if a number of type T can be parsed from string
static const std::vector< std::string > & discreteChoices (SumoXMLTag tag, SumoXMLAttr attr)
return a list of discrete choices for this attribute or an empty vector
static bool discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr)
return whether the given attribute allows for a combination of discrete values
static std::string getAttributeType (SumoXMLTag tag, SumoXMLAttr attr)
get type of attribute
template<typename T >
static T getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
return the default value of the attribute of an element
static std::string getDefinition (SumoXMLTag tag, SumoXMLAttr attr)
return definition of a certain SumoXMLAttr
static int getHigherNumberOfAttributes ()
return the number of attributes of the tag with the most highter number of attributes
static bool hasAttribute (SumoXMLTag tag, SumoXMLAttr attr)
check if an element with certain tag has a certain attribute
static bool hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
check if attribute of an element has a default avlue
static bool isBool (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool for a certain tag
static bool isDiscrete (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is Discrete
static bool isFilename (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a filename
static bool isFloat (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical of type float
static bool isInt (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical or type int
static bool isList (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool
static bool isNonEditable (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is non editable
static bool isNumerical (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical (int or float)
static bool isPositive (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is only Positive (i.e. cannot take negative values)
template<typename T >
static bool isPositive (const std::string &string)
true if a positive number of type T can be parsed from string
static bool isProbability (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is a probability (i.e. oly can values between [0, 1])
static bool isString (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type string
static bool isTime (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is time
static bool isUnique (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
static bool isValidFilename (const std::string &value)
true if value is a valid file value
static bool isValidID (const std::string &value)
true if value is a valid sumo ID
template<typename T >
static T parse (const std::string &string)
parses a number of type T from string
Static Public Attributes
static const std::string APPROVED = "approved"
feature has been approved but not changed (i.e. after being reguessed)
static const std::string GUESSED = "guessed"
feature has been reguessed (may still be unchanged be we can't tell (yet)
static const GUIGlID INVALID_ID = 0
static const std::string LOADED = "loaded"
feature is still unchanged after being loaded (implies approval)
static const std::string MODIFIED = "modified"
feature has been manually modified (implies approval)
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void changeEdge (const std::string &edgeID)
change edge of additional
void changeLane (const std::string &laneID)
change lane of additional
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
GNEAdditionalDialog * myAdditionalDialog
pointer to additional dialog
RGBColor myBaseColor
base color (Default green)
RGBColor myBaseColorSelected
base color selected (Default blue)
bool myBlocked
boolean to check if additional element is blocked (i.e. cannot be moved with mouse)
std::vector< std::vector< Position > > myConnectionPositions
Matrix with the Vertex's positions of connections between Additional Parent an their childs.
GNEEdge * myEdge
The edge this additional belongs.
std::string myFilename
The path to the output file.
double myFreq
The aggregation period the values the detector collects shall be summed up.
bool myInspectionable
boolean to check if additional element is inspectionable (With GNEInspectorFrame). By default true
GNELane * myLane
The lane this additional belongs.
bool myMovable
boolean to check if additional element is movable (with the mouse). By default true
Position myPosition
The position in which this additional element is located.
bool myRotationLefthand
rotation depending of the option "Lefthand"
bool mySelectable
boolean to check if additional element is selectable (With GNESelectorFrame). By default true
PositionVector myShape
The shape of the additional element.
bool mySplitByType
attribute to enable or disable splitByType
GNEViewNet * myViewNet
The GNEViewNet this additional element belongs.
computed only once (for performance) in updateGeometry()
The rotations of the shape parts
std::vector< double > myShapeRotations
std::vector< double > myShapeLengths
The lengths of the shape parts.
Private Member Functions
GNEDetectorE1 (const GNEDetectorE1 &)
Invalidated copy constructor.
GNEDetectorE1 & operator= (const GNEDetectorE1 &)
Invalidated assignment operator.
void setAttribute (SumoXMLAttr key, const std::string &value)
set attribute after validation
members and functions relative to block icon
Position myBlockIconPosition
position of the block icon
Position myBlockIconOffset
The offSet of the block icon.
double myBlockIconRotation
The rotation of the block icon.
void setBlockIconRotation (GNELane *lane=NULL)
set Rotation of block Icon
void drawLockIcon (double size=0.5) const
draw lock icon
void drawParentAndChildrenConnections () const
draw connections between Parent and childrens
members and functions relative to detector icon
set Rotation of block Icon
Position myDetectorLogoOffset
The position of detector.
void drawDetectorIcon (const int GNELogoID, double sizex=0.5, double sizey=0.5) const
Detailed Description
Definition at line 47 of file GNEDetectorE1.h.
Constructor & Destructor Documentation
GNEDetectorE1::GNEDetectorE1 (const std::string & id, GNELane * lane, GNEViewNet * viewNet, double pos, double freq, const std::string & filename, bool splitByType)
Constructor.
Parameters
[in] id The storage of gl-ids to get the one for this lane representation from
[in] lane Lane of this StoppingPlace belongs
[in] viewNet pointer to GNEViewNet of this additional element belongs
[in] pos position of the detector on the lane
[in] freq the aggregation period the values the detector collects shall be summed up.
[in] filename The path to the output file.
[in] splitByType If set, the collected values will be additionally reported on per-vehicle type base.
Definition at line 62 of file GNEDetectorE1.cpp.
References GNEAdditional::myBaseColor, GNEAdditional::myBaseColorSelected, and updateGeometry().
GNEDetectorE1::~GNEDetectorE1 ()
Destructor.
Definition at line 73 of file GNEDetectorE1.cpp.
GNEDetectorE1::GNEDetectorE1 (const GNEDetectorE1 &) private
Invalidated copy constructor.
Member Function Documentation
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 256 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
const std::vector< std::pair< SumoXMLAttr, std::string > > & GNEAttributeCarrier::allowedAttributes (SumoXMLTag tag) static inherited
get all editable attributes for tag and their default values.
Definition at line 250 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, NODEFAULTVALUE, SUMO_ATTR_ACCEL, SUMO_ATTR_ACCELERATION, SUMO_ATTR_ALLOW, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, SUMO_TAG_VTYPE, and toString().
Referenced by GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAttributeCarrier::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNESelectorFrame::onCmdSelMBAttribute(), GNESelectorFrame::onCmdSelMBTag(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedTags (bool net) static inherited
get all editable for tag (net or additional).
Definition at line 481 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalTags, GNEAttributeCarrier::myAllowedNetElementTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAdditionalFrame::GNEAdditionalFrame(), GNEAdditionalFrame::onCmdSelectAdditional(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 185 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 194 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 175 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 235 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 204 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 247 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 217 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 226 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
template<typename T > static bool GNEAttributeCarrier::canParse (const std::string & string) inline static inherited
true if a number of type T can be parsed from string
Definition at line 184 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::parse().
Referenced by GNECalibratorRoute::setEdges().
void GNEAdditional::changeEdge (const std::string & edgeID) protected inherited
change edge of additional
Exceptions
exception if additional doesn't belong to an edge
expcetion if edge doesn't exist
Definition at line 356 of file GNEAdditional.cpp.
References GNEEdge::addAdditionalChild(), GUIGlObject::getMicrosimID(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEAdditional::getViewNet(), GNEAdditional::myEdge, GNEEdge::removeAdditionalChild(), GNENet::retrieveEdge(), SUMO_TAG_EDGE, toString(), and GNEAdditional::updateGeometry().
Referenced by GNEVaporizer::setAttribute(), and GNERouteProbe::setAttribute().
void GNEAdditional::changeLane (const std::string & laneID) protected inherited
change lane of additional
Exceptions
exception if additional doesn't belong to a lane
expcetion if edge doesn't exist
Definition at line 370 of file GNEAdditional.cpp.
References GNELane::addAdditionalChild(), GUIGlObject::getMicrosimID(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEAdditional::getViewNet(), GNEAdditional::myLane, GNELane::removeAdditionalChild(), GNENet::retrieveLane(), SUMO_TAG_LANE, toString(), and GNEAdditional::updateGeometry().
Referenced by setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorEntry::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNEChargingStation::setAttribute(), and GNECalibrator::setAttribute().
void GNEDetector::commmitAdditionalGeometryMoved (double oldPosx, double , GNEUndoList * undoList) virtual inherited
updated geometry changes in the attributes of additional
Implements GNEAdditional.
Definition at line 97 of file GNEDetector.cpp.
References GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::GNEChange_Attribute, GNEAdditional::myPosition, GNEAdditional::myViewNet, GNEUndoList::p_add(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::refreshAdditional(), SUMO_ATTR_POSITION, toString(), and Position::x().
void GNEAdditional::commmitAdditionalGeometryMoved (const Position & oldPos, GNEUndoList * undoList) inherited
updated geometry changes in the attributes of additional
Parameters
[in] oldPos old position X of additional
[in] undoList The undoList on which to register changes
Note
simply call function commmitAdditionalGeometryMoved(double oldPosx, double oldPosy, GNEUndoList* undoList)
Definition at line 93 of file GNEAdditional.cpp.
References GNEViewNet::getNet(), GNEAdditional::myViewNet, GNENet::refreshAdditional(), Position::x(), and Position::y().
Referenced by GNEViewNet::onLeftBtnRelease().
void GNEReferenceCounter::decRef (const std::string & debugMsg = "") inline inherited
Definition at line 61 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_TLS::~GNEChange_TLS(), and GNEInspectorFrame::~GNEInspectorFrame().
const std::vector< std::string > & GNEAttributeCarrier::discreteChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return a list of discrete choices for this attribute or an empty vector
Definition at line 946 of file GNEAttributeCarrier.cpp.
References StringBijection< T >::getStrings(), SUMOXMLDefinitions::LaneSpreadFunctions, GNEAttributeCarrier::myDiscreteChoices, NODETYPE_DEAD_END_DEPRECATED, SUMOXMLDefinitions::NodeTypes, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_GUISHAPE, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, SUMO_ATTR_VCLASS, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_VTYPE, SumoVehicleClassStrings, SumoVehicleShapeStrings, TLTYPE_INVALID, toString(), and SUMOXMLDefinitions::TrafficLightTypes.
Referenced by GNEAttributeCarrier::isDiscrete(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return whether the given attribute allows for a combination of discrete values
Definition at line 1003 of file GNEAttributeCarrier.cpp.
References SUMO_ATTR_ALLOW, and SUMO_ATTR_DISALLOW.
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GNEDetector::drawDetectorIcon (const int GNELogoID, double sizex = 0.5, double sizey = 0.5) const protected inherited
Definition at line 159 of file GNEDetector.cpp.
References GUITexturesHelper::drawTexturedBox(), PositionVector::getLineCenter(), GUIGlObject::getType(), GNEAdditional::myBlockIconRotation, GNEDetector::myDetectorLogoOffset, GNEAdditional::myShape, Position::x(), and Position::y().
Referenced by drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), and GNEDetectorE2::drawGL().
void GNEDetectorE1::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GNEDetector.
Definition at line 142 of file GNEDetectorE1.cpp.
References GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GNEDetector::drawDetectorIcon(), GNEAdditional::drawLockIcon(), GUIGlObject::drawName(), GNEAdditional::getCenteringBoundary(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), GUITextureSubSys::getTexture(), GUIGlObject::getType(), GNETEXTURE_E1, GNEAdditional::myShape, GNEAdditional::myShapeRotations, and GUIVisualizationSettings::scale.
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 154 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GNEAdditional::drawLockIcon (double size = 0.5) const protected inherited
draw lock icon
Definition at line 291 of file GNEAdditional.cpp.
References GUITexturesHelper::drawTexturedBox(), GUITextureSubSys::getTexture(), GUIGlObject::getType(), GNETEXTURE_EMPTY, GNETEXTURE_EMPTYSELECTED, GNETEXTURE_LOCK, GNETEXTURE_LOCKSELECTED, GNETEXTURE_NOTMOVING, GNETEXTURE_NOTMOVINGSELECTED, GNEAdditional::isAdditionalSelected(), GNEAdditional::myBlocked, GNEAdditional::myBlockIconOffset, GNEAdditional::myBlockIconPosition, GNEAdditional::myBlockIconRotation, GNEAdditional::myMovable, GNEAdditional::myViewNet, GNEViewNet::showLockIcon(), Position::x(), and Position::y().
Referenced by drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GNERerouter::drawGL(), GNEChargingStation::drawGL(), and GNEDetectorE3::drawGL().
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 284 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), GNEEdge::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
void GNEAdditional::drawParentAndChildrenConnections () const protected inherited
draw connections between Parent and childrens
Definition at line 336 of file GNEAdditional.cpp.
References GLHelper::drawLine(), GUIGlObject::getType(), GNEAdditional::myConnectionPositions, and GLHelper::setColor().
Referenced by GNEDetectorE3::drawGL().
const std::string & GNEAdditional::getAdditionalID () const inherited
returns the ID of additional
Definition at line 105 of file GNEAdditional.cpp.
References GUIGlObject::getMicrosimID().
Referenced by getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE2::getAttribute(), GNEBusStop::getAttribute(), GNEContainerStop::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERouteProbe::getAttribute(), GNERerouter::getAttribute(), GNEChargingStation::getAttribute(), GNEDetectorE3::getAttribute(), and GNECalibrator::getAttribute().
std::string GNEDetectorE1::getAttribute (SumoXMLAttr key) const virtual
Implements GNEDetector.
Definition at line 210 of file GNEDetectorE1.cpp.
References GNEAdditional::getAdditionalID(), GNELane::getAttribute(), GNEAttributeCarrier::getTag(), GNE_ATTR_BLOCK_MOVEMENT, GNEAdditional::myBlocked, GNEDetector::myFilename, GNEDetector::myFreq, GNEAdditional::myLane, GNEAdditional::myPosition, mySplitByType, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SPLIT_VTYPE, toString(), and Position::x().
Referenced by setAttribute().
std::string GNEAttributeCarrier::getAttributeType (SumoXMLTag tag, SumoXMLAttr attr) static inherited
get type of attribute
Definition at line 212 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isList(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), and toString().
Referenced by GNEAdditionalHandler::getParsedAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
std::vector< SumoXMLAttr > GNEAttributeCarrier::getAttrs () const inherited
get vector of attributes
Definition at line 196 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::myTag.
Referenced by GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), GNEAttributeCarrier::isValid(), and GNEAttributeCarrier::~GNEAttributeCarrier().
Boundary GNEAdditional::getCenteringBoundary () const virtual inherited
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
Implements GUIGlObject.
Definition at line 268 of file GNEAdditional.cpp.
References PositionVector::getBoxBoundary(), Boundary::grow(), and GNEAdditional::myShape.
Referenced by drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GNERerouter::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), and GNECalibrator::drawGL().
template<typename T > static T GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return the default value of the attribute of an element
Note
It's advisable to check before with function hasDefaultValue if exits a default value
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
template<> int GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1217 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> double GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1229 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> bool GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1241 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> std::string GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1253 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> SUMOVehicleClass GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1265 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> SUMOVehicleShape GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1278 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> std::vector<int> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1290 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> std::vector<double> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1302 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> std::vector<bool> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1314 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, NODEFAULTVALUE, and toString().
template<> std::vector<std::string> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1326 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, and toString().
std::string GNEAttributeCarrier::getDefinition (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return definition of a certain SumoXMLAttr
Definition at line 1009 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAttrDefinitions, SUMO_ATTR_ACCEL, SUMO_ATTR_ALLOW, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_TLID, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VSS, and SUMO_TAG_VTYPE.
Referenced by GNECrossingFrame::crossingParameters::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), and GNEAttributeCarrier::~GNEAttributeCarrier().
std::string GNEAttributeCarrier::getDescription () virtual inherited
how should this attribute carrier be called
Definition at line 172 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag, and toString().
Referenced by GNEChange_Attribute::redoName(), GNEAdditionalFrame::removeAdditional(), GNEChange_Attribute::undoName(), and GNEAttributeCarrier::~GNEAttributeCarrier().
GNEEdge * GNEAdditional::getEdge () const inherited
get edge of additional, or NULL if additional isn't placed over an edge
Definition at line 169 of file GNEAdditional.cpp.
References GNEAdditional::myEdge.
Referenced by GNEChange_Additional::redo(), and GNEChange_Additional::undo().
std::string GNEDetector::getFilename () const inherited
returns the path to the output file
Definition at line 119 of file GNEDetector.cpp.
References GNEDetector::myFilename.
double GNEDetector::getFrequency () const inherited
returns the aggregation period the values the detector collects shall be summed up.
Definition at line 113 of file GNEDetector.cpp.
References GNEDetector::myFreq.
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 121 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEInternalLane::drawGL(), GNEJunction::drawGL(), GNECrossing::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdRevertRestriction(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
GUIIcon GNEAttributeCarrier::getGUIIcon () const inherited
get GUI icon assigned to this object
Definition at line 190 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myIcon.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
int GNEAttributeCarrier::getHigherNumberOfAttributes () static inherited
return the number of attributes of the tag with the most highter number of attributes
Definition at line 1201 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::allowedTags(), MAX2(), GNEAttributeCarrier::myAllowedAdditionalTags, GNEAttributeCarrier::myAllowedNetElementTags, and GNEAttributeCarrier::myMaxNumAttribute.
Referenced by GNEInspectorFrame::GNEInspectorFrame(), and GNEAttributeCarrier::~GNEAttributeCarrier().
FXIcon * GNEAttributeCarrier::getIcon () const inherited
get FXIcon assigned to this object
Definition at line 184 of file GNEAttributeCarrier.cpp.
References GUIIconSubSys::getIcon(), and GNEAttributeCarrier::myIcon.
Referenced by GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNEDeleteFrame::markAttributeCarrier(), GNEDeleteFrame::showAttributeCarrierChilds(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::updateCurrentLabel(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::string GNEAttributeCarrier::getID () const virtual inherited
function to support debugging
Implements GNEReferenceCounter.
Definition at line 206 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute(), and SUMO_ATTR_ID.
Referenced by GNEAdditionalFrame::addAdditional(), GNELane::addAdditionalChild(), GNEEdge::addAdditionalChild(), GNECrossingFrame::addCrossing(), GNERerouter::addEdgeChild(), GNEDetectorE3::addEntryChild(), GNEDetectorE3::addExitChild(), GNEEdge::addGNERerouter(), GNEJunction::addIncomingGNEEdge(), GNEJunction::addOutgoingGNEEdge(), GNENet::addReversedEdge(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::checkAdditionalParent(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), GNEVaporizer::getAttribute(), GNERouteProbe::getAttribute(), GNEConnection::getAttribute(), GNECalibrator::getAttribute(), GNEJunction::getAttribute(), GNECalibrator::getCalibratorFlow(), GNECalibrator::getCalibratorRoute(), GNECalibrator::getCalibratorVehicleType(), GNEAdditionalHandler::getPosition(), GNENet::insertAdditional(), GNERerouterInterval::insertClosingReroutes(), GNERerouterInterval::insertClosinLanegReroutes(), GNERerouterInterval::insertDestProbReroutes(), GNEDeleteFrame::markAttributeCarrier(), GNECrossingFrame::crossingParameters::markEdge(), GNEAdditionalHandler::parseVariableSpeedSignStep(), GNEChange_Junction::redo(), GNEChange_TLS::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), GNENet::refreshAdditional(), GNELane::removeAdditionalChild(), GNEEdge::removeAdditionalChild(), GNEDeleteFrame::removeAttributeCarrier(), GNERerouterInterval::removeClosingLaneReroutes(), GNERerouterInterval::removeClosingReroutes(), GNERerouterInterval::removeDestProbReroutes(), GNERerouter::removeEdgeChild(), GNEDetectorE3::removeEntryChild(), GNEDetectorE3::removeExitChild(), GNEEdge::removeGNERerouter(), GNEJunction::removeIncomingGNEEdge(), GNEJunction::removeOutgoingGNEEdge(), GNEAdditionalHandler::resetLastTag(), GNENet::reverseEdge(), GNERerouter::setAttribute(), GNEChange_Junction::undo(), GNEChange_TLS::undo(), GNEChange_Lane::undo(), GNEChange_Connection::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), GNENet::updateAdditionalID(), GNEDeleteFrame::updateCurrentLabel(), writeAdditional(), GNEChargingStation::writeAdditional(), GNEVaporizer::writeAdditional(), GNEDetectorE2::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNERouteProbe::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), and GNEChange_TLS::~GNEChange_TLS().
GNELane * GNEAdditional::getLane () const inherited
get lane of additional, or NULL if additional isn't placed over a Lane
Definition at line 175 of file GNEAdditional.cpp.
References GNEAdditional::myLane.
Referenced by GNEViewNet::onLeftBtnPress(), GNEViewNet::onLeftBtnRelease(), GNEViewNet::onMouseMove(), GNEChange_Additional::redo(), and GNEChange_Additional::undo().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 135 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNEJunction::getAttribute(), GNELane::getAttribute(), GNENetElement::getParentName(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSign::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNERerouter::getParentName(), GNEDetector::getParentName(), GNEDetectorE3::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEPoly::moveGeometry(), GNEEdge::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
GUIParameterTableWindow * GNEAdditional::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
complet with the rest of parameters
Implements GUIGlObject.
Definition at line 244 of file GNEAdditional.cpp.
References GUIParameterTableWindow::closeBuilding(), GNEAdditional::getAttribute(), GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::isUnique(), GUIParameterTableWindow::mkItem(), toString(), and UNUSED_PARAMETER.
const std::string & GNEDetector::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Implements GNEAdditional.
Definition at line 153 of file GNEDetector.cpp.
References GUIGlObject::getMicrosimID(), and GNEAdditional::myLane.
GUIGLObjectPopupMenu * GNEAdditional::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 186 of file GNEAdditional.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GNEAttributeCarrier::getAttrs(), GNEEdge::getLanes(), GUIGlObject::getMicrosimID(), GNEViewNet::getNet(), GNEAdditional::getParentName(), GUISUMOAbstractView::getPositionInformation(), GNELane::getShape(), GNEAttributeCarrier::getTag(), MID_COPY_NAME, MID_COPY_TYPED_NAME, GNEAdditional::myPosition, GNEAdditional::myShape, GNEAdditional::myViewNet, PositionVector::nearest_offset_to_point2D(), GNENet::retrieveEdge(), GNENet::retrieveLane(), SUMO_ATTR_EDGE, SUMO_ATTR_LANE, SUMO_TAG_LANE, toString(), Position::x(), and Position::y().
Position GNEDetectorE1::getPositionInView () const virtual
Returns position of detector E1 in view.
Implements GNEDetector.
Definition at line 116 of file GNEDetectorE1.cpp.
References GNELane::getPositionRelativeToParametricLength(), GNELane::getShape(), GNEAdditional::myLane, GNEAdditional::myPosition, PositionVector::positionAtOffset(), and Position::x().
double GNEDetector::getPositionOverLane () const inherited
Returns the position of the detector over lane.
Definition at line 107 of file GNEDetector.cpp.
References GNEAdditional::myPosition, and Position::x().
PositionVector GNEAdditional::getShape () const inherited
Returns additional element's shape.
Definition at line 117 of file GNEAdditional.cpp.
References GNEAdditional::myShape.
SumoXMLTag GNEAttributeCarrier::getTag () const inherited
get XML Tag assigned to this object
Definition at line 178 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag.
Referenced by GNELane::addAdditionalChild(), GNEEdge::addAdditionalChild(), GNERerouter::addEdgeChild(), GNEEdge::addGNERerouter(), GNEJunction::addIncomingGNEEdge(), GNEJunction::addOutgoingGNEEdge(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNEAdditionalHandler::checkAdditionalParent(), GNEVariableSpeedSign::commmitAdditionalGeometryMoved(), GNEDetector::commmitAdditionalGeometryMoved(), GNEStoppingPlace::commmitAdditionalGeometryMoved(), GNERerouter::commmitAdditionalGeometryMoved(), GNEDetectorE3::commmitAdditionalGeometryMoved(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE2::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNECrossing::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERouteProbe::getAttribute(), GNERerouter::getAttribute(), GNEChargingStation::getAttribute(), GNEDetectorE3::getAttribute(), GNEConnection::getAttribute(), GNEEdge::getAttribute(), GNECalibrator::getAttribute(), GNEJunction::getAttribute(), GNELane::getAttribute(), GNECalibrator::getCalibratorFlow(), GNECalibrator::getCalibratorRoute(), GNECalibrator::getCalibratorVehicleType(), GNESelectorFrame::getMatches(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), GNEEdge::getRouteProbeRelativePosition(), GNEEdge::getVaporizerRelativePosition(), GNENet::insertAdditional(), isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE2::isValid(), GNEBusStop::isValid(), GNEContainerStop::isValid(), GNECrossing::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSign::isValid(), GNERouteProbe::isValid(), GNERerouter::isValid(), GNEChargingStation::isValid(), GNEDetectorE3::isValid(), GNEConnection::isValid(), GNEEdge::isValid(), GNECalibrator::isValid(), GNEJunction::isValid(), GNELane::isValid(), GNEDeleteFrame::markAttributeCarrier(), GNEDetector::moveAdditionalGeometry(), GNECalibratorRouteDialog::onCmdAccept(), GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), GNEViewNet::onLeftBtnPress(), GNEAdditionalHandler::parseAndBuildDetectorE3(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), GNEAdditionalHandler::parseVariableSpeedSignStep(), GNEChange_Junction::redo(), GNEChange_TLS::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Additional::redoName(), GNENet::refreshAdditional(), GNELane::removeAdditionalChild(), GNEEdge::removeAdditionalChild(), GNEDeleteFrame::removeAttributeCarrier(), GNERerouter::removeEdgeChild(), GNEEdge::removeGNERerouter(), GNEJunction::removeIncomingGNEEdge(), GNEEdge::removeLane(), GNEJunction::removeOutgoingGNEEdge(), GNEAdditionalHandler::resetLastTag(), setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE2::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNECrossing::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNERouteProbe::setAttribute(), GNERerouter::setAttribute(), GNEChargingStation::setAttribute(), GNEDetectorE3::setAttribute(), GNEConnection::setAttribute(), GNEEdge::setAttribute(), GNECalibrator::setAttribute(), GNEJunction::setAttribute(), GNELane::setAttribute(), GNEDetector::setPositionOverLane(), GNEDeleteFrame::showAttributeCarrierChilds(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEChange_Junction::undo(), GNEChange_TLS::undo(), GNEChange_Lane::undo(), GNEChange_Connection::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Additional::undoName(), GNENet::updateAdditionalID(), GNEDeleteFrame::updateCurrentLabel(), writeAdditional(), GNEChargingStation::writeAdditional(), GNEVaporizer::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERouteProbe::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), and GNEChange_TLS::~GNEChange_TLS().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 148 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEDetector::drawDetectorIcon(), drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNECrossing::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEAdditional::drawParentAndChildrenConnections(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, and GUIPerson.
Definition at line 127 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
GNEViewNet * GNEAdditional::getViewNet () const inherited
Returns a pointer to GNEViewNet in which additional element is located.
Definition at line 111 of file GNEAdditional.cpp.
References GNEAdditional::myViewNet.
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNECalibratorRoute::checkEdgeRoute(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEChargingStation::isValid(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), GNECalibratorDialog::onCmdClickedRoute(), GNECalibratorDialog::onCmdClickedVehicleType(), GNERerouterIntervalDialog::onCmdEditClosingLaneReroute(), GNERerouterIntervalDialog::onCmdEditClosingReroute(), GNERerouterIntervalDialog::onCmdEditDestProbReroute(), setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNEChargingStation::setAttribute(), GNERerouter::setAttribute(), GNEDetectorE3::setAttribute(), GNECalibrator::setAttribute(), GNECalibratorRoute::setEdges(), GNECalibratorFlow::setFlowID(), GNECalibratorFlow::setRoute(), GNECalibratorRoute::setRouteID(), GNECalibratorFlow::setVehicleType(), and GNECalibratorVehicleType::setVehicleTypeID().
bool GNEAttributeCarrier::hasAttribute (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if an element with certain tag has a certain attribute
Definition at line 917 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes().
Referenced by GNEAdditionalFrame::addAdditional(), GNEDetector::moveAdditionalGeometry(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if attribute of an element has a default avlue
Definition at line 930 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
Referenced by GNEAdditionalHandler::getParsedAttribute(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GNEReferenceCounter::incRef (const std::string & debugMsg = "") inline inherited
Definition at line 73 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNEEdge::addLane(), GNENet::registerEdge(), GNENet::registerJunction(), GNEEdge::remakeGNEConnections(), and GNEInspectorFrame::setEdgeTemplate().
bool GNEAdditional::isAdditionalBlocked () const inherited
Check if additional item is currently blocked (i.e. cannot be moved with mouse)
Definition at line 123 of file GNEAdditional.cpp.
References GNEAdditional::myBlocked.
Referenced by GNEInspectorFrame::inspectMultisection(), and GNEViewNet::onLeftBtnPress().
bool GNEAdditional::isAdditionalInspectionable () const inherited
check if additional element is inspectionable (With GNEInspectorFrame)
Definition at line 129 of file GNEAdditional.cpp.
References GNEAdditional::myInspectionable.
bool GNEAdditional::isAdditionalMovable () const inherited
check if additional element is movable
Definition at line 141 of file GNEAdditional.cpp.
References GNEAdditional::myMovable.
Referenced by GNEInspectorFrame::inspectMultisection().
bool GNEAdditional::isAdditionalSelectable () const inherited
check if additional element is selectable (With GNESelectorFrame)
Definition at line 135 of file GNEAdditional.cpp.
References GNEAdditional::mySelectable.
bool GNEAdditional::isAdditionalSelected () const inherited
Definition at line 147 of file GNEAdditional.cpp.
References GUIGlObject::getGlID(), GUIGlObject::getType(), gSelected, and GUISelectedStorage::isSelected().
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GNERerouter::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), and GNEAdditional::drawLockIcon().
bool GNEAttributeCarrier::isBool (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool for a certain tag
Definition at line 642 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBoolAttrs, SUMO_ATTR_ACCELERATION, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CONT, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_OFF, SUMO_ATTR_PASS, SUMO_ATTR_PRIORITY, SUMO_ATTR_REROUTE, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_UNCONTROLLED, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, and SUMO_TAG_REROUTER.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isDiscrete (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is Discrete
Definition at line 775 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::discreteChoices().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isFilename (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a filename
Definition at line 876 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, SUMO_ATTR_FILE, SUMO_ATTR_OUTPUT, SUMO_TAG_CALIBRATOR, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalHandler::getParsedAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isFloat (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical of type float
Definition at line 541 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalFloatAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERIOD, SUMO_ATTR_POSITION, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_REROUTER, SUMO_TAG_STEP, and SUMO_TAG_VTYPE.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalHandler::getParsedAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isInt (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical or type int
Definition at line 516 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalIntAttrs, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_FROM_LANE, SUMO_ATTR_INDEX, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_LANE, and SUMO_TAG_VTYPE.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalHandler::getParsedAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isList (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 676 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myListAttrs, SUMO_ATTR_EDGES, SUMO_ATTR_LANES, SUMO_ATTR_LINES, SUMO_TAG_BUS_STOP, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isNonEditable (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is non editable
Definition at line 899 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNonEditableAttrs, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isNumerical (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical (int or float)
Definition at line 510 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isInt().
Referenced by GNESelectorFrame::getMatches(), GNEAttributeCarrier::isString(), GNESelectorFrame::onCmdSelMBString(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isPositive (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is only Positive (i.e. cannot take negative values)
Definition at line 785 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myPositiveAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, and SUMO_TAG_VTYPE.
Referenced by GNEAdditionalHandler::getParsedAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
template<typename T > static bool GNEAttributeCarrier::isPositive (const std::string & string) inline static inherited
true if a positive number of type T can be parsed from string
Definition at line 203 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::isValidFilename(), and GNEAttributeCarrier::isValidID().
bool GNEAttributeCarrier::isProbability (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is a probability (i.e. oly can values between [0, 1])
Definition at line 861 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myProbabilityAttrs, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_PROB, SUMO_TAG_CHARGING_STATION, SUMO_TAG_FLOW, and SUMO_TAG_REROUTER.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isString (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type string
Definition at line 670 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isNumerical(), and GNEAttributeCarrier::isTime().
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isTime (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is time
Definition at line 607 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTimeAttrs, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_END, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_STARTTIME, SUMO_ATTR_TIME, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, and SUMO_TAG_VTYPE.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalHandler::getParsedAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isUnique (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
Definition at line 697 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myUniqueAttrs, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_OUTPUT, SUMO_ATTR_POSITION, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TLID, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_POI, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAdditional::getParameterWindow(), GNEInspectorFrame::inspectMultisection(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEDetectorE1::isValid (SumoXMLAttr key, const std::string & value) virtual
method for checking if the key and their conrrespond attribute are valids
Parameters
[in] key The attribute key
[in] value The value asociated to key key
Returns
true if the value is valid, false in other case
Implements GNEDetector.
Definition at line 256 of file GNEDetectorE1.cpp.
References GNENet::getAdditional(), GNELane::getLaneParametricLength(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNE_ATTR_BLOCK_MOVEMENT, GNEAttributeCarrier::isValidFilename(), GNEAdditional::myLane, GNEAdditional::myViewNet, GNENet::retrieveLane(), SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SPLIT_VTYPE, and toString().
bool GNEAttributeCarrier::isValidFilename (const std::string & value) static inherited
true if value is a valid file value
Definition at line 238 of file GNEAttributeCarrier.cpp.
Referenced by GNEAdditionalHandler::getParsedAttribute(), GNEAttributeCarrier::isPositive(), isValid(), GNEDetectorE2::isValid(), GNEVariableSpeedSign::isValid(), GNERouteProbe::isValid(), GNERerouter::isValid(), GNEDetectorE3::isValid(), GNECalibrator::isValid(), and GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute().
bool GNEAttributeCarrier::isValidID (const std::string & value) static inherited
true if value is a valid sumo ID
Definition at line 232 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNEEdge::isValid(), and GNEJunction::isValid().
void GNEDetector::moveAdditionalGeometry (double offsetx, double offsety) virtual inherited
change the position of the additional geometry
Implements GNEAdditional.
Definition at line 76 of file GNEDetector.cpp.
References GNEDetector::getAttribute(), GNELane::getLaneShapeLength(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::hasAttribute(), GNEAdditional::myLane, GNEAdditional::myPosition, Position::set(), SUMO_ATTR_LENGTH, UNUSED_PARAMETER, GNEDetector::updateGeometry(), and Position::x().
void GNEAdditional::moveAdditionalGeometry (const Position & offset) inherited
change the position of the additional geometry
Parameters
[in] offset offset of movement
Note
simply call the function moveAdditionalGeometry(double offsetx, double offsety)
Definition at line 87 of file GNEAdditional.cpp.
References Position::x(), and Position::y().
Referenced by GNEViewNet::onMouseMove().
void GNEAdditional::openAdditionalDialog () virtual inherited
open Additional Dialog
Note
: if additional needs an additional dialog, this function has to be implemented in childrens (see GNERerouter and GNEVariableSpeedSign)
Reimplemented in GNECalibrator, GNERerouter, and GNEVariableSpeedSign.
Definition at line 101 of file GNEAdditional.cpp.
Referenced by GNEViewNet::onDoubleClicked().
GNEDetectorE1& GNEDetectorE1::operator= (const GNEDetectorE1 &) private
Invalidated assignment operator.
template<> int GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 76 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2int().
template<> double GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 82 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2double().
template<> bool GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 88 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2Bool().
template<> std::string GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 94 of file GNEAttributeCarrier.cpp.
template<> SUMOVehicleClass GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 100 of file GNEAttributeCarrier.cpp.
References SumoVehicleClassStrings, and SVC_IGNORING.
template<> SUMOVehicleShape GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 112 of file GNEAttributeCarrier.cpp.
References SumoVehicleShapeStrings, and SVS_UNKNOWN.
template<> std::vector<std::string> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 124 of file GNEAttributeCarrier.cpp.
References SUMOSAXAttributes::parseStringVector().
template<> std::vector<int> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 132 of file GNEAttributeCarrier.cpp.
template<> std::vector<double> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 143 of file GNEAttributeCarrier.cpp.
template<> std::vector<bool> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 154 of file GNEAttributeCarrier.cpp.
template<typename T > static T GNEAttributeCarrier::parse (const std::string & string) static inherited
parses a number of type T from string
Referenced by GNEAttributeCarrier::canParse(), and GNECalibratorRoute::setEdges().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 262 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GNEAdditional::setAdditionalID (const std::string & id) inherited
set the ID of additional
Definition at line 153 of file GNEAdditional.cpp.
References GUIGlObject::getMicrosimID(), GNEViewNet::getNet(), GNEAdditional::myViewNet, GUIGlObject::setMicrosimID(), and GNENet::updateAdditionalID().
Referenced by setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNEVaporizer::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNERerouter::setAttribute(), GNEDetectorE3::setAttribute(), and GNECalibrator::setAttribute().
void GNEDetectorE1::setAttribute (SumoXMLAttr key, const std::string & value, GNEUndoList * undoList) virtual
method for setting the attribute and letting the object perform additional changes
Parameters
[in] key The attribute key
[in] value The new value
[in] undoList The undoList on which to register changes
Implements GNEDetector.
Definition at line 233 of file GNEDetectorE1.cpp.
References getAttribute(), GNEAttributeCarrier::getTag(), GNE_ATTR_BLOCK_MOVEMENT, GNEAttributeCarrier::GNEChange_Attribute, GNEUndoList::p_add(), SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SPLIT_VTYPE, toString(), and updateGeometry().
void GNEDetectorE1::setAttribute (SumoXMLAttr key, const std::string & value) private virtual
set attribute after validation
Implements GNEDetector.
Definition at line 290 of file GNEDetectorE1.cpp.
References GNEAdditional::changeLane(), GNEAttributeCarrier::getTag(), GNEAdditional::getViewNet(), GNE_ATTR_BLOCK_MOVEMENT, GNEAdditional::myBlocked, GNEDetector::myFilename, GNEDetector::myFreq, GNEAdditional::myPosition, mySplitByType, GNEAdditional::setAdditionalID(), SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SPLIT_VTYPE, toString(), and updateGeometry().
void GNEAdditional::setBlockIconRotation (GNELane * lane = NULL) protected inherited
set Rotation of block Icon
Note
must be called in updateGeometry() after setting of Shape, and use parameter "lane" if additional is placed over a lane
Definition at line 276 of file GNEAdditional.cpp.
References GNELane::getPositionRelativeToParametricLength(), GNELane::getShape(), PositionVector::length(), GNEAdditional::myBlockIconRotation, GNEAdditional::myPosition, GNEAdditional::myShape, PositionVector::rotationDegreeAtOffset(), and Position::x().
Referenced by GNEVariableSpeedSign::updateGeometry(), updateGeometry(), GNERerouter::updateGeometry(), GNEChargingStation::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNERouteProbe::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), and GNEDetectorExit::updateGeometryByParent().
void GNEDetector::setFilename (std::string filename) inherited
Set a new filename in detector.
Parameters
[in] filename new filename of detector
Definition at line 147 of file GNEDetector.cpp.
References GNEDetector::myFilename.
void GNEDetector::setFrequency (const double freq) inherited
Set a new frequency in detector.
Parameters
[in] freq new frequency of detector
Exceptions
InvalidArgument if value of frequency isn't valid
Definition at line 137 of file GNEDetector.cpp.
References GNEDetector::myFreq, and toString().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 141 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
void GNEAdditional::setPositionInView (const Position & pos) inherited
set new position in the view
Note
movement cannot be undo with GNEUndoRedo
Definition at line 163 of file GNEAdditional.cpp.
References GNEAdditional::myPosition.
void GNEDetector::setPositionOverLane (double pos) inherited
Set a new position of detector over lane.
Parameters
[in] pos new position of detector over lane
Exceptions
InvalidArgument if value of pos isn't valid
Definition at line 125 of file GNEDetector.cpp.
References GNELane::getLaneShapeLength(), GNEAttributeCarrier::getTag(), GNEAdditional::myLane, GNEAdditional::myPosition, and toString().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 271 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
bool GNEReferenceCounter::unreferenced () inline inherited
Definition at line 82 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), and GNEReferenceCounter::myCount.
Referenced by GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_TLS::~GNEChange_TLS(), and GNEInspectorFrame::~GNEInspectorFrame().
void GNEDetectorE1::updateGeometry () virtual
update pre-computed geometry information
Note
: must be called when geometry changes (i.e. lane moved)
Implements GNEDetector.
Definition at line 78 of file GNEDetectorE1.cpp.
References PositionVector::getLineCenter(), GNEViewNet::getNet(), GNELane::getPositionRelativeToParametricLength(), GNELane::getShape(), GNEAdditional::myBlockIconOffset, GNEAdditional::myBlockIconPosition, GNEDetector::myDetectorLogoOffset, GNEAdditional::myLane, GNEAdditional::myPosition, GNEAdditional::myShape, GNEAdditional::myShapeLengths, GNEAdditional::myShapeRotations, GNEAdditional::myViewNet, PositionVector::positionAtOffset(), GNENet::refreshAdditional(), PositionVector::rotationDegreeAtOffset(), GNEAdditional::setBlockIconRotation(), and Position::x().
Referenced by GNEDetectorE1(), and setAttribute().
void GNEDetectorE1::writeAdditional (OutputDevice & device) const virtual
writte additional element into a xml file
Parameters
[in] device device in which write parameters of additional element
Implements GNEDetector.
Definition at line 122 of file GNEDetectorE1.cpp.
References OutputDevice::closeTag(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNE_ATTR_BLOCK_MOVEMENT, GNEAdditional::myBlocked, GNEDetector::myFilename, GNEDetector::myFreq, GNEAdditional::myLane, GNEAdditional::myPosition, mySplitByType, OutputDevice::openTag(), SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SPLIT_VTYPE, OutputDevice::writeAttr(), and Position::x().
Field Documentation
const std::string GNEAttributeCarrier::APPROVED = "approved" static inherited
feature has been approved but not changed (i.e. after being reguessed)
Definition at line 223 of file GNEAttributeCarrier.h.
const std::string GNEAttributeCarrier::GUESSED = "guessed" static inherited
feature has been reguessed (may still be unchanged be we can't tell (yet)
Definition at line 217 of file GNEAttributeCarrier.h.
Referenced by GNEJunction::setAttribute(), and GNEEdge::setAttribute().
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
const std::string GNEAttributeCarrier::LOADED = "loaded" static inherited
feature is still unchanged after being loaded (implies approval)
Definition at line 214 of file GNEAttributeCarrier.h.
const std::string GNEAttributeCarrier::MODIFIED = "modified" static inherited
feature has been manually modified (implies approval)
Definition at line 220 of file GNEAttributeCarrier.h.
Referenced by GNEJunction::markAsModified(), and GNEConnectorFrame::onCmdClearSelectedConnections().
GNEAdditionalDialog* GNEAdditional::myAdditionalDialog protected inherited
pointer to additional dialog
Definition at line 314 of file GNEAdditional.h.
RGBColor GNEAdditional::myBaseColor protected inherited
base color (Default green)
Note
default color can be defined in the constructor of every additional
Definition at line 306 of file GNEAdditional.h.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEChargingStation::drawGL(), GNEBusStop::GNEBusStop(), GNECalibrator::GNECalibrator(), GNEChargingStation::GNEChargingStation(), GNEContainerStop::GNEContainerStop(), GNEDetectorE1(), GNEDetectorE2::GNEDetectorE2(), GNEDetectorE3::GNEDetectorE3(), GNEDetectorEntry::GNEDetectorEntry(), GNEDetectorExit::GNEDetectorExit(), GNERerouter::GNERerouter(), and GNEVariableSpeedSign::GNEVariableSpeedSign().
RGBColor GNEAdditional::myBaseColorSelected protected inherited
base color selected (Default blue)
Note
default color can be defined in the constructor of every additional
Definition at line 311 of file GNEAdditional.h.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEChargingStation::drawGL(), GNEBusStop::GNEBusStop(), GNECalibrator::GNECalibrator(), GNEChargingStation::GNEChargingStation(), GNEContainerStop::GNEContainerStop(), GNEDetectorE1(), GNEDetectorE2::GNEDetectorE2(), GNEDetectorE3::GNEDetectorE3(), GNEDetectorEntry::GNEDetectorEntry(), GNEDetectorExit::GNEDetectorExit(), GNERerouter::GNERerouter(), and GNEVariableSpeedSign::GNEVariableSpeedSign().
bool GNEAdditional::myBlocked protected inherited
boolean to check if additional element is blocked (i.e. cannot be moved with mouse)
Definition at line 292 of file GNEAdditional.h.
Referenced by GNEAdditional::drawLockIcon(), getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE2::getAttribute(), GNEBusStop::getAttribute(), GNEContainerStop::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERerouter::getAttribute(), GNEChargingStation::getAttribute(), GNEDetectorE3::getAttribute(), GNEAdditional::isAdditionalBlocked(), setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNEChargingStation::setAttribute(), GNERerouter::setAttribute(), GNEDetectorE3::setAttribute(), writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorE2::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), and GNERerouter::writeAdditional().
Position GNEAdditional::myBlockIconOffset protected inherited
The offSet of the block icon.
Definition at line 285 of file GNEAdditional.h.
Referenced by GNEAdditional::drawLockIcon(), GNEVariableSpeedSign::updateGeometry(), updateGeometry(), GNERerouter::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNERouteProbe::updateGeometry(), and GNEDetectorE3::updateGeometry().
Position GNEAdditional::myBlockIconPosition protected inherited
position of the block icon
Definition at line 282 of file GNEAdditional.h.
Referenced by GNEAdditional::drawLockIcon(), GNEVariableSpeedSign::updateGeometry(), updateGeometry(), GNERerouter::updateGeometry(), GNEChargingStation::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNERouteProbe::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), and GNEDetectorExit::updateGeometryByParent().
double GNEAdditional::myBlockIconRotation protected inherited
The rotation of the block icon.
Definition at line 288 of file GNEAdditional.h.
Referenced by GNEDetector::drawDetectorIcon(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEChargingStation::drawGL(), GNEAdditional::drawLockIcon(), and GNEAdditional::setBlockIconRotation().
std::vector<std::vector<Position> > GNEAdditional::myConnectionPositions protected inherited
Matrix with the Vertex's positions of connections between Additional Parent an their childs.
Definition at line 317 of file GNEAdditional.h.
Referenced by GNEAdditional::drawParentAndChildrenConnections(), and GNEDetectorE3::updateGeometryConnections().
Position GNEDetector::myDetectorLogoOffset protected inherited
The position of detector.
Definition at line 158 of file GNEDetector.h.
Referenced by GNEDetector::drawDetectorIcon(), updateGeometry(), GNEDetectorE2::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), and GNEDetectorExit::updateGeometryByParent().
GNEEdge* GNEAdditional::myEdge protected inherited
The edge this additional belongs.
Note
is NULL if additional doesnt' belongs to a edge
Definition at line 239 of file GNEAdditional.h.
Referenced by GNEAdditional::changeEdge(), GNEVaporizer::getAttribute(), GNERouteProbe::getAttribute(), GNEAdditional::getEdge(), GNEVaporizer::getParentName(), GNERouteProbe::getParentName(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GNEVaporizer::updateGeometry(), GNERouteProbe::updateGeometry(), GNEVaporizer::writeAdditional(), and GNERouteProbe::writeAdditional().
std::string GNEDetector::myFilename protected inherited
The path to the output file.
Definition at line 150 of file GNEDetector.h.
Referenced by getAttribute(), GNEDetectorE2::getAttribute(), GNEDetector::getFilename(), setAttribute(), GNEDetectorE2::setAttribute(), GNEDetector::setFilename(), writeAdditional(), and GNEDetectorE2::writeAdditional().
double GNEDetector::myFreq protected inherited
The aggregation period the values the detector collects shall be summed up.
Definition at line 147 of file GNEDetector.h.
Referenced by getAttribute(), GNEDetectorE2::getAttribute(), GNEDetector::getFrequency(), setAttribute(), GNEDetectorE2::setAttribute(), GNEDetector::setFrequency(), writeAdditional(), and GNEDetectorE2::writeAdditional().
bool GNEAdditional::myInspectionable protected inherited
boolean to check if additional element is inspectionable (With GNEInspectorFrame). By default true
Definition at line 295 of file GNEAdditional.h.
Referenced by GNEAdditional::isAdditionalInspectionable().
GNELane* GNEAdditional::myLane protected inherited
The lane this additional belongs.
Note
is NULL if additional doesnt' belongs to a lane
Definition at line 244 of file GNEAdditional.h.
Referenced by GNEAdditional::changeLane(), getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE2::getAttribute(), GNEBusStop::getAttribute(), GNEContainerStop::getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), GNEAdditional::getLane(), GNEStoppingPlace::getParentName(), GNEDetector::getParentName(), GNECalibrator::getParentName(), GNEDetectorExit::getPositionInView(), GNEDetectorEntry::getPositionInView(), getPositionInView(), GNEStoppingPlace::getPositionInView(), GNEDetectorE2::getPositionInView(), GNECalibrator::GNECalibrator(), GNEDetector::GNEDetector(), GNEStoppingPlace::GNEStoppingPlace(), isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEChargingStation::isValid(), GNEDetector::moveAdditionalGeometry(), GNEStoppingPlace::moveAdditionalGeometry(), GNEContainerStop::setAttribute(), GNEBusStop::setAttribute(), GNEChargingStation::setAttribute(), GNEStoppingPlace::setEndPosition(), GNEDetector::setPositionOverLane(), updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNECalibrator::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), GNEDetectorExit::updateGeometryByParent(), GNEChargingStation::writeAdditional(), writeAdditional(), GNEDetectorE2::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), and GNECalibrator::writeAdditional().
bool GNEAdditional::myMovable protected inherited
boolean to check if additional element is movable (with the mouse). By default true
Definition at line 301 of file GNEAdditional.h.
Referenced by GNEAdditional::drawLockIcon(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), and GNEAdditional::isAdditionalMovable().
Position GNEAdditional::myPosition protected inherited
The position in which this additional element is located.
Note
if this element belongs to a Lane, x() value will be the position over Lane
Definition at line 249 of file GNEAdditional.h.
Referenced by GNEVariableSpeedSign::commmitAdditionalGeometryMoved(), GNEDetector::commmitAdditionalGeometryMoved(), GNERerouter::commmitAdditionalGeometryMoved(), GNEDetectorE3::commmitAdditionalGeometryMoved(), getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE2::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERerouter::getAttribute(), GNEDetectorE3::getAttribute(), GNECalibrator::getAttribute(), GNEAdditional::getPopUpMenu(), GNEVariableSpeedSign::getPositionInView(), GNEDetectorExit::getPositionInView(), getPositionInView(), GNEDetectorEntry::getPositionInView(), GNERerouter::getPositionInView(), GNEStoppingPlace::getPositionInView(), GNEVaporizer::getPositionInView(), GNEDetectorE2::getPositionInView(), GNERouteProbe::getPositionInView(), GNEDetectorE3::getPositionInView(), GNECalibrator::getPositionInView(), GNEDetector::getPositionOverLane(), GNEVariableSpeedSign::moveAdditionalGeometry(), GNEDetector::moveAdditionalGeometry(), GNERerouter::moveAdditionalGeometry(), GNEDetectorE3::moveAdditionalGeometry(), setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE2::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNERerouter::setAttribute(), GNEDetectorE3::setAttribute(), GNECalibrator::setAttribute(), GNEAdditional::setBlockIconRotation(), GNEAdditional::setPositionInView(), GNEDetector::setPositionOverLane(), GNEVariableSpeedSign::updateGeometry(), updateGeometry(), GNERerouter::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEDetectorE3::updateGeometry(), GNECalibrator::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), GNEDetectorExit::updateGeometryByParent(), writeAdditional(), GNEDetectorE2::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), GNEDetectorE3::writeAdditional(), and GNECalibrator::writeAdditional().
bool GNEAdditional::myRotationLefthand protected inherited
rotation depending of the option "Lefthand"
Definition at line 266 of file GNEAdditional.h.
Referenced by GNEAdditional::GNEAdditional(), and GNEChargingStation::updateGeometry().
bool GNEAdditional::mySelectable protected inherited
boolean to check if additional element is selectable (With GNESelectorFrame). By default true
Definition at line 298 of file GNEAdditional.h.
Referenced by GNEAdditional::isAdditionalSelectable().
PositionVector GNEAdditional::myShape protected inherited
The shape of the additional element.
Note
must be configured in updateGeometry()
Definition at line 254 of file GNEAdditional.h.
Referenced by GNEDetector::drawDetectorIcon(), drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GNERerouter::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), GNECalibrator::drawGL(), GNEAdditional::getCenteringBoundary(), GNEAdditional::getPopUpMenu(), GNEAdditional::getShape(), GNEAdditional::setBlockIconRotation(), GNEVariableSpeedSign::updateGeometry(), updateGeometry(), GNERerouter::updateGeometry(), GNEChargingStation::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNERouteProbe::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNECalibrator::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), and GNEDetectorExit::updateGeometryByParent().
std::vector<double> GNEAdditional::myShapeLengths protected inherited
The lengths of the shape parts.
Definition at line 262 of file GNEAdditional.h.
Referenced by GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEChargingStation::drawGL(), updateGeometry(), GNEChargingStation::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEDetectorE3::updateGeometry(), GNERouteProbe::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), GNECalibrator::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), and GNEDetectorExit::updateGeometryByParent().
std::vector<double> GNEAdditional::myShapeRotations protected inherited
Definition at line 259 of file GNEAdditional.h.
Referenced by drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEVaporizer::drawGL(), GNERouteProbe::drawGL(), GNEChargingStation::drawGL(), GNECalibrator::drawGL(), updateGeometry(), GNEChargingStation::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNERouteProbe::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNECalibrator::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), and GNEDetectorExit::updateGeometryByParent().
bool GNEDetectorE1::mySplitByType protected
attribute to enable or disable splitByType
Definition at line 109 of file GNEDetectorE1.h.
Referenced by getAttribute(), setAttribute(), and writeAdditional().
GNEViewNet* GNEAdditional::myViewNet protected inherited
The GNEViewNet this additional element belongs.
Definition at line 234 of file GNEAdditional.h.
Referenced by GNEVariableSpeedSign::commmitAdditionalGeometryMoved(), GNEDetector::commmitAdditionalGeometryMoved(), GNEStoppingPlace::commmitAdditionalGeometryMoved(), GNERerouter::commmitAdditionalGeometryMoved(), GNEDetectorE3::commmitAdditionalGeometryMoved(), GNEAdditional::commmitAdditionalGeometryMoved(), GNEAdditional::drawLockIcon(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNECalibrator::generateFlowID(), GNECalibrator::generateRouteID(), GNECalibrator::generateVehicleTypeID(), GNEVariableSpeedSign::getParentName(), GNERerouter::getParentName(), GNEDetectorE3::getParentName(), GNEAdditional::getParentName(), GNEAdditional::getPopUpMenu(), GNEAdditional::getViewNet(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE2::isValid(), GNEBusStop::isValid(), GNEContainerStop::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSign::isValid(), GNERouteProbe::isValid(), GNERerouter::isValid(), GNEChargingStation::isValid(), GNEDetectorE3::isValid(), GNECalibrator::isValid(), GNEAdditional::setAdditionalID(), GNEVariableSpeedSign::setAttribute(), GNERerouter::setAttribute(), GNECalibrator::setAttribute(), GNEVariableSpeedSign::updateGeometry(), updateGeometry(), GNERerouter::updateGeometry(), GNEChargingStation::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNERouteProbe::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), GNECalibrator::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), and GNEDetectorExit::updateGeometryByParent().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GNEDetectorE1.h
GNEDetectorE1.cpp