SUMO - Simulation of Urban MObility: GNECalibratorFlow Class Reference
GNECalibratorFlow Class Reference
#include <GNECalibratorFlow.h>
Public Types
enum TypeOfFlow { GNE_CALIBRATORFLOW_INVALID, GNE_CALIBRATORFLOW_VEHSPERHOUR, GNE_CALIBRATORFLOW_PERIOD, GNE_CALIBRATORFLOW_PROBABILITY }
type of flow
Public Member Functions
const std::string & getArrivalLane () const
get arrival lane
const std::string & getArrivalPos () const
get arrival position
std::string getArrivalPosLat () const
const std::string & getArrivalSpeed () const
get arrival speed
GNECalibrator * getCalibratorParent () const
get pointer to calibrator parent
const std::string & getColor () const
get color of flow
int getContainerNumber () const
get number of containers
const std::string & getDepartLane () const
get depart lane
const std::string & getDepartPos () const
get depart position
std::string getDepartPosLat () const
get departPosLat
const std::string & getDepartSpeed () const
get arrival speed
const std::string & getFlowID () const
get ID of flow
const std::string & getLine () const
get line of busStop/containerStop
int getPersonNumber () const
get number of persons
bool getReroute () const
get reroute
const std::string & getRoute () const
get route in which this flow is used
SumoXMLTag getTag () const
get tag
const std::string & getVehicleType () const
get vehicle type of flow
GNECalibratorFlow (GNECalibrator *calibratorParent)
constructor
GNECalibratorFlow (GNECalibrator *calibratorParent, std::string flowID, std::string vehicleType, std::string route, std::string color, std::string departLane, std::string departPos, std::string departSpeed, std::string arrivalLane, std::string arrivalPos, std::string arrivalSpeed, std::string line, int personNumber, int containerNumber, bool reroute, std::string departPosLat, std::string arrivalPosLat, double begin, double end, double vehsPerHour, double period, double probability, int number)
parameter constructor
bool operator== (const GNECalibratorFlow &calibratorFlow) const
overload operator ==
bool setArrivalLane (std::string arrivalLane="current")
set arrival lane
bool setArrivalPos (std::string arrivalPos="max")
set arrival position
bool setArrivalPosLat (std::string arrivalPosLat="")
set arrivalPosLat
bool setArrivalSpeed (std::string arrivalSpeed="current")
set arrival speed
bool setColor (std::string color="")
set color of flow
bool setContainerNumber (int containerNumber=0)
set number of container
bool setContainerNumber (std::string containerNumber="0")
set number of container (string)
bool setDepartLane (std::string departLane="first")
set depart lane
bool setDepartPos (std::string departPos="base")
set depart position
bool setDepartPosLat (std::string departPosLat="center")
set departPosLat
bool setDepartSpeed (std::string departSpeed="0")
set depart speed
bool setFlowID (std::string ID)
set ID of flow
bool setLine (std::string line="")
set line of busStop/containerStop
bool setPersonNumber (int personNumber=0)
set number of persons
bool setPersonNumber (std::string personNumber="0")
set number of persons (String)
bool setReroute (bool value)
set reroute
bool setReroute (std::string value)
set reroute (string)
bool setRoute (std::string route)
set route in which this flow is used
bool setVehicleType (std::string vehicleType)
set vehicleType of flow
~GNECalibratorFlow ()
destructor
value specific of
get begin time step
{
double getBegin () const
double getEnd () const
get end time step
double getVehsPerHour () const
get flows per hour
double getPeriod () const
get period of flow
double getProbability () const
get probability of flow
int getNumber () const
get number of flows
TypeOfFlow getFlowType () const
get type of flow
values specific of Flows
bool setBegin (double begin)
set begin step
bool setBegin (std::string begin)
set begin step (string)
bool setEnd (double end)
set end step
bool setEnd (std::string end)
set end step (string)
bool setVehsPerHour (double vehsPerHour)
set flows per hour
bool setVehsPerHour (std::string vehsPerHour)
set flows per hour (string)
bool setPeriod (double period)
set period of flows
bool setPeriod (std::string period)
set period of flows (string)
bool setProbability (double probability)
set probability of flow
bool setProbability (std::string probability)
set probability of flow (string)
bool setNumber (int number)
set number of flows
bool setNumber (std::string number)
set number of flows (string)
bool setTypeOfFlow (TypeOfFlow type)
set type of flow
Private Attributes
std::string myArrivalLane
arrival lane
std::string myArrivalPos
arrival pos
std::string myArrivalPosLat
std::string myArrivalSpeed
arrival speed
GNECalibrator * myCalibratorParent
pointer to calibrator parent
std::string myColor
color of flow
int myContainerNumber
number of container
std::string myDepartLane
depart lane
std::string myDepartPos
depart position
std::string myDepartPosLat
departPosLat
std::string myDepartSpeed
depart speed
std::string myFlowID
ID of flow.
std::string myLine
line of bus/container stop
int myPersonNumber
number of person
bool myReroute
reroute
std::string myRoute
route in which this flow is used
TypeOfFlow myTypeOfFlow
type of flow
std::string myVehicleType
type of flow
specific of flows
time step begin
double myBegin
double myEnd
time step end
double myVehsPerHour
flows per hour
double myPeriod
period
double myProbability
probability
int myNumber
number of flow
Detailed Description
flow flow used by GNECalibrators
Definition at line 49 of file GNECalibratorFlow.h.
Member Enumeration Documentation
enum GNECalibratorFlow::TypeOfFlow
type of flow
Enumerator
GNE_CALIBRATORFLOW_INVALID
GNE_CALIBRATORFLOW_VEHSPERHOUR
GNE_CALIBRATORFLOW_PERIOD
GNE_CALIBRATORFLOW_PROBABILITY
Definition at line 53 of file GNECalibratorFlow.h.
Constructor & Destructor Documentation
GNECalibratorFlow::GNECalibratorFlow (GNECalibrator * calibratorParent)
constructor
Definition at line 61 of file GNECalibratorFlow.cpp.
References GNECalibrator::getCalibratorRoutes(), GNECalibrator::getCalibratorVehicleTypes(), myCalibratorParent, myRoute, and myVehicleType.
GNECalibratorFlow::GNECalibratorFlow (GNECalibrator * calibratorParent, std::string flowID, std::string vehicleType, std::string route, std::string color, std::string departLane, std::string departPos, std::string departSpeed, std::string arrivalLane, std::string arrivalPos, std::string arrivalSpeed, std::string line, int personNumber, int containerNumber, bool reroute, std::string departPosLat, std::string arrivalPosLat, double begin, double end, double vehsPerHour, double period, double probability, int number)
parameter constructor
Definition at line 75 of file GNECalibratorFlow.cpp.
References setArrivalLane(), setArrivalPos(), setArrivalPosLat(), setArrivalSpeed(), setBegin(), setColor(), setContainerNumber(), setDepartLane(), setDepartPos(), setDepartPosLat(), setDepartSpeed(), setEnd(), setFlowID(), setLine(), setNumber(), setPeriod(), setPersonNumber(), setProbability(), setReroute(), setRoute(), setVehicleType(), and setVehsPerHour().
GNECalibratorFlow::~GNECalibratorFlow ()
destructor
Definition at line 109 of file GNECalibratorFlow.cpp.
Member Function Documentation
const std::string & GNECalibratorFlow::getArrivalLane () const
get arrival lane
Definition at line 167 of file GNECalibratorFlow.cpp.
References myArrivalLane.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
const std::string & GNECalibratorFlow::getArrivalPos () const
get arrival position
Definition at line 173 of file GNECalibratorFlow.cpp.
References myArrivalPos.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
std::string GNECalibratorFlow::getArrivalPosLat () const
Definition at line 215 of file GNECalibratorFlow.cpp.
References myArrivalPosLat.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
const std::string & GNECalibratorFlow::getArrivalSpeed () const
get arrival speed
Definition at line 179 of file GNECalibratorFlow.cpp.
References myArrivalSpeed.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
double GNECalibratorFlow::getBegin () const
Definition at line 221 of file GNECalibratorFlow.cpp.
References myBegin.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
GNECalibrator * GNECalibratorFlow::getCalibratorParent () const
get pointer to calibrator parent
Definition at line 113 of file GNECalibratorFlow.cpp.
References myCalibratorParent.
Referenced by GNECalibratorFlowDialog::onCmdAccept().
const std::string & GNECalibratorFlow::getColor () const
get color of flow
Definition at line 143 of file GNECalibratorFlow.cpp.
References myColor.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
int GNECalibratorFlow::getContainerNumber () const
get number of containers
Definition at line 197 of file GNECalibratorFlow.cpp.
References myContainerNumber.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
const std::string & GNECalibratorFlow::getDepartLane () const
get depart lane
Definition at line 149 of file GNECalibratorFlow.cpp.
References myDepartLane.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
const std::string & GNECalibratorFlow::getDepartPos () const
get depart position
Definition at line 155 of file GNECalibratorFlow.cpp.
References myDepartPos.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
std::string GNECalibratorFlow::getDepartPosLat () const
get departPosLat
Definition at line 209 of file GNECalibratorFlow.cpp.
References myDepartPosLat.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
const std::string & GNECalibratorFlow::getDepartSpeed () const
get arrival speed
Definition at line 161 of file GNECalibratorFlow.cpp.
References myDepartSpeed.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
double GNECalibratorFlow::getEnd () const
get end time step
Definition at line 227 of file GNECalibratorFlow.cpp.
References myEnd.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
const std::string & GNECalibratorFlow::getFlowID () const
get ID of flow
Definition at line 125 of file GNECalibratorFlow.cpp.
References myFlowID.
Referenced by GNECalibratorFlowDialog::onCmdSetVariable(), operator==(), and GNECalibratorFlowDialog::updateCalibratorFlowValues().
GNECalibratorFlow::TypeOfFlow GNECalibratorFlow::getFlowType () const
get type of flow
Definition at line 257 of file GNECalibratorFlow.cpp.
References myTypeOfFlow.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
const std::string & GNECalibratorFlow::getLine () const
get line of busStop/containerStop
Definition at line 185 of file GNECalibratorFlow.cpp.
References myLine.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
int GNECalibratorFlow::getNumber () const
get number of flows
Definition at line 251 of file GNECalibratorFlow.cpp.
References myNumber.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
double GNECalibratorFlow::getPeriod () const
get period of flow
Definition at line 239 of file GNECalibratorFlow.cpp.
References myPeriod.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
int GNECalibratorFlow::getPersonNumber () const
get number of persons
Definition at line 191 of file GNECalibratorFlow.cpp.
References myPersonNumber.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
double GNECalibratorFlow::getProbability () const
get probability of flow
Definition at line 245 of file GNECalibratorFlow.cpp.
References myProbability.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
bool GNECalibratorFlow::getReroute () const
get reroute
Definition at line 203 of file GNECalibratorFlow.cpp.
References myReroute.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
const std::string & GNECalibratorFlow::getRoute () const
get route in which this flow is used
Definition at line 137 of file GNECalibratorFlow.cpp.
References myRoute.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
SumoXMLTag GNECalibratorFlow::getTag () const
get tag
Definition at line 119 of file GNECalibratorFlow.cpp.
References SUMO_TAG_FLOW.
Referenced by GNECalibratorFlowDialog::onCmdAccept().
const std::string & GNECalibratorFlow::getVehicleType () const
get vehicle type of flow
Definition at line 131 of file GNECalibratorFlow.cpp.
References myVehicleType.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
double GNECalibratorFlow::getVehsPerHour () const
get flows per hour
Definition at line 233 of file GNECalibratorFlow.cpp.
References myVehsPerHour.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
bool GNECalibratorFlow::operator== (const GNECalibratorFlow & calibratorFlow) const
overload operator ==
Definition at line 658 of file GNECalibratorFlow.cpp.
References getFlowID(), and myFlowID.
bool GNECalibratorFlow::setArrivalLane (std::string arrivalLane = "current")
set arrival lane
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 356 of file GNECalibratorFlow.cpp.
References myArrivalLane.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setArrivalPos (std::string arrivalPos = "max")
set arrival position
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 371 of file GNECalibratorFlow.cpp.
References myArrivalPos.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setArrivalPosLat (std::string arrivalPosLat = "")
set arrivalPosLat
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 499 of file GNECalibratorFlow.cpp.
References myArrivalPosLat.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setArrivalSpeed (std::string arrivalSpeed = "current")
set arrival speed
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 386 of file GNECalibratorFlow.cpp.
References myArrivalSpeed.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setBegin (double begin)
set begin step
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 514 of file GNECalibratorFlow.cpp.
References myBegin.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setBegin().
bool GNECalibratorFlow::setBegin (std::string begin)
set begin step (string)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 525 of file GNECalibratorFlow.cpp.
References setBegin().
bool GNECalibratorFlow::setColor (std::string color = "")
set color of flow
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 302 of file GNECalibratorFlow.cpp.
References myColor.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setContainerNumber (int containerNumber = 0)
set number of container
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 437 of file GNECalibratorFlow.cpp.
References myContainerNumber.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setContainerNumber().
bool GNECalibratorFlow::setContainerNumber (std::string containerNumber = "0")
set number of container (string)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 448 of file GNECalibratorFlow.cpp.
References setContainerNumber().
bool GNECalibratorFlow::setDepartLane (std::string departLane = "first")
set depart lane
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 309 of file GNECalibratorFlow.cpp.
References myDepartLane.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setDepartPos (std::string departPos = "base")
set depart position
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 325 of file GNECalibratorFlow.cpp.
References myDepartPos.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setDepartPosLat (std::string departPosLat = "center")
set departPosLat
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 483 of file GNECalibratorFlow.cpp.
References myDepartPosLat.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setDepartSpeed (std::string departSpeed = "0")
set depart speed
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 341 of file GNECalibratorFlow.cpp.
References myDepartSpeed.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setEnd (double end)
set end step
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 535 of file GNECalibratorFlow.cpp.
References myEnd.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setEnd().
bool GNECalibratorFlow::setEnd (std::string end)
set end step (string)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 546 of file GNECalibratorFlow.cpp.
References setEnd().
bool GNECalibratorFlow::setFlowID (std::string ID)
set ID of flow
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 263 of file GNECalibratorFlow.cpp.
References GNENet::flowExists(), GNEViewNet::getNet(), GNEAdditional::getViewNet(), myCalibratorParent, and myFlowID.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setLine (std::string line = "")
set line of busStop/containerStop
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 401 of file GNECalibratorFlow.cpp.
References myLine.
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setNumber (int number)
set number of flows
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 618 of file GNECalibratorFlow.cpp.
References myNumber.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setNumber().
bool GNECalibratorFlow::setNumber (std::string number)
set number of flows (string)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 629 of file GNECalibratorFlow.cpp.
References setNumber().
bool GNECalibratorFlow::setPeriod (double period)
set period of flows
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 577 of file GNECalibratorFlow.cpp.
References myPeriod.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setPeriod().
bool GNECalibratorFlow::setPeriod (std::string period)
set period of flows (string)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 588 of file GNECalibratorFlow.cpp.
References setPeriod().
bool GNECalibratorFlow::setPersonNumber (int personNumber = 0)
set number of persons
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 408 of file GNECalibratorFlow.cpp.
References myPersonNumber.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setPersonNumber().
bool GNECalibratorFlow::setPersonNumber (std::string personNumber = "0")
set number of persons (String)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 419 of file GNECalibratorFlow.cpp.
References setPersonNumber().
bool GNECalibratorFlow::setProbability (double probability)
set probability of flow
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 597 of file GNECalibratorFlow.cpp.
References myProbability.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setProbability().
bool GNECalibratorFlow::setProbability (std::string probability)
set probability of flow (string)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 608 of file GNECalibratorFlow.cpp.
References setProbability().
bool GNECalibratorFlow::setReroute (bool value)
set reroute
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 466 of file GNECalibratorFlow.cpp.
References myReroute.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setReroute().
bool GNECalibratorFlow::setReroute (std::string value)
set reroute (string)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 473 of file GNECalibratorFlow.cpp.
References setReroute().
bool GNECalibratorFlow::setRoute (std::string route)
set route in which this flow is used
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 289 of file GNECalibratorFlow.cpp.
References GNEViewNet::getNet(), GNEAdditional::getViewNet(), myCalibratorParent, myRoute, and GNENet::routeExists().
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setTypeOfFlow (TypeOfFlow type)
set type of flow
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 647 of file GNECalibratorFlow.cpp.
References GNE_CALIBRATORFLOW_PERIOD, GNE_CALIBRATORFLOW_PROBABILITY, GNE_CALIBRATORFLOW_VEHSPERHOUR, and myTypeOfFlow.
Referenced by GNECalibratorFlowDialog::onCmdSetTypeOfFlow().
bool GNECalibratorFlow::setVehicleType (std::string vehicleType)
set vehicleType of flow
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 276 of file GNECalibratorFlow.cpp.
References GNEViewNet::getNet(), GNEAdditional::getViewNet(), myCalibratorParent, myVehicleType, and GNENet::vehicleTypeExists().
Referenced by GNECalibratorFlow(), and GNECalibratorFlowDialog::onCmdSetVariable().
bool GNECalibratorFlow::setVehsPerHour (double vehsPerHour)
set flows per hour
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 556 of file GNECalibratorFlow.cpp.
References myVehsPerHour.
Referenced by GNECalibratorFlow(), GNECalibratorFlowDialog::onCmdSetVariable(), and setVehsPerHour().
bool GNECalibratorFlow::setVehsPerHour (std::string vehsPerHour)
set flows per hour (string)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 567 of file GNECalibratorFlow.cpp.
References setVehsPerHour().
Field Documentation
std::string GNECalibratorFlow::myArrivalLane private
arrival lane
Definition at line 342 of file GNECalibratorFlow.h.
Referenced by getArrivalLane(), and setArrivalLane().
std::string GNECalibratorFlow::myArrivalPos private
arrival pos
Definition at line 345 of file GNECalibratorFlow.h.
Referenced by getArrivalPos(), and setArrivalPos().
std::string GNECalibratorFlow::myArrivalPosLat private
Definition at line 366 of file GNECalibratorFlow.h.
Referenced by getArrivalPosLat(), and setArrivalPosLat().
std::string GNECalibratorFlow::myArrivalSpeed private
arrival speed
Definition at line 348 of file GNECalibratorFlow.h.
Referenced by getArrivalSpeed(), and setArrivalSpeed().
double GNECalibratorFlow::myBegin private
Definition at line 371 of file GNECalibratorFlow.h.
Referenced by getBegin(), and setBegin().
GNECalibrator* GNECalibratorFlow::myCalibratorParent private
pointer to calibrator parent
Definition at line 318 of file GNECalibratorFlow.h.
Referenced by getCalibratorParent(), GNECalibratorFlow(), setFlowID(), setRoute(), and setVehicleType().
std::string GNECalibratorFlow::myColor private
color of flow
Definition at line 330 of file GNECalibratorFlow.h.
Referenced by getColor(), and setColor().
int GNECalibratorFlow::myContainerNumber private
number of container
Definition at line 357 of file GNECalibratorFlow.h.
Referenced by getContainerNumber(), and setContainerNumber().
std::string GNECalibratorFlow::myDepartLane private
depart lane
Definition at line 333 of file GNECalibratorFlow.h.
Referenced by getDepartLane(), and setDepartLane().
std::string GNECalibratorFlow::myDepartPos private
depart position
Definition at line 336 of file GNECalibratorFlow.h.
Referenced by getDepartPos(), and setDepartPos().
std::string GNECalibratorFlow::myDepartPosLat private
departPosLat
Definition at line 363 of file GNECalibratorFlow.h.
Referenced by getDepartPosLat(), and setDepartPosLat().
std::string GNECalibratorFlow::myDepartSpeed private
depart speed
Definition at line 339 of file GNECalibratorFlow.h.
Referenced by getDepartSpeed(), and setDepartSpeed().
double GNECalibratorFlow::myEnd private
time step end
Definition at line 374 of file GNECalibratorFlow.h.
Referenced by getEnd(), and setEnd().
std::string GNECalibratorFlow::myFlowID private
ID of flow.
Definition at line 321 of file GNECalibratorFlow.h.
Referenced by getFlowID(), operator==(), and setFlowID().
std::string GNECalibratorFlow::myLine private
line of bus/container stop
Definition at line 351 of file GNECalibratorFlow.h.
Referenced by getLine(), and setLine().
int GNECalibratorFlow::myNumber private
number of flow
Definition at line 386 of file GNECalibratorFlow.h.
Referenced by getNumber(), and setNumber().
double GNECalibratorFlow::myPeriod private
period
Definition at line 380 of file GNECalibratorFlow.h.
Referenced by getPeriod(), and setPeriod().
int GNECalibratorFlow::myPersonNumber private
number of person
Definition at line 354 of file GNECalibratorFlow.h.
Referenced by getPersonNumber(), and setPersonNumber().
double GNECalibratorFlow::myProbability private
probability
Definition at line 383 of file GNECalibratorFlow.h.
Referenced by getProbability(), and setProbability().
bool GNECalibratorFlow::myReroute private
reroute
Definition at line 360 of file GNECalibratorFlow.h.
Referenced by getReroute(), and setReroute().
std::string GNECalibratorFlow::myRoute private
route in which this flow is used
Definition at line 327 of file GNECalibratorFlow.h.
Referenced by getRoute(), GNECalibratorFlow(), and setRoute().
TypeOfFlow GNECalibratorFlow::myTypeOfFlow private
type of flow
Definition at line 390 of file GNECalibratorFlow.h.
Referenced by getFlowType(), and setTypeOfFlow().
std::string GNECalibratorFlow::myVehicleType private
type of flow
Definition at line 324 of file GNECalibratorFlow.h.
Referenced by getVehicleType(), GNECalibratorFlow(), and setVehicleType().
double GNECalibratorFlow::myVehsPerHour private
flows per hour
Definition at line 377 of file GNECalibratorFlow.h.
Referenced by getVehsPerHour(), and setVehsPerHour().
The documentation for this class was generated from the following files:
GNECalibratorFlow.h
GNECalibratorFlow.cpp