SUMO - Simulation of Urban MObility: TraCI_POI Class Reference
TraCI_POI Class Reference
C++ TraCI client API implementation.
#include <TraCI_POI.h>
Static Public Member Functions
static bool add (const std::string &poiID, const TraCIPosition &pos, const TraCIColor &c, const std::string &type, int layer)
static void addParameter (const std::string &poiID, const std::string &param, const std::string &value)
static TraCIColor getColor (const std::string &poiID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static std::string getParameter (const std::string &poiID, const std::string &param)
static TraCIPosition getPosition (const std::string &poiID)
static std::string getType (const std::string &poiID)
static bool remove (const std::string &poiID, int layer=0)
static void setColor (const std::string &poiID, const TraCIColor &c)
static void setPosition (const std::string &poiID, const TraCIPosition &pos)
static void setType (const std::string &poiID, const std::string &setType)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
TraCI_POI & operator= (const TraCI_POI &src)
invalidated assignment operator
TraCI_POI ()
invalidated standard constructor
TraCI_POI (const TraCI_POI &src)
invalidated copy constructor
Static Private Member Functions
static PointOfInterest * getPoI (const std::string &id)
Detailed Description
C++ TraCI client API implementation.
Definition at line 53 of file TraCI_POI.h.
Constructor & Destructor Documentation
TraCI_POI::TraCI_POI () private
invalidated standard constructor
TraCI_POI::TraCI_POI (const TraCI_POI & src) private
invalidated copy constructor
Member Function Documentation
bool TraCI_POI::add (const std::string & poiID, const TraCIPosition & pos, const TraCIColor & c, const std::string & type, int layer) static
Definition at line 107 of file TraCI_POI.cpp.
References ShapeContainer::addPOI(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_IMG_HEIGHT, Shape::DEFAULT_IMG_WIDTH, MSNet::getInstance(), MSNet::getShapeContainer(), TraCI::makePosition(), and TraCI::makeRGBColor().
Referenced by TraCIServerAPI_POI::processSet().
void TraCI_POI::addParameter (const std::string & poiID, const std::string & param, const std::string & value) static
Definition at line 124 of file TraCI_POI.cpp.
References Parameterised::addParameter(), and getPoI().
Referenced by TraCIServerAPI_POI::processSet().
TraCIColor TraCI_POI::getColor (const std::string & poiID) static
Definition at line 66 of file TraCI_POI.cpp.
References Shape::getColor(), getPoI(), and TraCI::makeTraCIColor().
Referenced by TraCIServerAPI_POI::processGet().
int TraCI_POI::getIDCount () static
Definition at line 56 of file TraCI_POI.cpp.
References getIDList().
Referenced by TraCIServerAPI_POI::processGet().
std::vector< std::string > TraCI_POI::getIDList () static
Definition at line 48 of file TraCI_POI.cpp.
References MSNet::getInstance(), ShapeContainer::getPOIs(), MSNet::getShapeContainer(), and NamedObjectCont< T >::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_POI::processGet().
std::string TraCI_POI::getParameter (const std::string & poiID, const std::string & param) static
Definition at line 83 of file TraCI_POI.cpp.
References Parameterised::getParameter(), and getPoI().
Referenced by TraCIServerAPI_POI::processGet().
PointOfInterest * TraCI_POI::getPoI (const std::string & id) static private
Definition at line 131 of file TraCI_POI.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), ShapeContainer::getPOIs(), and MSNet::getShapeContainer().
Referenced by addParameter(), getColor(), getParameter(), getPosition(), getType(), setColor(), setPosition(), and setType().
TraCIPosition TraCI_POI::getPosition (const std::string & poiID) static
Definition at line 73 of file TraCI_POI.cpp.
References getPoI(), Position::x(), TraCIPosition::x, Position::y(), TraCIPosition::y, TraCIPosition::z, and Position::z().
Referenced by TraCIServerAPI_POI::processGet().
std::string TraCI_POI::getType (const std::string & poiID) static
Definition at line 61 of file TraCI_POI.cpp.
References getPoI(), and Shape::getType().
Referenced by TraCIServerAPI_POI::processGet().
TraCI_POI& TraCI_POI::operator= (const TraCI_POI & src) private
invalidated assignment operator
bool TraCI_POI::remove (const std::string & poiID, int layer = 0) static
Definition at line 118 of file TraCI_POI.cpp.
References MSNet::getInstance(), MSNet::getShapeContainer(), and ShapeContainer::removePOI().
Referenced by TraCIServerAPI_POI::processSet().
void TraCI_POI::setColor (const std::string & poiID, const TraCIColor & c) static
Definition at line 101 of file TraCI_POI.cpp.
References getPoI(), TraCI::makeRGBColor(), and Shape::setColor().
Referenced by TraCIServerAPI_POI::processSet().
void TraCI_POI::setPosition (const std::string & poiID, const TraCIPosition & pos) static
Definition at line 95 of file TraCI_POI.cpp.
References getPoI(), TraCI::makePosition(), and Position::set().
Referenced by TraCIServerAPI_POI::processSet().
void TraCI_POI::setType (const std::string & poiID, const std::string & setType) static
Definition at line 89 of file TraCI_POI.cpp.
References getPoI(), and Shape::setType().
Referenced by TraCIServerAPI_POI::processSet().
static void TraCI_POI::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
static void TraCI_POI::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
TraCI_POI.h
TraCI_POI.cpp