SUMO - Simulation of Urban MObility: MSDelayBasedTrafficLightLogic Class Reference
MSDelayBasedTrafficLightLogic Class Reference
An actuated traffic light logic based on time delay of approaching vehicles.
#include <MSDelayBasedTrafficLightLogic.h>
Public Types
typedef std::map< MSLane *, MSDetectorFileOutput * > LaneDetectorMap
Definition of a map from lanes to corresponding areal detectors.
Structure definitions
typedef std::vector< MSPhaseDefinition * > Phases
Definition of a list of phases, being the junction logic.
typedef std::vector< MSLink * > LinkVector
Definition of the list of links that are subjected to this tls.
typedef std::vector< LinkVector > LinkVectorVector
Definition of a list that holds lists of links that do have the same attribute.
typedef std::vector< MSLane * > LaneVector
Definition of the list of arrival lanes subjected to this tls.
typedef std::vector< LaneVector > LaneVectorVector
Definition of a list that holds lists of lanes that do have the same attribute.
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void clearParameter ()
Clears the parameter map.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::string & getID () const
Returns the id.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
void init (NLDetectorBuilder &nb)
Initializes the tls with information about incoming lanes.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSDelayBasedTrafficLightLogic (MSTLLogicControl &tlcontrol, const std::string &id, const std::string &programID, const MSSimpleTrafficLightLogic::Phases &phases, int step, SUMOTime delay, const std::map< std::string, std::string > &parameter, const std::string &basePath)
Constructor.
void setID (const std::string &newID)
resets the id
void writeParams (OutputDevice &out) const
~MSDelayBasedTrafficLightLogic ()
Destructor.
Switching and setting current rows
SUMOTime trySwitch ()
Switches to the next phase, if possible.
Static Information Retrieval
int getPhaseNumber () const
Returns the number of phases.
const Phases & getPhases () const
Returns the phases of this tls program.
Phases & getPhases ()
Returns the phases of this tls program.
const MSPhaseDefinition & getPhase (int givenstep) const
Returns the definition of the phase from the given position within the plan.
const std::string getLogicType () const
Returns the type of the logic as a string.
Dynamic Information Retrieval
int getCurrentPhaseIndex () const
Returns the current index within the program.
const MSPhaseDefinition & getCurrentPhaseDef () const
Returns the definition of the current phase.
Conversion between time and phase
SUMOTime getPhaseIndexAtTime (SUMOTime simStep) const
Returns the index of the logic at the given simulation step.
SUMOTime getOffsetFromIndex (int index) const
Returns the position (start of a phase during a cycle) from of a given step.
int getIndexFromOffset (SUMOTime offset) const
Returns the step (the phasenumber) of a given position of the cycle.
Changing phases and phase durations
void changeStepAndDuration (MSTLLogicControl &tlcontrol, SUMOTime simStep, int step, SUMOTime stepDuration)
Changes the current phase and her duration.
void setPhases (const Phases &phases, int index)
Replaces the phases and set the phase index.
Handling of controlled links
virtual void addLink (MSLink *link, MSLane *lane, int pos)
Adds a link on building.
virtual void adaptLinkInformationFrom (const MSTrafficLightLogic &logic)
Applies information about controlled links and lanes from the given logic.
std::map< MSLink *, LinkState > collectLinkStates () const
Returns the (uncontrolled) states of the controlled links.
void resetLinkStates (const std::map< MSLink *, LinkState > &vals) const
Resets the states of controlled links.
Switching and setting current rows
bool setTrafficLightSignals (SUMOTime t) const
Applies the current signal states to controlled links.
Static Information Retrieval
const std::string & getProgramID () const
Returns this tl-logic's id.
const LaneVectorVector & getLaneVectors () const
Returns the list of lists of all lanes controlled by this tls.
const LaneVector & getLanesAt (int i) const
Returns the list of lanes that are controlled by the signals at the given position.
const LinkVectorVector & getLinks () const
Returns the list of lists of all affected links.
const LinkVector & getLinksAt (int i) const
Returns the list of links that are controlled by the signals at the given position.
int getLinkIndex (const MSLink *const link) const
Returns the index of the given link.
Dynamic Information Retrieval
SUMOTime getDefaultCycleTime () const
Returns the cycle time (in ms)
SUMOTime getNextSwitchTime () const
Returns the assumed next switch time.
Changing phases and phase durations
void addOverridingDuration (SUMOTime duration)
Changes the duration of the next phase.
void setCurrentDurationIncrement (SUMOTime delay)
Delays current phase by the given delay.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Attributes
SUMOTime myCurrentDurationIncrement
A value for enlarge the current duration.
SUMOTime myDefaultCycleTime
The cycle time (without changes)
std::string myID
The name of the object.
LaneVectorVector myLanes
The list of LaneVectors; each vector contains the incoming lanes that belong to the same link index.
LinkVectorVector myLinks
The list of LinkVectors; each vector contains the links that belong to the same link index.
std::vector< SUMOTime > myOverridingTimes
A list of duration overrides.
Phases myPhases
The list of phases this logic uses.
std::string myProgramID
The id of the logic.
int myStep
The current step.
SwitchCommand * mySwitchCommand
The current switch command.
Static Protected Attributes
static const LaneVector myEmptyLaneVector
An empty lane vector.
"actuated" algorithm methods
LaneDetectorMap myLaneDetectors
A map from lanes to the corresponding lane detectors.
bool myShowDetectors
Whether the detectors shall be shown in the GUI.
double myDetectionRange
Range of the connected detector, which provides the information on approaching vehicles.
double myTimeLossThreshold
std::string myFile
The output file for generated detectors.
SUMOTime myFreq
The frequency for aggregating detector output.
std::string myVehicleTypes
Whether detector output separates by vType.
SUMOTime checkForWaitingTime ()
Checks for approaching vehicles on the lanes associated with green signals and returns the minimal time to keep the green phase going. This is zero if no vehicle on the lane has gathered any waiting time or if the green time is exhausted (maximal green time has passed since switch).
SUMOTime proposeProlongation (const SUMOTime actDuration, const SUMOTime maxDuration, bool &othersEmpty)
The returned, proposed prolongation for the green phase is oriented on the largest estimated passing time among the vehicles with waiting time.
Detailed Description
An actuated traffic light logic based on time delay of approaching vehicles.
Todo:
Validate against the original algorithm's details.
Note
The current phase is not prolonged if the passing time of the next approaching vehicle is larger than the remaining greentime (in contrast to the original algorithm)
The maximal green time can be exceeded if no vehicles are present on other approaches;
Definition at line 54 of file MSDelayBasedTrafficLightLogic.h.
Member Typedef Documentation
typedef std::map<MSLane*, MSDetectorFileOutput*> MSDelayBasedTrafficLightLogic::LaneDetectorMap
Definition of a map from lanes to corresponding areal detectors.
Definition at line 58 of file MSDelayBasedTrafficLightLogic.h.
typedef std::vector<MSLane*> MSTrafficLightLogic::LaneVector inherited
Definition of the list of arrival lanes subjected to this tls.
Definition at line 78 of file MSTrafficLightLogic.h.
typedef std::vector<LaneVector> MSTrafficLightLogic::LaneVectorVector inherited
Definition of a list that holds lists of lanes that do have the same attribute.
Definition at line 81 of file MSTrafficLightLogic.h.
typedef std::vector<MSLink*> MSTrafficLightLogic::LinkVector inherited
Definition of the list of links that are subjected to this tls.
Definition at line 72 of file MSTrafficLightLogic.h.
typedef std::vector<LinkVector> MSTrafficLightLogic::LinkVectorVector inherited
Definition of a list that holds lists of links that do have the same attribute.
Definition at line 75 of file MSTrafficLightLogic.h.
typedef std::vector<MSPhaseDefinition*> MSTrafficLightLogic::Phases inherited
Definition of a list of phases, being the junction logic.
Definition at line 69 of file MSTrafficLightLogic.h.
Constructor & Destructor Documentation
MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic (MSTLLogicControl & tlcontrol, const std::string & id, const std::string & programID, const MSSimpleTrafficLightLogic::Phases & phases, int step, SUMOTime delay, const std::map< std::string, std::string > & parameter, const std::string & basePath)
Constructor.
Parameters
[in] tlcontrol The tls control responsible for this tls
[in] id This tls' id
[in] programID This tls' sub-id (program id)
[in] phases Definitions of the phases
[in] step The initial phase index
[in] delay The time to wait before the first switch
[in] parameter The parameter to use for tls set-up
Definition at line 53 of file MSDelayBasedTrafficLightLogic.cpp.
References TplConvert::_2bool(), TplConvert::_2double(), FileHelpers::checkForRelativity(), Parameterised::getParameter(), myDetectionRange, myFile, myFreq, myShowDetectors, myTimeLossThreshold, myVehicleTypes, and TIME2STEPS.
MSDelayBasedTrafficLightLogic::~MSDelayBasedTrafficLightLogic ()
Destructor.
Definition at line 104 of file MSDelayBasedTrafficLightLogic.cpp.
Member Function Documentation
void MSTrafficLightLogic::adaptLinkInformationFrom (const MSTrafficLightLogic & logic) virtual inherited
Applies information about controlled links and lanes from the given logic.
If we load a logic after the network has been loaded, we do not get the information about controlled links afterwards. We have to copy them from a previously loaded logic.
Parameters
[in] logic The logic to use the information about controlled links/lanes from
Reimplemented in MSRailSignal, MSRailCrossing, and MSOffTrafficLightLogic.
Definition at line 200 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLanes, and MSTrafficLightLogic::myLinks.
Referenced by MSOffTrafficLightLogic::adaptLinkInformationFrom(), MSRailCrossing::adaptLinkInformationFrom(), MSRailSignal::adaptLinkInformationFrom(), and MSTLLogicControl::TLSLogicVariants::addLogic().
void MSTrafficLightLogic::addLink (MSLink * link, MSLane * lane, int pos) virtual inherited
Adds a link on building.
Parameters
[in] link The controlled link
[in] lane The lane this link starts at
[in] pos The link's index (signal group) within this program
Reimplemented in MSRailCrossing.
Definition at line 182 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSNet::getInstance(), MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myLinks, and MSLink::setTLState().
Referenced by MSRailCrossing::addLink().
void MSTrafficLightLogic::addOverridingDuration (SUMOTime duration) inherited
Changes the duration of the next phase.
Parameters
[in] duration The new duration
Definition at line 273 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myOverridingTimes.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTrafficLightLogic::getDefaultCycleTime(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic().
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), TraCI_POI::addParameter(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenDrive::loadNetwork(), MSStateHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCI_Polygon::setParameter(), TraCI_Route::setParameter(), and TraCI_Lane::setParameter().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 65 of file Parameterised.cpp.
References Parameterised::myMap.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
void MSSimpleTrafficLightLogic::changeStepAndDuration (MSTLLogicControl & tlcontrol, SUMOTime simStep, int step, SUMOTime stepDuration) virtual inherited
Changes the current phase and her duration.
Parameters
[in] tlcontrol The responsible traffic lights control
[in] simStep The current simulation step
[in] step Index of the phase to use
[in] stepDuration The left duration of the phase
See also
MSTrafficLightLogic::changeStepAndDuration
Implements MSTrafficLightLogic.
Definition at line 191 of file MSSimpleTrafficLightLogic.cpp.
References MSEventControl::addEvent(), MSTrafficLightLogic::SwitchCommand::deschedule(), MSTLLogicControl::TLSLogicVariants::executeOnSwitchActions(), MSTLLogicControl::get(), MSNet::getBeginOfTimestepEvents(), Named::getID(), MSNet::getInstance(), MSSimpleTrafficLightLogic::myStep, MSTrafficLightLogic::mySwitchCommand, and MSTrafficLightLogic::setTrafficLightSignals().
Referenced by MSSimpleTrafficLightLogic::getLogicType(), and GUIViewTraffic::onGamingClick().
SUMOTime MSDelayBasedTrafficLightLogic::checkForWaitingTime () protected
Checks for approaching vehicles on the lanes associated with green signals and returns the minimal time to keep the green phase going. This is zero if no vehicle on the lane has gathered any waiting time or if the green time is exhausted (maximal green time has passed since switch).
Returns
Minimal remaining green time.
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 99 of file Parameterised.cpp.
References Parameterised::myMap.
std::map< MSLink *, LinkState > MSTrafficLightLogic::collectLinkStates () const inherited
Returns the (uncontrolled) states of the controlled links.
Returns
The controlled link's states
Definition at line 207 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::saveInitialStates().
const MSPhaseDefinition & MSSimpleTrafficLightLogic::getCurrentPhaseDef () const virtual inherited
Returns the definition of the current phase.
Returns
The current phase
See also
MSTrafficLightLogic::getCurrentPhaseDef
Implements MSTrafficLightLogic.
Definition at line 133 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases, and MSSimpleTrafficLightLogic::myStep.
Referenced by MSActuatedTrafficLightLogic::duration(), MSActuatedTrafficLightLogic::gapControl(), MSSimpleTrafficLightLogic::getLogicType(), proposeProlongation(), trySwitch(), and MSActuatedTrafficLightLogic::trySwitch().
int MSSimpleTrafficLightLogic::getCurrentPhaseIndex () const virtual inherited
Returns the current index within the program.
Returns
The index of the current phase within the tls
See also
MSTrafficLightLogic::getCurrentPhaseIndex
Implements MSTrafficLightLogic.
Definition at line 127 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myStep.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
SUMOTime MSTrafficLightLogic::getDefaultCycleTime () const inline inherited
Returns the cycle time (in ms)
Returns
The (maybe changing) cycle time of this tls
Definition at line 267 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::addOverridingDuration(), MSTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::getIndexFromOffset(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::getOffsetFromIndex(), MSTrafficLightLogic::getPhaseIndexAtTime(), MSTrafficLightLogic::myDefaultCycleTime, and MSTrafficLightLogic::setCurrentDurationIncrement().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NLJunctionControlBuilder::closeTrafficLightLogic(), and MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP().
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 89 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), MSNet::addParkingArea(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), TraCI_Vehicle::getBestLanes(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), TraCI_Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), TraCI_Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), TraCI_Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSNet::getParkingAreaID(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), TraCI_Vehicle::getRoadID(), TraCI_Vehicle::getRouteID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_SSM::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSDevice_SSM::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_SSM::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingZone(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), toString(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSDevice_SSM::updateEncounter(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSPModel_Striping::PState::moveToNextLane(), operator<<(), TraCIServerAPI_Vehicle::processSet(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), MSAbstractLaneChangeModel::updateShadowLane(), and TraCIServerAPI_Vehicle::vtdMap().
int MSSimpleTrafficLightLogic::getIndexFromOffset (SUMOTime offset) const virtual inherited
Returns the step (the phasenumber) of a given position of the cycle.
Parameters
[in] offset The offset (time) for which the according phase shall be returned
Returns
The according phase
See also
MSTrafficLightLogic::getIndexFromOffset
Implements MSTrafficLightLogic.
Definition at line 169 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), MSTrafficLightLogic::myDefaultCycleTime, and MSSimpleTrafficLightLogic::myPhases.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
const LaneVector& MSTrafficLightLogic::getLanesAt (int i) const inline inherited
Returns the list of lanes that are controlled by the signals at the given position.
Parameters
[in] i The index of the signal
Returns
The lanes controlled by the signal at the given index
Definition at line 190 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myEmptyLaneVector, and MSTrafficLightLogic::myLanes.
Referenced by GUITrafficLightLogicWrapper::drawGL(), Command_SaveTLSSwitches::execute(), MSActuatedTrafficLightLogic::gapControl(), GUIViewTraffic::onGamingClick(), and proposeProlongation().
const LaneVectorVector& MSTrafficLightLogic::getLaneVectors () const inline inherited
Returns the list of lists of all lanes controlled by this tls.
Returns
All lanes controlled by this tls, sorted by the signal index
Definition at line 181 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLanes.
Referenced by MSSOTLWaveTrafficLightLogic::countVehicles(), GUITrafficLightLogicWrapper::getCenteringBoundary(), MSSOTLTrafficLightLogic::init(), TraCIServerAPI_TLS::processGet(), and MSFullExport::writeTLS().
int MSTrafficLightLogic::getLinkIndex (const MSLink *const link) const inherited
Returns the index of the given link.
Parameters
[in] link The link to retrieve the index for
Returns
The index of the given link (-1 if it is not controlled by this tls)
Definition at line 249 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by GUITrafficLightLogicWrapper::getLinkIndex(), and MSTrafficLightLogic::getLinksAt().
const LinkVectorVector& MSTrafficLightLogic::getLinks () const inline inherited
Returns the list of lists of all affected links.
Returns
All links controlled by this tls, sorted by the signal index
Definition at line 202 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), GUINet::createTLWrapper(), GUITLLogicPhasesTrackerWindow::drawValues(), Command_SaveTLSSwitches::execute(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSDeterministicHiLevelTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), TraCIServerAPI_TLS::processGet(), and MSOffTrafficLightLogic::rebuildPhase().
const LinkVector& MSTrafficLightLogic::getLinksAt (int i) const inline inherited
Returns the list of links that are controlled by the signals at the given position.
Parameters
[in] i The index of the signal
Returns
The links controlled by the signal at the given index
Definition at line 211 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSTrafficLightLogic::getLinkIndex(), MSTrafficLightLogic::getLogicType(), MSTrafficLightLogic::getPhase(), MSTrafficLightLogic::getPhaseNumber(), MSTrafficLightLogic::getPhases(), and MSTrafficLightLogic::myLinks.
Referenced by MSDeterministicHiLevelTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), and MSSwarmTrafficLightLogic::init().
const std::string MSSimpleTrafficLightLogic::getLogicType () const inline virtual inherited
Returns the type of the logic as a string.
Returns
The type of the logic
Implements MSTrafficLightLogic.
Definition at line 127 of file MSSimpleTrafficLightLogic.h.
References MSSimpleTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSSimpleTrafficLightLogic::getCurrentPhaseIndex(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), and MSSimpleTrafficLightLogic::setPhases().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 119 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NBTrafficLightDefinition::compute(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROPerson::saveAsXML(), and PointOfInterest::writeXML().
SUMOTime MSTrafficLightLogic::getNextSwitchTime () const inherited
Returns the assumed next switch time.
The time may change in case of adaptive/actuated traffic lights.
Returns
The assumed next switch time (simulation time)
Definition at line 266 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::SwitchCommand::getNextSwitchTime(), and MSTrafficLightLogic::mySwitchCommand.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTrafficLightLogic::getDefaultCycleTime(), MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP(), and TraCIServerAPI_TLS::processGet().
SUMOTime MSSimpleTrafficLightLogic::getOffsetFromIndex (int index) const virtual inherited
Returns the position (start of a phase during a cycle) from of a given step.
Parameters
[in] index The index of the phase to return the begin of
Returns
The begin time of the phase
See also
MSTrafficLightLogic::getOffsetFromIndex
Implements MSTrafficLightLogic.
Definition at line 155 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), and MSSimpleTrafficLightLogic::myPhases.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 79 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getLoggingFrequency(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), TraCI_Polygon::getParameter(), TraCI_VehicleType::getParameter(), TraCI_Route::getParameter(), TraCI_POI::getParameter(), TraCI_Lane::getParameter(), TraCI_Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), TraCIServerAPI_Vehicle::vtdMap(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
const MSPhaseDefinition & MSSimpleTrafficLightLogic::getPhase (int givenstep) const virtual inherited
Returns the definition of the phase from the given position within the plan.
Parameters
[in] givenstep The index of the phase within the plan
Returns
The definition of the phase at the given position
See also
MSTrafficLightLogic::getPhase
Implements MSTrafficLightLogic.
Definition at line 119 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
Referenced by MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), and GUIViewTraffic::onGamingClick().
SUMOTime MSSimpleTrafficLightLogic::getPhaseIndexAtTime (SUMOTime simStep) const virtual inherited
Returns the index of the logic at the given simulation step.
Returns
The (estimated) index of the tls at the given simulation time step
See also
MSTrafficLightLogic::getPhaseIndexAtTime
Implements MSTrafficLightLogic.
Definition at line 140 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), MSTrafficLightLogic::myDefaultCycleTime, MSPhaseDefinition::myLastSwitch, and MSSimpleTrafficLightLogic::myStep.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
int MSSimpleTrafficLightLogic::getPhaseNumber () const virtual inherited
Returns the number of phases.
Returns
The number of this tls program's phases
See also
MSTrafficLightLogic::getPhaseNumber
Implements MSTrafficLightLogic.
Definition at line 101 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
const MSSimpleTrafficLightLogic::Phases & MSSimpleTrafficLightLogic::getPhases () const virtual inherited
Returns the phases of this tls program.
Returns
The phases of this tls program
See also
MSTrafficLightLogic::getPhases
Implements MSTrafficLightLogic.
Definition at line 107 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
MSSimpleTrafficLightLogic::Phases & MSSimpleTrafficLightLogic::getPhases () inherited
Returns the phases of this tls program.
Returns
The phases of this tls program
Todo:
Recheck!
Definition at line 113 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
const std::string& MSTrafficLightLogic::getProgramID () const inline inherited
Returns this tl-logic's id.
Returns
This program's id
Definition at line 173 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myProgramID.
Referenced by Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSTrafficLightLogic::init(), GUIViewTraffic::onGamingClick(), and TraCIServerAPI_TLS::processGet().
void MSDelayBasedTrafficLightLogic::init (NLDetectorBuilder & nb) virtual
Initializes the tls with information about incoming lanes.
Parameters
[in] nb The detector builder
Exceptions
ProcessError If something fails on initialization
Reimplemented from MSTrafficLightLogic.
Definition at line 82 of file MSDelayBasedTrafficLightLogic.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::createE2Detector(), DU_TL_CONTROL, MSNet::getDetectorControl(), Named::getID(), MSNet::getInstance(), MSLane::getLength(), MSTrafficLightLogic::init(), INVALID_POSITION, myDetectionRange, myFile, myFreq, Named::myID, myLaneDetectors, MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myProgramID, myShowDetectors, myVehicleTypes, and SUMO_TAG_E2DETECTOR.
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 73 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getLoggingFrequency(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), and MSDevice_SSM::requestsTrajectories().
SUMOTime MSDelayBasedTrafficLightLogic::proposeProlongation (const SUMOTime actDuration, const SUMOTime maxDuration, bool & othersEmpty) protected
The returned, proposed prolongation for the green phase is oriented on the largest estimated passing time among the vehicles with waiting time.
Parameters
actDuration Duration of the current phase
maxDuration Maximal duration of the current phase
Definition at line 110 of file MSDelayBasedTrafficLightLogic.cpp.
References MSE2Collector::VehicleInfo::accumulatedTimeLoss, MSE2Collector::VehicleInfo::distToDetectorEnd, MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSE2Collector::getCurrentVehicles(), Named::getID(), MSTrafficLightLogic::getLanesAt(), MSPhaseDefinition::getState(), MSE2Collector::VehicleInfo::id, LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, MAX2(), MSPhaseDefinition::maxDuration, myLaneDetectors, MSSimpleTrafficLightLogic::myStep, myTimeLossThreshold, SIMTIME, and TIME2STEPS.
Referenced by trySwitch().
void MSTrafficLightLogic::resetLinkStates (const std::map< MSLink *, LinkState > & vals) const inherited
Resets the states of controlled links.
Parameters
[in] vals The state of controlled links to use
Definition at line 236 of file MSTrafficLightLogic.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and MSTrafficLightLogic::myLinks.
void MSTrafficLightLogic::setCurrentDurationIncrement (SUMOTime delay) inherited
Delays current phase by the given delay.
Parameters
[in] delay The time by which the current phase shall be delayed
Definition at line 279 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myCurrentDurationIncrement.
Referenced by MSTrafficLightLogic::getDefaultCycleTime().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::Distribution_Parameterized(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MSSimpleTrafficLightLogic::setPhases (const Phases & phases, int index) inherited
Replaces the phases and set the phase index.
Definition at line 206 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::deletePhases(), MSSimpleTrafficLightLogic::myPhases, and MSSimpleTrafficLightLogic::myStep.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
bool MSTrafficLightLogic::setTrafficLightSignals (SUMOTime t) const inherited
Applies the current signal states to controlled links.
Parameters
[in] t The current time
Returns
Always true
See also
LinkState
MSLink::setTLState
Definition at line 220 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSPhaseDefinition::getState(), and MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::SwitchCommand::execute(), MSRailCrossing::init(), MSRailSignal::init(), MSTLLogicControl::TLSLogicVariants::switchTo(), MSRailCrossing::trySwitch(), and MSRailSignal::trySwitch().
SUMOTime MSDelayBasedTrafficLightLogic::trySwitch () virtual
Switches to the next phase, if possible.
Returns
The time of the next switch
See also
MSTrafficLightLogic::trySwitch
Reimplemented from MSSimpleTrafficLightLogic.
Definition at line 186 of file MSDelayBasedTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSGlobals::gUseMesoSim, MSPhaseDefinition::isGreenPhase(), MAX2(), MAX3(), MSPhaseDefinition::maxDuration, MIN2(), MSPhaseDefinition::minDuration, MSPhaseDefinition::myLastSwitch, MSSimpleTrafficLightLogic::myPhases, MSSimpleTrafficLightLogic::myStep, proposeProlongation(), and TIME2STEPS.
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 104 of file Parameterised.cpp.
References OutputDevice::closeTag(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MSVehicle::saveState(), SUMOVTypeParameter::write(), MSDevice_Vehroutes::writeOutput(), and SUMO::Polygon::writeXML().
Field Documentation
SUMOTime MSTrafficLightLogic::myCurrentDurationIncrement protected inherited
A value for enlarge the current duration.
Definition at line 411 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::setCurrentDurationIncrement(), and MSSimpleTrafficLightLogic::trySwitch().
SUMOTime MSTrafficLightLogic::myDefaultCycleTime protected inherited
The cycle time (without changes)
Definition at line 417 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getDefaultCycleTime(), MSPhasedTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSPhasedTrafficLightLogic::getPhaseIndexAtTime(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSOffTrafficLightLogic::MSOffTrafficLightLogic(), MSPhasedTrafficLightLogic::MSPhasedTrafficLightLogic(), MSRailSignal::MSRailSignal(), and MSSimpleTrafficLightLogic::MSSimpleTrafficLightLogic().
double MSDelayBasedTrafficLightLogic::myDetectionRange protected
Range of the connected detector, which provides the information on approaching vehicles.
Definition at line 132 of file MSDelayBasedTrafficLightLogic.h.
Referenced by init(), and MSDelayBasedTrafficLightLogic().
const MSTrafficLightLogic::LaneVector MSTrafficLightLogic::myEmptyLaneVector static protected inherited
An empty lane vector.
Definition at line 420 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getLanesAt().
std::string MSDelayBasedTrafficLightLogic::myFile protected
The output file for generated detectors.
Definition at line 140 of file MSDelayBasedTrafficLightLogic.h.
Referenced by init(), and MSDelayBasedTrafficLightLogic().
SUMOTime MSDelayBasedTrafficLightLogic::myFreq protected
The frequency for aggregating detector output.
Definition at line 143 of file MSDelayBasedTrafficLightLogic.h.
Referenced by init(), and MSDelayBasedTrafficLightLogic().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
LaneDetectorMap MSDelayBasedTrafficLightLogic::myLaneDetectors protected
A map from lanes to the corresponding lane detectors.
Definition at line 126 of file MSDelayBasedTrafficLightLogic.h.
Referenced by init(), and proposeProlongation().
LaneVectorVector MSTrafficLightLogic::myLanes protected inherited
The list of LaneVectors; each vector contains the incoming lanes that belong to the same link index.
Definition at line 405 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSTrafficLightLogic::getLanesAt(), MSTrafficLightLogic::getLaneVectors(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), and MSSwarmTrafficLightLogic::resetLaneCheck().
LinkVectorVector MSTrafficLightLogic::myLinks protected inherited
The list of LinkVectors; each vector contains the links that belong to the same link index.
Definition at line 402 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSTrafficLightLogic::collectLinkStates(), MSRailSignal::getAppropriateState(), MSTrafficLightLogic::getLinkIndex(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getLinksAt(), MSRailCrossing::init(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSTrafficLightLogic::initMesoTLSPenalties(), MSSwarmTrafficLightLogic::resetLaneCheck(), MSTrafficLightLogic::resetLinkStates(), and MSTrafficLightLogic::setTrafficLightSignals().
std::vector<SUMOTime> MSTrafficLightLogic::myOverridingTimes protected inherited
A list of duration overrides.
Definition at line 408 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::addOverridingDuration(), and MSSimpleTrafficLightLogic::trySwitch().
Phases MSSimpleTrafficLightLogic::myPhases protected inherited
The list of phases this logic uses.
Definition at line 202 of file MSSimpleTrafficLightLogic.h.
Referenced by MSSimpleTrafficLightLogic::deletePhases(), MSActuatedTrafficLightLogic::duration(), MSActuatedTrafficLightLogic::gapControl(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getPhase(), MSSimpleTrafficLightLogic::getPhaseNumber(), MSSimpleTrafficLightLogic::getPhases(), MSRailCrossing::init(), MSRailCrossing::MSRailCrossing(), MSSimpleTrafficLightLogic::MSSimpleTrafficLightLogic(), MSSimpleTrafficLightLogic::setPhases(), MSSimpleTrafficLightLogic::trySwitch(), trySwitch(), and MSActuatedTrafficLightLogic::trySwitch().
std::string MSTrafficLightLogic::myProgramID protected inherited
The id of the logic.
Definition at line 399 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getProgramID(), init(), and MSActuatedTrafficLightLogic::init().
bool MSDelayBasedTrafficLightLogic::myShowDetectors protected
Whether the detectors shall be shown in the GUI.
Definition at line 129 of file MSDelayBasedTrafficLightLogic.h.
Referenced by init(), and MSDelayBasedTrafficLightLogic().
int MSSimpleTrafficLightLogic::myStep protected inherited
The current step.
Definition at line 205 of file MSSimpleTrafficLightLogic.h.
Referenced by MSSimpleTrafficLightLogic::changeStepAndDuration(), MSActuatedTrafficLightLogic::duration(), MSActuatedTrafficLightLogic::gapControl(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSSimpleTrafficLightLogic::getCurrentPhaseIndex(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), proposeProlongation(), MSSimpleTrafficLightLogic::setPhases(), MSSimpleTrafficLightLogic::trySwitch(), trySwitch(), MSActuatedTrafficLightLogic::trySwitch(), and MSRailCrossing::updateCurrentPhase().
SwitchCommand* MSTrafficLightLogic::mySwitchCommand protected inherited
The current switch command.
Definition at line 414 of file MSTrafficLightLogic.h.
Referenced by MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::getNextSwitchTime(), and MSTrafficLightLogic::MSTrafficLightLogic().
double MSDelayBasedTrafficLightLogic::myTimeLossThreshold protected
If a vehicle's timeloss is below myTimeLossThreshold, this is counted as insignificant, since this may stem from dawdling, or driving only slightly slower than the maximal velocity on the lane.
Definition at line 137 of file MSDelayBasedTrafficLightLogic.h.
Referenced by MSDelayBasedTrafficLightLogic(), and proposeProlongation().
std::string MSDelayBasedTrafficLightLogic::myVehicleTypes protected
Whether detector output separates by vType.
Definition at line 146 of file MSDelayBasedTrafficLightLogic.h.
Referenced by init(), and MSDelayBasedTrafficLightLogic().
The documentation for this class was generated from the following files:
MSDelayBasedTrafficLightLogic.h
MSDelayBasedTrafficLightLogic.cpp