SUMO - Simulation of Urban MObility: GNECalibratorRoute Class Reference
GNECalibratorRoute Class Reference
#include <GNECalibratorRoute.h>
Public Member Functions
std::string checkEdgeRoute (const std::vector< std::string > &edge) const
check if a list of edges is valid to set a route
GNECalibrator * getCalibratorParent () const
get pointer to calibrator parent
const std::string & getColor () const
get color of route
const std::vector< GNEEdge * > & getEdges () const
get edges
std::vector< std::string > getEdgesIDs () const
get IDs of Edges
const std::string & getRouteID () const
get route ID
SumoXMLTag getTag () const
get tag
GNECalibratorRoute (GNECalibrator *calibratorParent)
default constructor
GNECalibratorRoute (GNECalibrator *calibratorParent, std::string routeID, std::vector< std::string > edges, std::string color)
parameter constructor 1 (Using edges IDs)
GNECalibratorRoute (GNECalibrator *calibratorParent, std::string routeID, std::vector< GNEEdge * > edges, std::string color)
parameter constructor 2 (Using GNEEdges)
bool operator== (const GNECalibratorRoute &calibratorRoute) const
overload operator ==
bool setColor (std::string color="")
set color of route
bool setEdges (const std::vector< std::string > &edgeIDs)
set edges of route using IDs
bool setEdges (const std::vector< GNEEdge * > &edges)
set edges of route using pointers
bool setEdges (const std::string &edgeIDs)
set edges of route using a single string
bool setRouteID (std::string routeID)
set route ID
~GNECalibratorRoute ()
destructor
Private Attributes
GNECalibrator * myCalibratorParent
pointer to calibrator parent
std::string myColor
color of flow
std::vector< GNEEdge * > myEdges
edges of route
std::string myRouteID
route in which this flow is used
Detailed Description
vehicle route used by GNECalibrators
Definition at line 50 of file GNECalibratorRoute.h.
Constructor & Destructor Documentation
GNECalibratorRoute::GNECalibratorRoute (GNECalibrator * calibratorParent)
default constructor
Definition at line 62 of file GNECalibratorRoute.cpp.
GNECalibratorRoute::GNECalibratorRoute (GNECalibrator * calibratorParent, std::string routeID, std::vector< std::string > edges, std::string color)
parameter constructor 1 (Using edges IDs)
Definition at line 67 of file GNECalibratorRoute.cpp.
References setColor(), setEdges(), and setRouteID().
GNECalibratorRoute::GNECalibratorRoute (GNECalibrator * calibratorParent, std::string routeID, std::vector< GNEEdge * > edges, std::string color)
parameter constructor 2 (Using GNEEdges)
Definition at line 76 of file GNECalibratorRoute.cpp.
References setColor(), setEdges(), and setRouteID().
GNECalibratorRoute::~GNECalibratorRoute ()
destructor
Definition at line 84 of file GNECalibratorRoute.cpp.
Member Function Documentation
std::string GNECalibratorRoute::checkEdgeRoute (const std::vector< std::string > & edge) const
check if a list of edges is valid to set a route
Returns
"" if is correct, a error string in other case
Definition at line 182 of file GNECalibratorRoute.cpp.
References GNEEdge::getGNEJunctionDestiny(), GNEJunction::getGNEOutgoingEdges(), GNEViewNet::getNet(), GNEAdditional::getViewNet(), myCalibratorParent, GNENet::retrieveEdge(), SUMO_TAG_EDGE, and toString().
GNECalibrator * GNECalibratorRoute::getCalibratorParent () const
get pointer to calibrator parent
Definition at line 88 of file GNECalibratorRoute.cpp.
References myCalibratorParent.
Referenced by GNECalibratorRouteDialog::onCmdAccept().
const std::string & GNECalibratorRoute::getColor () const
get color of route
Definition at line 122 of file GNECalibratorRoute.cpp.
References myColor.
Referenced by GNECalibratorRouteDialog::onCmdSetVariable(), and GNECalibratorRouteDialog::updateCalibratorRouteValues().
const std::vector< GNEEdge * > & GNECalibratorRoute::getEdges () const
get edges
Definition at line 116 of file GNECalibratorRoute.cpp.
References myEdges.
Referenced by GNECalibratorRouteDialog::onCmdSetVariable(), and GNECalibratorRouteDialog::updateCalibratorRouteValues().
std::vector< std::string > GNECalibratorRoute::getEdgesIDs () const
get IDs of Edges
Definition at line 106 of file GNECalibratorRoute.cpp.
References myEdges.
Referenced by GNECalibratorRouteDialog::updateCalibratorRouteValues().
const std::string & GNECalibratorRoute::getRouteID () const
get route ID
Definition at line 100 of file GNECalibratorRoute.cpp.
References myRouteID.
Referenced by GNECalibratorRouteDialog::onCmdSetVariable(), operator==(), and GNECalibratorRouteDialog::updateCalibratorRouteValues().
SumoXMLTag GNECalibratorRoute::getTag () const
get tag
Definition at line 94 of file GNECalibratorRoute.cpp.
References SUMO_TAG_ROUTE.
Referenced by GNECalibratorRouteDialog::onCmdAccept().
bool GNECalibratorRoute::operator== (const GNECalibratorRoute & calibratorRoute) const
overload operator ==
Definition at line 212 of file GNECalibratorRoute.cpp.
References getRouteID(), and myRouteID.
bool GNECalibratorRoute::setColor (std::string color = "")
set color of route
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 175 of file GNECalibratorRoute.cpp.
References myColor.
Referenced by GNECalibratorRoute(), and GNECalibratorRouteDialog::onCmdSetVariable().
bool GNECalibratorRoute::setEdges (const std::vector< std::string > & edgeIDs)
set edges of route using IDs
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 141 of file GNECalibratorRoute.cpp.
References GNEViewNet::getNet(), GNEAdditional::getViewNet(), myCalibratorParent, and GNENet::retrieveEdge().
Referenced by GNECalibratorRoute(), GNECalibratorRouteDialog::onCmdSetVariable(), and setEdges().
bool GNECalibratorRoute::setEdges (const std::vector< GNEEdge * > & edges)
set edges of route using pointers
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 158 of file GNECalibratorRoute.cpp.
References myEdges.
bool GNECalibratorRoute::setEdges (const std::string & edgeIDs)
set edges of route using a single string
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 165 of file GNECalibratorRoute.cpp.
References GNEAttributeCarrier::canParse(), GNEAttributeCarrier::parse(), and setEdges().
bool GNECalibratorRoute::setRouteID (std::string routeID)
set route ID
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 128 of file GNECalibratorRoute.cpp.
References GNEViewNet::getNet(), GNEAdditional::getViewNet(), myCalibratorParent, myRouteID, and GNENet::routeExists().
Referenced by GNECalibratorRoute(), and GNECalibratorRouteDialog::onCmdSetVariable().
Field Documentation
GNECalibrator* GNECalibratorRoute::myCalibratorParent private
pointer to calibrator parent
Definition at line 118 of file GNECalibratorRoute.h.
Referenced by checkEdgeRoute(), getCalibratorParent(), setEdges(), and setRouteID().
std::string GNECalibratorRoute::myColor private
color of flow
Definition at line 127 of file GNECalibratorRoute.h.
Referenced by getColor(), and setColor().
std::vector<GNEEdge*> GNECalibratorRoute::myEdges private
edges of route
Definition at line 124 of file GNECalibratorRoute.h.
Referenced by getEdges(), getEdgesIDs(), and setEdges().
std::string GNECalibratorRoute::myRouteID private
route in which this flow is used
Definition at line 121 of file GNECalibratorRoute.h.
Referenced by getRouteID(), operator==(), and setRouteID().
The documentation for this class was generated from the following files:
GNECalibratorRoute.h
GNECalibratorRoute.cpp