SUMO - Simulation of Urban MObility: TraCI_Lane Class Reference
TraCI_Lane Class Reference
C++ TraCI client API implementation.
#include <TraCI_Lane.h>
Static Public Member Functions
static std::vector< std::string > getAllowed (std::string laneID)
static double getCO2Emission (std::string laneID)
static double getCOEmission (std::string laneID)
static std::vector< std::string > getDisallowed (std::string laneID)
static std::string getEdgeID (std::string laneID)
static double getElectricityConsumption (std::string laneID)
static double getFuelConsumption (std::string laneID)
static double getHCEmission (std::string laneID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static const MSLane * getLane (const std::string &id)
static int getLastStepHaltingNumber (std::string laneID)
static double getLastStepLength (std::string laneID)
static double getLastStepMeanSpeed (std::string laneID)
static double getLastStepOccupancy (std::string laneID)
static std::vector< std::string > getLastStepVehicleIDs (std::string laneID)
static int getLastStepVehicleNumber (std::string laneID)
static double getLength (std::string laneID)
static int getLinkNumber (std::string laneID)
static std::vector< TraCIConnection > getLinks (std::string laneID)
static double getMaxSpeed (std::string laneID)
static double getNoiseEmission (std::string laneID)
static double getNOxEmission (std::string laneID)
static std::string getParameter (const std::string &laneID, const std::string &param)
static double getPMxEmission (std::string laneID)
static TraCIPositionVector getShape (std::string laneID)
static double getTraveltime (std::string laneID)
static double getWaitingTime (std::string laneID)
static double getWidth (std::string laneID)
static void setAllowed (std::string laneID, std::vector< std::string > allowedClasses)
static void setDisallowed (std::string laneID, std::vector< std::string > disallowedClasses)
static void setLength (std::string laneID, double length)
static void setMaxSpeed (std::string laneID, double speed)
static void setParameter (const std::string &routeID, const std::string &key, const std::string &value)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
TraCI_Lane & operator= (const TraCI_Lane &src)
invalidated assignment operator
TraCI_Lane ()
invalidated standard constructor
TraCI_Lane (const TraCI_Lane &src)
invalidated copy constructor
Detailed Description
C++ TraCI client API implementation.
Definition at line 52 of file TraCI_Lane.h.
Constructor & Destructor Documentation
TraCI_Lane::TraCI_Lane () private
invalidated standard constructor
TraCI_Lane::TraCI_Lane (const TraCI_Lane & src) private
invalidated copy constructor
Member Function Documentation
std::vector< std::string > TraCI_Lane::getAllowed (std::string laneID) static
Definition at line 109 of file TraCI_Lane.cpp.
References getLane(), MSLane::getPermissions(), getVehicleClassNamesList(), and SVCAll.
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getCO2Emission (std::string laneID) static
Definition at line 146 of file TraCI_Lane.cpp.
References MSLane::getCO2Emissions(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getCOEmission (std::string laneID) static
Definition at line 152 of file TraCI_Lane.cpp.
References MSLane::getCOEmissions(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
std::vector< std::string > TraCI_Lane::getDisallowed (std::string laneID) static
Definition at line 119 of file TraCI_Lane.cpp.
References getLane(), and getVehicleClassNamesList().
Referenced by TraCIServerAPI_Lane::processGet().
std::string TraCI_Lane::getEdgeID (std::string laneID) static
Definition at line 61 of file TraCI_Lane.cpp.
References MSLane::getEdge(), Named::getID(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getElectricityConsumption (std::string laneID) static
Definition at line 187 of file TraCI_Lane.cpp.
References MSLane::getElectricityConsumption(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getFuelConsumption (std::string laneID) static
Definition at line 175 of file TraCI_Lane.cpp.
References MSLane::getFuelConsumption(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getHCEmission (std::string laneID) static
Definition at line 158 of file TraCI_Lane.cpp.
References MSLane::getHCEmissions(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
int TraCI_Lane::getIDCount () static
Definition at line 55 of file TraCI_Lane.cpp.
References getIDList().
Referenced by TraCIServerAPI_Lane::processGet().
std::vector< std::string > TraCI_Lane::getIDList () static
Definition at line 47 of file TraCI_Lane.cpp.
References MSLane::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_Lane::processGet().
const MSLane * TraCI_Lane::getLane (const std::string & id) static
Definition at line 317 of file TraCI_Lane.cpp.
References MSLane::dictionary().
Referenced by getAllowed(), getCO2Emission(), getCOEmission(), getDisallowed(), getEdgeID(), getElectricityConsumption(), getFuelConsumption(), getHCEmission(), getLastStepHaltingNumber(), getLastStepLength(), getLastStepMeanSpeed(), getLastStepOccupancy(), getLastStepVehicleIDs(), getLastStepVehicleNumber(), getLength(), getLinkNumber(), getLinks(), getMaxSpeed(), getNoiseEmission(), getNOxEmission(), getParameter(), getPMxEmission(), getShape(), getTraveltime(), getWaitingTime(), getWidth(), setAllowed(), setDisallowed(), setLength(), setMaxSpeed(), and setParameter().
int TraCI_Lane::getLastStepHaltingNumber (std::string laneID) static
Definition at line 244 of file TraCI_Lane.cpp.
References getLane(), MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMO_const_haltingSpeed.
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getLastStepLength (std::string laneID) static
Definition at line 205 of file TraCI_Lane.cpp.
References getLane(), MSLane::getVehiclesSecure(), and MSLane::releaseVehicles().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getLastStepMeanSpeed (std::string laneID) static
Definition at line 193 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getMeanSpeed().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getLastStepOccupancy (std::string laneID) static
Definition at line 199 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getNettoOccupancy().
Referenced by TraCIServerAPI_Lane::processGet().
std::vector< std::string > TraCI_Lane::getLastStepVehicleIDs (std::string laneID) static
Definition at line 259 of file TraCI_Lane.cpp.
References getLane(), MSLane::getVehiclesSecure(), and MSLane::releaseVehicles().
Referenced by TraCIServerAPI_Lane::processGet().
int TraCI_Lane::getLastStepVehicleNumber (std::string laneID) static
Definition at line 239 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getVehicleNumber().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getLength (std::string laneID) static
Definition at line 67 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getLength().
Referenced by TraCIServerAPI_Lane::processGet().
int TraCI_Lane::getLinkNumber (std::string laneID) static
Definition at line 79 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getLinkCont().
Referenced by TraCIServerAPI_Lane::processGet().
std::vector< TraCIConnection > TraCI_Lane::getLinks (std::string laneID) static
Definition at line 85 of file TraCI_Lane.cpp.
References MSNet::getCurrentTimeStep(), SUMOVTypeParameter::getDefault(), SUMOVTypeParameter::getDefaultDecel(), MSLink::getDirection(), Named::getID(), MSNet::getInstance(), getLane(), MSLink::getLane(), MSLink::getLength(), MSLane::getLinkCont(), MSLane::getSpeedLimit(), MSLink::getState(), StringBijection< T >::getString(), MSLink::getViaLane(), MSLink::hasApproachingFoe(), MSLink::havePriority(), SUMOXMLDefinitions::LinkDirections, SUMOXMLDefinitions::LinkStates, MIN2(), and MSLink::opened().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getMaxSpeed (std::string laneID) static
Definition at line 73 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getSpeedLimit().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getNoiseEmission (std::string laneID) static
Definition at line 181 of file TraCI_Lane.cpp.
References MSLane::getHarmonoise_NoiseEmissions(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getNOxEmission (std::string laneID) static
Definition at line 170 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getNOxEmissions().
Referenced by TraCIServerAPI_Lane::processGet().
std::string TraCI_Lane::getParameter (const std::string & laneID, const std::string & param) static
Definition at line 304 of file TraCI_Lane.cpp.
References getLane(), and Parameterised::getParameter().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getPMxEmission (std::string laneID) static
Definition at line 164 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getPMxEmissions().
Referenced by TraCIServerAPI_Lane::processGet().
TraCIPositionVector TraCI_Lane::getShape (std::string laneID) static
Definition at line 125 of file TraCI_Lane.cpp.
References getLane(), MSLane::getShape(), TraCIPosition::x, TraCIPosition::y, and TraCIPosition::z.
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getTraveltime (std::string laneID) static
Definition at line 227 of file TraCI_Lane.cpp.
References getLane(), MSLane::getLength(), and MSLane::getMeanSpeed().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getWaitingTime (std::string laneID) static
Definition at line 221 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getWaitingSeconds().
Referenced by TraCIServerAPI_Lane::processGet().
double TraCI_Lane::getWidth (std::string laneID) static
Definition at line 140 of file TraCI_Lane.cpp.
References getLane(), and MSLane::getWidth().
Referenced by TraCIServerAPI_Lane::processGet().
TraCI_Lane& TraCI_Lane::operator= (const TraCI_Lane & src) private
invalidated assignment operator
void TraCI_Lane::setAllowed (std::string laneID, std::vector< std::string > allowedClasses) static
Definition at line 274 of file TraCI_Lane.cpp.
References MSLane::CHANGE_PERMISSIONS_PERMANENT, MSLane::getEdge(), getLane(), parseVehicleClasses(), MSEdge::rebuildAllowedLanes(), and MSLane::setPermissions().
Referenced by TraCIServerAPI_Lane::processSet().
void TraCI_Lane::setDisallowed (std::string laneID, std::vector< std::string > disallowedClasses) static
Definition at line 282 of file TraCI_Lane.cpp.
References MSLane::CHANGE_PERMISSIONS_PERMANENT, MSLane::getEdge(), getLane(), parseVehicleClasses(), MSEdge::rebuildAllowedLanes(), and MSLane::setPermissions().
Referenced by TraCIServerAPI_Lane::processSet().
void TraCI_Lane::setLength (std::string laneID, double length) static
Definition at line 297 of file TraCI_Lane.cpp.
References getLane(), and MSLane::setLength().
Referenced by TraCIServerAPI_Lane::processSet().
void TraCI_Lane::setMaxSpeed (std::string laneID, double speed) static
Definition at line 290 of file TraCI_Lane.cpp.
References getLane(), and MSLane::setMaxSpeed().
Referenced by TraCIServerAPI_Lane::processSet().
void TraCI_Lane::setParameter (const std::string & routeID, const std::string & key, const std::string & value) static
Definition at line 310 of file TraCI_Lane.cpp.
References Parameterised::addParameter(), and getLane().
Referenced by TraCIServerAPI_Lane::processSet().
static void TraCI_Lane::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
static void TraCI_Lane::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
TraCI_Lane.h
TraCI_Lane.cpp