SUMO - Simulation of Urban MObility: GUIE2Collector Class Reference
GUIE2Collector Class Reference
The gui-version of the MSE2Collector.
#include <GUIE2Collector.h>
Data Structures
class MyWrapper
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
typedef std::map< std::string, VehicleInfo * > VehicleInfoMap
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Returns the wrapper for this detector.
const std::string & getDescription () const
double getEndPos () const
Returns the end position of the detector.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
std::vector< MSLane * > getLanes ()
Returns a vector containing pointers to the lanes covered by the detector ordered from its first to its last lane.
MSLane * getLastLane () const
Returns the id of the detector's last lane.
double getLength () const
Returns the length of the detector.
double getStartPos () const
Returns the begin position of the detector.
virtual DetectorUsage getUsageType () const
Returns the detector's usage type.
GUIE2Collector (const std::string &id, DetectorUsage usage, MSLane *lane, double startPos, double endPos, double detLength, SUMOTime haltingTimeThreshold, double haltingSpeedThreshold, double jamDistThreshold, const std::string &vTypes, bool showDetector)
Constructor with given end position and detector length.
GUIE2Collector (const std::string &id, DetectorUsage usage, std::vector< MSLane * > lanes, double startPos, double endPos, SUMOTime haltingTimeThreshold, double haltingSpeedThreshold, double jamDistThreshold, const std::string &vTypes, bool showDetector)
Constructor with a sequence of lanes and given start and end position on the first and last lanes.
virtual void notifyMoveInternal (const SUMOVehicle &veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane)
Internal notification about the vehicle moves.
virtual void reset ()
Resets all values.
void setDescription (const std::string &description)
void setID (const std::string &newID)
resets the id
~GUIE2Collector ()
Destructor.
Methods inherited from MSMoveReminder
virtual bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Adds/removes vehicles from the list of vehicles to regard.
virtual bool notifyLeave (SUMOVehicle &veh, double lastPos, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Removes a known vehicle due to its lane-change.
virtual bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason, const MSLane *enteredLane)
Adds the vehicle to known vehicles if not beyond the dector.
Methods inherited from MSDetectorFileOutput.
virtual void detectorUpdate (const SUMOTime step)
Computes the detector values in each time step.
virtual void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Write the generated output to the given device.
virtual void writeXMLDetectorProlog (OutputDevice &dev) const
Open the XML-output.
Methods returning current values
int getCurrentVehicleNumber () const
Returns the number of vehicles currently on the detector.
double getCurrentOccupancy () const
Returns the current detector occupancy.
double getCurrentMeanSpeed () const
Returns the mean vehicle speed of vehicles currently on the detector.
double getCurrentMeanLength () const
Returns the mean vehicle length of vehicles currently on the detector.
int getCurrentJamNumber () const
Returns the current number of jams.
int getCurrentMaxJamLengthInVehicles () const
Returns the length in vehicles of the currently largest jam.
double getCurrentMaxJamLengthInMeters () const
Returns the length in meters of the currently largest jam.
int getCurrentJamLengthInVehicles () const
Returns the length of all jams in vehicles.
double getCurrentJamLengthInMeters () const
Returns the length of all jams in meters.
int getCurrentStartedHalts () const
Returns the length of all jams in meters.
int getCurrentHaltingNumber () const
Returns the number of current haltings within the area.
std::vector< std::string > getCurrentVehicleIDs () const
Returns the IDs of the vehicles within the area.
std::vector< VehicleInfo * > getCurrentVehicles () const
Returns the VehicleInfos for the vehicles currently on the detector.
int getPassedVeh ()
Returns the number of vehicles passed over the sensor (i.e. entered the sensor)
void subtractPassedVeh (int passed)
Subtract the number of vehicles indicated from passed from the sensor count.
Estimation methods
TODO: Need documentation, used for tls control in MSSOTLE2Sensors (->Daniel?)
int getEstimatedCurrentVehicleNumber (double speedThreshold) const
Returns an estimate of the number of vehicles currently on the detector.
double getEstimateQueueLength () const
Returns an estimate of the lenght of the queue of vehicles currently stopped on the detector.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
Private Attributes
bool myShowDetectorInGUI
Whether the detector shall be drawn in the gui.
Virtual methods to implement by derived classes
bool vehicleApplies (const SUMOVehicle &veh) const
Checks whether the detector measures vehicles of the given type.
bool isTyped () const
Checks whether the detector is type specific.
std::set< std::string > myVehicleTypes
The vehicle types to look for (empty means all)
Detailed Description
The gui-version of the MSE2Collector.
Allows the building of a wrapper (also declared herein) which draws the detector on the gl-canvas. Beside this, the method "amVisible" is overridden to signalise that this detector is not used for simulation- -internal reasons, but is placed over the simulation by the user.
Definition at line 51 of file GUIE2Collector.h.
Member Typedef Documentation
typedef std::map<std::string, VehicleInfo*> MSE2Collector::VehicleInfoMap inherited
Definition at line 158 of file MSE2Collector.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 96 of file MSMoveReminder.h.
Constructor & Destructor Documentation
GUIE2Collector::GUIE2Collector (const std::string & id, DetectorUsage usage, MSLane * lane, double startPos, double endPos, double detLength, SUMOTime haltingTimeThreshold, double haltingSpeedThreshold, double jamDistThreshold, const std::string & vTypes, bool showDetector)
Constructor with given end position and detector length.
Parameters
[in] id The detector's unique id.
[in] usage Information how the detector is used
[in] lane The lane the detector ends
[in] startPos The start position on the lane the detector is placed at
[in] endPos The end position on the lane the detector is placed at
[in] length The length the detector has (heuristic lane selection is done if the continuation is not unique)
[in] haltingTimeThreshold The time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold The speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold The distance between two vehicles in order to not count them to one jam
[in] vTypes Vehicle types, that the detector takes into account
[in] friendlyPositioning Whether positions should be corrected to "snap" on lane beginnings or ends if closer than POS_EPSILON
[in] showDetector Whether the detector should be visible in the GUI
Note
Exactly one of the arguments startPos, endPos and length should be invalid (i.e. equal to std::numeric_limits<double>::max()). If length is invalid, it is required that 0 <= startPos < endPos <= lane->length If endPos is invalid, the detector may span over several lanes downstream of the lane If pos is invalid, the detector may span over several lanes upstream of the lane
Definition at line 51 of file GUIE2Collector.cpp.
GUIE2Collector::GUIE2Collector (const std::string & id, DetectorUsage usage, std::vector< MSLane * > lanes, double startPos, double endPos, SUMOTime haltingTimeThreshold, double haltingSpeedThreshold, double jamDistThreshold, const std::string & vTypes, bool showDetector)
Constructor with a sequence of lanes and given start and end position on the first and last lanes.
Parameters
[in] id The detector's unique id.
[in] usage Information how the detector is used
[in] lanes A sequence of lanes the detector covers (must form a continuous piece)
[in] startPos The position of the detector start on the first lane the detector is placed at
[in] endPos The position of the detector end on the last lane the detector is placed at
[in] haltingTimeThreshold The time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold The speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold The distance between two vehicles in order to not count them to one jam
[in] vTypes Vehicle types, that the detector takes into account
[in] friendlyPositioning Whether positions should be corrected to "snap" on lane beginnings or ends if closer than POS_EPSILON
[in] showDetector Whether the detector should be visible in the GUI
Definition at line 59 of file GUIE2Collector.cpp.
GUIE2Collector::~GUIE2Collector ()
Destructor.
Definition at line 67 of file GUIE2Collector.cpp.
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
GUIDetectorWrapper * GUIE2Collector::buildDetectorGUIRepresentation () virtual
Returns the wrapper for this detector.
Returns
The wrapper representing the detector
See also
MyWrapper
Reimplemented from MSDetectorFileOutput.
Definition at line 71 of file GUIE2Collector.cpp.
void MSE2Collector::detectorUpdate (const SUMOTime step) virtual inherited
Computes the detector values in each time step.
This method should be called at the end of a simulation step, when all vehicles have moved. The current values are computed and summed up with the previous.
Parameters
[in] currentTime The current simulation time
Reimplemented from MSDetectorFileOutput.
Definition at line 730 of file MSE2Collector.cpp.
References MSE2Collector::aggregateOutputValues(), MSE2Collector::buildJam(), MSE2Collector::checkJam(), MSE2Collector::compareMoveNotification(), MSE2Collector::integrateMoveNotification(), MSE2Collector::myCurrentHaltingsNumber, MSE2Collector::myCurrentMeanLength, MSE2Collector::myCurrentMeanSpeed, MSE2Collector::myCurrentStartedHalts, MSE2Collector::myHaltingVehicleDurations, Named::myID, MSE2Collector::myIntervalHaltingVehicleDurations, MSE2Collector::myLeftVehicles, MSE2Collector::myMoveNotifications, MSE2Collector::myNumberOfEnteredVehicles, MSE2Collector::myNumberOfLeftVehicles, MSE2Collector::myVehicleInfos, MSE2Collector::processJams(), and SIMTIME.
Referenced by MSE2Collector::getUsageType().
int MSE2Collector::getCurrentHaltingNumber () const inline inherited
Returns the number of current haltings within the area.
If no vehicle is within the area, 0 is returned.
Returns
The mean number of haltings within the area
Definition at line 475 of file MSE2Collector.h.
References MSE2Collector::getCurrentVehicleIDs(), MSE2Collector::getCurrentVehicles(), and MSE2Collector::myCurrentHaltingsNumber.
Referenced by TraCI_LaneArea::getLastStepHaltingNumber().
double MSE2Collector::getCurrentJamLengthInMeters () const inline inherited
Returns the length of all jams in meters.
Definition at line 460 of file MSE2Collector.h.
References MSE2Collector::myCurrentJamLengthInMeters.
Referenced by TraCI_LaneArea::getJamLengthMeters(), and GUIE2Collector::MyWrapper::getParameterWindow().
int MSE2Collector::getCurrentJamLengthInVehicles () const inline inherited
Returns the length of all jams in vehicles.
Definition at line 455 of file MSE2Collector.h.
References MSE2Collector::myCurrentJamLengthInVehicles.
Referenced by TraCI_LaneArea::getJamLengthVehicle(), and GUIE2Collector::MyWrapper::getParameterWindow().
int MSE2Collector::getCurrentJamNumber () const inline inherited
Returns the current number of jams.
Definition at line 440 of file MSE2Collector.h.
References MSE2Collector::myCurrentJamNo.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
double MSE2Collector::getCurrentMaxJamLengthInMeters () const inline inherited
Returns the length in meters of the currently largest jam.
Definition at line 450 of file MSE2Collector.h.
References MSE2Collector::myCurrentMaxJamLengthInMeters.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
int MSE2Collector::getCurrentMaxJamLengthInVehicles () const inline inherited
Returns the length in vehicles of the currently largest jam.
Definition at line 445 of file MSE2Collector.h.
References MSE2Collector::myCurrentMaxJamLengthInVehicles.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
double MSE2Collector::getCurrentMeanLength () const inline inherited
Returns the mean vehicle length of vehicles currently on the detector.
Definition at line 435 of file MSE2Collector.h.
References MSE2Collector::myCurrentMeanLength.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
double MSE2Collector::getCurrentMeanSpeed () const inline inherited
Returns the mean vehicle speed of vehicles currently on the detector.
Definition at line 430 of file MSE2Collector.h.
References MSE2Collector::myCurrentMeanSpeed.
Referenced by TraCI_LaneArea::getLastStepMeanSpeed(), GUIE2Collector::MyWrapper::getParameterWindow(), and MSSOTLE2Sensors::meanVehiclesSpeed().
double MSE2Collector::getCurrentOccupancy () const inline inherited
Returns the current detector occupancy.
Definition at line 425 of file MSE2Collector.h.
References MSE2Collector::myCurrentOccupancy.
Referenced by TraCI_LaneArea::getLastStepOccupancy(), and GUIE2Collector::MyWrapper::getParameterWindow().
int MSE2Collector::getCurrentStartedHalts () const inline inherited
Returns the length of all jams in meters.
Definition at line 465 of file MSE2Collector.h.
References MSE2Collector::myCurrentStartedHalts.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
std::vector< std::string > MSE2Collector::getCurrentVehicleIDs () const inherited
Returns the IDs of the vehicles within the area.
Returns
The IDs of the vehicles that have passed the entry, but not yet an exit point
Definition at line 1248 of file MSE2Collector.cpp.
References MSE2Collector::myVehicleInfos.
Referenced by MSE2Collector::getCurrentHaltingNumber(), and TraCI_LaneArea::getLastStepVehicleIDs().
int MSE2Collector::getCurrentVehicleNumber () const inherited
Returns the number of vehicles currently on the detector.
Definition at line 1235 of file MSE2Collector.cpp.
References MSE2Collector::myVehicleInfos.
Referenced by MSSOTLE2Sensors::count(), MSE2Collector::getLastLane(), TraCI_LaneArea::getLastStepVehicleNumber(), GUIE2Collector::MyWrapper::getParameterWindow(), and MSSOTLE2Sensors::meanVehiclesSpeed().
std::vector< MSE2Collector::VehicleInfo * > MSE2Collector::getCurrentVehicles () const inherited
Returns the VehicleInfos for the vehicles currently on the detector.
Definition at line 1261 of file MSE2Collector.cpp.
References MSE2Collector::myVehicleInfos.
Referenced by MSSOTLE2Sensors::count(), MSE2Collector::getCurrentHaltingNumber(), and MSDelayBasedTrafficLightLogic::proposeProlongation().
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 231 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::setDeviceParameter().
double MSE2Collector::getEndPos () const inline inherited
Returns the end position of the detector.
Returns
The detector's end position
Definition at line 383 of file MSE2Collector.h.
References MSE2Collector::myEndPos.
Referenced by TraCI_LaneArea::getLength().
int MSE2Collector::getEstimatedCurrentVehicleNumber (double speedThreshold) const inherited
Returns an estimate of the number of vehicles currently on the detector.
Definition at line 1275 of file MSE2Collector.cpp.
References MSLane::getSpeedLimit(), MSMoveReminder::myLane, and MSE2Collector::myVehicleInfos.
Referenced by MSE2Collector::subtractPassedVeh().
double MSE2Collector::getEstimateQueueLength () const inherited
Returns an estimate of the lenght of the queue of vehicles currently stopped on the detector.
Definition at line 1299 of file MSE2Collector.cpp.
References MSLane::getLength(), max, MIN2(), MSMoveReminder::myLane, and MSE2Collector::myVehicleInfos.
Referenced by MSE2Collector::subtractPassedVeh().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), MSNet::addParkingArea(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), TraCI_Vehicle::getBestLanes(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), TraCI_Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), TraCI_Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), TraCI_Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSNet::getParkingAreaID(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), TraCI_Vehicle::getRoadID(), TraCI_Vehicle::getRouteID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_SSM::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSDevice_SSM::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_SSM::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingZone(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), toString(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSDevice_SSM::updateEncounter(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSPModel_Striping::PState::moveToNextLane(), operator<<(), TraCIServerAPI_Vehicle::processSet(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), MSAbstractLaneChangeModel::updateShadowLane(), and TraCIServerAPI_Vehicle::vtdMap().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 90 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
std::vector< MSLane * > MSE2Collector::getLanes () inherited
Returns a vector containing pointers to the lanes covered by the detector ordered from its first to its last lane.
Definition at line 557 of file MSE2Collector.cpp.
References MSLane::dictionary(), and MSE2Collector::myLanes.
Referenced by MSE2Collector::getLastLane(), MSE2Collector::initAuxiliaries(), and GUIE2Collector::MyWrapper::MyWrapper().
MSLane* MSE2Collector::getLastLane () const inline inherited
Returns the id of the detector's last lane.
Returns
The detector's end position
Definition at line 400 of file MSE2Collector.h.
References MSE2Collector::getCurrentVehicleNumber(), MSE2Collector::getLanes(), MSE2Collector::myLastLane, and MSE2Collector::reset().
double MSE2Collector::getLength () const inline inherited
Returns the length of the detector.
Returns
The detector's length
Definition at line 391 of file MSE2Collector.h.
References MSE2Collector::myDetectorLength.
Referenced by MSE2Collector::checkPositioning(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::MyWrapper(), and MSE2Collector::selectLanes().
int MSE2Collector::getPassedVeh () inline inherited
Returns the number of vehicles passed over the sensor (i.e. entered the sensor)
Returns
number of cars passed over the sensor
Definition at line 493 of file MSE2Collector.h.
References MSE2Collector::myNumberOfEnteredVehicles.
Referenced by MSSOTLE2Sensors::getPassedVeh().
double MSE2Collector::getStartPos () const inline inherited
Returns the begin position of the detector.
Returns
The detector's begin position
Definition at line 374 of file MSE2Collector.h.
References MSE2Collector::myStartPos.
Referenced by TraCI_LaneArea::getLength(), GUIE2Collector::MyWrapper::getParameterWindow(), TraCI_LaneArea::getPosition(), and GUIE2Collector::MyWrapper::MyWrapper().
virtual DetectorUsage MSE2Collector::getUsageType () const inline virtual inherited
Returns the detector's usage type.
See also
DetectorUsage
Returns
How the detector is used.
Definition at line 271 of file MSE2Collector.h.
References MSE2Collector::detectorUpdate(), MSE2Collector::VehicleInfo::lastPos, MSE2Collector::myUsage, MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSE2Collector::writeXMLDetectorProlog(), and MSE2Collector::writeXMLOutput().
Referenced by GUIE2Collector::MyWrapper::drawGL().
bool MSDetectorFileOutput::isTyped () const inline inherited
Checks whether the detector is type specific.
Returns
whether vehicle types are considered
Definition at line 155 of file MSDetectorFileOutput.h.
References MSDetectorFileOutput::myVehicleTypes.
Referenced by MSMeanData_Amitran::MSLaneMeanDataValues::write().
bool MSE2Collector::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason, const MSLane * enteredLane) virtual inherited
Adds the vehicle to known vehicles if not beyond the dector.
If the vehicles is within the detector are, it is added to the list of known vehicles. The method returns true as long as the vehicle is not beyond the detector.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
False, if vehicle passed the detector entirely, else true.
See also
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 659 of file MSE2Collector.cpp.
References Named::getID(), SUMOVehicle::getID(), SUMOVehicle::getLane(), SUMOVehicle::isOnRoad(), MSE2Collector::makeVehicleInfo(), MSE2Collector::myLanes, MSE2Collector::myVehicleInfos, SIMTIME, and MSDetectorFileOutput::vehicleApplies().
Referenced by MSE2Collector::getUsageType().
bool MSE2Collector::notifyLeave (SUMOVehicle & veh, double lastPos, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual inherited
Removes a known vehicle due to its lane-change.
If the reported vehicle is known, it is removed from the list of vehicles to regard (myKnownVehicles).
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 620 of file MSE2Collector.cpp.
References Named::getID(), SUMOVehicle::getID(), MIN2(), MSE2Collector::myLanes, MSE2Collector::myNumberOfLeftVehicles, MSE2Collector::myOffsets, MSE2Collector::myVehicleInfos, MSMoveReminder::NOTIFICATION_JUNCTION, and SIMTIME.
Referenced by MSE2Collector::getUsageType().
bool MSE2Collector::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) virtual inherited
Adds/removes vehicles from the list of vehicles to regard.
As soon as the reported vehicle enters the detector area (position>myStartPos) it is added to the list of vehicles to regard (myKnownVehicles). It is removed from this list if it leaves the detector (position<length>myEndPos). The method returns true as long as the vehicle is not beyond the detector.
Parameters
[in] veh The vehicle in question.
[in] oldPos Position before the move-micro-timestep.
[in] newPos Position after the move-micro-timestep. Note that this position is given in reference to the begin of the entry lane of the vehicle.
[in] newSpeed Unused here.
Returns
False, if vehicle passed the detector entirely, else true.
See also
MSMoveReminder
MSMoveReminder::notifyMove
Reimplemented from MSMoveReminder.
Definition at line 567 of file MSE2Collector.cpp.
References MSE2Collector::VehicleInfo::distToDetectorEnd, MSE2Collector::VehicleInfo::entryOffset, MSE2Collector::VehicleInfo::exitOffset, SUMOVehicle::getID(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), MSE2Collector::VehicleInfo::hasEntered, MSE2Collector::makeMoveNotification(), MSE2Collector::myDetectorLength, MSE2Collector::myLeftVehicles, MSE2Collector::myMoveNotifications, MSE2Collector::myNumberOfEnteredVehicles, MSE2Collector::myVehicleInfos, and SIMTIME.
Referenced by MSE2Collector::getUsageType().
virtual void MSMoveReminder::notifyMoveInternal (const SUMOVehicle & veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane) inline virtual inherited
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] frontOnLane time the front of the vehicle spent on the lane.
[in] timeOnLane time some part of the vehicle spent on the lane.
[in] meanSpeedFrontOnLane Average speed for the time that the front is on the lane.
[in] meanSpeedVehicleOnLane Average speed for the time that the vehicle is on the lane (with front or back).
[in] travelledDistanceFrontOnLane distance travelled while overlapping with the lane.
[in] travelledDistanceVehicleOnLane distance travelled while front was on the lane.
Reimplemented in MSMeanData::MeanDataValueTracker, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 211 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and MSMoveReminder::updateDetector().
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 94 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
void MSE2Collector::reset () virtual inherited
Resets all values.
This method is called on initialisation and as soon as the values were written. Values for the next interval may be collected, then. The list of known vehicles stays untouched.
Reimplemented from MSDetectorFileOutput.
Definition at line 1207 of file MSE2Collector.cpp.
References MSE2Collector::myIntervalHaltingVehicleDurations, MSE2Collector::myJamLengthInMetersSum, MSE2Collector::myJamLengthInVehiclesSum, MSE2Collector::myMaxJamInMeters, MSE2Collector::myMaxJamInVehicles, MSE2Collector::myMaxOccupancy, MSE2Collector::myMaxVehicleNumber, MSE2Collector::myMeanMaxJamInMeters, MSE2Collector::myMeanMaxJamInVehicles, MSE2Collector::myMeanVehicleNumber, MSE2Collector::myNumberOfEnteredVehicles, MSE2Collector::myNumberOfLeftVehicles, MSE2Collector::myOccupancySum, MSE2Collector::myPastIntervalStandingDurations, MSE2Collector::myPastStandingDurations, MSE2Collector::mySpeedSum, MSE2Collector::myStartedHalts, MSE2Collector::myTimeSamples, MSE2Collector::myTotalTimeLoss, and MSE2Collector::myVehicleSamples.
Referenced by MSE2Collector::getLastLane(), MSE2Collector::MSE2Collector(), and MSE2Collector::writeXMLOutput().
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 227 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::Distribution_Parameterized(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MSE2Collector::subtractPassedVeh (int passed) inline inherited
Subtract the number of vehicles indicated from passed from the sensor count.
Parameters
[in] passed - int that indicates the number of vehicles to subtract
Definition at line 501 of file MSE2Collector.h.
References MSE2Collector::addDetectorToLanes(), MSE2Collector::aggregateOutputValues(), MSE2Collector::buildJam(), MSE2Collector::calculateSegmentTimeLoss(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSE2Collector::checkJam(), MSE2Collector::checkPositioning(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSE2Collector::initAuxiliaries(), MSE2Collector::integrateMoveNotification(), MSE2Collector::VehicleInfo::length, MSE2Collector::makeMoveNotification(), MSE2Collector::makeVehicleInfo(), MSE2Collector::myNumberOfEnteredVehicles, MSE2Collector::processJams(), MSE2Collector::recalculateDetectorLength(), MSE2Collector::selectLanes(), and MSE2Collector::snap().
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 51 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
bool MSDetectorFileOutput::vehicleApplies (const SUMOVehicle & veh) const inline inherited
Checks whether the detector measures vehicles of the given type.
Parameters
[in] veh the vehicle of which the type is checked.
Returns
whether it should be measured
Definition at line 146 of file MSDetectorFileOutput.h.
References MSVehicleType::getID(), SUMOVehicle::getVehicleType(), and MSDetectorFileOutput::myVehicleTypes.
Referenced by MSMeanData::MeanDataValues::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSInductLoop::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSInstantInductLoop::notifyMove().
void MSE2Collector::writeXMLDetectorProlog (OutputDevice & dev) const virtual inherited
Open the XML-output.
The implementing function should open an xml element using OutputDevice::writeXMLHeader.
Parameters
[in] dev The output device to write the root into
Exceptions
IOError If an error on writing occurs
Implements MSDetectorFileOutput.
Definition at line 1122 of file MSE2Collector.cpp.
References OutputDevice::writeXMLHeader().
Referenced by MSE2Collector::getUsageType().
void MSE2Collector::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) virtual inherited
Write the generated output to the given device.
Parameters
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
Exceptions
IOError If an error on writing occurs
Implements MSDetectorFileOutput.
Definition at line 1127 of file MSE2Collector.cpp.
References Named::getID(), MAX2(), MSE2Collector::myHaltingVehicleDurations, MSE2Collector::myIntervalHaltingVehicleDurations, MSE2Collector::myJamLengthInMetersSum, MSE2Collector::myJamLengthInVehiclesSum, MSE2Collector::myMaxJamInMeters, MSE2Collector::myMaxJamInVehicles, MSE2Collector::myMaxOccupancy, MSE2Collector::myMaxVehicleNumber, MSE2Collector::myMeanMaxJamInMeters, MSE2Collector::myMeanMaxJamInVehicles, MSE2Collector::myMeanVehicleNumber, MSE2Collector::myNumberOfEnteredVehicles, MSE2Collector::myOccupancySum, MSE2Collector::myPastIntervalStandingDurations, MSE2Collector::myPastStandingDurations, MSE2Collector::mySpeedSum, MSE2Collector::myStartedHalts, MSE2Collector::myTimeSamples, MSE2Collector::myTotalTimeLoss, MSE2Collector::myVehicleSamples, MSE2Collector::reset(), STEPS2TIME, and time2string().
Referenced by MSE2Collector::getUsageType().
Field Documentation
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 243 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 241 of file MSMoveReminder.h.
Referenced by MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSMoveReminder::MSMoveReminder(), MSInductLoop::notifyEnter(), and MSMeanData::MeanDataValueTracker::reset().
bool GUIE2Collector::myShowDetectorInGUI private
Whether the detector shall be drawn in the gui.
Definition at line 111 of file GUIE2Collector.h.
Referenced by GUIE2Collector::MyWrapper::drawGL().
std::set<std::string> MSDetectorFileOutput::myVehicleTypes protected inherited
The vehicle types to look for (empty means all)
Definition at line 162 of file MSDetectorFileOutput.h.
Referenced by MSDetectorFileOutput::isTyped(), MSDetectorFileOutput::MSDetectorFileOutput(), and MSDetectorFileOutput::vehicleApplies().
The documentation for this class was generated from the following files:
GUIE2Collector.h
GUIE2Collector.cpp