SUMO - Simulation of Urban MObility: polyconvert_main.cpp File Reference
polyconvert_main.cpp File Reference
#include <config.h>
#include <iostream>
#include <string>
#include <utils/options/OptionsIO.h>
#include <utils/options/OptionsCont.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/StringTokenizer.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/TplConvert.h>
#include <utils/common/ToString.h>
#include <utils/iodevices/OutputDevice.h>
#include <utils/importio/LineReader.h>
#include <utils/geom/GeoConvHelper.h>
#include <utils/geom/GeomConvHelper.h>
#include <utils/geom/Boundary.h>
#include <utils/xml/SUMOSAXReader.h>
#include <utils/xml/XMLSubSys.h>
#include <polyconvert/PCLoaderVisum.h>
#include <polyconvert/PCLoaderDlrNavteq.h>
#include <polyconvert/PCLoaderXML.h>
#include <polyconvert/PCLoaderOSM.h>
#include <polyconvert/PCLoaderArcView.h>
#include <polyconvert/PCTypeMap.h>
#include <polyconvert/PCTypeDefHandler.h>
#include <polyconvert/PCNetProjectionLoader.h>
#include "pc_typemap.h"
Functions
void fillOptions ()
int main (int argc, char **argv)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Christoph Sommer
Michael Behrisch
Melanie Knocke
Date
Mon, 05 Dec 2005
Version
Id
polyconvert_main.cpp 23529 2017-03-18 10:22:36Z behrisch
Definition in file polyconvert_main.cpp.
Function Documentation
void fillOptions ()
Definition at line 71 of file polyconvert_main.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), GeoConvHelper::addProjectionOptions(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), and OptionsCont::getOptions().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 223 of file polyconvert_main.cpp.
References SystemFrame::checkOptions(), SystemFrame::close(), GeoConvHelper::computeFinal(), fillOptions(), OptionsCont::getBool(), FileHelpers::getConfigurationRelative(), GeoConvHelper::getConvBoundary(), MsgHandler::getErrorInstance(), GeoConvHelper::getFinal(), OptionsIO::getOptions(), OptionsCont::getOptions(), XMLSubSys::getSAXReader(), OptionsCont::getString(), OptionsCont::getStringVector(), MsgHandler::inform(), XMLSubSys::init(), GeoConvHelper::init(), MsgHandler::initOutputOptions(), OptionsCont::isDefault(), OptionsCont::isSet(), PCNetProjectionLoader::load(), PCLoaderVisum::loadIfSet(), PCLoaderOSM::loadIfSet(), PCLoaderXML::loadIfSet(), PCLoaderArcView::loadIfSet(), PCLoaderDlrNavteq::loadIfSet(), navteqTypemap, osmTypemap, GeomConvHelper::parseBoundaryReporting(), SUMOSAXReader::parseString(), OptionsCont::processMetaOptions(), XMLSubSys::runParser(), OptionsCont::set(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), OptionsCont::setDefault(), GenericSAXHandler::setFileName(), XMLSubSys::setValidation(), toString(), VERSION_STRING, visumTypemap, WRITE_ERROR, WRITE_WARNING, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().