SUMO - Simulation of Urban MObility: GNEUndoList Class Reference
GNEUndoList Class Reference
#include <GNEUndoList.h>
Data Structures
class CommandGroup
class CommandGroup
Public Member Functions
GNEUndoList (GNEApplicationWindow *parent)
FOX declaration.
bool hasCommandGroup () const
Check if undoList has command group.
void p_abort ()
reverts and discards ALL active command groups
void p_add (GNEChange_Attribute *cmd)
special method, avoid empty changes, always execute
void p_begin (const std::string &description)
Begin undo command sub-group. This begins a new group of commands that are treated as a single command. Must eventually be followed by a matching end() after recording the sub-commands. The new sub-group will be appended to its parent group's undo list when end() is called.
void p_clear ()
clears the undo list (implies abort)
void p_end ()
End undo command sub-group. If the sub-group is still empty, it will be deleted; otherwise, the sub-group will be added as a new command into parent group. A matching begin() must have been called previously.
void redo ()
redo the last command group
void undo ()
undo the last command group
FOX-callbacks
event after Undo
long p_onUpdUndo (FXObject *, FXSelector, void *)
long p_onUpdRedo (FXObject *, FXSelector, void *)
event after Redo
Private Attributes
std::stack< CommandGroup * > myCommandGroups
GNEApplicationWindow *const myParent
Detailed Description
Definition at line 55 of file GNEUndoList.h.
Constructor & Destructor Documentation
GNEUndoList::GNEUndoList (GNEApplicationWindow * parent)
FOX declaration.
constructor
Note
be aware that "parent" may be not fully initialized when stored here, so don't call any methods on it.
Definition at line 75 of file GNEUndoList.cpp.
Member Function Documentation
bool GNEUndoList::hasCommandGroup () const
Check if undoList has command group.
Definition at line 174 of file GNEUndoList.cpp.
References myCommandGroups.
Referenced by GNEJunction::invalidateTLS(), GNEViewNet::onLeftBtnPress(), p_abort(), p_onUpdRedo(), p_onUpdUndo(), and GNEJunction::setLogicValid().
void GNEUndoList::p_abort ()
reverts and discards ALL active command groups
Definition at line 103 of file GNEUndoList.cpp.
References hasCommandGroup(), and myCommandGroups.
Referenced by GNEViewNet::abortOperation(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), and p_clear().
void GNEUndoList::p_add (GNEChange_Attribute * cmd)
special method, avoid empty changes, always execute
Definition at line 129 of file GNEUndoList.cpp.
References GNEChange_Attribute::trueChange().
Referenced by GNEVariableSpeedSign::commmitAdditionalGeometryMoved(), GNEDetector::commmitAdditionalGeometryMoved(), GNEStoppingPlace::commmitAdditionalGeometryMoved(), GNERerouter::commmitAdditionalGeometryMoved(), GNEDetectorE3::commmitAdditionalGeometryMoved(), GNEDetectorE1::setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE2::setAttribute(), GNEContainerStop::setAttribute(), GNEBusStop::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNERouteProbe::setAttribute(), GNERerouter::setAttribute(), GNEChargingStation::setAttribute(), GNEDetectorE3::setAttribute(), GNEConnection::setAttribute(), GNEEdge::setAttribute(), GNECalibrator::setAttribute(), and GNELane::setAttribute().
void GNEUndoList::p_begin (const std::string & description)
Begin undo command sub-group. This begins a new group of commands that are treated as a single command. Must eventually be followed by a matching end() after recording the sub-commands. The new sub-group will be appended to its parent group's undo list when end() is called.
Definition at line 82 of file GNEUndoList.cpp.
References myCommandGroups.
Referenced by GNEViewNet::addRestrictedLane(), GNENet::addReversedEdge(), GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GNEAdditionalHandler::buildVariableSpeedSign(), GNEVariableSpeedSign::commmitAdditionalGeometryMoved(), GNEDetector::commmitAdditionalGeometryMoved(), GNEStoppingPlace::commmitAdditionalGeometryMoved(), GNERerouter::commmitAdditionalGeometryMoved(), GNEDetectorE3::commmitAdditionalGeometryMoved(), GNEEdge::copyTemplate(), GNENet::createEdge(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNEViewNet::deleteSelectedAdditionals(), GNEViewNet::deleteSelectedEdges(), GNEViewNet::deleteSelectedJunctions(), GNENet::duplicateLane(), GNETLSEditorFrame::editJunction(), GNENet::finishMoveSelection(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNEViewNet::hotkeyDel(), GNENet::joinSelectedJunctions(), GNENet::mergeJunctions(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEViewNet::onCmdDuplicateLane(), GNEApplicationWindow::onCmdOpenAdditionals(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNEViewNet::onCmdRevertRestriction(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GNEViewNet::removeRestrictedLane(), GNENet::removeSolitaryJunctions(), GNENet::replaceJunctionByGeometry(), GNEViewNet::restrictLane(), GNENet::reverseEdge(), GNEEdge::setAttribute(), GNEJunction::setAttribute(), GNEEdge::setEndpoint(), GNEEdge::setNumLanes(), GNENet::splitEdge(), and GNENet::splitEdgesBidi().
void GNEUndoList::p_clear ()
clears the undo list (implies abort)
Definition at line 96 of file GNEUndoList.cpp.
References p_abort().
Referenced by GNEApplicationWindow::closeAllWindows(), and GNEApplicationWindow::continueWithUnsavedAdditionalChanges().
void GNEUndoList::p_end ()
End undo command sub-group. If the sub-group is still empty, it will be deleted; otherwise, the sub-group will be added as a new command into parent group. A matching begin() must have been called previously.
Definition at line 89 of file GNEUndoList.cpp.
References myCommandGroups.
Referenced by GNEViewNet::addRestrictedLane(), GNENet::addReversedEdge(), GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GNEAdditionalHandler::buildVariableSpeedSign(), GNEVariableSpeedSign::commmitAdditionalGeometryMoved(), GNEDetector::commmitAdditionalGeometryMoved(), GNEStoppingPlace::commmitAdditionalGeometryMoved(), GNERerouter::commmitAdditionalGeometryMoved(), GNEDetectorE3::commmitAdditionalGeometryMoved(), GNEEdge::copyTemplate(), GNENet::createEdge(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNEViewNet::deleteSelectedAdditionals(), GNEViewNet::deleteSelectedEdges(), GNEViewNet::deleteSelectedJunctions(), GNENet::duplicateLane(), GNENet::finishMoveSelection(), GNESelectorFrame::handleIDs(), GNEViewNet::hotkeyDel(), GNENet::joinSelectedJunctions(), GNENet::mergeJunctions(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEViewNet::onCmdDuplicateLane(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNEApplicationWindow::onCmdOpenAdditionals(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNEViewNet::onCmdRevertRestriction(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GNEViewNet::removeRestrictedLane(), GNENet::removeSolitaryJunctions(), GNENet::replaceJunctionByGeometry(), GNEViewNet::restrictLane(), GNEEdge::setAttribute(), GNEJunction::setAttribute(), GNEEdge::setEndpoint(), GNEEdge::setNumLanes(), and GNENet::splitEdgesBidi().
long GNEUndoList::p_onUpdRedo (FXObject * sender, FXSelector , void *)
event after Redo
Definition at line 156 of file GNEUndoList.cpp.
References hasCommandGroup(), and myCommandGroups.
long GNEUndoList::p_onUpdUndo (FXObject * sender, FXSelector , void *)
Definition at line 138 of file GNEUndoList.cpp.
References hasCommandGroup(), and myCommandGroups.
void GNEUndoList::redo ()
redo the last command group
Definition at line 121 of file GNEUndoList.cpp.
References myParent, and GNEApplicationWindow::updateControls().
void GNEUndoList::undo ()
undo the last command group
Definition at line 113 of file GNEUndoList.cpp.
References myParent, and GNEApplicationWindow::updateControls().
Field Documentation
std::stack<CommandGroup*> GNEUndoList::myCommandGroups private
Definition at line 127 of file GNEUndoList.h.
Referenced by hasCommandGroup(), p_abort(), p_begin(), p_end(), p_onUpdRedo(), and p_onUpdUndo().
GNEApplicationWindow* const GNEUndoList::myParent private
Definition at line 130 of file GNEUndoList.h.
Referenced by redo(), and undo().
The documentation for this class was generated from the following files:
GNEUndoList.h
GNEUndoList.cpp