SUMO - Simulation of Urban MObility: TraCI_MultiEntryExit Class Reference
TraCI_MultiEntryExit Class Reference
C++ TraCI client API implementation.
#include <TraCI_MultiEntryExit.h>
Static Public Member Functions
static int getIDCount ()
static std::vector< std::string > getIDList ()
static int getLastStepHaltingNumber (const std::string &detID)
static double getLastStepMeanSpeed (const std::string &detID)
static std::vector< std::string > getLastStepVehicleIDs (const std::string &detID)
static int getLastStepVehicleNumber (const std::string &detID)
Private Member Functions
TraCI_MultiEntryExit & operator= (const TraCI_MultiEntryExit &src)
invalidated assignment operator
TraCI_MultiEntryExit ()
invalidated standard constructor
TraCI_MultiEntryExit (const TraCI_MultiEntryExit &src)
invalidated copy constructor
Static Private Member Functions
static MSE3Collector * getDetector (const std::string &detID)
Detailed Description
C++ TraCI client API implementation.
Definition at line 49 of file TraCI_MultiEntryExit.h.
Constructor & Destructor Documentation
TraCI_MultiEntryExit::TraCI_MultiEntryExit () private
invalidated standard constructor
TraCI_MultiEntryExit::TraCI_MultiEntryExit (const TraCI_MultiEntryExit & src) private
invalidated copy constructor
Member Function Documentation
MSE3Collector * TraCI_MultiEntryExit::getDetector (const std::string & detID) static private
Definition at line 84 of file TraCI_MultiEntryExit.cpp.
References NamedObjectCont< T >::get(), MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), and SUMO_TAG_ENTRY_EXIT_DETECTOR.
Referenced by getLastStepHaltingNumber(), getLastStepMeanSpeed(), getLastStepVehicleIDs(), and getLastStepVehicleNumber().
int TraCI_MultiEntryExit::getIDCount () static
Definition at line 53 of file TraCI_MultiEntryExit.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::size(), and SUMO_TAG_ENTRY_EXIT_DETECTOR.
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
std::vector< std::string > TraCI_MultiEntryExit::getIDList () static
Definition at line 45 of file TraCI_MultiEntryExit.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::insertIDs(), and SUMO_TAG_ENTRY_EXIT_DETECTOR.
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
int TraCI_MultiEntryExit::getLastStepHaltingNumber (const std::string & detID) static
Definition at line 78 of file TraCI_MultiEntryExit.cpp.
References MSE3Collector::getCurrentHaltingNumber(), and getDetector().
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
double TraCI_MultiEntryExit::getLastStepMeanSpeed (const std::string & detID) static
Definition at line 66 of file TraCI_MultiEntryExit.cpp.
References MSE3Collector::getCurrentMeanSpeed(), and getDetector().
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
std::vector< std::string > TraCI_MultiEntryExit::getLastStepVehicleIDs (const std::string & detID) static
Definition at line 72 of file TraCI_MultiEntryExit.cpp.
References MSE3Collector::getCurrentVehicleIDs(), and getDetector().
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
int TraCI_MultiEntryExit::getLastStepVehicleNumber (const std::string & detID) static
Definition at line 60 of file TraCI_MultiEntryExit.cpp.
References getDetector(), and MSE3Collector::getVehiclesWithin().
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
TraCI_MultiEntryExit& TraCI_MultiEntryExit::operator= (const TraCI_MultiEntryExit & src) private
invalidated assignment operator
The documentation for this class was generated from the following files:
TraCI_MultiEntryExit.h
TraCI_MultiEntryExit.cpp