# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('provaaaaa', ['core'])
    module.source = [
        'model/provaaaaa.cc',
        'helper/provaaaaa-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('provaaaaa')
    module_test.source = [
        'test/provaaaaa-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'provaaaaa'
    headers.source = [
        'model/provaaaaa.h',
        'helper/provaaaaa-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

