SUMO - Simulation of Urban MObility: TraCIServerAPI_LaneArea Class Reference
TraCIServerAPI_LaneArea Class Reference
#include <TraCIServerAPI_LaneArea.h>
Static Public Member Functions
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa1: Get AreaDetector Variable)
Private Member Functions
TraCIServerAPI_LaneArea & operator= (const TraCIServerAPI_LaneArea &s)
invalidated assignment operator
TraCIServerAPI_LaneArea (const TraCIServerAPI_LaneArea &s)
invalidated copy constructor
Detailed Description
Definition at line 52 of file TraCIServerAPI_LaneArea.h.
Constructor & Destructor Documentation
TraCIServerAPI_LaneArea::TraCIServerAPI_LaneArea (const TraCIServerAPI_LaneArea & s) private
invalidated copy constructor
Member Function Documentation
TraCIServerAPI_LaneArea& TraCIServerAPI_LaneArea::operator= (const TraCIServerAPI_LaneArea & s) private
invalidated assignment operator
bool TraCIServerAPI_LaneArea::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa1: Get AreaDetector Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 48 of file TraCIServerAPI_LaneArea.cpp.
References CMD_GET_LANEAREA_VARIABLE, TraCI_LaneArea::getIDCount(), TraCI_LaneArea::getIDList(), TraCI_LaneArea::getJamLengthMeters(), TraCI_LaneArea::getJamLengthVehicle(), TraCI_LaneArea::getLaneID(), TraCI_LaneArea::getLastStepHaltingNumber(), TraCI_LaneArea::getLastStepMeanSpeed(), TraCI_LaneArea::getLastStepOccupancy(), TraCI_LaneArea::getLastStepVehicleIDs(), TraCI_LaneArea::getLastStepVehicleNumber(), TraCI_LaneArea::getLength(), TraCI_LaneArea::getPosition(), ID_COUNT, ID_LIST, JAM_LENGTH_METERS, JAM_LENGTH_VEHICLE, LAST_STEP_MEAN_SPEED, LAST_STEP_OCCUPANCY, LAST_STEP_VEHICLE_HALTING_NUMBER, LAST_STEP_VEHICLE_ID_LIST, LAST_STEP_VEHICLE_NUMBER, tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_LANEAREA_VARIABLE, RTYPE_OK, toHex(), TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, VAR_LANE_ID, VAR_LENGTH, VAR_POSITION, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_LaneArea.h
TraCIServerAPI_LaneArea.cpp