SUMO - Simulation of Urban MObility: GNEAdditionalFrame::AdditionalAttributeSingle Class Reference
GNEAdditionalFrame::AdditionalAttributeSingle Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
AdditionalAttributeSingle (FXComposite *parent)
FOX-declaration.
SumoXMLAttr getAttr () const
return Attr
SumoXMLTag getTag () const
return tag
std::string getValue () const
return value
void hideParameter ()
hide all parameters
const std::string & isAttributeValid () const
returns a empty string if current value is valid, a string with information about invalid value in other case
void showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, std::string value)
show name and value of attribute of type string
void showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, int value)
show name and value of parameters of type int
void showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, double value)
show name and value of parameters of type float/real/time
void showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, bool value)
show name and value of parameters of type bool
~AdditionalAttributeSingle ()
destructor
FOX-callbacks
called when user set the value of an attribute of type int/float/string
long onCmdSetAttribute (FXObject *, FXSelector, void *)
long onCmdSetBooleanAttribute (FXObject *, FXSelector, void *)
called when user change the value of myBoolCheckButton
Protected Member Functions
AdditionalAttributeSingle ()
FOX needs this.
Private Attributes
SumoXMLAttr myAdditionalAttr
current XML attribute
SumoXMLTag myAdditionalTag
current XML attribute
FXCheckButton * myBoolCheckButton
check button to enable/disable the value of boolean parameters
std::string myInvalidValue
string which indicates the reason due current value is invalid
FXLabel * myLabel
lael with the name of the parameter
FXTextField * myTextFieldInt
textField to modify the default value of int/float/string parameters
FXTextField * myTextFieldReal
textField to modify the default value of real/times parameters
FXTextField * myTextFieldStrings
textField to modify the default value of string parameters
Detailed Description
Definition at line 66 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame::AdditionalAttributeSingle::AdditionalAttributeSingle (FXComposite * parent)
FOX-declaration.
constructor
Definition at line 609 of file GNEAdditionalFrame.cpp.
References GUIDesignCheckButtonAttribute, GUIDesignLabelAttribute, GUIDesignTextField, GUIDesignTextFieldInt, GUIDesignTextFieldNCol, GUIDesignTextFieldReal, hideParameter(), MID_GNE_MODE_ADDITIONAL_CHANGEPARAMETER_BOOL, MID_GNE_MODE_ADDITIONAL_CHANGEPARAMETER_TEXT, myBoolCheckButton, myLabel, myTextFieldInt, myTextFieldReal, and myTextFieldStrings.
GNEAdditionalFrame::AdditionalAttributeSingle::~AdditionalAttributeSingle ()
destructor
Definition at line 624 of file GNEAdditionalFrame.cpp.
GNEAdditionalFrame::AdditionalAttributeSingle::AdditionalAttributeSingle () inline protected
FOX needs this.
Definition at line 115 of file GNEAdditionalFrame.h.
Member Function Documentation
SumoXMLAttr GNEAdditionalFrame::AdditionalAttributeSingle::getAttr () const
return Attr
Definition at line 708 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr.
SumoXMLTag GNEAdditionalFrame::AdditionalAttributeSingle::getTag () const
return tag
Definition at line 702 of file GNEAdditionalFrame.cpp.
References myAdditionalTag.
std::string GNEAdditionalFrame::AdditionalAttributeSingle::getValue () const
return value
Definition at line 714 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isTime(), myAdditionalAttr, myAdditionalTag, myBoolCheckButton, myTextFieldInt, myTextFieldReal, and myTextFieldStrings.
void GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter ()
hide all parameters
Definition at line 689 of file GNEAdditionalFrame.cpp.
References GNEFrame::hide(), myAdditionalAttr, myAdditionalTag, myBoolCheckButton, myLabel, myTextFieldInt, myTextFieldReal, myTextFieldStrings, SUMO_ATTR_NOTHING, and SUMO_TAG_NOTHING.
Referenced by AdditionalAttributeSingle().
const std::string & GNEAdditionalFrame::AdditionalAttributeSingle::isAttributeValid () const
returns a empty string if current value is valid, a string with information about invalid value in other case
Definition at line 728 of file GNEAdditionalFrame.cpp.
References myInvalidValue.
long GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute (FXObject * , FXSelector , void *)
Definition at line 734 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::isFilename(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isPositive(), GNEAttributeCarrier::isProbability(), GNEAttributeCarrier::isTime(), GNEAttributeCarrier::isValidFilename(), myAdditionalAttr, myAdditionalTag, myInvalidValue, myTextFieldInt, myTextFieldReal, myTextFieldStrings, and toString().
long GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetBooleanAttribute (FXObject * , FXSelector , void *)
called when user change the value of myBoolCheckButton
Definition at line 802 of file GNEAdditionalFrame.cpp.
References myBoolCheckButton.
void GNEAdditionalFrame::AdditionalAttributeSingle::showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, std::string value)
show name and value of attribute of type string
Definition at line 628 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr, myAdditionalTag, myInvalidValue, myLabel, myTextFieldStrings, GNEAdditionalFrame::show(), and toString().
void GNEAdditionalFrame::AdditionalAttributeSingle::showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, int value)
show name and value of parameters of type int
Definition at line 642 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr, myAdditionalTag, myInvalidValue, myLabel, myTextFieldInt, GNEAdditionalFrame::show(), and toString().
void GNEAdditionalFrame::AdditionalAttributeSingle::showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, double value)
show name and value of parameters of type float/real/time
Definition at line 656 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr, myAdditionalTag, myInvalidValue, myLabel, myTextFieldReal, GNEAdditionalFrame::show(), and toString().
void GNEAdditionalFrame::AdditionalAttributeSingle::showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, bool value)
show name and value of parameters of type bool
Definition at line 670 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr, myAdditionalTag, myBoolCheckButton, myInvalidValue, myLabel, GNEAdditionalFrame::show(), and toString().
Field Documentation
SumoXMLAttr GNEAdditionalFrame::AdditionalAttributeSingle::myAdditionalAttr private
current XML attribute
Definition at line 122 of file GNEAdditionalFrame.h.
Referenced by getAttr(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
SumoXMLTag GNEAdditionalFrame::AdditionalAttributeSingle::myAdditionalTag private
current XML attribute
Definition at line 119 of file GNEAdditionalFrame.h.
Referenced by getTag(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
FXCheckButton* GNEAdditionalFrame::AdditionalAttributeSingle::myBoolCheckButton private
check button to enable/disable the value of boolean parameters
Definition at line 137 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), getValue(), hideParameter(), onCmdSetBooleanAttribute(), and showParameter().
std::string GNEAdditionalFrame::AdditionalAttributeSingle::myInvalidValue private
string which indicates the reason due current value is invalid
Definition at line 140 of file GNEAdditionalFrame.h.
Referenced by isAttributeValid(), onCmdSetAttribute(), and showParameter().
FXLabel* GNEAdditionalFrame::AdditionalAttributeSingle::myLabel private
lael with the name of the parameter
Definition at line 125 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), hideParameter(), and showParameter().
FXTextField* GNEAdditionalFrame::AdditionalAttributeSingle::myTextFieldInt private
textField to modify the default value of int/float/string parameters
Definition at line 128 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
FXTextField* GNEAdditionalFrame::AdditionalAttributeSingle::myTextFieldReal private
textField to modify the default value of real/times parameters
Definition at line 131 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
FXTextField* GNEAdditionalFrame::AdditionalAttributeSingle::myTextFieldStrings private
textField to modify the default value of string parameters
Definition at line 134 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp