SUMO - Simulation of Urban MObility: MSCFModel_PWag2009 Class Reference
MSCFModel_PWag2009 Class Reference
Scalable model based on Krauss by Peter Wagner.
#include <MSCFModel_PWag2009.h>
Data Structures
class VehicleVariables
Public Member Functions
virtual MSCFModel::VehicleVariables * createVehicleVariables () const
Returns model specific values which are stored inside a vehicle and must be used with casting.
MSCFModel * duplicate (const MSVehicleType *vtype) const
Duplicates the car-following model.
double estimateSpeedAfterDistance (const double dist, const double v, const double accel) const
double getMaxAccel () const
Get the vehicle type's maximum acceleration [m/s^2].
double getMaxDecel () const
Get the vehicle type's maximum deceleration [m/s^2].
double getMinimalArrivalSpeed (double dist, double currentSpeed) const
Computes the minimal possible arrival speed after covering a given distance.
double getMinimalArrivalSpeedEuler (double dist, double currentSpeed) const
Computes the minimal possible arrival speed after covering a given distance for Euler update.
SUMOTime getMinimalArrivalTime (double dist, double currentSpeed, double arrivalSpeed) const
Computes the minimal time needed to cover a distance given the desired speed at arrival.
double maximumSafeFollowSpeed (double gap, double egoSpeed, double predSpeed, double predMaxDecel, bool onInsertion=false) const
Returns the maximum safe velocity for following the given leader.
double maximumSafeStopSpeed (double gap, double currentSpeed, bool onInsertion=false, double headway=-1) const
Returns the maximum next velocity for stopping within gap.
double maximumSafeStopSpeedBallistic (double gap, double currentSpeed, bool onInsertion=false, double headway=-1) const
Returns the maximum next velocity for stopping within gap when using the ballistic positional update.
double maximumSafeStopSpeedEuler (double gap) const
Returns the maximum next velocity for stopping within gap when using the semi-implicit Euler update.
MSCFModel_PWag2009 (const MSVehicleType *vtype, double accel, double decel, double emergencyDecel, double dawdle, double headwayTime, double tauLast, double apProb)
Constructor.
~MSCFModel_PWag2009 ()
Destructor.
Implementations of the MSCFModel interface
double moveHelper (MSVehicle *const veh, double vPos) const
Applies interaction with stops and lane changing model influences.
double followSpeed (const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const
Computes the vehicle's safe speed (no dawdling)
double stopSpeed (const MSVehicle *const veh, const double speed, double gap2pred) const
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling)
int getModelID () const
Returns the model's name.
double getImperfection () const
Get the driver's imperfection.
Methods to override by model implementation
virtual double freeSpeed (const MSVehicle *const veh, double speed, double seen, double maxSpeed, const bool onInsertion=false) const
Computes the vehicle's safe speed without a leader.
virtual double insertionFollowSpeed (const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const
Computes the vehicle's safe speed (no dawdling) This method is used during the insertion stage. Whereas the method followSpeed returns the desired speed which may be lower than the safe speed, this method only considers safety constraints.
virtual double insertionStopSpeed (const MSVehicle *const veh, double speed, double gap) const
Computes the vehicle's safe speed for approaching an obstacle at insertion without constraints due to acceleration capabilities and previous speeds.
virtual double interactionGap (const MSVehicle *const veh, double vL) const
Returns the maximum gap at which an interaction between both vehicles occurs.
Virtual methods with default implementation
virtual double getHeadwayTime () const
Get the driver's reaction time [s].
Setter methods
virtual void setMaxAccel (double accel)
Sets a new value for maximum acceleration [m/s^2].
virtual void setMaxDecel (double decel)
Sets a new value for maximum deceleration [m/s^2].
virtual void setImperfection (double imperfection)
Sets a new value for driver imperfection.
virtual void setHeadwayTime (double headwayTime)
Sets a new value for driver reaction time [s].
Static Public Member Functions
static double gapExtrapolation (const double duration, const double currentGap, double v1, double v2, double a1=0, double a2=0, const double maxV1=std::numeric_limits< double >::max(), const double maxV2=std::numeric_limits< double >::max())
return the resulting gap if, starting with gap currentGap, two vehicles continue with constant accelerations (velocities bounded by 0 and maxSpeed) for a given timespan of length 'duration'.
static double passingTime (const double lastPos, const double passedPos, const double currentPos, const double lastSpeed, const double currentSpeed)
Calculates the time at which the position passedPosition has been passed In case of a ballistic update, the possibility of a stop within a time step requires more information about the last time-step than in case of the euler update to determine the last position if the currentSpeed is zero.
static double speedAfterTime (const double t, const double oldSpeed, const double dist)
Calculates the speed after a time t [0,TS] given the initial speed and the distance traveled in an interval of step length TS.
Protected Attributes
double myAccel
The vehicle's maximum acceleration [m/s^2].
double myApparentDecel
The vehicle's deceleration as expected by surrounding traffic [m/s^2].
double myDecel
The vehicle's maximum deceleration [m/s^2].
double myEmergencyDecel
The vehicle's maximum emergency deceleration [m/s^2].
double myHeadwayTime
The driver's desired time headway (aka reaction time tau) [s].
const MSVehicleType * myType
The type to which this model definition belongs to.
Private Member Functions
double _v (const MSVehicle *const veh, double speed, double gap, double predSpeed) const
Returns the next velocity.
double dawdle (double speed) const
Applies driver imperfection (dawdling / sigma)
Private Attributes
model parameter
The vehicle's dawdle-parameter. 0 for no dawdling, 1 for max.
double myDawdle
double myTauDecel
The precomputed value for myDecel*myTau.
double myDecelDivTau
The precomputed value for myDecel/myTau.
double myTauLastDecel
The precomputed value for (minimum headway time)*myDecel.
double myActionPointProbability
The probability for any action.
Currently fixed methods
virtual double maxNextSpeed (double speed, const MSVehicle *const veh) const
Returns the maximum speed given the current speed.
virtual double minNextSpeed (double speed, const MSVehicle *const veh=0) const
Returns the minimum speed given the current speed (depends on the numerical update scheme and its step width) Note that it wouldn't have to depend on the numerical update scheme if the semantics would rely on acceleration instead of velocity.
double brakeGap (const double speed) const
Returns the distance the vehicle needs to halt including driver's reaction time, assuming that during the reaction time, the speed remains constant.
double getSecureGap (const double speed, const double leaderSpeed, const double leaderMaxDecel) const
Returns the minimum gap to reserve if the leader is braking at maximum (>=0)
virtual double getSpeedAfterMaxDecel (double v) const
Returns the velocity after maximum deceleration.
static double freeSpeed (const double currentSpeed, const double decel, const double dist, const double maxSpeed, const bool onInsertion)
static double brakeGap (const double speed, const double decel, const double headwayTime)
Detailed Description
Scalable model based on Krauss by Peter Wagner.
See also
MSCFModel
Definition at line 45 of file MSCFModel_PWag2009.h.
Constructor & Destructor Documentation
MSCFModel_PWag2009::MSCFModel_PWag2009 (const MSVehicleType * vtype, double accel, double decel, double emergencyDecel, double dawdle, double headwayTime, double tauLast, double apProb)
Constructor.
Parameters
[in] accel The maximum acceleration
[in] decel The maximum deceleration
[in] emergencyDecel The maximum emergency deceleration
[in] dawdle The driver imperfection
[in] tau The driver's reaction time
Definition at line 43 of file MSCFModel_PWag2009.cpp.
Referenced by duplicate().
MSCFModel_PWag2009::~MSCFModel_PWag2009 ()
Destructor.
Definition at line 54 of file MSCFModel_PWag2009.cpp.
Member Function Documentation
double MSCFModel_PWag2009::_v (const MSVehicle *const veh, double speed, double gap, double predSpeed) const private
Returns the next velocity.
Parameters
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The LEADER's speed
Returns
the safe velocity
double MSCFModel::brakeGap (const double speed) const inline inherited
Returns the distance the vehicle needs to halt including driver's reaction time, assuming that during the reaction time, the speed remains constant.
Parameters
[in] speed The vehicle's current speed
Returns
The distance needed to halt
Definition at line 263 of file MSCFModel.h.
References MSCFModel::freeSpeed(), MSCFModel::myDecel, and MSCFModel::myHeadwayTime.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), MSLane::getCriticalLeader(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLaneChanger::getRealLeader(), MSVehicle::getRerouteOrigin(), MSCFModel::getSecureGap(), MSLane::handleCollisionBetween(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSCFModel::maximumSafeFollowSpeed(), MSVehicle::planMoveInternal(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), and MSVehicle::unsafeLinkAhead().
double MSCFModel::brakeGap (const double speed, const double decel, const double headwayTime) static inherited
Definition at line 66 of file MSCFModel.cpp.
References ACCEL2SPEED, MSGlobals::gSemiImplicitEulerUpdate, and SPEED2DIST.
virtual MSCFModel::VehicleVariables* MSCFModel_PWag2009::createVehicleVariables () const inline virtual
Returns model specific values which are stored inside a vehicle and must be used with casting.
Reimplemented from MSCFModel.
Definition at line 121 of file MSCFModel_PWag2009.h.
References MSCFModel_PWag2009::VehicleVariables::aOld.
double MSCFModel_PWag2009::dawdle (double speed) const private
Applies driver imperfection (dawdling / sigma)
Parameters
[in] speed The speed with no dawdling
Returns
The speed after dawdling
Definition at line 113 of file MSCFModel_PWag2009.cpp.
MSCFModel * MSCFModel_PWag2009::duplicate (const MSVehicleType * vtype) const virtual
Duplicates the car-following model.
Parameters
[in] vtype The vehicle type this model belongs to (1:1)
Returns
A duplicate of this car-following model
Implements MSCFModel.
Definition at line 143 of file MSCFModel_PWag2009.cpp.
References MSCFModel_PWag2009(), MSCFModel::myAccel, myActionPointProbability, myDawdle, MSCFModel::myDecel, MSCFModel::myEmergencyDecel, MSCFModel::myHeadwayTime, and myTauLastDecel.
Referenced by getImperfection().
double MSCFModel::estimateSpeedAfterDistance (const double dist, const double v, const double accel) const inherited
Definition at line 473 of file MSCFModel.cpp.
References MSVehicleType::getMaxSpeed(), MAX2(), MIN2(), and MSCFModel::myType.
Referenced by MSVehicle::estimateLeaveSpeed(), MSCFModel::getMinimalArrivalSpeed(), MSCFModel::getMinimalArrivalSpeedEuler(), MSCFModel::getSpeedAfterMaxDecel(), and MSVehicle::planMoveInternal().
double MSCFModel_PWag2009::followSpeed (const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const virtual
Computes the vehicle's safe speed (no dawdling)
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
Returns
EGO's safe speed
See also
MSCFModel::ffeV
Implements MSCFModel.
Definition at line 72 of file MSCFModel_PWag2009.cpp.
References ACCEL2SPEED, MSCFModel_PWag2009::VehicleVariables::aOld, MSVehicle::getCarFollowVariables(), MAX2(), MIN2(), MSCFModel::myAccel, myActionPointProbability, myDawdle, MSCFModel::myDecel, myDecelDivTau, MSCFModel::myHeadwayTime, myTauDecel, myTauLastDecel, RandHelper::rand(), SPEED2ACCEL, and TS.
double MSCFModel::freeSpeed (const MSVehicle *const veh, double speed, double seen, double maxSpeed, const bool onInsertion = false) const virtual inherited
Computes the vehicle's safe speed without a leader.
Returns the velocity of the vehicle in dependence to the length of the free street and the target velocity at the end of the free range. If onInsertion is true, the vehicle may still brake before the next movement.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] seen The look ahead distance
[in] maxSpeed The maximum allowed speed
[in] onInsertion whether speed at insertion is asked for
Returns
EGO's safe speed
Reimplemented in MSCFModel_Rail.
Definition at line 211 of file MSCFModel.cpp.
References MSCFModel::myDecel.
Referenced by MSCFModel::brakeGap(), MSLane::isInsertionSuccess(), and MSVehicle::planMoveInternal().
double MSCFModel::freeSpeed (const double currentSpeed, const double decel, const double dist, const double maxSpeed, const bool onInsertion) static inherited
Definition at line 85 of file MSCFModel.cpp.
References ACCEL2DIST, ACCEL2SPEED, DIST2SPEED, MSGlobals::gSemiImplicitEulerUpdate, MAX2(), NUMERICAL_EPS, SPEED2DIST, and TS.
double MSCFModel::gapExtrapolation (const double duration, const double currentGap, double v1, double v2, double a1 = 0, double a2 = 0, const double maxV1 = std::numeric_limits<double>::max(), const double maxV2 = std::numeric_limits<double>::max()) static inherited
return the resulting gap if, starting with gap currentGap, two vehicles continue with constant accelerations (velocities bounded by 0 and maxSpeed) for a given timespan of length 'duration'.
Parameters
[in] currentGap (pos(veh1) - pos(veh2) at start)
[in] v1 initial speed of vehicle 1
[in] v2 initial speed of vehicle 2
[in] a1 acceleration of vehicle 1
[in] a2 acceleration of vehicle 2
[in] maxV1 maximal speed of vehicle 1
[in] maxV2 maximal speed of vehicle 2
[in] duration time span for the process
Returns
estimated gap after 'duration' seconds
Definition at line 278 of file MSCFModel.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, MAX2(), MIN2(), and TS.
Referenced by MSCFModel::getSpeedAfterMaxDecel(), and MSLCM_LC2013::informFollower().
virtual double MSCFModel::getHeadwayTime () const inline virtual inherited
Get the driver's reaction time [s].
Returns
The reaction time of this class' drivers in s
Definition at line 220 of file MSCFModel.h.
References MSCFModel::maxNextSpeed(), MSCFModel::minNextSpeed(), and MSCFModel::myHeadwayTime.
Referenced by MSLCM_SL2015::checkBlockingVehicles(), MSVehicle::checkRewindLinkLanes(), MSCFModel::getMinimalArrivalSpeed(), MSCFModel::getMinimalArrivalSpeedEuler(), TraCI_VehicleType::getTau(), and MSCalibrator::remainingVehicleCapacity().
double MSCFModel_PWag2009::getImperfection () const inline virtual
Get the driver's imperfection.
Returns
The imperfection of drivers of this class
Reimplemented from MSCFModel.
Definition at line 107 of file MSCFModel_PWag2009.h.
References duplicate(), and myDawdle.
double MSCFModel::getMaxAccel () const inline inherited
Get the vehicle type's maximum acceleration [m/s^2].
Returns
The maximum acceleration (in m/s^2) of vehicles of this class
Definition at line 193 of file MSCFModel.h.
References MSCFModel::myAccel.
Referenced by MSLCM_LC2013::_wantsChange(), MSLaneChanger::computeOvertakingTime(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), TraCI_VehicleType::getAccel(), MSCFModel::getMinimalArrivalTime(), MSLCM_LC2013::informFollower(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::maxNextSpeed(), MSVehicle::planMoveInternal(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
double MSCFModel::getMaxDecel () const inline inherited
Get the vehicle type's maximum deceleration [m/s^2].
Returns
The maximum deceleration (in m/s^2) of vehicles of this class
Definition at line 201 of file MSCFModel.h.
References MSCFModel::myDecel.
Referenced by MSLCM_LC2013::_wantsChange(), MSCriticalFollowerDistanceInfo::addFollower(), MSLink::blockedByFoe(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), MSVehicle::executeMove(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), TraCI_VehicleType::getDecel(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSCFModel::getMinimalArrivalSpeed(), MSCFModel::getMinimalArrivalSpeedEuler(), MSCFModel::getMinimalArrivalTime(), MSLane::getMissingRearGap(), MSLink::getZipperSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSCFModel_KraussOrig1::moveHelper(), MSLCM_LC2013::overtakeDistance(), MSVehicle::planMoveInternal(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSVehicleControl::vehicleDeparted(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
double MSCFModel::getMinimalArrivalSpeed (double dist, double currentSpeed) const inherited
Computes the minimal possible arrival speed after covering a given distance.
Parameters
[in] dist Distance to be covered
[in] currentSpeed Actual speed of vehicle
Definition at line 252 of file MSCFModel.cpp.
References MSCFModel::estimateSpeedAfterDistance(), MSCFModel::getHeadwayTime(), and MSCFModel::getMaxDecel().
Referenced by MSCFModel::getSpeedAfterMaxDecel(), and MSVehicle::planMoveInternal().
double MSCFModel::getMinimalArrivalSpeedEuler (double dist, double currentSpeed) const inherited
Computes the minimal possible arrival speed after covering a given distance for Euler update.
Parameters
[in] dist Distance to be covered
[in] currentSpeed Actual speed of vehicle
Definition at line 259 of file MSCFModel.cpp.
References MSCFModel::estimateSpeedAfterDistance(), MSCFModel::getHeadwayTime(), MSCFModel::getMaxDecel(), and INVALID_SPEED.
Referenced by MSCFModel::getSpeedAfterMaxDecel(), and MSVehicle::planMoveInternal().
SUMOTime MSCFModel::getMinimalArrivalTime (double dist, double currentSpeed, double arrivalSpeed) const inherited
Computes the minimal time needed to cover a distance given the desired speed at arrival.
Parameters
[in] dist Distance to be covered
[in] currentSpeed Actual speed of vehicle
[in] arrivalSpeed Desired speed at arrival
Definition at line 239 of file MSCFModel.cpp.
References MSCFModel::getMaxAccel(), MSCFModel::getMaxDecel(), MAX2(), MAX3(), SUMO_const_haltingSpeed, and TIME2STEPS.
Referenced by MSCFModel::getSpeedAfterMaxDecel(), and MSVehicle::planMoveInternal().
int MSCFModel_PWag2009::getModelID () const inline virtual
Returns the model's name.
Returns
The model's name
See also
MSCFModel::getModelName
Implements MSCFModel.
Definition at line 99 of file MSCFModel_PWag2009.h.
References SUMO_TAG_CF_PWAGNER2009.
double MSCFModel::getSecureGap (const double speed, const double leaderSpeed, const double leaderMaxDecel) const inline inherited
Returns the minimum gap to reserve if the leader is braking at maximum (>=0)
Parameters
[in] speed EGO's speed
[in] leaderSpeed LEADER's speed
[in] leaderMaxDecel LEADER's max. deceleration rate
Definition at line 276 of file MSCFModel.h.
References MSCFModel::brakeGap(), MAX2(), MIN2(), MSCFModel::myDecel, and MSCFModel::myHeadwayTime.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLaneChanger::computeOvertakingTime(), MSLane::freeInsertion(), MSLane::getMissingRearGap(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), and MSLCM_LC2013::overtakeDistance().
virtual double MSCFModel::getSpeedAfterMaxDecel (double v) const inline virtual inherited
Returns the velocity after maximum deceleration.
Parameters
[in] v The velocity
Returns
The velocity after maximum deceleration
Reimplemented in MSCFModel_Rail.
Definition at line 302 of file MSCFModel.h.
References ACCEL2SPEED, MSCFModel::estimateSpeedAfterDistance(), MSCFModel::gapExtrapolation(), MSCFModel::getMinimalArrivalSpeed(), MSCFModel::getMinimalArrivalSpeedEuler(), MSCFModel::getMinimalArrivalTime(), max, MAX2(), MSCFModel::myDecel, MSCFModel::passingTime(), and MSCFModel::speedAfterTime().
Referenced by MSCFModel_SmartSK::followSpeed(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel::moveHelper(), MSVehicle::planMoveInternal(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_Wiedemann::stopSpeed().
double MSCFModel::insertionFollowSpeed (const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const virtual inherited
Computes the vehicle's safe speed (no dawdling) This method is used during the insertion stage. Whereas the method followSpeed returns the desired speed which may be lower than the safe speed, this method only considers safety constraints.
Returns the velocity of the vehicle in dependence to the vehicle's and its leader's values and the distance between them.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
Returns
EGO's safe speed
Reimplemented in MSCFModel_KraussOrig1.
Definition at line 218 of file MSCFModel.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, and MSCFModel::maximumSafeFollowSpeed().
Referenced by MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::isInsertionSuccess(), and MSLane::safeInsertionSpeed().
double MSCFModel::insertionStopSpeed (const MSVehicle *const veh, double speed, double gap) const virtual inherited
Computes the vehicle's safe speed for approaching an obstacle at insertion without constraints due to acceleration capabilities and previous speeds.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap The (netto) distance to the the obstacle
Returns
EGO's safe speed for approaching a non-moving obstacle at insertion
See also
stopSpeed() and insertionFollowSpeed()
Definition at line 229 of file MSCFModel.cpp.
References MSVehicleType::getMaxSpeed(), MSGlobals::gSemiImplicitEulerUpdate, MSCFModel::maximumSafeStopSpeed(), MIN2(), MSCFModel::myType, and MSCFModel::stopSpeed().
Referenced by MSLane::isInsertionSuccess().
double MSCFModel::interactionGap (const MSVehicle *const veh, double vL) const virtual inherited
Returns the maximum gap at which an interaction between both vehicles occurs.
"interaction" means that the LEADER influences EGO's speed.
Parameters
[in] veh The EGO vehicle
[in] vL LEADER's speed
Returns
The interaction gap
Todo:
evaluate signature
Reimplemented in MSCFModel_IDM, and MSCFModel_Wiedemann.
Definition at line 178 of file MSCFModel.cpp.
References MSVehicle::getLane(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MAX2(), MSCFModel::maxNextSpeed(), MIN2(), MSCFModel::myDecel, MSCFModel::myHeadwayTime, and SPEED2DIST.
Referenced by MSAbstractLaneChangeModel::predInteraction().
double MSCFModel::maximumSafeFollowSpeed (double gap, double egoSpeed, double predSpeed, double predMaxDecel, bool onInsertion = false) const inherited
Returns the maximum safe velocity for following the given leader.
Parameters
[in] gap2pred The (netto) distance to the LEADER
[in] egoSpeed The FOLLOWERS's speed
[in] predSpeed The LEADER's speed
[in] predMaxDecel The LEADER's maximum deceleration
[in] onInsertion Indicator whether the call is triggered during vehicle insertion
Returns
the safe velocity
Returns the SK-vsafe.
Definition at line 590 of file MSCFModel.cpp.
References MSCFModel::brakeGap(), MSGlobals::gSemiImplicitEulerUpdate, ISNAN(), MAX2(), MSCFModel::maximumSafeStopSpeed(), MSCFModel::myDecel, and MSCFModel::myHeadwayTime.
Referenced by MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel_KraussOrig1::insertionFollowSpeed(), MSCFModel::insertionFollowSpeed(), and MSCFModel::setHeadwayTime().
double MSCFModel::maximumSafeStopSpeed (double gap, double currentSpeed, bool onInsertion = false, double headway = -1) const inherited
Returns the maximum next velocity for stopping within gap.
Parameters
[in] gap The (netto) distance to the desired stopping point
[in] currentSpeed The current speed of the ego vehicle
[in] onInsertion Indicator whether the call is triggered during vehicle insertion
[in] headway The desired time headway to be included in the calculations (default argument -1 induces the use of myHeadway)
Definition at line 482 of file MSCFModel.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, MSCFModel::maximumSafeStopSpeedBallistic(), and MSCFModel::maximumSafeStopSpeedEuler().
Referenced by MSCFModel::insertionStopSpeed(), MSCFModel::maximumSafeFollowSpeed(), MSVehicle::planMoveInternal(), MSCFModel::setHeadwayTime(), MSCFModel_Krauss::stopSpeed(), and MSCFModel_Rail::stopSpeed().
double MSCFModel::maximumSafeStopSpeedBallistic (double gap, double currentSpeed, bool onInsertion = false, double headway = -1) const inherited
Returns the maximum next velocity for stopping within gap when using the ballistic positional update.
Note
This takes into account the driver's reaction time and the car's current speed. (The latter is required to calculate the distance covered in the following timestep.)
Parameters
[in] gap The (netto) distance to the desired stopping point
[in] currentSpeed The current speed of the ego vehicle
[in] onInsertion Indicator whether the call is triggered during vehicle insertion
[in] headway The desired time headway to be included in the calculations (default argument -1 induces the use of myHeadway)
Returns
the safe velocity (to be attained at the end of the following time step) that assures the possibility of stopping within gap. If a negative value is returned, the required stop has to take place before the end of the time step.
Definition at line 523 of file MSCFModel.cpp.
References INVALID_SPEED, MAX2(), MSCFModel::myDecel, MSCFModel::myHeadwayTime, NUMERICAL_EPS, and TS.
Referenced by MSCFModel::maximumSafeStopSpeed(), MSCFModel::setHeadwayTime(), and MSCFModel_KraussOrig1::stopSpeed().
double MSCFModel::maximumSafeStopSpeedEuler (double gap) const inherited
Returns the maximum next velocity for stopping within gap when using the semi-implicit Euler update.
Parameters
[in] gap The (netto) distance to the LEADER
Definition at line 492 of file MSCFModel.cpp.
References ACCEL2SPEED, DIST2SPEED, MIN2(), MSCFModel::myDecel, MSCFModel::myHeadwayTime, NUMERICAL_EPS, and TS.
Referenced by MSCFModel::maximumSafeStopSpeed(), and MSCFModel::setHeadwayTime().
double MSCFModel::maxNextSpeed (double speed, const MSVehicle *const veh) const virtual inherited
Returns the maximum speed given the current speed.
The implementation of this method must take into account the time step duration.
Justification: Due to air brake or other influences, the vehicle's next maximum speed may depend on the vehicle's current speed (given).
Parameters
[in] speed The vehicle's current speed
[in] speed The vehicle itself, for obtaining other values
Returns
The maximum possible speed for the next step
Reimplemented in MSCFModel_KraussPS, and MSCFModel_Rail.
Definition at line 193 of file MSCFModel.cpp.
References ACCEL2SPEED, MSCFModel::getMaxAccel(), MSVehicleType::getMaxSpeed(), MIN2(), and MSCFModel::myType.
Referenced by MSVehicle::executeMove(), MSCFModel_Kerner::followSpeed(), MSCFModel_Daniel1::followSpeed(), MSCFModel_SmartSK::followSpeed(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel::getHeadwayTime(), MSCFModel::interactionGap(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel::moveHelper(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSCFModel_Krauss::stopSpeed(), MSCFModel_Kerner::stopSpeed(), MSCFModel_Daniel1::stopSpeed(), MSCFModel_SmartSK::stopSpeed(), MSCFModel_KraussOrig1::stopSpeed(), and MSCFModel_Wiedemann::stopSpeed().
double MSCFModel::minNextSpeed (double speed, const MSVehicle *const veh = 0) const virtual inherited
Returns the minimum speed given the current speed (depends on the numerical update scheme and its step width) Note that it wouldn't have to depend on the numerical update scheme if the semantics would rely on acceleration instead of velocity.
Parameters
[in] speed The vehicle's current speed
[in] speed The vehicle itself, for obtaining other values, if needed as e.g. road conditions.
Returns
The minimum possible speed for the next step
Reimplemented in MSCFModel_Rail.
Definition at line 198 of file MSCFModel.cpp.
References ACCEL2SPEED, MSGlobals::gSemiImplicitEulerUpdate, MAX2(), and MSCFModel::myEmergencyDecel.
Referenced by MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel::getHeadwayTime(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), and MSCFModel::moveHelper().
double MSCFModel_PWag2009::moveHelper (MSVehicle *const veh, double vPos) const virtual
Applies interaction with stops and lane changing model influences.
Parameters
[in] veh The ego vehicle
[in] vPos The possible velocity
Returns
The velocity after applying interactions with stops and lane change model influences
Reimplemented from MSCFModel.
Definition at line 58 of file MSCFModel_PWag2009.cpp.
References MSCFModel_PWag2009::VehicleVariables::aOld, MSVehicle::getCarFollowVariables(), MSVehicle::getSpeed(), MSCFModel::moveHelper(), and SPEED2ACCEL.
double MSCFModel::passingTime (const double lastPos, const double passedPos, const double currentPos, const double lastSpeed, const double currentSpeed) static inherited
Calculates the time at which the position passedPosition has been passed In case of a ballistic update, the possibility of a stop within a time step requires more information about the last time-step than in case of the euler update to determine the last position if the currentSpeed is zero.
Parameters
[in] lastPos the position at time t=0 (must be < currentPos)
[in] passedPos the position for which the passing time is to be determined (has to lie within [lastPos, currentPos]!)
[in] currentPos the position at time t=TS (one time-step after lastPos) (must be > lastPos)
[in] lastSpeed the speed at moment t=0
[in] currentSpeed the speed at moment t=TS
Returns
time t in [0,TS] at which passedPos in [lastPos, currentPos] was passed.
Definition at line 372 of file MSCFModel.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, MAX2(), MIN2(), NUMERICAL_EPS, SPEED2ACCEL, TS, and WRITE_ERROR.
Referenced by MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSCFModel::getSpeedAfterMaxDecel(), MSE3Collector::MSE3EntryReminder::notifyMove(), MSInstantInductLoop::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSInductLoop::notifyMove(), and MSE3Collector::MSE3LeaveReminder::notifyMove().
virtual void MSCFModel::setHeadwayTime (double headwayTime) inline virtual inherited
Sets a new value for driver reaction time [s].
Parameters
[in] headwayTime The new driver reaction time (in s)
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 415 of file MSCFModel.h.
References MSCFModel::maximumSafeFollowSpeed(), MSCFModel::maximumSafeStopSpeed(), MSCFModel::maximumSafeStopSpeedBallistic(), MSCFModel::maximumSafeStopSpeedEuler(), and MSCFModel::myHeadwayTime.
Referenced by TraCI_VehicleType::setTau().
virtual void MSCFModel::setImperfection (double imperfection) inline virtual inherited
Sets a new value for driver imperfection.
Parameters
[in] accel The new driver imperfection
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 407 of file MSCFModel.h.
References UNUSED_PARAMETER.
Referenced by TraCI_VehicleType::setImperfection().
virtual void MSCFModel::setMaxAccel (double accel) inline virtual inherited
Sets a new value for maximum acceleration [m/s^2].
Parameters
[in] accel The new acceleration in m/s^2
Definition at line 391 of file MSCFModel.h.
References MSCFModel::myAccel.
Referenced by TraCI_VehicleType::setAccel().
virtual void MSCFModel::setMaxDecel (double decel) inline virtual inherited
Sets a new value for maximum deceleration [m/s^2].
Parameters
[in] accel The new deceleration in m/s^2
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 399 of file MSCFModel.h.
References MSCFModel::myDecel.
Referenced by MSCFModel_Rail::MSCFModel_Rail(), and TraCI_VehicleType::setDecel().
double MSCFModel::speedAfterTime (const double t, const double oldSpeed, const double dist) static inherited
Calculates the speed after a time t [0,TS] given the initial speed and the distance traveled in an interval of step length TS.
Note
If the acceleration were known, this would be much nicer, but in this way we need to reconstruct it (for the ballistic update at least, where we assume that a stop may occur within the interval)
Parameters
[in] t time in [0,TS] for which the speed shall be determined
[in] oldSpeed speed before the last time step (referred to as t == 0)
[in] distance covered
Returns
speed at time t
Definition at line 444 of file MSCFModel.cpp.
References DIST2SPEED, MSGlobals::gSemiImplicitEulerUpdate, and TS.
Referenced by MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSCFModel::getSpeedAfterMaxDecel(), MSInstantInductLoop::notifyMove(), and MSMeanData::MeanDataValues::notifyMove().
double MSCFModel_PWag2009::stopSpeed (const MSVehicle *const veh, const double speed, double gap2pred) const virtual
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling)
Parameters
[in] veh The vehicle (EGO)
[in] gap2pred The (netto) distance to the the obstacle
Returns
EGO's safe speed for approaching a non-moving obstacle
See also
MSCFModel::ffeS
Todo:
generic Interface, models can call for the values they need
Implements MSCFModel.
Definition at line 94 of file MSCFModel_PWag2009.cpp.
References ACCEL2SPEED, MAX2(), MIN2(), MSCFModel::myAccel, MSCFModel::myDecel, myDecelDivTau, MSCFModel::myHeadwayTime, myTauDecel, and SPEED2ACCEL.
Field Documentation
double MSCFModel::myAccel protected inherited
The vehicle's maximum acceleration [m/s^2].
Definition at line 466 of file MSCFModel.h.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel_Krauss::dawdle(), MSCFModel_Daniel1::dawdle(), MSCFModel_SmartSK::dawdle(), MSCFModel_KraussOrig1::dawdle(), MSCFModel_KraussX::dawdleX(), MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), duplicate(), MSCFModel_Wiedemann::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), followSpeed(), MSCFModel_Wiedemann::fullspeed(), MSCFModel::getMaxAccel(), MSCFModel_IDM::interactionGap(), MSCFModel_SmartSK::MSCFModel_SmartSK(), MSCFModel::setMaxAccel(), and stopSpeed().
double MSCFModel_PWag2009::myActionPointProbability private
The probability for any action.
Definition at line 164 of file MSCFModel_PWag2009.h.
Referenced by duplicate(), and followSpeed().
double MSCFModel::myApparentDecel protected inherited
The vehicle's deceleration as expected by surrounding traffic [m/s^2].
Definition at line 473 of file MSCFModel.h.
Referenced by MSCFModel_KraussX::duplicate(), MSCFModel_Krauss::duplicate(), and MSCFModel_KraussOrig1::duplicate().
double MSCFModel_PWag2009::myDawdle private
Definition at line 152 of file MSCFModel_PWag2009.h.
Referenced by duplicate(), followSpeed(), and getImperfection().
double MSCFModel::myDecel protected inherited
The vehicle's maximum deceleration [m/s^2].
Definition at line 469 of file MSCFModel.h.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_Daniel1::_vsafe(), MSCFModel_SmartSK::_vsafe(), MSCFModel::brakeGap(), MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), duplicate(), MSCFModel_Wiedemann::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_Wiedemann::emergency(), followSpeed(), MSCFModel_Rail::freeSpeed(), MSCFModel::freeSpeed(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSCFModel::getSpeedAfterMaxDecel(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), MSCFModel::maximumSafeFollowSpeed(), MSCFModel::maximumSafeStopSpeedBallistic(), MSCFModel::maximumSafeStopSpeedEuler(), MSCFModel_SmartSK::MSCFModel_SmartSK(), MSCFModel_Daniel1::setHeadwayTime(), MSCFModel_SmartSK::setHeadwayTime(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel_Daniel1::setMaxDecel(), MSCFModel_SmartSK::setMaxDecel(), MSCFModel_KraussOrig1::setMaxDecel(), MSCFModel::setMaxDecel(), stopSpeed(), and MSCFModel_KraussOrig1::vsafe().
double MSCFModel_PWag2009::myDecelDivTau private
The precomputed value for myDecel/myTau.
Definition at line 158 of file MSCFModel_PWag2009.h.
Referenced by followSpeed(), and stopSpeed().
double MSCFModel::myEmergencyDecel protected inherited
The vehicle's maximum emergency deceleration [m/s^2].
Definition at line 471 of file MSCFModel.h.
Referenced by MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), duplicate(), MSCFModel_Wiedemann::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), and MSCFModel::minNextSpeed().
double MSCFModel::myHeadwayTime protected inherited
The driver's desired time headway (aka reaction time tau) [s].
Definition at line 476 of file MSCFModel.h.
Referenced by MSCFModel_IDM::_v(), MSCFModel::brakeGap(), MSCFModel_SmartSK::createVehicleVariables(), MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), followSpeed(), MSCFModel::getHeadwayTime(), MSCFModel::getSecureGap(), MSCFModel::interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), MSCFModel::maximumSafeFollowSpeed(), MSCFModel::maximumSafeStopSpeedBallistic(), MSCFModel::maximumSafeStopSpeedEuler(), MSCFModel_Daniel1::setHeadwayTime(), MSCFModel_SmartSK::setHeadwayTime(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel::setHeadwayTime(), MSCFModel_Daniel1::setMaxDecel(), MSCFModel_SmartSK::setMaxDecel(), MSCFModel_KraussOrig1::setMaxDecel(), stopSpeed(), and MSCFModel_SmartSK::updateMyHeadway().
double MSCFModel_PWag2009::myTauDecel private
The precomputed value for myDecel*myTau.
Definition at line 155 of file MSCFModel_PWag2009.h.
Referenced by followSpeed(), and stopSpeed().
double MSCFModel_PWag2009::myTauLastDecel private
The precomputed value for (minimum headway time)*myDecel.
Definition at line 161 of file MSCFModel_PWag2009.h.
Referenced by duplicate(), and followSpeed().
const MSVehicleType* MSCFModel::myType protected inherited
The type to which this model definition belongs to.
Definition at line 463 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel::estimateSpeedAfterDistance(), MSCFModel::insertionStopSpeed(), MSCFModel_KraussPS::maxNextSpeed(), and MSCFModel::maxNextSpeed().
The documentation for this class was generated from the following files:
MSCFModel_PWag2009.h
MSCFModel_PWag2009.cpp