SUMO - Simulation of Urban MObility: LayeredRTree Class Reference
LayeredRTree Class Reference
A RT-tree for efficient storing of SUMO's GL-objects in layers.
#include <LayeredRTree.h>
Public Member Functions
void add (double x, double y, double z=0)
Makes the boundary include the given coordinate.
void add (const Position &p)
Makes the boundary include the given coordinate.
void add (const Boundary &p)
Makes the boundary include the given boundary.
void addAdditionalGLObject (GUIGlObject *o)
Adds an additional object (detector/shape/trigger) for visualisation.
bool around (const Position &p, double offset=0) const
Returns whether the boundary contains the given coordinate.
bool crosses (const Position &p1, const Position &p2) const
Returns whether the boundary crosses the given line.
void flipY ()
flips ymin and ymax
Position getCenter () const
Returns the center of the boundary.
double getHeight () const
Returns the height of the boundary (y-axis)
double getWidth () const
Returns the width of the boudary (x-axis)
double getZRange () const
Returns the elevation range of the boundary (z-axis)
Boundary & grow (double by)
extends the boundary by the given amount
void growHeight (double by)
Increases the height of the boundary (y-axis)
void growWidth (double by)
Increases the width of the boundary (x-axis)
void Insert (const float a_min[2], const float a_max[2], GUIGlObject *const &a_dataId)
Insert entry (delegate to appropriate layer)
LayeredRTree ()
Constructor.
void moveby (double x, double y, double z=0)
Moves the boundary by the given amount.
bool overlapsWith (const AbstractPoly &poly, double offset=0) const
Returns whether the boundary overlaps with the given polygon.
bool partialWithin (const AbstractPoly &poly, double offset=0) const
Returns whether the boundary is partially within the given polygon.
void Remove (const float a_min[2], const float a_max[2], GUIGlObject *const &a_dataId)
Remove entry (delegate to appropriate layer)
void removeAdditionalGLObject (GUIGlObject *o)
Removes an additional object (detector/shape/trigger) from being visualised.
void reset ()
Resets the boundary.
int Search (const float a_min[2], const float a_max[2], const GUIVisualizationSettings &c) const
Find all within search rectangle (searches all layers in order)
void set (double xmin, double ymin, double xmax, double ymax)
Sets the boundary to the given values.
double xmax () const
Returns maximum x-coordinate.
double xmin () const
Returns minimum x-coordinate.
double ymax () const
Returns maximum y-coordinate.
double ymin () const
Returns minimum y-coordinate.
double zmax () const
Returns maximum z-coordinate.
double zmin () const
Returns minimum z-coordinate.
~LayeredRTree ()
Destructor.
Protected Attributes
std::vector< SUMORTree * > myLayers
the layers for drawing
MFXMutex myLock
A mutex avoiding parallel change and traversal of the tree.
Private Member Functions
size_t selectLayer (GUIGlObject *o)
select the appropriate layer for each object
Detailed Description
A RT-tree for efficient storing of SUMO's GL-objects in layers.
This class maintains SUMORTrees for each layer (only 2 at the moment) but provides the same interface as SUMORTree
Definition at line 56 of file LayeredRTree.h.
Constructor & Destructor Documentation
LayeredRTree::LayeredRTree () inline
Constructor.
Definition at line 59 of file LayeredRTree.h.
References myLayers, and SUMORTree::SUMORTree().
LayeredRTree::~LayeredRTree () inline
Destructor.
Definition at line 66 of file LayeredRTree.h.
References myLayers.
Member Function Documentation
void Boundary::add (double x, double y, double z = 0) inherited
Makes the boundary include the given coordinate.
Definition at line 86 of file Boundary.cpp.
References Boundary::myWasInitialised, Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, and Boundary::myZmin.
Referenced by Boundary::add(), NIVissimConnectionCluster::NodeSubCluster::add(), NIVissimConnectionCluster::add(), Boundary::Boundary(), GUIDanielPerspectiveChanger::centerTo(), NBNetBuilder::compute(), GNENet::computeAndUpdate(), NIVissimDisturbance::computeBounding(), NIVissimConnection::computeBounding(), NBNetBuilder::computeSingleNode(), GNEEdge::getBoundary(), GUIEdge::getBoundary(), PositionVector::getBoxBoundary(), MSDevice_BTsender::VehicleInformation::getBoxBoundary(), GUITrafficLightLogicWrapper::getCenteringBoundary(), GUIContainer::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GUIPointOfInterest::getCenteringBoundary(), GUIPerson::getCenteringBoundary(), GUIBaseVehicle::getCenteringBoundary(), GUILane::getCenteringBoundary(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GNENet::GNENet(), GUICalibrator::GUICalibrator(), GUILaneSpeedTrigger::GUILaneSpeedTrigger(), GUITriggeredRerouter::GUITriggeredRerouter(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), GUINet::initGUIStructures(), NBHeightMapper::loadShapeFile(), NBHeightMapper::loadTiff(), GNEViewNet::mergeJunctions(), GUITriggeredRerouter::myEndElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIE3Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GNEViewNet::onLeftBtnRelease(), NIVissimConnectionCluster::recomputeBoundary(), GNENet::registerEdge(), GNENet::registerJunction(), GUIDanielPerspectiveChanger::setViewport(), GNEJunction::updateGeometry(), and GeoConvHelper::x2cartesian().
void Boundary::add (const Position & p) inherited
Makes the boundary include the given coordinate.
Definition at line 107 of file Boundary.cpp.
References Boundary::add(), Position::x(), Position::y(), and Position::z().
void Boundary::add (const Boundary & p) inherited
Makes the boundary include the given boundary.
Definition at line 113 of file Boundary.cpp.
References Boundary::add(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), Boundary::ymin(), Boundary::zmax(), and Boundary::zmin().
void SUMORTree::addAdditionalGLObject (GUIGlObject * o) inline inherited
Adds an additional object (detector/shape/trigger) for visualisation.
Parameters
[in] o The object to add
Definition at line 129 of file SUMORTree.h.
References GUIGlObject::getCenteringBoundary(), SUMORTree::Insert(), SUMORTree::myLock, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIShapeContainer::addPOI(), GUIShapeContainer::addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), GUINet::createTLWrapper(), GUITriggeredRerouter::GUITriggeredRerouter(), GUINet::initGUIStructures(), GNENet::insertAdditional(), GUIShapeContainer::movePOI(), GNEViewNet::onCmdNodeShape(), GNENet::refreshAdditional(), GNENet::refreshElement(), GNENet::registerEdge(), GNENet::registerJunction(), and GUIShapeContainer::reshapePolygon().
bool Boundary::around (const Position & p, double offset = 0) const virtual inherited
Returns whether the boundary contains the given coordinate.
Implements AbstractPoly.
Definition at line 180 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, Boundary::myZmin, Position::x(), Position::y(), and Position::z().
Referenced by PCPolyContainer::add(), NIVissimConnectionCluster::around(), NBHeightMapper::getZ(), and NIVissimConnectionCluster::recheckEdges().
bool Boundary::crosses (const Position & p1, const Position & p2) const virtual inherited
Returns whether the boundary crosses the given line.
Implements AbstractPoly.
Definition at line 210 of file Boundary.cpp.
References PositionVector::intersects(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
void Boundary::flipY () inherited
flips ymin and ymax
Definition at line 256 of file Boundary.cpp.
References Boundary::myYmax, and Boundary::myYmin.
Referenced by GeoConvHelper::computeFinal().
Position Boundary::getCenter () const inherited
Returns the center of the boundary.
Definition at line 120 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, and Boundary::myZmin.
Referenced by GUISUMOAbstractView::centerTo(), GUIDanielPerspectiveChanger::getXPos(), GUIDanielPerspectiveChanger::getYPos(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), GUIBaseVehicle::setFunctionalColor(), and GUIDanielPerspectiveChanger::zoom().
double Boundary::getHeight () const inherited
Returns the height of the boundary (y-axis)
Definition at line 168 of file Boundary.cpp.
References Boundary::myYmax, and Boundary::myYmin.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUIPolygon::drawGL(), GUISUMOAbstractView::getGridHeight(), GNENet::GNENet(), GUIJunctionWrapper::GUIJunctionWrapper(), GUINet::initGUIStructures(), GUIDanielPerspectiveChanger::onKeyPress(), GUIPerspectiveChanger::patchedViewPort(), GUISUMOAbstractView::screenPos2NetPos(), and GNEJunction::updateGeometry().
double Boundary::getWidth () const inherited
Returns the width of the boudary (x-axis)
Definition at line 162 of file Boundary.cpp.
References Boundary::myXmax, and Boundary::myXmin.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUIPolygon::drawGL(), GUISUMOAbstractView::getGridWidth(), GUIDanielPerspectiveChanger::getZoom(), GUIDanielPerspectiveChanger::getZPos(), GNENet::GNENet(), GUIJunctionWrapper::GUIJunctionWrapper(), GUINet::initGUIStructures(), GUISUMOAbstractView::m2p(), GUIDanielPerspectiveChanger::onKeyPress(), GUISUMOAbstractView::p2m(), GUIPerspectiveChanger::patchedViewPort(), GUISUMOAbstractView::screenPos2NetPos(), and GNEJunction::updateGeometry().
double Boundary::getZRange () const inherited
Returns the elevation range of the boundary (z-axis)
Definition at line 174 of file Boundary.cpp.
References Boundary::myZmax, and Boundary::myZmin.
Referenced by NBNetBuilder::compute(), and NBNetBuilder::computeSingleNode().
Boundary & Boundary::grow (double by) inherited
extends the boundary by the given amount
The method returns a reference to the instance for further use
Definition at line 234 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
Referenced by GUIDanielPerspectiveChanger::centerTo(), NBEdgeCont::checkOverlap(), TraCIServer::collectObjectsInRange(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), GUIEdge::getBoundary(), GNEEdge::getBoundary(), GNEInternalLane::getCenteringBoundary(), GUITrafficLightLogicWrapper::getCenteringBoundary(), GNEJunction::getCenteringBoundary(), GNECrossing::getCenteringBoundary(), GUIContainer::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GUIInstantInductLoop::MyWrapper::getCenteringBoundary(), GUILaneSpeedTrigger::getCenteringBoundary(), GUICalibrator::getCenteringBoundary(), GUIPointOfInterest::getCenteringBoundary(), GUIPerson::getCenteringBoundary(), GUIMEInductLoop::MyWrapper::getCenteringBoundary(), GUIJunctionWrapper::getCenteringBoundary(), GNEEdge::getCenteringBoundary(), GNELane::getCenteringBoundary(), GUIE3Collector::MyWrapper::getCenteringBoundary(), GUITriggeredRerouter::getCenteringBoundary(), GUIChargingStation::getCenteringBoundary(), GUIContainerStop::getCenteringBoundary(), GUIBusStop::getCenteringBoundary(), GUIParkingArea::getCenteringBoundary(), GUIEdge::getCenteringBoundary(), GUIE2Collector::MyWrapper::getCenteringBoundary(), GUIBaseVehicle::getCenteringBoundary(), GUIInductLoop::MyWrapper::getCenteringBoundary(), GUITriggeredRerouter::GUITriggeredRerouterEdge::getCenteringBoundary(), GNEAdditional::getCenteringBoundary(), GUILane::getCenteringBoundary(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), NBEdgeCont::ignoreFilterMatch(), GUINet::initGUIStructures(), and GNEViewNet::mergeJunctions().
void Boundary::growHeight (double by) inherited
Increases the height of the boundary (y-axis)
Definition at line 250 of file Boundary.cpp.
References Boundary::myYmax, and Boundary::myYmin.
Referenced by GUIPointOfInterest::getCenteringBoundary(), GUIPerspectiveChanger::patchedViewPort(), and GUIDanielPerspectiveChanger::setViewport().
void Boundary::growWidth (double by) inherited
Increases the width of the boundary (x-axis)
Definition at line 243 of file Boundary.cpp.
References Boundary::myXmax, and Boundary::myXmin.
Referenced by GUIPointOfInterest::getCenteringBoundary(), GUIPerspectiveChanger::patchedViewPort(), and GUIDanielPerspectiveChanger::setViewport().
void LayeredRTree::Insert (const float a_min[2], const float a_max[2], GUIGlObject *const & a_dataId) inline virtual
Insert entry (delegate to appropriate layer)
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_dataId Positive Id of data. Maybe zero, but negative numbers not allowed.
Reimplemented from SUMORTree.
Definition at line 79 of file LayeredRTree.h.
References myLayers, and selectLayer().
Referenced by GUINet::initGUIStructures().
void Boundary::moveby (double x, double y, double z = 0) inherited
Moves the boundary by the given amount.
Definition at line 283 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, and Boundary::myZmin.
Referenced by GUIDanielPerspectiveChanger::centerTo(), GUIDanielPerspectiveChanger::move(), GeoConvHelper::moveConvertedBy(), GUIDanielPerspectiveChanger::onKeyPress(), and GNEJunction::setPosition().
bool Boundary::overlapsWith (const AbstractPoly & poly, double offset = 0) const virtual inherited
Returns whether the boundary overlaps with the given polygon.
Implements AbstractPoly.
Definition at line 189 of file Boundary.cpp.
References AbstractPoly::crosses(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, AbstractPoly::partialWithin(), and Boundary::partialWithin().
Referenced by NBEdgeCont::checkOverlap(), NIVissimBoundedClusterObject::crosses(), NBEdgeCont::ignoreFilterMatch(), NIVissimConnectionCluster::overlapsWith(), and NIVissimConnectionCluster::NodeSubCluster::overlapsWith().
bool Boundary::partialWithin (const AbstractPoly & poly, double offset = 0) const virtual inherited
Returns whether the boundary is partially within the given polygon.
Implements AbstractPoly.
Definition at line 224 of file Boundary.cpp.
References AbstractPoly::around(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
Referenced by PCPolyContainer::add(), and Boundary::overlapsWith().
void LayeredRTree::Remove (const float a_min[2], const float a_max[2], GUIGlObject *const & a_dataId) inline virtual
Remove entry (delegate to appropriate layer)
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_dataId Positive Id of data. Maybe zero, but negative numbers not allowed.
Reimplemented from SUMORTree.
Definition at line 89 of file LayeredRTree.h.
References myLayers, and selectLayer().
void SUMORTree::removeAdditionalGLObject (GUIGlObject * o) inline inherited
Removes an additional object (detector/shape/trigger) from being visualised.
Parameters
[in] o The object to remove
Definition at line 141 of file SUMORTree.h.
References GUIGlObject::getCenteringBoundary(), SUMORTree::myLock, SUMORTree::Remove(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GNETLSEditorFrame::buildIinternalLanes(), GNENet::deleteAdditional(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIShapeContainer::movePOI(), GNEViewNet::onCmdNodeShape(), GNENet::refreshAdditional(), GNENet::refreshElement(), GNEViewNet::removeCurrentPoly(), GUIShapeContainer::removePOI(), GUIShapeContainer::removePolygon(), and GUIShapeContainer::reshapePolygon().
void Boundary::reset () inherited
Resets the boundary.
Definition at line 74 of file Boundary.cpp.
References Boundary::myWasInitialised, Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, and Boundary::myZmin.
Referenced by NBHeightMapper::clearData(), and GNENet::computeAndUpdate().
int LayeredRTree::Search (const float a_min[2], const float a_max[2], const GUIVisualizationSettings & c) const inline virtual
Find all within search rectangle (searches all layers in order)
Parameters
a_min Min of search bounding rect
a_max Max of search bounding rect
a_searchResult Search result array. Caller should set grow size. Function will reset, not append to array.
a_resultCallback Callback function to return result. Callback should return 'true' to continue searching
a_context User context to pass as parameter to a_resultCallback
Returns
Returns the number of entries found
Reimplemented from SUMORTree.
Definition at line 101 of file LayeredRTree.h.
References myLayers.
size_t LayeredRTree::selectLayer (GUIGlObject * o) inline private
select the appropriate layer for each object
Definition at line 117 of file LayeredRTree.h.
References GUIGlObject::getType(), GLO_EDGE, GLO_LANE, GLO_PERSON, GLO_POI, and GLO_VEHICLE.
Referenced by Insert(), and Remove().
void Boundary::set (double xmin, double ymin, double xmax, double ymax) inherited
Sets the boundary to the given values.
Definition at line 274 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by TraCIServer::readTypeCheckingBoundary().
double Boundary::xmax () const inherited
Returns maximum x-coordinate.
Definition at line 132 of file Boundary.cpp.
References Boundary::myXmax.
Referenced by Boundary::add(), NIVissimConnectionCluster::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), NIVissimConnectionCluster::around(), NIVissimConnection::buildNodeClusters(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimBoundedClusterObject::crosses(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), NIVissimConnection::getBoundingBox(), NIVissimConnectionCluster::getPositionForEdge(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Polygon::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimConnectionCluster::overlapsWith(), NIVissimConnectionCluster::NodeSubCluster::overlapsWith(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), SUMORTree::removeAdditionalGLObject(), Boundary::set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and GUIDanielPerspectiveChanger::zoom().
double Boundary::xmin () const inherited
Returns minimum x-coordinate.
Definition at line 126 of file Boundary.cpp.
References Boundary::myXmin.
Referenced by Boundary::add(), NIVissimConnectionCluster::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUISUMOAbstractView::applyGLTransform(), NIVissimConnectionCluster::around(), NIVissimConnection::buildNodeClusters(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimBoundedClusterObject::crosses(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), NIVissimConnection::getBoundingBox(), NIVissimConnectionCluster::getPositionForEdge(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Polygon::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimConnectionCluster::overlapsWith(), NIVissimConnectionCluster::NodeSubCluster::overlapsWith(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), SUMORTree::removeAdditionalGLObject(), GUISUMOAbstractView::screenPos2NetPos(), Boundary::set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and GUIDanielPerspectiveChanger::zoom().
double Boundary::ymax () const inherited
Returns maximum y-coordinate.
Definition at line 144 of file Boundary.cpp.
References Boundary::myYmax.
Referenced by Boundary::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Polygon::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), SUMORTree::removeAdditionalGLObject(), Boundary::set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and GUIDanielPerspectiveChanger::zoom().
double Boundary::ymin () const inherited
Returns minimum y-coordinate.
Definition at line 138 of file Boundary.cpp.
References Boundary::myYmin.
Referenced by Boundary::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUISUMOAbstractView::applyGLTransform(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Polygon::getTree(), GNENet::GNENet(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), SUMORTree::removeAdditionalGLObject(), GUISUMOAbstractView::screenPos2NetPos(), Boundary::set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and GUIDanielPerspectiveChanger::zoom().
double Boundary::zmax () const inherited
Returns maximum z-coordinate.
Definition at line 156 of file Boundary.cpp.
References Boundary::myZmax.
Referenced by Boundary::add().
double Boundary::zmin () const inherited
Returns minimum z-coordinate.
Definition at line 150 of file Boundary.cpp.
References Boundary::myZmin.
Referenced by Boundary::add().
Field Documentation
std::vector<SUMORTree*> LayeredRTree::myLayers protected
the layers for drawing
Definition at line 112 of file LayeredRTree.h.
Referenced by Insert(), LayeredRTree(), Remove(), Search(), and ~LayeredRTree().
MFXMutex SUMORTree::myLock mutable protected inherited
A mutex avoiding parallel change and traversal of the tree.
Definition at line 152 of file SUMORTree.h.
Referenced by SUMORTree::addAdditionalGLObject(), SUMORTree::Insert(), SUMORTree::Remove(), SUMORTree::removeAdditionalGLObject(), and SUMORTree::Search().
The documentation for this class was generated from the following file:
LayeredRTree.h