SUMO - Simulation of Urban MObility: GNEVariableSpeedSignStep Class Reference
GNEVariableSpeedSignStep Class Reference
#include <GNEVariableSpeedSignStep.h>
Public Member Functions
double getSpeed () const
get speed
SumoXMLTag getTag () const
get tag
double getTime () const
get time
GNEVariableSpeedSign * getVariableSpeedSignParent () const
get variable speed sign parent
GNEVariableSpeedSignStep (GNEVariableSpeedSign *variableSpeedSignParent)
default constructor
GNEVariableSpeedSignStep (GNEVariableSpeedSign *variableSpeedSignParent, double time, double speed)
constructor
bool operator!= (const GNEVariableSpeedSignStep &variableSpeedSignStep) const
overload operator !=
bool operator< (const GNEVariableSpeedSignStep &variableSpeedSignStep) const
overload operator <
bool operator<= (const GNEVariableSpeedSignStep &variableSpeedSignStep) const
overload operator <=
bool operator== (const GNEVariableSpeedSignStep &variableSpeedSignStep) const
overload operator ==
bool operator> (const GNEVariableSpeedSignStep &variableSpeedSignStep) const
overload operator >
bool operator>= (const GNEVariableSpeedSignStep &variableSpeedSignStep) const
overload operator >=
bool setSpeed (double speed)
set speed time
bool setTime (double time)
set time
~GNEVariableSpeedSignStep ()
destructor
Protected Attributes
double mySpeed
speed in this timeStep
SumoXMLTag myTag
XML Tag of a variable speed sign interval.
double myTime
timeStep
GNEVariableSpeedSign * myVariableSpeedSignParent
pointer to variable speed sign parent
Detailed Description
class used to represent a interval used in variable speed sign
Definition at line 50 of file GNEVariableSpeedSignStep.h.
Constructor & Destructor Documentation
GNEVariableSpeedSignStep::GNEVariableSpeedSignStep (GNEVariableSpeedSign * variableSpeedSignParent)
default constructor
Definition at line 41 of file GNEVariableSpeedSignStep.cpp.
GNEVariableSpeedSignStep::GNEVariableSpeedSignStep (GNEVariableSpeedSign * variableSpeedSignParent, double time, double speed)
constructor
Definition at line 49 of file GNEVariableSpeedSignStep.cpp.
References setSpeed(), and setTime().
GNEVariableSpeedSignStep::~GNEVariableSpeedSignStep ()
destructor
Definition at line 60 of file GNEVariableSpeedSignStep.cpp.
Member Function Documentation
double GNEVariableSpeedSignStep::getSpeed () const
get speed
Definition at line 82 of file GNEVariableSpeedSignStep.cpp.
References mySpeed.
SumoXMLTag GNEVariableSpeedSignStep::getTag () const
get tag
Definition at line 70 of file GNEVariableSpeedSignStep.cpp.
References myTag.
Referenced by GNEAdditionalHandler::parseVariableSpeedSignStep().
double GNEVariableSpeedSignStep::getTime () const
get time
Definition at line 76 of file GNEVariableSpeedSignStep.cpp.
References myTime.
GNEVariableSpeedSign * GNEVariableSpeedSignStep::getVariableSpeedSignParent () const
get variable speed sign parent
Definition at line 64 of file GNEVariableSpeedSignStep.cpp.
References myVariableSpeedSignParent.
bool GNEVariableSpeedSignStep::operator!= (const GNEVariableSpeedSignStep & variableSpeedSignStep) const
overload operator !=
Definition at line 116 of file GNEVariableSpeedSignStep.cpp.
References myTime.
bool GNEVariableSpeedSignStep::operator< (const GNEVariableSpeedSignStep & variableSpeedSignStep) const
overload operator <
Definition at line 128 of file GNEVariableSpeedSignStep.cpp.
References myTime.
bool GNEVariableSpeedSignStep::operator<= (const GNEVariableSpeedSignStep & variableSpeedSignStep) const
overload operator <=
Definition at line 140 of file GNEVariableSpeedSignStep.cpp.
References myTime.
bool GNEVariableSpeedSignStep::operator== (const GNEVariableSpeedSignStep & variableSpeedSignStep) const
overload operator ==
Definition at line 110 of file GNEVariableSpeedSignStep.cpp.
References myTime.
bool GNEVariableSpeedSignStep::operator> (const GNEVariableSpeedSignStep & variableSpeedSignStep) const
overload operator >
Definition at line 122 of file GNEVariableSpeedSignStep.cpp.
References myTime.
bool GNEVariableSpeedSignStep::operator>= (const GNEVariableSpeedSignStep & variableSpeedSignStep) const
overload operator >=
Definition at line 134 of file GNEVariableSpeedSignStep.cpp.
References myTime.
bool GNEVariableSpeedSignStep::setSpeed (double speed)
set speed time
return true if was sucesfully set, false in other case
Definition at line 99 of file GNEVariableSpeedSignStep.cpp.
References mySpeed.
Referenced by GNEVariableSpeedSignStep(), and GNEVariableSpeedSignDialog::onCmdAddRow().
bool GNEVariableSpeedSignStep::setTime (double time)
set time
return true if was sucesfully set, false in other case
Definition at line 88 of file GNEVariableSpeedSignStep.cpp.
References myTime.
Referenced by GNEVariableSpeedSignStep(), and GNEVariableSpeedSignDialog::onCmdAddRow().
Field Documentation
double GNEVariableSpeedSignStep::mySpeed protected
speed in this timeStep
Definition at line 109 of file GNEVariableSpeedSignStep.h.
Referenced by getSpeed(), and setSpeed().
SumoXMLTag GNEVariableSpeedSignStep::myTag protected
XML Tag of a variable speed sign interval.
Definition at line 112 of file GNEVariableSpeedSignStep.h.
Referenced by getTag().
double GNEVariableSpeedSignStep::myTime protected
timeStep
Definition at line 106 of file GNEVariableSpeedSignStep.h.
Referenced by getTime(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and setTime().
GNEVariableSpeedSign* GNEVariableSpeedSignStep::myVariableSpeedSignParent protected
pointer to variable speed sign parent
Definition at line 103 of file GNEVariableSpeedSignStep.h.
Referenced by getVariableSpeedSignParent().
The documentation for this class was generated from the following files:
GNEVariableSpeedSignStep.h
GNEVariableSpeedSignStep.cpp