SUMO - Simulation of Urban MObility: MSLCM_DK2008 Class Reference
MSLCM_DK2008 Class Reference
A lane change model developed by D. Krajzewicz between 2004 and 2010.
#include <MSLCM_DK2008.h>
Public Types
enum MyLCAEnum {
LCA_AMBLOCKINGLEADER = 1 << 16, LCA_AMBLOCKINGFOLLOWER = 1 << 17, LCA_MRIGHT = 1 << 18, LCA_MLEFT = 1 << 19,
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE = 1 << 21, LCA_AMBACKBLOCKER = 1 << 26, LCA_AMBACKBLOCKER_STANDING = 1 << 27
}
Public Member Functions
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
virtual void changed ()
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void cleanupShadowLane ()
virtual bool debugVehicle () const
whether the current vehicles shall be debugged
virtual StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
double getAngleOffset () const
return the angle offset during a continuous change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
double getLateralSpeed () const
return the lateral speed of the current lane change maneuver
int getOwnState () const
virtual std::string getParameter (const std::string &key) const
try to retrieve the given parameter from this laneChangeModel. Throw exception for unsupported key
const std::pair< int, int > & getSavedState (const int dir) const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< double > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
virtual void * inform (void *info, MSVehicle *sender)
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
MSLCM_DK2008 (MSVehicle &v)
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
virtual double patchSpeed (const double min, const double wanted, const double max, const MSCFModel &cfModel)
Called to adapt the speed in order to allow a lane change.
virtual void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
virtual void saveBlockerLength (double length)
reserve space at the end of the lane to avoid dead locks
void saveState (const int dir, const int stateWithoutTraCI, const int state)
void setNoShadowPartialOccupator (MSLane *lane)
virtual void setOwnState (const int state)
virtual void setParameter (const std::string &key, const std::string &value)
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
bool updateCompletion ()
virtual void updateExpectedSublaneSpeeds (const MSLeaderInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
void updateShadowLane ()
int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, double > &leader, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, double &latDist, int &blocked)
virtual ~MSLCM_DK2008 ()
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
Protected Types
typedef std::pair< double, int > Info
Protected Member Functions
bool amBlockingFollower ()
bool amBlockingFollowerNB ()
bool amBlockingFollowerPlusNB ()
bool amBlockingLeader ()
bool cancelRequest (int state)
whether the influencer cancels the given request
virtual bool congested (const MSVehicle *const neighLeader)
bool currentDistAllows (double dist, int laneOffset, double lookForwardDist)
bool currentDistDisallows (double dist, int laneOffset, double lookForwardDist)
void informBlocker (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int &blocked, int dir, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow)
void initLastLaneChangeOffset (int dir)
virtual bool predInteraction (const std::pair< MSVehicle *, double > &leader)
virtual int wantsChangeToLeft (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, double > &leader, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change to left This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeToRight (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, double > &leader, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change to right This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
double myChangeProbability
bool myDontBrake
double myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
double myLastLateralGapLeft
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
double myLastLateralGapRight
double myLateralspeed
The lateral offset during a continuous LaneChangeManeuver.
double myLeadingBlockerLength
double myLeftSpace
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
std::map< int, std::pair< int, int > > mySavedStates
std::vector< MSLane * > myShadowFurtherLanes
std::vector< double > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
std::vector< double > myVSafes
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCOutput
whether to record lane-changing
static const double NO_LATERAL_NEIGHBOR
Detailed Description
A lane change model developed by D. Krajzewicz between 2004 and 2010.
Definition at line 47 of file MSLCM_DK2008.h.
Member Typedef Documentation
typedef std::pair<double, int> MSLCM_DK2008::Info protected
Definition at line 153 of file MSLCM_DK2008.h.
Member Enumeration Documentation
enum MSLCM_DK2008::MyLCAEnum
Enumerator
LCA_AMBLOCKINGLEADER
LCA_AMBLOCKINGFOLLOWER
LCA_MRIGHT
LCA_MLEFT
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE
LCA_AMBACKBLOCKER
LCA_AMBACKBLOCKER_STANDING
Definition at line 50 of file MSLCM_DK2008.h.
Constructor & Destructor Documentation
MSLCM_DK2008::MSLCM_DK2008 (MSVehicle & v)
Definition at line 62 of file MSLCM_DK2008.cpp.
MSLCM_DK2008::~MSLCM_DK2008 () virtual
Definition at line 67 of file MSLCM_DK2008.cpp.
References changed().
Member Function Documentation
bool MSAbstractLaneChangeModel::alreadyChanged () const inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 338 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyChanged.
Referenced by MSLaneChanger::change().
bool MSLCM_DK2008::amBlockingFollower () inline protected
Definition at line 137 of file MSLCM_DK2008.h.
References LCA_AMBLOCKINGFOLLOWER, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_DK2008::amBlockingFollowerNB () inline protected
Definition at line 140 of file MSLCM_DK2008.h.
References LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_DK2008::amBlockingFollowerPlusNB () inline protected
Definition at line 143 of file MSLCM_DK2008.h.
References LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2008::amBlockingLeader () inline protected
Definition at line 134 of file MSLCM_DK2008.h.
References LCA_AMBLOCKINGLEADER, and MSAbstractLaneChangeModel::myOwnState.
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static inherited
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 63 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::sameDirection().
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected inherited
whether the influencer cancels the given request
Definition at line 257 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), and MSAbstractLaneChangeModel::setParameter().
void MSLCM_DK2008::changed () virtual
Implements MSAbstractLaneChangeModel.
Definition at line 616 of file MSLCM_DK2008.cpp.
References myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, and myVSafes.
Referenced by patchSpeed(), and ~MSLCM_DK2008().
void MSAbstractLaneChangeModel::changedToOpposite () inherited
called when a vehicle changes between lanes in opposite directions
Definition at line 364 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myAlreadyChanged, and MSAbstractLaneChangeModel::myAmOpposite.
Referenced by MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::executeMove(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
void MSAbstractLaneChangeModel::cleanupShadowLane () inherited
Definition at line 237 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::resetChanged(), and MSVehicle::~MSVehicle().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual inherited
Definition at line 114 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::setParameter(), wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2008::currentDistAllows (double dist, int laneOffset, double lookForwardDist) inline protected
Definition at line 149 of file MSLCM_DK2008.h.
References abs.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2008::currentDistDisallows (double dist, int laneOffset, double lookForwardDist) inline protected
Definition at line 146 of file MSLCM_DK2008.h.
References abs.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
virtual bool MSAbstractLaneChangeModel::debugVehicle () const inline virtual inherited
whether the current vehicles shall be debugged
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 265 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::changedToOpposite().
Referenced by MSLaneChangerSublane::change(), MSLaneChangerSublane::startChangeSublane(), and MSAbstractLaneChangeModel::updateShadowLane().
virtual StateAndDist MSAbstractLaneChangeModel::decideDirection (StateAndDist sd1, StateAndDist sd2) const inline virtual inherited
decide in which direction to move in case both directions are desirable
Reimplemented in MSLCM_SL2015.
Definition at line 237 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::changed(), MSAbstractLaneChangeModel::inform(), max, min, MSAbstractLaneChangeModel::myModel, MSAbstractLaneChangeModel::patchSpeed(), toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE) inherited
Definition at line 201 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSVehicle::fixPosition(), MSAbstractLaneChangeModel::myAmOpposite, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSAbstractLaneChangeModel::updateShadowLane().
double MSAbstractLaneChangeModel::getAngleOffset () const inherited
return the angle offset during a continuous change maneuver
Definition at line 335 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::pastMidpoint(), and STEPS2TIME.
Referenced by MSAbstractLaneChangeModel::getLaneChangeDirection().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline inherited
return the direction of the current lane change maneuver
Definition at line 322 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::myLaneChangeDirection.
Referenced by MSLaneChanger::continueChange().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline inherited
Definition at line 303 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
double MSAbstractLaneChangeModel::getLateralSpeed () const inline inherited
return the lateral speed of the current lane change maneuver
Definition at line 333 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLateralspeed.
Referenced by MSLaneChanger::continueChange().
int MSAbstractLaneChangeModel::getOwnState () const inline inherited
Definition at line 152 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState, and MSAbstractLaneChangeModel::setOwnState().
Referenced by MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), and MSVehicle::setBlinkerInformation().
virtual std::string MSAbstractLaneChangeModel::getParameter (const std::string & key) const inline virtual inherited
try to retrieve the given parameter from this laneChangeModel. Throw exception for unsupported key
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 391 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, and toString().
Referenced by TraCI_Vehicle::getParameter().
const std::pair<int, int>& MSAbstractLaneChangeModel::getSavedState (const int dir) const inline inherited
Definition at line 158 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::mySavedStates.
Referenced by TraCI_Vehicle::getLaneChangeState().
int MSAbstractLaneChangeModel::getShadowDirection () const inherited
return the direction in which the current shadow lane lies
Definition at line 318 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, and MSAbstractLaneChangeModel::pastMidpoint().
Referenced by MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::getLaneChangeDirection(), and GUIVehicle::selectBlockingFoes().
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline inherited
Definition at line 295 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
const std::vector<double>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline inherited
Definition at line 299 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline inherited
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 283 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), MSVehicle::isFrontOnLane(), MSVehicle::planMoveInternal(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const inherited
return the shadow lane for the given lane
Definition at line 215 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, and SIMTIME.
void * MSLCM_DK2008::inform (void * info, MSVehicle * sender) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 606 of file MSLCM_DK2008.cpp.
References MSAbstractLaneChangeModel::myOwnState.
void MSLCM_DK2008::informBlocker (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int & blocked, int dir, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow) protected
Definition at line 627 of file MSLCM_DK2008.cpp.
References ACCEL2DIST, MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, MAX2(), MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, and SPEED2DIST.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static inherited
init global model parameters
Definition at line 56 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), MSAbstractLaneChangeModel::myAllowOvertakingRight, and MSAbstractLaneChangeModel::myLCOutput.
Referenced by MSAbstractLaneChangeModel::StateAndDist::sameDirection(), and MSFrame::setMSGlobals().
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected inherited
Definition at line 264 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSAbstractLaneChangeModel::primaryLaneChanged().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline inherited
return true if the vehicle currently performs a lane change maneuver
Definition at line 317 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
bool MSAbstractLaneChangeModel::isOpposite () const inline inherited
Definition at line 386 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAmOpposite.
Referenced by MSLCM_LC2013::_wantsChange(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtInsertion(), MSLink::getLeaderInfo(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSLCM_LC2013::informLeader(), and MSVehicle::planMoveInternal().
bool MSAbstractLaneChangeModel::pastMidpoint () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 309 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::remainingTime().
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::updateCompletion().
double MSLCM_DK2008::patchSpeed (const double min, const double wanted, const double max, const MSCFModel & cfModel) virtual
Called to adapt the speed in order to allow a lane change.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implements MSAbstractLaneChangeModel.
Definition at line 513 of file MSLCM_DK2008.cpp.
References changed(), MSEdge::EDGEFUNCTION_INTERNAL, gDebugSelectedVehicle, MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSEdge::getLanes(), MSVehicleType::getMinGap(), MSEdge::getPurpose(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_WANTS_LANECHANGE, MAX2(), MSCFModel::maxNextSpeed(), min, MIN2(), myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, and MSCFModel::stopSpeed().
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, double > & leader) protected virtual inherited
Definition at line 134 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), MSAbstractLaneChangeModel::myCarFollowModel, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::setParameter(), wantsChangeToLeft(), and wantsChangeToRight().
void MSLCM_DK2008::prepareStep () virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 656 of file MSLCM_DK2008.cpp.
References myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, myVSafes, and MSAbstractLaneChangeModel::prepareStep().
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction) inherited
called once when the vehicles primary lane changes
Definition at line 166 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), OutputDevice::closeTag(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getSpeed(), MSGlobals::gLateralResolution, MSAbstractLaneChangeModel::initLastLaneChangeOffset(), LCA_LEFT, LCA_RIGHT, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), MSAbstractLaneChangeModel::myLastLateralGapLeft, MSAbstractLaneChangeModel::myLastLateralGapRight, MSAbstractLaneChangeModel::myLCOutput, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::NO_LATERAL_NEIGHBOR, MSMoveReminder::NOTIFICATION_LANE_CHANGE, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, time2string(), toString(), and OutputDevice::writeAttr().
Referenced by MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::remainingTime () const inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 342 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and MSAbstractLaneChangeModel::myLaneChangeCompletion.
Referenced by MSAbstractLaneChangeModel::pastMidpoint().
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const inherited
Definition at line 354 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::resetChanged () inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 343 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSAbstractLaneChangeModel::updateCompletion(), and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by MSVehicle::planMove().
virtual void MSAbstractLaneChangeModel::saveBlockerLength (double length) inline virtual inherited
reserve space at the end of the lane to avoid dead locks
Reimplemented in MSLCM_LC2013, and MSLCM_SL2015.
Definition at line 367 of file MSAbstractLaneChangeModel.h.
References UNUSED_PARAMETER.
Referenced by MSLCM_LC2013::saveBlockerLength().
void MSAbstractLaneChangeModel::saveState (const int dir, const int stateWithoutTraCI, const int state) inline inherited
Definition at line 162 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::mySavedStates.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), and MSAbstractLaneChangeModel::prepareStep().
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 375 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), and MSAbstractLaneChangeModel::setShadowApproachingInformation().
Referenced by MSVehicle::enterLaneAtLaneChange().
void MSAbstractLaneChangeModel::setOwnState (const int state) virtual inherited
Reimplemented in MSLCM_SL2015.
Definition at line 105 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getInfluencer(), MSVehicle::hasInfluencer(), MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, and MSVehicle::Influencer::setSublaneChange().
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSAbstractLaneChangeModel::getOwnState(), and MSLCM_SL2015::setOwnState().
virtual void MSAbstractLaneChangeModel::setParameter (const std::string & key, const std::string & value) inline virtual inherited
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 396 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cancelRequest(), MSAbstractLaneChangeModel::congested(), MSAbstractLaneChangeModel::myModel, MSAbstractLaneChangeModel::predInteraction(), toString(), and UNUSED_PARAMETER.
Referenced by TraCI_Vehicle::setParameter().
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const inherited
set approach information for the shadow vehicle
Definition at line 348 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline inherited
set the shadow lane
Definition at line 291 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 371 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow.
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction) inherited
start the lane change maneuver and return whether it continues
Definition at line 147 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLateralspeed, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::primaryLaneChanged(), MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::changeOpposite(), MSAbstractLaneChangeModel::resetChanged(), MSLaneChanger::startChange(), and MSLaneChangerSublane::startChangeSublane().
void MSAbstractLaneChangeModel::unchanged () inline inherited
Definition at line 272 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
bool MSAbstractLaneChangeModel::updateCompletion () inherited
Definition at line 193 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::pastMidpoint().
Referenced by MSLaneChanger::continueChange(), and MSAbstractLaneChangeModel::resetChanged().
virtual void MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds (const MSLeaderInfo & ahead, int sublaneOffset, int laneIndex) inline virtual inherited
update expected speeds for each sublane of the current edge
Reimplemented in MSLCM_SL2015.
Definition at line 229 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::updateShadowLane () inherited
Definition at line 273 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSLinkContHelper::getConnectingLink(), MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSLaneChangerSublane::startChangeSublane().
int MSLCM_DK2008::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, double > & leader, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 72 of file MSLCM_DK2008.cpp.
References UNUSED_PARAMETER, wantsChangeToLeft(), and wantsChangeToRight().
virtual int MSAbstractLaneChangeModel::wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, double & latDist, int & blocked) inline virtual inherited
Reimplemented in MSLCM_SL2015.
Definition at line 199 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::checkChangeSublane().
int MSLCM_DK2008::wantsChangeToLeft (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, double > & leader, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) protected virtual
Called to examine whether the vehicle wants to change to left This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
!!
Definition at line 303 of file MSLCM_DK2008.cpp.
References ACCEL2SPEED, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestLaneOffset, MSAbstractLaneChangeModel::congested(), currentDistAllows(), currentDistDisallows(), MSEdge::EDGEFUNCTION_INTERNAL, MSCFModel::followSpeed(), gDebugSelectedVehicle, MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), MSCFModel::getMaxDecel(), MSVehicleType::getMaxSpeed(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSEdge::getPurpose(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), informBlocker(), JAM_FACTOR2, MSVehicle::LaneQ::lane, LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_BLOCKED, LCA_COOPERATIVE, LCA_LEFT, LCA_MLEFT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_FORWARD_FAR, LOOK_FORWARD_NEAR, LOOK_FORWARD_SPEED_DIVIDER, MAX2(), MIN2(), MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSVehicle::LaneQ::occupation, MSAbstractLaneChangeModel::predInteraction(), SUMO_const_haltingSpeed, TS, and UNUSED_PARAMETER.
Referenced by wantsChange().
int MSLCM_DK2008::wantsChangeToRight (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, double > & leader, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) protected virtual
Called to examine whether the vehicle wants to change to right This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
!!
Definition at line 91 of file MSLCM_DK2008.cpp.
References ACCEL2SPEED, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestLaneOffset, MSAbstractLaneChangeModel::congested(), currentDistAllows(), currentDistDisallows(), MSEdge::EDGEFUNCTION_INTERNAL, MSCFModel::followSpeed(), gDebugSelectedVehicle, MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), MSCFModel::getMaxDecel(), MSVehicleType::getMaxSpeed(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSEdge::getPurpose(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), informBlocker(), JAM_FACTOR2, MSVehicle::LaneQ::lane, LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_BLOCKED, LCA_COOPERATIVE, LCA_LEFT, LCA_MRIGHT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_FORWARD_FAR, LOOK_FORWARD_NEAR, LOOK_FORWARD_SPEED_DIVIDER, MAX2(), MIN2(), MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSVehicle::LaneQ::occupation, MSAbstractLaneChangeModel::predInteraction(), SUMO_const_haltingSpeed, TS, and UNUSED_PARAMETER.
Referenced by wantsChange().
Field Documentation
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected inherited
whether overtaking on the right is permitted
Definition at line 461 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), and MSAbstractLaneChangeModel::initGlobalOptions().
bool MSAbstractLaneChangeModel::myAlreadyChanged protected inherited
whether the vehicle has already moved this step
Definition at line 428 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::alreadyChanged(), MSAbstractLaneChangeModel::changedToOpposite(), and MSAbstractLaneChangeModel::resetChanged().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected inherited
The vehicle's car following model.
Definition at line 439 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), wantsChangeToLeft(), and wantsChangeToRight().
double MSLCM_DK2008::myChangeProbability protected
Definition at line 158 of file MSLCM_DK2008.h.
Referenced by changed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2008::myDontBrake protected
Definition at line 164 of file MSLCM_DK2008.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
double MSAbstractLaneChangeModel::myLaneChangeCompletion protected inherited
progress of the lane change maneuver 0:started, 1:complete
Definition at line 419 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::pastMidpoint(), MSAbstractLaneChangeModel::remainingTime(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::updateCompletion().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected inherited
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 422 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getLaneChangeDirection(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
double MSAbstractLaneChangeModel::myLastLateralGapLeft protected inherited
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
Definition at line 452 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), and MSLCM_SL2015::updateGaps().
double MSAbstractLaneChangeModel::myLastLateralGapRight protected inherited
Definition at line 453 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), and MSLCM_SL2015::updateGaps().
double MSAbstractLaneChangeModel::myLateralspeed protected inherited
The lateral offset during a continuous LaneChangeManeuver.
Definition at line 425 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getLateralSpeed(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLCOutput static protected inherited
whether to record lane-changing
Definition at line 464 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::initGlobalOptions(), and MSAbstractLaneChangeModel::primaryLaneChanged().
double MSLCM_DK2008::myLeadingBlockerLength protected
Definition at line 160 of file MSLCM_DK2008.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
double MSLCM_DK2008::myLeftSpace protected
Definition at line 161 of file MSLCM_DK2008.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected inherited
the type of this model
Definition at line 442 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::decideDirection(), MSLCM_LC2013::getParameter(), MSLCM_SL2015::getParameter(), MSAbstractLaneChangeModel::getParameter(), MSLCM_LC2013::setParameter(), MSLCM_SL2015::setParameter(), MSAbstractLaneChangeModel::setParameter(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::wantsChange(), and MSAbstractLaneChangeModel::wantsChangeSublane().
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected inherited
Definition at line 449 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
int MSAbstractLaneChangeModel::myOwnState protected inherited
The current state of the vehicle.
Definition at line 415 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), amBlockingFollower(), MSLCM_SL2015::amBlockingFollower(), MSLCM_LC2013::amBlockingFollower(), amBlockingFollowerNB(), MSLCM_SL2015::amBlockingFollowerNB(), MSLCM_LC2013::amBlockingFollowerNB(), amBlockingFollowerPlusNB(), MSLCM_SL2015::amBlockingFollowerPlusNB(), MSLCM_LC2013::amBlockingFollowerPlusNB(), amBlockingLeader(), MSLCM_SL2015::amBlockingLeader(), MSLCM_LC2013::amBlockingLeader(), changed(), MSLCM_LC2013::changed(), MSLCM_SL2015::changed(), MSAbstractLaneChangeModel::getOwnState(), inform(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), patchSpeed(), prepareStep(), MSLCM_LC2013::prepareStep(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::setOwnState(), wantsChangeToLeft(), and wantsChangeToRight().
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected inherited
list of lanes where the shadow vehicle is partial occupator
Definition at line 445 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::setShadowPartialOccupator().
std::map<int, std::pair<int, int> > MSAbstractLaneChangeModel::mySavedStates protected inherited
Definition at line 416 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getSavedState(), and MSAbstractLaneChangeModel::saveState().
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected inherited
Definition at line 435 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
std::vector<double> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected inherited
Definition at line 436 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected inherited
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 431 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::setShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected inherited
The vehicle this lane-changer belongs to.
Definition at line 412 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSAbstractLaneChangeModel::cancelRequest(), MSLCM_LC2013::changed(), MSLCM_SL2015::changed(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::congested(), MSLCM_SL2015::decideDirection(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::msg(), MSLCM_LC2013::MSLCM_LC2013(), patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::setOwnState(), MSAbstractLaneChangeModel::setOwnState(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), wantsChangeToLeft(), and wantsChangeToRight().
std::vector<double> MSLCM_DK2008::myVSafes protected
Definition at line 163 of file MSLCM_DK2008.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
const double MSAbstractLaneChangeModel::NO_LATERAL_NEIGHBOR static protected inherited
Definition at line 466 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::prepareStep(), and MSAbstractLaneChangeModel::primaryLaneChanged().
The documentation for this class was generated from the following files:
MSLCM_DK2008.h
MSLCM_DK2008.cpp