SUMO - Simulation of Urban MObility: netconvert_main.cpp File Reference
netconvert_main.cpp File Reference
#include <config.h>
#include <version.h>
#include <iostream>
#include <string>
#include <netimport/NIFrame.h>
#include <netimport/NILoader.h>
#include <netbuild/NBFrame.h>
#include <netbuild/NBNetBuilder.h>
#include <netwrite/NWFrame.h>
#include <utils/options/OptionsIO.h>
#include <utils/options/OptionsCont.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/RandHelper.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/MsgHandler.h>
#include <utils/distribution/DistributionCont.h>
#include <utils/xml/XMLSubSys.h>
#include <utils/iodevices/OutputDevice.h>
#include <utils/geom/GeoConvHelper.h>
Functions
bool checkOptions ()
void fillOptions ()
int main (int argc, char **argv)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Tue, 20 Nov 2001
Version
Id
netconvert_main.cpp 23529 2017-03-18 10:22:36Z behrisch
Definition in file netconvert_main.cpp.
Function Documentation
bool checkOptions ()
Definition at line 87 of file netconvert_main.cpp.
References NIFrame::checkOptions(), NWFrame::checkOptions(), NBFrame::checkOptions(), and SystemFrame::checkOptions().
Referenced by main().
void fillOptions ()
Definition at line 60 of file netconvert_main.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), OptionsCont::addOptionSubTopic(), GeoConvHelper::addProjectionOptions(), SystemFrame::addReportOptions(), NIFrame::fillOptions(), NWFrame::fillOptions(), NBFrame::fillOptions(), OptionsCont::getOptions(), and RandHelper::insertRandOptions().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 100 of file netconvert_main.cpp.
References NBNetBuilder::applyOptions(), checkOptions(), DistributionCont::clear(), MsgHandler::clear(), SystemFrame::close(), NBNetBuilder::compute(), fillOptions(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), MsgHandler::inform(), XMLSubSys::init(), GeoConvHelper::init(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), NILoader::load(), OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), XMLSubSys::setValidation(), VERSION_STRING, WRITE_ERROR, and NWFrame::writeNetwork().