SUMO - Simulation of Urban MObility: GUIApplicationWindow Class Reference
GUIApplicationWindow Class Reference
The main window of the SUMO-gui.
#include <GUIApplicationWindow.h>
Public Member Functions
void addChild (FXMDIChild *child, bool updateOnSimStep=true)
Adds a further child window to the list.
void addChild (FXMainWindow *child, bool updateOnSimStep=true)
void addRecentFile (const FX::FXString &f, const bool isNet)
void dependentBuild ()
GUISUMOAbstractView * getActiveView () const
get the active view or 0
FXFont * getBoldFont ()
FXGLCanvas * getBuildGLCanvas () const
FXLabel & getCartesianLabel ()
SUMOTime getCurrentSimTime () const
FXCursor * getDefaultCursor ()
virtual double getDelay () const
Returns the simulation delay.
FXLabel & getGeoLabel ()
FXGLVisual * getGLVisual () const
FXMDIChild * getViewByID (const std::string &id) const
std::vector< std::string > getViewIDs () const
GUIApplicationWindow (FXApp *a, const std::string &configPattern)
Constructor.
bool isGaming () const
return whether the gui is in gaming mode
bool listInternal () const
return whether to list internal structures
bool listParking () const
return whether to list parking vehicles
bool listTeleporting () const
return whether to list teleporting vehicles
void loadOnStartup ()
void removeChild (FXMDIChild *child)
removes the given child window from the list
void removeChild (FXMainWindow *child)
virtual void sendBlockingEvent (GUIEvent *event)
Sends an event from the application thread to the GUI and waits until it is handled.
virtual void setDelay (double delay)
Sets the delay of the parent application.
void setStatusBarText (const std::string &text)
void updateChildren ()
virtual ~GUIApplicationWindow ()
Destructor.
FOX-interactions
{
virtual void create ()
Creates the main window (required by FOX)
virtual void detach ()
Detaches the tool/menu bar.
Inter-thread event handling
virtual void eventOccured ()
void handleEvent_SimulationLoaded (GUIEvent *e)
void handleEvent_SimulationStep (GUIEvent *e)
void handleEvent_Message (GUIEvent *e)
void handleEvent_SimulationEnded (GUIEvent *e)
void handleEvent_Screenshot (GUIEvent *e)
FOX-callbacks
long onCmdOpenConfiguration (FXObject *, FXSelector, void *)
Called on menu File->Open Configuration.
long onCmdOpenNetwork (FXObject *, FXSelector, void *)
Called on menu File->Open Network.
long onCmdOpenShapes (FXObject *, FXSelector, void *)
Called on menu File->Load Shapes.
long onCmdReload (FXObject *, FXSelector, void *)
Called on reload.
long onCmdOpenRecent (FXObject *, FXSelector, void *)
Called on opening a recent file.
long onCmdClose (FXObject *, FXSelector, void *)
Called on menu File->Close.
long onCmdQuit (FXObject *, FXSelector, void *)
Called by FOX if the application shall be closed.
long onCmdEditChosen (FXObject *, FXSelector, void *)
Called on menu Edit->Edit Chosen.
long onCmdEditBreakpoints (FXObject *, FXSelector, void *)
Called on menu Edit->Edit Breakpoints.
long onCmdHelp (FXObject *sender, FXSelector sel, void *ptr)
called if the user selects help->Documentation
long onCmdNetedit (FXObject *, FXSelector, void *)
Called on menu Edit->Netedit.
long onCmdAppSettings (FXObject *, FXSelector, void *)
Opens the application settings menu (Settings->Application Settings...)
long onCmdGaming (FXObject *, FXSelector, void *)
Toggle gaming mode.
long onCmdFullScreen (FXObject *, FXSelector, void *)
Toggle full screen mode.
long onCmdListInternal (FXObject *, FXSelector, void *)
Toggle listing of internal structures.
long onCmdListParking (FXObject *, FXSelector, void *)
Toggle listing of parking vehicles.
long onCmdListTeleporting (FXObject *, FXSelector, void *)
Toggle listing of teleporting vehicles.
long onCmdAbout (FXObject *, FXSelector, void *)
Shows the about dialog.
long onCmdStart (FXObject *, FXSelector, void *)
Called on "play".
long onCmdStop (FXObject *, FXSelector, void *)
Called on "stop".
long onCmdStep (FXObject *, FXSelector, void *)
Called on "step".
long onCmdTimeToggle (FXObject *, FXSelector, void *)
Called on "time toggle".
long onCmdDelayToggle (FXObject *, FXSelector, void *)
Called on "delay toggle".
long onCmdNewView (FXObject *, FXSelector, void *)
Called if a new view shall be opened (2D view)
long onUpdOpen (FXObject *, FXSelector, void *)
Determines whether opening is enabled.
long onUpdReload (FXObject *, FXSelector, void *)
Determines whether reloading is enabled.
long onUpdOpenRecent (FXObject *, FXSelector, void *)
Determines whether opening a recent file is enabled.
long onUpdAddView (FXObject *, FXSelector, void *)
Determines whether adding a view is enabled.
long onUpdStart (FXObject *sender, FXSelector, void *ptr)
Determines whether "play" is enabled.
long onUpdStop (FXObject *, FXSelector, void *)
Determines whether "stop" is enabled.
long onUpdStep (FXObject *, FXSelector, void *)
Determines whether "step" is enabled.
long onUpdNeedsSimulation (FXObject *, FXSelector, void *)
Determines whether some buttons which require an active simulation may be shown.
long onCmdClearMsgWindow (FXObject *, FXSelector, void *)
Called if the message window shall be cleared.
long onCmdLocate (FXObject *, FXSelector, void *)
Called on menu commands from the Locator menu.
long onCmdShowStats (FXObject *, FXSelector, void *)
Called on commands from the statistic buttons.
long onLoadThreadEvent (FXObject *, FXSelector, void *)
Called on an event from the loading thread.
long onRunThreadEvent (FXObject *, FXSelector, void *)
Called on an event from the simulation thread.
long onClipboardRequest (FXObject *sender, FXSelector sel, void *ptr)
Somebody wants our clipped text.
long onKeyPress (FXObject *o, FXSelector sel, void *data)
handle keys
long onKeyRelease (FXObject *o, FXSelector sel, void *data)
Static Public Member Functions
static GUIMainWindow * getInstance ()
Protected Member Functions
virtual void addToWindowsMenu (FXMenuPane *)
virtual void buildToolBars ()
Builds the tool bar.
virtual void fillMenuBar ()
Builds the menu bar.
GUIApplicationWindow ()
FOX needs this for static members.
void setWindowSizeAndPos ()
perform initial window positioning and sizing according to user options / previous call
Protected Attributes
bool hadDependentBuild
SUMOTime myAlternateSimDelay
The alternate simulation delay for toggling.
bool myAmFullScreen
whether to show the window in full screen mode
bool myAmGaming
information whether the gui is currently in gaming mode
bool myAmLoading
information whether the gui is currently loading and the load-options shall be greyed out
FXFont * myBoldFont
Font used for popup-menu titles.
FXDockSite * myBottomDock
FXLabel * myCartesianCoordinate
Labels for the current cartesian and geo-coordinate.
FXHorizontalFrame * myCartesianFrame
std::string myConfigPattern
Input file pattern.
FXMenuPane * myControlMenu
FXMenuPane * myEditMenu
FXCondition myEventCondition
the semaphore when waiting for event completion
FXMutex myEventMutex
the mutex for the waiting semaphore
MFXEventQue< GUIEvent * > myEvents
List of got requests.
FXMenuPane * myFileMenu
the submenus
FXLabel * myGeoCoordinate
FXHorizontalFrame * myGeoFrame
FXGLVisual * myGLVisual
The gl-visual used.
bool myHaveNotifiedAboutSimEnd
whether the simulation end was already announced
FXMenuPane * myHelpMenu
FXEX::FXLCDLabel * myLCDLabel
the simulation step display
FXDockSite * myLeftDock
bool myListInternal
information whether the locator should list internal structures
bool myListParking
information whether the locator should list parking vehicles
bool myListTeleporting
information whether the locator should list teleporting vehicles
GUILoadThread * myLoadThread
FXEX::FXThreadEvent myLoadThreadEvent
io-event with the load-thread
FXMenuPane * myLocatorMenu
FXSplitter * myMainSplitter
The splitter that divides the main window into vies and the log window.
FXMDIClient * myMDIClient
The multi view panel.
FXMDIMenu * myMDIMenu
The menu used for the MDI-windows.
FXMenuBar * myMenuBar
The application menu bar.
FXToolBarShell * myMenuBarDrag
GUIMessageWindow * myMessageWindow
A window to display messages, warnings and error in.
std::string myName
FXRecentFiles myRecentConfigs
List of recent config files.
FXRecentFiles myRecentNets
List of recent nets.
FXDockSite * myRightDock
GUIRunThread * myRunThread
FXEX::FXThreadEvent myRunThreadEvent
io-event with the run-thread
FXMenuPane * mySelectByPermissions
FXMenuPane * mySettingsMenu
bool myShowTimeAsHMS
whether to show time as hour:minute:second
FXRealSpinDial * mySimDelayTarget
std::vector< FXButton * > myStatButtons
Buttons showing and running values and triggering statistic windows.
FXStatusBar * myStatusbar
The status bar.
std::vector< FXMDIChild * > mySubWindows
FXToolBar * myToolBar1
The application tool bar.
FXToolBar * myToolBar2
FXToolBar * myToolBar3
FXToolBar * myToolBar4
FXToolBar * myToolBar5
FXToolBarShell * myToolBarDrag1
for some menu detaching fun
FXToolBarShell * myToolBarDrag2
FXToolBarShell * myToolBarDrag3
FXToolBarShell * myToolBarDrag4
FXToolBarShell * myToolBarDrag5
FXDockSite * myTopDock
MFXMutex myTrackerLock
A lock to make the removal and addition of trackers secure.
std::vector< FXMainWindow * > myTrackerWindows
int myViewNumber
The current view number.
bool myWasStarted
FXMenuPane * myWindowsMenu
Static Protected Attributes
static GUIMainWindow * myInstance = 0
the singleton window instance
Private Member Functions
void checkGamingEvents ()
handles additional game-related events
void closeAllWindows ()
void loadConfigOrNet (const std::string &file, bool isNet)
GUISUMOAbstractView * openNewView (GUISUMOViewParent::ViewType vt=GUISUMOViewParent::VIEW_2D_OPENGL)
void updateTimeLCD (SUMOTime time)
updates the simulation time display
game related things
{
RandomDistributor< std::string > myJamSounds
RandomDistributor< std::string > myCollisionSounds
double myJamSoundTime
waiting time after which vehicles trigger jam sounds
int myPreviousCollisionNumber
FXEX::FXLCDLabel * myWaitingTimeLabel
performance indicators
FXEX::FXLCDLabel * myTimeLossLabel
SUMOTime myWaitingTime
SUMOTime myTimeLoss
FXToolBar * myToolBar6
FXToolBar * myToolBar7
FXToolBarShell * myToolBarDrag6
FXToolBarShell * myToolBarDrag7
static MTRand myGamingRNG
A random number generator used to choose a gaming sound.
Detailed Description
The main window of the SUMO-gui.
Beside views on the simulation, shown within a MDI-window, the main window may also have some further views (children) assigned which are stored within a separate list.
Definition at line 74 of file GUIApplicationWindow.h.
Constructor & Destructor Documentation
GUIApplicationWindow::GUIApplicationWindow (FXApp * a, const std::string & configPattern)
Constructor.
Parameters
[in] a The FOX application
[in] configPattern The pattern used for loading configurations
Definition at line 194 of file GUIApplicationWindow.cpp.
References GUIIconSubSys::initIcons().
GUIApplicationWindow::~GUIApplicationWindow () virtual
Destructor.
Definition at line 314 of file GUIApplicationWindow.cpp.
References GUIIconSubSys::close(), closeAllWindows(), MFXEventQue< T >::empty(), myControlMenu, myEditMenu, myEvents, myFileMenu, GUIMainWindow::myGLVisual, myHelpMenu, myLoadThread, myLocatorMenu, myRunThread, mySelectByPermissions, mySettingsMenu, myToolBarDrag1, myWindowsMenu, MFXEventQue< T >::pop(), GUIRunThread::prepareDestruction(), and MFXEventQue< T >::top().
GUIApplicationWindow::GUIApplicationWindow () inline protected
FOX needs this for static members.
Definition at line 300 of file GUIApplicationWindow.h.
References buildToolBars(), and fillMenuBar().
Member Function Documentation
void GUIMainWindow::addChild (FXMDIChild * child, bool updateOnSimStep = true) inherited
Adds a further child window to the list.
Definition at line 100 of file GUIMainWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by GUIParameterTableWindow::closeBuilding(), and GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow().
void GUIMainWindow::addChild (FXMainWindow * child, bool updateOnSimStep = true) inherited
Definition at line 115 of file GUIMainWindow.cpp.
References MFXMutex::lock(), GUIMainWindow::myTrackerLock, GUIMainWindow::myTrackerWindows, and MFXMutex::unlock().
void GUIApplicationWindow::addRecentFile (const FX::FXString & f, const bool isNet)
Definition at line 1564 of file GUIApplicationWindow.cpp.
References myRecentConfigs, and myRecentNets.
Referenced by GUILoadThread::run().
virtual void GUIApplicationWindow::addToWindowsMenu (FXMenuPane *) inline protected virtual
Definition at line 280 of file GUIApplicationWindow.h.
References checkGamingEvents(), closeAllWindows(), loadConfigOrNet(), openNewView(), updateTimeLCD(), and GUISUMOViewParent::VIEW_2D_OPENGL.
Referenced by fillMenuBar().
void GUIApplicationWindow::buildToolBars () protected virtual
Builds the tool bar.
game specific stuff
Definition at line 553 of file GUIApplicationWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignButtonToolbarText, GUIDesignSpinDial, GUIDesignToolBarGrip, GUIDesignToolBarShell1, GUIDesignToolBarShell2, GUIDesignToolBarShell3, ICON_MICROVIEW, ICON_OPEN_CONFIG, ICON_OPEN_NET, ICON_RELOAD, ICON_START, ICON_STEP, ICON_STOP, MID_DELAY_TOOGLE, MID_NEW_MICROVIEW, MID_NEW_OSGVIEW, MID_OPEN_CONFIG, MID_OPEN_NETWORK, MID_RELOAD, MID_SIMDELAY, MID_START, MID_STEP, MID_STOP, MID_TIME_TOOGLE, myLCDLabel, mySimDelayTarget, myTimeLossLabel, myToolBar1, myToolBar2, myToolBar3, myToolBar4, myToolBar5, myToolBar6, myToolBar7, myToolBarDrag1, myToolBarDrag2, myToolBarDrag3, myToolBarDrag4, myToolBarDrag5, myToolBarDrag6, myToolBarDrag7, GUIMainWindow::myTopDock, myWaitingTimeLabel, FXEX::FXLCDLabel::setGroove(), FXEX::FXLCDLabel::setHorizontal(), FX::FXRealSpinDial::setIncrements(), FX::FXRealSpinDial::setNumberFormat(), FX::FXRealSpinDial::setRange(), FXEX::FXLCDLabel::setText(), FXEX::FXLCDLabel::setThickness(), FX::FXRealSpinDial::setValue(), and FXEX::FXLCDLabel::setVertical().
Referenced by dependentBuild(), and GUIApplicationWindow().
void GUIApplicationWindow::checkGamingEvents () private
handles additional game-related events
Definition at line 1386 of file GUIApplicationWindow.cpp.
References DELTA_T, RandomDistributor< T >::get(), MSVehicleControl::getCollisionCount(), MSBaseVehicle::getEdge(), MSNet::getInstance(), MSVehicleType::getMaxSpeed(), RandomDistributor< T >::getOverallProb(), MSVehicle::getSpeed(), MSEdge::getSpeedLimit(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSVehicle::isOnRoad(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), MIN2(), myCollisionSounds, myGamingRNG, myJamSounds, myJamSoundTime, myPreviousCollisionNumber, myTimeLoss, myTimeLossLabel, myWaitingTime, myWaitingTimeLabel, SysUtils::runHiddenCommand(), FXEX::FXLCDLabel::setText(), SUMO_const_haltingSpeed, TIME2STEPS, time2string(), and TS.
Referenced by addToWindowsMenu(), and handleEvent_SimulationStep().
void GUIApplicationWindow::closeAllWindows () private
this method closes all windows and deletes the current simulation
Definition at line 1494 of file GUIApplicationWindow.cpp.
References GUIMessageWindow::addSeparator(), GUISelectedStorage::clear(), GUITexturesHelper::clearTextures(), GUIRunThread::deleteSim(), MFXUtils::getTitleText(), gSelected, MFXMutex::lock(), GUIMainWindow::myCartesianCoordinate, GUIMainWindow::myGeoCoordinate, myLCDLabel, myMessageWindow, myRunThread, myStatButtons, GUIMainWindow::mySubWindows, GUIMainWindow::myTrackerLock, GUIMainWindow::myTrackerWindows, FXEX::FXLCDLabel::setText(), MFXMutex::unlock(), and VERSION_STRING.
Referenced by addToWindowsMenu(), handleEvent_SimulationEnded(), handleEvent_SimulationLoaded(), loadConfigOrNet(), onCmdClose(), onCmdReload(), and ~GUIApplicationWindow().
void GUIApplicationWindow::create () virtual
Creates the main window (required by FOX)
Definition at line 278 of file GUIApplicationWindow.cpp.
References gCurrentFolder, OptionsCont::getOptions(), myAlternateSimDelay, GUIMainWindow::myCartesianFrame, myControlMenu, myEditMenu, myFileMenu, GUIMainWindow::myGeoFrame, myHelpMenu, myLocatorMenu, myMenuBarDrag, mySelectByPermissions, mySettingsMenu, myShowTimeAsHMS, myToolBarDrag1, myToolBarDrag2, myToolBarDrag3, myToolBarDrag4, myToolBarDrag5, myToolBarDrag6, myToolBarDrag7, myWindowsMenu, and GUIMainWindow::setWindowSizeAndPos().
void GUIApplicationWindow::dependentBuild ()
Definition at line 215 of file GUIApplicationWindow.cpp.
References buildToolBars(), fillMenuBar(), GUIIconSubSys::getIcon(), MFXUtils::getTitleText(), GUIDesignBar, GUIDesignHorizontalFrameStatusBar, GUIDesignMDIButtonLeft, GUIDesignMDIButtonRight, GUIDesignSplitter, GUIDesignSplitterMDI, GUIDesignStatusBar, GUIDesignToolBarGrip, GUIDesignToolBarShell3, hadDependentBuild, ICON_APP, ICON_GREENEDGE, ICON_GREENPERSON, ICON_GREENVEHICLE, ID_LOADTHREAD_EVENT, ID_RUNTHREAD_EVENT, MID_SHOWPERSONSTATS, MID_SHOWVEHSTATS, MID_WINDOW, GUIMainWindow::myCartesianCoordinate, GUIMainWindow::myCartesianFrame, myEvents, GUIMainWindow::myGeoCoordinate, GUIMainWindow::myGeoFrame, myLoadThread, myLoadThreadEvent, myMainSplitter, GUIMainWindow::myMDIClient, myMDIMenu, myMenuBar, myMenuBarDrag, myMessageWindow, myRunThread, myRunThreadEvent, mySimDelayTarget, myStatButtons, GUIMainWindow::myStatusbar, myToolBar6, myToolBar7, GUIMainWindow::myTopDock, FXEX::FXBaseObject::setSelector(), FXEX::FXBaseObject::setTarget(), and VERSION_STRING.
Referenced by main().
void GUIApplicationWindow::detach () virtual
Detaches the tool/menu bar.
Definition at line 346 of file GUIApplicationWindow.cpp.
References myMenuBarDrag, and myToolBarDrag1.
void GUIApplicationWindow::eventOccured () virtual
Implements MFXInterThreadEventClient.
Definition at line 1172 of file GUIApplicationWindow.cpp.
References MFXEventQue< T >::empty(), EVENT_ERROR_OCCURED, EVENT_MESSAGE_OCCURED, EVENT_SCREENSHOT, EVENT_SIMULATION_ENDED, EVENT_SIMULATION_LOADED, EVENT_SIMULATION_STEP, EVENT_STATUS_OCCURED, EVENT_WARNING_OCCURED, GUIEvent::getOwnType(), handleEvent_Message(), handleEvent_Screenshot(), handleEvent_SimulationEnded(), handleEvent_SimulationLoaded(), handleEvent_SimulationStep(), myEvents, myRunThread, myToolBar2, myToolBar3, MFXEventQue< T >::pop(), GUIRunThread::simulationAvailable(), and MFXEventQue< T >::top().
Referenced by onLoadThreadEvent(), and onRunThreadEvent().
void GUIApplicationWindow::fillMenuBar () protected virtual
Builds the menu bar.
Definition at line 354 of file GUIApplicationWindow.cpp.
References addToWindowsMenu(), GUIIconSubSys::getIcon(), MSGlobals::gUseMesoSim, ICON_APP, ICON_CLOSE, ICON_FLAG, ICON_LOCATEADD, ICON_LOCATEEDGE, ICON_LOCATEJUNCTION, ICON_LOCATEPERSON, ICON_LOCATEPOI, ICON_LOCATEPOLY, ICON_LOCATETLS, ICON_LOCATEVEHICLE, ICON_OPEN_CONFIG, ICON_OPEN_NET, ICON_OPEN_SHAPES, ICON_RELOAD, ICON_START, ICON_STEP, ICON_STOP, ICON_WINDOWS_CASCADE, ICON_WINDOWS_TILE_HORI, ICON_WINDOWS_TILE_VERT, GUIMainWindow::listParking(), MID_ABOUT, MID_APPSETTINGS, MID_CLEARMESSAGEWINDOW, MID_CLOSE, MID_EDIT_BREAKPOINTS, MID_EDITCHOSEN, MID_FULLSCREEN, MID_GAMING, MID_HELP, MID_LISTINTERNAL, MID_LISTPARKING, MID_LISTTELEPORTING, MID_LOCATEADD, MID_LOCATEEDGE, MID_LOCATEJUNCTION, MID_LOCATEPERSON, MID_LOCATEPOI, MID_LOCATEPOLY, MID_LOCATETLS, MID_LOCATEVEHICLE, MID_NETEDIT, MID_OPEN_CONFIG, MID_OPEN_NETWORK, MID_OPEN_SHAPES, MID_QUIT, MID_RECENTFILE, MID_RELOAD, MID_START, MID_STEP, MID_STOP, myControlMenu, myEditMenu, myFileMenu, myHelpMenu, GUIMainWindow::myListParking, myLocatorMenu, GUIMainWindow::myMDIClient, myMenuBar, myMessageWindow, myRecentConfigs, myRecentNets, mySelectByPermissions, mySettingsMenu, GUIMainWindow::myStatusbar, myToolBar3, myToolBar4, myWindowsMenu, and SumoVehicleClassStrings.
Referenced by dependentBuild(), and GUIApplicationWindow().
GUISUMOAbstractView * GUIMainWindow::getActiveView () const inherited
get the active view or 0
Definition at line 199 of file GUIMainWindow.cpp.
References GUIGlChildWindow::getView(), and GUIMainWindow::myMDIClient.
Referenced by GUIVehicle::drawOutsideNetwork(), and GUIMainWindow::sendBlockingEvent().
FXFont * GUIMainWindow::getBoldFont () inherited
Definition at line 153 of file GUIMainWindow.cpp.
References GUIMainWindow::myBoldFont.
Referenced by GUIGlObject::buildPopupHeader(), GNEDeleteFrame::createPopUpMenu(), and GNEInspectorFrame::createPopUpMenu().
FXGLCanvas * GUIApplicationWindow::getBuildGLCanvas () const virtual
Implements GUIMainWindow.
Definition at line 1483 of file GUIApplicationWindow.cpp.
References GUIGlChildWindow::getBuildGLCanvas(), and GUIMainWindow::myMDIClient.
Referenced by openNewView().
FXLabel & GUIMainWindow::getCartesianLabel () inherited
Definition at line 178 of file GUIMainWindow.cpp.
References GUIMainWindow::myCartesianCoordinate.
Referenced by GUIMainWindow::setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
SUMOTime GUIApplicationWindow::getCurrentSimTime () const virtual
Implements GUIMainWindow.
Definition at line 1544 of file GUIApplicationWindow.cpp.
References MSNet::getCurrentTimeStep(), GUIRunThread::getNet(), and myRunThread.
FXCursor * GUIApplicationWindow::getDefaultCursor ()
Definition at line 1538 of file GUIApplicationWindow.cpp.
virtual double GUIApplicationWindow::getDelay () const inline virtual
Returns the simulation delay.
Returns
delay in milliseconds
Reimplemented from GUIMainWindow.
Definition at line 264 of file GUIApplicationWindow.h.
References FX::FXRealSpinDial::getValue(), and mySimDelayTarget.
FXLabel & GUIMainWindow::getGeoLabel () inherited
Definition at line 184 of file GUIMainWindow.cpp.
References GUIMainWindow::myGeoCoordinate.
Referenced by GUIMainWindow::setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
FXGLVisual * GUIMainWindow::getGLVisual () const inherited
Definition at line 172 of file GUIMainWindow.cpp.
References GUIMainWindow::myGLVisual.
Referenced by GUISUMOViewParent::init().
GUIMainWindow * GUIMainWindow::getInstance (void) static inherited
Definition at line 190 of file GUIMainWindow.cpp.
References GUIMainWindow::myInstance.
Referenced by GUIVehicle::drawOutsideNetwork(), TraCIServerAPI_GUI::getNamedView(), GUITexturesHelper::getTextureID(), GUIMainWindow::listTeleporting(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), and GUIMessageWindow::setCursorPos().
FXMDIChild * GUIMainWindow::getViewByID (const std::string & id) const inherited
Definition at line 142 of file GUIMainWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by TraCIServerAPI_GUI::getNamedView(), and GUIMessageWindow::setCursorPos().
std::vector< std::string > GUIMainWindow::getViewIDs () const inherited
Definition at line 132 of file GUIMainWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by TraCIServerAPI_GUI::processGet(), and GUIMessageWindow::setCursorPos().
void GUIApplicationWindow::handleEvent_Message (GUIEvent * e)
Definition at line 1337 of file GUIApplicationWindow.cpp.
References GUIMessageWindow::appendMsg(), EVENT_STATUS_OCCURED, GUIEvent_Message::getMsg(), GUIEvent::getOwnType(), myMessageWindow, and setStatusBarText().
Referenced by eventOccured().
void GUIApplicationWindow::handleEvent_Screenshot (GUIEvent * e)
Definition at line 1373 of file GUIApplicationWindow.cpp.
References GUISUMOAbstractView::makeSnapshot(), myEventCondition, myEventMutex, GUIEvent_Screenshot::myFile, GUIEvent_Screenshot::myView, and WRITE_WARNING.
Referenced by eventOccured().
void GUIApplicationWindow::handleEvent_SimulationEnded (GUIEvent * e)
Definition at line 1348 of file GUIApplicationWindow.cpp.
References closeAllWindows(), GUIGlobals::gDemoAutoReload, GUIEvent_SimulationEnded::getReason(), MSNet::getStateMessage(), GUIEvent_SimulationEnded::getTimeStep(), GUIGlobals::gQuitOnEnd, myHaveNotifiedAboutSimEnd, onCmdReload(), onCmdStop(), MSNet::SIMSTATE_ERROR_IN_SIM, MSNet::SIMSTATE_LOADING, text(), and time2string().
Referenced by eventOccured().
void GUIApplicationWindow::handleEvent_SimulationLoaded (GUIEvent * e)
Definition at line 1210 of file GUIApplicationWindow.cpp.
References GUISUMOAbstractView::addDecals(), GUISettingsHandler::addSettings(), GUISettingsHandler::applyViewport(), closeAllWindows(), GUIRunThread::getBreakpointLock(), GUIRunThread::getBreakpoints(), GUISettingsHandler::getBreakpoints(), GUISettingsHandler::getDecals(), GUISettingsHandler::getDelay(), GUISettingsHandler::getEventDistribution(), GUISettingsHandler::getJamSoundTime(), OptionsCont::getOptions(), MFXUtils::getTitleText(), GUISettingsHandler::getViewType(), GUIGlobals::gQuitOnEnd, GUIGlobals::gRunAfterLoad, GUIRunThread::init(), GUIMainWindow::isGaming(), myAmLoading, GUIEvent_SimulationLoaded::myBegin, myCollisionSounds, GUIEvent_SimulationLoaded::myEnd, GUIEvent_SimulationLoaded::myFile, myHaveNotifiedAboutSimEnd, myJamSounds, myJamSoundTime, myLCDLabel, GUIEvent_SimulationLoaded::myNet, GUIEvent_SimulationLoaded::myOsgView, myRunThread, GUIEvent_SimulationLoaded::mySettingsFiles, mySimDelayTarget, myStatButtons, myViewNumber, myWasStarted, onCmdGaming(), onCmdStart(), openNewView(), GUISettingsHandler::setSnapshots(), setStatusBarText(), FXEX::FXLCDLabel::setText(), FX::FXRealSpinDial::setValue(), GUIRunThread::simulationIsStartable(), VERSION_STRING, GUISUMOViewParent::VIEW_2D_OPENGL, and GUISUMOViewParent::VIEW_3D_OSG.
Referenced by eventOccured().
void GUIApplicationWindow::handleEvent_SimulationStep (GUIEvent * e)
Definition at line 1299 of file GUIApplicationWindow.cpp.
References checkGamingEvents(), GUINet::getContainerControl(), MSNet::getCurrentTimeStep(), GUIIconSubSys::getIcon(), MSNet::getInsertionControl(), GUIRunThread::getNet(), GUINet::getPersonControl(), MSTransportableControl::getRunningNumber(), MSVehicleControl::getRunningVehicleNo(), MSNet::getVehicleControl(), MSInsertionControl::getWaitingVehicleNo(), MSNet::hasContainers(), MSNet::hasPersons(), ICON_GREENVEHICLE, ICON_YELLOWVEHICLE, GUIMainWindow::myAmGaming, myRunThread, myStatButtons, GUIRunThread::simulationIsStartable(), toString(), GUIMainWindow::updateChildren(), and updateTimeLCD().
Referenced by eventOccured().
bool GUIMainWindow::isGaming () const inline inherited
return whether the gui is in gaming mode
Definition at line 85 of file GUIMainWindow.h.
References GUIMainWindow::myAmGaming.
Referenced by handleEvent_SimulationLoaded(), GUISUMOViewParent::init(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseWheel(), GUISUMOAbstractView::onRightBtnRelease(), and GUIViewTraffic::setColorScheme().
bool GUIMainWindow::listInternal () const inline inherited
return whether to list internal structures
Definition at line 90 of file GUIMainWindow.h.
References GUIMainWindow::myListInternal.
Referenced by GUISUMOViewParent::onCmdLocate().
bool GUIMainWindow::listParking () const inline inherited
return whether to list parking vehicles
Definition at line 95 of file GUIMainWindow.h.
References GUIMainWindow::myListParking.
Referenced by fillMenuBar(), and GUISUMOViewParent::onCmdLocate().
bool GUIMainWindow::listTeleporting () const inline inherited
return whether to list teleporting vehicles
Definition at line 100 of file GUIMainWindow.h.
References GUIMainWindow::getInstance(), and GUIMainWindow::myListTeleporting.
Referenced by GUISUMOViewParent::onCmdLocate().
void GUIApplicationWindow::loadConfigOrNet (const std::string & file, bool isNet) private
starts to load a simulation
Definition at line 1437 of file GUIApplicationWindow.cpp.
References closeAllWindows(), gSchemeStorage, GUILoadThread::loadConfigOrNet(), myAmLoading, myLoadThread, GUICompleteSchemeStorage::saveViewport(), and setStatusBarText().
Referenced by addToWindowsMenu(), loadOnStartup(), onCmdOpenConfiguration(), onCmdOpenNetwork(), and onCmdOpenRecent().
void GUIApplicationWindow::loadOnStartup ()
Definition at line 1550 of file GUIApplicationWindow.cpp.
References loadConfigOrNet().
Referenced by main().
long GUIApplicationWindow::onClipboardRequest (FXObject * sender, FXSelector sel, void * ptr)
Somebody wants our clipped text.
Definition at line 1149 of file GUIApplicationWindow.cpp.
References GUIUserIO::clipped.
long GUIApplicationWindow::onCmdAbout (FXObject * , FXSelector , void *)
Shows the about dialog.
Definition at line 1141 of file GUIApplicationWindow.cpp.
References GUIDialog_AboutSUMO::create().
long GUIApplicationWindow::onCmdAppSettings (FXObject * , FXSelector , void *)
Opens the application settings menu (Settings->Application Settings...)
Definition at line 1011 of file GUIApplicationWindow.cpp.
long GUIApplicationWindow::onCmdClearMsgWindow (FXObject * , FXSelector , void *)
Called if the message window shall be cleared.
Definition at line 942 of file GUIApplicationWindow.cpp.
References GUIMessageWindow::clear(), and myMessageWindow.
long GUIApplicationWindow::onCmdClose (FXObject * , FXSelector , void *)
Called on menu File->Close.
Definition at line 835 of file GUIApplicationWindow.cpp.
References closeAllWindows().
long GUIApplicationWindow::onCmdDelayToggle (FXObject * , FXSelector , void *)
Called on "delay toggle".
Definition at line 933 of file GUIApplicationWindow.cpp.
References FX::FXRealSpinDial::getValue(), myAlternateSimDelay, mySimDelayTarget, and FX::FXRealSpinDial::setValue().
long GUIApplicationWindow::onCmdEditBreakpoints (FXObject * , FXSelector , void *)
Called on menu Edit->Edit Breakpoints.
Definition at line 697 of file GUIApplicationWindow.cpp.
References GUIRunThread::getBreakpointLock(), GUIRunThread::getBreakpoints(), myRunThread, and GUIDialog_Breakpoints::show().
long GUIApplicationWindow::onCmdEditChosen (FXObject * menu, FXSelector , void *)
Called on menu Edit->Edit Chosen.
Definition at line 662 of file GUIApplicationWindow.cpp.
References MSEdge::getAllEdges(), GUIGlObject::getGlID(), MSLane::getPermissions(), GUIGlChildWindow::getView(), GUISUMOAbstractView::getVisualisationSettings(), gSelected, GUIVisualizationSettings::laneColorer, myAmLoading, GUIMainWindow::myMDIClient, myRunThread, GUISelectedStorage::select(), GUIPropertySchemeStorage< T >::setActive(), GUIRunThread::simulationAvailable(), SumoVehicleClassStrings, and GUIMainWindow::updateChildren().
long GUIApplicationWindow::onCmdFullScreen (FXObject * , FXSelector , void *)
Toggle full screen mode.
Definition at line 1061 of file GUIApplicationWindow.cpp.
References myAmFullScreen, GUIMainWindow::myAmGaming, GUIMainWindow::myMDIClient, myMenuBar, myMessageWindow, GUIMainWindow::myStatusbar, myToolBar1, myToolBar2, myToolBar3, myToolBar4, myToolBar5, myToolBar6, myToolBar7, onCmdGaming(), and GUISUMOViewParent::setToolBarVisibility().
long GUIApplicationWindow::onCmdGaming (FXObject * , FXSelector , void *)
Toggle gaming mode.
Definition at line 1020 of file GUIApplicationWindow.cpp.
References GUIVisualizationSettings::gaming, GUICompleteSchemeStorage::getDefault(), MFXUtils::getFXColor(), RGBColor::GREEN, gSchemeStorage, myAmFullScreen, GUIMainWindow::myAmGaming, myLCDLabel, GUIMainWindow::myMDIClient, myMenuBar, myMessageWindow, GUIMainWindow::myStatusbar, myTimeLossLabel, myToolBar1, myToolBar2, myToolBar4, myToolBar5, myToolBar6, myToolBar7, myWaitingTimeLabel, RGBColor::RED, FXEX::FXLCDLabel::setFgColor(), and GUISUMOViewParent::setToolBarVisibility().
Referenced by handleEvent_SimulationLoaded(), and onCmdFullScreen().
long GUIApplicationWindow::onCmdHelp (FXObject * sender, FXSelector sel, void * ptr)
called if the user selects help->Documentation
Definition at line 706 of file GUIApplicationWindow.cpp.
References FXLinkLabel::fxexecute().
long GUIApplicationWindow::onCmdListInternal (FXObject * , FXSelector , void *)
Toggle listing of internal structures.
Definition at line 1105 of file GUIApplicationWindow.cpp.
References GUIMainWindow::myListInternal.
long GUIApplicationWindow::onCmdListParking (FXObject * , FXSelector , void *)
Toggle listing of parking vehicles.
Definition at line 1112 of file GUIApplicationWindow.cpp.
References GUIMainWindow::myListParking.
long GUIApplicationWindow::onCmdListTeleporting (FXObject * , FXSelector , void *)
Toggle listing of teleporting vehicles.
Definition at line 1118 of file GUIApplicationWindow.cpp.
References GUIMainWindow::myListTeleporting.
long GUIApplicationWindow::onCmdLocate (FXObject * , FXSelector sel, void *)
Called on menu commands from the Locator menu.
Definition at line 989 of file GUIApplicationWindow.cpp.
References GUIMainWindow::myMDIClient, and GUISUMOViewParent::onCmdLocate().
long GUIApplicationWindow::onCmdNetedit (FXObject * , FXSelector , void *)
Called on menu Edit->Netedit.
Definition at line 713 of file GUIApplicationWindow.cpp.
References GUISUMOAbstractView::getChanger(), OptionsCont::getOptions(), OptionsCont::getString(), GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZPos(), FileHelpers::isReadable(), GUIMainWindow::mySubWindows, SysUtils::runHiddenCommand(), and WRITE_MESSAGE.
long GUIApplicationWindow::onCmdNewView (FXObject * , FXSelector , void *)
Called if a new view shall be opened (2D view)
Definition at line 1125 of file GUIApplicationWindow.cpp.
References openNewView(), GUISUMOViewParent::VIEW_2D_OPENGL, and GUISUMOViewParent::VIEW_3D_OSG.
long GUIApplicationWindow::onCmdOpenConfiguration (FXObject * , FXSelector , void *)
Called on menu File->Open Configuration.
Definition at line 748 of file GUIApplicationWindow.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, loadConfigOrNet(), myConfigPattern, and myRecentConfigs.
long GUIApplicationWindow::onCmdOpenNetwork (FXObject * , FXSelector , void *)
Called on menu File->Open Network.
Definition at line 768 of file GUIApplicationWindow.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, loadConfigOrNet(), and myRecentNets.
long GUIApplicationWindow::onCmdOpenRecent (FXObject * sender, FXSelector , void * data)
Called on opening a recent file.
Definition at line 823 of file GUIApplicationWindow.cpp.
References loadConfigOrNet(), myAmLoading, myRecentNets, and GUIMainWindow::myStatusbar.
long GUIApplicationWindow::onCmdOpenShapes (FXObject * , FXSelector , void *)
Called on menu File->Load Shapes.
Definition at line 788 of file GUIApplicationWindow.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), GUIRunThread::getNet(), MSNet::getShapeContainer(), ICON_EMPTY, myRunThread, XMLSubSys::runParser(), and WRITE_MESSAGE.
long GUIApplicationWindow::onCmdQuit (FXObject * , FXSelector , void *)
Called by FOX if the application shall be closed.
Called either by FileMenu->Quit, the normal close-menu or SIGINT
Definition at line 645 of file GUIApplicationWindow.cpp.
References gCurrentFolder, myAlternateSimDelay, myAmFullScreen, and myShowTimeAsHMS.
long GUIApplicationWindow::onCmdReload (FXObject * , FXSelector , void *)
Called on reload.
Definition at line 811 of file GUIApplicationWindow.cpp.
References closeAllWindows(), myAmLoading, myLoadThread, and setStatusBarText().
Referenced by handleEvent_SimulationEnded().
long GUIApplicationWindow::onCmdShowStats (FXObject * , FXSelector , void *)
Called on commands from the statistic buttons.
Definition at line 1001 of file GUIApplicationWindow.cpp.
References GUINet::getGUIInstance(), GUINet::getParameterWindow(), GUIGlChildWindow::getView(), and GUIMainWindow::myMDIClient.
long GUIApplicationWindow::onCmdStart (FXObject * , FXSelector , void *)
Called on "play".
Definition at line 880 of file GUIApplicationWindow.cpp.
References GUIRunThread::begin(), myRunThread, GUIMainWindow::myStatusbar, myWasStarted, GUIRunThread::resume(), and GUIRunThread::simulationAvailable().
Referenced by handleEvent_SimulationLoaded().
long GUIApplicationWindow::onCmdStep (FXObject * , FXSelector , void *)
Called on "step".
Definition at line 906 of file GUIApplicationWindow.cpp.
References GUIRunThread::begin(), myRunThread, GUIMainWindow::myStatusbar, myWasStarted, GUIRunThread::simulationAvailable(), and GUIRunThread::singleStep().
long GUIApplicationWindow::onCmdStop (FXObject * , FXSelector , void *)
Called on "stop".
Definition at line 898 of file GUIApplicationWindow.cpp.
References myRunThread, and GUIRunThread::stop().
Referenced by handleEvent_SimulationEnded().
long GUIApplicationWindow::onCmdTimeToggle (FXObject * , FXSelector , void *)
Called on "time toggle".
Definition at line 923 of file GUIApplicationWindow.cpp.
References MSNet::getCurrentTimeStep(), GUIRunThread::getNet(), myRunThread, myShowTimeAsHMS, GUIRunThread::simulationAvailable(), and updateTimeLCD().
long GUIApplicationWindow::onKeyPress (FXObject * o, FXSelector sel, void * data)
handle keys
Definition at line 1608 of file GUIApplicationWindow.cpp.
References GUIMainWindow::myMDIClient, and GUISUMOViewParent::onKeyPress().
long GUIApplicationWindow::onKeyRelease (FXObject * o, FXSelector sel, void * data)
Definition at line 1621 of file GUIApplicationWindow.cpp.
References GUIMainWindow::myMDIClient, and GUISUMOViewParent::onKeyRelease().
long GUIApplicationWindow::onLoadThreadEvent (FXObject * , FXSelector , void *)
Called on an event from the loading thread.
Definition at line 1158 of file GUIApplicationWindow.cpp.
References eventOccured().
long GUIApplicationWindow::onRunThreadEvent (FXObject * , FXSelector , void *)
Called on an event from the simulation thread.
Definition at line 1165 of file GUIApplicationWindow.cpp.
References eventOccured().
long GUIApplicationWindow::onUpdAddView (FXObject * sender, FXSelector , void * ptr)
Determines whether adding a view is enabled.
Definition at line 870 of file GUIApplicationWindow.cpp.
References myAmLoading, myRunThread, and GUIRunThread::simulationAvailable().
long GUIApplicationWindow::onUpdNeedsSimulation (FXObject * sender, FXSelector , void * ptr)
Determines whether some buttons which require an active simulation may be shown.
Definition at line 979 of file GUIApplicationWindow.cpp.
References myAmLoading, myRunThread, and GUIRunThread::simulationAvailable().
long GUIApplicationWindow::onUpdOpen (FXObject * sender, FXSelector , void * ptr)
Determines whether opening is enabled.
Definition at line 842 of file GUIApplicationWindow.cpp.
References myAmLoading.
long GUIApplicationWindow::onUpdOpenRecent (FXObject * sender, FXSelector , void * ptr)
Determines whether opening a recent file is enabled.
Definition at line 861 of file GUIApplicationWindow.cpp.
References myAmLoading.
long GUIApplicationWindow::onUpdReload (FXObject * sender, FXSelector , void * ptr)
Determines whether reloading is enabled.
Definition at line 851 of file GUIApplicationWindow.cpp.
References GUILoadThread::getFileName(), myAmLoading, and myLoadThread.
long GUIApplicationWindow::onUpdStart (FXObject * sender, FXSelector , void * ptr)
Determines whether "play" is enabled.
Definition at line 949 of file GUIApplicationWindow.cpp.
References myAmLoading, myRunThread, and GUIRunThread::simulationIsStartable().
long GUIApplicationWindow::onUpdStep (FXObject * sender, FXSelector , void * ptr)
Determines whether "step" is enabled.
Definition at line 969 of file GUIApplicationWindow.cpp.
References myAmLoading, myRunThread, and GUIRunThread::simulationIsStepable().
long GUIApplicationWindow::onUpdStop (FXObject * sender, FXSelector , void * ptr)
Determines whether "stop" is enabled.
Definition at line 959 of file GUIApplicationWindow.cpp.
References myAmLoading, myRunThread, and GUIRunThread::simulationIsStopable().
GUISUMOAbstractView * GUIApplicationWindow::openNewView (GUISUMOViewParent::ViewType vt = GUISUMOViewParent::VIEW_2D_OPENGL) private
opens a new simulation display
Definition at line 1449 of file GUIApplicationWindow.cpp.
References GUISUMOAbstractView::copyViewportTo(), GUIGlChildWindow::create(), getBuildGLCanvas(), GUIIconSubSys::getIcon(), GUIRunThread::getNet(), GUIGlChildWindow::getView(), ICON_APP, GUISUMOViewParent::init(), GUIMainWindow::myMDIClient, myMDIMenu, myRunThread, GUIMainWindow::myStatusbar, myViewNumber, GUIRunThread::simulationAvailable(), and toString().
Referenced by addToWindowsMenu(), handleEvent_SimulationLoaded(), and onCmdNewView().
void GUIMainWindow::removeChild (FXMDIChild * child) inherited
removes the given child window from the list
Definition at line 106 of file GUIMainWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by GNEViewParent::~GNEViewParent(), GUIDialog_Breakpoints::~GUIDialog_Breakpoints(), GUIDialog_GLChosenEditor::~GUIDialog_GLChosenEditor(), GUIDialog_GLObjChooser::~GUIDialog_GLObjChooser(), GUIParameterTableWindow::~GUIParameterTableWindow(), GUIParameterTracker::~GUIParameterTracker(), GUISUMOViewParent::~GUISUMOViewParent(), and GUITLLogicPhasesTrackerWindow::~GUITLLogicPhasesTrackerWindow().
void GUIMainWindow::removeChild (FXMainWindow * child) inherited
Definition at line 123 of file GUIMainWindow.cpp.
References MFXMutex::lock(), GUIMainWindow::myTrackerLock, GUIMainWindow::myTrackerWindows, and MFXMutex::unlock().
void GUIApplicationWindow::sendBlockingEvent (GUIEvent * event) virtual
Sends an event from the application thread to the GUI and waits until it is handled.
Parameters
event the event to send
Reimplemented from GUIMainWindow.
Definition at line 1634 of file GUIApplicationWindow.cpp.
References MFXEventQue< T >::add(), myEventCondition, myEventMutex, myEvents, myRunThreadEvent, and FXEX::FXThreadEvent::signal().
Referenced by setDelay().
virtual void GUIApplicationWindow::setDelay (double delay) inline virtual
Sets the delay of the parent application.
Reimplemented from GUIMainWindow.
Definition at line 270 of file GUIApplicationWindow.h.
References mySimDelayTarget, sendBlockingEvent(), and FX::FXRealSpinDial::setValue().
void GUIApplicationWindow::setStatusBarText (const std::string & text) virtual
Reimplemented from GUIMainWindow.
Definition at line 1556 of file GUIApplicationWindow.cpp.
References GUIMainWindow::myStatusbar.
Referenced by handleEvent_Message(), handleEvent_SimulationLoaded(), loadConfigOrNet(), and onCmdReload().
void GUIMainWindow::setWindowSizeAndPos () protected inherited
perform initial window positioning and sizing according to user options / previous call
Definition at line 208 of file GUIMainWindow.cpp.
References TplCheck::_str2int(), TplConvert::_str2int(), OptionsCont::getOptions(), OptionsCont::getStringVector(), OptionsCont::isSet(), MAX2(), MIN2(), and WRITE_ERROR.
Referenced by GNEApplicationWindow::create(), create(), and GUIMainWindow::GUIMainWindow().
void GUIMainWindow::updateChildren () inherited
Definition at line 159 of file GUIMainWindow.cpp.
References MFXMutex::lock(), MID_SIMSTEP, GUIMainWindow::myMDIClient, GUIMainWindow::myTrackerLock, GUIMainWindow::myTrackerWindows, and MFXMutex::unlock().
Referenced by handleEvent_SimulationStep(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdChangeOption(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdChangeOption(), GUIDialog_GLChosenEditor::onCmdClear(), GUIDialog_GLChosenEditor::onCmdDeselect(), onCmdEditChosen(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdPreDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdUserDef(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdUserDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdPreDef(), GUICalibrator::GUIManip_Calibrator::onUpdPreDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdUserDef(), GUICalibrator::GUIManip_Calibrator::onUpdUserDef(), and GUITriggeredRerouter::GUIManip_TriggeredRerouter::onUpdUserDef().
void GUIApplicationWindow::updateTimeLCD (SUMOTime time) private
updates the simulation time display
Definition at line 1574 of file GUIApplicationWindow.cpp.
References DELTA_T, GUIRunThread::getSimEndTime(), GUIMainWindow::myAmGaming, myLCDLabel, myRunThread, myShowTimeAsHMS, and FXEX::FXLCDLabel::setText().
Referenced by addToWindowsMenu(), handleEvent_SimulationStep(), and onCmdTimeToggle().
Field Documentation
bool GUIApplicationWindow::hadDependentBuild protected
Definition at line 382 of file GUIApplicationWindow.h.
Referenced by dependentBuild().
SUMOTime GUIApplicationWindow::myAlternateSimDelay protected
The alternate simulation delay for toggling.
Definition at line 350 of file GUIApplicationWindow.h.
Referenced by create(), onCmdDelayToggle(), and onCmdQuit().
bool GUIApplicationWindow::myAmFullScreen protected
whether to show the window in full screen mode
Definition at line 388 of file GUIApplicationWindow.h.
Referenced by onCmdFullScreen(), onCmdGaming(), and onCmdQuit().
bool GUIMainWindow::myAmGaming protected inherited
information whether the gui is currently in gaming mode
Definition at line 152 of file GUIMainWindow.h.
Referenced by handleEvent_SimulationStep(), GUIMainWindow::isGaming(), onCmdFullScreen(), onCmdGaming(), and updateTimeLCD().
bool GUIApplicationWindow::myAmLoading protected
information whether the gui is currently loading and the load-options shall be greyed out
Definition at line 326 of file GUIApplicationWindow.h.
Referenced by handleEvent_SimulationLoaded(), loadConfigOrNet(), onCmdEditChosen(), onCmdOpenRecent(), onCmdReload(), onUpdAddView(), onUpdNeedsSimulation(), onUpdOpen(), onUpdOpenRecent(), onUpdReload(), onUpdStart(), onUpdStep(), and onUpdStop().
FXFont* GUIMainWindow::myBoldFont protected inherited
Font used for popup-menu titles.
Definition at line 134 of file GUIMainWindow.h.
Referenced by GUIMainWindow::getBoldFont(), GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
FXDockSite * GUIMainWindow::myBottomDock protected inherited
Definition at line 149 of file GUIMainWindow.h.
Referenced by GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
FXLabel* GUIMainWindow::myCartesianCoordinate protected inherited
Labels for the current cartesian and geo-coordinate.
Definition at line 143 of file GUIMainWindow.h.
Referenced by closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GNEApplicationWindow::dependentBuild(), dependentBuild(), and GUIMainWindow::getCartesianLabel().
FXHorizontalFrame* GUIMainWindow::myCartesianFrame protected inherited
Definition at line 144 of file GUIMainWindow.h.
Referenced by GNEApplicationWindow::create(), create(), GNEApplicationWindow::dependentBuild(), and dependentBuild().
RandomDistributor<std::string> GUIApplicationWindow::myCollisionSounds protected
Definition at line 402 of file GUIApplicationWindow.h.
Referenced by checkGamingEvents(), and handleEvent_SimulationLoaded().
std::string GUIApplicationWindow::myConfigPattern protected
Input file pattern.
Definition at line 380 of file GUIApplicationWindow.h.
Referenced by onCmdOpenConfiguration().
FXMenuPane * GUIApplicationWindow::myControlMenu protected
Definition at line 329 of file GUIApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GUIApplicationWindow().
FXMenuPane * GUIApplicationWindow::myEditMenu protected
Definition at line 329 of file GUIApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GUIApplicationWindow().
FXCondition GUIApplicationWindow::myEventCondition protected
the semaphore when waiting for event completion
Definition at line 397 of file GUIApplicationWindow.h.
Referenced by handleEvent_Screenshot(), and sendBlockingEvent().
FXMutex GUIApplicationWindow::myEventMutex protected
the mutex for the waiting semaphore
Definition at line 394 of file GUIApplicationWindow.h.
Referenced by handleEvent_Screenshot(), and sendBlockingEvent().
MFXEventQue<GUIEvent*> GUIApplicationWindow::myEvents protected
List of got requests.
Definition at line 353 of file GUIApplicationWindow.h.
Referenced by dependentBuild(), eventOccured(), sendBlockingEvent(), and ~GUIApplicationWindow().
FXMenuPane* GUIApplicationWindow::myFileMenu protected
the submenus
Definition at line 329 of file GUIApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GUIApplicationWindow().
MTRand GUIApplicationWindow::myGamingRNG static protected
A random number generator used to choose a gaming sound.
Definition at line 406 of file GUIApplicationWindow.h.
Referenced by checkGamingEvents().
FXLabel * GUIMainWindow::myGeoCoordinate protected inherited
Definition at line 143 of file GUIMainWindow.h.
Referenced by closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GNEApplicationWindow::dependentBuild(), dependentBuild(), and GUIMainWindow::getGeoLabel().
FXHorizontalFrame * GUIMainWindow::myGeoFrame protected inherited
Definition at line 144 of file GUIMainWindow.h.
Referenced by GNEApplicationWindow::create(), create(), GNEApplicationWindow::dependentBuild(), and dependentBuild().
FXGLVisual* GUIMainWindow::myGLVisual protected inherited
The gl-visual used.
Definition at line 147 of file GUIMainWindow.h.
Referenced by GUIMainWindow::getGLVisual(), GNEApplicationWindow::~GNEApplicationWindow(), and ~GUIApplicationWindow().
bool GUIApplicationWindow::myHaveNotifiedAboutSimEnd protected
whether the simulation end was already announced
Definition at line 391 of file GUIApplicationWindow.h.
Referenced by handleEvent_SimulationEnded(), and handleEvent_SimulationLoaded().
FXMenuPane * GUIApplicationWindow::myHelpMenu protected
Definition at line 329 of file GUIApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GUIApplicationWindow().
GUIMainWindow * GUIMainWindow::myInstance = 0 static protected inherited
the singleton window instance
Definition at line 164 of file GUIMainWindow.h.
Referenced by GUIMainWindow::getInstance(), and GUIMainWindow::GUIMainWindow().
RandomDistributor<std::string> GUIApplicationWindow::myJamSounds protected
Definition at line 401 of file GUIApplicationWindow.h.
Referenced by checkGamingEvents(), and handleEvent_SimulationLoaded().
double GUIApplicationWindow::myJamSoundTime protected
waiting time after which vehicles trigger jam sounds
Definition at line 404 of file GUIApplicationWindow.h.
Referenced by checkGamingEvents(), and handleEvent_SimulationLoaded().
FXEX::FXLCDLabel* GUIApplicationWindow::myLCDLabel protected
the simulation step display
Definition at line 365 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), closeAllWindows(), handleEvent_SimulationLoaded(), onCmdGaming(), and updateTimeLCD().
FXDockSite * GUIMainWindow::myLeftDock protected inherited
Definition at line 149 of file GUIMainWindow.h.
Referenced by GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
bool GUIMainWindow::myListInternal protected inherited
information whether the locator should list internal structures
Definition at line 155 of file GUIMainWindow.h.
Referenced by GUIMainWindow::listInternal(), and onCmdListInternal().
bool GUIMainWindow::myListParking protected inherited
information whether the locator should list parking vehicles
Definition at line 158 of file GUIMainWindow.h.
Referenced by fillMenuBar(), GUIMainWindow::listParking(), and onCmdListParking().
bool GUIMainWindow::myListTeleporting protected inherited
information whether the locator should list teleporting vehicles
Definition at line 161 of file GUIMainWindow.h.
Referenced by GUIMainWindow::listTeleporting(), and onCmdListTeleporting().
GUILoadThread* GUIApplicationWindow::myLoadThread protected
the thread that loads simulations
Definition at line 314 of file GUIApplicationWindow.h.
Referenced by dependentBuild(), loadConfigOrNet(), onCmdReload(), onUpdReload(), and ~GUIApplicationWindow().
FXEX::FXThreadEvent GUIApplicationWindow::myLoadThreadEvent protected
io-event with the load-thread
Definition at line 368 of file GUIApplicationWindow.h.
Referenced by dependentBuild().
FXMenuPane * GUIApplicationWindow::myLocatorMenu protected
Definition at line 329 of file GUIApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GUIApplicationWindow().
FXSplitter* GUIApplicationWindow::myMainSplitter protected
The splitter that divides the main window into vies and the log window.
Definition at line 340 of file GUIApplicationWindow.h.
Referenced by dependentBuild().
FXMDIClient* GUIMainWindow::myMDIClient protected inherited
The multi view panel.
Definition at line 137 of file GUIMainWindow.h.
Referenced by GNEApplicationWindow::dependentBuild(), dependentBuild(), fillMenuBar(), GUIMainWindow::getActiveView(), getBuildGLCanvas(), GNEApplicationWindow::getBuildGLCanvas(), onCmdEditChosen(), onCmdFullScreen(), onCmdGaming(), GNEApplicationWindow::onCmdLocate(), onCmdLocate(), onCmdShowStats(), GNEApplicationWindow::onKeyPress(), onKeyPress(), GNEApplicationWindow::onKeyRelease(), onKeyRelease(), openNewView(), GNEApplicationWindow::openNewView(), and GUIMainWindow::updateChildren().
FXMDIMenu* GUIApplicationWindow::myMDIMenu protected
The menu used for the MDI-windows.
Definition at line 356 of file GUIApplicationWindow.h.
Referenced by dependentBuild(), and openNewView().
FXMenuBar* GUIApplicationWindow::myMenuBar protected
The application menu bar.
Definition at line 359 of file GUIApplicationWindow.h.
Referenced by dependentBuild(), fillMenuBar(), onCmdFullScreen(), and onCmdGaming().
FXToolBarShell * GUIApplicationWindow::myMenuBarDrag protected
Definition at line 343 of file GUIApplicationWindow.h.
Referenced by create(), dependentBuild(), and detach().
GUIMessageWindow* GUIApplicationWindow::myMessageWindow protected
A window to display messages, warnings and error in.
Definition at line 337 of file GUIApplicationWindow.h.
Referenced by closeAllWindows(), dependentBuild(), fillMenuBar(), handleEvent_Message(), onCmdClearMsgWindow(), onCmdFullScreen(), and onCmdGaming().
std::string GUIApplicationWindow::myName protected
the name of the simulation
Definition at line 311 of file GUIApplicationWindow.h.
int GUIApplicationWindow::myPreviousCollisionNumber protected
Definition at line 407 of file GUIApplicationWindow.h.
Referenced by checkGamingEvents().
FXRecentFiles GUIApplicationWindow::myRecentConfigs protected
List of recent config files.
Definition at line 374 of file GUIApplicationWindow.h.
Referenced by addRecentFile(), fillMenuBar(), and onCmdOpenConfiguration().
FXRecentFiles GUIApplicationWindow::myRecentNets protected
List of recent nets.
Definition at line 377 of file GUIApplicationWindow.h.
Referenced by addRecentFile(), fillMenuBar(), onCmdOpenNetwork(), and onCmdOpenRecent().
FXDockSite * GUIMainWindow::myRightDock protected inherited
Definition at line 149 of file GUIMainWindow.h.
Referenced by GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
GUIRunThread* GUIApplicationWindow::myRunThread protected
the thread that runs simulations
Definition at line 317 of file GUIApplicationWindow.h.
Referenced by closeAllWindows(), dependentBuild(), eventOccured(), getCurrentSimTime(), handleEvent_SimulationLoaded(), handleEvent_SimulationStep(), onCmdEditBreakpoints(), onCmdEditChosen(), onCmdOpenShapes(), onCmdStart(), onCmdStep(), onCmdStop(), onCmdTimeToggle(), onUpdAddView(), onUpdNeedsSimulation(), onUpdStart(), onUpdStep(), onUpdStop(), openNewView(), updateTimeLCD(), and ~GUIApplicationWindow().
FXEX::FXThreadEvent GUIApplicationWindow::myRunThreadEvent protected
io-event with the run-thread
Definition at line 371 of file GUIApplicationWindow.h.
Referenced by dependentBuild(), and sendBlockingEvent().
FXMenuPane * GUIApplicationWindow::mySelectByPermissions protected
Definition at line 329 of file GUIApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GUIApplicationWindow().
FXMenuPane * GUIApplicationWindow::mySettingsMenu protected
Definition at line 329 of file GUIApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GUIApplicationWindow().
bool GUIApplicationWindow::myShowTimeAsHMS protected
whether to show time as hour:minute:second
Definition at line 385 of file GUIApplicationWindow.h.
Referenced by create(), onCmdQuit(), onCmdTimeToggle(), and updateTimeLCD().
FXRealSpinDial* GUIApplicationWindow::mySimDelayTarget protected
Definition at line 347 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), dependentBuild(), getDelay(), handleEvent_SimulationLoaded(), onCmdDelayToggle(), and setDelay().
std::vector<FXButton*> GUIApplicationWindow::myStatButtons protected
Buttons showing and running values and triggering statistic windows.
Definition at line 334 of file GUIApplicationWindow.h.
Referenced by closeAllWindows(), dependentBuild(), handleEvent_SimulationLoaded(), and handleEvent_SimulationStep().
FXStatusBar* GUIMainWindow::myStatusbar protected inherited
The status bar.
Definition at line 140 of file GUIMainWindow.h.
Referenced by GNEApplicationWindow::dependentBuild(), dependentBuild(), GNEApplicationWindow::fillMenuBar(), fillMenuBar(), onCmdFullScreen(), onCmdGaming(), GNEApplicationWindow::onCmdOpenRecent(), onCmdOpenRecent(), onCmdStart(), onCmdStep(), openNewView(), GNEApplicationWindow::setStatusBarText(), and setStatusBarText().
std::vector<FXMDIChild*> GUIMainWindow::mySubWindows protected inherited
Definition at line 128 of file GUIMainWindow.h.
Referenced by GUIMainWindow::addChild(), closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GNEApplicationWindow::getView(), GUIMainWindow::getViewByID(), GUIMainWindow::getViewIDs(), onCmdNetedit(), and GUIMainWindow::removeChild().
SUMOTime GUIApplicationWindow::myTimeLoss protected
Definition at line 413 of file GUIApplicationWindow.h.
Referenced by checkGamingEvents().
FXEX::FXLCDLabel* GUIApplicationWindow::myTimeLossLabel protected
Definition at line 411 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), checkGamingEvents(), and onCmdGaming().
FXToolBar* GUIApplicationWindow::myToolBar1 protected
The application tool bar.
Definition at line 362 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), onCmdFullScreen(), and onCmdGaming().
FXToolBar * GUIApplicationWindow::myToolBar2 protected
Definition at line 362 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), eventOccured(), onCmdFullScreen(), and onCmdGaming().
FXToolBar * GUIApplicationWindow::myToolBar3 protected
Definition at line 362 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), eventOccured(), fillMenuBar(), and onCmdFullScreen().
FXToolBar * GUIApplicationWindow::myToolBar4 protected
Definition at line 362 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), fillMenuBar(), onCmdFullScreen(), and onCmdGaming().
FXToolBar * GUIApplicationWindow::myToolBar5 protected
Definition at line 362 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), onCmdFullScreen(), and onCmdGaming().
FXToolBar* GUIApplicationWindow::myToolBar6 protected
Definition at line 414 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), dependentBuild(), onCmdFullScreen(), and onCmdGaming().
FXToolBar * GUIApplicationWindow::myToolBar7 protected
Definition at line 414 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), dependentBuild(), onCmdFullScreen(), and onCmdGaming().
FXToolBarShell* GUIApplicationWindow::myToolBarDrag1 protected
for some menu detaching fun
Definition at line 343 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), create(), detach(), and ~GUIApplicationWindow().
FXToolBarShell * GUIApplicationWindow::myToolBarDrag2 protected
Definition at line 343 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), and create().
FXToolBarShell * GUIApplicationWindow::myToolBarDrag3 protected
Definition at line 343 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), and create().
FXToolBarShell * GUIApplicationWindow::myToolBarDrag4 protected
Definition at line 343 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), and create().
FXToolBarShell * GUIApplicationWindow::myToolBarDrag5 protected
Definition at line 343 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), and create().
FXToolBarShell* GUIApplicationWindow::myToolBarDrag6 protected
Definition at line 415 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), and create().
FXToolBarShell * GUIApplicationWindow::myToolBarDrag7 protected
Definition at line 415 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), and create().
FXDockSite* GUIMainWindow::myTopDock protected inherited
Definition at line 149 of file GUIMainWindow.h.
Referenced by buildToolBars(), GNEApplicationWindow::dependentBuild(), dependentBuild(), GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
MFXMutex GUIMainWindow::myTrackerLock protected inherited
A lock to make the removal and addition of trackers secure.
Definition at line 131 of file GUIMainWindow.h.
Referenced by GUIMainWindow::addChild(), closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GUIMainWindow::removeChild(), and GUIMainWindow::updateChildren().
std::vector<FXMainWindow*> GUIMainWindow::myTrackerWindows protected inherited
Definition at line 129 of file GUIMainWindow.h.
Referenced by GUIMainWindow::addChild(), closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GUIMainWindow::removeChild(), and GUIMainWindow::updateChildren().
int GUIApplicationWindow::myViewNumber protected
The current view number.
Definition at line 323 of file GUIApplicationWindow.h.
Referenced by handleEvent_SimulationLoaded(), and openNewView().
SUMOTime GUIApplicationWindow::myWaitingTime protected
Definition at line 412 of file GUIApplicationWindow.h.
Referenced by checkGamingEvents().
FXEX::FXLCDLabel* GUIApplicationWindow::myWaitingTimeLabel protected
performance indicators
Definition at line 410 of file GUIApplicationWindow.h.
Referenced by buildToolBars(), checkGamingEvents(), and onCmdGaming().
bool GUIApplicationWindow::myWasStarted protected
the information whether the simulation was started before
Definition at line 320 of file GUIApplicationWindow.h.
Referenced by handleEvent_SimulationLoaded(), onCmdStart(), and onCmdStep().
FXMenuPane * GUIApplicationWindow::myWindowsMenu protected
Definition at line 329 of file GUIApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GUIApplicationWindow().
The documentation for this class was generated from the following files:
GUIApplicationWindow.h
GUIApplicationWindow.cpp