SUMO - Simulation of Urban MObility: PointOfInterest Class Reference
PointOfInterest Class Reference
A point-of-interest.
#include <PointOfInterest.h>
Public Member Functions
void add (const Position &pos)
Adds the given position to this one.
void add (double dx, double dy)
Adds the given position to this one.
void add (double dx, double dy, double dz)
Adds the given position to this one.
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool almostSame (const Position &p2, double maxDiv=POSITION_EPS) const
checki if two position is almost the sme as other
double angleTo2D (const Position &other) const
returns the angle in the plane of the vector pointing from here to the other position
void clearParameter ()
Clears the parameter map.
Position crossProduct (const Position &pos)
returns the cross product between this point and the second one
double distanceSquaredTo (const Position &p2) const
returns the square of the distance to another position
double distanceSquaredTo2D (const Position &p2) const
returns the square of the distance to another position (Only using x and y positions)
double distanceTo (const Position &p2) const
returns the euclidean distance in 3 dimension
double distanceTo2D (const Position &p2) const
returns the euclidean distance in the x-y-plane
double dotProduct (const Position &pos)
returns the dot product (scalar product) between this point and the second one
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::string & getID () const
Returns the id.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void mul (double val)
Multiplies both positions with the given value.
void mul (double mx, double my)
Multiplies position with the given values.
void mul (double mx, double my, double mz)
Multiplies position with the given values.
void norm2d ()
bool operator!= (const Position &p2) const
difference operator
Position operator* (double scalar) const
keep the direction but modify the length of the (location) vector to length * scalar
Position operator+ (const Position &p2) const
add operator
Position operator+ (double offset) const
keep the direction but modify the length of the (location) vector to length + scalar
Position operator- (const Position &p2) const
sub operator
bool operator< (const Position &p2) const
lexicographical sorting for use in maps and sets
bool operator== (const Position &p2) const
comparation operator
PointOfInterest (const std::string &id, const std::string &type, const RGBColor &color, const Position &pos, double layer=DEFAULT_LAYER, double angle=DEFAULT_ANGLE, const std::string &imgFile=DEFAULT_IMG_FILE, double width=DEFAULT_IMG_WIDTH, double height=DEFAULT_IMG_HEIGHT)
Constructor.
void set (double x, double y)
set positions x and y
void set (double x, double y, double z)
set positions x, y and z
void set (const Position &pos)
set position with another position
void setID (const std::string &newID)
resets the id
void setx (double x)
set position x
void sety (double y)
set position y
void setz (double z)
set position z
void sub (double dx, double dy)
Substracts the given position from this one.
void sub (double dx, double dy, double dz)
Substracts the given position from this one.
void sub (const Position &pos)
Substracts the given position from this one.
void writeParams (OutputDevice &out) const
void writeXML (OutputDevice &out, const bool geo=false, const double zOffset=0., const std::string laneID="", const double pos=0.)
double x () const
Returns the x-position.
double y () const
Returns the y-position.
double z () const
Returns the z-position.
virtual ~PointOfInterest ()
Destructor.
Getter
double getWidth () const
Returns the image width of the POI.
double getHeight () const
Returns the image height of the POI.
Setter
void setWidth (double width)
set the image width of the POI
void setHeight (double height)
set the image height of the POI
Getter
const std::string & getType () const
Returns the (abstract) type of the Shape.
const RGBColor & getColor () const
Returns the color of the Shape.
double getLayer () const
Returns the layer of the Shape.
double getNaviDegree () const
Returns the angle of the Shape in navigational degrees.
const std::string & getImgFile () const
Returns the imgFile of the Shape.
Setter
void setType (const std::string &type)
Sets a new type.
void setColor (const RGBColor &col)
Sets a new color.
void setLayer (const double layer)
Sets a new layer.
void setNaviDegree (const double angle)
Sets a new angle in navigational degrees.
void setImgFile (const std::string &imgFile)
Sets a new imgFile.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Static Public Attributes
static const double DEFAULT_ANGLE = 0
static const std::string DEFAULT_IMG_FILE = ""
static const double DEFAULT_IMG_HEIGHT = 1
static const double DEFAULT_IMG_WIDTH = 1
static const double DEFAULT_LAYER = 128
static const std::string DEFAULT_TYPE = ""
static const Position INVALID
used to indicate that a position is valid
Protected Attributes
RGBColor myColor
The color of the Shape.
double myHalfImgHeight
The half height of the image when rendering this POI.
double myHalfImgWidth
The half width of the image when rendering this POI.
std::string myID
The name of the object.
std::string myImgFile
The angle of the Shape.
double myLayer
The layer of the Shape.
double myNaviDegreeAngle
The angle of the Shape.
std::string myType
The type of the Shape.
Detailed Description
A point-of-interest.
Definition at line 51 of file PointOfInterest.h.
Constructor & Destructor Documentation
PointOfInterest::PointOfInterest (const std::string & id, const std::string & type, const RGBColor & color, const Position & pos, double layer = DEFAULT_LAYER, double angle = DEFAULT_ANGLE, const std::string & imgFile = DEFAULT_IMG_FILE, double width = DEFAULT_IMG_WIDTH, double height = DEFAULT_IMG_HEIGHT) inline
Constructor.
Parameters
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] layer The layer of the POI
[in] angle The rotation of the POI
[in] imgFile The raster image of the shape
[in] pos The position of the POI
[in] width The width of the POI image
[in] height The height of the POI image
Definition at line 64 of file PointOfInterest.h.
virtual PointOfInterest::~PointOfInterest () inline virtual
Destructor.
Definition at line 79 of file PointOfInterest.h.
Member Function Documentation
void Position::add (const Position & pos) inline inherited
Adds the given position to this one.
Definition at line 133 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), NBNodeShapeComputer::computeNodeShapeDefault(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), GNEEdge::drawGL(), GUIEdge::drawGL(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), GeoConvHelper::moveConvertedBy(), NBDistrict::reshiftPosition(), NBNode::reshiftPosition(), NBPTStop::reshiftPostion(), GUISUMOAbstractView::showToolTipFor(), and GeoConvHelper::x2cartesian_const().
void Position::add (double dx, double dy) inline inherited
Adds the given position to this one.
Definition at line 140 of file Position.h.
References Position::myX, and Position::myY.
void Position::add (double dx, double dy, double dz) inline inherited
Adds the given position to this one.
Definition at line 146 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), TraCI_POI::addParameter(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenDrive::loadNetwork(), MSStateHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCI_Polygon::setParameter(), TraCI_Route::setParameter(), and TraCI_Lane::setParameter().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 65 of file Parameterised.cpp.
References Parameterised::myMap.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
bool Position::almostSame (const Position & p2, double maxDiv = POSITION_EPS) const inline inherited
checki if two position is almost the sme as other
Definition at line 235 of file Position.h.
References Position::distanceTo().
Referenced by AGPosition::operator==(), PositionVector::push_back_noDoublePos(), and PositionVector::push_front_noDoublePos().
double Position::angleTo2D (const Position & other) const inline inherited
returns the angle in the plane of the vector pointing from here to the other position
Definition at line 260 of file Position.h.
References Position::myX, and Position::myY.
Referenced by NBNode::bezierControlPoints(), MSVehicle::computeAngle(), NBEdge::computeAngle(), GUIBusStop::drawGL(), GLHelper::drawTriangleAtEnd(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), TraCIServerAPI_Vehicle::processSet(), PositionVector::rotationAtOffset(), and NWWriter_OpenDrive::writeGeomSmooth().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 99 of file Parameterised.cpp.
References Parameterised::myMap.
Position Position::crossProduct (const Position & pos) inline inherited
returns the cross product between this point and the second one
Definition at line 265 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Referenced by NBHeightMapper::Triangle::normalVector().
double Position::distanceSquaredTo (const Position & p2) const inline inherited
returns the square of the distance to another position
Definition at line 245 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by Position::distanceTo().
double Position::distanceSquaredTo2D (const Position & p2) const inline inherited
returns the square of the distance to another position (Only using x and y positions)
Definition at line 255 of file Position.h.
References Position::myX, and Position::myY.
Referenced by Position::distanceTo2D().
double Position::distanceTo (const Position & p2) const inline inherited
returns the euclidean distance in 3 dimension
Definition at line 240 of file Position.h.
References Position::distanceSquaredTo().
Referenced by Position::almostSame(), TraCIServerAPI_Simulation::commandDistanceRequest(), NBHelpers::distance(), AGPosition::distanceTo(), GLHelper::drawBoxLines(), GLHelper::drawTriangleAtEnd(), PositionVector::extrapolate(), ROEdge::getLengthGeometryFactor(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), PositionVector::indexOfClosest(), NBEdge::init(), GUIE2Collector::MyWrapper::MyWrapper(), GUIViewTraffic::onGamingClick(), Position::operator+(), PositionVector::positionAtOffset(), NIVissimEdge::remapOneOfNodes(), PositionVector::rotationAtOffset(), GUIBaseVehicle::setFunctionalColor(), PositionVector::slopeDegreeAtOffset(), GUILane::splitAtSegments(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), and MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility().
double Position::distanceTo2D (const Position & p2) const inline inherited
returns the euclidean distance in the x-y-plane
Definition at line 250 of file Position.h.
References Position::distanceSquaredTo2D().
Referenced by NBNode::bezierControlPoints(), NBNode::buildWalkingAreas(), NGRandomNetBuilder::canConnect(), NBNode::checkCrossing(), GUIVehicle::computeSeats(), NIImporter_OpenDrive::computeShapes(), PositionVector::distance2D(), GUIVehicle::drawAction_drawRailCarriages(), GUIBusStop::drawGL(), PositionVector::extrapolate2D(), ROEdge::getDistanceTo(), MSEdge::getDistanceTo(), PositionVector::getMaxGrade(), CState::getPosition(), GNEInternalLane::GNEInternalLane(), GUILane::GUILane(), MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), MSPModel_Striping::initWalkingAreaPaths(), PositionVector::insertAtClosest(), PositionVector::intersects(), PositionVector::intersectsAtLengths2D(), PositionVector::move2side(), GeomHelper::nearest_offset_on_line_to_point2D(), PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset2D(), PositionVector::removeClosest(), GNEEdge::resetEndpoint(), GNEEdge::setEndpoint(), PositionVector::sideOffset(), PositionVector::simplified(), PositionVector::slopeDegreeAtOffset(), PositionVector::smoothedZFront(), PositionVector::transformToVectorCoordinates(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNELane::updateGeometry(), TraCIServerAPI_Vehicle::vtdMap(), NWWriter_OpenDrive::writeGeomLines(), and NWWriter_OpenDrive::writeGeomSmooth().
double Position::dotProduct (const Position & pos) inline inherited
returns the dot product (scalar product) between this point and the second one
Definition at line 273 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NBHeightMapper::Triangle::getZ().
const RGBColor& Shape::getColor () const inline inherited
Returns the color of the Shape.
Returns
The Shape's color
Definition at line 79 of file Shape.h.
References Shape::myColor.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), TraCI_Polygon::getColor(), TraCI_POI::getColor(), writeXML(), and SUMO::Polygon::writeXML().
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 89 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
double PointOfInterest::getHeight () const inline
Returns the image height of the POI.
Definition at line 92 of file PointOfInterest.h.
References myHalfImgHeight.
Referenced by writeXML().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), MSNet::addParkingArea(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), TraCI_Vehicle::getBestLanes(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), TraCI_Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), TraCI_Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), TraCI_Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSNet::getParkingAreaID(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), TraCI_Vehicle::getRoadID(), TraCI_Vehicle::getRouteID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_SSM::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSDevice_SSM::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_SSM::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingZone(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), toString(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSDevice_SSM::updateEncounter(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSPModel_Striping::PState::moveToNextLane(), operator<<(), TraCIServerAPI_Vehicle::processSet(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), MSAbstractLaneChangeModel::updateShadowLane(), and TraCIServerAPI_Vehicle::vtdMap().
const std::string& Shape::getImgFile () const inline inherited
Returns the imgFile of the Shape.
Returns
The Shape's rotation imgFile
Definition at line 101 of file Shape.h.
References Shape::myImgFile.
Referenced by GUIPolygon::drawGL(), writeXML(), and SUMO::Polygon::writeXML().
double Shape::getLayer () const inline inherited
Returns the layer of the Shape.
Returns
The Shape's layer
Definition at line 87 of file Shape.h.
References Shape::myLayer.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), writeXML(), and SUMO::Polygon::writeXML().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 119 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NBTrafficLightDefinition::compute(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROPerson::saveAsXML(), and writeXML().
double Shape::getNaviDegree () const inline inherited
Returns the angle of the Shape in navigational degrees.
Returns
The Shape's rotation angle
Definition at line 94 of file Shape.h.
References Shape::myNaviDegreeAngle.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), writeXML(), and SUMO::Polygon::writeXML().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 79 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getLoggingFrequency(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), TraCI_Polygon::getParameter(), TraCI_VehicleType::getParameter(), TraCI_Route::getParameter(), TraCI_POI::getParameter(), TraCI_Lane::getParameter(), TraCI_Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), TraCIServerAPI_Vehicle::vtdMap(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
const std::string& Shape::getType () const inline inherited
Returns the (abstract) type of the Shape.
Returns
The Shape's (abstract) type
Definition at line 71 of file Shape.h.
References Shape::myType.
Referenced by GNEPOI::getAttribute(), TraCI_Polygon::getType(), TraCI_POI::getType(), writeXML(), and SUMO::Polygon::writeXML().
double PointOfInterest::getWidth () const inline
Returns the image width of the POI.
Definition at line 87 of file PointOfInterest.h.
References myHalfImgWidth.
Referenced by writeXML().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 73 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getLoggingFrequency(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), and MSDevice_SSM::requestsTrajectories().
void Position::mul (double val) inline inherited
Multiplies both positions with the given value.
Definition at line 113 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NIXMLNodesHandler::addNode(), NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), GeoConvHelper::computeFinal(), NBNodeShapeComputer::computeNodeShapeDefault(), GNEEdge::drawGL(), GUIEdge::drawGL(), NBNode::getEmptyDir(), NBDistrict::mirrorX(), NBNode::mirrorX(), PCPolyContainer::saveDlrTDP(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeTrafficSignals().
void Position::mul (double mx, double my) inline inherited
Multiplies position with the given values.
Definition at line 120 of file Position.h.
References Position::myX, and Position::myY.
void Position::mul (double mx, double my, double mz) inline inherited
Multiplies position with the given values.
Definition at line 126 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::norm2d () inline inherited
Definition at line 173 of file Position.h.
References Position::myX, and Position::myY.
Referenced by NBNode::getEmptyDir().
bool Position::operator!= (const Position & p2) const inline inherited
difference operator
Definition at line 219 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Position Position::operator* (double scalar) const inline inherited
keep the direction but modify the length of the (location) vector to length * scalar
Definition at line 199 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Position Position::operator+ (const Position & p2) const inline inherited
add operator
Definition at line 189 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Position Position::operator+ (double offset) const inline inherited
keep the direction but modify the length of the (location) vector to length + scalar
Definition at line 204 of file Position.h.
References Position::distanceTo(), Position::myX, Position::myY, Position::myZ, and Position::Position().
Position Position::operator- (const Position & p2) const inline inherited
sub operator
Definition at line 194 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
bool Position::operator< (const Position & p2) const inline inherited
lexicographical sorting for use in maps and sets
Definition at line 224 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
bool Position::operator== (const Position & p2) const inline inherited
comparation operator
Definition at line 214 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::set (double x, double y) inline inherited
set positions x and y
Definition at line 93 of file Position.h.
References Position::myX, Position::myY, Position::x(), and Position::y().
Referenced by NIXMLNodesHandler::addNode(), ShapeHandler::addPOI(), NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeSmall(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUICompleteSchemeStorage::init(), NBHeightMapper::loadTiff(), TraCI::makePosition(), GNEDetector::moveAdditionalGeometry(), GNEDetectorE3::moveAdditionalGeometry(), GUISettingsHandler::myStartElement(), GNEViewNet::onLeftBtnPress(), GNEViewNet::onMouseMove(), NLJunctionControlBuilder::openJunction(), operator>>(), TraCIServerAPI_GUI::processSet(), GUICompleteSchemeStorage::saveViewport(), TraCI_POI::setPosition(), NGNode::setX(), NGNode::setY(), GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
void Position::set (double x, double y, double z) inline inherited
set positions x, y and z
Definition at line 99 of file Position.h.
References Position::myX, Position::myY, Position::myZ, Position::x(), Position::y(), and Position::z().
void Position::set (const Position & pos) inline inherited
set position with another position
Definition at line 106 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Shape::setColor (const RGBColor & col) inline inherited
Sets a new color.
Parameters
[in] col The new color to use
Definition at line 121 of file Shape.h.
References Shape::myColor.
Referenced by TraCI_Polygon::setColor(), and TraCI_POI::setColor().
void PointOfInterest::setHeight (double height) inline
set the image height of the POI
Definition at line 108 of file PointOfInterest.h.
References myHalfImgHeight.
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::Distribution_Parameterized(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void Shape::setImgFile (const std::string & imgFile) inline inherited
Sets a new imgFile.
Parameters
[in] imgFile The new imgFile to use
Definition at line 144 of file Shape.h.
References Shape::myImgFile.
void Shape::setLayer (const double layer) inline inherited
Sets a new layer.
Parameters
[in] layer The new layer to use
Definition at line 129 of file Shape.h.
References Shape::myLayer.
void Shape::setNaviDegree (const double angle) inline inherited
Sets a new angle in navigational degrees.
Parameters
[in] layer The new angle to use
Definition at line 137 of file Shape.h.
References Shape::myNaviDegreeAngle.
void Shape::setType (const std::string & type) inline inherited
Sets a new type.
Parameters
[in] type The new type to use
Definition at line 113 of file Shape.h.
References Shape::myType.
Referenced by TraCI_Polygon::setType(), and TraCI_POI::setType().
void PointOfInterest::setWidth (double width) inline
set the image width of the POI
Definition at line 103 of file PointOfInterest.h.
References myHalfImgWidth.
void Position::setx (double x) inline inherited
set position x
Definition at line 78 of file Position.h.
References Position::myX, and Position::x().
Referenced by GNEDetectorE3::setAttribute(), and GUISUMOAbstractView::snapToActiveGrid().
void Position::sety (double y) inline inherited
set position y
Definition at line 83 of file Position.h.
References Position::myY, and Position::y().
Referenced by GNEDetectorE3::setAttribute(), and GUISUMOAbstractView::snapToActiveGrid().
void Position::setz (double z) inline inherited
set position z
Definition at line 88 of file Position.h.
References Position::myZ, and Position::z().
Referenced by NBNodeShapeComputer::computeNodeShapeDefault(), and NBEdge::startShapeAt().
void Position::sub (double dx, double dy) inline inherited
Substracts the given position from this one.
Definition at line 153 of file Position.h.
References Position::myX, and Position::myY.
Referenced by NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), AGPosition::compute2dPosition(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), and NBHeightMapper::Triangle::getZ().
void Position::sub (double dx, double dy, double dz) inline inherited
Substracts the given position from this one.
Definition at line 159 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::sub (const Position & pos) inline inherited
Substracts the given position from this one.
Definition at line 166 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 104 of file Parameterised.cpp.
References OutputDevice::closeTag(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MSVehicle::saveState(), SUMOVTypeParameter::write(), MSDevice_Vehroutes::writeOutput(), and SUMO::Polygon::writeXML().
void PointOfInterest::writeXML (OutputDevice & out, const bool geo = false, const double zOffset = 0., const std::string laneID = "", const double pos = 0.) inline
Definition at line 117 of file PointOfInterest.h.
References GeoConvHelper::cartesian2geo(), OutputDevice::closeTag(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_IMG_HEIGHT, Shape::DEFAULT_IMG_WIDTH, StringUtils::escapeXML(), Shape::getColor(), GeoConvHelper::getFinal(), getHeight(), Named::getID(), Shape::getImgFile(), Shape::getLayer(), Parameterised::getMap(), Shape::getNaviDegree(), Shape::getType(), getWidth(), OutputDevice::openTag(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_KEY, SUMO_ATTR_LANE, SUMO_ATTR_LAT, SUMO_ATTR_LAYER, SUMO_ATTR_LON, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_ATTR_VALUE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_PARAM, SUMO_TAG_POI, OutputDevice::writeAttr(), Position::x(), and Position::y().
Referenced by GNEPOI::saveToFile().
double Position::x () const inline inherited
Returns the x-position.
Definition at line 63 of file Position.h.
References Position::myX.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), GNEDetector::commmitAdditionalGeometryMoved(), GNEDetectorE3::commmitAdditionalGeometryMoved(), GNEAdditional::commmitAdditionalGeometryMoved(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GUISUMOAbstractView::drawDecals(), GNEDetector::drawDetectorIcon(), GLHelper::drawFilledPoly(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GLHelper::drawTextAtEnd(), GLHelper::drawTextBox(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), GeomHelper::findLineCircleIntersections(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE2::getAttribute(), GNEDetectorE3::getAttribute(), GNECalibrator::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), PositionVector::getPolygonCenter(), GNEAdditional::getPopUpMenu(), TraCI_POI::getPosition(), GNEDetectorExit::getPositionInView(), GNEDetectorE1::getPositionInView(), GNEDetectorEntry::getPositionInView(), GNEStoppingPlace::getPositionInView(), GNEVaporizer::getPositionInView(), GNEDetectorE2::getPositionInView(), GNERouteProbe::getPositionInView(), GNEDetector::getPositionOverLane(), MSVTKExport::getPositions(), TraCIServerAPI_InductionLoop::getTree(), GUIDanielPerspectiveChanger::getXPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), GUIParkingArea::GUIParkingArea(), NBNodeCont::insert(), PositionVector::intersects(), isLeft(), PositionVector::isLeft(), NBHeightMapper::loadTiff(), TraCI::makeTraCIPosition(), GNEDetector::moveAdditionalGeometry(), GNEAdditional::moveAdditionalGeometry(), GNEEdge::moveGeometry(), MSPModel_Striping::moveInDirection(), MSParkingArea::MSParkingArea(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIE2Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GNEViewNet::onMouseMove(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), PCPolyContainer::saveDlrTDP(), Position::set(), GNEAdditional::setBlockIconRotation(), GUIBaseVehicle::setFunctionalColor(), GNEJunction::setPosition(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), Position::setx(), NGNode::setY(), PositionVector::sideOffset(), PositionVector::simplified(), GUISUMOAbstractView::snapToActiveGrid(), NBNetBuilder::transformCoordinate(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), GNECalibrator::updateGeometry(), GNELane::updateGeometry(), GNEJunction::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), GNEDetectorExit::updateGeometryByParent(), GNEDetectorE3::updateGeometryConnections(), GUISUMOAbstractView::updatePositionInformation(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), GNEDetectorE1::writeAdditional(), GNEDetectorE2::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
double Position::y () const inline inherited
Returns the y-position.
Definition at line 68 of file Position.h.
References Position::myY.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), GNEDetectorE3::commmitAdditionalGeometryMoved(), GNEAdditional::commmitAdditionalGeometryMoved(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GUISUMOAbstractView::drawDecals(), GNEDetector::drawDetectorIcon(), GLHelper::drawFilledPoly(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GLHelper::drawTextAtEnd(), GLHelper::drawTextBox(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), GeomHelper::findLineCircleIntersections(), GNEDetectorE3::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), GNEAdditional::getPopUpMenu(), TraCI_POI::getPosition(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), MSVTKExport::getPositions(), TraCIServerAPI_InductionLoop::getTree(), GUIDanielPerspectiveChanger::getYPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), GUIParkingArea::GUIParkingArea(), NBNodeCont::insert(), PositionVector::intersects(), isLeft(), PositionVector::isLeft(), NBHeightMapper::loadTiff(), TraCI::makeTraCIPosition(), GNEAdditional::moveAdditionalGeometry(), GNEEdge::moveGeometry(), MSPModel_Striping::moveInDirection(), MSParkingArea::MSParkingArea(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIE2Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), PCPolyContainer::saveDlrTDP(), Position::set(), GUIBaseVehicle::setFunctionalColor(), GNEJunction::setPosition(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), NGNode::setX(), Position::sety(), PositionVector::sideOffset(), PositionVector::simplified(), GUISUMOAbstractView::snapToActiveGrid(), NBNetBuilder::transformCoordinate(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNELane::updateGeometry(), GNEJunction::updateGeometry(), GNEDetectorE3::updateGeometryConnections(), GUISUMOAbstractView::updatePositionInformation(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), GNEDetectorE3::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
double Position::z () const inline inherited
Returns the z-position.
Definition at line 73 of file Position.h.
References Position::myZ.
Referenced by Boundary::add(), PositionVector::add(), GUISettingsHandler::applyViewport(), Boundary::around(), bezier(), NBNode::bezierControlPoints(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NBEdge::cutAtIntersection(), MSVTypeProbe::execute(), PositionVector::getMaxGrade(), PositionVector::getOverlapWith(), GNELane::getPopUpMenu(), GUILane::getPopUpMenu(), TraCI_POI::getPosition(), MSVTKExport::getPositions(), TraCI::makeTraCIPosition(), PositionVector::move2side(), GNEEdge::moveGeometry(), GUISettingsHandler::myStartElement(), TraCIServerAPI_Person::processGet(), GNENet::registerJunction(), Position::set(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), Position::setz(), PositionVector::slopeDegreeAtOffset(), NBEdge::startShapeAt(), MSFCDExport::write(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), and MSFCDExport::writeTransportable().
Field Documentation
const double Shape::DEFAULT_ANGLE = 0 static inherited
Definition at line 151 of file Shape.h.
Referenced by TraCI_Polygon::add(), TraCI_POI::add(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), writeXML(), and SUMO::Polygon::writeXML().
const std::string Shape::DEFAULT_IMG_FILE = "" static inherited
Definition at line 152 of file Shape.h.
Referenced by TraCI_Polygon::add(), TraCI_POI::add(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), writeXML(), and SUMO::Polygon::writeXML().
const double Shape::DEFAULT_IMG_HEIGHT = 1 static inherited
Definition at line 154 of file Shape.h.
Referenced by TraCI_POI::add(), ShapeHandler::addPOI(), and writeXML().
const double Shape::DEFAULT_IMG_WIDTH = 1 static inherited
Definition at line 153 of file Shape.h.
Referenced by TraCI_POI::add(), ShapeHandler::addPOI(), and writeXML().
const double Shape::DEFAULT_LAYER = 128 static inherited
Definition at line 150 of file Shape.h.
Referenced by ShapeHandler::myStartElement().
const std::string Shape::DEFAULT_TYPE = "" static inherited
Definition at line 149 of file Shape.h.
Referenced by ShapeHandler::addPoly().
const Position Position::INVALID static inherited
used to indicate that a position is valid
Definition at line 278 of file Position.h.
Referenced by NBNode::bezierControlPoints(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), NLShapeHandler::getLanePos(), PCLoaderXML::getLanePos(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), MSPModel_Striping::PState::getPosition(), MSTransportable::Stage_Driving::getPosition(), MSVehicle::getPosition(), MSParkingArea::getVehiclePosition(), PositionVector::intersectionPosition2D(), PositionVector::move2side(), MSPModel_Striping::moveInDirection(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdOk(), PositionVector::positionAtOffset(), PositionVector::positionAtOffset2D(), MSPerson::MSPersonStage_Driving::proceed(), GUISUMOAbstractView::showViewportEditor(), MSLaneChangerSublane::startChangeSublane(), PositionVector::transformToVectorCoordinates(), and MSVehicle::updateState().
RGBColor Shape::myColor protected inherited
The color of the Shape.
Definition at line 161 of file Shape.h.
Referenced by Shape::getColor(), and Shape::setColor().
double PointOfInterest::myHalfImgHeight protected
The half height of the image when rendering this POI.
Definition at line 164 of file PointOfInterest.h.
Referenced by GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), getHeight(), and setHeight().
double PointOfInterest::myHalfImgWidth protected
The half width of the image when rendering this POI.
Definition at line 161 of file PointOfInterest.h.
Referenced by GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), getWidth(), and setWidth().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::string Shape::myImgFile protected inherited
The angle of the Shape.
Definition at line 170 of file Shape.h.
Referenced by GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), Shape::getImgFile(), and Shape::setImgFile().
double Shape::myLayer protected inherited
The layer of the Shape.
Definition at line 164 of file Shape.h.
Referenced by Shape::getLayer(), and Shape::setLayer().
double Shape::myNaviDegreeAngle protected inherited
The angle of the Shape.
Definition at line 167 of file Shape.h.
Referenced by Shape::getNaviDegree(), and Shape::setNaviDegree().
std::string Shape::myType protected inherited
The type of the Shape.
Definition at line 158 of file Shape.h.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), Shape::getType(), and Shape::setType().
The documentation for this class was generated from the following file:
PointOfInterest.h