SUMO - Simulation of Urban MObility: GNECalibratorVehicleType Class Reference
GNECalibratorVehicleType Class Reference
#include <GNECalibratorVehicleType.h>
Public Member Functions
double getAccel () const
get accel
double getBoardingDuration () const
get boarding duration
GNECalibrator * getCalibratorParent () const
get pointer to calibrator parent
std::string getCarFollowModel () const
get car follow model
std::string getColor () const
get color
int getContainerCapacity () const
get container capacity
double getDecel () const
get decel
std::string getEmissionClass () const
get emission class
std::string getFilename () const
get filename
double getImpatience () const
get impatience
std::string getLaneChangeModel () const
get lane change model
std::string getLatAlignment () const
get lateral lat
double getLength () const
get length
double getLoadingDuration () const
get loading duration
double getMaxSpeed () const
get max speed
double getMaxSpeedLat () const
get max speed lat
double getMinGap () const
get min gap
double getMinGapLat () const
get min gap lat
int getPersonCapacity () const
get person capacity
SUMOVehicleShape getShape () const
get shape
double getSigma () const
get sigma
double getSpeedDev () const
get speed dev
double getSpeedFactor () const
get speed factor
SumoXMLTag getTag () const
get tag
double getTau () const
get tau
SUMOVehicleClass getVClass () const
get VClass
std::string getVehicleTypeID () const
get VehicleTypeID
double getWidth () const
get width
GNECalibratorVehicleType (GNECalibrator *calibratorParent)
constructor
GNECalibratorVehicleType (GNECalibrator *calibratorParent, std::string vehicleTypeID, double accel, double decel, double sigma, double tau, double length, double minGap, double maxSpeed, double speedFactor, double speedDev, const std::string &color, SUMOVehicleClass vClass, const std::string &emissionClass, SUMOVehicleShape shape, double width, const std::string &filename, double impatience, const std::string &laneChangeModel, const std::string &carFollowModel, int personCapacity, int containerCapacity, double boardingDuration, double loadingDuration, const std::string &latAlignment, double minGapLat, double maxSpeedLat)
parameter constructor
bool operator== (const GNECalibratorVehicleType &calibratorVehicleType) const
overload operator ==
bool setAccel (double accel=2.6)
set accel
bool setAccel (std::string accel)
set accel (string version)
bool setBoardingDuration (double boardingDuration=0.5)
set boarding duration
bool setBoardingDuration (std::string boardingDuration)
set boarding duration (string version)
bool setCarFollowModel (std::string carFollowModel="Krauss")
set car follow model
bool setColor (std::string color="1,1,0")
set color
bool setContainerCapacity (int containerCapacity=0)
set container capacity
bool setContainerCapacity (std::string containerCapacity)
set container capacity (string version)
bool setDecel (double decel=4.5)
set decel
bool setDecel (std::string decel)
set decel (string version)
bool setEmissionClass (std::string emissionClass="P_7_7")
set emission class
bool setFilename (std::string filename="")
set filename
bool setImpatience (double impatience=0.0)
set impatience
bool setImpatience (std::string impatience)
set impatience (string version)
bool setLaneChangeModel (std::string laneChangeModel="LC2013")
set lane change model
bool setLatAlignment (std::string latAlignment="center")
set lateral lat
bool setLength (double length=5.0)
set length
bool setLength (std::string length)
set length (string version)
bool setLoadingDuration (double loadingDuration=90.0)
set loading duration
bool setLoadingDuration (std::string loadingDuration)
set loading duration (string version)
bool setMaxSpeed (double maxSpeed=70.0)
set max speed
bool setMaxSpeed (std::string maxSpeed)
set max speed (string version)
bool setMaxSpeedLat (double maxSpeedLat=1.0)
set max speed lat
bool setMaxSpeedLat (std::string maxSpeedLat)
set max speed lat (string version)
bool setMinGap (double minGap=2.5)
set min gap
bool setMinGap (std::string minGap)
set min gap (string version)
bool setMinGapLat (double minGapLat=0.12)
set min gap lat
bool setMinGapLat (std::string minGapLat)
set min gap lat (string version)
bool setPersonCapacity (int personCapacity=4)
set person capacity
bool setPersonCapacity (std::string personCapacity)
set person capacity (string version)
bool setShape (std::string shape)
set shape (string version)
bool setShape (SUMOVehicleShape shape=SVS_PASSENGER)
set shape
bool setSigma (double sigma=0.5)
set sigma
bool setSigma (std::string sigma)
set sigma (string version)
bool setSpeedDev (double speedDev=0.0)
set speed dev
bool setSpeedDev (std::string speedDev)
set speed dev (string version)
bool setSpeedFactor (double speedFactor=1.0)
set speed factor
bool setSpeedFactor (std::string speedFactor)
set speed factor (string version)
bool setTau (double tau=1.0)
set tau
bool setTau (std::string tau)
set tau (string version)
bool setVClass (SUMOVehicleClass vClass=SVC_PRIVATE)
set VClass
bool setVClass (std::string vClass)
set VClass (string version)
bool setVehicleTypeID (std::string vehicleTypeID)
set vehicleType ID
bool setWidth (double width=2.0)
set width
bool setWidth (std::string width)
set width (string version)
~GNECalibratorVehicleType ()
destructor
Private Attributes
double myAccel
The acceleration ability of vehicles of this type (in m/s^2)
double myBoardingDuration
The time required by a person to board the vehicle.
GNECalibrator * myCalibratorParent
pointer to calibrator parent
std::string myCarFollowModel
The model used for car following.
std::string myColor
This vehicle type's color.
int myContainerCapacity
The number of containers the vehicle can transport.
double myDecel
The deceleration ability of vehicles of this type (in m/s^2)
std::string myEmissionClass
An abstract emission class.
std::string myFilename
Image file for rendering vehicles of this type (should be grayscale to allow functional coloring)
double myImpatience
Willingess of drivers to impede vehicles with higher priority. See below for semantics.
std::string myLaneChangeModel
The model used for changing lanes.
std::string myLatAlignment
The preferred lateral alignment when using the sublane-model. One of (left, right, center, compact, nice, arbitrary).
double myLength
The vehicle's netto-length (length) (in m)
double myLoadingDuration
The time required to load a container onto the vehicle.
double myMaxSpeed
The vehicle's maximum velocity (in m/s)
double myMaxSpeedLat
The maximum lateral speed when using the sublane-model.
double myMinGap
Empty space after leader [m].
double myMinGapLat
The minimum lateral gap at a speed difference of 100km/h when using the sublane-model.
int myPersonCapacity
The number of persons (excluding an autonomous driver) the vehicle can transport.
SUMOVehicleShape myShape
How this vehicle is rendered.
double mySigma
Car-following model parameter.
double mySpeedDev
The deviation of the speedFactor; see below for details.
double mySpeedFactor
The vehicles expected multiplicator for lane speed limits.
double myTau
Car-following model parameter.
SUMOVehicleClass myVClass
An abstract vehicle class.
std::string myVehicleTypeID
vehicleType ID
double myWidth
The vehicle's width [m] (only used for drawing)
Detailed Description
vehicleType vehicleType used by GNECalibrators
Definition at line 50 of file GNECalibratorVehicleType.h.
Constructor & Destructor Documentation
GNECalibratorVehicleType::GNECalibratorVehicleType (GNECalibrator * calibratorParent)
constructor
Definition at line 61 of file GNECalibratorVehicleType.cpp.
References setAccel(), setBoardingDuration(), setCarFollowModel(), setColor(), setContainerCapacity(), setDecel(), setEmissionClass(), setFilename(), setImpatience(), setLaneChangeModel(), setLatAlignment(), setLength(), setLoadingDuration(), setMaxSpeed(), setMaxSpeedLat(), setMinGap(), setMinGapLat(), setPersonCapacity(), setShape(), setSigma(), setSpeedDev(), setSpeedFactor(), setTau(), setVClass(), and setWidth().
GNECalibratorVehicleType::GNECalibratorVehicleType (GNECalibrator * calibratorParent, std::string vehicleTypeID, double accel, double decel, double sigma, double tau, double length, double minGap, double maxSpeed, double speedFactor, double speedDev, const std::string & color, SUMOVehicleClass vClass, const std::string & emissionClass, SUMOVehicleShape shape, double width, const std::string & filename, double impatience, const std::string & laneChangeModel, const std::string & carFollowModel, int personCapacity, int containerCapacity, double boardingDuration, double loadingDuration, const std::string & latAlignment, double minGapLat, double maxSpeedLat)
parameter constructor
Definition at line 92 of file GNECalibratorVehicleType.cpp.
References setAccel(), setBoardingDuration(), setCarFollowModel(), setColor(), setContainerCapacity(), setDecel(), setEmissionClass(), setFilename(), setImpatience(), setLaneChangeModel(), setLatAlignment(), setLength(), setLoadingDuration(), setMaxSpeed(), setMaxSpeedLat(), setMinGap(), setMinGapLat(), setPersonCapacity(), setShape(), setSigma(), setSpeedDev(), setSpeedFactor(), setTau(), setVClass(), setVehicleTypeID(), and setWidth().
GNECalibratorVehicleType::~GNECalibratorVehicleType ()
destructor
Definition at line 129 of file GNECalibratorVehicleType.cpp.
Member Function Documentation
double GNECalibratorVehicleType::getAccel () const
get accel
Definition at line 151 of file GNECalibratorVehicleType.cpp.
References myAccel.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getBoardingDuration () const
get boarding duration
Definition at line 271 of file GNECalibratorVehicleType.cpp.
References myBoardingDuration.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
GNECalibrator * GNECalibratorVehicleType::getCalibratorParent () const
get pointer to calibrator parent
Definition at line 133 of file GNECalibratorVehicleType.cpp.
References myCalibratorParent.
Referenced by GNECalibratorVehicleTypeDialog::onCmdAccept().
std::string GNECalibratorVehicleType::getCarFollowModel () const
get car follow model
Definition at line 253 of file GNECalibratorVehicleType.cpp.
References myCarFollowModel.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
std::string GNECalibratorVehicleType::getColor () const
get color
Definition at line 205 of file GNECalibratorVehicleType.cpp.
References myColor.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
int GNECalibratorVehicleType::getContainerCapacity () const
get container capacity
Definition at line 265 of file GNECalibratorVehicleType.cpp.
References myContainerCapacity.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getDecel () const
get decel
Definition at line 157 of file GNECalibratorVehicleType.cpp.
References myDecel.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
std::string GNECalibratorVehicleType::getEmissionClass () const
get emission class
Definition at line 217 of file GNECalibratorVehicleType.cpp.
References myEmissionClass.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
std::string GNECalibratorVehicleType::getFilename () const
get filename
Definition at line 235 of file GNECalibratorVehicleType.cpp.
References myFilename.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getImpatience () const
get impatience
Definition at line 241 of file GNECalibratorVehicleType.cpp.
References myImpatience.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
std::string GNECalibratorVehicleType::getLaneChangeModel () const
get lane change model
Definition at line 247 of file GNECalibratorVehicleType.cpp.
References myLaneChangeModel.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
std::string GNECalibratorVehicleType::getLatAlignment () const
get lateral lat
Definition at line 283 of file GNECalibratorVehicleType.cpp.
References myLatAlignment.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getLength () const
get length
Definition at line 175 of file GNECalibratorVehicleType.cpp.
References myLength.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getLoadingDuration () const
get loading duration
Definition at line 277 of file GNECalibratorVehicleType.cpp.
References myLoadingDuration.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getMaxSpeed () const
get max speed
Definition at line 187 of file GNECalibratorVehicleType.cpp.
References myMaxSpeed.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getMaxSpeedLat () const
get max speed lat
Definition at line 295 of file GNECalibratorVehicleType.cpp.
References myMaxSpeedLat.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getMinGap () const
get min gap
Definition at line 181 of file GNECalibratorVehicleType.cpp.
References myMinGap.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getMinGapLat () const
get min gap lat
Definition at line 289 of file GNECalibratorVehicleType.cpp.
References myMinGapLat.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
int GNECalibratorVehicleType::getPersonCapacity () const
get person capacity
Definition at line 259 of file GNECalibratorVehicleType.cpp.
References myPersonCapacity.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
SUMOVehicleShape GNECalibratorVehicleType::getShape () const
get shape
Definition at line 223 of file GNECalibratorVehicleType.cpp.
References myShape.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getSigma () const
get sigma
Definition at line 163 of file GNECalibratorVehicleType.cpp.
References mySigma.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getSpeedDev () const
get speed dev
Definition at line 199 of file GNECalibratorVehicleType.cpp.
References mySpeedDev.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getSpeedFactor () const
get speed factor
Definition at line 193 of file GNECalibratorVehicleType.cpp.
References mySpeedFactor.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
SumoXMLTag GNECalibratorVehicleType::getTag () const
get tag
Definition at line 139 of file GNECalibratorVehicleType.cpp.
References SUMO_TAG_VTYPE.
Referenced by GNECalibratorVehicleTypeDialog::onCmdAccept().
double GNECalibratorVehicleType::getTau () const
get tau
Definition at line 169 of file GNECalibratorVehicleType.cpp.
References myTau.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
SUMOVehicleClass GNECalibratorVehicleType::getVClass () const
get VClass
Definition at line 211 of file GNECalibratorVehicleType.cpp.
References myVClass.
Referenced by GNECalibratorVehicleTypeDialog::setVClassLabelImage(), and GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
std::string GNECalibratorVehicleType::getVehicleTypeID () const
get VehicleTypeID
Definition at line 145 of file GNECalibratorVehicleType.cpp.
References myVehicleTypeID.
Referenced by GNECalibratorVehicleTypeDialog::onCmdSetVariable(), operator==(), and GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
double GNECalibratorVehicleType::getWidth () const
get width
Definition at line 229 of file GNECalibratorVehicleType.cpp.
References myWidth.
Referenced by GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues().
bool GNECalibratorVehicleType::operator== (const GNECalibratorVehicleType & calibratorVehicleType) const
overload operator ==
Definition at line 763 of file GNECalibratorVehicleType.cpp.
References getVehicleTypeID(), and myVehicleTypeID.
bool GNECalibratorVehicleType::setAccel (double accel = 2.6)
set accel
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 313 of file GNECalibratorVehicleType.cpp.
References myAccel.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setAccel().
bool GNECalibratorVehicleType::setAccel (std::string accel)
set accel (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 324 of file GNECalibratorVehicleType.cpp.
References setAccel().
bool GNECalibratorVehicleType::setBoardingDuration (double boardingDuration = 0.5)
set boarding duration
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 667 of file GNECalibratorVehicleType.cpp.
References myBoardingDuration.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setBoardingDuration().
bool GNECalibratorVehicleType::setBoardingDuration (std::string boardingDuration)
set boarding duration (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 678 of file GNECalibratorVehicleType.cpp.
References setBoardingDuration().
bool GNECalibratorVehicleType::setCarFollowModel (std::string carFollowModel = "Krauss")
set car follow model
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 606 of file GNECalibratorVehicleType.cpp.
References myCarFollowModel.
Referenced by GNECalibratorVehicleType(), and GNECalibratorVehicleTypeDialog::onCmdSetVariable().
bool GNECalibratorVehicleType::setColor (std::string color = "1,1,0")
set color
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 502 of file GNECalibratorVehicleType.cpp.
References myColor.
Referenced by GNECalibratorVehicleType(), and GNECalibratorVehicleTypeDialog::onCmdSetVariable().
bool GNECalibratorVehicleType::setContainerCapacity (int containerCapacity = 0)
set container capacity
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 640 of file GNECalibratorVehicleType.cpp.
References myContainerCapacity.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setContainerCapacity().
bool GNECalibratorVehicleType::setContainerCapacity (std::string containerCapacity)
set container capacity (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 651 of file GNECalibratorVehicleType.cpp.
References setContainerCapacity().
bool GNECalibratorVehicleType::setDecel (double decel = 4.5)
set decel
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 334 of file GNECalibratorVehicleType.cpp.
References myDecel.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setDecel().
bool GNECalibratorVehicleType::setDecel (std::string decel)
set decel (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 345 of file GNECalibratorVehicleType.cpp.
References setDecel().
bool GNECalibratorVehicleType::setEmissionClass (std::string emissionClass = "P_7_7")
set emission class
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 526 of file GNECalibratorVehicleType.cpp.
References myEmissionClass.
Referenced by GNECalibratorVehicleType(), and GNECalibratorVehicleTypeDialog::onCmdSetVariable().
bool GNECalibratorVehicleType::setFilename (std::string filename = "")
set filename
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 571 of file GNECalibratorVehicleType.cpp.
References myFilename.
Referenced by GNECalibratorVehicleType(), and GNECalibratorVehicleTypeDialog::onCmdSetVariable().
bool GNECalibratorVehicleType::setImpatience (double impatience = 0.0)
set impatience
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 578 of file GNECalibratorVehicleType.cpp.
References myImpatience.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setImpatience().
bool GNECalibratorVehicleType::setImpatience (std::string impatience)
set impatience (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 589 of file GNECalibratorVehicleType.cpp.
References setImpatience().
bool GNECalibratorVehicleType::setLaneChangeModel (std::string laneChangeModel = "LC2013")
set lane change model
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 599 of file GNECalibratorVehicleType.cpp.
References myLaneChangeModel.
Referenced by GNECalibratorVehicleType(), and GNECalibratorVehicleTypeDialog::onCmdSetVariable().
bool GNECalibratorVehicleType::setLatAlignment (std::string latAlignment = "center")
set lateral lat
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 709 of file GNECalibratorVehicleType.cpp.
References myLatAlignment.
Referenced by GNECalibratorVehicleType(), and GNECalibratorVehicleTypeDialog::onCmdSetVariable().
bool GNECalibratorVehicleType::setLength (double length = 5.0)
set length
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 397 of file GNECalibratorVehicleType.cpp.
References myLength.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setLength().
bool GNECalibratorVehicleType::setLength (std::string length)
set length (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 408 of file GNECalibratorVehicleType.cpp.
References setLength().
bool GNECalibratorVehicleType::setLoadingDuration (double loadingDuration = 90.0)
set loading duration
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 688 of file GNECalibratorVehicleType.cpp.
References myLoadingDuration.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setLoadingDuration().
bool GNECalibratorVehicleType::setLoadingDuration (std::string loadingDuration)
set loading duration (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 699 of file GNECalibratorVehicleType.cpp.
References setLoadingDuration().
bool GNECalibratorVehicleType::setMaxSpeed (double maxSpeed = 70.0)
set max speed
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 439 of file GNECalibratorVehicleType.cpp.
References myMaxSpeed.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setMaxSpeed().
bool GNECalibratorVehicleType::setMaxSpeed (std::string maxSpeed)
set max speed (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 450 of file GNECalibratorVehicleType.cpp.
References setMaxSpeed().
bool GNECalibratorVehicleType::setMaxSpeedLat (double maxSpeedLat = 1.0)
set max speed lat
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 742 of file GNECalibratorVehicleType.cpp.
References myMaxSpeedLat.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setMaxSpeedLat().
bool GNECalibratorVehicleType::setMaxSpeedLat (std::string maxSpeedLat)
set max speed lat (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 753 of file GNECalibratorVehicleType.cpp.
References setMaxSpeedLat().
bool GNECalibratorVehicleType::setMinGap (double minGap = 2.5)
set min gap
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 418 of file GNECalibratorVehicleType.cpp.
References myMinGap.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setMinGap().
bool GNECalibratorVehicleType::setMinGap (std::string minGap)
set min gap (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 429 of file GNECalibratorVehicleType.cpp.
References setMinGap().
bool GNECalibratorVehicleType::setMinGapLat (double minGapLat = 0.12)
set min gap lat
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 721 of file GNECalibratorVehicleType.cpp.
References myMinGapLat.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setMinGapLat().
bool GNECalibratorVehicleType::setMinGapLat (std::string minGapLat)
set min gap lat (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 732 of file GNECalibratorVehicleType.cpp.
References setMinGapLat().
bool GNECalibratorVehicleType::setPersonCapacity (int personCapacity = 4)
set person capacity
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 613 of file GNECalibratorVehicleType.cpp.
References myPersonCapacity.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setPersonCapacity().
bool GNECalibratorVehicleType::setPersonCapacity (std::string personCapacity)
set person capacity (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 624 of file GNECalibratorVehicleType.cpp.
References setPersonCapacity().
bool GNECalibratorVehicleType::setShape (std::string shape)
set shape (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 540 of file GNECalibratorVehicleType.cpp.
References canParseVehicleShape(), and getVehicleShapeID().
Referenced by GNECalibratorVehicleType(), and GNECalibratorVehicleTypeDialog::onCmdSetVariable().
bool GNECalibratorVehicleType::setShape (SUMOVehicleShape shape = SVS_PASSENGER)
set shape
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 533 of file GNECalibratorVehicleType.cpp.
References myShape.
bool GNECalibratorVehicleType::setSigma (double sigma = 0.5)
set sigma
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 355 of file GNECalibratorVehicleType.cpp.
References mySigma.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setSigma().
bool GNECalibratorVehicleType::setSigma (std::string sigma)
set sigma (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 366 of file GNECalibratorVehicleType.cpp.
References setSigma().
bool GNECalibratorVehicleType::setSpeedDev (double speedDev = 0.0)
set speed dev
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 481 of file GNECalibratorVehicleType.cpp.
References mySpeedDev.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setSpeedDev().
bool GNECalibratorVehicleType::setSpeedDev (std::string speedDev)
set speed dev (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 492 of file GNECalibratorVehicleType.cpp.
References setSpeedDev().
bool GNECalibratorVehicleType::setSpeedFactor (double speedFactor = 1.0)
set speed factor
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 460 of file GNECalibratorVehicleType.cpp.
References mySpeedFactor.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setSpeedFactor().
bool GNECalibratorVehicleType::setSpeedFactor (std::string speedFactor)
set speed factor (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 471 of file GNECalibratorVehicleType.cpp.
References setSpeedFactor().
bool GNECalibratorVehicleType::setTau (double tau = 1.0)
set tau
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 376 of file GNECalibratorVehicleType.cpp.
References myTau.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setTau().
bool GNECalibratorVehicleType::setTau (std::string tau)
set tau (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 387 of file GNECalibratorVehicleType.cpp.
References setTau().
bool GNECalibratorVehicleType::setVClass (SUMOVehicleClass vClass = SVC_PRIVATE)
set VClass
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 509 of file GNECalibratorVehicleType.cpp.
References myVClass.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setVClass().
bool GNECalibratorVehicleType::setVClass (std::string vClass)
set VClass (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 516 of file GNECalibratorVehicleType.cpp.
References canParseVehicleClasses(), getVehicleClassID(), and setVClass().
bool GNECalibratorVehicleType::setVehicleTypeID (std::string vehicleTypeID)
set vehicleType ID
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 300 of file GNECalibratorVehicleType.cpp.
References GNEViewNet::getNet(), GNEAdditional::getViewNet(), myCalibratorParent, myVehicleTypeID, and GNENet::vehicleTypeExists().
Referenced by GNECalibratorVehicleType(), and GNECalibratorVehicleTypeDialog::onCmdSetVariable().
bool GNECalibratorVehicleType::setWidth (double width = 2.0)
set width
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 550 of file GNECalibratorVehicleType.cpp.
References myWidth.
Referenced by GNECalibratorVehicleType(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), and setWidth().
bool GNECalibratorVehicleType::setWidth (std::string width)
set width (string version)
Returns
true if was sucesfully set, or false if value isn't valid
Definition at line 561 of file GNECalibratorVehicleType.cpp.
References setWidth().
Field Documentation
double GNECalibratorVehicleType::myAccel private
The acceleration ability of vehicles of this type (in m/s^2)
Definition at line 387 of file GNECalibratorVehicleType.h.
Referenced by getAccel(), and setAccel().
double GNECalibratorVehicleType::myBoardingDuration private
The time required by a person to board the vehicle.
Definition at line 447 of file GNECalibratorVehicleType.h.
Referenced by getBoardingDuration(), and setBoardingDuration().
GNECalibrator* GNECalibratorVehicleType::myCalibratorParent private
pointer to calibrator parent
Definition at line 381 of file GNECalibratorVehicleType.h.
Referenced by getCalibratorParent(), and setVehicleTypeID().
std::string GNECalibratorVehicleType::myCarFollowModel private
The model used for car following.
Definition at line 438 of file GNECalibratorVehicleType.h.
Referenced by getCarFollowModel(), and setCarFollowModel().
std::string GNECalibratorVehicleType::myColor private
This vehicle type's color.
Definition at line 414 of file GNECalibratorVehicleType.h.
Referenced by getColor(), and setColor().
int GNECalibratorVehicleType::myContainerCapacity private
The number of containers the vehicle can transport.
Definition at line 444 of file GNECalibratorVehicleType.h.
Referenced by getContainerCapacity(), and setContainerCapacity().
double GNECalibratorVehicleType::myDecel private
The deceleration ability of vehicles of this type (in m/s^2)
Definition at line 390 of file GNECalibratorVehicleType.h.
Referenced by getDecel(), and setDecel().
std::string GNECalibratorVehicleType::myEmissionClass private
An abstract emission class.
Definition at line 420 of file GNECalibratorVehicleType.h.
Referenced by getEmissionClass(), and setEmissionClass().
std::string GNECalibratorVehicleType::myFilename private
Image file for rendering vehicles of this type (should be grayscale to allow functional coloring)
Definition at line 429 of file GNECalibratorVehicleType.h.
Referenced by getFilename(), and setFilename().
double GNECalibratorVehicleType::myImpatience private
Willingess of drivers to impede vehicles with higher priority. See below for semantics.
Definition at line 432 of file GNECalibratorVehicleType.h.
Referenced by getImpatience(), and setImpatience().
std::string GNECalibratorVehicleType::myLaneChangeModel private
The model used for changing lanes.
Definition at line 435 of file GNECalibratorVehicleType.h.
Referenced by getLaneChangeModel(), and setLaneChangeModel().
std::string GNECalibratorVehicleType::myLatAlignment private
The preferred lateral alignment when using the sublane-model. One of (left, right, center, compact, nice, arbitrary).
Definition at line 453 of file GNECalibratorVehicleType.h.
Referenced by getLatAlignment(), and setLatAlignment().
double GNECalibratorVehicleType::myLength private
The vehicle's netto-length (length) (in m)
Definition at line 399 of file GNECalibratorVehicleType.h.
Referenced by getLength(), and setLength().
double GNECalibratorVehicleType::myLoadingDuration private
The time required to load a container onto the vehicle.
Definition at line 450 of file GNECalibratorVehicleType.h.
Referenced by getLoadingDuration(), and setLoadingDuration().
double GNECalibratorVehicleType::myMaxSpeed private
The vehicle's maximum velocity (in m/s)
Definition at line 405 of file GNECalibratorVehicleType.h.
Referenced by getMaxSpeed(), and setMaxSpeed().
double GNECalibratorVehicleType::myMaxSpeedLat private
The maximum lateral speed when using the sublane-model.
Definition at line 459 of file GNECalibratorVehicleType.h.
Referenced by getMaxSpeedLat(), and setMaxSpeedLat().
double GNECalibratorVehicleType::myMinGap private
Empty space after leader [m].
Definition at line 402 of file GNECalibratorVehicleType.h.
Referenced by getMinGap(), and setMinGap().
double GNECalibratorVehicleType::myMinGapLat private
The minimum lateral gap at a speed difference of 100km/h when using the sublane-model.
Definition at line 456 of file GNECalibratorVehicleType.h.
Referenced by getMinGapLat(), and setMinGapLat().
int GNECalibratorVehicleType::myPersonCapacity private
The number of persons (excluding an autonomous driver) the vehicle can transport.
Definition at line 441 of file GNECalibratorVehicleType.h.
Referenced by getPersonCapacity(), and setPersonCapacity().
SUMOVehicleShape GNECalibratorVehicleType::myShape private
How this vehicle is rendered.
Definition at line 423 of file GNECalibratorVehicleType.h.
Referenced by getShape(), and setShape().
double GNECalibratorVehicleType::mySigma private
Car-following model parameter.
Definition at line 393 of file GNECalibratorVehicleType.h.
Referenced by getSigma(), and setSigma().
double GNECalibratorVehicleType::mySpeedDev private
The deviation of the speedFactor; see below for details.
Definition at line 411 of file GNECalibratorVehicleType.h.
Referenced by getSpeedDev(), and setSpeedDev().
double GNECalibratorVehicleType::mySpeedFactor private
The vehicles expected multiplicator for lane speed limits.
Definition at line 408 of file GNECalibratorVehicleType.h.
Referenced by getSpeedFactor(), and setSpeedFactor().
double GNECalibratorVehicleType::myTau private
Car-following model parameter.
Definition at line 396 of file GNECalibratorVehicleType.h.
Referenced by getTau(), and setTau().
SUMOVehicleClass GNECalibratorVehicleType::myVClass private
An abstract vehicle class.
Definition at line 417 of file GNECalibratorVehicleType.h.
Referenced by getVClass(), and setVClass().
std::string GNECalibratorVehicleType::myVehicleTypeID private
vehicleType ID
Definition at line 384 of file GNECalibratorVehicleType.h.
Referenced by getVehicleTypeID(), operator==(), and setVehicleTypeID().
double GNECalibratorVehicleType::myWidth private
The vehicle's width [m] (only used for drawing)
Definition at line 426 of file GNECalibratorVehicleType.h.
Referenced by getWidth(), and setWidth().
The documentation for this class was generated from the following files:
GNECalibratorVehicleType.h
GNECalibratorVehicleType.cpp