SUMO - Simulation of Urban MObility: MSMoveReminder Class Reference
MSMoveReminder Class Reference
Something on a lane to be noticed about vehicle movement.
#include <MSMoveReminder.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
Public Member Functions
const std::string & getDescription () const
const MSLane * getLane () const
Returns the lane the reminder works on.
MSMoveReminder (const std::string &description, MSLane *const lane=0, const bool doAdd=true)
Constructor.
virtual void notifyMoveInternal (const SUMOVehicle &veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane)
Internal notification about the vehicle moves.
void setDescription (const std::string &description)
virtual ~MSMoveReminder ()
Destructor.
Interface methods, to be derived by subclasses
virtual bool notifyEnter (SUMOVehicle &veh, Notification reason, const MSLane *enteredLane)
Checks whether the reminder is activated by a vehicle entering the lane.
virtual bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
virtual bool notifyLeave (SUMOVehicle &veh, double lastPos, Notification reason, const MSLane *enteredLane=0)
Called if the vehicle leaves the reminder's lane.
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
MSLane *const myLane
Lane on which the reminder works.
Private Member Functions
MSMoveReminder & operator= (const MSMoveReminder &)
Private Attributes
std::map< SUMOVehicle *, std::pair< SUMOTime, double > > myLastVehicleUpdateValues
Detailed Description
Something on a lane to be noticed about vehicle movement.
Base class of all move-reminders. During move, the vehicles call notifyMove() for all reminders on their current lane (all lanes they pass during one step). If a vehicle enters the lane the reminder is positioned at during insertion or lanechange notifyEnter() is called. If a vehicle leaves the reminder lane it calls notifyLeave().
The reminder knows whom to tell about move, insertion and lanechange. The vehicles will remove the reminder that is not notifyMove() from their reminder container.
See also
MSLane::addMoveReminder
MSLane::getMoveReminder
Note
: cannot inherit from Named because it would couse double inheritance
Definition at line 71 of file MSMoveReminder.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 96 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSMoveReminder::MSMoveReminder (const std::string & description, MSLane *const lane = 0, const bool doAdd = true)
Constructor.
Parameters
[in] lane Lane on which the reminder will work.
[in] doAdd whether to add the reminder to the lane
Definition at line 40 of file MSMoveReminder.cpp.
References MSLane::addMoveReminder(), and myLane.
virtual MSMoveReminder::~MSMoveReminder () inline virtual
Destructor.
Definition at line 83 of file MSMoveReminder.h.
Member Function Documentation
const std::string& MSMoveReminder::getDescription () const inline
Definition at line 231 of file MSMoveReminder.h.
References myDescription, and removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::setDeviceParameter().
const MSLane* MSMoveReminder::getLane () const inline
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 90 of file MSMoveReminder.h.
References myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
virtual bool MSMoveReminder::notifyEnter (SUMOVehicle & veh, Notification reason, const MSLane * enteredLane) inline virtual
Checks whether the reminder is activated by a vehicle entering the lane.
Lane change means in this case that the vehicle changes to the lane the reminder is placed at.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
True if vehicle enters the reminder.
See also
Notification
Reimplemented in MSE2Collector, MSDevice_SSM, MSMeanData::MeanDataValueTracker, MSDevice_Routing, MSTriggeredRerouter, MSMeanData_Net::MSLaneMeanDataValues, MSCalibrator::VehicleRemover, MSInductLoop, MSDevice_Tripinfo, MSMeanData_Amitran::MSLaneMeanDataValues, MSDevice_Example, MSDevice_BTsender, MSMeanData::MeanDataValues, MSDevice_BTreceiver, MSRouteProbe, MSDevice_Vehroutes, and MSDevice_Transportable.
Definition at line 135 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
virtual bool MSMoveReminder::notifyLeave (SUMOVehicle & veh, double lastPos, Notification reason, const MSLane * enteredLane = 0) inline virtual
Called if the vehicle leaves the reminder's lane.
Informs if vehicle leaves reminder lane (due to lane change, removal from the network, or leaving to the next lane). The default is to do nothing.
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See also
Notification
Returns
True if the reminder wants to receive further info.
Reimplemented in MSE2Collector, MSDevice_SSM, MSMeanData::MeanDataValueTracker, MSE3Collector::MSE3LeaveReminder, MSTriggeredRerouter, MSInductLoop, MSDevice_BTsender, MSDevice_BTreceiver, MSMeanData::MeanDataValues, MSDevice_Tripinfo, MSDevice_Example, MSInstantInductLoop, MSDevice_Vehroutes, MSE3Collector::MSE3EntryReminder, MSMeanData_Net::MSLaneMeanDataValues, and MSDevice_Transportable.
Definition at line 181 of file MSMoveReminder.h.
References UNUSED_PARAMETER, and updateDetector().
virtual bool MSMoveReminder::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) inline virtual
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the reminder completely.
Reimplemented in MSE2Collector, MSDevice_SSM, MSE3Collector::MSE3LeaveReminder, MSTriggeredRerouter, MSInductLoop, MSDevice_BTsender, MSMeanData::MeanDataValues, MSDevice_BTreceiver, MSDevice_Emissions, MSDevice_Tripinfo, MSInstantInductLoop, MSE3Collector::MSE3EntryReminder, MSDevice_Example, MSDevice_Battery, and MSDevice_Transportable.
Definition at line 156 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
virtual void MSMoveReminder::notifyMoveInternal (const SUMOVehicle & veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane) inline virtual
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] frontOnLane time the front of the vehicle spent on the lane.
[in] timeOnLane time some part of the vehicle spent on the lane.
[in] meanSpeedFrontOnLane Average speed for the time that the front is on the lane.
[in] meanSpeedVehicleOnLane Average speed for the time that the vehicle is on the lane (with front or back).
[in] travelledDistanceFrontOnLane distance travelled while overlapping with the lane.
[in] travelledDistanceVehicleOnLane distance travelled while front was on the lane.
Reimplemented in MSMeanData::MeanDataValueTracker, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 211 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and updateDetector().
MSMoveReminder& MSMoveReminder::operator= (const MSMoveReminder &) private
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected
Definition at line 94 of file MSMoveReminder.cpp.
References myLastVehicleUpdateValues.
Referenced by getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and updateDetector().
void MSMoveReminder::setDescription (const std::string & description) inline
Definition at line 227 of file MSMoveReminder.h.
References myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Definition at line 51 of file MSMoveReminder.cpp.
References myLastVehicleUpdateValues, notifyMoveInternal(), removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by notifyLeave(), and MEVehicle::updateDetectorForWriting().
Field Documentation
std::string MSMoveReminder::myDescription protected
a description of this moveReminder
Definition at line 243 of file MSMoveReminder.h.
Referenced by getDescription(), and setDescription().
MSLane* const MSMoveReminder::myLane protected
Lane on which the reminder works.
Definition at line 241 of file MSMoveReminder.h.
Referenced by MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), getLane(), MSMoveReminder(), MSInductLoop::notifyEnter(), and MSMeanData::MeanDataValueTracker::reset().
std::map<SUMOVehicle*, std::pair<SUMOTime, double> > MSMoveReminder::myLastVehicleUpdateValues private
Definition at line 246 of file MSMoveReminder.h.
Referenced by removeFromVehicleUpdateValues(), and updateDetector().
The documentation for this class was generated from the following files:
MSMoveReminder.h
MSMoveReminder.cpp