SUMO - Simulation of Urban MObility: TraCI_Route Class Reference
TraCI_Route Class Reference
C++ TraCI client API implementation.
#include <TraCI_Route.h>
Static Public Member Functions
static void add (const std::string &routeID, const std::vector< std::string > &edgeIDs)
static std::vector< std::string > getEdges (const std::string &routeID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static std::string getParameter (const std::string &routeID, const std::string &param)
static const MSRoute * getRoute (const std::string &id)
static void setParameter (const std::string &routeID, const std::string &key, const std::string &value)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
TraCI_Route & operator= (const TraCI_Route &src)
invalidated assignment operator
TraCI_Route ()
invalidated standard constructor
TraCI_Route (const TraCI_Route &src)
invalidated copy constructor
Detailed Description
C++ TraCI client API implementation.
Definition at line 51 of file TraCI_Route.h.
Constructor & Destructor Documentation
TraCI_Route::TraCI_Route () private
invalidated standard constructor
TraCI_Route::TraCI_Route (const TraCI_Route & src) private
invalidated copy constructor
Member Function Documentation
void TraCI_Route::add (const std::string & routeID, const std::vector< std::string > & edgeIDs) static
Definition at line 82 of file TraCI_Route.cpp.
References MSRoute::dictionary(), and MSEdge::dictionary().
Referenced by TraCIServerAPI_Route::processSet().
std::vector< std::string > TraCI_Route::getEdges (const std::string & routeID) static
Definition at line 52 of file TraCI_Route.cpp.
References MSRoute::getEdges(), and getRoute().
Referenced by TraCIServerAPI_Route::processGet().
int TraCI_Route::getIDCount () static
Definition at line 63 of file TraCI_Route.cpp.
References getIDList().
Referenced by TraCIServerAPI_Route::processGet().
std::vector< std::string > TraCI_Route::getIDList () static
Definition at line 45 of file TraCI_Route.cpp.
References MSRoute::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_Route::processGet().
std::string TraCI_Route::getParameter (const std::string & routeID, const std::string & param) static
Definition at line 69 of file TraCI_Route.cpp.
References Parameterised::getParameter(), and getRoute().
Referenced by TraCIServerAPI_Route::processGet().
const MSRoute * TraCI_Route::getRoute (const std::string & id) static
Definition at line 99 of file TraCI_Route.cpp.
References MSRoute::dictionary().
Referenced by getEdges(), getParameter(), and setParameter().
TraCI_Route& TraCI_Route::operator= (const TraCI_Route & src) private
invalidated assignment operator
void TraCI_Route::setParameter (const std::string & routeID, const std::string & key, const std::string & value) static
Definition at line 75 of file TraCI_Route.cpp.
References Parameterised::addParameter(), and getRoute().
Referenced by TraCIServerAPI_Route::processSet().
static void TraCI_Route::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
static void TraCI_Route::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
TraCI_Route.h
TraCI_Route.cpp