SUMO - Simulation of Urban MObility: RODFDetector Class Reference
RODFDetector Class Reference
Class representing a detector within the DFROUTER.
#include <RODFDetector.h>
Public Member Functions
void addFollowingDetector (const RODFDetector *det)
void addPriorDetector (const RODFDetector *det)
void addRoute (RODFRouteDesc &nrd)
void addRoutes (RODFRouteCont *routes)
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void buildDestinationDistribution (const RODFDetectorCon &detectors, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, const RODFNet &net, std::map< SUMOTime, RandomDistributor< int > * > &into) const
void computeSplitProbabilities (const RODFNet *net, const RODFDetectorCon &detectors, const RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
const std::set< const RODFDetector * > & getFollowerDetectors () const
const std::string & getID () const
Returns the id.
const std::set< const RODFDetector * > & getPriorDetectors () const
const std::vector< RODFRouteDesc > & getRouteVector () const
const std::vector< std::map< RODFEdge *, double > > & getSplitProbabilities () const
bool hasRoutes () const
RODFDetector (const std::string &id, const std::string &laneID, double pos, const RODFDetectorType type)
Constructor.
RODFDetector (const std::string &id, const RODFDetector &f)
Constructor.
void setID (const std::string &newID)
resets the id
void setType (RODFDetectorType type)
~RODFDetector ()
Destructor.
Atomar getter methods
const std::string & getLaneID () const
Returns the id of the lane this detector is placed on.
std::string getEdgeID () const
Returns the id of the edge this detector is placed on.
double getPos () const
Returns the position at which the detector lies.
RODFDetectorType getType () const
Returns the type of the detector.
Writing methods
bool writeEmitterDefinition (const std::string &file, const std::map< SUMOTime, RandomDistributor< int > * > &dists, const RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, bool includeUnusedRoutes, double scale, bool insertionsOnly, double defaultSpeed) const
bool writeRoutes (std::vector< std::string > &saved, OutputDevice &out)
void writeSingleSpeedTrigger (const std::string &file, const RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, double defaultSpeed)
void writeEndRerouterDetectors (const std::string &file)
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Member Functions
double computeDistanceFactor (const RODFRouteDesc &rd) const
int getFlowFor (const ROEdge *edge, SUMOTime time) const
Protected Attributes
std::set< const RODFDetector * > myFollowingDetectors
std::string myID
The name of the object.
std::string myLaneID
double myPosition
std::set< const RODFDetector * > myPriorDetectors
std::map< std::string, RODFEdge * > myRoute2Edge
RODFRouteCont * myRoutes
std::vector< std::map< RODFEdge *, double > > mySplitProbabilities
RODFDetectorType myType
Private Member Functions
RODFDetector & operator= (const RODFDetector &src)
Invalidated assignment operator.
RODFDetector (const RODFDetector &src)
Invalidated copy constructor.
Detailed Description
Class representing a detector within the DFROUTER.
Definition at line 89 of file RODFDetector.h.
Constructor & Destructor Documentation
RODFDetector::RODFDetector (const std::string & id, const std::string & laneID, double pos, const RODFDetectorType type)
Constructor.
This constructor is used when detectors are read from a file
Parameters
[in] id The id of the detector
[in] laneID The id of the lane the detector is placed at
[in] pos The position of the detector at the lane
[in] type The df-router type of the detector
See also
RODFDetectorType
Definition at line 62 of file RODFDetector.cpp.
Referenced by RODFDetectorCon::mesoJoin().
RODFDetector::RODFDetector (const std::string & id, const RODFDetector & f)
Constructor.
This constructor is used when detectors shall be joined
Parameters
[in] id The id of the detector
[in] f A detector from which routes shall be copied
Definition at line 67 of file RODFDetector.cpp.
References myRoutes.
RODFDetector::~RODFDetector ()
Destructor.
Definition at line 76 of file RODFDetector.cpp.
References myRoutes.
RODFDetector::RODFDetector (const RODFDetector & src) private
Invalidated copy constructor.
Member Function Documentation
void RODFDetector::addFollowingDetector (const RODFDetector * det)
Definition at line 240 of file RODFDetector.cpp.
References myFollowingDetectors.
Referenced by getType().
void RODFDetector::addPriorDetector (const RODFDetector * det)
Definition at line 234 of file RODFDetector.cpp.
References myPriorDetectors.
Referenced by RODFNet::buildDetectorDependencies(), and getType().
void RODFDetector::addRoute (RODFRouteDesc & nrd)
Definition at line 266 of file RODFDetector.cpp.
References RODFRouteCont::addRouteDesc(), and myRoutes.
Referenced by getType().
void RODFDetector::addRoutes (RODFRouteCont * routes)
Definition at line 259 of file RODFDetector.cpp.
References myRoutes.
Referenced by getType().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
void RODFDetector::buildDestinationDistribution (const RODFDetectorCon & detectors, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, const RODFNet & net, std::map< SUMOTime, RandomDistributor< int > * > & into) const
Definition at line 174 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, DISCARDED_DETECTOR, RODFRouteCont::get(), RODFDetectorCon::getAnyDetectorForEdge(), getSplitProbabilities(), RODFNet::hasDetector(), Named::myID, myRoutes, myType, and WRITE_ERROR.
Referenced by getType(), and RODFDetectorCon::writeEmitters().
double RODFDetector::computeDistanceFactor (const RODFRouteDesc & rd) const protected
Definition at line 88 of file RODFDetector.cpp.
References RODFRouteDesc::edges2Pass.
Referenced by getSplitProbabilities().
void RODFDetector::computeSplitProbabilities (const RODFNet * net, const RODFDetectorCon & detectors, const RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 99 of file RODFDetector.cpp.
References RODFRouteDesc::edges2Pass, RODFRouteCont::get(), RODFDetectorCon::getAggFlowFor(), OptionsCont::getBool(), ROEdge::getNumSuccessors(), OptionsCont::getOptions(), ROEdge::getPredecessors(), RODFNet::hasDetector(), myRoute2Edge, myRoutes, mySplitProbabilities, and RODFRouteDesc::routename.
Referenced by getType().
std::string RODFDetector::getEdgeID () const inline
Returns the id of the edge this detector is placed on.
Returns
The id of the edge this detector is placed on
Definition at line 134 of file RODFDetector.h.
References myLaneID.
Referenced by RODFDetectorCon::writeEmitters(), and RODFDetectorCon::writeSpeedTrigger().
int RODFDetector::getFlowFor (const ROEdge * edge, SUMOTime time) const protected
Referenced by getSplitProbabilities().
const std::set< const RODFDetector * > & RODFDetector::getFollowerDetectors () const
Definition at line 252 of file RODFDetector.cpp.
References myFollowingDetectors.
Referenced by getType(), and RODFDetectorCon::guessEmptyFlows().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), MSNet::addParkingArea(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), TraCI_Vehicle::getBestLanes(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), TraCI_Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), TraCI_Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), TraCI_Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSNet::getParkingAreaID(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), TraCI_Vehicle::getRoadID(), TraCI_Vehicle::getRouteID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_SSM::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSDevice_SSM::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_SSM::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingZone(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), toString(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSDevice_SSM::updateEncounter(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSPModel_Striping::PState::moveToNextLane(), operator<<(), TraCIServerAPI_Vehicle::processSet(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), MSAbstractLaneChangeModel::updateShadowLane(), and TraCIServerAPI_Vehicle::vtdMap().
const std::string& RODFDetector::getLaneID () const inline
Returns the id of the lane this detector is placed on.
Returns
The id of the lane this detector is placed on
Definition at line 126 of file RODFDetector.h.
References myLaneID.
Referenced by RODFDetectorCon::addDetector(), RODFNet::getDetectorEdge(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), RODFDetectorCon::writeSpeedTrigger(), and RODFDetectorCon::writeValidationDetectors().
double RODFDetector::getPos () const inline
Returns the position at which the detector lies.
Returns
The position of the detector at the lane
Definition at line 142 of file RODFDetector.h.
References myPosition.
Referenced by RODFNet::buildEdgeFlowMap(), RODFNet::getAbsPos(), RODFNet::mesoJoin(), RODFDetectorCon::writeEmitters(), and RODFDetectorCon::writeValidationDetectors().
const std::set< const RODFDetector * > & RODFDetector::getPriorDetectors () const
Definition at line 246 of file RODFDetector.cpp.
References myPriorDetectors.
Referenced by getType(), and RODFDetectorCon::guessEmptyFlows().
const std::vector< RODFRouteDesc > & RODFDetector::getRouteVector () const
Definition at line 228 of file RODFDetector.cpp.
References RODFRouteCont::get(), and myRoutes.
Referenced by RODFNet::buildDetectorDependencies(), and getType().
const std::vector<std::map<RODFEdge*, double> >& RODFDetector::getSplitProbabilities () const inline
Definition at line 195 of file RODFDetector.h.
References computeDistanceFactor(), getFlowFor(), and mySplitProbabilities.
Referenced by buildDestinationDistribution().
RODFDetectorType RODFDetector::getType () const inline
Returns the type of the detector.
Returns
This detector's type
See also
RODFDetectorType
Definition at line 151 of file RODFDetector.h.
References addFollowingDetector(), addPriorDetector(), addRoute(), addRoutes(), buildDestinationDistribution(), computeSplitProbabilities(), getFollowerDetectors(), getPriorDetectors(), getRouteVector(), hasRoutes(), myType, setType(), writeEmitterDefinition(), writeEndRerouterDetectors(), writeRoutes(), and writeSingleSpeedTrigger().
Referenced by RODFNet::buildRoutes(), RODFNet::hasInBetweenDetectorsOnly(), RODFNet::hasSourceDetector(), RODFNet::isFalseSource(), writeEmitterDefinition(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), RODFDetectorCon::writeSpeedTrigger(), and RODFDetectorCon::writeValidationDetectors().
bool RODFDetector::hasRoutes () const
Definition at line 275 of file RODFDetector.cpp.
References RODFRouteCont::get(), and myRoutes.
Referenced by RODFNet::buildDetectorDependencies(), and getType().
RODFDetector& RODFDetector::operator= (const RODFDetector & src) private
Invalidated assignment operator.
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::Distribution_Parameterized(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void RODFDetector::setType (RODFDetectorType type)
Definition at line 82 of file RODFDetector.cpp.
References myType.
Referenced by getType().
bool RODFDetector::writeEmitterDefinition (const std::string & file, const std::map< SUMOTime, RandomDistributor< int > * > & dists, const RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, bool includeUnusedRoutes, double scale, bool insertionsOnly, double defaultSpeed) const
Definition at line 281 of file RODFDetector.cpp.
References TplConvert::_2double(), TplConvert::_2int(), OutputDevice::close(), OutputDevice::closeTag(), RandomDistributor< T >::get(), RODFRouteCont::get(), OptionsCont::getBool(), OutputDevice::getDevice(), RODFDetectorFlows::getFlowDefs(), Named::getID(), OptionsCont::getOptions(), RandomDistributor< T >::getOverallProb(), OptionsCont::getString(), getType(), OptionsCont::isSet(), RODFDetectorFlows::knows(), Named::myID, myLaneID, myPosition, myRoutes, OutputDevice::openTag(), SOURCE_DETECTOR, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_DEPART, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_VEHICLE, time2string(), toString(), WRITE_ERROR, OutputDevice::writeAttr(), OutputDevice::writeNonEmptyAttr(), and OutputDevice::writeXMLHeader().
Referenced by getType(), and RODFDetectorCon::writeEmitters().
void RODFDetector::writeEndRerouterDetectors (const std::string & file)
Referenced by getType().
bool RODFDetector::writeRoutes (std::vector< std::string > & saved, OutputDevice & out)
Definition at line 422 of file RODFDetector.cpp.
References myRoutes, and RODFRouteCont::save().
Referenced by getType().
void RODFDetector::writeSingleSpeedTrigger (const std::string & file, const RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, double defaultSpeed)
Definition at line 432 of file RODFDetector.cpp.
References OutputDevice::close(), OutputDevice::closeTag(), OutputDevice::getDevice(), RODFDetectorFlows::getFlowDefs(), MAX2(), Named::myID, OutputDevice::openTag(), SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_TAG_STEP, time2string(), OutputDevice::writeAttr(), and OutputDevice::writeXMLHeader().
Referenced by getType(), and RODFDetectorCon::writeSpeedTrigger().
Field Documentation
std::set<const RODFDetector*> RODFDetector::myFollowingDetectors protected
Definition at line 209 of file RODFDetector.h.
Referenced by addFollowingDetector(), and getFollowerDetectors().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::string RODFDetector::myLaneID protected
Definition at line 205 of file RODFDetector.h.
Referenced by getEdgeID(), getLaneID(), and writeEmitterDefinition().
double RODFDetector::myPosition protected
Definition at line 206 of file RODFDetector.h.
Referenced by getPos(), and writeEmitterDefinition().
std::set<const RODFDetector*> RODFDetector::myPriorDetectors protected
Definition at line 209 of file RODFDetector.h.
Referenced by addPriorDetector(), and getPriorDetectors().
std::map<std::string, RODFEdge*> RODFDetector::myRoute2Edge protected
Definition at line 211 of file RODFDetector.h.
Referenced by computeSplitProbabilities().
RODFRouteCont* RODFDetector::myRoutes protected
Definition at line 208 of file RODFDetector.h.
Referenced by addRoute(), addRoutes(), buildDestinationDistribution(), computeSplitProbabilities(), getRouteVector(), hasRoutes(), RODFDetector(), writeEmitterDefinition(), writeRoutes(), and ~RODFDetector().
std::vector<std::map<RODFEdge*, double> > RODFDetector::mySplitProbabilities protected
Definition at line 210 of file RODFDetector.h.
Referenced by computeSplitProbabilities(), and getSplitProbabilities().
RODFDetectorType RODFDetector::myType protected
Definition at line 207 of file RODFDetector.h.
Referenced by buildDestinationDistribution(), getType(), and setType().
The documentation for this class was generated from the following files:
RODFDetector.h
RODFDetector.cpp