SUMO - Simulation of Urban MObility: GNEAdditionalFrame::SelectorParentLanes Class Reference
GNEAdditionalFrame::SelectorParentLanes Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
std::string getIdsSelected () const
get list of selecte id's in string format
void hideList ()
hide SelectorParentLanes
bool isUseSelectedLanesEnable () const
get status of checkBox UseSelectedLanes
SelectorParentLanes (FXComposite *parent, GNEViewNet *viewNet)
FOX-declaration.
void showList (std::string search="")
Show list of SelectorParentLanes.
void updateUseSelectedLanes ()
~SelectorParentLanes ()
destructor
FOX-callbacks
called when user trigger checkBox of useSelectedLanes
long onCmdUseSelectedLanes (FXObject *, FXSelector, void *)
long onCmdTypeInSearchBox (FXObject *, FXSelector, void *)
called when user type in search box
long onCmdSelectLane (FXObject *, FXSelector, void *)
called when user select a lane of the list
long onCmdClearSelection (FXObject *, FXSelector, void *)
called when clear selection button is pressed
long onCmdInvertSelection (FXObject *, FXSelector, void *)
called when invert selection button is pressed
long onCmdHelp (FXObject *, FXSelector, void *)
Called when help button is pressed.
Protected Member Functions
SelectorParentLanes ()
FOX needs this.
Private Attributes
FXButton * clearLanesSelection
button for clear selection
FXButton * helpLanes
button for help
FXButton * invertLanesSelection
button for invert selection
FXTextField * myLanesSearch
text field for search lane IDs
FXList * myList
List of SelectorParentLanes.
FXCheckButton * myUseSelectedLanesCheckButton
CheckBox for selected lanes.
GNEViewNet * myViewNet
viewNet associated to GNEAdditionalFrame
Detailed Description
Definition at line 549 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame::SelectorParentLanes::SelectorParentLanes (FXComposite * parent, GNEViewNet * viewNet)
FOX-declaration.
constructor
Definition at line 1672 of file GNEAdditionalFrame.cpp.
References clearLanesSelection, GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonRectangular, GUIDesignCheckButtonAttribute, GUIDesignList, GUIDesignTextField, GUIDesignTextFieldNCol, helpLanes, hideList(), invertLanesSelection, MID_GNE_CLEARLANESELECTION, MID_GNE_INVERTLANESELECTION, MID_GNE_SEARCHLANE, MID_GNE_SELECTLANE, MID_GNE_USESELECTEDLANES, MID_HELP, myLanesSearch, myList, myUseSelectedLanesCheckButton, SUMO_TAG_LANE, and toString().
GNEAdditionalFrame::SelectorParentLanes::~SelectorParentLanes ()
destructor
Definition at line 1701 of file GNEAdditionalFrame.cpp.
GNEAdditionalFrame::SelectorParentLanes::SelectorParentLanes () inline protected
FOX needs this.
Definition at line 598 of file GNEAdditionalFrame.h.
Member Function Documentation
std::string GNEAdditionalFrame::SelectorParentLanes::getIdsSelected () const
get list of selecte id's in string format
Definition at line 1705 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::getIdsSelected(), and myList.
Referenced by GNEAdditionalFrame::addAdditional().
void GNEAdditionalFrame::SelectorParentLanes::hideList ()
hide SelectorParentLanes
Definition at line 1727 of file GNEAdditionalFrame.cpp.
References GNEFrame::hide().
Referenced by SelectorParentLanes(), and GNEAdditionalFrame::setParametersOfAdditional().
bool GNEAdditionalFrame::SelectorParentLanes::isUseSelectedLanesEnable () const
get status of checkBox UseSelectedLanes
Definition at line 1744 of file GNEAdditionalFrame.cpp.
References myUseSelectedLanesCheckButton.
Referenced by GNEAdditionalFrame::addAdditional().
long GNEAdditionalFrame::SelectorParentLanes::onCmdClearSelection (FXObject * , FXSelector , void *)
called when clear selection button is pressed
Definition at line 1791 of file GNEAdditionalFrame.cpp.
References myList.
long GNEAdditionalFrame::SelectorParentLanes::onCmdHelp (FXObject * , FXSelector , void *)
Called when help button is pressed.
Definition at line 1815 of file GNEAdditionalFrame.cpp.
long GNEAdditionalFrame::SelectorParentLanes::onCmdInvertSelection (FXObject * , FXSelector , void *)
called when invert selection button is pressed
Definition at line 1802 of file GNEAdditionalFrame.cpp.
References myList.
long GNEAdditionalFrame::SelectorParentLanes::onCmdSelectLane (FXObject * , FXSelector , void *)
called when user select a lane of the list
Definition at line 1785 of file GNEAdditionalFrame.cpp.
long GNEAdditionalFrame::SelectorParentLanes::onCmdTypeInSearchBox (FXObject * , FXSelector , void *)
called when user type in search box
Definition at line 1777 of file GNEAdditionalFrame.cpp.
References myLanesSearch, and showList().
long GNEAdditionalFrame::SelectorParentLanes::onCmdUseSelectedLanes (FXObject * , FXSelector , void *)
Definition at line 1754 of file GNEAdditionalFrame.cpp.
References clearLanesSelection, helpLanes, invertLanesSelection, myLanesSearch, myList, and myUseSelectedLanesCheckButton.
void GNEAdditionalFrame::SelectorParentLanes::showList (std::string search = "")
Show list of SelectorParentLanes.
Definition at line 1711 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getNet(), myList, myUseSelectedLanesCheckButton, myViewNet, GNENet::retrieveLanes(), and GNEAdditionalFrame::show().
Referenced by onCmdTypeInSearchBox(), and GNEAdditionalFrame::setParametersOfAdditional().
void GNEAdditionalFrame::SelectorParentLanes::updateUseSelectedLanes ()
Definition at line 1733 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getNet(), myUseSelectedLanesCheckButton, myViewNet, and GNENet::retrieveLanes().
Referenced by GNEAdditionalFrame::show().
Field Documentation
FXButton* GNEAdditionalFrame::SelectorParentLanes::clearLanesSelection private
button for clear selection
Definition at line 614 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedLanes(), and SelectorParentLanes().
FXButton* GNEAdditionalFrame::SelectorParentLanes::helpLanes private
button for help
Definition at line 611 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedLanes(), and SelectorParentLanes().
FXButton* GNEAdditionalFrame::SelectorParentLanes::invertLanesSelection private
button for invert selection
Definition at line 617 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedLanes(), and SelectorParentLanes().
FXTextField* GNEAdditionalFrame::SelectorParentLanes::myLanesSearch private
text field for search lane IDs
Definition at line 608 of file GNEAdditionalFrame.h.
Referenced by onCmdTypeInSearchBox(), onCmdUseSelectedLanes(), and SelectorParentLanes().
FXList* GNEAdditionalFrame::SelectorParentLanes::myList private
List of SelectorParentLanes.
Definition at line 605 of file GNEAdditionalFrame.h.
Referenced by getIdsSelected(), onCmdClearSelection(), onCmdInvertSelection(), onCmdUseSelectedLanes(), SelectorParentLanes(), and showList().
FXCheckButton* GNEAdditionalFrame::SelectorParentLanes::myUseSelectedLanesCheckButton private
CheckBox for selected lanes.
Definition at line 602 of file GNEAdditionalFrame.h.
Referenced by isUseSelectedLanesEnable(), onCmdUseSelectedLanes(), SelectorParentLanes(), showList(), and updateUseSelectedLanes().
GNEViewNet* GNEAdditionalFrame::SelectorParentLanes::myViewNet private
viewNet associated to GNEAdditionalFrame
Definition at line 620 of file GNEAdditionalFrame.h.
Referenced by showList(), and updateUseSelectedLanes().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp