SUMO - Simulation of Urban MObility: TraCI_InductionLoop Class Reference
TraCI_InductionLoop Class Reference
C++ TraCI client API implementation.
#include <TraCI_InductionLoop.h>
Static Public Member Functions
static int getIDCount ()
static std::vector< std::string > getIDList ()
static std::string getLaneID (const std::string &detID)
static double getLastStepMeanLength (const std::string &detID)
static double getLastStepMeanSpeed (const std::string &detID)
static double getLastStepOccupancy (const std::string &detID)
static std::vector< std::string > getLastStepVehicleIDs (const std::string &detID)
static int getLastStepVehicleNumber (const std::string &detID)
static double getPosition (const std::string &detID)
static double getTimeSinceDetection (const std::string &detID)
static std::vector< TraCIVehicleData > getVehicleData (const std::string &detID)
Private Member Functions
TraCI_InductionLoop & operator= (const TraCI_InductionLoop &src)
invalidated assignment operator
TraCI_InductionLoop ()
invalidated standard constructor
TraCI_InductionLoop (const TraCI_InductionLoop &src)
invalidated copy constructor
Static Private Member Functions
static MSInductLoop * getDetector (const std::string &detID)
Detailed Description
C++ TraCI client API implementation.
Definition at line 50 of file TraCI_InductionLoop.h.
Constructor & Destructor Documentation
TraCI_InductionLoop::TraCI_InductionLoop () private
invalidated standard constructor
TraCI_InductionLoop::TraCI_InductionLoop (const TraCI_InductionLoop & src) private
invalidated copy constructor
Member Function Documentation
MSInductLoop * TraCI_InductionLoop::getDetector (const std::string & detID) static private
Definition at line 125 of file TraCI_InductionLoop.cpp.
References NamedObjectCont< T >::get(), MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), and SUMO_TAG_INDUCTION_LOOP.
Referenced by getLaneID(), getLastStepMeanLength(), getLastStepMeanSpeed(), getLastStepOccupancy(), getLastStepVehicleIDs(), getLastStepVehicleNumber(), getPosition(), getTimeSinceDetection(), and getVehicleData().
int TraCI_InductionLoop::getIDCount () static
Definition at line 53 of file TraCI_InductionLoop.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::size(), and SUMO_TAG_INDUCTION_LOOP.
Referenced by TraCIServerAPI_InductionLoop::processGet().
std::vector< std::string > TraCI_InductionLoop::getIDList () static
Definition at line 45 of file TraCI_InductionLoop.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::insertIDs(), and SUMO_TAG_INDUCTION_LOOP.
Referenced by TraCIServerAPI_InductionLoop::processGet().
std::string TraCI_InductionLoop::getLaneID (const std::string & detID) static
Definition at line 66 of file TraCI_InductionLoop.cpp.
References getDetector(), Named::getID(), and MSMoveReminder::getLane().
Referenced by TraCIServerAPI_InductionLoop::processGet().
double TraCI_InductionLoop::getLastStepMeanLength (const std::string & detID) static
Definition at line 96 of file TraCI_InductionLoop.cpp.
References MSInductLoop::getCurrentLength(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
double TraCI_InductionLoop::getLastStepMeanSpeed (const std::string & detID) static
Definition at line 78 of file TraCI_InductionLoop.cpp.
References MSInductLoop::getCurrentSpeed(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
double TraCI_InductionLoop::getLastStepOccupancy (const std::string & detID) static
Definition at line 90 of file TraCI_InductionLoop.cpp.
References MSInductLoop::getCurrentOccupancy(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
std::vector< std::string > TraCI_InductionLoop::getLastStepVehicleIDs (const std::string & detID) static
Definition at line 84 of file TraCI_InductionLoop.cpp.
References MSInductLoop::getCurrentVehicleIDs(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
int TraCI_InductionLoop::getLastStepVehicleNumber (const std::string & detID) static
Definition at line 72 of file TraCI_InductionLoop.cpp.
References MSInductLoop::getCurrentPassedNumber(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
double TraCI_InductionLoop::getPosition (const std::string & detID) static
Definition at line 60 of file TraCI_InductionLoop.cpp.
References getDetector(), and MSInductLoop::getPosition().
Referenced by TraCIServerAPI_InductionLoop::processGet().
double TraCI_InductionLoop::getTimeSinceDetection (const std::string & detID) static
Definition at line 102 of file TraCI_InductionLoop.cpp.
References getDetector(), and MSInductLoop::getTimeSinceLastDetection().
Referenced by TraCIServerAPI_InductionLoop::processGet().
std::vector< TraCIVehicleData > TraCI_InductionLoop::getVehicleData (const std::string & detID) static
Definition at line 108 of file TraCI_InductionLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, getDetector(), and MSNet::getInstance().
Referenced by TraCIServerAPI_InductionLoop::processGet().
TraCI_InductionLoop& TraCI_InductionLoop::operator= (const TraCI_InductionLoop & src) private
invalidated assignment operator
The documentation for this class was generated from the following files:
TraCI_InductionLoop.h
TraCI_InductionLoop.cpp