SUMO - Simulation of Urban MObility: PollutantsInterface::Helper Class Reference
PollutantsInterface::Helper Class Reference abstract
abstract superclass for the model helpers
#include <PollutantsInterface.h>
Public Member Functions
void addAllClassesInto (std::vector< SUMOEmissionClass > &list) const
Add all known emission classes of this model to the given container.
virtual double compute (const SUMOEmissionClass c, const EmissionType e, const double v, const double a, const double slope, const std::map< int, double > *param) const =0
Returns the amount of the emitted pollutant given the vehicle type and state (in mg/s or ml/s for fuel)
virtual SUMOEmissionClass getClassByName (const std::string &eClass, const SUMOVehicleClass vc)
Returns the emission class associated with the given name, aliases are possible If this method is asked for the "unknown" class it should return the default (possibly depending on the given vehicle class). The class name is case insensitive.
const std::string getClassName (const SUMOEmissionClass c) const
Returns the complete name of the emission class including the model.
const std::string & getName () const
Returns the name of the model.
Helper (std::string name)
Constructor, intializes the name.
virtual bool isSilent (const SUMOEmissionClass c)
Returns whether the class denotes a silent vehicle for interfacing with the noise model. By default the first class in each model is the silent class.
Methods for Amitran interfaces
virtual SUMOEmissionClass getClass (const SUMOEmissionClass base, const std::string &vClass, const std::string &fuel, const std::string &eClass, const double weight) const
Returns the emission class described by the given parameters. The base is used to determine the model to use and as default return values. Default implementation returns always base.
virtual std::string getAmitranVehicleClass (const SUMOEmissionClass c) const
Returns the vehicle class described by this emission class as described in the Amitran interface (Passenger, ...) Default implementation returns always "Passenger".
virtual std::string getFuel (const SUMOEmissionClass c) const
Returns the fuel type described by this emission class as described in the Amitran interface (Gasoline, Diesel, ...) Default implementation returns always "Gasoline".
virtual int getEuroClass (const SUMOEmissionClass c) const
Returns the Euro emission class described by this emission class as described in the Amitran interface (0, ..., 6) Default implementation returns always 0.
virtual double getWeight (const SUMOEmissionClass c) const
Returns a reference weight in kg described by this emission class as described in the Amitran interface It might return -1, if the weight is not important to distinguish different emission classes. Default implementation returns always -1.
Protected Attributes
StringBijection< SUMOEmissionClass > myEmissionClassStrings
Mapping between emission class names and integer representations.
const std::string myName
the name of the model
Private Member Functions
Helper & operator= (const Helper &)
Detailed Description
abstract superclass for the model helpers
Definition at line 112 of file PollutantsInterface.h.
Constructor & Destructor Documentation
PollutantsInterface::Helper::Helper (std::string name) inline
Constructor, intializes the name.
Parameters
[in] name the name of the model (string before the '/' in the emission class attribute)
Definition at line 117 of file PollutantsInterface.h.
Member Function Documentation
void PollutantsInterface::Helper::addAllClassesInto (std::vector< SUMOEmissionClass > & list) const inline
Add all known emission classes of this model to the given container.
Parameters
[in] list the vector to add to
Definition at line 239 of file PollutantsInterface.h.
Referenced by PollutantsInterface::getAllClasses().
virtual double PollutantsInterface::Helper::compute (const SUMOEmissionClass c, const EmissionType e, const double v, const double a, const double slope, const std::map< int, double > * param) const pure virtual
Returns the amount of the emitted pollutant given the vehicle type and state (in mg/s or ml/s for fuel)
Parameters
[in] c The vehicle emission class
[in] e the type of emission (CO, CO2, ...)
[in] v The vehicle's current velocity
[in] a The vehicle's current acceleration
[in] slope The road's slope at vehicle's position [deg]
Returns
The amount emitted by the given emission class when moving with the given velocity and acceleration [mg/s or ml/s]
Implemented in HelpersPHEMlight, HelpersHBEFA3, HelpersHBEFA, and HelpersEnergy.
Referenced by PollutantsInterface::compute(), PollutantsInterface::computeAll(), and PollutantsInterface::computeDefault().
virtual std::string PollutantsInterface::Helper::getAmitranVehicleClass (const SUMOEmissionClass c) const inline virtual
Returns the vehicle class described by this emission class as described in the Amitran interface (Passenger, ...) Default implementation returns always "Passenger".
Parameters
[in] c the emission class
Returns
the name of the vehicle class
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 189 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getAmitranVehicleClass().
virtual SUMOEmissionClass PollutantsInterface::Helper::getClass (const SUMOEmissionClass base, const std::string & vClass, const std::string & fuel, const std::string & eClass, const double weight) const inline virtual
Returns the emission class described by the given parameters. The base is used to determine the model to use and as default return values. Default implementation returns always base.
Parameters
[in] base the base class giving the model and the default
[in] vClass the vehicle class as described in the Amitran interface (Passenger, ...)
[in] fuel the fuel type as described in the Amitran interface (Gasoline, Diesel, ...)
[in] eClass the emission class as described in the Amitran interface (Euro0, ...)
[in] weight the vehicle weight in kg as described in the Amitran interface
Returns
the class described by the parameters
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 175 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getClass().
virtual SUMOEmissionClass PollutantsInterface::Helper::getClassByName (const std::string & eClass, const SUMOVehicleClass vc) inline virtual
Returns the emission class associated with the given name, aliases are possible If this method is asked for the "unknown" class it should return the default (possibly depending on the given vehicle class). The class name is case insensitive.
Parameters
[in] eClass the name of the emission class (string after the '/' in the emission class attribute)
[in] vc the vehicle class to use when determining default class
Returns
the name of the model (string before the '/' in the emission class)
Reimplemented in HelpersPHEMlight.
Definition at line 135 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getClassByName().
const std::string PollutantsInterface::Helper::getClassName (const SUMOEmissionClass c) const inline
Returns the complete name of the emission class including the model.
Parameters
[in] c the emission class
Returns
the name of the class (the complete emission class attribute)
Definition at line 149 of file PollutantsInterface.h.
Referenced by PollutantsInterface::getName().
virtual int PollutantsInterface::Helper::getEuroClass (const SUMOEmissionClass c) const inline virtual
Returns the Euro emission class described by this emission class as described in the Amitran interface (0, ..., 6) Default implementation returns always 0.
Parameters
[in] c the emission class
Returns
the Euro class
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 209 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getEuroClass().
virtual std::string PollutantsInterface::Helper::getFuel (const SUMOEmissionClass c) const inline virtual
Returns the fuel type described by this emission class as described in the Amitran interface (Gasoline, Diesel, ...) Default implementation returns always "Gasoline".
Parameters
[in] c the emission class
Returns
the fuel type
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 199 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getFuel().
const std::string& PollutantsInterface::Helper::getName () const inline
Returns the name of the model.
Returns
the name of the model (string before the '/' in the emission class attribute)
Definition at line 122 of file PollutantsInterface.h.
virtual double PollutantsInterface::Helper::getWeight (const SUMOEmissionClass c) const inline virtual
Returns a reference weight in kg described by this emission class as described in the Amitran interface It might return -1, if the weight is not important to distinguish different emission classes. Default implementation returns always -1.
Parameters
[in] c the emission class
Returns
a reference weight
Reimplemented in HelpersPHEMlight.
Definition at line 220 of file PollutantsInterface.h.
References PollutantsInterface::compute(), and UNUSED_PARAMETER.
Referenced by PollutantsInterface::getWeight().
virtual bool PollutantsInterface::Helper::isSilent (const SUMOEmissionClass c) inline virtual
Returns whether the class denotes a silent vehicle for interfacing with the noise model. By default the first class in each model is the silent class.
Parameters
[in] c the emission class
Returns
whether the class denotes a silent vehicle
Definition at line 158 of file PollutantsInterface.h.
References PollutantsInterface::HEAVY_BIT.
Referenced by PollutantsInterface::isSilent().
Helper& PollutantsInterface::Helper::operator= (const Helper &) private
Field Documentation
StringBijection<SUMOEmissionClass> PollutantsInterface::Helper::myEmissionClassStrings protected
Mapping between emission class names and integer representations.
Definition at line 249 of file PollutantsInterface.h.
Referenced by HelpersHBEFA3::getAmitranVehicleClass(), HelpersPHEMlight::getAmitranVehicleClass(), HelpersHBEFA3::getClass(), HelpersPHEMlight::getClass(), HelpersPHEMlight::getClassByName(), HelpersHBEFA3::getEuroClass(), HelpersPHEMlight::getEuroClass(), HelpersHBEFA3::getFuel(), HelpersPHEMlight::getFuel(), HelpersPHEMlight::getWeight(), HelpersEnergy::HelpersEnergy(), HelpersHBEFA::HelpersHBEFA(), HelpersHBEFA3::HelpersHBEFA3(), and HelpersPHEMlight::HelpersPHEMlight().
const std::string PollutantsInterface::Helper::myName protected
the name of the model
Definition at line 246 of file PollutantsInterface.h.
The documentation for this class was generated from the following file:
PollutantsInterface.h