SUMO - Simulation of Urban MObility: GUIVehicleControl Class Reference
GUIVehicleControl Class Reference
The class responsible for building and deletion of vehicles (gui-version)
#include <GUIVehicleControl.h>
Public Types
typedef std::map< std::string, SUMOVehicle * >::const_iterator constVehIt
Definition of the internal vehicles map iterator.
Public Member Functions
void abortWaiting ()
informes about all waiting vehicles (deletion in destructor)
bool addVehicle (const std::string &id, SUMOVehicle *v)
Tries to insert the vehicle into the internal vehicle container.
void addWaiting (const MSEdge *const edge, SUMOVehicle *vehicle)
Adds a vehicle to the list of waiting vehiclse to a given edge.
SUMOTime computeRandomDepartOffset () const
compute (optional) random offset to the departure time
void deleteVehicle (SUMOVehicle *v, bool discard=false)
Deletes the vehicle.
void discountStateLoaded (bool removed=false)
avoid counting a vehicle twice if it was loaded from state and route input
double getMaxSpeedFactor () const
return the maximum speed factor for all vehicles that ever entered the network
double getMinDeceleration () const
return the minimum deceleration capability for all vehicles that ever entered the network
SUMOVehicle * getWaitingVehicle (const MSEdge *const edge, const std::set< std::string > &lines, const double position, const std::string ridingID)
GUIVehicleControl ()
Constructor.
void insertVehicleIDs (std::vector< GUIGlID > &into, bool listParking, bool listTeleporting)
Returns the list of all known vehicles by gl-id.
void registerCollision ()
registers one collision-related teleport
void registerEmergencyStop ()
register emergency stop
void registerOneWaitingForContainer ()
increases the count of vehicles waiting for a container to allow recogniztion of container related deadlocks
void registerOneWaitingForPerson ()
increases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
void registerTeleportJam ()
register one non-collision-related teleport
void registerTeleportWrongLane ()
register one non-collision-related teleport
void registerTeleportYield ()
register one non-collision-related teleport
void releaseVehicles ()
unlock access to vehicle removal/additions for thread synchronization
void removeWaiting (const MSEdge *const edge, SUMOVehicle *vehicle)
Removes a vehicle from the list of waiting vehicles to a given edge.
void secureVehicles ()
lock access to vehicle removal/additions for thread synchronization
void unregisterOneWaitingForContainer ()
decreases the count of vehicles waiting for a container to allow recogniztion of container related deadlocks
void unregisterOneWaitingForPerson ()
decreases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
~GUIVehicleControl ()
Destructor.
Vehicle creation
SUMOVehicle * buildVehicle (SUMOVehicleParameter *defs, const MSRoute *route, const MSVehicleType *type, const bool ignoreStopErrors, const bool fromRouteFile=true)
Builds a vehicle, increases the number of built vehicles.
Insertion, deletion and retrieval of vehicles
SUMOVehicle * getVehicle (const std::string &id) const
Returns the vehicle with the given id.
void scheduleVehicleRemoval (SUMOVehicle *veh)
Removes a vehicle after it has ended.
constVehIt loadedVehBegin () const
Returns the begin of the internal vehicle map.
constVehIt loadedVehEnd () const
Returns the end of the internal vehicle map.
Setting vehicle statistics
void vehicleDeparted (const SUMOVehicle &v)
Informs this control about a vehicle's departure.
Retrieval of vehicle statistics (always accessable)
int getLoadedVehicleNo () const
Returns the number of build vehicles.
int getEndedVehicleNo () const
Returns the number of removed vehicles.
int getRunningVehicleNo () const
Returns the number of build and inserted, but not yet deleted vehicles.
int getDepartedVehicleNo () const
Returns the number of inserted vehicles.
int getQuota (double frac=-1) const
Returns the number of instances of the current vehicle that shall be emitted considering that "frac" of all vehicles shall be emitted overall if a negative fraction is given the demand scaling factor is used (–scale)
int getActiveVehicleCount () const
Returns the number of build vehicles that have not been removed or need to wait for a passenger or a container.
int getCollisionCount () const
return the number of collisions
int getTeleportsJam () const
return the number of teleports due to jamming
int getTeleportsYield () const
return the number of teleports due to vehicles stuck on a minor road
int getTeleportsWrongLane () const
return the number of teleports due to vehicles stuck on the wrong lane
int getTeleportCount () const
return the number of teleports (including collisions)
int getEmergencyStops () const
return the number of emergency stops
double getTotalDepartureDelay () const
Returns the total departure delay.
double getTotalTravelTime () const
Returns the total travel time.
Insertion and retrieval of vehicle types
bool addVType (MSVehicleType *vehType)
Adds a vehicle type.
void removeVType (const MSVehicleType *vehType)
bool addVTypeDistribution (const std::string &id, RandomDistributor< MSVehicleType * > *vehTypeDistribution)
Adds a vehicle type distribution.
bool hasVTypeDistribution (const std::string &id) const
Asks for a vehicle type distribution.
MSVehicleType * getVType (const std::string &id=DEFAULT_VTYPE_ID, MTRand *rng=0)
Returns the named vehicle type or a sample from the named distribution.
void insertVTypeIDs (std::vector< std::string > &into) const
Inserts ids of all known vehicle types and vehicle type distributions to the given vector.
State I/O
void setState (int runningVehNo, int loadedVehNo, int endedVehNo, double totalDepartureDelay, double totalTravelTime)
Sets the current state variables as loaded from the stream.
void saveState (OutputDevice &out)
Saves the current state into the given stream.
Protected Attributes
Vehicle statistics (always accessable)
int myLoadedVehNo
The number of build vehicles.
int myRunningVehNo
The number of vehicles within the network (build and inserted but not removed)
int myEndedVehNo
The number of removed vehicles.
int myDiscarded
The number of vehicles which were discarded while loading.
int myCollisions
The number of collisions.
int myTeleportsJam
The number of teleports due to jam.
int myTeleportsYield
The number of teleports due to vehicles stuck on a minor road.
int myTeleportsWrongLane
The number of teleports due to vehicles stuck on the wrong lane.
int myEmergencyStops
The number of emergency stops.
Vehicle statistics
double myTotalDepartureDelay
The aggregated time vehicles had to wait for departure (in seconds)
double myTotalTravelTime
The aggregated time vehicles needed to aacomplish their route (in seconds)
Private Member Functions
GUIVehicleControl (const GUIVehicleControl &s)
invalidated copy constructor
GUIVehicleControl & operator= (const GUIVehicleControl &s)
invalidated assignment operator
Private Attributes
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
Vehicle container
typedef std::map< std::string, SUMOVehicle * > VehicleDictType
Vehicle dictionary type.
VehicleDictType myVehicleDict
Dictionary of vehicles.
Vehicle type container
typedef std::map< std::string, MSVehicleType * > VTypeDictType
Vehicle type dictionary type.
typedef std::map< std::string, RandomDistributor< MSVehicleType * > * > VTypeDistDictType
Vehicle type distribution dictionary type.
VTypeDictType myVTypeDict
Dictionary of vehicle types.
VTypeDistDictType myVTypeDistDict
A distribution of vehicle types (probability->vehicle type)
bool myDefaultVTypeMayBeDeleted
Whether no vehicle type was loaded.
bool myDefaultPedTypeMayBeDeleted
Whether no pedestrian type was loaded.
std::map< const MSEdge *const, std::vector< SUMOVehicle * > > myWaiting
the lists of waiting vehicles to a given edge
int myWaitingForPerson
the number of vehicles wainting for persons contained in myWaiting which can only continue by being triggered
int myWaitingForContainer
the number of vehicles wainting for containers contained in myWaiting which can only continue by being triggered
double myScale
The scaling factor (especially for inc-dua)
SUMOTime myMaxRandomDepartOffset
The maximum random offset to be added to vehicles departure times (non-negative)
double myMaxSpeedFactor
The maximum speed factor for all vehicles in the network.
double myMinDeceleration
The minimum deceleration capability for all vehicles in the network.
Detailed Description
The class responsible for building and deletion of vehicles (gui-version)
Builds GUIVehicle instances instead of MSVehicle.
See also
MSVehicleControl
Todo:
This is partially unsecure due to concurrent access...
Recheck vehicle deletion
Definition at line 59 of file GUIVehicleControl.h.
Member Typedef Documentation
typedef std::map<std::string, SUMOVehicle*>::const_iterator MSVehicleControl::constVehIt inherited
Definition of the internal vehicles map iterator.
Definition at line 77 of file MSVehicleControl.h.
typedef std::map< std::string, SUMOVehicle* > MSVehicleControl::VehicleDictType protected inherited
Vehicle dictionary type.
Definition at line 520 of file MSVehicleControl.h.
typedef std::map< std::string, MSVehicleType* > MSVehicleControl::VTypeDictType protected inherited
Vehicle type dictionary type.
Definition at line 530 of file MSVehicleControl.h.
typedef std::map< std::string, RandomDistributor<MSVehicleType*>* > MSVehicleControl::VTypeDistDictType protected inherited
Vehicle type distribution dictionary type.
Definition at line 535 of file MSVehicleControl.h.
Constructor & Destructor Documentation
GUIVehicleControl::GUIVehicleControl ()
Constructor.
Definition at line 44 of file GUIVehicleControl.cpp.
GUIVehicleControl::~GUIVehicleControl ()
Destructor.
Definition at line 48 of file GUIVehicleControl.cpp.
References MFXMutex::locked(), myLock, and MFXMutex::unlock().
GUIVehicleControl::GUIVehicleControl (const GUIVehicleControl & s) private
invalidated copy constructor
Member Function Documentation
void MSVehicleControl::abortWaiting () inherited
informes about all waiting vehicles (deletion in destructor)
Definition at line 366 of file MSVehicleControl.cpp.
References MSVehicleControl::myVehicleDict, and WRITE_WARNING.
Referenced by MSVehicleControl::discountStateLoaded(), and MSNet::simulationState().
bool GUIVehicleControl::addVehicle (const std::string & id, SUMOVehicle * v) virtual
Tries to insert the vehicle into the internal vehicle container.
Identical to the MSVehicleControl implementation except for locking.
Parameters
[in] id The id of the vehicle
[in] v The vehicle
Returns
Whether the vehicle could be inserted (no other vehicle with the same id was inserted before)
Reimplemented from MSVehicleControl.
Definition at line 72 of file GUIVehicleControl.cpp.
References MSVehicleControl::addVehicle(), and myLock.
bool MSVehicleControl::addVType (MSVehicleType * vehType) inherited
Adds a vehicle type.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type is added to the internal vehicle type container "myVTypeDict".
This control get responsible for deletion of the added vehicle type.
Parameters
[in] vehType The vehicle type to add
Returns
Whether the vehicle type could be added
Definition at line 247 of file MSVehicleControl.cpp.
References MSVehicleControl::checkVType(), MSVehicleType::getID(), and MSVehicleControl::myVTypeDict.
Referenced by MSVehicleControl::getTotalTravelTime().
bool MSVehicleControl::addVTypeDistribution (const std::string & id, RandomDistributor< MSVehicleType * > * vehTypeDistribution) inherited
Adds a vehicle type distribution.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type distribution is added to the internal vehicle type distribution container "myVTypeDistDict".
This control get responsible for deletion of the added vehicle type distribution.
Parameters
[in] id The id of the distribution to add
[in] vehTypeDistribution The vehicle type distribution to add
Returns
Whether the vehicle type could be added
Definition at line 266 of file MSVehicleControl.cpp.
References MSVehicleControl::checkVType(), and MSVehicleControl::myVTypeDistDict.
Referenced by MSVehicleControl::getTotalTravelTime().
void MSVehicleControl::addWaiting (const MSEdge *const edge, SUMOVehicle * vehicle) inherited
Adds a vehicle to the list of waiting vehiclse to a given edge.
Definition at line 313 of file MSVehicleControl.cpp.
References MSVehicleControl::myWaiting.
Referenced by MSRouteHandler::closeVehicle(), MSVehicleControl::getTotalTravelTime(), and MSVehicle::processNextStop().
SUMOVehicle * GUIVehicleControl::buildVehicle (SUMOVehicleParameter * defs, const MSRoute * route, const MSVehicleType * type, const bool ignoreStopErrors, const bool fromRouteFile = true) virtual
Builds a vehicle, increases the number of built vehicles.
Instead of a MSVehicle, a GUIVehicle is built
Parameters
[in] defs The parameter defining the vehicle
[in] route The route of this vehicle
[in] type The type of this vehicle
[in] ignoreStopErrors whether invalid stops trigger a warning only
[in] fromRouteFile whether we are just reading the route file or creating via trigger, traci, ...
Returns
The built vehicle (GUIVehicle instance)
See also
MSVehicleControl::buildVehicle
Reimplemented from MSVehicleControl.
Definition at line 57 of file GUIVehicleControl.cpp.
References MSBaseVehicle::addStops(), MSVehicleType::computeChosenSpeedDeviation(), MSVehicleControl::computeRandomDepartOffset(), SUMOVehicleParameter::depart, MSNet::getInstance(), MSRouteHandler::getParsingRNG(), MSNet::informVehicleStateListener(), MSVehicleControl::myLoadedVehNo, and MSNet::VEHICLE_STATE_BUILT.
SUMOTime MSVehicleControl::computeRandomDepartOffset () const inherited
compute (optional) random offset to the departure time
Definition at line 99 of file MSVehicleControl.cpp.
References DELTA_T, MSRouteHandler::getParsingRNG(), and MSVehicleControl::myMaxRandomDepartOffset.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), buildVehicle(), MSVehicleControl::buildVehicle(), and MSVehicleControl::discountStateLoaded().
void GUIVehicleControl::deleteVehicle (SUMOVehicle * v, bool discard = false) virtual
Deletes the vehicle.
Identical to the MSVehicleControl implementation except for locking.
Parameters
[in] v The vehicle to delete
Reimplemented from MSVehicleControl.
Definition at line 79 of file GUIVehicleControl.cpp.
References MSVehicleControl::deleteVehicle(), and myLock.
void MSVehicleControl::discountStateLoaded (bool removed = false) inline inherited
avoid counting a vehicle twice if it was loaded from state and route input
Definition at line 434 of file MSVehicleControl.h.
References MSVehicleControl::abortWaiting(), MSVehicleControl::computeRandomDepartOffset(), MSVehicleControl::myDiscarded, MSVehicleControl::myEndedVehNo, MSVehicleControl::myLoadedVehNo, and MSVehicleControl::myRunningVehNo.
Referenced by MSStateHandler::closeVehicle(), and MSInsertionControl::determineCandidates().
int MSVehicleControl::getActiveVehicleCount () const inline inherited
Returns the number of build vehicles that have not been removed or need to wait for a passenger or a container.
Returns
Number of active vehicles
Definition at line 243 of file MSVehicleControl.h.
References MSVehicleControl::myEndedVehNo, MSVehicleControl::myLoadedVehNo, MSVehicleControl::myWaitingForContainer, and MSVehicleControl::myWaitingForPerson.
Referenced by MSNet::simulationState().
int MSVehicleControl::getCollisionCount () const inline inherited
return the number of collisions
Definition at line 249 of file MSVehicleControl.h.
References MSVehicleControl::myCollisions.
Referenced by GUIApplicationWindow::checkGamingEvents(), MSNet::closeSimulation(), and GUINet::getParameterWindow().
int MSVehicleControl::getDepartedVehicleNo () const inline inherited
Returns the number of inserted vehicles.
Returns
The number of vehicles that have entered the simulation so far
Definition at line 225 of file MSVehicleControl.h.
References MSVehicleControl::getQuota(), MSVehicleControl::myDiscarded, MSVehicleControl::myEndedVehNo, and MSVehicleControl::myRunningVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), MSNet::postSimStepOutput(), and MSNet::writeOutput().
int MSVehicleControl::getEmergencyStops () const inline inherited
return the number of emergency stops
Definition at line 272 of file MSVehicleControl.h.
References MSVehicleControl::myEmergencyStops.
Referenced by MSNet::closeSimulation().
int MSVehicleControl::getEndedVehicleNo () const inline inherited
Returns the number of removed vehicles.
Returns
The number of vehicles that have left the simulation
Definition at line 209 of file MSVehicleControl.h.
References MSVehicleControl::myEndedVehNo.
Referenced by GUINet::getParameterWindow(), and MSNet::writeOutput().
int MSVehicleControl::getLoadedVehicleNo () const inline inherited
Returns the number of build vehicles.
Returns
The number of loaded (build) vehicles
Definition at line 201 of file MSVehicleControl.h.
References MSVehicleControl::myLoadedVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), and MSNet::writeOutput().
double MSVehicleControl::getMaxSpeedFactor () const inline inherited
return the maximum speed factor for all vehicles that ever entered the network
Definition at line 453 of file MSVehicleControl.h.
References MSVehicleControl::myMaxSpeedFactor.
Referenced by MSLane::getMaximumBrakeDist().
double MSVehicleControl::getMinDeceleration () const inline inherited
return the minimum deceleration capability for all vehicles that ever entered the network
Definition at line 458 of file MSVehicleControl.h.
References MSVehicleControl::checkVType(), and MSVehicleControl::myMinDeceleration.
Referenced by MSLane::getMaximumBrakeDist().
int MSVehicleControl::getQuota (double frac = -1) const inherited
Returns the number of instances of the current vehicle that shall be emitted considering that "frac" of all vehicles shall be emitted overall if a negative fraction is given the demand scaling factor is used (–scale)
Returns
the number of vehicles to create (something between 0 and ceil(frac))
Definition at line 374 of file MSVehicleControl.cpp.
References MSVehicleControl::myLoadedVehNo, and MSVehicleControl::myScale.
Referenced by MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), MSDevice::equippedByDefaultAssignmentOptions(), and MSVehicleControl::getDepartedVehicleNo().
int MSVehicleControl::getRunningVehicleNo () const inline inherited
Returns the number of build and inserted, but not yet deleted vehicles.
Returns
The number simulated vehicles (including those in teleporter)
Definition at line 217 of file MSVehicleControl.h.
References MSVehicleControl::myRunningVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), GUIApplicationWindow::handleEvent_SimulationStep(), MSNet::postSimStepOutput(), GUINet::setSimDuration(), MSNet::simulationStep(), and MSNet::writeOutput().
int MSVehicleControl::getTeleportCount () const inherited
return the number of teleports (including collisions)
Definition at line 392 of file MSVehicleControl.cpp.
References MSVehicleControl::myCollisions, MSVehicleControl::myTeleportsJam, MSVehicleControl::myTeleportsWrongLane, MSVehicleControl::myTeleportsYield, and MSLane::teleportOnCollision().
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), MSVehicleControl::getTeleportsWrongLane(), and MSNet::simulationState().
int MSVehicleControl::getTeleportsJam () const inline inherited
return the number of teleports due to jamming
Definition at line 254 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsJam.
Referenced by MSNet::closeSimulation().
int MSVehicleControl::getTeleportsWrongLane () const inline inherited
return the number of teleports due to vehicles stuck on the wrong lane
Definition at line 264 of file MSVehicleControl.h.
References MSVehicleControl::getTeleportCount(), and MSVehicleControl::myTeleportsWrongLane.
Referenced by MSNet::closeSimulation().
int MSVehicleControl::getTeleportsYield () const inline inherited
return the number of teleports due to vehicles stuck on a minor road
Definition at line 259 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsYield.
Referenced by MSNet::closeSimulation().
double MSVehicleControl::getTotalDepartureDelay () const inline inherited
Returns the total departure delay.
Returns
Sum of steps vehicles had to wait until being inserted
Definition at line 280 of file MSVehicleControl.h.
References MSVehicleControl::myTotalDepartureDelay.
Referenced by MSNet::writeOutput().
double MSVehicleControl::getTotalTravelTime () const inline inherited
Returns the total travel time.
Returns
Sum of travel times of arrived vehicles
Definition at line 288 of file MSVehicleControl.h.
References MSVehicleControl::addVType(), MSVehicleControl::addVTypeDistribution(), MSVehicleControl::addWaiting(), DEFAULT_VTYPE_ID, MSVehicleControl::getVType(), MSVehicleControl::getWaitingVehicle(), MSVehicleControl::hasVTypeDistribution(), MSVehicleControl::insertVTypeIDs(), MSVehicleControl::myTotalTravelTime, MSVehicleControl::removeVType(), and MSVehicleControl::removeWaiting().
Referenced by MSNet::writeOutput().
SUMOVehicle * MSVehicleControl::getVehicle (const std::string & id) const inherited
Returns the vehicle with the given id.
If no vehicle with the given id is store din "myVehicleDict", 0 is returned.
Parameters
[in] id The id of the vehicle to retrieve
Returns
The vehicle with the given id, 0 if no such vehicle exists
Definition at line 198 of file MSVehicleControl.cpp.
References MSVehicleControl::myVehicleDict.
Referenced by MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), TraCIServerAPI_Vehicle::getPosition(), TraCI_Vehicle::getVehicle(), MSVehicleTransfer::loadState(), MESegment::loadState(), MSLane::loadState(), TraCI_Vehicle::onInit(), TraCIServer::postProcessVTD(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Vehicle::processSet(), MSCalibrator::removePending(), and GUINet::vehicleExists().
MSVehicleType * MSVehicleControl::getVType (const std::string & id = DEFAULT_VTYPE_ID, MTRand * rng = 0) inherited
Returns the named vehicle type or a sample from the named distribution.
Parameters
[in] id The id of the vehicle type to return. If left out, the default type is returned.
Returns
The named vehicle type, or 0 if no such type exists
Definition at line 282 of file MSVehicleControl.cpp.
References DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, MSVehicleControl::myDefaultPedTypeMayBeDeleted, MSVehicleControl::myDefaultVTypeMayBeDeleted, MSVehicleControl::myVTypeDict, and MSVehicleControl::myVTypeDistDict.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSVehicleControl::getTotalTravelTime(), TraCI_VehicleType::getVType(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), MSRouteHandler::openVehicleTypeDistribution(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Person::processSet(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
SUMOVehicle * MSVehicleControl::getWaitingVehicle (const MSEdge *const edge, const std::set< std::string > & lines, const double position, const std::string ridingID) inherited
Definition at line 333 of file MSVehicleControl.cpp.
References DEPART_TRIGGERED, Named::getID(), SUMOVehicle::getParameter(), MSVehicle::isStoppedInRange(), SUMOVehicleParameter::line, MSVehicleControl::myWaiting, toString(), and WRITE_WARNING.
Referenced by MSVehicleControl::getTotalTravelTime(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
bool MSVehicleControl::hasVTypeDistribution (const std::string & id) const inherited
Asks for a vehicle type distribution.
If vehicle type distribution with the id exists, true is returned, false otherwise.
Parameters
[in] id The id of the distribution
Returns
Whether the vehicle type distribution exists
Definition at line 276 of file MSVehicleControl.cpp.
References MSVehicleControl::myVTypeDistDict.
Referenced by MSVehicleControl::getTotalTravelTime().
void GUIVehicleControl::insertVehicleIDs (std::vector< GUIGlID > & into, bool listParking, bool listTeleporting)
Returns the list of all known vehicles by gl-id.
Parameters
Definition at line 86 of file GUIVehicleControl.cpp.
References SUMOVehicle::isOnRoad(), SUMOVehicle::isParking(), myLock, and MSVehicleControl::myVehicleDict.
void MSVehicleControl::insertVTypeIDs (std::vector< std::string > & into) const inherited
Inserts ids of all known vehicle types and vehicle type distributions to the given vector.
Parameters
[in] into The vector to fill with ids
Definition at line 301 of file MSVehicleControl.cpp.
References MSVehicleControl::myVTypeDict, and MSVehicleControl::myVTypeDistDict.
Referenced by TraCI_VehicleType::getIDList(), and MSVehicleControl::getTotalTravelTime().
constVehIt MSVehicleControl::loadedVehBegin () const inline inherited
Returns the begin of the internal vehicle map.
Returns
The begin of the internal vehicle map
Definition at line 165 of file MSVehicleControl.h.
References MSVehicleControl::myVehicleDict.
Referenced by GUIApplicationWindow::checkGamingEvents(), MSVTypeProbe::execute(), TraCI_Vehicle::getIDList(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), and MSFullExport::writeVehicles().
constVehIt MSVehicleControl::loadedVehEnd () const inline inherited
Returns the end of the internal vehicle map.
Returns
The end of the internal vehicle map
Definition at line 173 of file MSVehicleControl.h.
References MSVehicleControl::myVehicleDict, and MSVehicleControl::vehicleDeparted().
Referenced by GUIApplicationWindow::checkGamingEvents(), MSVTypeProbe::execute(), TraCI_Vehicle::getIDList(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), and MSFullExport::writeVehicles().
GUIVehicleControl& GUIVehicleControl::operator= (const GUIVehicleControl & s) private
invalidated assignment operator
void MSVehicleControl::registerCollision () inline inherited
registers one collision-related teleport
Definition at line 397 of file MSVehicleControl.h.
References MSVehicleControl::myCollisions.
Referenced by MSLane::executeMovements(), and MSLane::handleCollisionBetween().
void MSVehicleControl::registerEmergencyStop () inline inherited
register emergency stop
Definition at line 417 of file MSVehicleControl.h.
References MSVehicleControl::myEmergencyStops, MSVehicleControl::saveState(), and MSVehicleControl::setState().
Referenced by MSVehicle::executeMove().
void MSVehicleControl::registerOneWaitingForContainer () inline inherited
increases the count of vehicles waiting for a container to allow recogniztion of container related deadlocks
Definition at line 386 of file MSVehicleControl.h.
References MSVehicleControl::myWaitingForContainer.
Referenced by MSRouteHandler::closeVehicle(), and MSVehicle::processNextStop().
void MSVehicleControl::registerOneWaitingForPerson () inline inherited
increases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
Definition at line 374 of file MSVehicleControl.h.
References MSVehicleControl::myWaitingForPerson.
Referenced by MSRouteHandler::closeVehicle(), and MSVehicle::processNextStop().
void MSVehicleControl::registerTeleportJam () inline inherited
register one non-collision-related teleport
Definition at line 402 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsJam.
Referenced by MSLane::executeMovements(), and MELoop::teleportVehicle().
void MSVehicleControl::registerTeleportWrongLane () inline inherited
register one non-collision-related teleport
Definition at line 412 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsWrongLane.
Referenced by MSLane::executeMovements().
void MSVehicleControl::registerTeleportYield () inline inherited
register one non-collision-related teleport
Definition at line 407 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsYield.
Referenced by MSLane::executeMovements().
void GUIVehicleControl::releaseVehicles ()
unlock access to vehicle removal/additions for thread synchronization
Definition at line 105 of file GUIVehicleControl.cpp.
References myLock, and MFXMutex::unlock().
void MSVehicleControl::removeVType (const MSVehicleType * vehType) inherited
Definition at line 257 of file MSVehicleControl.cpp.
References MSVehicleType::getID(), and MSVehicleControl::myVTypeDict.
Referenced by MSVehicleType::buildSingularType(), and MSVehicleControl::getTotalTravelTime().
void MSVehicleControl::removeWaiting (const MSEdge *const edge, SUMOVehicle * vehicle) inherited
Removes a vehicle from the list of waiting vehicles to a given edge.
Definition at line 322 of file MSVehicleControl.cpp.
References MSVehicleControl::myWaiting.
Referenced by MSVehicleControl::getTotalTravelTime(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), and MSVehicle::resumeFromStopping().
void MSVehicleControl::saveState (OutputDevice & out) inherited
Saves the current state into the given stream.
Definition at line 162 of file MSVehicleControl.cpp.
References OutputDevice::closeTag(), MSVehicleControl::myEndedVehNo, MSVehicleControl::myLoadedVehNo, MSVehicleControl::myRunningVehNo, MSVehicleControl::myTotalDepartureDelay, MSVehicleControl::myTotalTravelTime, MSVehicleControl::myVehicleDict, MSVehicleControl::myVTypeDict, MSVehicleControl::myVTypeDistDict, OutputDevice::openTag(), SUMO_ATTR_BEGIN, SUMO_ATTR_DEPART, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_NUMBER, SUMO_ATTR_PROBS, SUMO_ATTR_TIME, SUMO_ATTR_VTYPES, SUMO_TAG_DELAY, SUMO_TAG_VTYPE_DISTRIBUTION, and OutputDevice::writeAttr().
Referenced by MSVehicleControl::registerEmergencyStop(), and MSStateHandler::saveState().
void MSVehicleControl::scheduleVehicleRemoval (SUMOVehicle * veh) inherited
Removes a vehicle after it has ended.
Writes output to tripinfos and vehroutes if wished; decrements the number of running vehicles and increments the number of ended vehicles. Then deletes the vehicle using "deleteVehicle".
This method should be called for each vehicle that was inserted into the network and quits its ride.
Parameters
[in] veh The vehicle to remove
Definition at line 125 of file MSVehicleControl.cpp.
References OutputDevice::closeTag(), MSVehicleControl::deleteVehicle(), SUMOVehicle::getDeparture(), OutputDevice::getDeviceByOption(), SUMOVehicle::getDevices(), MSNet::getInstance(), OptionsCont::getOptions(), MSNet::informVehicleStateListener(), MSVehicleControl::myRunningVehNo, MSVehicleControl::myTotalTravelTime, STEPS2TIME, and MSNet::VEHICLE_STATE_ARRIVED.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), MSVehicleTransfer::checkInsertions(), MSLane::detectCollisions(), MSLane::executeMovements(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), and MSCalibrator::removePending().
void GUIVehicleControl::secureVehicles ()
lock access to vehicle removal/additions for thread synchronization
Definition at line 99 of file GUIVehicleControl.cpp.
References MFXMutex::lock(), and myLock.
void MSVehicleControl::setState (int runningVehNo, int loadedVehNo, int endedVehNo, double totalDepartureDelay, double totalTravelTime) inherited
Sets the current state variables as loaded from the stream.
Definition at line 152 of file MSVehicleControl.cpp.
References MSVehicleControl::myEndedVehNo, MSVehicleControl::myLoadedVehNo, MSVehicleControl::myRunningVehNo, MSVehicleControl::myTotalDepartureDelay, and MSVehicleControl::myTotalTravelTime.
Referenced by MSStateHandler::myStartElement(), and MSVehicleControl::registerEmergencyStop().
void MSVehicleControl::unregisterOneWaitingForContainer () inline inherited
decreases the count of vehicles waiting for a container to allow recogniztion of container related deadlocks
Definition at line 392 of file MSVehicleControl.h.
References MSVehicleControl::myWaitingForContainer.
Referenced by MSContainer::MSContainerStage_Driving::proceed(), MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
void MSVehicleControl::unregisterOneWaitingForPerson () inline inherited
decreases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
Definition at line 380 of file MSVehicleControl.h.
References MSVehicleControl::myWaitingForPerson.
Referenced by MSPerson::MSPersonStage_Driving::proceed(), MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
void MSVehicleControl::vehicleDeparted (const SUMOVehicle & v) inherited
Informs this control about a vehicle's departure.
If the mean waiting time shall be computed (f.e. for summary-output), the absolut waiting time is increased by the waiting time of the given vehicle.
Parameters
[in] v The inserted vehicle
Definition at line 142 of file MSVehicleControl.cpp.
References SUMOVehicleParameter::depart, MSVehicleType::getCarFollowModel(), SUMOVehicle::getChosenSpeedFactor(), SUMOVehicle::getDeparture(), MSNet::getInstance(), MSCFModel::getMaxDecel(), SUMOVehicle::getParameter(), SUMOVehicle::getVehicleType(), MSNet::informVehicleStateListener(), MAX2(), MIN2(), MSVehicleControl::myMaxSpeedFactor, MSVehicleControl::myMinDeceleration, MSVehicleControl::myRunningVehNo, MSVehicleControl::myTotalDepartureDelay, STEPFLOOR, STEPS2TIME, and MSNet::VEHICLE_STATE_DEPARTED.
Referenced by MSVehicleControl::loadedVehEnd(), and MSBaseVehicle::onDepart().
Field Documentation
int MSVehicleControl::myCollisions protected inherited
The number of collisions.
Definition at line 488 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getCollisionCount(), MSVehicleControl::getTeleportCount(), and MSVehicleControl::registerCollision().
bool MSVehicleControl::myDefaultPedTypeMayBeDeleted protected inherited
Whether no pedestrian type was loaded.
Definition at line 543 of file MSVehicleControl.h.
Referenced by MSVehicleControl::checkVType(), and MSVehicleControl::getVType().
bool MSVehicleControl::myDefaultVTypeMayBeDeleted protected inherited
Whether no vehicle type was loaded.
Definition at line 540 of file MSVehicleControl.h.
Referenced by MSVehicleControl::checkVType(), and MSVehicleControl::getVType().
int MSVehicleControl::myDiscarded protected inherited
The number of vehicles which were discarded while loading.
Definition at line 485 of file MSVehicleControl.h.
Referenced by MSVehicleControl::deleteVehicle(), MSVehicleControl::discountStateLoaded(), and MSVehicleControl::getDepartedVehicleNo().
int MSVehicleControl::myEmergencyStops protected inherited
The number of emergency stops.
Definition at line 500 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getEmergencyStops(), and MSVehicleControl::registerEmergencyStop().
int MSVehicleControl::myEndedVehNo protected inherited
The number of removed vehicles.
Definition at line 482 of file MSVehicleControl.h.
Referenced by MSVehicleControl::deleteVehicle(), MSVehicleControl::discountStateLoaded(), MSVehicleControl::getActiveVehicleCount(), MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getEndedVehicleNo(), MSVehicleControl::saveState(), and MSVehicleControl::setState().
int MSVehicleControl::myLoadedVehNo protected inherited
The number of build vehicles.
Definition at line 476 of file MSVehicleControl.h.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleControl::discountStateLoaded(), MSVehicleControl::getActiveVehicleCount(), MSVehicleControl::getLoadedVehicleNo(), MSVehicleControl::getQuota(), MSVehicleControl::saveState(), and MSVehicleControl::setState().
MFXMutex GUIVehicleControl::myLock mutable private
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 129 of file GUIVehicleControl.h.
Referenced by addVehicle(), deleteVehicle(), insertVehicleIDs(), releaseVehicles(), secureVehicles(), and ~GUIVehicleControl().
SUMOTime MSVehicleControl::myMaxRandomDepartOffset protected inherited
The maximum random offset to be added to vehicles departure times (non-negative)
Definition at line 558 of file MSVehicleControl.h.
Referenced by MSVehicleControl::computeRandomDepartOffset(), and MSVehicleControl::MSVehicleControl().
double MSVehicleControl::myMaxSpeedFactor protected inherited
The maximum speed factor for all vehicles in the network.
Definition at line 561 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getMaxSpeedFactor(), and MSVehicleControl::vehicleDeparted().
double MSVehicleControl::myMinDeceleration protected inherited
The minimum deceleration capability for all vehicles in the network.
Definition at line 564 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getMinDeceleration(), and MSVehicleControl::vehicleDeparted().
int MSVehicleControl::myRunningVehNo protected inherited
The number of vehicles within the network (build and inserted but not removed)
Definition at line 479 of file MSVehicleControl.h.
Referenced by MSVehicleControl::discountStateLoaded(), MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getRunningVehicleNo(), MSVehicleControl::saveState(), MSVehicleControl::scheduleVehicleRemoval(), MSVehicleControl::setState(), and MSVehicleControl::vehicleDeparted().
double MSVehicleControl::myScale protected inherited
The scaling factor (especially for inc-dua)
Definition at line 555 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getQuota(), and MSVehicleControl::MSVehicleControl().
int MSVehicleControl::myTeleportsJam protected inherited
The number of teleports due to jam.
Definition at line 491 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getTeleportCount(), MSVehicleControl::getTeleportsJam(), and MSVehicleControl::registerTeleportJam().
int MSVehicleControl::myTeleportsWrongLane protected inherited
The number of teleports due to vehicles stuck on the wrong lane.
Definition at line 497 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getTeleportCount(), MSVehicleControl::getTeleportsWrongLane(), and MSVehicleControl::registerTeleportWrongLane().
int MSVehicleControl::myTeleportsYield protected inherited
The number of teleports due to vehicles stuck on a minor road.
Definition at line 494 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getTeleportCount(), MSVehicleControl::getTeleportsYield(), and MSVehicleControl::registerTeleportYield().
double MSVehicleControl::myTotalDepartureDelay protected inherited
The aggregated time vehicles had to wait for departure (in seconds)
Definition at line 509 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getTotalDepartureDelay(), MSVehicleControl::saveState(), MSVehicleControl::setState(), and MSVehicleControl::vehicleDeparted().
double MSVehicleControl::myTotalTravelTime protected inherited
The aggregated time vehicles needed to aacomplish their route (in seconds)
Definition at line 512 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getTotalTravelTime(), MSVehicleControl::saveState(), MSVehicleControl::scheduleVehicleRemoval(), and MSVehicleControl::setState().
VehicleDictType MSVehicleControl::myVehicleDict protected inherited
Dictionary of vehicles.
Definition at line 522 of file MSVehicleControl.h.
Referenced by MSVehicleControl::abortWaiting(), MSVehicleControl::addVehicle(), MSVehicleControl::deleteVehicle(), MSVehicleControl::getVehicle(), GUIMEVehicleControl::insertVehicleIDs(), insertVehicleIDs(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), MSVehicleControl::saveState(), and MSVehicleControl::~MSVehicleControl().
VTypeDictType MSVehicleControl::myVTypeDict protected inherited
Dictionary of vehicle types.
Definition at line 532 of file MSVehicleControl.h.
Referenced by MSVehicleControl::addVType(), MSVehicleControl::checkVType(), MSVehicleControl::getVType(), MSVehicleControl::insertVTypeIDs(), MSVehicleControl::MSVehicleControl(), MSVehicleControl::removeVType(), MSVehicleControl::saveState(), and MSVehicleControl::~MSVehicleControl().
VTypeDistDictType MSVehicleControl::myVTypeDistDict protected inherited
A distribution of vehicle types (probability->vehicle type)
Definition at line 537 of file MSVehicleControl.h.
Referenced by MSVehicleControl::addVTypeDistribution(), MSVehicleControl::checkVType(), MSVehicleControl::getVType(), MSVehicleControl::hasVTypeDistribution(), MSVehicleControl::insertVTypeIDs(), MSVehicleControl::saveState(), and MSVehicleControl::~MSVehicleControl().
std::map<const MSEdge* const, std::vector<SUMOVehicle*> > MSVehicleControl::myWaiting protected inherited
the lists of waiting vehicles to a given edge
Definition at line 546 of file MSVehicleControl.h.
Referenced by MSVehicleControl::addWaiting(), MSVehicleControl::getWaitingVehicle(), and MSVehicleControl::removeWaiting().
int MSVehicleControl::myWaitingForContainer protected inherited
the number of vehicles wainting for containers contained in myWaiting which can only continue by being triggered
Definition at line 552 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getActiveVehicleCount(), MSVehicleControl::registerOneWaitingForContainer(), and MSVehicleControl::unregisterOneWaitingForContainer().
int MSVehicleControl::myWaitingForPerson protected inherited
the number of vehicles wainting for persons contained in myWaiting which can only continue by being triggered
Definition at line 549 of file MSVehicleControl.h.
Referenced by MSVehicleControl::getActiveVehicleCount(), MSVehicleControl::registerOneWaitingForPerson(), and MSVehicleControl::unregisterOneWaitingForPerson().
The documentation for this class was generated from the following files:
GUIVehicleControl.h
GUIVehicleControl.cpp