SUMO - Simulation of Urban MObility: NBNodeShapeComputer.cpp File Reference
NBNodeShapeComputer.cpp File Reference
#include <config.h>
#include <algorithm>
#include <iterator>
#include <utils/geom/PositionVector.h>
#include <utils/options/OptionsCont.h>
#include <utils/geom/GeomHelper.h>
#include <utils/common/StdDefs.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/ToString.h>
#include <utils/iodevices/OutputDevice.h>
#include "NBNode.h"
#include "NBNodeShapeComputer.h"
Macros
#define DEBUGCOND (myNode.getID() == "disabled")
Functions
void computeSameEnd (PositionVector &l1, PositionVector &l2)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Sept 2002
Version
Id
NBNodeShapeComputer.cpp 24108 2017-04-27 18:43:30Z behrisch
Definition in file NBNodeShapeComputer.cpp.
Macro Definition Documentation
#define DEBUGCOND (myNode.getID() == "disabled")
Definition at line 47 of file NBNodeShapeComputer.cpp.
Referenced by NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), and NBNodeShapeComputer::joinSameDirectionEdges().
Function Documentation
void computeSameEnd (PositionVector & l1, PositionVector & l2)
Definition at line 112 of file NBNodeShapeComputer.cpp.
References PositionVector::add(), PositionVector::extrapolate2D(), PositionVector::getSubpart2D(), PositionVector::intersects(), PositionVector::intersectsAtLengths2D(), PositionVector::length2D(), POSITION_EPS, and PositionVector::positionAtOffset2D().
Referenced by NBNodeShapeComputer::computeUniqueDirectionList().