SUMO - Simulation of Urban MObility: GNERouteProbReroute Class Reference
GNERouteProbReroute Class Reference
#include <GNERouteProbReroute.h>
Public Member Functions
std::string getNewRouteId () const
get new route id
double getProbability () const
get probability
const GNERerouterInterval & getRerouterIntervalParent () const
get rerouter interval parent
SumoXMLTag getTag () const
get tag
GNERouteProbReroute (GNERerouterInterval &rerouterIntervalParent, std::string newRouteId, double probability)
constructor
bool operator== (const GNERouteProbReroute &routeProbReroute) const
overload == operator
void setNewRouteId (std::string newRouteId)
set new route id
bool setProbability (double probability)
set probability, if the new probability is valid
~GNERouteProbReroute ()
destructor
Protected Attributes
std::string myNewRouteId
id of new route
double myProbability
probability with which a vehicle will use the given edge as destination
GNERerouterInterval * myRerouterIntervalParent
reference to rerouter interval parent
SumoXMLTag myTag
XML Tag of route probability reroute.
Detailed Description
Definition at line 52 of file GNERouteProbReroute.h.
Constructor & Destructor Documentation
GNERouteProbReroute::GNERouteProbReroute (GNERerouterInterval & rerouterIntervalParent, std::string newRouteId, double probability)
constructor
Definition at line 40 of file GNERouteProbReroute.cpp.
References setProbability().
GNERouteProbReroute::~GNERouteProbReroute ()
destructor
Definition at line 50 of file GNERouteProbReroute.cpp.
Member Function Documentation
std::string GNERouteProbReroute::getNewRouteId () const
get new route id
Definition at line 55 of file GNERouteProbReroute.cpp.
References myNewRouteId.
Referenced by GNERerouterInterval::insertRouteProbReroute(), and GNERerouterInterval::removeRouteProbReroute().
double GNERouteProbReroute::getProbability () const
get probability
Definition at line 67 of file GNERouteProbReroute.cpp.
References myProbability.
const GNERerouterInterval & GNERouteProbReroute::getRerouterIntervalParent () const
get rerouter interval parent
Definition at line 90 of file GNERouteProbReroute.cpp.
References myRerouterIntervalParent.
SumoXMLTag GNERouteProbReroute::getTag () const
get tag
Definition at line 84 of file GNERouteProbReroute.cpp.
References myTag.
Referenced by GNERerouterInterval::insertRouteProbReroute(), and GNERerouterInterval::removeRouteProbReroute().
bool GNERouteProbReroute::operator== (const GNERouteProbReroute & routeProbReroute) const
overload == operator
Definition at line 96 of file GNERouteProbReroute.cpp.
References myNewRouteId, myProbability, and myRerouterIntervalParent.
void GNERouteProbReroute::setNewRouteId (std::string newRouteId)
set new route id
Definition at line 61 of file GNERouteProbReroute.cpp.
References myNewRouteId.
bool GNERouteProbReroute::setProbability (double probability)
set probability, if the new probability is valid
Definition at line 73 of file GNERouteProbReroute.cpp.
References myProbability.
Referenced by GNERouteProbReroute().
Field Documentation
std::string GNERouteProbReroute::myNewRouteId protected
id of new route
Todo:
change string to GNERoute
Definition at line 87 of file GNERouteProbReroute.h.
Referenced by getNewRouteId(), operator==(), and setNewRouteId().
double GNERouteProbReroute::myProbability protected
probability with which a vehicle will use the given edge as destination
Definition at line 90 of file GNERouteProbReroute.h.
Referenced by getProbability(), operator==(), and setProbability().
GNERerouterInterval* GNERouteProbReroute::myRerouterIntervalParent protected
reference to rerouter interval parent
Definition at line 83 of file GNERouteProbReroute.h.
Referenced by getRerouterIntervalParent(), and operator==().
SumoXMLTag GNERouteProbReroute::myTag protected
XML Tag of route probability reroute.
Definition at line 93 of file GNERouteProbReroute.h.
Referenced by getTag().
The documentation for this class was generated from the following files:
GNERouteProbReroute.h
GNERouteProbReroute.cpp