SUMO - Simulation of Urban MObility: MSTransportable::Stage Class Reference
MSTransportable::Stage Class Reference abstract
#include <MSTransportable.h>
Public Member Functions
virtual void abort (MSTransportable *)
abort this stage (TraCI)
virtual void beginEventOutput (const MSTransportable &transportable, SUMOTime t, OutputDevice &os) const =0
Called for writing the events output (begin of an action)
virtual void endEventOutput (const MSTransportable &transportable, SUMOTime t, OutputDevice &os) const =0
Called for writing the events output (end of an action)
virtual double getAngle (SUMOTime now) const =0
returns the angle of the transportable
double getArrivalPos () const
const MSEdge & getDestination () const
returns the destination edge
const MSStoppingPlace * getDestinationStop () const
returns the destination stop (if any)
virtual const MSEdge * getEdge () const =0
Returns the current edge.
double getEdgeAngle (const MSEdge *e, double at) const
get angle of the edge at a certain position
virtual double getEdgePos (SUMOTime now) const =0
Position getEdgePosition (const MSEdge *e, double at, double offset) const
get position on edge e at length at with orthogonal offset
virtual ConstMSEdgeVector getEdges () const =0
the edges of the current stage
virtual const MSEdge * getFromEdge () const =0
Position getLanePosition (const MSLane *lane, double at, double offset) const
get position on lane at length at with orthogonal offset
virtual Position getPosition (SUMOTime now) const =0
returns the position of the transportable
virtual double getSpeed () const =0
the speed of the transportable
virtual std::string getStageDescription () const =0
return string representation of the current stage
StageType getStageType () const
virtual SUMOVehicle * getVehicle () const
Whether the transportable waits for a vehicle.
virtual SUMOTime getWaitingTime (SUMOTime now) const =0
the time this transportable spent waiting
virtual bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
virtual bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
virtual void proceed (MSNet *net, MSTransportable *transportable, SUMOTime now, Stage *previous)=0
proceeds to this stage
virtual void routeOutput (OutputDevice &os) const =0
Called on writing vehroute output.
void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual void setSpeed (double)
sets the walking speed (ignored in other stages)
Stage (const MSEdge &destination, MSStoppingPlace *toStop, const double arrivalPos, StageType type)
constructor
virtual void tripInfoOutput (OutputDevice &os) const =0
Called on writing tripinfo output.
virtual ~Stage ()
destructor
Protected Attributes
double myArrivalPos
the position at which we want to arrive
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach by getting transported
MSStoppingPlace *const myDestinationStop
the stop to reach by getting transported (if any)
StageType myType
The type of this stage.
Private Member Functions
Stage & operator= (const Stage &)
Invalidated assignment operator.
Stage (const Stage &)
Invalidated copy constructor.
Detailed Description
The "abstract" class for a single stage of a movement Contains the destination of the current movement step
Definition at line 73 of file MSTransportable.h.
Constructor & Destructor Documentation
MSTransportable::Stage::Stage (const MSEdge & destination, MSStoppingPlace * toStop, const double arrivalPos, StageType type)
constructor
Definition at line 53 of file MSTransportable.cpp.
MSTransportable::Stage::~Stage () virtual
destructor
Definition at line 56 of file MSTransportable.cpp.
MSTransportable::Stage::Stage (const Stage &) private
Invalidated copy constructor.
Member Function Documentation
virtual void MSTransportable::Stage::abort (MSTransportable *) inline virtual
abort this stage (TraCI)
Reimplemented in MSTransportable::Stage_Driving, and MSPerson::MSPersonStage_Walking.
Definition at line 116 of file MSTransportable.h.
virtual void MSTransportable::Stage::beginEventOutput (const MSTransportable & transportable, SUMOTime t, OutputDevice & os) const pure virtual
Called for writing the events output (begin of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), getVehicle(), and MSTransportable::Stage_Driving::setVehicle().
virtual void MSTransportable::Stage::endEventOutput (const MSTransportable & transportable, SUMOTime t, OutputDevice & os) const pure virtual
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), getVehicle(), and MSTransportable::Stage_Driving::setVehicle().
virtual double MSTransportable::Stage::getAngle (SUMOTime now) const pure virtual
returns the angle of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), and MSTransportable::getFromEdge().
double MSTransportable::Stage::getArrivalPos () const inline
Definition at line 89 of file MSTransportable.h.
References getAngle(), getEdge(), getEdgePos(), getFromEdge(), getPosition(), and myArrivalPos.
const MSEdge & MSTransportable::Stage::getDestination () const
returns the destination edge
Definition at line 59 of file MSTransportable.cpp.
References myDestination.
Referenced by MSTransportable::Stage_Waiting::getEdges(), MSTransportable::Stage_Driving::getEdges(), MSPModel_Striping::moveInDirectionOnLane(), MSContainer::MSContainerStage_Driving::routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
const MSStoppingPlace* MSTransportable::Stage::getDestinationStop () const inline
returns the destination stop (if any)
Definition at line 85 of file MSTransportable.h.
References myDestinationStop.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
virtual const MSEdge* MSTransportable::Stage::getEdge () const pure virtual
Returns the current edge.
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Walking::proceed(), MSContainer::MSContainerStage_Tranship::proceed(), MSContainer::proceed(), MSTransportable::Stage_Waiting::proceed(), MSPerson::MSPersonStage_Driving::proceed(), and MSPerson::proceed().
double MSTransportable::Stage::getEdgeAngle (const MSEdge * e, double at) const
get angle of the edge at a certain position
Definition at line 92 of file MSTransportable.cpp.
References MSEdge::getLanes().
Referenced by MSPModel_NonInteracting::PState::getAngle(), CState::getAngle(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), and getVehicle().
virtual double MSTransportable::Stage::getEdgePos (SUMOTime now) const pure virtual
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), MSTransportable::getFromEdge(), MSEdge::transportable_by_position_sorter::operator()(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Walking::proceed(), MSContainer::MSContainerStage_Tranship::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
Position MSTransportable::Stage::getEdgePosition (const MSEdge * e, double at, double offset) const
get position on edge e at length at with orthogonal offset
Definition at line 82 of file MSTransportable.cpp.
References getLanePosition(), and MSEdge::getLanes().
Referenced by MSTransportable::Stage_Waiting::getPosition(), MSTransportable::Stage_Driving::getPosition(), and getVehicle().
virtual ConstMSEdgeVector MSTransportable::Stage::getEdges () const pure virtual
the edges of the current stage
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::getEdges(), getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
virtual const MSEdge* MSTransportable::Stage::getFromEdge () const pure virtual
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos().
Position MSTransportable::Stage::getLanePosition (const MSLane * lane, double at, double offset) const
get position on lane at length at with orthogonal offset
Definition at line 87 of file MSTransportable.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::positionAtOffset().
Referenced by CState::computeTranshipTime(), getEdgePosition(), MSPModel_NonInteracting::PState::getPosition(), MSPModel_Striping::PState::getPosition(), and getVehicle().
virtual Position MSTransportable::Stage::getPosition (SUMOTime now) const pure virtual
returns the position of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), and MSTransportable::getFromEdge().
virtual double MSTransportable::Stage::getSpeed () const pure virtual
the speed of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::getFromEdge(), getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
virtual std::string MSTransportable::Stage::getStageDescription () const pure virtual
return string representation of the current stage
Implemented in MSPerson::MSPersonStage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by getStageType().
StageType MSTransportable::Stage::getStageType () const inline
Definition at line 105 of file MSTransportable.h.
References getStageDescription(), myType, and proceed().
Referenced by MSTransportable::getStageType().
virtual SUMOVehicle* MSTransportable::Stage::getVehicle () const inline virtual
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 136 of file MSTransportable.h.
References beginEventOutput(), endEventOutput(), getEdgeAngle(), getEdgePosition(), getEdges(), getLanePosition(), getSpeed(), getWaitingTime(), routeOutput(), and tripInfoOutput().
virtual SUMOTime MSTransportable::Stage::getWaitingTime (SUMOTime now) const pure virtual
the time this transportable spent waiting
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
virtual bool MSTransportable::Stage::isWaiting4Vehicle () const inline virtual
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 131 of file MSTransportable.h.
bool MSTransportable::Stage::isWaitingFor (const std::string & line) const virtual
Whether the transportable waits for a vehicle of the line specified.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 77 of file MSTransportable.cpp.
Referenced by setSpeed().
Stage& MSTransportable::Stage::operator= (const Stage &) private
Invalidated assignment operator.
virtual void MSTransportable::Stage::proceed (MSNet * net, MSTransportable * transportable, SUMOTime now, Stage * previous) pure virtual
proceeds to this stage
Implemented in MSPerson::MSPersonStage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), and getStageType().
virtual void MSTransportable::Stage::routeOutput (OutputDevice & os) const pure virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSPerson::MSPersonStage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by MSTransportable::getEdges(), MSTransportable::Stage_Waiting::getStageDescription(), and getVehicle().
void MSTransportable::Stage::setArrived (SUMOTime now)
logs end of the step
Definition at line 72 of file MSTransportable.cpp.
References myArrived.
Referenced by MSContainer::proceed(), MSPerson::proceed(), and setSpeed().
void MSTransportable::Stage::setDeparted (SUMOTime now)
logs end of the step
Definition at line 65 of file MSTransportable.cpp.
References myDeparted.
Referenced by MSTransportable::getVehicleType(), and setSpeed().
virtual void MSTransportable::Stage::setSpeed (double) inline virtual
sets the walking speed (ignored in other stages)
Reimplemented in MSPerson::MSPersonStage_Walking.
Definition at line 119 of file MSTransportable.h.
References isWaitingFor(), setArrived(), and setDeparted().
Referenced by MSTransportable::getVehicle().
virtual void MSTransportable::Stage::tripInfoOutput (OutputDevice & os) const pure virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSPerson::MSPersonStage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by MSTransportable::getEdges(), MSTransportable::Stage_Waiting::getStageDescription(), and getVehicle().
Field Documentation
double MSTransportable::Stage::myArrivalPos protected
the position at which we want to arrive
Definition at line 190 of file MSTransportable.h.
Referenced by MSPerson::MSPersonStage_Walking::computeAverageSpeed(), MSTransportable::Stage_Waiting::getAngle(), getArrivalPos(), MSPerson::MSPersonStage_Walking::getArrivalPos(), MSContainer::MSContainerStage_Tranship::getArrivalPos(), MSTransportable::Stage_Waiting::getEdgePos(), and MSTransportable::Stage_Waiting::getPosition().
SUMOTime MSTransportable::Stage::myArrived protected
the time at which this stage ended
Definition at line 196 of file MSTransportable.h.
Referenced by setArrived(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
SUMOTime MSTransportable::Stage::myDeparted protected
the time at which this stage started
Definition at line 193 of file MSTransportable.h.
Referenced by setDeparted(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
const MSEdge& MSTransportable::Stage::myDestination protected
the next edge to reach by getting transported
Definition at line 184 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getAngle(), getDestination(), MSTransportable::Stage_Waiting::getEdge(), MSTransportable::Stage_Waiting::getFromEdge(), and MSTransportable::Stage_Waiting::getPosition().
MSStoppingPlace* const MSTransportable::Stage::myDestinationStop protected
the stop to reach by getting transported (if any)
Definition at line 187 of file MSTransportable.h.
Referenced by getDestinationStop(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and MSContainer::MSContainerStage_Tranship::moveToNextEdge().
StageType MSTransportable::Stage::myType protected
The type of this stage.
Definition at line 199 of file MSTransportable.h.
Referenced by getStageType(), MSTransportable::Stage_Waiting::routeOutput(), and MSTransportable::Stage_Waiting::tripInfoOutput().
The documentation for this class was generated from the following files:
MSTransportable.h
MSTransportable.cpp