SUMO - Simulation of Urban MObility: MSTransportable::Stage_Waiting Class Reference
MSTransportable::Stage_Waiting Class Reference
#include <MSTransportable.h>
Public Member Functions
virtual void abort (MSTransportable *)
abort this stage (TraCI)
virtual void beginEventOutput (const MSTransportable &p, SUMOTime t, OutputDevice &os) const
Called for writing the events output.
virtual void endEventOutput (const MSTransportable &p, SUMOTime t, OutputDevice &os) const
Called for writing the events output (end of an action)
double getAngle (SUMOTime now) const
returns the angle of the transportable
double getArrivalPos () const
const MSEdge & getDestination () const
returns the destination edge
const MSStoppingPlace * getDestinationStop () const
returns the destination stop (if any)
const MSEdge * getEdge () const
Returns the current edge.
double getEdgeAngle (const MSEdge *e, double at) const
get angle of the edge at a certain position
double getEdgePos (SUMOTime now) const
Position getEdgePosition (const MSEdge *e, double at, double offset) const
get position on edge e at length at with orthogonal offset
ConstMSEdgeVector getEdges () const
the edges of the current stage
const MSEdge * getFromEdge () const
Position getLanePosition (const MSLane *lane, double at, double offset) const
get position on lane at length at with orthogonal offset
Position getPosition (SUMOTime now) const
returns the position of the transportable
double getSpeed () const
the speed of the transportable
std::string getStageDescription () const
return string representation of the current stage
StageType getStageType () const
SUMOTime getUntil () const
virtual SUMOVehicle * getVehicle () const
Whether the transportable waits for a vehicle.
SUMOTime getWaitingTime (SUMOTime now) const
the time this transportable spent waiting
virtual bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
virtual bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
virtual void proceed (MSNet *net, MSTransportable *transportable, SUMOTime now, Stage *previous)
proceeds to the next step
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual void setSpeed (double)
sets the walking speed (ignored in other stages)
Stage_Waiting (const MSEdge &destination, SUMOTime duration, SUMOTime until, double pos, const std::string &actType, const bool initial)
constructor
virtual void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
virtual ~Stage_Waiting ()
destructor
Protected Attributes
double myArrivalPos
the position at which we want to arrive
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach by getting transported
MSStoppingPlace *const myDestinationStop
the stop to reach by getting transported (if any)
StageType myType
The type of this stage.
Private Member Functions
Stage_Waiting & operator= (const Stage_Waiting &)
Invalidated assignment operator.
Stage_Waiting (const Stage_Waiting &)
Invalidated copy constructor.
Private Attributes
std::string myActType
The type of activity.
SUMOTime myWaitingDuration
the time the person is waiting
SUMOTime myWaitingStart
the time the person is waiting
SUMOTime myWaitingUntil
the time until the person is waiting
Detailed Description
A "real" stage performing a waiting over the specified time
Definition at line 213 of file MSTransportable.h.
Constructor & Destructor Documentation
MSTransportable::Stage_Waiting::Stage_Waiting (const MSEdge & destination, SUMOTime duration, SUMOTime until, double pos, const std::string & actType, const bool initial)
constructor
Definition at line 100 of file MSTransportable.cpp.
MSTransportable::Stage_Waiting::~Stage_Waiting () virtual
destructor
Definition at line 112 of file MSTransportable.cpp.
MSTransportable::Stage_Waiting::Stage_Waiting (const Stage_Waiting &) private
Invalidated copy constructor.
Member Function Documentation
virtual void MSTransportable::Stage::abort (MSTransportable *) inline virtual inherited
abort this stage (TraCI)
Reimplemented in MSTransportable::Stage_Driving, and MSPerson::MSPersonStage_Walking.
Definition at line 116 of file MSTransportable.h.
void MSTransportable::Stage_Waiting::beginEventOutput (const MSTransportable & p, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 189 of file MSTransportable.cpp.
References getEdge(), Named::getID(), MSTransportable::getID(), myActType, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
void MSTransportable::Stage_Waiting::endEventOutput (const MSTransportable & p, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 196 of file MSTransportable.cpp.
References getEdge(), Named::getID(), MSTransportable::getID(), myActType, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
double MSTransportable::Stage_Waiting::getAngle (SUMOTime now) const virtual
returns the angle of the transportable
Implements MSTransportable::Stage.
Definition at line 146 of file MSTransportable.cpp.
References MSTransportable::Stage::getEdgeAngle(), M_PI, MSTransportable::Stage::myArrivalPos, and MSTransportable::Stage::myDestination.
double MSTransportable::Stage::getArrivalPos () const inline inherited
Definition at line 89 of file MSTransportable.h.
References MSTransportable::Stage::getAngle(), MSTransportable::Stage::getEdge(), MSTransportable::Stage::getEdgePos(), MSTransportable::Stage::getFromEdge(), MSTransportable::Stage::getPosition(), and MSTransportable::Stage::myArrivalPos.
const MSEdge & MSTransportable::Stage::getDestination () const inherited
returns the destination edge
Definition at line 59 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
Referenced by getEdges(), MSTransportable::Stage_Driving::getEdges(), MSPModel_Striping::moveInDirectionOnLane(), MSContainer::MSContainerStage_Driving::routeOutput(), routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
const MSStoppingPlace* MSTransportable::Stage::getDestinationStop () const inline inherited
returns the destination stop (if any)
Definition at line 85 of file MSTransportable.h.
References MSTransportable::Stage::myDestinationStop.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
const MSEdge * MSTransportable::Stage_Waiting::getEdge () const virtual
Returns the current edge.
Implements MSTransportable::Stage.
Definition at line 116 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
Referenced by beginEventOutput(), and endEventOutput().
double MSTransportable::Stage::getEdgeAngle (const MSEdge * e, double at) const inherited
get angle of the edge at a certain position
Definition at line 92 of file MSTransportable.cpp.
References MSEdge::getLanes().
Referenced by MSPModel_NonInteracting::PState::getAngle(), CState::getAngle(), getAngle(), MSTransportable::Stage_Driving::getAngle(), and MSTransportable::Stage::getVehicle().
double MSTransportable::Stage_Waiting::getEdgePos (SUMOTime now) const virtual
Implements MSTransportable::Stage.
Definition at line 128 of file MSTransportable.cpp.
References MSTransportable::Stage::myArrivalPos.
Position MSTransportable::Stage::getEdgePosition (const MSEdge * e, double at, double offset) const inherited
get position on edge e at length at with orthogonal offset
Definition at line 82 of file MSTransportable.cpp.
References MSTransportable::Stage::getLanePosition(), and MSEdge::getLanes().
Referenced by getPosition(), MSTransportable::Stage_Driving::getPosition(), and MSTransportable::Stage::getVehicle().
ConstMSEdgeVector MSTransportable::Stage_Waiting::getEdges () const virtual
the edges of the current stage
Implements MSTransportable::Stage.
Definition at line 215 of file MSTransportable.cpp.
References MSTransportable::Stage::getDestination().
const MSEdge * MSTransportable::Stage_Waiting::getFromEdge () const virtual
Implements MSTransportable::Stage.
Definition at line 122 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
Position MSTransportable::Stage::getLanePosition (const MSLane * lane, double at, double offset) const inherited
get position on lane at length at with orthogonal offset
Definition at line 87 of file MSTransportable.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::positionAtOffset().
Referenced by CState::computeTranshipTime(), MSTransportable::Stage::getEdgePosition(), MSPModel_NonInteracting::PState::getPosition(), MSPModel_Striping::PState::getPosition(), and MSTransportable::Stage::getVehicle().
Position MSTransportable::Stage_Waiting::getPosition (SUMOTime now) const virtual
returns the position of the transportable
Implements MSTransportable::Stage.
Definition at line 140 of file MSTransportable.cpp.
References MSTransportable::Stage::getEdgePosition(), MSTransportable::Stage::myArrivalPos, MSTransportable::Stage::myDestination, and MSTransportable::ROADSIDE_OFFSET.
double MSTransportable::Stage_Waiting::getSpeed () const virtual
the speed of the transportable
Implements MSTransportable::Stage.
Definition at line 209 of file MSTransportable.cpp.
std::string MSTransportable::Stage_Waiting::getStageDescription () const inline virtual
return string representation of the current stage
Implements MSTransportable::Stage.
Definition at line 239 of file MSTransportable.h.
References MSTransportable::Stage::beginEventOutput(), MSTransportable::Stage::endEventOutput(), MSTransportable::Stage::proceed(), MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
StageType MSTransportable::Stage::getStageType () const inline inherited
Definition at line 105 of file MSTransportable.h.
References MSTransportable::Stage::getStageDescription(), MSTransportable::Stage::myType, and MSTransportable::Stage::proceed().
Referenced by MSTransportable::getStageType().
SUMOTime MSTransportable::Stage_Waiting::getUntil () const
Definition at line 134 of file MSTransportable.cpp.
References myWaitingUntil.
virtual SUMOVehicle* MSTransportable::Stage::getVehicle () const inline virtual inherited
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 136 of file MSTransportable.h.
References MSTransportable::Stage::beginEventOutput(), MSTransportable::Stage::endEventOutput(), MSTransportable::Stage::getEdgeAngle(), MSTransportable::Stage::getEdgePosition(), MSTransportable::Stage::getEdges(), MSTransportable::Stage::getLanePosition(), MSTransportable::Stage::getSpeed(), MSTransportable::Stage::getWaitingTime(), MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
SUMOTime MSTransportable::Stage_Waiting::getWaitingTime (SUMOTime now) const virtual
the time this transportable spent waiting
Implements MSTransportable::Stage.
Definition at line 203 of file MSTransportable.cpp.
References myWaitingStart.
virtual bool MSTransportable::Stage::isWaiting4Vehicle () const inline virtual inherited
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 131 of file MSTransportable.h.
bool MSTransportable::Stage::isWaitingFor (const std::string & line) const virtual inherited
Whether the transportable waits for a vehicle of the line specified.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 77 of file MSTransportable.cpp.
Referenced by MSTransportable::Stage::setSpeed().
Stage_Waiting& MSTransportable::Stage_Waiting::operator= (const Stage_Waiting &) private
Invalidated assignment operator.
void MSTransportable::Stage_Waiting::proceed (MSNet * net, MSTransportable * transportable, SUMOTime now, Stage * previous) virtual
proceeds to the next step
Implements MSTransportable::Stage.
Definition at line 152 of file MSTransportable.cpp.
References MSEdge::addContainer(), MSEdge::addPerson(), MSNet::getContainerControl(), MSTransportable::Stage::getEdge(), MSNet::getPersonControl(), MAX3(), myWaitingDuration, myWaitingStart, myWaitingUntil, and MSTransportableControl::setWaitEnd().
void MSTransportable::Stage_Waiting::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 174 of file MSTransportable.cpp.
References OutputDevice::closeTag(), MSTransportable::Stage::getDestination(), MSTransportable::getID(), MSTransportable::Stage::myType, myWaitingDuration, myWaitingUntil, OutputDevice::openTag(), SUMO_ATTR_DURATION, SUMO_ATTR_LANE, SUMO_ATTR_UNTIL, time2string(), MSTransportable::WAITING_FOR_DEPART, and OutputDevice::writeAttr().
void MSTransportable::Stage::setArrived (SUMOTime now) inherited
logs end of the step
Definition at line 72 of file MSTransportable.cpp.
References MSTransportable::Stage::myArrived.
Referenced by MSContainer::proceed(), MSPerson::proceed(), and MSTransportable::Stage::setSpeed().
void MSTransportable::Stage::setDeparted (SUMOTime now) inherited
logs end of the step
Definition at line 65 of file MSTransportable.cpp.
References MSTransportable::Stage::myDeparted.
Referenced by MSTransportable::getVehicleType(), and MSTransportable::Stage::setSpeed().
virtual void MSTransportable::Stage::setSpeed (double) inline virtual inherited
sets the walking speed (ignored in other stages)
Reimplemented in MSPerson::MSPersonStage_Walking.
Definition at line 119 of file MSTransportable.h.
References MSTransportable::Stage::isWaitingFor(), MSTransportable::Stage::setArrived(), and MSTransportable::Stage::setDeparted().
Referenced by MSTransportable::getVehicle().
void MSTransportable::Stage_Waiting::tripInfoOutput (OutputDevice & os) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 166 of file MSTransportable.cpp.
References OutputDevice::closeTag(), MSTransportable::Stage::myArrived, MSTransportable::Stage::myType, OutputDevice::openTag(), time2string(), MSTransportable::WAITING_FOR_DEPART, and OutputDevice::writeAttr().
Field Documentation
std::string MSTransportable::Stage_Waiting::myActType private
The type of activity.
Definition at line 283 of file MSTransportable.h.
Referenced by beginEventOutput(), and endEventOutput().
double MSTransportable::Stage::myArrivalPos protected inherited
the position at which we want to arrive
Definition at line 190 of file MSTransportable.h.
Referenced by MSPerson::MSPersonStage_Walking::computeAverageSpeed(), getAngle(), MSTransportable::Stage::getArrivalPos(), MSPerson::MSPersonStage_Walking::getArrivalPos(), MSContainer::MSContainerStage_Tranship::getArrivalPos(), getEdgePos(), and getPosition().
SUMOTime MSTransportable::Stage::myArrived protected inherited
the time at which this stage ended
Definition at line 196 of file MSTransportable.h.
Referenced by MSTransportable::Stage::setArrived(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
SUMOTime MSTransportable::Stage::myDeparted protected inherited
the time at which this stage started
Definition at line 193 of file MSTransportable.h.
Referenced by MSTransportable::Stage::setDeparted(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
const MSEdge& MSTransportable::Stage::myDestination protected inherited
the next edge to reach by getting transported
Definition at line 184 of file MSTransportable.h.
Referenced by getAngle(), MSTransportable::Stage::getDestination(), getEdge(), getFromEdge(), and getPosition().
MSStoppingPlace* const MSTransportable::Stage::myDestinationStop protected inherited
the stop to reach by getting transported (if any)
Definition at line 187 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getDestinationStop(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and MSContainer::MSContainerStage_Tranship::moveToNextEdge().
StageType MSTransportable::Stage::myType protected inherited
The type of this stage.
Definition at line 199 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getStageType(), routeOutput(), and tripInfoOutput().
SUMOTime MSTransportable::Stage_Waiting::myWaitingDuration private
the time the person is waiting
Definition at line 274 of file MSTransportable.h.
Referenced by proceed(), and routeOutput().
SUMOTime MSTransportable::Stage_Waiting::myWaitingStart private
the time the person is waiting
Definition at line 280 of file MSTransportable.h.
Referenced by getWaitingTime(), and proceed().
SUMOTime MSTransportable::Stage_Waiting::myWaitingUntil private
the time until the person is waiting
Definition at line 277 of file MSTransportable.h.
Referenced by getUntil(), proceed(), and routeOutput().
The documentation for this class was generated from the following files:
MSTransportable.h
MSTransportable.cpp