SUMO - Simulation of Urban MObility: MSParkingArea Class Reference
MSParkingArea Class Reference
A lane area vehicles can halt at.
#include <MSParkingArea.h>
Data Structures
struct LotSpaceDefinition
Representation of a single lot space.
Public Member Functions
virtual void addAccess (MSLane *lane, const double pos)
adds an access point to this stop
void addLotEntry (double x, double y, double z, double width, double length, double angle)
Add a lot entry to parking area.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void addTransportable (MSTransportable *p)
adds a transportable to this stop
void enter (SUMOVehicle *what, double beg, double end)
Called if a vehicle enters this stop.
double getAngle () const
Returns the lot rectangle angle.
double getBeginLanePosition () const
Returns the begin position of this stop.
int getCapacity () const
Returns the area capacity.
double getEndLanePosition () const
Returns the end position of this stop.
const std::string & getID () const
Returns the id.
const MSLane & getLane () const
Returns the lane this stop is located at.
double getLastFreePos (const SUMOVehicle &forVehicle) const
Returns the last free position on this stop.
double getLength () const
Returns the lot rectangle length.
const std::string & getMyName () const
int getOccupancy () const
Returns the area occupancy.
double getSpaceDim () const
Returns the space dimension.
double getStoppingPosition (const SUMOVehicle *veh) const
For vehicles at the stop this gives the the actual stopping position of the vehicle. For all others the last free stopping position.
int getTransportableNumber () const
Returns the number of transportables waiting on this stop.
double getVehicleAngle (const SUMOVehicle &forVehicle)
Returns the angle of parked vehicle.
Position getVehiclePosition (const SUMOVehicle &forVehicle)
Returns the position of parked vehicle.
Position getWaitPosition () const
Returns the next free waiting place for pedestrians / containers.
double getWidth () const
Returns the lot rectangle width.
bool hasAccess (const MSEdge *edge) const
checks whether this stop provides access to the given edge
void leaveFrom (SUMOVehicle *what)
Called if a vehicle leaves this stop.
MSParkingArea (const std::string &id, const std::vector< std::string > &lines, MSLane &lane, double begPos, double endPos, unsigned int capacity, double width, double length, double angle)
Constructor.
void removeTransportable (MSTransportable *p)
Removes a transportable from this stop.
void setID (const std::string &newID)
resets the id
virtual ~MSParkingArea ()
Destructor.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Member Functions
void computeLastFreePos ()
Computes the last free position on this stop.
Protected Attributes
std::multimap< MSLane *, double > myAccessPos
lanes and positions connected to this stop
double myAngle
The default angle of each parking space.
const double myBegPos
The begin position this bus stop is located at.
int myCapacity
Stop area capacity.
const double myEndPos
The end position this bus stop is located at.
std::map< const SUMOVehicle *, std::pair< double, double > > myEndPositions
A map from objects (vehicles) to the areas they acquire after entering the stop.
std::string myID
The name of the object.
const MSLane & myLane
The lane this bus stop is located at.
int myLastFreeLot
Last free lot number (0 no free lot)
double myLastFreePos
The last free position at this stop (variable)
double myLength
The default length of each parking space.
std::vector< std::string > myLines
The list of lines that are assigned to this stop.
const std::string myName
The name of the stopping place.
PositionVector myShape
The roadside shape of this parkingArea.
std::map< unsigned int, LotSpaceDefinition > mySpaceOccupancies
A map from objects (vehicles) to the areas they acquire after entering the stop.
double myWaitingPos
The next free position for persons / containers.
std::vector< MSTransportable * > myWaitingTransportables
Persons waiting at this stop.
double myWidth
The default width of each parking space.
Private Member Functions
MSParkingArea (const MSParkingArea &)
Invalidated copy constructor.
MSParkingArea & operator= (const MSParkingArea &)
Invalidated assignment operator.
Detailed Description
A lane area vehicles can halt at.
The stop tracks the last free space a vehicle may halt at by being informed about a vehicle's entering and depart. It keeps the information about entered vehicles' begin and end position within an internal container ("myEndPositions") and is so able to compute the last free space.
Please note that using the last free space disallows vehicles to enter a free space in between other vehicles.
Definition at line 66 of file MSParkingArea.h.
Constructor & Destructor Documentation
MSParkingArea::MSParkingArea (const std::string & id, const std::vector< std::string > & lines, MSLane & lane, double begPos, double endPos, unsigned int capacity, double width, double length, double angle)
Constructor.
Parameters
[in] id The id of the stop
[in] net The net the stop belongs to
[in] lines Names of the lines that halt on this stop
[in] lane The lane the stop is placed on
[in] begPos Begin position of the stop on the lane
[in] endPos End position of the stop on the lane
[in] capacity Capacity of the stop
[in] width Width of the default lot rectangle
[in] length Length of the default lot rectangle
[in] angle Angle of the default lot rectangle
Definition at line 45 of file MSParkingArea.cpp.
References computeLastFreePos(), MSLane::getShape(), getSpaceDim(), PositionVector::getSubpart(), MSLane::getWidth(), PositionVector::move2side(), myAngle, MSStoppingPlace::myBegPos, myCapacity, myLength, myShape, mySpaceOccupancies, myWidth, PI, PositionVector::positionAtOffset(), SUMO_const_laneWidth, Position::x(), and Position::y().
MSParkingArea::~MSParkingArea () virtual
Destructor.
Definition at line 95 of file MSParkingArea.cpp.
MSParkingArea::MSParkingArea (const MSParkingArea &) private
Invalidated copy constructor.
Member Function Documentation
virtual void MSStoppingPlace::addAccess (MSLane * lane, const double pos) inline virtual inherited
adds an access point to this stop
Reimplemented in GUIBusStop.
Definition at line 165 of file MSStoppingPlace.h.
References MSStoppingPlace::computeLastFreePos(), MSStoppingPlace::hasAccess(), and MSStoppingPlace::myAccessPos.
Referenced by GUIBusStop::addAccess(), and NLTriggerBuilder::addAccess().
void MSParkingArea::addLotEntry (double x, double y, double z, double width, double length, double angle)
Add a lot entry to parking area.
Parameters
[in] x X position of the lot center
[in] y Y position of the lot center
[in] z Z position of the lot center
[in] width Width of the lot rectangle
[in] length Length of the lot rectangle
[in] angle Angle of the lot rectangle
Returns
Whether the lot entry could be added
Definition at line 132 of file MSParkingArea.cpp.
References computeLastFreePos(), myCapacity, MSStoppingPlace::myEndPos, and mySpaceOccupancies.
Referenced by NLTriggerBuilder::addLotEntry().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
void MSStoppingPlace::addTransportable (MSTransportable * p) inherited
adds a transportable to this stop
Definition at line 109 of file MSStoppingPlace.cpp.
References MSVehicleType::getLength(), MSTransportable::getVehicleType(), MSStoppingPlace::myWaitingPos, and MSStoppingPlace::myWaitingTransportables.
Referenced by MSStoppingPlace::getTransportableNumber(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and MSContainer::MSContainerStage_Tranship::moveToNextEdge().
void MSParkingArea::computeLastFreePos () protected
Computes the last free position on this stop.
The last free position is the one, the last vehicle ends at. It is stored in myLastFreePos. If no vehicle halts, the last free position gets the value of myEndPos.
Definition at line 176 of file MSParkingArea.cpp.
References MSStoppingPlace::myBegPos, myLastFreeLot, MSStoppingPlace::myLastFreePos, and mySpaceOccupancies.
Referenced by addLotEntry(), enter(), leaveFrom(), and MSParkingArea().
void MSParkingArea::enter (SUMOVehicle * what, double beg, double end)
Called if a vehicle enters this stop.
Stores the position of the entering vehicle in myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that enters the bus stop
[in] beg The begin halting position of the vehicle
[in] what The end halting position of the vehicle
See also
computeLastFreePos
Definition at line 151 of file MSParkingArea.cpp.
References computeLastFreePos(), MSStoppingPlace::myEndPositions, myLastFreeLot, and mySpaceOccupancies.
Referenced by MSVehicle::processNextStop().
double MSParkingArea::getAngle () const
Returns the lot rectangle angle.
Returns
The angle
Definition at line 203 of file MSParkingArea.cpp.
References myAngle.
Referenced by NLTriggerBuilder::parseAndAddLotEntry().
double MSStoppingPlace::getBeginLanePosition () const inherited
Returns the begin position of this stop.
Returns
The position the stop begins at
Definition at line 65 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myBegPos.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getChargingStationID(), MSChargingStation::MSChargingStation(), MSRouteHandler::parseWalkPositions(), MSVehicle::processNextStop(), MSVehicle::replaceParkingArea(), MSTriggeredRerouter::rerouteParkingZone(), and MSChargingStation::vehicleIsInside().
int MSParkingArea::getCapacity () const
Returns the area capacity.
Returns
The capacity
Definition at line 209 of file MSParkingArea.cpp.
References myCapacity.
Referenced by GUIParkingArea::getParameterWindow(), MSVehicle::processNextStop(), and MSTriggeredRerouter::rerouteParkingZone().
double MSStoppingPlace::getEndLanePosition () const inherited
Returns the end position of this stop.
Returns
The position the stop ends at
Definition at line 71 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myEndPos.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getBusStopID(), MSNet::getChargingStationID(), MSNet::getContainerStopID(), MSNet::getParkingAreaID(), MSChargingStation::MSChargingStation(), MSRouteHandler::parseWalkPositions(), MSVehicle::processNextStop(), MSStoppingPlace::removeTransportable(), MSVehicle::replaceParkingArea(), and MSChargingStation::vehicleIsInside().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), MSNet::addParkingArea(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), TraCI_Vehicle::getBestLanes(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), TraCI_Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), TraCI_Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), TraCI_Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSNet::getParkingAreaID(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), TraCI_Vehicle::getRoadID(), TraCI_Vehicle::getRouteID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_SSM::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSDevice_SSM::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_SSM::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingZone(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), toString(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSDevice_SSM::updateEncounter(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSPModel_Striping::PState::moveToNextLane(), operator<<(), TraCIServerAPI_Vehicle::processSet(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), MSAbstractLaneChangeModel::updateShadowLane(), and TraCIServerAPI_Vehicle::vtdMap().
const MSLane & MSStoppingPlace::getLane () const inherited
Returns the lane this stop is located at.
Returns
Reference to the lane the stop is located at
Definition at line 59 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myLane.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getBusStopID(), MSNet::getChargingStationID(), MSNet::getContainerStopID(), MSNet::getParkingAreaID(), MSTriggeredRerouter::notifyEnter(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSVehicle::replaceParkingArea(), and MSTriggeredRerouter::rerouteParkingZone().
double MSParkingArea::getLastFreePos (const SUMOVehicle & forVehicle) const
Returns the last free position on this stop.
Returns
The last free position of this bus stop
Definition at line 98 of file MSParkingArea.cpp.
References MSStoppingPlace::myLastFreePos.
Referenced by MSVehicle::processNextStop().
double MSParkingArea::getLength () const
Returns the lot rectangle length.
Returns
The length
Definition at line 197 of file MSParkingArea.cpp.
References myLength.
Referenced by NLTriggerBuilder::parseAndAddLotEntry().
const std::string & MSStoppingPlace::getMyName () const inherited
Definition at line 165 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myName.
Referenced by GUIBusStop::drawGL().
int MSParkingArea::getOccupancy () const
Returns the area occupancy.
Returns
The occupancy computed as number of vehicles in myEndPositions
Definition at line 215 of file MSParkingArea.cpp.
References MSStoppingPlace::myEndPositions.
Referenced by GUIParkingArea::getParameterWindow(), MSVehicle::processNextStop(), and MSTriggeredRerouter::rerouteParkingZone().
double MSParkingArea::getSpaceDim () const
Returns the space dimension.
Returns
The space dimension
Definition at line 126 of file MSParkingArea.cpp.
References MSStoppingPlace::myBegPos, myCapacity, and MSStoppingPlace::myEndPos.
Referenced by MSParkingArea().
double MSStoppingPlace::getStoppingPosition (const SUMOVehicle * veh) const inherited
For vehicles at the stop this gives the the actual stopping position of the vehicle. For all others the last free stopping position.
Definition at line 99 of file MSStoppingPlace.cpp.
References MSStoppingPlace::getLastFreePos(), and MSStoppingPlace::myEndPositions.
int MSStoppingPlace::getTransportableNumber () const inline inherited
Returns the number of transportables waiting on this stop.
Definition at line 154 of file MSStoppingPlace.h.
References MSStoppingPlace::addTransportable(), MSStoppingPlace::myWaitingTransportables, and MSStoppingPlace::removeTransportable().
Referenced by GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), and TraCIServerAPI_Simulation::processGet().
double MSParkingArea::getVehicleAngle (const SUMOVehicle & forVehicle)
Returns the angle of parked vehicle.
Returns
The angle of parked vehicle
Definition at line 114 of file MSParkingArea.cpp.
References mySpaceOccupancies, and PI.
Position MSParkingArea::getVehiclePosition (const SUMOVehicle & forVehicle)
Returns the position of parked vehicle.
Returns
The position of parked vehicle
Definition at line 103 of file MSParkingArea.cpp.
References Position::INVALID, and mySpaceOccupancies.
Position MSStoppingPlace::getWaitPosition () const inherited
Returns the next free waiting place for pedestrians / containers.
Returns
The next free waiting place for pedestrians / containers
Definition at line 93 of file MSStoppingPlace.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), MSStoppingPlace::myLane, MSStoppingPlace::myWaitingPos, and PositionVector::positionAtOffset().
Referenced by MSPerson::MSPersonStage_Driving::proceed().
double MSParkingArea::getWidth () const
Returns the lot rectangle width.
Returns
The width
Definition at line 191 of file MSParkingArea.cpp.
References myWidth.
Referenced by NLTriggerBuilder::parseAndAddLotEntry().
bool MSStoppingPlace::hasAccess (const MSEdge * edge) const inherited
checks whether this stop provides access to the given edge
Definition at line 151 of file MSStoppingPlace.cpp.
References MSLane::getEdge(), MSStoppingPlace::myAccessPos, and MSStoppingPlace::myLane.
Referenced by MSStoppingPlace::addAccess(), and MSRouteHandler::parseWalkPositions().
void MSParkingArea::leaveFrom (SUMOVehicle * what)
Called if a vehicle leaves this stop.
Removes the position of the vehicle from myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that leaves the bus stop
See also
computeLastFreePos
Definition at line 161 of file MSParkingArea.cpp.
References computeLastFreePos(), MSStoppingPlace::myEndPositions, and mySpaceOccupancies.
MSParkingArea& MSParkingArea::operator= (const MSParkingArea &) private
Invalidated assignment operator.
void MSStoppingPlace::removeTransportable (MSTransportable * p) inherited
Removes a transportable from this stop.
Definition at line 116 of file MSStoppingPlace.cpp.
References MSStoppingPlace::getEndLanePosition(), MSVehicleType::getLength(), MSTransportable::getVehicleType(), MSStoppingPlace::myWaitingPos, and MSStoppingPlace::myWaitingTransportables.
Referenced by MSStoppingPlace::getTransportableNumber(), and MSVehicle::processNextStop().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::Distribution_Parameterized(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
Field Documentation
std::multimap<MSLane*, double> MSStoppingPlace::myAccessPos protected inherited
lanes and positions connected to this stop
Definition at line 214 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addAccess(), and MSStoppingPlace::hasAccess().
double MSParkingArea::myAngle protected
The default angle of each parking space.
Definition at line 237 of file MSParkingArea.h.
Referenced by getAngle(), and MSParkingArea().
const double MSStoppingPlace::myBegPos protected inherited
The begin position this bus stop is located at.
Definition at line 193 of file MSStoppingPlace.h.
Referenced by computeLastFreePos(), MSStoppingPlace::getBeginLanePosition(), GUIChargingStation::getParameterWindow(), GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), GUIParkingArea::getParameterWindow(), getSpaceDim(), and MSParkingArea().
int MSParkingArea::myCapacity protected
Stop area capacity.
Definition at line 228 of file MSParkingArea.h.
Referenced by addLotEntry(), getCapacity(), getSpaceDim(), and MSParkingArea().
const double MSStoppingPlace::myEndPos protected inherited
The end position this bus stop is located at.
Definition at line 196 of file MSStoppingPlace.h.
Referenced by addLotEntry(), MSStoppingPlace::computeLastFreePos(), MSStoppingPlace::getEndLanePosition(), MSStoppingPlace::getLastFreePos(), GUIChargingStation::getParameterWindow(), GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), GUIParkingArea::getParameterWindow(), and getSpaceDim().
std::map<const SUMOVehicle*, std::pair<double, double> > MSStoppingPlace::myEndPositions protected inherited
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 187 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::computeLastFreePos(), enter(), MSStoppingPlace::enter(), getOccupancy(), MSStoppingPlace::getStoppingPosition(), leaveFrom(), and MSStoppingPlace::leaveFrom().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
const MSLane& MSStoppingPlace::myLane protected inherited
The lane this bus stop is located at.
Definition at line 190 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::getLane(), MSStoppingPlace::getWaitPosition(), and MSStoppingPlace::hasAccess().
int MSParkingArea::myLastFreeLot protected
Last free lot number (0 no free lot)
Definition at line 225 of file MSParkingArea.h.
Referenced by computeLastFreePos(), and enter().
double MSStoppingPlace::myLastFreePos protected inherited
The last free position at this stop (variable)
Definition at line 199 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::computeLastFreePos(), computeLastFreePos(), getLastFreePos(), and MSStoppingPlace::getLastFreePos().
double MSParkingArea::myLength protected
The default length of each parking space.
Definition at line 234 of file MSParkingArea.h.
Referenced by getLength(), and MSParkingArea().
std::vector<std::string> MSStoppingPlace::myLines protected inherited
The list of lines that are assigned to this stop.
Definition at line 184 of file MSStoppingPlace.h.
Referenced by GUIContainerStop::drawGL(), GUIBusStop::drawGL(), and GUIParkingArea::drawGL().
const std::string MSStoppingPlace::myName protected inherited
The name of the stopping place.
Definition at line 205 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::getMyName().
PositionVector MSParkingArea::myShape protected
The roadside shape of this parkingArea.
Definition at line 244 of file MSParkingArea.h.
Referenced by GUIParkingArea::drawGL(), GUIParkingArea::getCenteringBoundary(), GUIParkingArea::GUIParkingArea(), and MSParkingArea().
std::map<unsigned int, LotSpaceDefinition > MSParkingArea::mySpaceOccupancies protected
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 241 of file MSParkingArea.h.
Referenced by addLotEntry(), computeLastFreePos(), GUIParkingArea::drawGL(), enter(), getVehicleAngle(), getVehiclePosition(), leaveFrom(), and MSParkingArea().
double MSStoppingPlace::myWaitingPos protected inherited
The next free position for persons / containers.
Definition at line 202 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addTransportable(), MSStoppingPlace::getWaitPosition(), and MSStoppingPlace::removeTransportable().
std::vector<MSTransportable*> MSStoppingPlace::myWaitingTransportables protected inherited
Persons waiting at this stop.
Definition at line 211 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addTransportable(), GUIContainerStop::drawGL(), GUIParkingArea::drawGL(), MSStoppingPlace::getTransportableNumber(), and MSStoppingPlace::removeTransportable().
double MSParkingArea::myWidth protected
The default width of each parking space.
Definition at line 231 of file MSParkingArea.h.
Referenced by GUIParkingArea::drawGL(), getWidth(), GUIParkingArea::GUIParkingArea(), and MSParkingArea().
The documentation for this class was generated from the following files:
MSParkingArea.h
MSParkingArea.cpp