SUMO - Simulation of Urban MObility: GUIParkingArea Class Reference
GUIParkingArea Class Reference
A lane area vehicles can halt at (gui-version)
#include <GUIParkingArea.h>
Public Member Functions
virtual void addAccess (MSLane *lane, const double pos)
adds an access point to this stop
void addLotEntry (double x, double y, double z, double width, double length, double angle)
Add a lot entry to parking area.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void addTransportable (MSTransportable *p)
adds a transportable to this stop
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
void enter (SUMOVehicle *what, double beg, double end)
Called if a vehicle enters this stop.
double getAngle () const
Returns the lot rectangle angle.
double getBeginLanePosition () const
Returns the begin position of this stop.
int getCapacity () const
Returns the area capacity.
double getEndLanePosition () const
Returns the end position of this stop.
const std::string & getID () const
Returns the id.
const MSLane & getLane () const
Returns the lane this stop is located at.
double getLastFreePos (const SUMOVehicle &forVehicle) const
Returns the last free position on this stop.
double getLength () const
Returns the lot rectangle length.
const std::string & getMyName () const
int getOccupancy () const
Returns the area occupancy.
double getSpaceDim () const
Returns the space dimension.
double getStoppingPosition (const SUMOVehicle *veh) const
For vehicles at the stop this gives the the actual stopping position of the vehicle. For all others the last free stopping position.
int getTransportableNumber () const
Returns the number of transportables waiting on this stop.
double getVehicleAngle (const SUMOVehicle &forVehicle)
Returns the angle of parked vehicle.
Position getVehiclePosition (const SUMOVehicle &forVehicle)
Returns the position of parked vehicle.
Position getWaitPosition () const
Returns the next free waiting place for pedestrians / containers.
double getWidth () const
Returns the lot rectangle width.
GUIParkingArea (const std::string &id, const std::vector< std::string > &lines, MSLane &lane, double frompos, double topos, unsigned int capacity, double width, double length, double angle)
Constructor.
bool hasAccess (const MSEdge *edge) const
checks whether this stop provides access to the given edge
void leaveFrom (SUMOVehicle *what)
Called if a vehicle leaves this stop.
void removeTransportable (MSTransportable *p)
Removes a transportable from this stop.
void setID (const std::string &newID)
resets the id
~GUIParkingArea ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clearDictionary ()
Clears the dictionary (the objects will not be deleted)
static GUIGlObject_AbstractAdd * get (const std::string &name)
Returns a named object.
static std::vector< GUIGlID > getIDList ()
Returns the list of gl-ids of all additional objects.
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static const std::vector< GUIGlObject_AbstractAdd * > & getObjectList ()
Returns the list of all additional objects.
static void remove (GUIGlObject_AbstractAdd *o)
Removes an object.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void computeLastFreePos ()
Computes the last free position on this stop.
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
std::multimap< MSLane *, double > myAccessPos
lanes and positions connected to this stop
double myAngle
The default angle of each parking space.
const double myBegPos
The begin position this bus stop is located at.
int myCapacity
Stop area capacity.
const double myEndPos
The end position this bus stop is located at.
std::map< const SUMOVehicle *, std::pair< double, double > > myEndPositions
A map from objects (vehicles) to the areas they acquire after entering the stop.
std::string myID
The name of the object.
const MSLane & myLane
The lane this bus stop is located at.
int myLastFreeLot
Last free lot number (0 no free lot)
double myLastFreePos
The last free position at this stop (variable)
double myLength
The default length of each parking space.
std::vector< std::string > myLines
The list of lines that are assigned to this stop.
const std::string myName
The name of the stopping place.
PositionVector myShape
The roadside shape of this parkingArea.
std::map< unsigned int, LotSpaceDefinition > mySpaceOccupancies
A map from objects (vehicles) to the areas they acquire after entering the stop.
double myWaitingPos
The next free position for persons / containers.
std::vector< MSTransportable * > myWaitingTransportables
Persons waiting at this stop.
double myWidth
The default width of each parking space.
Static Protected Attributes
static std::vector< GUIGlObject_AbstractAdd * > myObjectList
The list of all addtional objects currently loaded.
static std::map< std::string, GUIGlObject_AbstractAdd * > myObjects
Map from names of loaded additional objects to the objects themselves.
Private Attributes
std::vector< double > myShapeLengths
The lengths of the shape parts.
std::vector< double > myShapeRotations
The rotations of the shape parts.
Position mySignPos
The position of the sign.
double mySignRot
The rotation of the sign.
Detailed Description
A lane area vehicles can halt at (gui-version)
This gui-version of a parking-area extends MSStoppingPlace by methods for displaying and interaction.
See also
MSStoppingPlace
GUIGlObject_AbstractAdd
GUIGlObject
Definition at line 69 of file GUIParkingArea.h.
Constructor & Destructor Documentation
GUIParkingArea::GUIParkingArea (const std::string & id, const std::vector< std::string > & lines, MSLane & lane, double frompos, double topos, unsigned int capacity, double width, double length, double angle)
Constructor.
Parameters
[in] idStorage The gl-id storage for giving this object an gl-id
[in] id The id of the parking area
[in] lines Names of the parking lines that halt on this parking area
[in] lane The lane the parking area is placed on
[in] begPos Begin position of the parking area on the lane
[in] endPos End position of the parking area on the lane
[in] capacity Capacity of the parking area (if > 0 lots are generated, otherwise expected addLotEntry())
[in] width Default width of the lot rectangle (if = 0 is computed from line.getWidth())
[in] length Default length of the lot rectangle (if = 0 is computed from endPos-begPos)
[in] angle Default angle of the lot rectangle relative to lane direction (if = 0 is computed ... TODO)
Definition at line 61 of file GUIParkingArea.cpp.
References Position::distanceTo(), PositionVector::getLineCenter(), MSLane::getWidth(), PositionVector::length(), PositionVector::move2side(), MSParkingArea::myShape, myShapeLengths, myShapeRotations, mySignPos, mySignRot, MSParkingArea::myWidth, PI, PositionVector::rotationDegreeAtOffset(), Position::x(), and Position::y().
GUIParkingArea::~GUIParkingArea ()
Destructor.
Definition at line 86 of file GUIParkingArea.cpp.
Member Function Documentation
virtual void MSStoppingPlace::addAccess (MSLane * lane, const double pos) inline virtual inherited
adds an access point to this stop
Reimplemented in GUIBusStop.
Definition at line 165 of file MSStoppingPlace.h.
References MSStoppingPlace::computeLastFreePos(), MSStoppingPlace::hasAccess(), and MSStoppingPlace::myAccessPos.
Referenced by GUIBusStop::addAccess(), and NLTriggerBuilder::addAccess().
void MSParkingArea::addLotEntry (double x, double y, double z, double width, double length, double angle) inherited
Add a lot entry to parking area.
Parameters
[in] x X position of the lot center
[in] y Y position of the lot center
[in] z Z position of the lot center
[in] width Width of the lot rectangle
[in] length Length of the lot rectangle
[in] angle Angle of the lot rectangle
Returns
Whether the lot entry could be added
Definition at line 132 of file MSParkingArea.cpp.
References MSParkingArea::computeLastFreePos(), MSParkingArea::myCapacity, MSStoppingPlace::myEndPos, and MSParkingArea::mySpaceOccupancies.
Referenced by NLTriggerBuilder::addLotEntry().
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 256 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
void MSStoppingPlace::addTransportable (MSTransportable * p) inherited
adds a transportable to this stop
Definition at line 109 of file MSStoppingPlace.cpp.
References MSVehicleType::getLength(), MSTransportable::getVehicleType(), MSStoppingPlace::myWaitingPos, and MSStoppingPlace::myWaitingTransportables.
Referenced by MSStoppingPlace::getTransportableNumber(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and MSContainer::MSContainerStage_Tranship::moveToNextEdge().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 185 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 194 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 175 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 235 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 204 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 247 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 217 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 226 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
void GUIGlObject_AbstractAdd::clearDictionary () static inherited
Clears the dictionary (the objects will not be deleted)
!! delete (*i).second;
Definition at line 62 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
Referenced by GUINet::~GUINet().
void MSParkingArea::computeLastFreePos () protected inherited
Computes the last free position on this stop.
The last free position is the one, the last vehicle ends at. It is stored in myLastFreePos. If no vehicle halts, the last free position gets the value of myEndPos.
Definition at line 176 of file MSParkingArea.cpp.
References MSStoppingPlace::myBegPos, MSParkingArea::myLastFreeLot, MSStoppingPlace::myLastFreePos, and MSParkingArea::mySpaceOccupancies.
Referenced by MSParkingArea::addLotEntry(), MSParkingArea::enter(), MSParkingArea::leaveFrom(), and MSParkingArea::MSParkingArea().
void GUIParkingArea::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 120 of file GUIParkingArea.cpp.
References GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GLHelper::drawBoxLines(), GLHelper::drawFilledCircle(), GUIContainer::drawGL(), GUIGlObject::drawName(), GLHelper::drawText(), getCenteringBoundary(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), GUIGlObject::getType(), MIN2(), MSStoppingPlace::myLines, MSParkingArea::myShape, myShapeLengths, myShapeRotations, mySignPos, mySignRot, MSParkingArea::mySpaceOccupancies, MSStoppingPlace::myWaitingTransportables, MSParkingArea::myWidth, pfDrawString(), pfSetPosition(), pfSetScale(), GUIVisualizationSettings::scale, GLHelper::setColor(), Position::x(), and Position::y().
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 154 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 284 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), GNEEdge::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
void MSParkingArea::enter (SUMOVehicle * what, double beg, double end) inherited
Called if a vehicle enters this stop.
Stores the position of the entering vehicle in myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that enters the bus stop
[in] beg The begin halting position of the vehicle
[in] what The end halting position of the vehicle
See also
computeLastFreePos
Definition at line 151 of file MSParkingArea.cpp.
References MSParkingArea::computeLastFreePos(), MSStoppingPlace::myEndPositions, MSParkingArea::myLastFreeLot, and MSParkingArea::mySpaceOccupancies.
Referenced by MSVehicle::processNextStop().
GUIGlObject_AbstractAdd * GUIGlObject_AbstractAdd::get (const std::string & name) static inherited
Returns a named object.
Definition at line 73 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjects.
double MSParkingArea::getAngle () const inherited
Returns the lot rectangle angle.
Returns
The angle
Definition at line 203 of file MSParkingArea.cpp.
References MSParkingArea::myAngle.
Referenced by NLTriggerBuilder::parseAndAddLotEntry().
double MSStoppingPlace::getBeginLanePosition () const inherited
Returns the begin position of this stop.
Returns
The position the stop begins at
Definition at line 65 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myBegPos.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getChargingStationID(), MSChargingStation::MSChargingStation(), MSRouteHandler::parseWalkPositions(), MSVehicle::processNextStop(), MSVehicle::replaceParkingArea(), MSTriggeredRerouter::rerouteParkingZone(), and MSChargingStation::vehicleIsInside().
int MSParkingArea::getCapacity () const inherited
Returns the area capacity.
Returns
The capacity
Definition at line 209 of file MSParkingArea.cpp.
References MSParkingArea::myCapacity.
Referenced by getParameterWindow(), MSVehicle::processNextStop(), and MSTriggeredRerouter::rerouteParkingZone().
Boundary GUIParkingArea::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 202 of file GUIParkingArea.cpp.
References PositionVector::getBoxBoundary(), Boundary::grow(), and MSParkingArea::myShape.
Referenced by drawGL().
double MSStoppingPlace::getEndLanePosition () const inherited
Returns the end position of this stop.
Returns
The position the stop ends at
Definition at line 71 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myEndPos.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getBusStopID(), MSNet::getChargingStationID(), MSNet::getContainerStopID(), MSNet::getParkingAreaID(), MSChargingStation::MSChargingStation(), MSRouteHandler::parseWalkPositions(), MSVehicle::processNextStop(), MSStoppingPlace::removeTransportable(), MSVehicle::replaceParkingArea(), and MSChargingStation::vehicleIsInside().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 121 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEInternalLane::drawGL(), GNEJunction::drawGL(), GNECrossing::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdRevertRestriction(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), MSNet::addParkingArea(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), TraCI_Vehicle::getBestLanes(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), TraCI_Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), TraCI_Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), TraCI_Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSNet::getParkingAreaID(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), TraCI_Vehicle::getRoadID(), TraCI_Vehicle::getRouteID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_SSM::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSDevice_SSM::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_SSM::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Person::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingZone(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), toString(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSDevice_SSM::updateEncounter(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
std::vector< GUIGlID > GUIGlObject_AbstractAdd::getIDList () static inherited
Returns the list of gl-ids of all additional objects.
Definition at line 96 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GUISUMOViewParent::onCmdLocate().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSPModel_Striping::PState::moveToNextLane(), operator<<(), TraCIServerAPI_Vehicle::processSet(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), MSAbstractLaneChangeModel::updateShadowLane(), and TraCIServerAPI_Vehicle::vtdMap().
const MSLane & MSStoppingPlace::getLane () const inherited
Returns the lane this stop is located at.
Returns
Reference to the lane the stop is located at
Definition at line 59 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myLane.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getBusStopID(), MSNet::getChargingStationID(), MSNet::getContainerStopID(), MSNet::getParkingAreaID(), MSTriggeredRerouter::notifyEnter(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSVehicle::replaceParkingArea(), and MSTriggeredRerouter::rerouteParkingZone().
double MSParkingArea::getLastFreePos (const SUMOVehicle & forVehicle) const inherited
Returns the last free position on this stop.
Returns
The last free position of this bus stop
Definition at line 98 of file MSParkingArea.cpp.
References MSStoppingPlace::myLastFreePos.
Referenced by MSVehicle::processNextStop().
double MSParkingArea::getLength () const inherited
Returns the lot rectangle length.
Returns
The length
Definition at line 197 of file MSParkingArea.cpp.
References MSParkingArea::myLength.
Referenced by NLTriggerBuilder::parseAndAddLotEntry().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 135 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNEJunction::getAttribute(), GNELane::getAttribute(), GNENetElement::getParentName(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSign::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNERerouter::getParentName(), GNEDetector::getParentName(), GNEDetectorE3::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEPoly::moveGeometry(), GNEEdge::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
const std::string & MSStoppingPlace::getMyName () const inherited
Definition at line 165 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myName.
Referenced by GUIBusStop::drawGL().
const std::vector< GUIGlObject_AbstractAdd * > & GUIGlObject_AbstractAdd::getObjectList () static inherited
Returns the list of all additional objects.
Definition at line 90 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GNEPOI::saveToFile().
int MSParkingArea::getOccupancy () const inherited
Returns the area occupancy.
Returns
The occupancy computed as number of vehicles in myEndPositions
Definition at line 215 of file MSParkingArea.cpp.
References MSStoppingPlace::myEndPositions.
Referenced by getParameterWindow(), MSVehicle::processNextStop(), and MSTriggeredRerouter::rerouteParkingZone().
GUIParameterTableWindow * GUIParkingArea::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Container stops have no parameter windows (yet).
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window (always 0 in this case)
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 104 of file GUIParkingArea.cpp.
References GUIParameterTableWindow::closeBuilding(), MSParkingArea::getCapacity(), MSParkingArea::getOccupancy(), GUIParameterTableWindow::mkItem(), MSStoppingPlace::myBegPos, and MSStoppingPlace::myEndPos.
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEDetectorE3, GNEDetector, GNERerouter, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSign, GNEVaporizer, GUILane, GNELane, and GNENetElement.
Definition at line 115 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
GUIGLObjectPopupMenu * GUIParkingArea::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 90 of file GUIParkingArea.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
double MSParkingArea::getSpaceDim () const inherited
Returns the space dimension.
Returns
The space dimension
Definition at line 126 of file MSParkingArea.cpp.
References MSStoppingPlace::myBegPos, MSParkingArea::myCapacity, and MSStoppingPlace::myEndPos.
Referenced by MSParkingArea::MSParkingArea().
double MSStoppingPlace::getStoppingPosition (const SUMOVehicle * veh) const inherited
For vehicles at the stop this gives the the actual stopping position of the vehicle. For all others the last free stopping position.
Definition at line 99 of file MSStoppingPlace.cpp.
References MSStoppingPlace::getLastFreePos(), and MSStoppingPlace::myEndPositions.
int MSStoppingPlace::getTransportableNumber () const inline inherited
Returns the number of transportables waiting on this stop.
Definition at line 154 of file MSStoppingPlace.h.
References MSStoppingPlace::addTransportable(), MSStoppingPlace::myWaitingTransportables, and MSStoppingPlace::removeTransportable().
Referenced by GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), and TraCIServerAPI_Simulation::processGet().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 148 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEDetector::drawDetectorIcon(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNECrossing::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEAdditional::drawParentAndChildrenConnections(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, and GUIPerson.
Definition at line 127 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
double MSParkingArea::getVehicleAngle (const SUMOVehicle & forVehicle) inherited
Returns the angle of parked vehicle.
Returns
The angle of parked vehicle
Definition at line 114 of file MSParkingArea.cpp.
References MSParkingArea::mySpaceOccupancies, and PI.
Position MSParkingArea::getVehiclePosition (const SUMOVehicle & forVehicle) inherited
Returns the position of parked vehicle.
Returns
The position of parked vehicle
Definition at line 103 of file MSParkingArea.cpp.
References Position::INVALID, and MSParkingArea::mySpaceOccupancies.
Position MSStoppingPlace::getWaitPosition () const inherited
Returns the next free waiting place for pedestrians / containers.
Returns
The next free waiting place for pedestrians / containers
Definition at line 93 of file MSStoppingPlace.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), MSStoppingPlace::myLane, MSStoppingPlace::myWaitingPos, and PositionVector::positionAtOffset().
Referenced by MSPerson::MSPersonStage_Driving::proceed().
double MSParkingArea::getWidth () const inherited
Returns the lot rectangle width.
Returns
The width
Definition at line 191 of file MSParkingArea.cpp.
References MSParkingArea::myWidth.
Referenced by NLTriggerBuilder::parseAndAddLotEntry().
bool MSStoppingPlace::hasAccess (const MSEdge * edge) const inherited
checks whether this stop provides access to the given edge
Definition at line 151 of file MSStoppingPlace.cpp.
References MSLane::getEdge(), MSStoppingPlace::myAccessPos, and MSStoppingPlace::myLane.
Referenced by MSStoppingPlace::addAccess(), and MSRouteHandler::parseWalkPositions().
void MSParkingArea::leaveFrom (SUMOVehicle * what) inherited
Called if a vehicle leaves this stop.
Removes the position of the vehicle from myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that leaves the bus stop
See also
computeLastFreePos
Definition at line 161 of file MSParkingArea.cpp.
References MSParkingArea::computeLastFreePos(), MSStoppingPlace::myEndPositions, and MSParkingArea::mySpaceOccupancies.
void GUIGlObject_AbstractAdd::remove (GUIGlObject_AbstractAdd * o) static inherited
Removes an object.
Definition at line 83 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject::getFullName(), GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 262 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void MSStoppingPlace::removeTransportable (MSTransportable * p) inherited
Removes a transportable from this stop.
Definition at line 116 of file MSStoppingPlace.cpp.
References MSStoppingPlace::getEndLanePosition(), MSVehicleType::getLength(), MSTransportable::getVehicleType(), MSStoppingPlace::myWaitingPos, and MSStoppingPlace::myWaitingTransportables.
Referenced by MSStoppingPlace::getTransportableNumber(), and MSVehicle::processNextStop().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::Distribution_Parameterized(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 141 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 271 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
std::multimap<MSLane*, double> MSStoppingPlace::myAccessPos protected inherited
lanes and positions connected to this stop
Definition at line 214 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addAccess(), and MSStoppingPlace::hasAccess().
double MSParkingArea::myAngle protected inherited
The default angle of each parking space.
Definition at line 237 of file MSParkingArea.h.
Referenced by MSParkingArea::getAngle(), and MSParkingArea::MSParkingArea().
const double MSStoppingPlace::myBegPos protected inherited
The begin position this bus stop is located at.
Definition at line 193 of file MSStoppingPlace.h.
Referenced by MSParkingArea::computeLastFreePos(), MSStoppingPlace::getBeginLanePosition(), GUIChargingStation::getParameterWindow(), GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), getParameterWindow(), MSParkingArea::getSpaceDim(), and MSParkingArea::MSParkingArea().
int MSParkingArea::myCapacity protected inherited
Stop area capacity.
Definition at line 228 of file MSParkingArea.h.
Referenced by MSParkingArea::addLotEntry(), MSParkingArea::getCapacity(), MSParkingArea::getSpaceDim(), and MSParkingArea::MSParkingArea().
const double MSStoppingPlace::myEndPos protected inherited
The end position this bus stop is located at.
Definition at line 196 of file MSStoppingPlace.h.
Referenced by MSParkingArea::addLotEntry(), MSStoppingPlace::computeLastFreePos(), MSStoppingPlace::getEndLanePosition(), MSStoppingPlace::getLastFreePos(), GUIChargingStation::getParameterWindow(), GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), getParameterWindow(), and MSParkingArea::getSpaceDim().
std::map<const SUMOVehicle*, std::pair<double, double> > MSStoppingPlace::myEndPositions protected inherited
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 187 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::computeLastFreePos(), MSParkingArea::enter(), MSStoppingPlace::enter(), MSParkingArea::getOccupancy(), MSStoppingPlace::getStoppingPosition(), MSParkingArea::leaveFrom(), and MSStoppingPlace::leaveFrom().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
const MSLane& MSStoppingPlace::myLane protected inherited
The lane this bus stop is located at.
Definition at line 190 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::getLane(), MSStoppingPlace::getWaitPosition(), and MSStoppingPlace::hasAccess().
int MSParkingArea::myLastFreeLot protected inherited
Last free lot number (0 no free lot)
Definition at line 225 of file MSParkingArea.h.
Referenced by MSParkingArea::computeLastFreePos(), and MSParkingArea::enter().
double MSStoppingPlace::myLastFreePos protected inherited
The last free position at this stop (variable)
Definition at line 199 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::computeLastFreePos(), MSParkingArea::computeLastFreePos(), MSParkingArea::getLastFreePos(), and MSStoppingPlace::getLastFreePos().
double MSParkingArea::myLength protected inherited
The default length of each parking space.
Definition at line 234 of file MSParkingArea.h.
Referenced by MSParkingArea::getLength(), and MSParkingArea::MSParkingArea().
std::vector<std::string> MSStoppingPlace::myLines protected inherited
The list of lines that are assigned to this stop.
Definition at line 184 of file MSStoppingPlace.h.
Referenced by GUIContainerStop::drawGL(), GUIBusStop::drawGL(), and drawGL().
const std::string MSStoppingPlace::myName protected inherited
The name of the stopping place.
Definition at line 205 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::getMyName().
std::vector< GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjectList static protected inherited
The list of all addtional objects currently loaded.
Definition at line 78 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::getIDList(), GUIGlObject_AbstractAdd::getObjectList(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
std::map< std::string, GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjects static protected inherited
Map from names of loaded additional objects to the objects themselves.
Definition at line 75 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::get(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
PositionVector MSParkingArea::myShape protected inherited
The roadside shape of this parkingArea.
Definition at line 244 of file MSParkingArea.h.
Referenced by drawGL(), getCenteringBoundary(), GUIParkingArea(), and MSParkingArea::MSParkingArea().
std::vector<double> GUIParkingArea::myShapeLengths private
The lengths of the shape parts.
Definition at line 143 of file GUIParkingArea.h.
Referenced by drawGL(), and GUIParkingArea().
std::vector<double> GUIParkingArea::myShapeRotations private
The rotations of the shape parts.
Definition at line 140 of file GUIParkingArea.h.
Referenced by drawGL(), and GUIParkingArea().
Position GUIParkingArea::mySignPos private
The position of the sign.
Definition at line 146 of file GUIParkingArea.h.
Referenced by drawGL(), and GUIParkingArea().
double GUIParkingArea::mySignRot private
The rotation of the sign.
Definition at line 149 of file GUIParkingArea.h.
Referenced by drawGL(), and GUIParkingArea().
std::map<unsigned int, LotSpaceDefinition > MSParkingArea::mySpaceOccupancies protected inherited
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 241 of file MSParkingArea.h.
Referenced by MSParkingArea::addLotEntry(), MSParkingArea::computeLastFreePos(), drawGL(), MSParkingArea::enter(), MSParkingArea::getVehicleAngle(), MSParkingArea::getVehiclePosition(), MSParkingArea::leaveFrom(), and MSParkingArea::MSParkingArea().
double MSStoppingPlace::myWaitingPos protected inherited
The next free position for persons / containers.
Definition at line 202 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addTransportable(), MSStoppingPlace::getWaitPosition(), and MSStoppingPlace::removeTransportable().
std::vector<MSTransportable*> MSStoppingPlace::myWaitingTransportables protected inherited
Persons waiting at this stop.
Definition at line 211 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addTransportable(), GUIContainerStop::drawGL(), drawGL(), MSStoppingPlace::getTransportableNumber(), and MSStoppingPlace::removeTransportable().
double MSParkingArea::myWidth protected inherited
The default width of each parking space.
Definition at line 231 of file MSParkingArea.h.
Referenced by drawGL(), MSParkingArea::getWidth(), GUIParkingArea(), and MSParkingArea::MSParkingArea().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIParkingArea.h
GUIParkingArea.cpp