SUMO - Simulation of Urban MObility: MSLink Class Reference
MSLink Class Reference
#include <MSLink.h>
Data Structures
struct ApproachingVehicleInformation
A structure holding the information about vehicles approaching a link.
struct LinkLeader
Public Types
typedef std::vector< LinkLeader > LinkLeaders
Public Member Functions
void addBlockedLink (MSLink *link)
bool blockedAtTime (SUMOTime arrivalTime, SUMOTime leaveTime, double arrivalSpeed, double leaveSpeed, bool sameTargetLane, double impatience, double decel, SUMOTime waitingTime, std::vector< const SUMOVehicle * > *collectFoes=0) const
Returns the information whether this link is blocked Valid after the vehicles have set their requests.
bool fromInternalLane () const
return whether the fromLane of this link is an internal lane
ApproachingVehicleInformation getApproaching (const SUMOVehicle *veh) const
const std::map< const SUMOVehicle *, ApproachingVehicleInformation > & getApproaching () const
return all approaching vehicles
LinkDirection getDirection () const
Returns the direction the vehicle passing this link take.
const std::vector< const MSLane * > & getFoeLanes ()
const std::vector< MSLink * > & getFoeLinks ()
double getFoeVisibilityDistance () const
Returns the distance on the approaching lane from which an approaching vehicle is able to see all relevant foes and may accelerate if the link is minor and no foe is approaching.
double getGreenFraction () const
Returns the average proportion of green time to cycle time.
int getIndex () const
Returns the respond index (for visualization)
const MSLane * getInternalLaneBefore () const
return myInternalLaneBefore (always 0 when compiled without internal lanes)
double getInternalLengthsAfter () const
Returns the cumulative length of all internal lanes after this link.
MSJunction * getJunction () const
MSLane * getLane () const
Returns the connected lane.
const MSLane * getLaneBefore () const
return the internalLaneBefore if it exists and the laneBefore otherwise
SUMOTime getLastStateChange () const
LinkLeaders getLeaderInfo (const MSVehicle *ego, double dist, std::vector< const MSPerson * > *collectBlockers=0) const
Returns all potential link leaders (vehicles on foeLanes) Valid during the planMove() phase.
SUMOTime getLeaveTime (const SUMOTime arrivalTime, const double arrivalSpeed, const double leaveSpeed, const double vehicleLength) const
return the expected time at which the given vehicle will clear the link
double getLength () const
Returns the length of this link.
double getLengthBeforeCrossing (const MSLink *foeEntryLink) const
Returns the complete internal lengths from the link until the crossing point with the given foe link's lane The crossing point is the intersection of the lane's central reference lines.
SUMOTime getMesoTLSPenalty () const
Returns the time penalty for passing a tls-controlled link (meso)
MSLink * getParallelLink (int direction) const
return the link that is parallel to this lane or 0
LinkState getState () const
Returns the current state of the link.
int getTLIndex () const
Returns the TLS index.
const MSTrafficLightLogic * getTLLogic () const
Returns the TLS index.
MSLane * getViaLane () const
Returns the following inner lane.
MSLane * getViaLaneOrLane () const
return the via lane if it exists and the lane otherwise
double getZipperSpeed (const MSVehicle *ego, const double dist, double vSafe, SUMOTime arrivalTime, std::vector< const SUMOVehicle * > *collectFoes) const
return the speed at which ego vehicle must approach the zipper link
bool hasApproachingFoe (SUMOTime arrivalTime, SUMOTime leaveTime, double speed, double decel) const
Returns the information whether a vehicle is approaching on one of the link's foe streams.
bool hasFoes () const
Returns whether this link belongs to a junction where more than one edge is incoming.
bool havePriority () const
Returns whether this link is a major link.
bool haveRed () const
Returns whether this link is blocked by a red (or redyellow) traffic light.
void initParallelLinks ()
initialize parallel links (to be called after all links are loaded)
bool isBlockingAnyone () const
bool isCont () const
bool isExitLink () const
return whether the fromLane of this link is an internal lane and toLane is a normal lane
bool isInternalJunctionLink () const
return whether the fromLane and the toLane of this link are internal lanes
bool isLeader (const MSVehicle *ego, const MSVehicle *foe) const
bool isTLSControlled () const
bool keepClear () const
whether the junction after this link must be kept clear
bool lastWasContMajor () const
whether this is a link past an internal junction which currently has priority
MSLink (MSLane *predLane, MSLane *succLane, MSLane *via, LinkDirection dir, LinkState state, double length, double foeVisibilityDistance, bool keepClear, MSTrafficLightLogic *logic, int tlLinkIdx)
Constructor for simulation which uses internal lanes.
bool opened (SUMOTime arrivalTime, double arrivalSpeed, double leaveSpeed, double vehicleLength, double impatience, double decel, SUMOTime waitingTime, double posLat=0, std::vector< const SUMOVehicle * > *collectFoes=0) const
Returns the information whether the link may be passed.
void passedJunction (const MSVehicle *vehicle)
erase vehicle from myLinkLeaders of this links junction
void removeApproaching (const SUMOVehicle *veh)
removes the vehicle from myApproachingVehicles
void setApproaching (const SUMOVehicle *approaching, const SUMOTime arrivalTime, const double arrivalSpeed, const double leaveSpeed, const bool setRequest, const SUMOTime arrivalTimeBraking, const double arrivalSpeedBraking, const SUMOTime waitingTime, double dist)
Sets the information about an approaching vehicle.
void setGreenFraction (const double fraction)
Sets the green fraction for passing a tls-controlled link (meso)
void setMesoTLSPenalty (const SUMOTime penalty)
Sets the time penalty for passing a tls-controlled link (meso)
void setRequestInformation (int index, bool hasFoes, bool isCont, const std::vector< MSLink * > &foeLinks, const std::vector< MSLane * > &foeLanes, MSLane *internalLaneBefore=0)
Sets the request information.
void setTLState (LinkState state, SUMOTime t)
Sets the current tl-state.
bool willHaveBlockedFoe () const
void writeApproaching (OutputDevice &od, const std::string fromLaneID) const
write information about all approaching vehicles to the given output device
~MSLink ()
Destructor.
Static Public Attributes
static const double ZIPPER_ADAPT_DIST
Private Member Functions
bool blockedByFoe (const SUMOVehicle *veh, const ApproachingVehicleInformation &avi, SUMOTime arrivalTime, SUMOTime leaveTime, double arrivalSpeed, double leaveSpeed, bool sameTargetLane, double impatience, double decel, SUMOTime waitingTime) const
MSLink * computeParallelLink (int direction)
MSLink (const MSLink &s)
invalidated copy constructor
MSLink & operator= (const MSLink &s)
invalidated assignment operator
Static Private Member Functions
static bool couldBrakeForLeader (double followDist, double leaderDist, const MSVehicle *follow, const MSVehicle *leader)
whether fllower could stay behind leader (possibly by braking)
static bool maybeOccupied (MSLane *lane)
returns whether the given lane may still be occupied by a vehicle currently on it
static bool unsafeMergeSpeeds (double leaderSpeed, double followerSpeed, double leaderDecel, double followerDecel)
return whether the given vehicles may NOT merge safely
Private Attributes
bool myAmCont
std::map< const SUMOVehicle *, ApproachingVehicleInformation > myApproachingVehicles
std::set< MSLink * > myBlockedFoeLinks
LinkDirection myDirection
An abstract (hopefully human readable) definition of the link's direction.
std::vector< const MSLane * > myFoeLanes
std::vector< MSLink * > myFoeLinks
double myFoeVisibilityDistance
distance from which an approaching vehicle is able to see all relevant foes and may accelerate if the link is minor and no foe is approaching. Defaults to 4.5m.
double myGreenFraction
green fraction at tls for mesoscopic simulation
bool myHasFoes
Whether any foe links exist.
int myIndex
The position within this respond.
MSLane *const myInternalLane
The following junction-internal lane if used.
const MSLane * myInternalLaneBefore
MSJunction * myJunction
the junction to which this link belongs
bool myKeepClear
MSLane * myLane
The lane behind the junction approached by this link.
MSLane * myLaneBefore
The lane approaching this link.
SUMOTime myLastStateChange
The time of the last state change.
double myLength
The length of the link.
std::vector< std::pair< double, double > > myLengthsBehindCrossing
const MSTrafficLightLogic * myLogic
the controlling logic or 0
SUMOTime myMesoTLSPenalty
penalty time at tls for mesoscopic simulation
MSLink * myParallelLeft
MSLink * myParallelRight
LinkState myState
The state of the link.
std::vector< MSLink * > mySublaneFoeLinks
const int myTLIndex
the traffic light index
Static Private Attributes
static const SUMOTime myLookaheadTime = TIME2STEPS(1)
static const SUMOTime myLookaheadTimeZipper = TIME2STEPS(4)
Detailed Description
Definition at line 77 of file MSLink.h.
Member Typedef Documentation
typedef std::vector<LinkLeader> MSLink::LinkLeaders
Definition at line 92 of file MSLink.h.
Constructor & Destructor Documentation
MSLink::MSLink (MSLane * predLane, MSLane * succLane, MSLane * via, LinkDirection dir, LinkState state, double length, double foeVisibilityDistance, bool keepClear, MSTrafficLightLogic * logic, int tlLinkIdx)
Constructor for simulation which uses internal lanes.
Parameters
[in] succLane The lane approached by this link
[in] via The lane to use within the junction
[in] dir The direction of this link
[in] state The state of this link
[in] length The length of this link
Definition at line 67 of file MSLink.cpp.
MSLink::~MSLink ()
Destructor.
Definition at line 91 of file MSLink.cpp.
MSLink::MSLink (const MSLink & s) private
invalidated copy constructor
Member Function Documentation
void MSLink::addBlockedLink (MSLink * link)
Definition at line 256 of file MSLink.cpp.
References myBlockedFoeLinks.
bool MSLink::blockedAtTime (SUMOTime arrivalTime, SUMOTime leaveTime, double arrivalSpeed, double leaveSpeed, bool sameTargetLane, double impatience, double decel, SUMOTime waitingTime, std::vector< const SUMOVehicle * > * collectFoes = 0) const
Returns the information whether this link is blocked Valid after the vehicles have set their requests.
Parameters
[in] arrivalTime The arrivalTime of the vehicle who checks for an approaching foe
[in] leaveTime The leaveTime of the vehicle who checks for an approaching foe
[in] arrivalSpeed The speed with which the checking vehicle plans to arrive at the link
[in] leaveSpeed The speed with which the checking vehicle plans to leave the link
[in] sameTargetLane Whether the link that calls this method has the same target lane as this link
[in] impatience The impatience of the checking vehicle
[in] decel The maximum deceleration of the checking vehicle
[in] waitingTime The waiting time of the checking vehicle
[in] collectFoes If a vector is passed the return value is always False, instead all blocking foes are collected and inserted into this vector
Returns
Whether this link is blocked
Note
Since this needs to be called without a SUMOVehicle (TraCI), we cannot simply pass the checking vehicle itself
Definition at line 366 of file MSLink.cpp.
References blockedByFoe(), and myApproachingVehicles.
Referenced by getApproaching().
bool MSLink::blockedByFoe (const SUMOVehicle * veh, const ApproachingVehicleInformation & avi, SUMOTime arrivalTime, SUMOTime leaveTime, double arrivalSpeed, double leaveSpeed, bool sameTargetLane, double impatience, double decel, SUMOTime waitingTime) const private
Definition at line 384 of file MSLink.cpp.
References MSLink::ApproachingVehicleInformation::arrivalSpeedBraking, MSLink::ApproachingVehicleInformation::arrivalTime, MSLink::ApproachingVehicleInformation::arrivalTimeBraking, MSVehicleType::getCarFollowModel(), MSCFModel::getMaxDecel(), SUMOVehicle::getVehicleType(), MSLink::ApproachingVehicleInformation::leaveSpeed, MSLink::ApproachingVehicleInformation::leavingTime, LINKSTATE_ALLWAY_STOP, LINKSTATE_ZIPPER, myLookaheadTime, myLookaheadTimeZipper, myState, unsafeMergeSpeeds(), MSLink::ApproachingVehicleInformation::waitingTime, and MSLink::ApproachingVehicleInformation::willPass.
Referenced by blockedAtTime(), opened(), and unsafeMergeSpeeds().
MSLink * MSLink::computeParallelLink (int direction) private
Definition at line 745 of file MSLink.cpp.
References MSLinkContHelper::getConnectingLink(), getLaneBefore(), MSLane::getParallelLane(), and getViaLaneOrLane().
Referenced by initParallelLinks(), and unsafeMergeSpeeds().
bool MSLink::couldBrakeForLeader (double followDist, double leaderDist, const MSVehicle * follow, const MSVehicle * leader) static private
whether fllower could stay behind leader (possibly by braking)
Definition at line 853 of file MSLink.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), and MSVehicle::getSpeed().
Referenced by getZipperSpeed(), and unsafeMergeSpeeds().
bool MSLink::fromInternalLane () const
return whether the fromLane of this link is an internal lane
Definition at line 618 of file MSLink.cpp.
References isExitLink(), and isInternalJunctionLink().
Referenced by getLeaderInfo(), and keepClear().
MSLink::ApproachingVehicleInformation MSLink::getApproaching (const SUMOVehicle * veh) const
Definition at line 280 of file MSLink.cpp.
References myApproachingVehicles.
Referenced by getZipperSpeed().
const std::map<const SUMOVehicle*, ApproachingVehicleInformation>& MSLink::getApproaching () const inline
return all approaching vehicles
Definition at line 193 of file MSLink.h.
References blockedAtTime(), myApproachingVehicles, and opened().
LinkDirection MSLink::getDirection () const
Returns the direction the vehicle passing this link take.
Returns
The direction of this link
Definition at line 455 of file MSLink.cpp.
References myDirection.
Referenced by MSLaneChanger::changeOpposite(), MSVehicle::executeMove(), getLastStateChange(), and TraCI_Lane::getLinks().
const std::vector<const MSLane*>& MSLink::getFoeLanes () inline
Definition at line 450 of file MSLink.h.
References myFoeLanes.
const std::vector<MSLink*>& MSLink::getFoeLinks () inline
Definition at line 454 of file MSLink.h.
References initParallelLinks(), and myFoeLinks.
Referenced by MSLane::incoming_lane_priority_sorter::operator()(), and MSDevice_SSM::updateEncounter().
double MSLink::getFoeVisibilityDistance () const inline
Returns the distance on the approaching lane from which an approaching vehicle is able to see all relevant foes and may accelerate if the link is minor and no foe is approaching.
Returns
The foe-visibility-distance
Definition at line 340 of file MSLink.h.
References myFoeVisibilityDistance.
double MSLink::getGreenFraction () const inline
Returns the average proportion of green time to cycle time.
Definition at line 436 of file MSLink.h.
References myGreenFraction.
Referenced by MESegment::getTLSCapacity().
int MSLink::getIndex () const inline
Returns the respond index (for visualization)
Returns
The respond index for this link
Definition at line 293 of file MSLink.h.
References myIndex.
Referenced by GUILane::drawLinkNo().
const MSLane * MSLink::getInternalLaneBefore () const
return myInternalLaneBefore (always 0 when compiled without internal lanes)
Definition at line 774 of file MSLink.cpp.
References myInternalLaneBefore.
Referenced by getLengthBeforeCrossing(), isExitLink(), isInternalJunctionLink(), and keepClear().
double MSLink::getInternalLengthsAfter () const
Returns the cumulative length of all internal lanes after this link.
Returns
sum of the lengths of all internal lanes following this link
Definition at line 526 of file MSLink.cpp.
References MSLane::getLength(), MSLane::getLinkCont(), MSLane::isInternal(), and myInternalLane.
Referenced by MSLCM_LC2013::distanceAlongNextRoundabout(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSLCM_LC2013::getRoundaboutAheadInfo(), keepClear(), and MSDevice_SSM::updateEncounter().
MSJunction* MSLink::getJunction () const inline
Definition at line 247 of file MSLink.h.
References myJunction.
MSLane * MSLink::getLane () const
Returns the connected lane.
Returns
The lane approached by this link
Definition at line 470 of file MSLink.cpp.
References myLane.
Referenced by MSVehicle::checkRewindLinkLanes(), Command_SaveTLSSwitches::execute(), MSLinkContHelper::getConnectingLink(), MSLinkContHelper::getInternalFollowingEdge(), MSEdge::getInternalFollowingEdge(), MSLinkContHelper::getInternalFollowingLane(), getLastStateChange(), TraCI_Lane::getLinks(), MSPModel_Striping::getNextWalkingArea(), MSRailSignal::init(), MESegment::limitedControlOverride(), opened(), MSLane::outgoing_lane_priority_sorter::operator()(), TraCIServerAPI_TLS::processGet(), MSDevice_SSM::updateEncounter(), and writeApproaching().
const MSLane * MSLink::getLaneBefore () const
return the internalLaneBefore if it exists and the laneBefore otherwise
Definition at line 721 of file MSLink.cpp.
References myInternalLaneBefore, and myLaneBefore.
Referenced by computeParallelLink(), getLengthBeforeCrossing(), MSRailSignal::init(), keepClear(), and MSDevice_SSM::updateEncounter().
SUMOTime MSLink::getLastStateChange () const inline
Definition at line 262 of file MSLink.h.
References getDirection(), getLane(), myLastStateChange, and setTLState().
MSLink::LinkLeaders MSLink::getLeaderInfo (const MSVehicle * ego, double dist, std::vector< const MSPerson * > * collectBlockers = 0) const
Returns all potential link leaders (vehicles on foeLanes) Valid during the planMove() phase.
Parameters
[in] ego The ego vehicle that is looking for leaders
[in] dist The distance of the vehicle who is asking about the leader to this link
[out] blocking Return blocking pedestrians if a vector is given
Returns
The all vehicles on foeLanes and their (virtual) distances to the asking vehicle
Definition at line 623 of file MSLink.cpp.
References MSLane::anyVehiclesBegin(), MSLane::anyVehiclesEnd(), MSEdge::EDGEFUNCTION_INTERNAL, fromInternalLane(), gDebugFlag1, MSVehicle::getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSLane::getLength(), MSLane::getLinkCont(), MSLane::getLogicalPredecessorLane(), MSVehicleType::getMinGap(), MSPModel::getModel(), MSBaseVehicle::getVehicleType(), MSVehicle::getWaitingTime(), MSLane::getWidth(), MSGlobals::gIgnoreJunctionBlocker, MSVehicle::isFrontOnLane(), MSAbstractLaneChangeModel::isOpposite(), myFoeLanes, myInternalLaneBefore, myLane, myLengthsBehindCrossing, and MSPModel::SAFETY_GAP.
Referenced by MSVehicle::checkLinkLeader(), and keepClear().
SUMOTime MSLink::getLeaveTime (const SUMOTime arrivalTime, const double arrivalSpeed, const double leaveSpeed, const double vehicleLength) const
return the expected time at which the given vehicle will clear the link
Definition at line 291 of file MSLink.cpp.
References getLength(), MAX2(), NUMERICAL_EPS, and TIME2STEPS.
Referenced by keepClear(), opened(), and setApproaching().
double MSLink::getLength () const inline
Returns the length of this link.
Returns
The length of this link
Definition at line 329 of file MSLink.h.
References myLength.
Referenced by MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), getLeaveTime(), TraCI_Lane::getLinks(), MSE2Collector::initAuxiliaries(), MSE2Collector::recalculateDetectorLength(), and MSE2Collector::selectLanes().
double MSLink::getLengthBeforeCrossing (const MSLink * foeEntryLink) const
Returns the complete internal lengths from the link until the crossing point with the given foe link's lane The crossing point is the intersection of the lane's central reference lines.
Definition at line 539 of file MSLink.cpp.
References Named::getID(), getInternalLaneBefore(), getLaneBefore(), MSLane::getLength(), MSLane::getLinkCont(), getViaLane(), INVALID_DOUBLE, myFoeLanes, myLengthsBehindCrossing, and toString().
Referenced by keepClear(), and MSDevice_SSM::updateEncounter().
SUMOTime MSLink::getMesoTLSPenalty () const inline
Returns the time penalty for passing a tls-controlled link (meso)
Definition at line 431 of file MSLink.h.
References myMesoTLSPenalty.
Referenced by MESegment::getLinkPenalty(), MESegment::getMaxPenaltySeconds(), and MSEdge::recalcCache().
MSLink * MSLink::getParallelLink (int direction) const
return the link that is parallel to this lane or 0
Definition at line 732 of file MSLink.cpp.
References myParallelLeft, and myParallelRight.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), keepClear(), MSVehicle::planMoveInternal(), and GUIVehicle::selectBlockingFoes().
LinkState MSLink::getState () const inline
Returns the current state of the link.
Returns
The current state of this link
Definition at line 256 of file MSLink.h.
References myState.
Referenced by MSEdge::allowsLaneChanging(), MSLaneChanger::changeOpposite(), GUILane::drawLinkRule(), Command_SaveTLCoupledLaneDet::execute(), MSVehicle::executeMove(), MSLane::getIncomingLinkState(), TraCI_Lane::getLinks(), and MELoop::setApproaching().
int MSLink::getTLIndex () const inline
Returns the TLS index.
Definition at line 298 of file MSLink.h.
References myTLIndex.
const MSTrafficLightLogic* MSLink::getTLLogic () const inline
Returns the TLS index.
Definition at line 303 of file MSLink.h.
References myLogic.
MSLane * MSLink::getViaLane () const
Returns the following inner lane.
Returns
The inner lane to use to cross the junction
Definition at line 600 of file MSLink.cpp.
References myInternalLane.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSLinkContHelper::getInternalFollowingEdge(), MSEdge::getInternalFollowingEdge(), MSLinkContHelper::getInternalFollowingLane(), getLengthBeforeCrossing(), TraCI_Lane::getLinks(), MSE2Collector::initAuxiliaries(), keepClear(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), TraCIServerAPI_TLS::processGet(), MSDevice_SSM::updateEncounter(), and writeApproaching().
MSLane * MSLink::getViaLaneOrLane () const
return the via lane if it exists and the lane otherwise
Definition at line 712 of file MSLink.cpp.
References myInternalLane, and myLane.
Referenced by computeParallelLink(), GUIVehicle::drawAction_drawLinkItems(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSVehicle::executeMove(), MSLinkContHelper::getConnectingLink(), MSPModel_Striping::getNextLane(), keepClear(), GUIVehicle::selectBlockingFoes(), and setRequestInformation().
double MSLink::getZipperSpeed (const MSVehicle * ego, const double dist, double vSafe, SUMOTime arrivalTime, std::vector< const SUMOVehicle * > * collectFoes) const
return the speed at which ego vehicle must approach the zipper link
Definition at line 780 of file MSLink.cpp.
References MSLink::ApproachingVehicleInformation::arrivalTime, couldBrakeForLeader(), MSLink::ApproachingVehicleInformation::dist, MSCFModel::followSpeed(), getApproaching(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), Named::getID(), MSLane::getIndex(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicleType::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MAX2(), MIN2(), myFoeLinks, myJunction, STEPS2TIME, TS, ZIPPER_ADAPT_DIST, and ZIPPER_ADAPT_TIME.
Referenced by keepClear().
bool MSLink::hasApproachingFoe (SUMOTime arrivalTime, SUMOTime leaveTime, double speed, double decel) const
Returns the information whether a vehicle is approaching on one of the link's foe streams.
Valid after the vehicles have set their requests
Parameters
[in] arrivalTime The arrivalTime of the vehicle who checks for an approaching foe
[in] leaveTime The leaveTime of the vehicle who checks for an approaching foe
[in] speed The speed with which the checking vehicle plans to leave the link
[in] decel The maximum deceleration of the checking vehicle
Returns
Whether a foe of this link is approaching
Definition at line 439 of file MSLink.cpp.
References myFoeLanes, myFoeLinks, and myLane.
Referenced by TraCI_Lane::getLinks(), and isBlockingAnyone().
bool MSLink::hasFoes () const inline
Returns whether this link belongs to a junction where more than one edge is incoming.
Returns
Whether any foe links exist
Definition at line 349 of file MSLink.h.
References myHasFoes.
Referenced by MSVehicle::checkRewindLinkLanes(), and setRequestInformation().
bool MSLink::havePriority () const inline
Returns whether this link is a major link.
Returns
Whether the link has a large priority
Definition at line 310 of file MSLink.h.
References myState.
Referenced by MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), GUILane::drawGL(), MESegment::getLinkPenalty(), TraCI_Lane::getLinks(), MESegment::getMaxPenaltySeconds(), MESegment::isOpen(), lastWasContMajor(), MSVehicle::nextLinkPriority(), opened(), and MSEdge::recalcCache().
bool MSLink::haveRed () const inline
Returns whether this link is blocked by a red (or redyellow) traffic light.
Returns
Whether the link has a red light
Definition at line 317 of file MSLink.h.
References LINKSTATE_TL_RED, LINKSTATE_TL_REDYELLOW, and myState.
Referenced by opened().
void MSLink::initParallelLinks ()
initialize parallel links (to be called after all links are loaded)
Definition at line 862 of file MSLink.cpp.
References computeParallelLink(), myParallelLeft, and myParallelRight.
Referenced by getFoeLinks().
bool MSLink::isBlockingAnyone () const inline
Definition at line 228 of file MSLink.h.
References hasApproachingFoe(), myApproachingVehicles, and willHaveBlockedFoe().
bool MSLink::isCont () const inline
Definition at line 354 of file MSLink.h.
References myAmCont.
Referenced by MSVehicle::checkRewindLinkLanes(), and setRequestInformation().
bool MSLink::isExitLink () const
return whether the fromLane of this link is an internal lane and toLane is a normal lane
XXX this only works in networks with internal lanes
Definition at line 606 of file MSLink.cpp.
References MSEdge::EDGEFUNCTION_NORMAL, MSLane::getEdge(), getInternalLaneBefore(), MSEdge::getPurpose(), and myLane.
Referenced by fromInternalLane(), and keepClear().
bool MSLink::isInternalJunctionLink () const
return whether the fromLane and the toLane of this link are internal lanes
Definition at line 613 of file MSLink.cpp.
References getInternalLaneBefore(), and myInternalLane.
Referenced by fromInternalLane(), and keepClear().
bool MSLink::isLeader (const MSVehicle * ego, const MSVehicle * foe) const
Definition at line 764 of file MSLink.cpp.
References MSJunction::isLeader(), and myJunction.
Referenced by MSVehicle::checkLinkLeader(), keepClear(), and GUIVehicle::selectBlockingFoes().
bool MSLink::isTLSControlled () const inline
Definition at line 321 of file MSLink.h.
References myLogic.
Referenced by MESegment::getLinkPenalty(), and MESegment::getTLSCapacity().
bool MSLink::keepClear () const inline
whether the junction after this link must be kept clear
Definition at line 360 of file MSLink.h.
References fromInternalLane(), getInternalLaneBefore(), getInternalLengthsAfter(), getLaneBefore(), getLeaderInfo(), getLeaveTime(), getLengthBeforeCrossing(), getParallelLink(), getViaLane(), getViaLaneOrLane(), getZipperSpeed(), isExitLink(), isInternalJunctionLink(), isLeader(), lastWasContMajor(), myKeepClear, passedJunction(), and writeApproaching().
Referenced by MSVehicle::checkRewindLinkLanes().
bool MSLink::lastWasContMajor () const
whether this is a link past an internal junction which currently has priority
Definition at line 475 of file MSLink.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSLane::getLogicalPredecessorLane(), MSEdge::getPurpose(), havePriority(), myAmCont, and myInternalLane.
Referenced by keepClear().
bool MSLink::maybeOccupied (MSLane * lane) static private
returns whether the given lane may still be occupied by a vehicle currently on it
Definition at line 423 of file MSLink.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), MSLane::getLastAnyVehicle(), MSLane::getLength(), MSCFModel::getMaxDecel(), and MSVehicle::getSpeed().
Referenced by unsafeMergeSpeeds().
bool MSLink::opened (SUMOTime arrivalTime, double arrivalSpeed, double leaveSpeed, double vehicleLength, double impatience, double decel, SUMOTime waitingTime, double posLat = 0, std::vector< const SUMOVehicle * > * collectFoes = 0) const
Returns the information whether the link may be passed.
Valid after the junctions have set their reponds
Parameters
[in] collectFoes If a vector is passed, all blocking foes are collected and inserted into this vector
Returns
Whether this link may be passed.
Definition at line 298 of file MSLink.cpp.
References blockedByFoe(), MSLane::getIndex(), getLane(), SUMOVehicle::getLateralPositionOnLane(), getLeaveTime(), MSGlobals::gLateralResolution, MSGlobals::gUseMesoSim, MSGlobals::gUsingInternalLanes, havePriority(), haveRed(), LINKSTATE_ALLWAY_STOP, LINKSTATE_STOP, LINKSTATE_ZIPPER, myAmCont, myApproachingVehicles, myFoeLinks, myLane, myState, and mySublaneFoeLinks.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), getApproaching(), TraCI_Lane::getLinks(), MESegment::isOpen(), MSPModel_Striping::moveInDirectionOnLane(), and GUIVehicle::selectBlockingFoes().
MSLink& MSLink::operator= (const MSLink & s) private
invalidated assignment operator
void MSLink::passedJunction (const MSVehicle * vehicle)
erase vehicle from myLinkLeaders of this links junction
Definition at line 756 of file MSLink.cpp.
References myJunction, and MSJunction::passedJunction().
Referenced by MSVehicle::executeMove(), and keepClear().
void MSLink::removeApproaching (const SUMOVehicle * veh)
removes the vehicle from myApproachingVehicles
Definition at line 274 of file MSLink.cpp.
References myApproachingVehicles.
Referenced by MEVehicle::replaceRoute().
void MSLink::setApproaching (const SUMOVehicle * approaching, const SUMOTime arrivalTime, const double arrivalSpeed, const double leaveSpeed, const bool setRequest, const SUMOTime arrivalTimeBraking, const double arrivalSpeedBraking, const SUMOTime waitingTime, double dist)
Sets the information about an approaching vehicle.
The information is stored in myApproachingVehicles.
Definition at line 246 of file MSLink.cpp.
References getLeaveTime(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), and myApproachingVehicles.
Referenced by MSVehicle::checkRewindLinkLanes(), and MELoop::setApproaching().
void MSLink::setGreenFraction (const double fraction) inline
Sets the green fraction for passing a tls-controlled link (meso)
Definition at line 446 of file MSLink.h.
References myGreenFraction.
void MSLink::setMesoTLSPenalty (const SUMOTime penalty) inline
Sets the time penalty for passing a tls-controlled link (meso)
Definition at line 441 of file MSLink.h.
References myMesoTLSPenalty.
void MSLink::setRequestInformation (int index, bool hasFoes, bool isCont, const std::vector< MSLink * > & foeLinks, const std::vector< MSLane * > & foeLanes, MSLane * internalLaneBefore = 0)
Sets the request information.
Because traffic lights and junction logics are loaded after links, we have to assign the information about the right-of-way requests and responses after the initialisation.
Todo:
Unsecure!
Definition at line 95 of file MSLink.cpp.
References MSLane::getEdge(), MSEdge::getFromJunction(), Named::getID(), MSLane::getIncomingLanes(), getLastIntersections(), MSLane::getLength(), MSLane::getLinkCont(), MSLane::getLogicalPredecessorLane(), MSLane::getShape(), getViaLaneOrLane(), MSLane::getWidth(), MSGlobals::gLateralResolution, hasFoes(), MSLane::interpolateGeometryPosToLanePos(), PositionVector::intersectsAtLengths2D(), isCont(), MSEdge::isInternal(), myAmCont, myFoeLanes, myFoeLinks, myHasFoes, myIndex, myInternalLaneBefore, myJunction, myLane, myLaneBefore, myLengthsBehindCrossing, mySublaneFoeLinks, NUMERICAL_EPS, and toString().
void MSLink::setTLState (LinkState state, SUMOTime t)
Sets the current tl-state.
Parameters
[in] state The current state of the link
[in] t The time of the state change
Definition at line 461 of file MSLink.cpp.
References myLastStateChange, and myState.
Referenced by MSTrafficLightLogic::addLink(), and getLastStateChange().
static bool MSLink::unsafeMergeSpeeds (double leaderSpeed, double followerSpeed, double leaderDecel, double followerDecel) inline static private
return whether the given vehicles may NOT merge safely
Definition at line 463 of file MSLink.h.
References blockedByFoe(), computeParallelLink(), couldBrakeForLeader(), and maybeOccupied().
Referenced by blockedByFoe().
bool MSLink::willHaveBlockedFoe () const
Definition at line 263 of file MSLink.cpp.
References myBlockedFoeLinks.
Referenced by isBlockingAnyone().
void MSLink::writeApproaching (OutputDevice & od, const std::string fromLaneID) const
write information about all approaching vehicles to the given output device
Definition at line 494 of file MSLink.cpp.
References MSLink::ApproachingVehicleInformation::arrivalSpeed, MSLink::ApproachingVehicleInformation::arrivalSpeedBraking, MSLink::ApproachingVehicleInformation::arrivalTime, MSLink::ApproachingVehicleInformation::arrivalTimeBraking, OutputDevice::closeTag(), Named::getID(), getLane(), getViaLane(), MSLink::ApproachingVehicleInformation::leaveSpeed, MSLink::ApproachingVehicleInformation::leavingTime, myApproachingVehicles, OutputDevice::openTag(), SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_TO, SUMO_ATTR_VIA, time2string(), toString(), MSLink::ApproachingVehicleInformation::willPass, and OutputDevice::writeAttr().
Referenced by keepClear().
Field Documentation
bool MSLink::myAmCont private
Definition at line 519 of file MSLink.h.
Referenced by isCont(), lastWasContMajor(), opened(), and setRequestInformation().
std::map<const SUMOVehicle*, ApproachingVehicleInformation> MSLink::myApproachingVehicles private
Definition at line 486 of file MSLink.h.
Referenced by blockedAtTime(), getApproaching(), isBlockingAnyone(), opened(), removeApproaching(), setApproaching(), and writeApproaching().
std::set<MSLink*> MSLink::myBlockedFoeLinks private
Definition at line 487 of file MSLink.h.
Referenced by addBlockedLink(), and willHaveBlockedFoe().
LinkDirection MSLink::myDirection private
An abstract (hopefully human readable) definition of the link's direction.
Definition at line 505 of file MSLink.h.
Referenced by getDirection().
std::vector<const MSLane*> MSLink::myFoeLanes private
Definition at line 546 of file MSLink.h.
Referenced by getFoeLanes(), getLeaderInfo(), getLengthBeforeCrossing(), hasApproachingFoe(), and setRequestInformation().
std::vector<MSLink*> MSLink::myFoeLinks private
Definition at line 545 of file MSLink.h.
Referenced by getFoeLinks(), getZipperSpeed(), hasApproachingFoe(), opened(), and setRequestInformation().
double MSLink::myFoeVisibilityDistance private
distance from which an approaching vehicle is able to see all relevant foes and may accelerate if the link is minor and no foe is approaching. Defaults to 4.5m.
Definition at line 513 of file MSLink.h.
Referenced by getFoeVisibilityDistance().
double MSLink::myGreenFraction private
green fraction at tls for mesoscopic simulation
Definition at line 535 of file MSLink.h.
Referenced by getGreenFraction(), and setGreenFraction().
bool MSLink::myHasFoes private
Whether any foe links exist.
Definition at line 516 of file MSLink.h.
Referenced by hasFoes(), and setRequestInformation().
int MSLink::myIndex private
The position within this respond.
Definition at line 490 of file MSLink.h.
Referenced by getIndex(), and setRequestInformation().
MSLane* const MSLink::myInternalLane private
The following junction-internal lane if used.
Definition at line 524 of file MSLink.h.
Referenced by getInternalLengthsAfter(), getViaLane(), getViaLaneOrLane(), isInternalJunctionLink(), and lastWasContMajor().
const MSLane* MSLink::myInternalLaneBefore private
Definition at line 530 of file MSLink.h.
Referenced by getInternalLaneBefore(), getLaneBefore(), getLeaderInfo(), and setRequestInformation().
MSJunction* MSLink::myJunction private
the junction to which this link belongs
Definition at line 559 of file MSLink.h.
Referenced by getJunction(), getZipperSpeed(), isLeader(), passedJunction(), and setRequestInformation().
bool MSLink::myKeepClear private
Definition at line 521 of file MSLink.h.
Referenced by keepClear().
MSLane* MSLink::myLane private
The lane behind the junction approached by this link.
Definition at line 481 of file MSLink.h.
Referenced by getLane(), getLeaderInfo(), getViaLaneOrLane(), hasApproachingFoe(), isExitLink(), opened(), and setRequestInformation().
MSLane* MSLink::myLaneBefore private
The lane approaching this link.
Definition at line 484 of file MSLink.h.
Referenced by getLaneBefore(), and setRequestInformation().
SUMOTime MSLink::myLastStateChange private
The time of the last state change.
Definition at line 502 of file MSLink.h.
Referenced by getLastStateChange(), and setTLState().
double MSLink::myLength private
The length of the link.
Definition at line 508 of file MSLink.h.
Referenced by getLength().
std::vector<std::pair<double, double> > MSLink::myLengthsBehindCrossing private
Definition at line 542 of file MSLink.h.
Referenced by getLeaderInfo(), getLengthBeforeCrossing(), and setRequestInformation().
const MSTrafficLightLogic* MSLink::myLogic private
the controlling logic or 0
Definition at line 496 of file MSLink.h.
Referenced by getTLLogic(), and isTLSControlled().
const SUMOTime MSLink::myLookaheadTime = TIME2STEPS(1) static private
Definition at line 552 of file MSLink.h.
Referenced by blockedByFoe().
const SUMOTime MSLink::myLookaheadTimeZipper = TIME2STEPS(4) static private
Definition at line 553 of file MSLink.h.
Referenced by blockedByFoe().
SUMOTime MSLink::myMesoTLSPenalty private
penalty time at tls for mesoscopic simulation
Definition at line 533 of file MSLink.h.
Referenced by getMesoTLSPenalty(), and setMesoTLSPenalty().
MSLink* MSLink::myParallelLeft private
Definition at line 556 of file MSLink.h.
Referenced by getParallelLink(), and initParallelLinks().
MSLink* MSLink::myParallelRight private
Definition at line 555 of file MSLink.h.
Referenced by getParallelLink(), and initParallelLinks().
LinkState MSLink::myState private
The state of the link.
Definition at line 499 of file MSLink.h.
Referenced by blockedByFoe(), getState(), havePriority(), haveRed(), opened(), and setTLState().
std::vector<MSLink*> MSLink::mySublaneFoeLinks private
Definition at line 550 of file MSLink.h.
Referenced by opened(), and setRequestInformation().
const int MSLink::myTLIndex private
the traffic light index
Definition at line 493 of file MSLink.h.
Referenced by getTLIndex().
const double MSLink::ZIPPER_ADAPT_DIST static
Definition at line 81 of file MSLink.h.
Referenced by getZipperSpeed(), and MSVehicle::unsafeLinkAhead().
The documentation for this class was generated from the following files:
MSLink.h
MSLink.cpp