SUMO - Simulation of Urban MObility: MSMeanData_Net::MSLaneMeanDataValues Class Reference
MSMeanData_Net::MSLaneMeanDataValues Class Reference
Data structure for mean (aggregated) edge/lane values.
#include <MSMeanData_Net.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
Public Member Functions
void addTo (MSMeanData::MeanDataValues &val) const
Add the values of this to the given one and store them there.
const std::string & getDescription () const
const MSLane * getLane () const
Returns the lane the reminder works on.
virtual double getSamples () const
Returns the number of collected sample seconds.
double getTravelledDistance () const
Returns the total travelled distance.
bool isEmpty () const
Returns whether any data was collected.
MSLaneMeanDataValues (MSLane *const lane, const double length, const bool doAdd, const MSMeanData_Net *parent)
Constructor.
bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
void reset (bool afterWrite=false)
Resets values so they may be used for the next interval.
void setDescription (const std::string &description)
virtual void update ()
Called if a per timestep update is needed. Default does nothing.
void write (OutputDevice &dev, const SUMOTime period, const double numLanes, const double defaultTravelTime, const int numVehicles=-1) const
Writes output values into the given stream.
virtual ~MSLaneMeanDataValues ()
Destructor.
Methods inherited from MSMoveReminder
bool notifyLeave (SUMOVehicle &veh, double lastPos, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Called if the vehicle leaves the reminder's lane.
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Computes current values and adds them to their sums.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Protected Member Functions
void notifyMoveInternal (const SUMOVehicle &veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane)
Internal notification about the vehicle moves.
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
MSLane *const myLane
Lane on which the reminder works.
const double myLaneLength
The length of the lane / edge the data collector is on.
Collected values
The number of sampled vehicle movements (in s)
double sampleSeconds
double travelledDistance
The sum of the distances the vehicles travelled.
Private Attributes
const MSMeanData_Net * myParent
The meandata parent.
Collected values
The number of vehicles that were emitted on the lane
int nVehDeparted
int nVehArrived
The number of vehicles that finished on the lane.
int nVehEntered
The number of vehicles that entered this lane within the sample interval.
int nVehLeft
The number of vehicles that left this lane within the sample interval.
int nVehVaporized
The number of vehicles that left this lane within the sample interval.
double waitSeconds
The number of vehicle probes with small speed.
int nVehLaneChangeFrom
The number of vehicles that changed from this lane.
int nVehLaneChangeTo
The number of vehicles that changed to this lane.
double frontSampleSeconds
The number of vehicle probes regarding the vehicle front.
double frontTravelledDistance
The travelled distance regarding the vehicle front.
double vehLengthSum
The sum of the lengths the vehicles had.
Detailed Description
Data structure for mean (aggregated) edge/lane values.
Structure holding values that describe the flow and other physical properties aggregated over some seconds.
Definition at line 74 of file MSMeanData_Net.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 96 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSMeanData_Net::MSLaneMeanDataValues::MSLaneMeanDataValues (MSLane *const lane, const double length, const bool doAdd, const MSMeanData_Net * parent)
Constructor.
Parameters
[in] length The length of the object for which the data gets collected
Definition at line 54 of file MSMeanData_Net.cpp.
MSMeanData_Net::MSLaneMeanDataValues::~MSLaneMeanDataValues () virtual
Destructor.
Definition at line 66 of file MSMeanData_Net.cpp.
Member Function Documentation
void MSMeanData_Net::MSLaneMeanDataValues::addTo (MSMeanData::MeanDataValues & val) const virtual
Add the values of this to the given one and store them there.
Parameters
[in] val The meandata to add to
Implements MSMeanData::MeanDataValues.
Definition at line 89 of file MSMeanData_Net.cpp.
References frontSampleSeconds, frontTravelledDistance, nVehArrived, nVehDeparted, nVehEntered, nVehLaneChangeFrom, nVehLaneChangeTo, nVehLeft, nVehVaporized, MSMeanData::MeanDataValues::sampleSeconds, MSMeanData::MeanDataValues::travelledDistance, vehLengthSum, and waitSeconds.
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 231 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::setDeviceParameter().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 90 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), TraCI_InductionLoop::getLaneID(), TraCI_LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), notifyEnter(), notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
double MSMeanData::MeanDataValues::getSamples () const virtual inherited
Returns the number of collected sample seconds.
Returns
the number of collected sample seconds
Reimplemented in MSMeanData::MeanDataValueTracker.
Definition at line 182 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::sampleSeconds.
Referenced by MSMeanData::writePrefix(), MEInductLoop::writeXMLOutput(), and MSCalibrator::writeXMLOutput().
double MSMeanData::MeanDataValues::getTravelledDistance () const inline inherited
Returns the total travelled distance.
Returns
the total travelled distance
Definition at line 166 of file MSMeanData.h.
References MSMeanData::MeanDataValues::travelledDistance.
Referenced by MSCalibrator::writeXMLOutput().
bool MSMeanData_Net::MSLaneMeanDataValues::isEmpty () const virtual
Returns whether any data was collected.
Returns
whether no data was collected
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 164 of file MSMeanData_Net.cpp.
References nVehArrived, nVehDeparted, nVehEntered, nVehLaneChangeFrom, nVehLaneChangeTo, nVehLeft, nVehVaporized, and MSMeanData::MeanDataValues::sampleSeconds.
bool MSMeanData_Net::MSLaneMeanDataValues::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Computes current values and adds them to their sums.
The fraction of time the vehicle is on the lane is computed and used as a weight for the vehicle's current values. The "emitted" field is incremented, additionally.
Parameters
[in] veh The vehicle that enters the lane
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
Always true
See also
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 146 of file MSMeanData_Net.cpp.
References MSMoveReminder::getLane(), myParent, MSMoveReminder::NOTIFICATION_DEPARTED, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSMoveReminder::NOTIFICATION_SEGMENT, nVehDeparted, nVehEntered, nVehLaneChangeTo, and MSDetectorFileOutput::vehicleApplies().
bool MSMeanData_Net::MSLaneMeanDataValues::notifyLeave (SUMOVehicle & veh, double lastPos, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Called if the vehicle leaves the reminder's lane.
Parameters
veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 122 of file MSMeanData_Net.cpp.
References MSMoveReminder::getLane(), MSGlobals::gUseMesoSim, myParent, MSMoveReminder::NOTIFICATION_ARRIVED, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSMoveReminder::NOTIFICATION_SEGMENT, MSMoveReminder::NOTIFICATION_VAPORIZED, nVehArrived, nVehLaneChangeFrom, nVehLeft, nVehVaporized, MSMoveReminder::removeFromVehicleUpdateValues(), and MSDetectorFileOutput::vehicleApplies().
bool MSMeanData::MeanDataValues::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) virtual inherited
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the reminder completely.
Reimplemented from MSMoveReminder.
Definition at line 80 of file MSMeanData.cpp.
References Named::getID(), SUMOVehicle::getID(), MSMoveReminder::getLane(), MSVehicleType::getLength(), SUMOVehicle::getPreviousSpeed(), SUMOVehicle::getVehicleType(), MSGlobals::gSemiImplicitEulerUpdate, SUMOVehicle::hasArrived(), MAX2(), MIN2(), MSMeanData::MeanDataValues::myLaneLength, MSMoveReminder::notifyMoveInternal(), NUMERICAL_EPS, MSCFModel::passingTime(), MSCFModel::speedAfterTime(), TS, and WRITE_ERROR.
void MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal (const SUMOVehicle & veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane) protected virtual
Internal notification about the vehicle moves.
See also
MSMoveReminder::notifyMoveInternal
Reimplemented from MSMoveReminder.
Definition at line 108 of file MSMeanData_Net.cpp.
References frontSampleSeconds, frontTravelledDistance, MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), MSMeanData_Net::myHaltSpeed, myParent, MSMeanData::MeanDataValues::sampleSeconds, MSMeanData::MeanDataValues::travelledDistance, vehLengthSum, and waitSeconds.
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 94 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), notifyLeave(), and MSMoveReminder::updateDetector().
void MSMeanData_Net::MSLaneMeanDataValues::reset (bool afterWrite = false) virtual
Resets values so they may be used for the next interval.
Implements MSMeanData::MeanDataValues.
Definition at line 71 of file MSMeanData_Net.cpp.
References frontSampleSeconds, frontTravelledDistance, nVehArrived, nVehDeparted, nVehEntered, nVehLaneChangeFrom, nVehLaneChangeTo, nVehLeft, nVehVaporized, MSMeanData::MeanDataValues::sampleSeconds, MSMeanData::MeanDataValues::travelledDistance, vehLengthSum, and waitSeconds.
Referenced by METriggeredCalibrator::execute(), METriggeredCalibrator::reset(), MSCalibrator::reset(), MSCalibrator::updateMeanData(), and MEInductLoop::writeXMLOutput().
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 227 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
void MSMeanData::MeanDataValues::update () virtual inherited
Called if a per timestep update is needed. Default does nothing.
Reimplemented in MSMeanData_Harmonoise::MSLaneMeanDataValues.
Definition at line 177 of file MSMeanData.cpp.
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 51 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
void MSMeanData_Net::MSLaneMeanDataValues::write (OutputDevice & dev, const SUMOTime period, const double numLanes, const double defaultTravelTime, const int numVehicles = -1) const virtual
Writes output values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] period Length of the period the data were gathered
[in] numLanes The total number of lanes for which the data was collected
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSMeanData::MeanDataValues.
Definition at line 171 of file MSMeanData_Net.cpp.
References OutputDevice::closeTag(), frontSampleSeconds, frontTravelledDistance, MIN2(), MSMeanData::MeanDataValues::myLaneLength, MSMeanData::myMaxTravelTime, MSMeanData::myMinSamples, myParent, nVehArrived, nVehDeparted, nVehEntered, nVehLaneChangeFrom, nVehLaneChangeTo, nVehLeft, nVehVaporized, MSMeanData::MeanDataValues::sampleSeconds, STEPS2TIME, MSMeanData::MeanDataValues::travelledDistance, vehLengthSum, waitSeconds, and OutputDevice::writeAttr().
Referenced by MEInductLoop::writeXMLOutput().
Field Documentation
double MSMeanData_Net::MSLaneMeanDataValues::frontSampleSeconds private
The number of vehicle probes regarding the vehicle front.
Definition at line 174 of file MSMeanData_Net.h.
Referenced by addTo(), notifyMoveInternal(), reset(), and write().
double MSMeanData_Net::MSLaneMeanDataValues::frontTravelledDistance private
The travelled distance regarding the vehicle front.
Definition at line 177 of file MSMeanData_Net.h.
Referenced by addTo(), notifyMoveInternal(), reset(), and write().
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 243 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 241 of file MSMoveReminder.h.
Referenced by MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSMoveReminder::MSMoveReminder(), MSInductLoop::notifyEnter(), and MSMeanData::MeanDataValueTracker::reset().
const double MSMeanData::MeanDataValues::myLaneLength protected inherited
The length of the lane / edge the data collector is on.
Definition at line 175 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::notifyMove(), MSMeanData::MeanDataValueTracker::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and write().
const MSMeanData_Net* MSMeanData_Net::MSLaneMeanDataValues::myParent private
The meandata parent.
Definition at line 184 of file MSMeanData_Net.h.
Referenced by notifyEnter(), notifyLeave(), notifyMoveInternal(), and write().
int MSMeanData_Net::MSLaneMeanDataValues::nVehArrived
The number of vehicles that finished on the lane.
Definition at line 152 of file MSMeanData_Net.h.
Referenced by addTo(), MSCalibrator::execute(), isEmpty(), notifyLeave(), reset(), and write().
int MSMeanData_Net::MSLaneMeanDataValues::nVehDeparted
Definition at line 149 of file MSMeanData_Net.h.
Referenced by addTo(), MSCalibrator::execute(), isEmpty(), notifyEnter(), METriggeredCalibrator::passed(), MSCalibrator::passed(), reset(), write(), and MSCalibrator::writeXMLOutput().
int MSMeanData_Net::MSLaneMeanDataValues::nVehEntered
The number of vehicles that entered this lane within the sample interval.
Definition at line 155 of file MSMeanData_Net.h.
Referenced by addTo(), MSCalibrator::execute(), isEmpty(), notifyEnter(), METriggeredCalibrator::passed(), MSCalibrator::passed(), reset(), write(), and MSCalibrator::writeXMLOutput().
int MSMeanData_Net::MSLaneMeanDataValues::nVehLaneChangeFrom private
The number of vehicles that changed from this lane.
Definition at line 168 of file MSMeanData_Net.h.
Referenced by addTo(), isEmpty(), notifyLeave(), reset(), and write().
int MSMeanData_Net::MSLaneMeanDataValues::nVehLaneChangeTo private
The number of vehicles that changed to this lane.
Definition at line 171 of file MSMeanData_Net.h.
Referenced by addTo(), isEmpty(), notifyEnter(), reset(), and write().
int MSMeanData_Net::MSLaneMeanDataValues::nVehLeft
The number of vehicles that left this lane within the sample interval.
Definition at line 158 of file MSMeanData_Net.h.
Referenced by addTo(), MSCalibrator::execute(), isEmpty(), notifyLeave(), reset(), and write().
int MSMeanData_Net::MSLaneMeanDataValues::nVehVaporized
The number of vehicles that left this lane within the sample interval.
Definition at line 161 of file MSMeanData_Net.h.
Referenced by addTo(), MSCalibrator::execute(), isEmpty(), notifyLeave(), METriggeredCalibrator::passed(), reset(), write(), and MSCalibrator::writeXMLOutput().
double MSMeanData::MeanDataValues::sampleSeconds protected inherited
Definition at line 180 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::addTo(), MSMeanData_Amitran::MSLaneMeanDataValues::addTo(), addTo(), MSMeanData::MeanDataValues::getSamples(), MSMeanData_Amitran::MSLaneMeanDataValues::isEmpty(), isEmpty(), MSMeanData::MeanDataValues::isEmpty(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::reset(), reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and write().
double MSMeanData::MeanDataValues::travelledDistance protected inherited
The sum of the distances the vehicles travelled.
Definition at line 183 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::addTo(), MSMeanData_Amitran::MSLaneMeanDataValues::addTo(), addTo(), MSMeanData::MeanDataValues::getTravelledDistance(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::reset(), reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and write().
double MSMeanData_Net::MSLaneMeanDataValues::vehLengthSum private
The sum of the lengths the vehicles had.
Definition at line 180 of file MSMeanData_Net.h.
Referenced by addTo(), notifyMoveInternal(), reset(), and write().
double MSMeanData_Net::MSLaneMeanDataValues::waitSeconds
The number of vehicle probes with small speed.
Definition at line 164 of file MSMeanData_Net.h.
Referenced by addTo(), MSCalibrator::execute(), notifyMoveInternal(), reset(), and write().
The documentation for this class was generated from the following files:
MSMeanData_Net.h
MSMeanData_Net.cpp