# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    bld.env.append_value("LIB", ["boost_system", "boost_filesystem"])

    module = bld.create_ns3_module('fast-broadcast', ['core', 'network', 'internet', 'mobility', 'wifi', 'obstacle'])
    module.source = [
        'model/FBApplication.cc',
        'model/FBHeader.cc',
        'model/FBNode.cc',
        'model/Edge.cc'
        ]

    module_test = bld.create_ns3_module_test_library('fast-broadcast')
    module_test.source = [
        'test/fast-broadcast-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'fast-broadcast'
    headers.source = [
        'model/FBApplication.h',
        'model/FBHeader.h',
        'model/FBNode.h',
        'model/Edge.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

