SUMO - Simulation of Urban MObility: polyfonts.h File Reference
polyfonts.h File Reference
#include <config.h>
#include "polyfonttypes.h"
Functions
double pfdkGetStringWidth (const char *c)
int pfDrawChar (wchar_t c)
int pfDrawString (const char *c)
int pfDrawStringW (wchar_t *c)
wchar_t pfGetChar (int glyph)
double pfGetCharAdvance (wchar_t c)
double pfGetCharAscent (wchar_t c)
int pfGetCharBBox (wchar_t c, double *minx, double *miny, double *maxx, double *maxy)
double pfGetCharDescent (wchar_t c)
double pfGetCharHeight (wchar_t c)
double pfGetCharWidth (wchar_t c)
pffont * pfGetCurrentFont ()
double pfGetFontAscent ()
int pfGetFontBBox (double *minx, double *miny, double *maxx, double *maxy)
double pfGetFontDescent ()
double pfGetFontHeight ()
char * pfGetFontName ()
int pfGetFontNumGlyphs ()
double pfGetFontWidth ()
void pfGetPosition (double *x, double *y)
void pfSetAngleD (double a)
void pfSetAngleR (double a)
void pfSetCenter (int onOff)
int pfSetFont (pffont *f)
void pfSetPosition (double x, double y)
void pfSetScale (double s)
int pfSetScaleBox (char *c, double w, double h)
int pfSetScaleBoxW (wchar_t *c, double w, double h)
void pfSetScaleXY (double sx, double sy)
void pfSetSkew (double s)
void pfSetWeight (int w)
void pfUnloadFont (pffont *f)
Function Documentation
double pfdkGetStringWidth (const char * c)
Definition at line 1113 of file polyfonts.c.
References pfGetCharAdvance().
Referenced by GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNECalibrator::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GLHelper::drawText(), GLHelper::drawTextBox(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), and GUITLLogicPhasesTrackerWindow::drawValues().
int pfDrawChar (wchar_t c)
Definition at line 1058 of file polyfonts.c.
References drawWideChar().
int pfDrawString (const char * c)
Definition at line 1074 of file polyfonts.c.
References drawWideChar().
Referenced by GUISUMOAbstractView::displayLegend(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNECalibrator::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GLHelper::drawText(), GLHelper::drawTextBox(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), and GUITLLogicPhasesTrackerWindow::drawValues().
int pfDrawStringW (wchar_t * c)
Definition at line 1093 of file polyfonts.c.
References drawWideChar().
wchar_t pfGetChar (int glyph)
Definition at line 801 of file polyfonts.c.
References pfglyph::glyph, pffont::glyphs, and pffont::numglyphs.
double pfGetCharAdvance (wchar_t c)
Definition at line 869 of file polyfonts.c.
References pfglyph::advance, pfGetGlyph(), and pfScaleX.
Referenced by pfdkGetStringWidth().
double pfGetCharAscent (wchar_t c)
Definition at line 946 of file polyfonts.c.
References pfGetCharBBox().
int pfGetCharBBox (wchar_t c, double * minx, double * miny, double * maxx, double * maxy)
Definition at line 883 of file polyfonts.c.
References getCharBBox(), pfScaleX, pfScaleY, pfSkew(), and pfTextSkew.
Referenced by pfGetCharAscent(), pfGetCharDescent(), pfGetCharHeight(), and pfGetCharWidth().
double pfGetCharDescent (wchar_t c)
Definition at line 960 of file polyfonts.c.
References pfGetCharBBox().
double pfGetCharHeight (wchar_t c)
Definition at line 918 of file polyfonts.c.
References pfGetCharBBox().
double pfGetCharWidth (wchar_t c)
Definition at line 932 of file polyfonts.c.
References pfGetCharBBox().
pffont* pfGetCurrentFont ()
Definition at line 692 of file polyfonts.c.
References pfCurrentFont.
double pfGetFontAscent ()
Definition at line 761 of file polyfonts.c.
References pfGetFontBBox().
int pfGetFontBBox (double * minx, double * miny, double * maxx, double * maxy)
Definition at line 699 of file polyfonts.c.
References pffont::maxx, pffont::maxy, pffont::minx, pffont::miny, pfScaleX, pfScaleY, pfSkew(), and pfTextSkew.
Referenced by pfGetFontAscent(), pfGetFontDescent(), pfGetFontHeight(), and pfGetFontWidth().
double pfGetFontDescent ()
Definition at line 775 of file polyfonts.c.
References pfGetFontBBox().
double pfGetFontHeight ()
Definition at line 733 of file polyfonts.c.
References pfGetFontBBox().
char* pfGetFontName ()
Definition at line 678 of file polyfonts.c.
References pffont::name.
int pfGetFontNumGlyphs ()
Definition at line 789 of file polyfonts.c.
References pffont::numglyphs.
double pfGetFontWidth ()
Definition at line 747 of file polyfonts.c.
References pfGetFontBBox().
void pfGetPosition (double * x, double * y)
Definition at line 488 of file polyfonts.c.
References pfTextX, and pfTextY.
void pfSetAngleD (double a)
Definition at line 518 of file polyfonts.c.
References DtoR, and pfSetAngleR().
void pfSetAngleR (double a)
Definition at line 510 of file polyfonts.c.
References pfTextCos, and pfTextSin.
Referenced by pfSetAngleD().
void pfSetCenter (int onOff)
Definition at line 525 of file polyfonts.c.
References pfCenter.
int pfSetFont (pffont * f)
Definition at line 152 of file polyfonts.c.
void pfSetPosition (double x, double y)
Definition at line 480 of file polyfonts.c.
References pfTextX, and pfTextY.
Referenced by GUISUMOAbstractView::displayLegend(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNECalibrator::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GLHelper::drawText(), GLHelper::drawTextBox(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), and GUITLLogicPhasesTrackerWindow::drawValues().
void pfSetScale (double s)
Definition at line 465 of file polyfonts.c.
References pfScaleX, and pfScaleY.
Referenced by GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNECalibrator::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GLHelper::drawText(), GLHelper::drawTextBox(), and GUIParameterTracker::GUIParameterTrackerPanel::drawValues().
int pfSetScaleBox (char * c, double w, double h)
Definition at line 638 of file polyfonts.c.
References getStringBox(), and pfSetScaleXY().
int pfSetScaleBoxW (wchar_t * c, double w, double h)
Definition at line 658 of file polyfonts.c.
References getStringBoxW(), and pfSetScaleXY().
void pfSetScaleXY (double sx, double sy)
Definition at line 472 of file polyfonts.c.
References pfScaleX, and pfScaleY.
Referenced by GUISUMOAbstractView::displayLegend(), GUIParameterTracker::GUIParameterTrackerPanel::drawValues(), GUITLLogicPhasesTrackerWindow::drawValues(), pfSetScaleBox(), and pfSetScaleBoxW().
void pfSetSkew (double s)
Definition at line 496 of file polyfonts.c.
References max, min, and pfTextSkew.
void pfSetWeight (int w)
Definition at line 503 of file polyfonts.c.
References max, min, numWeights, and pfTextWeight.
void pfUnloadFont (pffont * f)
Definition at line 256 of file polyfonts.c.
References pffont::glyphs, pffont::loaded, lookupGlOp(), pffont::maxx, pffont::maxy, pffont::minx, pffont::miny, pffont::name, pffont::numglyphs, and pfglyph::segments.