SUMO - Simulation of Urban MObility: GNERerouterInterval Class Reference
GNERerouterInterval Class Reference
#include <GNERerouterInterval.h>
Public Member Functions
double getBegin () const
get begin time
const std::vector< GNEClosingLaneReroute > & getClosingLaneReroutes () const
get closing reroutes
const std::vector< GNEClosingReroute > & getClosingReroutes () const
get closing reroutes
const std::vector< GNEDestProbReroute > & getDestProbReroutes () const
get destiny probability reroutes
double getEnd () const
get end time
GNERerouter * getRerouterParent () const
get rerouter parent
const std::vector< GNERouteProbReroute > & getRouteProbReroutes () const
get reoute probability reroutes
SumoXMLTag getTag () const
get tag
GNERerouterInterval (GNERerouter *rerouterParent, double begin, double end)
constructor
bool insertClosingReroutes (const GNEClosingReroute &cr)
insert a new closing lane reroute
bool insertClosinLanegReroutes (const GNEClosingLaneReroute &clr)
insert a new closing lane reroute
bool insertDestProbReroutes (const GNEDestProbReroute &dpr)
insert destiny probability reroute
bool insertRouteProbReroute (const GNERouteProbReroute &rpr)
insert route probability reroute
bool operator< (const GNERerouterInterval &rerouterInterval) const
overload operator <
bool operator<= (const GNERerouterInterval &rerouterInterval) const
overload operator <=
GNERerouterInterval & operator= (const GNERerouterInterval &rerouterInterval)
overload operator =
bool operator== (const GNERerouterInterval &rerouterInterval) const
overload operator =
bool operator> (const GNERerouterInterval &rerouterInterval) const
overload operator >
bool operator>= (const GNERerouterInterval &rerouterInterval) const
overload operator >=
bool removeClosingLaneReroutes (const GNEClosingLaneReroute &clr)
remove a previously inserted closing reroute
bool removeClosingReroutes (const GNEClosingReroute &cr)
remove a previously inserted closing reroute
bool removeDestProbReroutes (const GNEDestProbReroute &dpr)
remove a previously inserted destiny probability reroute
bool removeRouteProbReroute (const GNERouteProbReroute &rpr)
remove a previously inserted route probability reroute
void setBegin (double begin)
set begin time
void setClosingLaneReroutes (const std::vector< GNEClosingLaneReroute > &closingLaneReroutes)
set closing reroutes
void setClosingReroutes (const std::vector< GNEClosingReroute > &closingReroutes)
set closing reroutes
void setDestProbReroutes (const std::vector< GNEDestProbReroute > &destProbReroutes)
set destiny probability reroutes
void setEnd (double end)
set end time
void setRouteProbReroutes (const std::vector< GNERouteProbReroute > &rerouteProbabilityReroutes)
set reoute probability reroutes
~GNERerouterInterval ()
destructor
Protected Attributes
double myBegin
begin timeStep
std::vector< GNEClosingLaneReroute > myClosingLaneReroutes
vector with the closingLaneReroutes
std::vector< GNEClosingReroute > myClosingReroutes
vector with the closingReroutes
std::vector< GNEDestProbReroute > myDestProbReroutes
vector with the destProbReroutes
double myEnd
end timeStep
GNERerouter * myRerouterParent
pointer to rerouter parent
std::vector< GNERouteProbReroute > myRouteProbReroutes
vector with the routeProbReroutes
SumoXMLTag myTag
XML Tag of a rerouter interval.
Detailed Description
class used to represent a interval used in rerouters
Definition at line 50 of file GNERerouterInterval.h.
Constructor & Destructor Documentation
GNERerouterInterval::GNERerouterInterval (GNERerouter * rerouterParent, double begin, double end)
constructor
Definition at line 42 of file GNERerouterInterval.cpp.
GNERerouterInterval::~GNERerouterInterval ()
destructor
Definition at line 51 of file GNERerouterInterval.cpp.
Member Function Documentation
double GNERerouterInterval::getBegin () const
get begin time
Definition at line 168 of file GNERerouterInterval.cpp.
References myBegin.
const std::vector< GNEClosingLaneReroute > & GNERerouterInterval::getClosingLaneReroutes () const
get closing reroutes
Definition at line 192 of file GNERerouterInterval.cpp.
References myClosingLaneReroutes.
Referenced by GNERerouterIntervalDialog::onCmdReset().
const std::vector< GNEClosingReroute > & GNERerouterInterval::getClosingReroutes () const
get closing reroutes
Definition at line 198 of file GNERerouterInterval.cpp.
References myClosingReroutes.
Referenced by GNERerouterIntervalDialog::onCmdReset().
const std::vector< GNEDestProbReroute > & GNERerouterInterval::getDestProbReroutes () const
get destiny probability reroutes
Definition at line 204 of file GNERerouterInterval.cpp.
References myDestProbReroutes.
Referenced by GNERerouterIntervalDialog::onCmdReset().
double GNERerouterInterval::getEnd () const
get end time
Definition at line 174 of file GNERerouterInterval.cpp.
References myEnd.
GNERerouter * GNERerouterInterval::getRerouterParent () const
get rerouter parent
Definition at line 156 of file GNERerouterInterval.cpp.
References myRerouterParent.
Referenced by GNERerouterDialog::checkModifyInterval(), GNERerouterIntervalDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdEditClosingLaneReroute(), GNERerouterIntervalDialog::onCmdEditClosingReroute(), and GNERerouterIntervalDialog::onCmdEditDestProbReroute().
const std::vector< GNERouteProbReroute > & GNERerouterInterval::getRouteProbReroutes () const
get reoute probability reroutes
Definition at line 210 of file GNERerouterInterval.cpp.
References myRouteProbReroutes.
Referenced by GNERerouterIntervalDialog::onCmdReset().
SumoXMLTag GNERerouterInterval::getTag () const
get tag
Definition at line 162 of file GNERerouterInterval.cpp.
References myTag.
Referenced by GNERerouterIntervalDialog::onCmdAccept().
bool GNERerouterInterval::insertClosingReroutes (const GNEClosingReroute & cr)
insert a new closing lane reroute
Returns
true if insertion was sucesfully, false if is duplicated
Definition at line 81 of file GNERerouterInterval.cpp.
References GNEClosingReroute::getClosedEdge(), GNEAttributeCarrier::getID(), GNEClosingReroute::getTag(), myClosingReroutes, toString(), and WRITE_WARNING.
bool GNERerouterInterval::insertClosinLanegReroutes (const GNEClosingLaneReroute & clr)
insert a new closing lane reroute
Returns
true if insertion was sucesfully, false if is duplicated
Definition at line 56 of file GNERerouterInterval.cpp.
References GNEClosingLaneReroute::getClosedLane(), GNEAttributeCarrier::getID(), GNEClosingLaneReroute::getTag(), myClosingLaneReroutes, toString(), and WRITE_WARNING.
bool GNERerouterInterval::insertDestProbReroutes (const GNEDestProbReroute & dpr)
insert destiny probability reroute
Returns
true if deletetion was sucesfully, false if wasn't found
Definition at line 106 of file GNERerouterInterval.cpp.
References GNEAttributeCarrier::getID(), GNEDestProbReroute::getNewDestination(), GNEDestProbReroute::getTag(), myDestProbReroutes, toString(), and WRITE_WARNING.
bool GNERerouterInterval::insertRouteProbReroute (const GNERouteProbReroute & rpr)
insert route probability reroute
Returns
true if insertion was sucesfully, false if is duplicated
Definition at line 131 of file GNERerouterInterval.cpp.
References GNERouteProbReroute::getNewRouteId(), GNERouteProbReroute::getTag(), myRouteProbReroutes, toString(), and WRITE_WARNING.
bool GNERerouterInterval::operator< (const GNERerouterInterval & rerouterInterval) const
overload operator <
Definition at line 281 of file GNERerouterInterval.cpp.
References myBegin, and myEnd.
bool GNERerouterInterval::operator<= (const GNERerouterInterval & rerouterInterval) const
overload operator <=
Definition at line 293 of file GNERerouterInterval.cpp.
References myBegin, and myEnd.
GNERerouterInterval & GNERerouterInterval::operator= (const GNERerouterInterval & rerouterInterval)
overload operator =
Definition at line 240 of file GNERerouterInterval.cpp.
References myBegin, myEnd, and myRerouterParent.
bool GNERerouterInterval::operator== (const GNERerouterInterval & rerouterInterval) const
overload operator =
Definition at line 251 of file GNERerouterInterval.cpp.
References myBegin, and myEnd.
bool GNERerouterInterval::operator> (const GNERerouterInterval & rerouterInterval) const
overload operator >
Definition at line 257 of file GNERerouterInterval.cpp.
References myBegin, and myEnd.
bool GNERerouterInterval::operator>= (const GNERerouterInterval & rerouterInterval) const
overload operator >=
Definition at line 269 of file GNERerouterInterval.cpp.
References myBegin, and myEnd.
bool GNERerouterInterval::removeClosingLaneReroutes (const GNEClosingLaneReroute & clr)
remove a previously inserted closing reroute
Returns
true if deletetion was sucesfully, false if wasn't found
Definition at line 68 of file GNERerouterInterval.cpp.
References GNEClosingLaneReroute::getClosedLane(), GNEAttributeCarrier::getID(), GNEClosingLaneReroute::getTag(), myClosingLaneReroutes, toString(), and WRITE_WARNING.
bool GNERerouterInterval::removeClosingReroutes (const GNEClosingReroute & cr)
remove a previously inserted closing reroute
Returns
true if deletetion was sucesfully, false if wasn't found
Definition at line 93 of file GNERerouterInterval.cpp.
References GNEClosingReroute::getClosedEdge(), GNEAttributeCarrier::getID(), GNEClosingReroute::getTag(), myClosingReroutes, toString(), and WRITE_WARNING.
bool GNERerouterInterval::removeDestProbReroutes (const GNEDestProbReroute & dpr)
remove a previously inserted destiny probability reroute
Returns
true if deletetion was sucesfully, false if wasn't found
Definition at line 118 of file GNERerouterInterval.cpp.
References GNEAttributeCarrier::getID(), GNEDestProbReroute::getNewDestination(), GNEDestProbReroute::getTag(), myDestProbReroutes, toString(), and WRITE_WARNING.
bool GNERerouterInterval::removeRouteProbReroute (const GNERouteProbReroute & rpr)
remove a previously inserted route probability reroute
Returns
true if deletetion was sucesfully, false if wasn't found
Definition at line 143 of file GNERerouterInterval.cpp.
References GNERouteProbReroute::getNewRouteId(), GNERouteProbReroute::getTag(), myRouteProbReroutes, toString(), and WRITE_WARNING.
void GNERerouterInterval::setBegin (double begin)
set begin time
Definition at line 180 of file GNERerouterInterval.cpp.
References myBegin.
Referenced by GNERerouterIntervalDialog::onCmdAccept().
void GNERerouterInterval::setClosingLaneReroutes (const std::vector< GNEClosingLaneReroute > & closingLaneReroutes)
set closing reroutes
Definition at line 216 of file GNERerouterInterval.cpp.
References myClosingLaneReroutes.
Referenced by GNERerouterIntervalDialog::onCmdAccept().
void GNERerouterInterval::setClosingReroutes (const std::vector< GNEClosingReroute > & closingReroutes)
set closing reroutes
Definition at line 222 of file GNERerouterInterval.cpp.
References myClosingReroutes.
Referenced by GNERerouterIntervalDialog::onCmdAccept().
void GNERerouterInterval::setDestProbReroutes (const std::vector< GNEDestProbReroute > & destProbReroutes)
set destiny probability reroutes
Definition at line 228 of file GNERerouterInterval.cpp.
References myDestProbReroutes.
Referenced by GNERerouterIntervalDialog::onCmdAccept().
void GNERerouterInterval::setEnd (double end)
set end time
Definition at line 186 of file GNERerouterInterval.cpp.
References myEnd.
Referenced by GNERerouterIntervalDialog::onCmdAccept().
void GNERerouterInterval::setRouteProbReroutes (const std::vector< GNERouteProbReroute > & rerouteProbabilityReroutes)
set reoute probability reroutes
Definition at line 234 of file GNERerouterInterval.cpp.
References myRouteProbReroutes.
Referenced by GNERerouterIntervalDialog::onCmdAccept().
Field Documentation
double GNERerouterInterval::myBegin protected
begin timeStep
Definition at line 163 of file GNERerouterInterval.h.
Referenced by getBegin(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), and setBegin().
std::vector<GNEClosingLaneReroute> GNERerouterInterval::myClosingLaneReroutes protected
vector with the closingLaneReroutes
Definition at line 172 of file GNERerouterInterval.h.
Referenced by getClosingLaneReroutes(), insertClosinLanegReroutes(), removeClosingLaneReroutes(), and setClosingLaneReroutes().
std::vector<GNEClosingReroute> GNERerouterInterval::myClosingReroutes protected
vector with the closingReroutes
Definition at line 175 of file GNERerouterInterval.h.
Referenced by getClosingReroutes(), insertClosingReroutes(), removeClosingReroutes(), and setClosingReroutes().
std::vector<GNEDestProbReroute> GNERerouterInterval::myDestProbReroutes protected
vector with the destProbReroutes
Definition at line 178 of file GNERerouterInterval.h.
Referenced by getDestProbReroutes(), insertDestProbReroutes(), removeDestProbReroutes(), and setDestProbReroutes().
double GNERerouterInterval::myEnd protected
end timeStep
Definition at line 166 of file GNERerouterInterval.h.
Referenced by getEnd(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), and setEnd().
GNERerouter* GNERerouterInterval::myRerouterParent protected
pointer to rerouter parent
Definition at line 160 of file GNERerouterInterval.h.
Referenced by getRerouterParent(), and operator=().
std::vector<GNERouteProbReroute> GNERerouterInterval::myRouteProbReroutes protected
vector with the routeProbReroutes
Definition at line 181 of file GNERerouterInterval.h.
Referenced by getRouteProbReroutes(), insertRouteProbReroute(), removeRouteProbReroute(), and setRouteProbReroutes().
SumoXMLTag GNERerouterInterval::myTag protected
XML Tag of a rerouter interval.
Definition at line 169 of file GNERerouterInterval.h.
Referenced by getTag().
The documentation for this class was generated from the following files:
GNERerouterInterval.h
GNERerouterInterval.cpp