SUMO - Simulation of Urban MObility: TraCI_Junction Class Reference
TraCI_Junction Class Reference
C++ TraCI client API implementation.
#include <TraCI_Junction.h>
Static Public Member Functions
static TraCIColor getColor (const std::string &poiID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static MSJunction * getJunction (const std::string &id)
static TraCIPosition getPosition (const std::string &junctionID)
static TraCIPositionVector getShape (const std::string &junctionID)
static std::string getType (const std::string &poiID)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
TraCI_Junction & operator= (const TraCI_Junction &src)
invalidated assignment operator
TraCI_Junction ()
invalidated standard constructor
TraCI_Junction (const TraCI_Junction &src)
invalidated copy constructor
Detailed Description
C++ TraCI client API implementation.
Definition at line 52 of file TraCI_Junction.h.
Constructor & Destructor Documentation
TraCI_Junction::TraCI_Junction () private
invalidated standard constructor
TraCI_Junction::TraCI_Junction (const TraCI_Junction & src) private
invalidated copy constructor
Member Function Documentation
static TraCIColor TraCI_Junction::getColor (const std::string & poiID) static
int TraCI_Junction::getIDCount () static
Definition at line 54 of file TraCI_Junction.cpp.
References getIDList().
Referenced by TraCIServerAPI_Junction::processGet().
std::vector< std::string > TraCI_Junction::getIDList () static
Definition at line 47 of file TraCI_Junction.cpp.
References MSNet::getInstance(), MSNet::getJunctionControl(), and NamedObjectCont< T >::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_Junction::processGet().
MSJunction * TraCI_Junction::getJunction (const std::string & id) static
Definition at line 69 of file TraCI_Junction.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), and MSNet::getJunctionControl().
Referenced by getPosition(), TraCIServerAPI_Junction::getPosition(), and getShape().
TraCIPosition TraCI_Junction::getPosition (const std::string & junctionID) static
Definition at line 59 of file TraCI_Junction.cpp.
References getJunction(), and TraCI::makeTraCIPosition().
Referenced by TraCIServerAPI_Junction::processGet().
TraCIPositionVector TraCI_Junction::getShape (const std::string & junctionID) static
Definition at line 64 of file TraCI_Junction.cpp.
References getJunction(), and TraCI::makeTraCIPositionVector().
Referenced by TraCIServerAPI_Junction::processGet().
static std::string TraCI_Junction::getType (const std::string & poiID) static
TraCI_Junction& TraCI_Junction::operator= (const TraCI_Junction & src) private
invalidated assignment operator
static void TraCI_Junction::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
static void TraCI_Junction::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
TraCI_Junction.h
TraCI_Junction.cpp