SUMO - Simulation of Urban MObility: GNERerouterDialog Class Reference
GNERerouterDialog Class Reference
Dialog for edit rerouters.
#include <GNERerouterDialog.h>
Public Member Functions
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
bool checkModifyInterval (const GNERerouterInterval &rerouterInterval, double newBegin, double newEnd) const
check if begin and end of an existent interval can be modified
bool findInterval (double begin, double end) const
check if a interval exists
GNERerouter * getRerouterParent () const
get rerouter parent
GNERerouterDialog (GNERerouter *rerouterParent)
FOX-declaration.
~GNERerouterDialog ()
destructor
FOX-callbacks
event after press accept button
long onCmdAccept (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
long onCmdAddInterval (FXObject *, FXSelector, void *)
add new interval
long onCmdClickedInterval (FXObject *, FXSelector, void *)
remove or edit interval
Protected Member Functions
GNERerouterDialog ()
FOX needs this.
void updateIntervalTable ()
update data table
Protected Attributes
FXButton * myAcceptButton
accept button
FXButton * myAddInterval
button for add new interval
FXButton * myCancelButton
cancel button
FXVerticalFrame * myContentFrame
frame for contents
std::vector< GNERerouterInterval > myCopyOfRerouterIntervals
set with a copy of rerouter intervals
FXTable * myIntervalList
list with intervals
GNERerouter * myRerouterParent
pointer to rerouter parent
FXButton * myResetButton
cancel button
Private Member Functions
GNERerouterDialog (const GNERerouterDialog &)
Invalidated copy constructor.
GNERerouterDialog & operator= (const GNERerouterDialog &)
Invalidated assignment operator.
Detailed Description
Dialog for edit rerouters.
Definition at line 52 of file GNERerouterDialog.h.
Constructor & Destructor Documentation
GNERerouterDialog::GNERerouterDialog (GNERerouter * rerouterParent)
FOX-declaration.
Constructor
Definition at line 60 of file GNERerouterDialog.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonIcon, GUIDesignLabelThick, GUIDesignTableAdditionals, ICON_ADD, MID_GNE_REROUTEDIALOG_ADD_INTERVAL, MID_GNE_REROUTEDIALOG_TABLE_INTERVAL, SUMO_TAG_CLOSING_LANE_REROUTE, and toString().
GNERerouterDialog::~GNERerouterDialog ()
destructor
Definition at line 82 of file GNERerouterDialog.cpp.
GNERerouterDialog::GNERerouterDialog () inline protected
FOX needs this.
Definition at line 92 of file GNERerouterDialog.h.
GNERerouterDialog::GNERerouterDialog (const GNERerouterDialog &) private
Invalidated copy constructor.
Member Function Documentation
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) inherited
change additional dialog header
Definition at line 81 of file GNEAdditionalDialog.cpp.
bool GNERerouterDialog::checkModifyInterval (const GNERerouterInterval & rerouterInterval, double newBegin, double newEnd) const
check if begin and end of an existent interval can be modified
Definition at line 105 of file GNERerouterDialog.cpp.
References GNERerouter::checkOverlapping(), GNERerouterInterval::getRerouterParent(), myCopyOfRerouterIntervals, and myRerouterParent.
Referenced by GNERerouterIntervalDialog::onCmdChangeBeginEnd().
bool GNERerouterDialog::findInterval (double begin, double end) const
check if a interval exists
Definition at line 93 of file GNERerouterDialog.cpp.
References myCopyOfRerouterIntervals.
GNERerouter * GNERerouterDialog::getRerouterParent () const
get rerouter parent
Definition at line 87 of file GNERerouterDialog.cpp.
References myRerouterParent.
Referenced by GNERerouterIntervalDialog::onCmdAccept().
long GNERerouterDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
Implements GNEAdditionalDialog.
Definition at line 135 of file GNERerouterDialog.cpp.
References myCopyOfRerouterIntervals, myRerouterParent, and GNERerouter::setRerouterIntervals().
long GNERerouterDialog::onCmdAddInterval (FXObject * , FXSelector , void *)
add new interval
Definition at line 164 of file GNERerouterDialog.cpp.
References myCopyOfRerouterIntervals, myRerouterParent, and updateIntervalTable().
long GNERerouterDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event after press cancel button
Implements GNEAdditionalDialog.
Definition at line 147 of file GNERerouterDialog.cpp.
long GNERerouterDialog::onCmdClickedInterval (FXObject * , FXSelector , void *)
remove or edit interval
Definition at line 179 of file GNERerouterDialog.cpp.
References myCopyOfRerouterIntervals, and myIntervalList.
long GNERerouterDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event after press reset button
Implements GNEAdditionalDialog.
Definition at line 155 of file GNERerouterDialog.cpp.
References GNERerouter::getRerouterIntervals(), myCopyOfRerouterIntervals, myRerouterParent, and updateIntervalTable().
GNERerouterDialog& GNERerouterDialog::operator= (const GNERerouterDialog &) private
Invalidated assignment operator.
void GNERerouterDialog::updateIntervalTable () protected
update data table
Definition at line 203 of file GNERerouterDialog.cpp.
References GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_REMOVE, myCopyOfRerouterIntervals, myIntervalList, SUMO_ATTR_BEGIN, SUMO_ATTR_END, and toString().
Referenced by onCmdAddInterval(), and onCmdReset().
Field Documentation
FXButton* GNEAdditionalDialog::myAcceptButton protected inherited
accept button
Definition at line 85 of file GNEAdditionalDialog.h.
FXButton* GNERerouterDialog::myAddInterval protected
button for add new interval
Definition at line 98 of file GNERerouterDialog.h.
FXButton* GNEAdditionalDialog::myCancelButton protected inherited
cancel button
Definition at line 88 of file GNEAdditionalDialog.h.
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 82 of file GNEAdditionalDialog.h.
std::vector<GNERerouterInterval> GNERerouterDialog::myCopyOfRerouterIntervals protected
set with a copy of rerouter intervals
Definition at line 104 of file GNERerouterDialog.h.
Referenced by checkModifyInterval(), findInterval(), onCmdAccept(), onCmdAddInterval(), onCmdClickedInterval(), onCmdReset(), and updateIntervalTable().
FXTable* GNERerouterDialog::myIntervalList protected
list with intervals
Definition at line 101 of file GNERerouterDialog.h.
Referenced by onCmdClickedInterval(), and updateIntervalTable().
GNERerouter* GNERerouterDialog::myRerouterParent protected
pointer to rerouter parent
Definition at line 95 of file GNERerouterDialog.h.
Referenced by checkModifyInterval(), getRerouterParent(), onCmdAccept(), onCmdAddInterval(), and onCmdReset().
FXButton* GNEAdditionalDialog::myResetButton protected inherited
cancel button
Definition at line 91 of file GNEAdditionalDialog.h.
The documentation for this class was generated from the following files:
GNERerouterDialog.h
GNERerouterDialog.cpp