SUMO - Simulation of Urban MObility: NWWriter_OpenDrive Class Reference
NWWriter_OpenDrive Class Reference
Exporter writing networks using the openDRIVE format.
#include <NWWriter_OpenDrive.h>
Static Public Member Functions
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into a openDRIVE-file.
Static Protected Member Functions
static void checkLaneGeometries (const NBEdge *e)
check if the lane geometries are compatible with OpenDRIVE assumptions (colinear stop line)
static int getID (const std::string &origID, StringBijection< int > &map, int &lastID)
static std::string getLaneType (SVCPermissions permissions)
static PositionVector getLeftLaneBorder (const NBEdge *edge, int laneIndex=-1)
get the left border of the given lane (the leftmost one by default)
static void writeElevationProfile (const PositionVector &shape, OutputDevice &device, const OutputDevice_String &elevationDevice)
static void writeEmptyCenterLane (OutputDevice &device, const std::string &mark, double markWidth)
static double writeGeomLines (const PositionVector &shape, OutputDevice &device, OutputDevice &elevationDevice, double offset=0)
write geometry as sequence of lines (sumo style)
static double writeGeomPP3 (OutputDevice &device, OutputDevice &elevationDevice, PositionVector init, double length, double offset=0)
write geometry as a single bezier curve (paramPoly3)
static bool writeGeomSmooth (const PositionVector &shape, double speed, OutputDevice &device, OutputDevice &elevationDevice, double straightThresh, double &length)
Detailed Description
Exporter writing networks using the openDRIVE format.
Definition at line 56 of file NWWriter_OpenDrive.h.
Member Function Documentation
void NWWriter_OpenDrive::checkLaneGeometries (const NBEdge * e) static protected
check if the lane geometries are compatible with OpenDRIVE assumptions (colinear stop line)
Definition at line 694 of file NWWriter_OpenDrive.cpp.
References PositionVector::distance2D(), NBEdge::getLaneID(), NBEdge::getLaneShape(), NBEdge::getNumLanes(), NUMERICAL_EPS, PositionVector::sideOffset(), toString(), and WRITE_WARNING.
Referenced by writeNetwork().
int NWWriter_OpenDrive::getID (const std::string & origID, StringBijection< int > & map, int & lastID) static protected
Definition at line 370 of file NWWriter_OpenDrive.cpp.
References StringBijection< T >::get(), StringBijection< T >::hasString(), and StringBijection< T >::insert().
Referenced by writeNetwork().
std::string NWWriter_OpenDrive::getLaneType (SVCPermissions permissions) static protected
Definition at line 380 of file NWWriter_OpenDrive.cpp.
References isRailway(), SVC_BICYCLE, SVC_PASSENGER, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_TRAM, and SVCAll.
Referenced by writeNetwork().
PositionVector NWWriter_OpenDrive::getLeftLaneBorder (const NBEdge * edge, int laneIndex = -1) static protected
get the left border of the given lane (the leftmost one by default)
it would be tempting to use
Definition at line 415 of file NWWriter_OpenDrive.cpp.
References NBEdge::getLaneShape(), NBEdge::getLaneWidth(), NBEdge::getNumLanes(), and PositionVector::move2side().
Referenced by writeNetwork().
void NWWriter_OpenDrive::writeElevationProfile (const PositionVector & shape, OutputDevice & device, const OutputDevice_String & elevationDevice) static protected
Definition at line 672 of file NWWriter_OpenDrive.cpp.
References OutputDevice_String::getString(), and NUMERICAL_EPS.
Referenced by writeNetwork().
void NWWriter_OpenDrive::writeEmptyCenterLane (OutputDevice & device, const std::string & mark, double markWidth) static protected
Definition at line 359 of file NWWriter_OpenDrive.cpp.
Referenced by writeNetwork().
double NWWriter_OpenDrive::writeGeomLines (const PositionVector & shape, OutputDevice & device, OutputDevice & elevationDevice, double offset = 0) static protected
write geometry as sequence of lines (sumo style)
Definition at line 337 of file NWWriter_OpenDrive.cpp.
References PositionVector::angleAt2D(), OutputDevice::closeTag(), Position::distanceTo2D(), MAX2(), OutputDevice::openTag(), POSITION_EPS, OutputDevice::writeAttr(), Position::x(), Position::y(), and Position::z().
Referenced by writeGeomSmooth(), and writeNetwork().
double NWWriter_OpenDrive::writeGeomPP3 (OutputDevice & device, OutputDevice & elevationDevice, PositionVector init, double length, double offset = 0) static protected
write geometry as a single bezier curve (paramPoly3)
Definition at line 442 of file NWWriter_OpenDrive.cpp.
References PositionVector::add(), PositionVector::angleAt2D(), OutputDevice::closeTag(), MAX2(), OutputDevice::openTag(), POSITION_EPS, PositionVector::rotate2D(), OutputDevice::writeAttr(), Position::x(), Position::y(), and Position::z().
Referenced by writeGeomSmooth(), and writeNetwork().
bool NWWriter_OpenDrive::writeGeomSmooth (const PositionVector & shape, double speed, OutputDevice & device, OutputDevice & elevationDevice, double straightThresh, double & length) static protected
Definition at line 538 of file NWWriter_OpenDrive.cpp.
References PositionVector::add(), GeomHelper::angleDiff(), Position::angleTo2D(), bezier(), NBNode::bezierControlPoints(), DEBUGCOND, Position::distanceTo2D(), PositionVector::length2D(), MAX2(), MIN2(), POSITION_EPS, PositionVector::positionAtOffset2D(), RAD2DEG, toString(), writeGeomLines(), and writeGeomPP3().
Referenced by writeNetwork().
void NWWriter_OpenDrive::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into a openDRIVE-file.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 62 of file NWWriter_OpenDrive.cpp.
References NBNodeCont::begin(), NBEdgeCont::begin(), bezier(), NBNode::bezierControlPoints(), checkLaneGeometries(), OutputDevice::closeTag(), DEBUGCOND, DEG2RAD, NBNodeCont::end(), NBEdgeCont::end(), StringUtils::escapeXML(), NBEdge::Connection::fromLane, OptionsCont::getBool(), NBEdge::getConnections(), GeoConvHelper::getConvBoundary(), OutputDevice::getDevice(), NBNetBuilder::getEdgeCont(), GeoConvHelper::getFinal(), OptionsCont::getFloat(), NBEdge::getFromNode(), Named::getID(), getID(), NBNode::getIncomingEdges(), NBEdge::getIncomingEdges(), NBEdge::Connection::getInternalLaneID(), NBEdge::getLaneID(), NBEdge::getLanes(), getLaneType(), NBEdge::getLaneWidth(), getLeftLaneBorder(), NBNetBuilder::getNodeCont(), NBEdge::getNumLanes(), NBEdge::getPermissions(), NBEdge::getSpeed(), NBEdge::getStreetName(), OutputDevice_String::getString(), OptionsCont::getString(), NBEdge::getToNode(), gPrecision, OptionsCont::isSet(), NBEdge::isTurningDirectionAt(), PositionVector::length2D(), MAX2(), OutputDevice::openTag(), POSITION_EPS, OutputDevice::setPrecision(), NBNodeCont::size(), SVC_PEDESTRIAN, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, WRITE_WARNING, writeElevationProfile(), writeEmptyCenterLane(), writeGeomLines(), writeGeomPP3(), writeGeomSmooth(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by NWFrame::writeNetwork().
The documentation for this class was generated from the following files:
NWWriter_OpenDrive.h
NWWriter_OpenDrive.cpp