SUMO - Simulation of Urban MObility: TraCIAPI::SimulationScope Class Reference
TraCIAPI::SimulationScope Class Reference
Scope for interaction with the simulation.
#include <TraCIAPI.h>
Public Member Functions
std::vector< std::string > getArrivedIDList () const
int getArrivedNumber () const
const SubscribedContextValues & getContextSubscriptionResults () const
const SubscribedValues & getContextSubscriptionResults (const std::string &objID) const
SUMOTime getCurrentTime () const
SUMOTime getDeltaT () const
std::vector< std::string > getDepartedIDList () const
int getDepartedNumber () const
std::vector< std::string > getEndingTeleportIDList () const
int getEndingTeleportNumber () const
std::vector< std::string > getLoadedIDList () const
int getLoadedNumber () const
int getMinExpectedNumber () const
TraCIBoundary getNetBoundary () const
std::vector< std::string > getStartingTeleportIDList () const
int getStartingTeleportNumber () const
const SubscribedValues & getSubscriptionResults () const
const TraCIValues & getSubscriptionResults (const std::string &objID) const
SimulationScope (TraCIAPI &parent)
void subscribe (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars) const
void subscribeContext (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars) const
virtual ~SimulationScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
SimulationScope & operator= (const SimulationScope &src)
invalidated assignment operator
SimulationScope (const SimulationScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with the simulation.
Definition at line 473 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::SimulationScope::SimulationScope (TraCIAPI & parent) inline
Definition at line 475 of file TraCIAPI.h.
virtual TraCIAPI::SimulationScope::~SimulationScope () inline virtual
Definition at line 476 of file TraCIAPI.h.
References TraCIAPI::TraCIScopeWrapper::operator=().
TraCIAPI::SimulationScope::SimulationScope (const SimulationScope & src) private
invalidated copy constructor
Member Function Documentation
std::vector< std::string > TraCIAPI::SimulationScope::getArrivedIDList () const
Definition at line 1391 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_ARRIVED_VEHICLES_IDS.
int TraCIAPI::SimulationScope::getArrivedNumber () const
Definition at line 1386 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_ARRIVED_VEHICLES_NUMBER.
const TraCIAPI::SubscribedContextValues & TraCIAPI::SimulationScope::getContextSubscriptionResults () const
Definition at line 1468 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
const TraCIAPI::SubscribedValues & TraCIAPI::SimulationScope::getContextSubscriptionResults (const std::string & objID) const
Definition at line 1474 of file TraCIAPI.cpp.
SUMOTime TraCIAPI::SimulationScope::getCurrentTime () const
Definition at line 1361 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TIME_STEP.
Referenced by TraCITestClient::testAPI().
SUMOTime TraCIAPI::SimulationScope::getDeltaT () const
Definition at line 1416 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_DELTA_T.
std::vector< std::string > TraCIAPI::SimulationScope::getDepartedIDList () const
Definition at line 1381 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_DEPARTED_VEHICLES_IDS.
int TraCIAPI::SimulationScope::getDepartedNumber () const
Definition at line 1376 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_DEPARTED_VEHICLES_NUMBER.
std::vector< std::string > TraCIAPI::SimulationScope::getEndingTeleportIDList () const
Definition at line 1411 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TELEPORT_ENDING_VEHICLES_IDS.
int TraCIAPI::SimulationScope::getEndingTeleportNumber () const
Definition at line 1406 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TELEPORT_ENDING_VEHICLES_NUMBER.
std::vector< std::string > TraCIAPI::SimulationScope::getLoadedIDList () const
Definition at line 1371 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_LOADED_VEHICLES_IDS.
int TraCIAPI::SimulationScope::getLoadedNumber () const
Definition at line 1366 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_LOADED_VEHICLES_NUMBER.
int TraCIAPI::SimulationScope::getMinExpectedNumber () const
Definition at line 1426 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_MIN_EXPECTED_VEHICLES.
TraCIBoundary TraCIAPI::SimulationScope::getNetBoundary () const
Definition at line 1421 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_NET_BOUNDING_BOX.
std::vector< std::string > TraCIAPI::SimulationScope::getStartingTeleportIDList () const
Definition at line 1401 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TELEPORT_STARTING_VEHICLES_IDS.
int TraCIAPI::SimulationScope::getStartingTeleportNumber () const
Definition at line 1396 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TELEPORT_STARTING_VEHICLES_NUMBER.
const TraCIAPI::SubscribedValues & TraCIAPI::SimulationScope::getSubscriptionResults () const
Definition at line 1452 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
const TraCIAPI::TraCIValues & TraCIAPI::SimulationScope::getSubscriptionResults (const std::string & objID) const
Definition at line 1458 of file TraCIAPI.cpp.
SimulationScope& TraCIAPI::SimulationScope::operator= (const SimulationScope & src) private
invalidated assignment operator
void TraCIAPI::SimulationScope::subscribe (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) const
Definition at line 1431 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
void TraCIAPI::SimulationScope::subscribeContext (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) const
Definition at line 1442 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 131 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp