SUMO - Simulation of Urban MObility: GNEDestProbReroute Class Reference
GNEDestProbReroute Class Reference
#include <GNEDestProbReroute.h>
Public Member Functions
GNEEdge * getNewDestination () const
get edge destination
double getProbability () const
get probability
const GNERerouterInterval & getRerouterIntervalParent () const
get rerouter interval parent
SumoXMLTag getTag () const
get tag
GNEDestProbReroute (GNERerouterInterval &rerouterIntervalParent, GNEEdge *newEdgeDestination, double probability)
constructor
bool operator== (const GNEDestProbReroute &destProbReroute) const
overload operator ==
void setNewDestination (GNEEdge *edge)
set edge destination
bool setProbability (double probability)
set probability, if new probability is valid
~GNEDestProbReroute ()
destructor
Protected Attributes
GNEEdge * myNewEdgeDestination
id of new edge destination
double myProbability
probability with which a vehicle will use the given edge as destination
GNERerouterInterval * myRerouterIntervalParent
reference to rerouter interval parent
SumoXMLTag myTag
XML Tag of destiny probability reroute.
Detailed Description
forces the rerouter to assign a new route
Definition at line 51 of file GNEDestProbReroute.h.
Constructor & Destructor Documentation
GNEDestProbReroute::GNEDestProbReroute (GNERerouterInterval & rerouterIntervalParent, GNEEdge * newEdgeDestination, double probability)
constructor
Definition at line 40 of file GNEDestProbReroute.cpp.
References setProbability().
GNEDestProbReroute::~GNEDestProbReroute ()
destructor
Definition at line 50 of file GNEDestProbReroute.cpp.
Member Function Documentation
GNEEdge * GNEDestProbReroute::getNewDestination () const
get edge destination
Definition at line 55 of file GNEDestProbReroute.cpp.
References myNewEdgeDestination.
Referenced by GNERerouterInterval::insertDestProbReroutes(), and GNERerouterInterval::removeDestProbReroutes().
double GNEDestProbReroute::getProbability () const
get probability
Definition at line 67 of file GNEDestProbReroute.cpp.
References myProbability.
const GNERerouterInterval & GNEDestProbReroute::getRerouterIntervalParent () const
get rerouter interval parent
Definition at line 90 of file GNEDestProbReroute.cpp.
References myRerouterIntervalParent.
SumoXMLTag GNEDestProbReroute::getTag () const
get tag
Definition at line 84 of file GNEDestProbReroute.cpp.
References myTag.
Referenced by GNERerouterInterval::insertDestProbReroutes(), and GNERerouterInterval::removeDestProbReroutes().
bool GNEDestProbReroute::operator== (const GNEDestProbReroute & destProbReroute) const
overload operator ==
Definition at line 96 of file GNEDestProbReroute.cpp.
References myNewEdgeDestination, myProbability, and myRerouterIntervalParent.
void GNEDestProbReroute::setNewDestination (GNEEdge * edge)
set edge destination
Definition at line 61 of file GNEDestProbReroute.cpp.
References myNewEdgeDestination.
bool GNEDestProbReroute::setProbability (double probability)
set probability, if new probability is valid
Definition at line 73 of file GNEDestProbReroute.cpp.
References myProbability.
Referenced by GNEDestProbReroute().
Field Documentation
GNEEdge* GNEDestProbReroute::myNewEdgeDestination protected
id of new edge destination
Definition at line 85 of file GNEDestProbReroute.h.
Referenced by getNewDestination(), operator==(), and setNewDestination().
double GNEDestProbReroute::myProbability protected
probability with which a vehicle will use the given edge as destination
Definition at line 88 of file GNEDestProbReroute.h.
Referenced by getProbability(), operator==(), and setProbability().
GNERerouterInterval* GNEDestProbReroute::myRerouterIntervalParent protected
reference to rerouter interval parent
Definition at line 82 of file GNEDestProbReroute.h.
Referenced by getRerouterIntervalParent(), and operator==().
SumoXMLTag GNEDestProbReroute::myTag protected
XML Tag of destiny probability reroute.
Definition at line 91 of file GNEDestProbReroute.h.
Referenced by getTag().
The documentation for this class was generated from the following files:
GNEDestProbReroute.h
GNEDestProbReroute.cpp