SUMO - Simulation of Urban MObility: MSContainer::MSContainerStage_Driving Class Reference
MSContainer::MSContainerStage_Driving Class Reference
#include <MSContainer.h>
Public Member Functions
void abort (MSTransportable *)
abort this stage (TraCI)
virtual void beginEventOutput (const MSTransportable &p, SUMOTime t, OutputDevice &os) const
Called for writing the events output.
virtual void endEventOutput (const MSTransportable &p, SUMOTime t, OutputDevice &os) const
Called for writing the events output (end of an action)
double getAngle (SUMOTime now) const
returns the angle of the transportable
double getArrivalPos () const
const MSEdge & getDestination () const
returns the destination edge
const MSStoppingPlace * getDestinationStop () const
returns the destination stop (if any)
const MSEdge * getEdge () const
Returns the current edge.
double getEdgeAngle (const MSEdge *e, double at) const
get angle of the edge at a certain position
double getEdgePos (SUMOTime now) const
Position getEdgePosition (const MSEdge *e, double at, double offset) const
get position on edge e at length at with orthogonal offset
ConstMSEdgeVector getEdges () const
the edges of the current stage
const MSEdge * getFromEdge () const
Position getLanePosition (const MSLane *lane, double at, double offset) const
get position on lane at length at with orthogonal offset
Position getPosition (SUMOTime now) const
returns the position of the transportable
double getSpeed () const
the speed of the transportable
std::string getStageDescription () const
returns the stage description as a string
StageType getStageType () const
SUMOVehicle * getVehicle () const
The vehicle the person is riding or 0.
SUMOTime getWaitingTime (SUMOTime now) const
time spent waiting for a ride
bool isWaiting4Vehicle () const
Whether the person waits for a vehicle.
bool isWaitingFor (const std::string &line) const
Whether the person waits for a vehicle of the line specified.
MSContainerStage_Driving (const MSEdge &destination, MSStoppingPlace *toStop, const double arrivalPos, const std::vector< std::string > &lines)
constructor
virtual void proceed (MSNet *net, MSTransportable *container, SUMOTime now, Stage *previous)
proceeds to the next step
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual void setSpeed (double)
sets the walking speed (ignored in other stages)
void setVehicle (SUMOVehicle *v)
virtual void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
~MSContainerStage_Driving ()
destructor
Protected Attributes
double myArrivalPos
the position at which we want to arrive
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach by getting transported
MSStoppingPlace *const myDestinationStop
the stop to reach by getting transported (if any)
const std::set< std::string > myLines
the lines to choose from
Position myStopWaitPos
StageType myType
The type of this stage.
SUMOVehicle * myVehicle
The taken vehicle.
const MSEdge * myWaitingEdge
double myWaitingPos
SUMOTime myWaitingSince
The time since which this person is waiting for a ride.
Detailed Description
A "real" stage performing the travelling by a transport system A container is in this stage if it is on a ride or if its waiting for a ride. The given route will be chosen. The travel time is computed by the simulation
Definition at line 77 of file MSContainer.h.
Constructor & Destructor Documentation
MSContainer::MSContainerStage_Driving::MSContainerStage_Driving (const MSEdge & destination, MSStoppingPlace * toStop, const double arrivalPos, const std::vector< std::string > & lines)
constructor
Definition at line 54 of file MSContainer.cpp.
MSContainer::MSContainerStage_Driving::~MSContainerStage_Driving ()
destructor
Definition at line 59 of file MSContainer.cpp.
Member Function Documentation
void MSTransportable::Stage_Driving::abort (MSTransportable * t) virtual inherited
abort this stage (TraCI)
Reimplemented from MSTransportable::Stage.
Definition at line 319 of file MSTransportable.cpp.
References MSTransportable::Stage_Driving::myVehicle.
void MSTransportable::Stage_Driving::beginEventOutput (const MSTransportable & p, SUMOTime t, OutputDevice & os) const virtual inherited
Called for writing the events output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 329 of file MSTransportable.cpp.
References MSTransportable::Stage_Driving::getEdge(), Named::getID(), MSTransportable::getID(), OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Referenced by MSContainer::MSContainerStage_Tranship::getStageDescription().
void MSTransportable::Stage_Driving::endEventOutput (const MSTransportable & p, SUMOTime t, OutputDevice & os) const virtual inherited
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 335 of file MSTransportable.cpp.
References MSTransportable::Stage_Driving::getEdge(), Named::getID(), MSTransportable::getID(), OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Referenced by MSContainer::MSContainerStage_Tranship::getStageDescription().
double MSTransportable::Stage_Driving::getAngle (SUMOTime now) const virtual inherited
returns the angle of the transportable
Implements MSTransportable::Stage.
Definition at line 273 of file MSTransportable.cpp.
References MSVehicle::getAngle(), MSTransportable::Stage::getEdgeAngle(), MSTransportable::Stage_Driving::isWaiting4Vehicle(), M_PI, MSTransportable::Stage_Driving::myVehicle, MSTransportable::Stage_Driving::myWaitingEdge, and MSTransportable::Stage_Driving::myWaitingPos.
double MSTransportable::Stage::getArrivalPos () const inline inherited
Definition at line 89 of file MSTransportable.h.
References MSTransportable::Stage::getAngle(), MSTransportable::Stage::getEdge(), MSTransportable::Stage::getEdgePos(), MSTransportable::Stage::getFromEdge(), MSTransportable::Stage::getPosition(), and MSTransportable::Stage::myArrivalPos.
const MSEdge & MSTransportable::Stage::getDestination () const inherited
returns the destination edge
Definition at line 59 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
Referenced by MSTransportable::Stage_Waiting::getEdges(), MSTransportable::Stage_Driving::getEdges(), MSPModel_Striping::moveInDirectionOnLane(), routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
const MSStoppingPlace* MSTransportable::Stage::getDestinationStop () const inline inherited
returns the destination stop (if any)
Definition at line 85 of file MSTransportable.h.
References MSTransportable::Stage::myDestinationStop.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), proceed(), and MSPerson::MSPersonStage_Driving::proceed().
const MSEdge * MSTransportable::Stage_Driving::getEdge () const virtual inherited
Returns the current edge.
Implements MSTransportable::Stage.
Definition at line 236 of file MSTransportable.cpp.
References MSLane::getEdge(), SUMOVehicle::getLane(), MSTransportable::Stage_Driving::myVehicle, and MSTransportable::Stage_Driving::myWaitingEdge.
Referenced by MSTransportable::Stage_Driving::beginEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), and MSTransportable::Stage_Driving::getEdgePos().
double MSTransportable::Stage::getEdgeAngle (const MSEdge * e, double at) const inherited
get angle of the edge at a certain position
Definition at line 92 of file MSTransportable.cpp.
References MSEdge::getLanes().
Referenced by MSPModel_NonInteracting::PState::getAngle(), CState::getAngle(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), and MSTransportable::Stage::getVehicle().
double MSTransportable::Stage_Driving::getEdgePos (SUMOTime now) const virtual inherited
Implements MSTransportable::Stage.
Definition at line 251 of file MSTransportable.cpp.
References MSTransportable::Stage_Driving::getEdge(), MSEdge::getLength(), SUMOVehicle::getPositionOnLane(), MSTransportable::Stage_Driving::isWaiting4Vehicle(), MIN2(), MSTransportable::Stage_Driving::myVehicle, and MSTransportable::Stage_Driving::myWaitingPos.
Position MSTransportable::Stage::getEdgePosition (const MSEdge * e, double at, double offset) const inherited
get position on edge e at length at with orthogonal offset
Definition at line 82 of file MSTransportable.cpp.
References MSTransportable::Stage::getLanePosition(), and MSEdge::getLanes().
Referenced by MSTransportable::Stage_Waiting::getPosition(), MSTransportable::Stage_Driving::getPosition(), and MSTransportable::Stage::getVehicle().
ConstMSEdgeVector MSTransportable::Stage_Driving::getEdges () const virtual inherited
the edges of the current stage
Implements MSTransportable::Stage.
Definition at line 311 of file MSTransportable.cpp.
References MSTransportable::Stage::getDestination(), and MSTransportable::Stage_Driving::getFromEdge().
const MSEdge * MSTransportable::Stage_Driving::getFromEdge () const virtual inherited
Implements MSTransportable::Stage.
Definition at line 245 of file MSTransportable.cpp.
References MSTransportable::Stage_Driving::myWaitingEdge.
Referenced by MSTransportable::Stage_Driving::getEdges(), routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
Position MSTransportable::Stage::getLanePosition (const MSLane * lane, double at, double offset) const inherited
get position on lane at length at with orthogonal offset
Definition at line 87 of file MSTransportable.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::positionAtOffset().
Referenced by CState::computeTranshipTime(), MSTransportable::Stage::getEdgePosition(), MSPModel_NonInteracting::PState::getPosition(), MSPModel_Striping::PState::getPosition(), and MSTransportable::Stage::getVehicle().
Position MSTransportable::Stage_Driving::getPosition (SUMOTime now) const virtual inherited
returns the position of the transportable
Implements MSTransportable::Stage.
Definition at line 261 of file MSTransportable.cpp.
References MSTransportable::Stage::getEdgePosition(), SUMOVehicle::getPosition(), Position::INVALID, MSTransportable::Stage_Driving::isWaiting4Vehicle(), MSTransportable::Stage_Driving::myStopWaitPos, MSTransportable::Stage_Driving::myVehicle, MSTransportable::Stage_Driving::myWaitingEdge, MSTransportable::Stage_Driving::myWaitingPos, and MSTransportable::ROADSIDE_OFFSET.
double MSTransportable::Stage_Driving::getSpeed () const virtual inherited
the speed of the transportable
Implements MSTransportable::Stage.
Definition at line 305 of file MSTransportable.cpp.
References SUMOVehicle::getSpeed(), MSTransportable::Stage_Driving::isWaiting4Vehicle(), and MSTransportable::Stage_Driving::myVehicle.
std::string MSContainer::MSContainerStage_Driving::getStageDescription () const virtual
returns the stage description as a string
Implements MSTransportable::Stage.
Definition at line 88 of file MSContainer.cpp.
References MSTransportable::Stage_Driving::isWaiting4Vehicle(), joinToString(), and MSTransportable::Stage_Driving::myLines.
StageType MSTransportable::Stage::getStageType () const inline inherited
Definition at line 105 of file MSTransportable.h.
References MSTransportable::Stage::getStageDescription(), MSTransportable::Stage::myType, and MSTransportable::Stage::proceed().
Referenced by MSTransportable::getStageType().
SUMOVehicle* MSTransportable::Stage_Driving::getVehicle () const inline virtual inherited
The vehicle the person is riding or 0.
Reimplemented from MSTransportable::Stage.
Definition at line 327 of file MSTransportable.h.
References MSTransportable::Stage::getEdges(), MSTransportable::Stage::getSpeed(), and MSTransportable::Stage::getWaitingTime().
SUMOTime MSTransportable::Stage_Driving::getWaitingTime (SUMOTime now) const virtual inherited
time spent waiting for a ride
Implements MSTransportable::Stage.
Definition at line 299 of file MSTransportable.cpp.
References MSTransportable::Stage_Driving::isWaiting4Vehicle(), and MSTransportable::Stage_Driving::myWaitingSince.
bool MSTransportable::Stage_Driving::isWaiting4Vehicle () const virtual inherited
Whether the person waits for a vehicle.
Reimplemented from MSTransportable::Stage.
Definition at line 293 of file MSTransportable.cpp.
References MSTransportable::Stage_Driving::myVehicle.
Referenced by MSTransportable::Stage_Driving::getAngle(), MSTransportable::Stage_Driving::getEdgePos(), MSTransportable::Stage_Driving::getPosition(), MSTransportable::Stage_Driving::getSpeed(), getStageDescription(), MSPerson::MSPersonStage_Driving::getStageDescription(), and MSTransportable::Stage_Driving::getWaitingTime().
bool MSTransportable::Stage_Driving::isWaitingFor (const std::string & line) const virtual inherited
Whether the person waits for a vehicle of the line specified.
Reimplemented from MSTransportable::Stage.
Definition at line 287 of file MSTransportable.cpp.
References MSTransportable::Stage_Driving::myLines.
void MSContainer::MSContainerStage_Driving::proceed (MSNet * net, MSTransportable * container, SUMOTime now, Stage * previous) virtual
proceeds to the next step
Implements MSTransportable::Stage.
Definition at line 63 of file MSContainer.cpp.
References MSInsertionControl::add(), SUMOVehicle::addContainer(), MSEdge::addContainer(), MSTransportableControl::addWaiting(), DEPART_CONTAINER_TRIGGERED, SUMOVehicleParameter::departProcedure, MSNet::getContainerControl(), MSTransportable::Stage::getDestinationStop(), MSTransportable::Stage::getEdge(), MSLane::getEdge(), MSTransportable::Stage::getEdgePos(), MSTransportable::getID(), MSNet::getInsertionControl(), MSStoppingPlace::getLane(), SUMOVehicle::getParameter(), MSNet::getVehicleControl(), MSVehicleControl::getWaitingVehicle(), SUMOVehicle::hasDeparted(), MSTransportable::Stage_Driving::myLines, MSTransportable::Stage_Driving::myVehicle, MSTransportable::Stage_Driving::myWaitingEdge, MSTransportable::Stage_Driving::myWaitingPos, MSTransportable::Stage_Driving::myWaitingSince, MSEdge::removeContainer(), MSVehicleControl::removeWaiting(), and MSVehicleControl::unregisterOneWaitingForContainer().
void MSContainer::MSContainerStage_Driving::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 100 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::Stage::getDestination(), MSTransportable::Stage_Driving::getFromEdge(), MSTransportable::getID(), MSTransportable::Stage_Driving::myLines, OutputDevice::openTag(), SUMO_ATTR_FROM, SUMO_ATTR_LINES, SUMO_ATTR_TO, and OutputDevice::writeAttr().
Referenced by MSContainer::MSContainerStage_Tranship::getStageDescription().
void MSTransportable::Stage::setArrived (SUMOTime now) inherited
logs end of the step
Definition at line 72 of file MSTransportable.cpp.
References MSTransportable::Stage::myArrived.
Referenced by MSContainer::proceed(), MSPerson::proceed(), and MSTransportable::Stage::setSpeed().
void MSTransportable::Stage::setDeparted (SUMOTime now) inherited
logs end of the step
Definition at line 65 of file MSTransportable.cpp.
References MSTransportable::Stage::myDeparted.
Referenced by MSTransportable::getVehicleType(), and MSTransportable::Stage::setSpeed().
virtual void MSTransportable::Stage::setSpeed (double) inline virtual inherited
sets the walking speed (ignored in other stages)
Reimplemented in MSPerson::MSPersonStage_Walking.
Definition at line 119 of file MSTransportable.h.
References MSTransportable::Stage::isWaitingFor(), MSTransportable::Stage::setArrived(), and MSTransportable::Stage::setDeparted().
Referenced by MSTransportable::getVehicle().
void MSTransportable::Stage_Driving::setVehicle (SUMOVehicle * v) inline inherited
Definition at line 338 of file MSTransportable.h.
References MSTransportable::Stage::beginEventOutput(), and MSTransportable::Stage::endEventOutput().
void MSContainer::MSContainerStage_Driving::tripInfoOutput (OutputDevice & os) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 94 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::Stage::myArrived, MSTransportable::Stage::myDeparted, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Referenced by MSContainer::MSContainerStage_Tranship::getStageDescription().
Field Documentation
double MSTransportable::Stage::myArrivalPos protected inherited
the position at which we want to arrive
Definition at line 190 of file MSTransportable.h.
Referenced by MSPerson::MSPersonStage_Walking::computeAverageSpeed(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage::getArrivalPos(), MSPerson::MSPersonStage_Walking::getArrivalPos(), MSContainer::MSContainerStage_Tranship::getArrivalPos(), MSTransportable::Stage_Waiting::getEdgePos(), and MSTransportable::Stage_Waiting::getPosition().
SUMOTime MSTransportable::Stage::myArrived protected inherited
the time at which this stage ended
Definition at line 196 of file MSTransportable.h.
Referenced by MSTransportable::Stage::setArrived(), tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
SUMOTime MSTransportable::Stage::myDeparted protected inherited
the time at which this stage started
Definition at line 193 of file MSTransportable.h.
Referenced by MSTransportable::Stage::setDeparted(), tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
const MSEdge& MSTransportable::Stage::myDestination protected inherited
the next edge to reach by getting transported
Definition at line 184 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage::getDestination(), MSTransportable::Stage_Waiting::getEdge(), MSTransportable::Stage_Waiting::getFromEdge(), and MSTransportable::Stage_Waiting::getPosition().
MSStoppingPlace* const MSTransportable::Stage::myDestinationStop protected inherited
the stop to reach by getting transported (if any)
Definition at line 187 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getDestinationStop(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and MSContainer::MSContainerStage_Tranship::moveToNextEdge().
const std::set<std::string> MSTransportable::Stage_Driving::myLines protected inherited
the lines to choose from
Definition at line 356 of file MSTransportable.h.
Referenced by getStageDescription(), MSPerson::MSPersonStage_Driving::getStageDescription(), MSTransportable::Stage_Driving::isWaitingFor(), proceed(), MSPerson::MSPersonStage_Driving::proceed(), routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
Position MSTransportable::Stage_Driving::myStopWaitPos protected inherited
Definition at line 365 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Driving::getPosition(), and MSPerson::MSPersonStage_Driving::proceed().
StageType MSTransportable::Stage::myType protected inherited
The type of this stage.
Definition at line 199 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getStageType(), MSTransportable::Stage_Waiting::routeOutput(), and MSTransportable::Stage_Waiting::tripInfoOutput().
SUMOVehicle* MSTransportable::Stage_Driving::myVehicle protected inherited
The taken vehicle.
Definition at line 359 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Driving::abort(), MSTransportable::Stage_Driving::getAngle(), MSTransportable::Stage_Driving::getEdge(), MSTransportable::Stage_Driving::getEdgePos(), MSTransportable::Stage_Driving::getPosition(), MSTransportable::Stage_Driving::getSpeed(), MSTransportable::Stage_Driving::isWaiting4Vehicle(), proceed(), and MSPerson::MSPersonStage_Driving::proceed().
const MSEdge* MSTransportable::Stage_Driving::myWaitingEdge protected inherited
Definition at line 364 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Driving::getAngle(), MSTransportable::Stage_Driving::getEdge(), MSTransportable::Stage_Driving::getFromEdge(), MSTransportable::Stage_Driving::getPosition(), proceed(), and MSPerson::MSPersonStage_Driving::proceed().
double MSTransportable::Stage_Driving::myWaitingPos protected inherited
Definition at line 361 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Driving::getAngle(), MSTransportable::Stage_Driving::getEdgePos(), MSTransportable::Stage_Driving::getPosition(), proceed(), and MSPerson::MSPersonStage_Driving::proceed().
SUMOTime MSTransportable::Stage_Driving::myWaitingSince protected inherited
The time since which this person is waiting for a ride.
Definition at line 363 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Driving::getWaitingTime(), proceed(), and MSPerson::MSPersonStage_Driving::proceed().
The documentation for this class was generated from the following files:
MSContainer.h
MSContainer.cpp