SUMO - Simulation of Urban MObility: GNEAdditionalHandler Class Reference
GNEAdditionalHandler Class Reference
Builds trigger objects for GNENet (busStops, chargingStations, detectors, etc..)
#include <GNEAdditionalHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
GNEAdditionalHandler (const std::string &file, GNEViewNet *viewNet)
Constructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~GNEAdditionalHandler ()
Destructor.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
parsing methods
These methods parse the attributes for each of the described trigger and call the according methods to build the trigger
void parseAndBuildVaporizer (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Builds a vaporization.
void parseAndBuildVariableSpeedSign (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Variable Speed Signal (lane speed trigger)
void parseAndBuildRerouter (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a rerouter.
void parseAndBuildBusStop (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a bus stop.
void parseAndBuildContainerStop (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a container stop.
void parseAndBuildChargingStation (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a charging station.
void parseAndBuildCalibrator (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a mesoscopic or microscopic calibrator.
void parseAndBuildDetectorE1 (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a induction loop detector (E1)
void parseAndBuildDetectorE2 (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a lane area detector (E2)
void parseAndBuildDetectorE3 (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a multi entry exit detector (E3)
void parseAndBuildDetectorEntry (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Entry detector.
void parseAndBuildDetectorExit (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Exit detector.
void parseAndBuildRouteProbe (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds routeProbe.
void parseCalibratorRoute (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses route values of Calibrators.
void parseCalibratorVehicleType (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses vehicle type values of Calibrators.
void parseCalibratorFlow (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses flow values of Calibrators.
void parseVariableSpeedSignStep (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses step values of VariableSpeedSigns.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
building methods
Called with parsed values, these methods build the trigger.
GNEViewNet * myViewNet
pointer to View's Net
GNEDetectorE3 * myE3Parent
Pointer to the last inserted E3.
GNECalibrator * myCalibratorParent
Pointer to the last inserted Calibrator.
GNEVariableSpeedSign * myVariableSpeedSignParent
Pointer to the last inserted variableSpeedSign.
GNERerouterInterval * rerouterIntervalToInsertValues
pointer to rerouterInterval in which insert GNEClosingReroute, GNEDestProbReroute, etc.
SumoXMLTag myLastTag
last used Tag
std::vector< GNECalibratorVehicleType > myLoadingCalibratorVehicleTypes
vector in wich save calibratorVehicleTypes during loading calibrators
std::string getFileName (const SUMOSAXAttributes &attrs, const std::string &base, const bool allowEmpty=false)
Helper method to obtain the filename.
double getPosition (const SUMOSAXAttributes &attrs, GNELane &lane, const std::string &tt, const std::string &tid)
extracts the position, checks whether it shall be mirrored and checks whether it is within the lane.
bool checkStopPos (double &startPos, double &endPos, const double laneLength, const double minLength, const bool friendlyPos)
check if the position of an stoppingPlace over a lane is valid
void resetLastTag ()
reset last Tag and clear non-valid Additionals (For example, created E3 withouts Entry/Exit childs)
static bool buildAdditional (GNEViewNet *viewNet, SumoXMLTag tag, std::map< SumoXMLAttr, std::string > values)
Build additionals.
static bool buildBusStop (GNEViewNet *viewNet, const std::string &id, GNELane *lane, double startPos, double endPos, const std::vector< std::string > &lines)
Builds a bus stop.
static bool buildContainerStop (GNEViewNet *viewNet, const std::string &id, GNELane *lane, double startPos, double endPos, const std::vector< std::string > &lines)
Builds a container stop.
static bool buildChargingStation (GNEViewNet *viewNet, const std::string &id, GNELane *lane, double startPos, double endPos, double chargingPower, double efficiency, bool chargeInTransit, double chargeDelay)
Builds a charging Station.
static bool buildDetectorE1 (GNEViewNet *viewNet, const std::string &id, GNELane *lane, double pos, double freq, const std::string &filename, bool splitByType)
Builds a induction loop detector (E1)
static bool buildDetectorE2 (GNEViewNet *viewNet, const std::string &id, GNELane *lane, double pos, double length, double freq, const std::string &filename, bool cont, const double timeThreshold, double speedThreshold, double jamThreshold)
Builds a lane Area Detector (E2)
static bool buildDetectorE3 (GNEViewNet *viewNet, const std::string &id, Position pos, double freq, const std::string &filename, const double timeThreshold, double speedThreshold)
Builds a multi entry exit detector (E3)
static bool buildDetectorEntry (GNEViewNet *viewNet, GNEDetectorE3 *E3Parent, GNELane *lane, double pos)
Builds a entry detector (E3)
static bool buildDetectorExit (GNEViewNet *viewNet, GNEDetectorE3 *E3Parent, GNELane *lane, double pos)
Builds a exit detector (E3)
static bool buildCalibrator (GNEViewNet *viewNet, const std::string &id, GNELane *lane, double pos, const std::string &outfile, double freq, const std::vector< GNECalibratorRoute > &calibratorRoutes, const std::vector< GNECalibratorFlow > &calibratorFlows, const std::vector< GNECalibratorVehicleType > &calibratorVehicleTypes)
builds a microscopic calibrator
static bool buildRerouter (GNEViewNet *viewNet, const std::string &id, Position pos, const std::vector< GNEEdge * > &edges, double prob, const std::string &file, bool off)
builds a rerouter
static bool buildRouteProbe (GNEViewNet *viewNet, const std::string &id, GNEEdge *edge, double freq, const std::string &file, double begin)
builds a Route probe
static bool buildVariableSpeedSign (GNEViewNet *viewNet, const std::string &id, Position pos, const std::vector< GNELane * > &destLanes, const std::string &file, const std::vector< GNEVariableSpeedSignStep > &steps)
Builds a VariableSpeedSign (lane speed trigger)
static bool buildVaporizer (GNEViewNet *viewNet, GNEEdge *edge, double startTime, double end)
Builds a vaporizer (lane speed trigger)
bool checkAdditionalParent (SumoXMLTag currentTag)
used to check hierarchy of aditionals with parents and childs (for example, E3)
template<typename T >
static T getParsedAttribute (const SUMOSAXAttributes &attrs, const char *objectid, SumoXMLTag tag, SumoXMLAttr attribute, bool &abort, bool report=true)
get parsed attribute of XML and show warnings if there are problems
bool getFriendlyPosition (const SUMOSAXAttributes &attrs, const char *objectid)
get special attribute friendly position, used in stopping places
GNECalibratorFlow::TypeOfFlow getTypeOfFlowDistribution (std::string flowID, double vehsPerHour, double period, double probability)
get a error message, if configuration of flow distribution is invalid
Detailed Description
Builds trigger objects for GNENet (busStops, chargingStations, detectors, etc..)
Definition at line 62 of file GNEAdditionalHandler.h.
Constructor & Destructor Documentation
GNEAdditionalHandler::GNEAdditionalHandler (const std::string & file, GNEViewNet * viewNet)
Constructor.
Definition at line 63 of file GNEAdditionalHandler.cpp.
GNEAdditionalHandler::~GNEAdditionalHandler ()
Destructor.
Definition at line 74 of file GNEAdditionalHandler.cpp.
Member Function Documentation
bool GNEAdditionalHandler::buildAdditional (GNEViewNet * viewNet, SumoXMLTag tag, std::map< SumoXMLAttr, std::string > values) static
Build additionals.
Parameters
[in] viewNet pointer to viewNet in wich additional will be created
[in] tag tag of the additiona lto create
[in] values map with the attributes and values of the additional to create
Returns
true if was sucesfully created, false in other case
Definition at line 723 of file GNEAdditionalHandler.cpp.
References buildBusStop(), buildCalibrator(), buildChargingStation(), buildContainerStop(), buildDetectorE1(), buildDetectorE2(), buildDetectorE3(), buildDetectorEntry(), buildDetectorExit(), buildRerouter(), buildRouteProbe(), buildVaporizer(), buildVariableSpeedSign(), GNEViewNet::getNet(), GNE_ATTR_PARENT, GeomConvHelper::parseShapeReporting(), GNENet::retrieveAdditional(), GNENet::retrieveEdge(), GNENet::retrieveLane(), SUMO_ATTR_BEGIN, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONT, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_END, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_LENGTH, SUMO_ATTR_LINES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_POSITION, SUMO_ATTR_PROB, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::addAdditional().
bool GNEAdditionalHandler::buildBusStop (GNEViewNet * viewNet, const std::string & id, GNELane * lane, double startPos, double endPos, const std::vector< std::string > & lines) static
Builds a bus stop.
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the bus stop
[in] lane The lane the bus stop is placed on
[in] startPos Begin position of the bus stop on the lane
[in] endPos End position of the bus stop on the lane
[in] lines Names of the bus lines that halt on this bus stop
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the bus stop can not be added to the net (is duplicate)
Definition at line 942 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_BUS_STOP, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildBusStop().
bool GNEAdditionalHandler::buildCalibrator (GNEViewNet * viewNet, const std::string & id, GNELane * lane, double pos, const std::string & outfile, double freq, const std::vector< GNECalibratorRoute > & calibratorRoutes, const std::vector< GNECalibratorFlow > & calibratorFlows, const std::vector< GNECalibratorVehicleType > & calibratorVehicleTypes) static
builds a microscopic calibrator
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the calibrator
[in] lane The lane the calibrator is placed at
[in] pos The position on the edge the calibrator lies at
[in] outfile te file in which write results
[in] calibratorRoutes routes of calibrator
[in] calibratorFlows flows of calibrator
[in] calibratorVehicleTypes vehicleTypes of calibrator
Returns
true if was sucesfully created, false in other case
Todo:
Is the position correct/needed
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the entry detector can not be added to the net (is duplicate)
Definition at line 1085 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_CALIBRATOR, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildCalibrator().
bool GNEAdditionalHandler::buildChargingStation (GNEViewNet * viewNet, const std::string & id, GNELane * lane, double startPos, double endPos, double chargingPower, double efficiency, bool chargeInTransit, double chargeDelay) static
Builds a charging Station.
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the charging Station
[in] lane The lane the charging Station is placed on
[in] startPos Begin position of the charging Station on the lane
[in] endPos End position of the charging Station on the lane
[in] chargingPower power charged in every timeStep
[in] efficiency efficiency of the charge
[in] chargeInTransit enable or disable charge in transit
[in] chargeDelay delay in the charge
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the charging Station can not be added to the net (is duplicate)
Definition at line 972 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_CHARGING_STATION, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildChargingStation().
bool GNEAdditionalHandler::buildContainerStop (GNEViewNet * viewNet, const std::string & id, GNELane * lane, double startPos, double endPos, const std::vector< std::string > & lines) static
Builds a container stop.
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the container stop
[in] lane The lane the container stop is placed on
[in] startPos Begin position of the container stop on the lane
[in] endPos End position of the container stop on the lane
[in] lines Names of the bus lines that halt on this container stop
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the container stop can not be added to the net (is duplicate)
Definition at line 957 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_CONTAINER_STOP, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildContainerStop().
bool GNEAdditionalHandler::buildDetectorE1 (GNEViewNet * viewNet, const std::string & id, GNELane * lane, double pos, double freq, const std::string & filename, bool splitByType) static
Builds a induction loop detector (E1)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the detector
[in] lane The lane the detector is placed on
[in] pos position of the detector on the lane
[in] freq the aggregation period the values the detector collects shall be summed up.
[in] filename The path to the output file.
[in] splitByType If set, the collected values will be additionally reported on per-vehicle type base.
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the detector can not be added to the net (is duplicate)
Definition at line 987 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_E1DETECTOR, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildDetectorE1().
bool GNEAdditionalHandler::buildDetectorE2 (GNEViewNet * viewNet, const std::string & id, GNELane * lane, double pos, double length, double freq, const std::string & filename, bool cont, const double timeThreshold, double speedThreshold, double jamThreshold) static
Builds a lane Area Detector (E2)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the detector
[in] lane The lane the detector is placed on
[in] pos position of the detector on the lane
Definition at line 1002 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_E2DETECTOR, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildDetectorE2().
bool GNEAdditionalHandler::buildDetectorE3 (GNEViewNet * viewNet, const std::string & id, Position pos, double freq, const std::string & filename, const double timeThreshold, double speedThreshold) static
Builds a multi entry exit detector (E3)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the detector
[in] pos position of the detector in the map
[in] freq the aggregation period the values the detector collects shall be summed up.
[in] filename The path to the output file.
[in] timeThreshold The time-based threshold that describes how much time has to pass until a vehicle is recognized as halting
[in] speedThreshold The speed-based threshold that describes how slow a vehicle has to be to be recognized as halting
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the detector can not be added to the net (is duplicate)
Definition at line 1018 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_E3DETECTOR, toString(), and WRITE_WARNING.
Referenced by buildAdditional().
bool GNEAdditionalHandler::buildDetectorEntry (GNEViewNet * viewNet, GNEDetectorE3 * E3Parent, GNELane * lane, double pos) static
Builds a entry detector (E3)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] E3Parent pointer to E3 detector parent
[in] lane The lane in which the entry detector is placed on
[in] pos position of the entry detector on the lane
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the entry detector can not be added to the net (invalid parent or lane)
Definition at line 1033 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEAttributeCarrier::getID(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_DET_ENTRY, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANE, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildDetectorEntry().
bool GNEAdditionalHandler::buildDetectorExit (GNEViewNet * viewNet, GNEDetectorE3 * E3Parent, GNELane * lane, double pos) static
Builds a exit detector (E3)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] E3Parent pointer to E3 detector parent
[in] lane The lane in which the exit detector is placed on
[in] pos position of the exit detector on the lane
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the exit detector can not be added to the net (invalid parent or lane
Definition at line 1059 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEAttributeCarrier::getID(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANE, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildDetectorExit().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 188 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
bool GNEAdditionalHandler::buildRerouter (GNEViewNet * viewNet, const std::string & id, Position pos, const std::vector< GNEEdge * > & edges, double prob, const std::string & file, bool off) static
builds a rerouter
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the rerouter
[in] pos position of the rerouter in the map
[in] edges The edges the rerouter is placed at
[in] prob The probability the rerouter reoutes vehicles with
[in] file The file to read the reroute definitions from
Returns
true if was sucesfully created, false in other case
Definition at line 1102 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_REROUTER, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildRerouter().
bool GNEAdditionalHandler::buildRouteProbe (GNEViewNet * viewNet, const std::string & id, GNEEdge * edge, double freq, const std::string & file, double begin) static
builds a Route probe
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the routeprobe
[in] edge The edges the routeprobe is placed at
[in] freq the aggregation period the values the routeprobe collects shall be summed up.
[in] file The file to read the routeprobe definitions from
[in] begin The time at which to start generating output
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the entry detector can not be added to the net (is duplicate)
Definition at line 1117 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_ROUTEPROBE, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildRouteProbe().
bool GNEAdditionalHandler::buildVaporizer (GNEViewNet * viewNet, GNEEdge * edge, double startTime, double end) static
Builds a vaporizer (lane speed trigger)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] edge edge in which tis vaporizer is placed
[in] startTime time in which this vaporizer start
[in] end time in which this vaporizer ends
Returns
true if was sucesfully created, false in other case
Exceptions
ProcessError If the XML definition file is errornous
Definition at line 1147 of file GNEAdditionalHandler.cpp.
References GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_VAPORIZER, and toString().
Referenced by buildAdditional(), and parseAndBuildVaporizer().
bool GNEAdditionalHandler::buildVariableSpeedSign (GNEViewNet * viewNet, const std::string & id, Position pos, const std::vector< GNELane * > & destLanes, const std::string & file, const std::vector< GNEVariableSpeedSignStep > & steps) static
Builds a VariableSpeedSign (lane speed trigger)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] id The id of the lane speed trigger
[in] destLanes List of lanes affected by this speed trigger
[in] file Name of the file to read the speeds to set from
[in] steps Step and speed values of variable speed signal
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the entry detector can not be added to the net (is duplicate)
Definition at line 1132 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_VSS, toString(), and WRITE_WARNING.
Referenced by buildAdditional(), and parseAndBuildVariableSpeedSign().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 171 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
bool GNEAdditionalHandler::checkAdditionalParent (SumoXMLTag currentTag) protected
used to check hierarchy of aditionals with parents and childs (for example, E3)
Definition at line 1402 of file GNEAdditionalHandler.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myCalibratorParent, myE3Parent, myLastTag, myVariableSpeedSignParent, SUMO_TAG_CALIBRATOR, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E3DETECTOR, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, SUMO_TAG_STEP, SUMO_TAG_VTYPE, toString(), and WRITE_WARNING.
Referenced by myStartElement().
bool GNEAdditionalHandler::checkStopPos (double & startPos, double & endPos, const double laneLength, const double minLength, const bool friendlyPos)
check if the position of an stoppingPlace over a lane is valid
Parameters
[in] startPos Start position of stoppingPlace
[in] endPos End position of stoppingPlace
[in] laneLength Length of the lane
[in] minLength Min length of the stoppingPlace
[in] friendlyPos Attribute of stoppingPlace
Returns
true if the stoppingPlace position is valid, false in otherweise
Definition at line 1198 of file GNEAdditionalHandler.cpp.
Referenced by parseAndBuildBusStop(), parseAndBuildChargingStation(), and parseAndBuildContainerStop().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 122 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 207 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 213 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 82 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
std::string GNEAdditionalHandler::getFileName (const SUMOSAXAttributes & attrs, const std::string & base, const bool allowEmpty = false)
Helper method to obtain the filename.
Parameters
[in] attrs The attributes to obtain the file name from
[in] base The base path (the path the loaded additional file lies in)
Returns
The (expanded) path to the named file
Todo:
Recheck usage of the helper class
Definition at line 1157 of file GNEAdditionalHandler.cpp.
References FileHelpers::getConfigurationRelative(), SUMOSAXAttributes::getOpt(), FileHelpers::isAbsolute(), SUMO_ATTR_FILE, and WRITE_WARNING.
bool GNEAdditionalHandler::getFriendlyPosition (const SUMOSAXAttributes & attrs, const char * objectid) private
get special attribute friendly position, used in stopping places
Definition at line 1355 of file GNEAdditionalHandler.cpp.
References SUMOSAXAttributes::getOpt(), and SUMO_ATTR_FRIENDLY_POS.
Referenced by parseAndBuildBusStop(), parseAndBuildChargingStation(), and parseAndBuildContainerStop().
template<typename T > T GNEAdditionalHandler::getParsedAttribute (const SUMOSAXAttributes & attrs, const char * objectid, SumoXMLTag tag, SumoXMLAttr attribute, bool & abort, bool report = true) static private
get parsed attribute of XML and show warnings if there are problems
Definition at line 1235 of file GNEAdditionalHandler.cpp.
References SUMOSAXAttributes::get(), GNEAttributeCarrier::getAttributeType(), SUMOSAXAttributes::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNEAttributeCarrier::isFilename(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isPositive(), GNEAttributeCarrier::isTime(), GNEAttributeCarrier::isValidFilename(), SUMO_ATTR_COLOR, SUMO_ATTR_GUISHAPE, SUMO_ATTR_VCLASS, toString(), and WRITE_WARNING.
double GNEAdditionalHandler::getPosition (const SUMOSAXAttributes & attrs, GNELane & lane, const std::string & tt, const std::string & tid)
extracts the position, checks whether it shall be mirrored and checks whether it is within the lane.
Parameters
[in] attrs The attributes to obtain the position from
[in] lane The lane the position shall be valid for
[in] tt The trigger type (for user output)
[in] tid The trigger id (for user output)
Returns
The position on the lane
Exceptions
InvalidArgument If the position is beyond the lane
Definition at line 1176 of file GNEAdditionalHandler.cpp.
References SUMOSAXAttributes::get(), GNEAttributeCarrier::getID(), GNELane::getLaneShapeLength(), SUMOSAXAttributes::getOpt(), SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_POSITION, and WRITE_WARNING.
GNECalibratorFlow::TypeOfFlow GNEAdditionalHandler::getTypeOfFlowDistribution (std::string flowID, double vehsPerHour, double period, double probability) private
get a error message, if configuration of flow distribution is invalid
Definition at line 1362 of file GNEAdditionalHandler.cpp.
References GNECalibratorFlow::GNE_CALIBRATORFLOW_INVALID, GNECalibratorFlow::GNE_CALIBRATORFLOW_PERIOD, GNECalibratorFlow::GNE_CALIBRATORFLOW_PROBABILITY, GNECalibratorFlow::GNE_CALIBRATORFLOW_VEHSPERHOUR, SUMO_ATTR_PERIOD, SUMO_ATTR_PROB, SUMO_ATTR_VEHSPERHOUR, SUMO_TAG_FLOW, toString(), and WRITE_WARNING.
Referenced by parseCalibratorFlow().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 223 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, NIXMLEdgesHandler, MSCalibrator, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, GNEPoly::GNEPolyHandler, and ROMARouteHandler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), NLHandler::networkVersion(), and SUMOSAXReader::parseNext().
void GNEAdditionalHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 78 of file GNEAdditionalHandler.cpp.
References checkAdditionalParent(), myCalibratorParent, myE3Parent, myVariableSpeedSignParent, parseAndBuildBusStop(), parseAndBuildCalibrator(), parseAndBuildChargingStation(), parseAndBuildContainerStop(), parseAndBuildDetectorE1(), parseAndBuildDetectorE2(), parseAndBuildDetectorE3(), parseAndBuildDetectorEntry(), parseAndBuildDetectorExit(), parseAndBuildRerouter(), parseAndBuildRouteProbe(), parseAndBuildVaporizer(), parseAndBuildVariableSpeedSign(), parseCalibratorFlow(), parseCalibratorRoute(), parseCalibratorVehicleType(), parseVariableSpeedSignStep(), SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_INDUCTION_LOOP, SUMO_TAG_LANE_AREA_DETECTOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, and SUMO_TAG_VTYPE.
void GNEAdditionalHandler::parseAndBuildBusStop (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a bus stop.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 490 of file GNEAdditionalHandler.cpp.
References buildBusStop(), checkStopPos(), getFriendlyPosition(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastTag, myViewNet, POSITION_EPS, GNENet::retrieveLane(), SUMO_ATTR_ENDPOS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_LINES, SUMO_ATTR_STARTPOS, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildCalibrator (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a mesoscopic or microscopic calibrator.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 571 of file GNEAdditionalHandler.cpp.
References buildCalibrator(), GNEViewNet::getNet(), myLastTag, myViewNet, GNENet::retrieveLane(), SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_OUTPUT, SUMO_ATTR_POSITION, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildChargingStation (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a charging station.
Parameters
[in] attrs SAXattributes which define the trigger
[in] tag of the additional
Definition at line 542 of file GNEAdditionalHandler.cpp.
References buildChargingStation(), checkStopPos(), getFriendlyPosition(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastTag, myViewNet, POSITION_EPS, GNENet::retrieveLane(), SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDPOS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_STARTPOS, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildContainerStop (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a container stop.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 516 of file GNEAdditionalHandler.cpp.
References buildContainerStop(), checkStopPos(), getFriendlyPosition(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastTag, myViewNet, POSITION_EPS, GNENet::retrieveLane(), SUMO_ATTR_ENDPOS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_LINES, SUMO_ATTR_STARTPOS, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildDetectorE1 (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a induction loop detector (E1)
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 598 of file GNEAdditionalHandler.cpp.
References buildDetectorE1(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastTag, myViewNet, GNENet::retrieveLane(), SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SPLIT_VTYPE, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildDetectorE2 (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a lane area detector (E2)
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 624 of file GNEAdditionalHandler.cpp.
References buildDetectorE2(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastTag, myViewNet, GNENet::retrieveLane(), SUMO_ATTR_CONT, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LANE, SUMO_ATTR_LENGTH, SUMO_ATTR_POSITION, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildDetectorE3 (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a multi entry exit detector (E3)
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 654 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), myE3Parent, myLastTag, myViewNet, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_E3DETECTOR, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildDetectorEntry (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Entry detector.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 679 of file GNEAdditionalHandler.cpp.
References buildDetectorEntry(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myE3Parent, myLastTag, myViewNet, GNENet::retrieveLane(), SUMO_ATTR_LANE, SUMO_ATTR_POSITION, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildDetectorExit (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Exit detector.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 701 of file GNEAdditionalHandler.cpp.
References buildDetectorExit(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myE3Parent, myLastTag, myViewNet, GNENet::retrieveLane(), SUMO_ATTR_LANE, SUMO_ATTR_POSITION, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildRerouter (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a rerouter.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 457 of file GNEAdditionalHandler.cpp.
References buildRerouter(), GNEViewNet::getNet(), myViewNet, GNENet::retrieveEdge(), SUMO_ATTR_EDGES, SUMO_ATTR_FILE, SUMO_ATTR_ID, SUMO_ATTR_OFF, SUMO_ATTR_PROB, SUMO_ATTR_X, and SUMO_ATTR_Y.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildRouteProbe (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds routeProbe.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 232 of file GNEAdditionalHandler.cpp.
References buildRouteProbe(), GNEViewNet::getNet(), myViewNet, GNENet::retrieveEdge(), SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildVaporizer (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Builds a vaporization.
Parameters
[in] attrs SAX-attributes which define the vaporizer
[in] tag of the additional
Note
recheck throwing the exception
Definition at line 206 of file GNEAdditionalHandler.cpp.
References buildVaporizer(), GNEViewNet::getNet(), myViewNet, GNENet::retrieveEdge(), SUMO_ATTR_EDGE, SUMO_ATTR_END, SUMO_ATTR_STARTTIME, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseAndBuildVariableSpeedSign (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Variable Speed Signal (lane speed trigger)
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
See also
buildLaneSpeedTrigger
Definition at line 423 of file GNEAdditionalHandler.cpp.
References buildVariableSpeedSign(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), myLastTag, myVariableSpeedSignParent, myViewNet, GNENet::retrieveAdditional(), GNENet::retrieveLane(), SUMO_ATTR_FILE, SUMO_ATTR_ID, SUMO_ATTR_LANES, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_LANE, SUMO_TAG_VSS, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseCalibratorFlow (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses flow values of Calibrators.
Parameters
[in] attrs SAX-attributes which define the flows
[in] tag of the additional
Definition at line 343 of file GNEAdditionalHandler.cpp.
References GNECalibrator::addCalibratorFlow(), GNENet::flowExists(), GNEViewNet::getNet(), getTypeOfFlowDistribution(), GNECalibratorFlow::GNE_CALIBRATORFLOW_INVALID, myCalibratorParent, myViewNet, GNENet::routeExists(), SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_ATTR_VEHSPERHOUR, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, SUMO_TAG_VTYPE, toString(), GNENet::vehicleTypeExists(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseCalibratorRoute (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses route values of Calibrators.
Parameters
[in] attrs SAX-attributes which define the routes
[in] tag of the additional
Definition at line 256 of file GNEAdditionalHandler.cpp.
References GNECalibrator::addCalibratorRoute(), GNEViewNet::getNet(), myCalibratorParent, myViewNet, GNENet::retrieveEdge(), GNENet::routeExists(), SUMO_ATTR_COLOR, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_TAG_EDGE, SUMO_TAG_ROUTE, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseCalibratorVehicleType (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses vehicle type values of Calibrators.
Parameters
[in] attrs SAX-attributes which define the vehicle types
[in] tag of the additional
Definition at line 294 of file GNEAdditionalHandler.cpp.
References GNECalibrator::addCalibratorVehicleType(), GNEViewNet::getNet(), myCalibratorParent, myViewNet, SUMO_ATTR_ACCEL, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_DECEL, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VCLASS, SUMO_ATTR_WIDTH, SUMO_TAG_VTYPE, toString(), GNENet::vehicleTypeExists(), and WRITE_WARNING.
Referenced by myStartElement().
void GNEAdditionalHandler::parseVariableSpeedSignStep (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses step values of VariableSpeedSigns.
Parameters
[in] attrs SAX-attributes which define the steps
[in] tag of the additional
Definition at line 402 of file GNEAdditionalHandler.cpp.
References GNEVariableSpeedSign::addStep(), GNEAttributeCarrier::getID(), GNEVariableSpeedSign::getSteps(), GNEVariableSpeedSignStep::getTag(), GNEAttributeCarrier::getTag(), myVariableSpeedSignParent, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 163 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GNEAdditionalHandler::resetLastTag ()
reset last Tag and clear non-valid Additionals (For example, created E3 withouts Entry/Exit childs)
Note
must be called after a XML parsing
Definition at line 1390 of file GNEAdditionalHandler.cpp.
References GNEAttributeCarrier::getID(), GNEDetectorE3::getNumberOfEntryChilds(), GNEDetectorE3::getNumberOfExitChilds(), GNEAttributeCarrier::getTag(), myE3Parent, myLastTag, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_NOTHING, toString(), and WRITE_WARNING.
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 76 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 101 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 201 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
GNECalibrator* GNEAdditionalHandler::myCalibratorParent protected
Pointer to the last inserted Calibrator.
Definition at line 409 of file GNEAdditionalHandler.h.
Referenced by checkAdditionalParent(), myStartElement(), parseCalibratorFlow(), parseCalibratorRoute(), and parseCalibratorVehicleType().
GNEDetectorE3* GNEAdditionalHandler::myE3Parent protected
Pointer to the last inserted E3.
Definition at line 406 of file GNEAdditionalHandler.h.
Referenced by checkAdditionalParent(), myStartElement(), parseAndBuildDetectorE3(), parseAndBuildDetectorEntry(), parseAndBuildDetectorExit(), and resetLastTag().
SumoXMLTag GNEAdditionalHandler::myLastTag protected
last used Tag
Definition at line 418 of file GNEAdditionalHandler.h.
Referenced by checkAdditionalParent(), parseAndBuildBusStop(), parseAndBuildCalibrator(), parseAndBuildChargingStation(), parseAndBuildContainerStop(), parseAndBuildDetectorE1(), parseAndBuildDetectorE2(), parseAndBuildDetectorE3(), parseAndBuildDetectorEntry(), parseAndBuildDetectorExit(), parseAndBuildVariableSpeedSign(), and resetLastTag().
std::vector<GNECalibratorVehicleType> GNEAdditionalHandler::myLoadingCalibratorVehicleTypes protected
vector in wich save calibratorVehicleTypes during loading calibrators
Definition at line 421 of file GNEAdditionalHandler.h.
GNEVariableSpeedSign* GNEAdditionalHandler::myVariableSpeedSignParent protected
Pointer to the last inserted variableSpeedSign.
Definition at line 412 of file GNEAdditionalHandler.h.
Referenced by checkAdditionalParent(), myStartElement(), parseAndBuildVariableSpeedSign(), and parseVariableSpeedSignStep().
GNEViewNet* GNEAdditionalHandler::myViewNet protected
pointer to View's Net
Definition at line 403 of file GNEAdditionalHandler.h.
Referenced by parseAndBuildBusStop(), parseAndBuildCalibrator(), parseAndBuildChargingStation(), parseAndBuildContainerStop(), parseAndBuildDetectorE1(), parseAndBuildDetectorE2(), parseAndBuildDetectorE3(), parseAndBuildDetectorEntry(), parseAndBuildDetectorExit(), parseAndBuildRerouter(), parseAndBuildRouteProbe(), parseAndBuildVaporizer(), parseAndBuildVariableSpeedSign(), parseCalibratorFlow(), parseCalibratorRoute(), and parseCalibratorVehicleType().
GNERerouterInterval* GNEAdditionalHandler::rerouterIntervalToInsertValues protected
pointer to rerouterInterval in which insert GNEClosingReroute, GNEDestProbReroute, etc.
Definition at line 415 of file GNEAdditionalHandler.h.
The documentation for this class was generated from the following files:
GNEAdditionalHandler.h
GNEAdditionalHandler.cpp