SUMO - Simulation of Urban MObility: GNEInspectorFrame Class Reference
GNEInspectorFrame Class Reference
#include <GNEInspectorFrame.h>
Data Structures
class AttributeInput
FOX-declaration.
Public Member Functions
void focusUpperElement ()
focus upper element of frame
const std::vector< GNEAttributeCarrier * > & getACs () const
get current list of ACs
GNEEdge * getEdgeTemplate () const
get the template edge (to copy attributes from)
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEViewNet * getViewNet () const
get view net
GNEInspectorFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
Constructor.
virtual void hide ()
hide Frame
void inspectChild (GNEAttributeCarrier *AC, GNEAttributeCarrier *previousElement)
inspect child of already inspected element
void inspectElement (GNEAttributeCarrier *AC)
Inspect a single element.
void inspectFromDeleteFrame (GNEAttributeCarrier *AC, GNEAttributeCarrier *previousElement, bool previousElementWasMarked)
inspect called from DeleteFrame
void inspectMultisection (const std::vector< GNEAttributeCarrier * > &ACs)
Inspect the given multi-selection.
void setEdgeTemplate (GNEEdge *tpl)
seh the template edge (we assume shared responsibility via reference counting)
void setFrameWidth (int width)
set width of GNEFrame
void show ()
show inspector frame
~GNEInspectorFrame ()
Destructor.
FOX-callbacks
copy edge attributes from edge template
long onCmdCopyTemplate (FXObject *, FXSelector, void *)
long onCmdSetTemplate (FXObject *, FXSelector, void *)
set current edge as new template
long onUpdCopyTemplate (FXObject *, FXSelector, void *)
update the copy button with the name of the template
long onCmdSetBlocking (FXObject *, FXSelector, void *)
called when user toogle the blocking button
long onCmdGoBack (FXObject *, FXSelector, void *)
called when user toogle the go back button
long onCmdShowChildMenu (FXObject *, FXSelector, void *data)
called when user press right click over an item of list of childs
long onCmdCenterItem (FXObject *, FXSelector, void *)
called when user select option "center item" of child Menu
long onCmdInspectItem (FXObject *, FXSelector, void *)
called when user select option "inspect item" of child menu
long onCmdDeleteItem (FXObject *, FXSelector, void *)
called when user select option "delte item" of child menu
Protected Member Functions
void createPopUpMenu (int X, int Y, GNEAttributeCarrier *ac)
GNEInspectorFrame ()
FOX needs this.
void showAttributeCarrierChilds ()
show child of current attributeCarrier
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
FXFont * myFrameHeaderFont
Font for the Header.
FXLabel * myFrameHeaderLabel
the label for the frame's header
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEViewNet * myViewNet
the window to inform when the tls is modfied
Private Attributes
std::vector< GNEAttributeCarrier * > myACs
the multi-selection currently being inspected
GNEAdditional * myAdditional
pointer to additional element
FXButton * myBackButton
back Button
FXCheckButton * myCheckBlocked
pointer to menu check block
FXLabel * myCheckBlockedLabel
Label for Check blocked.
FXButton * myCopyTemplateButton
copy template button
GNEEdge * myEdgeTemplate
the edge template
FXGroupBox * myGroupBoxForAttributes
groupBox for attributes
FXGroupBox * myGroupBoxForEditor
GropuBox for editor attributes.
FXGroupBox * myGroupBoxForTemplates
groupBox for templates
FXGroupBox * myGroupBoxForTreeList
groupBox for AttrConnection
GNEAttributeCarrier * myPreviousElementDelete
pointer to previous element called by Delete Frame
bool myPreviousElementDeleteWasMarked
flag to ckec if myPreviousElementDelete was marked in Delete Frame
GNEAttributeCarrier * myPreviousElementInspect
pointer to previous element called by Inspector Frame
GNEAttributeCarrier * myRightClickedAC
pointer to current right clicked Attribute Carrier
FXButton * mySetTemplateButton
set template button
std::set< FXTreeItem * > myTreeItemsWithoutAC
set used to save tree items without AC assigned (for example, Incoming/Outcoming connections)
std::map< FXTreeItem *, GNEAttributeCarrier * > myTreeItemToACMap
map used to save the Tree items with their AC
FXTreeList * myTreelist
tree list to show the childs of the element to erase
std::vector< GNEInspectorFrame::AttributeInput * > myVectorOfAttributeInputs
list of Attribute inputs
Detailed Description
The Widget for modifying network-element attributes (i.e. lane speed)
Definition at line 49 of file GNEInspectorFrame.h.
Constructor & Destructor Documentation
GNEInspectorFrame::GNEInspectorFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
Constructor.
parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 97 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::getHigherNumberOfAttributes(), GUIIconSubSys::getIcon(), GUIDesignAuxiliarHorizontalFrame, GUIDesignButton, GUIDesignButtonIconRectangular, GUIDesignCheckButtonAttribute, GUIDesignGroupBoxFrame, GUIDesignLabelAttribute, GUIDesignTreeListFrame, ICON_NETEDITARROW, MID_GNE_CHILDS, MID_GNE_COPY_TEMPLATE, MID_GNE_INSPECT_GOBACK, MID_GNE_SET_BLOCKING, and MID_GNE_SET_TEMPLATE.
GNEInspectorFrame::~GNEInspectorFrame ()
Destructor.
Definition at line 147 of file GNEInspectorFrame.cpp.
References GNEReferenceCounter::decRef(), myEdgeTemplate, and GNEReferenceCounter::unreferenced().
GNEInspectorFrame::GNEInspectorFrame () inline protected
FOX needs this.
Definition at line 193 of file GNEInspectorFrame.h.
References createPopUpMenu(), and showAttributeCarrierChilds().
Member Function Documentation
void GNEInspectorFrame::createPopUpMenu (int X, int Y, GNEAttributeCarrier * ac) protected
Definition at line 468 of file GNEInspectorFrame.cpp.
References GNEViewParent::getApp(), GUIMainWindow::getBoldFont(), GUIIconSubSys::getIcon(), GNEAttributeCarrier::getIcon(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNEViewNet::getViewParent(), ICON_MODEDELETE, ICON_MODEINSPECT, ICON_RECENTERVIEW, MID_GNE_INSPECTFRAME_CENTER, MID_GNE_INSPECTFRAME_DELETE, MID_GNE_INSPECTFRAME_INSPECT, myRightClickedAC, myTreelist, GNEFrame::myViewNet, and toString().
Referenced by GNEInspectorFrame(), and onCmdShowChildMenu().
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 92 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
const std::vector< GNEAttributeCarrier * > & GNEInspectorFrame::getACs () const
get current list of ACs
Definition at line 413 of file GNEInspectorFrame.cpp.
References myACs.
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
GNEEdge * GNEInspectorFrame::getEdgeTemplate () const
get the template edge (to copy attributes from)
Definition at line 322 of file GNEInspectorFrame.cpp.
References myEdgeTemplate.
Referenced by GNEViewNet::onLeftBtnPress().
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 135 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 129 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by inspectMultisection().
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 123 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), onCmdSetBlocking(), GNEDeleteFrame::removeAttributeCarrier(), and GNECrossingFrame::edgesSelector::restoreEdgeColors().
void GNEFrame::hide () virtual inherited
hide Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNECrossingFrame, and GNESelectorFrame.
Definition at line 107 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and GNEFrame::myViewNet.
Referenced by GNESelectorFrame::hide(), GNECrossingFrame::hide(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter(), onCmdDeleteItem(), onCmdGoBack(), GNEDeleteFrame::onCmdInspectItem(), and GNEDeleteFrame::removeAttributeCarrier().
void GNEInspectorFrame::inspectChild (GNEAttributeCarrier * AC, GNEAttributeCarrier * previousElement)
inspect child of already inspected element
Definition at line 294 of file GNEInspectorFrame.cpp.
References inspectElement(), myBackButton, GNEFrame::myHeaderLeftFrame, myPreviousElementDelete, and myPreviousElementInspect.
Referenced by onCmdInspectItem().
void GNEInspectorFrame::inspectElement (GNEAttributeCarrier * AC)
Inspect a single element.
Definition at line 165 of file GNEInspectorFrame.cpp.
References inspectMultisection().
Referenced by inspectChild(), inspectFromDeleteFrame(), onCmdGoBack(), GNEViewNet::onLeftBtnPress(), and show().
void GNEInspectorFrame::inspectFromDeleteFrame (GNEAttributeCarrier * AC, GNEAttributeCarrier * previousElement, bool previousElementWasMarked)
inspect called from DeleteFrame
Definition at line 307 of file GNEInspectorFrame.cpp.
References inspectElement(), myBackButton, GNEFrame::myHeaderLeftFrame, myPreviousElementDelete, myPreviousElementDeleteWasMarked, and myPreviousElementInspect.
Referenced by GNEDeleteFrame::onCmdInspectItem().
void GNEInspectorFrame::inspectMultisection (const std::vector< GNEAttributeCarrier * > & ACs)
Inspect the given multi-selection.
Definition at line 176 of file GNEInspectorFrame.cpp.
References GNEFrame::getFrameHeaderLabel(), GNEAdditional::isAdditionalBlocked(), GNEAdditional::isAdditionalMovable(), GNEAttributeCarrier::isUnique(), myACs, myAdditional, myBackButton, myCheckBlocked, GNEFrame::myContentFrame, myCopyTemplateButton, myGroupBoxForAttributes, myGroupBoxForEditor, myGroupBoxForTemplates, myGroupBoxForTreeList, GNEFrame::myHeaderLeftFrame, mySetTemplateButton, myVectorOfAttributeInputs, showAttributeCarrierChilds(), SUMO_ATTR_TLID, SUMO_ATTR_TLTYPE, SUMO_TAG_JUNCTION, and toString().
Referenced by inspectElement(), onCmdCopyTemplate(), and GNEViewNet::onLeftBtnPress().
long GNEInspectorFrame::onCmdCenterItem (FXObject * , FXSelector , void *)
called when user select option "center item" of child Menu
Definition at line 432 of file GNEInspectorFrame.cpp.
References GUISUMOAbstractView::centerTo(), myRightClickedAC, and GNEFrame::myViewNet.
long GNEInspectorFrame::onCmdCopyTemplate (FXObject * , FXSelector , void *)
Definition at line 341 of file GNEInspectorFrame.cpp.
References GNEEdge::copyTemplate(), GNEViewNet::getUndoList(), inspectMultisection(), myACs, myEdgeTemplate, and GNEFrame::myViewNet.
long GNEInspectorFrame::onCmdDeleteItem (FXObject * , FXSelector , void *)
called when user select option "delte item" of child menu
Definition at line 456 of file GNEInspectorFrame.cpp.
References GNEViewParent::getDeleteFrame(), GNEViewNet::getViewParent(), GNEFrame::hide(), myRightClickedAC, GNEFrame::myViewNet, GNEDeleteFrame::removeAttributeCarrier(), GNEFrame::show(), and showAttributeCarrierChilds().
long GNEInspectorFrame::onCmdGoBack (FXObject * , FXSelector , void *)
called when user toogle the go back button
Definition at line 393 of file GNEInspectorFrame.cpp.
References GNEViewParent::getDeleteFrame(), GNEViewNet::getViewParent(), GNEFrame::hide(), inspectElement(), GNEDeleteFrame::markAttributeCarrier(), myPreviousElementDelete, myPreviousElementDeleteWasMarked, myPreviousElementInspect, GNEFrame::myViewNet, GNEFrame::show(), and GNEDeleteFrame::showAttributeCarrierChilds().
long GNEInspectorFrame::onCmdInspectItem (FXObject * , FXSelector , void *)
called when user select option "inspect item" of child menu
Definition at line 448 of file GNEInspectorFrame.cpp.
References inspectChild(), myACs, and myRightClickedAC.
long GNEInspectorFrame::onCmdSetBlocking (FXObject * , FXSelector , void *)
called when user toogle the blocking button
Definition at line 378 of file GNEInspectorFrame.cpp.
References GNEFrame::getViewNet(), GNE_ATTR_BLOCK_MOVEMENT, myAdditional, myCheckBlocked, and GNEAdditional::setAttribute().
long GNEInspectorFrame::onCmdSetTemplate (FXObject * , FXSelector , void *)
set current edge as new template
Definition at line 353 of file GNEInspectorFrame.cpp.
References myACs, and setEdgeTemplate().
long GNEInspectorFrame::onCmdShowChildMenu (FXObject * , FXSelector , void * data)
called when user press right click over an item of list of childs
Definition at line 419 of file GNEInspectorFrame.cpp.
References createPopUpMenu(), myTreeItemsWithoutAC, myTreeItemToACMap, and myTreelist.
long GNEInspectorFrame::onUpdCopyTemplate (FXObject * sender, FXSelector , void *)
update the copy button with the name of the template
Definition at line 363 of file GNEInspectorFrame.cpp.
References GUIGlObject::getMicrosimID(), and myEdgeTemplate.
void GNEInspectorFrame::setEdgeTemplate (GNEEdge * tpl)
seh the template edge (we assume shared responsibility via reference counting)
Definition at line 328 of file GNEInspectorFrame.cpp.
References GNEReferenceCounter::decRef(), GNEReferenceCounter::incRef(), myEdgeTemplate, and GNEReferenceCounter::unreferenced().
Referenced by onCmdSetTemplate().
void GNEFrame::setFrameWidth (int width) inherited
set width of GNEFrame
Definition at line 116 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
void GNEInspectorFrame::show () virtual
show inspector frame
Reimplemented from GNEFrame.
Definition at line 158 of file GNEInspectorFrame.cpp.
References inspectElement(), and GNEFrame::show().
Referenced by GNEDeleteFrame::onCmdInspectItem(), and GNEViewNet::updateModeSpecificControls().
void GNEInspectorFrame::showAttributeCarrierChilds () protected
show child of current attributeCarrier
Definition at line 489 of file GNEInspectorFrame.cpp.
References GNELane::getAdditionalChilds(), GNEEdge::getAdditionalChilds(), GNEJunction::getGNECrossings(), GNEJunction::getGNEEdges(), GNELane::getGNEIncomingConnections(), GNELane::getGNEOutcomingConnections(), GNEAttributeCarrier::getIcon(), GNEEdge::getLanes(), GNEAttributeCarrier::getTag(), GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, myACs, myGroupBoxForTreeList, myTreeItemsWithoutAC, myTreeItemToACMap, myTreelist, and toString().
Referenced by GNEInspectorFrame(), inspectMultisection(), and onCmdDeleteItem().
Field Documentation
std::vector<GNEAttributeCarrier*> GNEInspectorFrame::myACs private
the multi-selection currently being inspected
Definition at line 245 of file GNEInspectorFrame.h.
Referenced by getACs(), inspectMultisection(), onCmdCopyTemplate(), onCmdInspectItem(), onCmdSetTemplate(), and showAttributeCarrierChilds().
GNEAdditional* GNEInspectorFrame::myAdditional private
pointer to additional element
Definition at line 233 of file GNEInspectorFrame.h.
Referenced by inspectMultisection(), and onCmdSetBlocking().
FXButton* GNEInspectorFrame::myBackButton private
back Button
Definition at line 209 of file GNEInspectorFrame.h.
Referenced by inspectChild(), inspectFromDeleteFrame(), and inspectMultisection().
FXCheckButton* GNEInspectorFrame::myCheckBlocked private
pointer to menu check block
Definition at line 230 of file GNEInspectorFrame.h.
Referenced by inspectMultisection(), and onCmdSetBlocking().
FXLabel* GNEInspectorFrame::myCheckBlockedLabel private
Label for Check blocked.
Definition at line 227 of file GNEInspectorFrame.h.
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 104 of file GNEFrame.h.
Referenced by GNECrossingFrame::GNECrossingFrame(), GNEFrame::GNEFrame(), and inspectMultisection().
FXButton* GNEInspectorFrame::myCopyTemplateButton private
copy template button
Definition at line 215 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
GNEEdge* GNEInspectorFrame::myEdgeTemplate private
the edge template
Definition at line 221 of file GNEInspectorFrame.h.
Referenced by getEdgeTemplate(), onCmdCopyTemplate(), onUpdCopyTemplate(), setEdgeTemplate(), and ~GNEInspectorFrame().
FXFont* GNEFrame::myFrameHeaderFont protected inherited
Font for the Header.
Definition at line 98 of file GNEFrame.h.
Referenced by GNEFrame::getFrameHeaderFont(), GNEFrame::GNEFrame(), and GNEFrame::~GNEFrame().
FXLabel* GNEFrame::myFrameHeaderLabel protected inherited
the label for the frame's header
Definition at line 101 of file GNEFrame.h.
Referenced by GNEFrame::focusUpperElement(), GNEFrame::getFrameHeaderLabel(), GNEFrame::GNEFrame(), and GNESelectorFrame::selectionUpdated().
FXGroupBox* GNEInspectorFrame::myGroupBoxForAttributes private
groupBox for attributes
Definition at line 203 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
FXGroupBox* GNEInspectorFrame::myGroupBoxForEditor private
GropuBox for editor attributes.
Definition at line 224 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
FXGroupBox* GNEInspectorFrame::myGroupBoxForTemplates private
groupBox for templates
Definition at line 212 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
FXGroupBox* GNEInspectorFrame::myGroupBoxForTreeList private
groupBox for AttrConnection
Definition at line 248 of file GNEInspectorFrame.h.
Referenced by inspectMultisection(), and showAttributeCarrierChilds().
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 107 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 110 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), inspectChild(), inspectFromDeleteFrame(), and inspectMultisection().
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 113 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
GNEAttributeCarrier* GNEInspectorFrame::myPreviousElementDelete private
pointer to previous element called by Delete Frame
Definition at line 239 of file GNEInspectorFrame.h.
Referenced by inspectChild(), inspectFromDeleteFrame(), and onCmdGoBack().
bool GNEInspectorFrame::myPreviousElementDeleteWasMarked private
flag to ckec if myPreviousElementDelete was marked in Delete Frame
Definition at line 242 of file GNEInspectorFrame.h.
Referenced by inspectFromDeleteFrame(), and onCmdGoBack().
GNEAttributeCarrier* GNEInspectorFrame::myPreviousElementInspect private
pointer to previous element called by Inspector Frame
Definition at line 236 of file GNEInspectorFrame.h.
Referenced by inspectChild(), inspectFromDeleteFrame(), and onCmdGoBack().
GNEAttributeCarrier* GNEInspectorFrame::myRightClickedAC private
pointer to current right clicked Attribute Carrier
Definition at line 260 of file GNEInspectorFrame.h.
Referenced by createPopUpMenu(), onCmdCenterItem(), onCmdDeleteItem(), and onCmdInspectItem().
FXButton* GNEInspectorFrame::mySetTemplateButton private
set template button
Definition at line 218 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
std::set<FXTreeItem*> GNEInspectorFrame::myTreeItemsWithoutAC private
set used to save tree items without AC assigned (for example, Incoming/Outcoming connections)
Definition at line 257 of file GNEInspectorFrame.h.
Referenced by onCmdShowChildMenu(), and showAttributeCarrierChilds().
std::map<FXTreeItem*, GNEAttributeCarrier*> GNEInspectorFrame::myTreeItemToACMap private
map used to save the Tree items with their AC
Definition at line 254 of file GNEInspectorFrame.h.
Referenced by onCmdShowChildMenu(), and showAttributeCarrierChilds().
FXTreeList* GNEInspectorFrame::myTreelist private
tree list to show the childs of the element to erase
Definition at line 251 of file GNEInspectorFrame.h.
Referenced by createPopUpMenu(), onCmdShowChildMenu(), and showAttributeCarrierChilds().
std::vector<GNEInspectorFrame::AttributeInput*> GNEInspectorFrame::myVectorOfAttributeInputs private
list of Attribute inputs
Definition at line 206 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
GNEViewNet* GNEFrame::myViewNet protected inherited
the window to inform when the tls is modfied
Definition at line 95 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNETLSEditorFrame::buildIinternalLanes(), GNEDeleteFrame::createPopUpMenu(), createPopUpMenu(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEDeleteFrame::onCmdCenterItem(), onCmdCenterItem(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), onCmdDeleteItem(), onCmdGoBack(), GNEDeleteFrame::onCmdInspectItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdSave(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEFrame::show().
The documentation for this class was generated from the following files:
GNEInspectorFrame.h
GNEInspectorFrame.cpp