SUMO - Simulation of Urban MObility: GUIInductLoop::MyWrapper Class Reference
GUIInductLoop::MyWrapper Class Reference
A MSInductLoop-visualiser.
#include <GUIInductLoop.h>
Public Member Functions
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
GUIInductLoop & getLoop ()
Returns the detector itself.
MyWrapper (GUIInductLoop &detector, double pos)
Constructor.
~MyWrapper ()
Destructor.
inherited from GUIGlObject
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clearDictionary ()
Clears the dictionary (the objects will not be deleted)
static GUIGlObject_AbstractAdd * get (const std::string &name)
Returns a named object.
static std::vector< GUIGlID > getIDList ()
Returns the list of gl-ids of all additional objects.
static const std::vector< GUIGlObject_AbstractAdd * > & getObjectList ()
Returns the list of all additional objects.
static void remove (GUIGlObject_AbstractAdd *o)
Removes an object.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Static Protected Attributes
static std::vector< GUIGlObject_AbstractAdd * > myObjectList
The list of all addtional objects currently loaded.
static std::map< std::string, GUIGlObject_AbstractAdd * > myObjects
Map from names of loaded additional objects to the objects themselves.
Private Member Functions
MyWrapper (const MyWrapper &)
Invalidated copy constructor.
MyWrapper & operator= (const MyWrapper &)
Invalidated assignment operator.
Private Attributes
Boundary myBoundary
The detector's boundary.
GUIInductLoop & myDetector
The wrapped detector.
Position myFGPosition
The position in full-geometry mode.
double myFGRotation
The rotation in full-geometry mode.
double myPosition
The position on the lane.
Detailed Description
A MSInductLoop-visualiser.
Definition at line 142 of file GUIInductLoop.h.
Constructor & Destructor Documentation
GUIInductLoop::MyWrapper::MyWrapper (GUIInductLoop & detector, double pos)
Constructor.
Definition at line 101 of file GUIInductLoop.cpp.
References Boundary::add(), MSLane::geometryPositionAtOffset(), MSMoveReminder::getLane(), MSLane::getShape(), myBoundary, myFGPosition, myFGRotation, PositionVector::rotationDegreeAtOffset(), Position::x(), and Position::y().
GUIInductLoop::MyWrapper::~MyWrapper ()
Destructor.
Definition at line 111 of file GUIInductLoop.cpp.
GUIInductLoop::MyWrapper::MyWrapper (const MyWrapper &) private
Invalidated copy constructor.
Member Function Documentation
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 256 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 185 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 194 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 175 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 235 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 204 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 247 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 217 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 226 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
void GUIGlObject_AbstractAdd::clearDictionary () static inherited
Clears the dictionary (the objects will not be deleted)
!! delete (*i).second;
Definition at line 62 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
Referenced by GUINet::~GUINet().
void GUIInductLoop::MyWrapper::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 149 of file GUIInductLoop.cpp.
References GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GUIGlObject::drawName(), getCenteringBoundary(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), GUIGlObject::getType(), myFGPosition, myFGRotation, GUIVisualizationSettings::scale, Position::x(), and Position::y().
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 154 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 284 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), GNEEdge::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), drawGL(), and GUIBaseVehicle::drawOnPos().
GUIGlObject_AbstractAdd * GUIGlObject_AbstractAdd::get (const std::string & name) static inherited
Returns a named object.
Definition at line 73 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjects.
Boundary GUIInductLoop::MyWrapper::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 115 of file GUIInductLoop.cpp.
References Boundary::grow(), and myBoundary.
Referenced by drawGL().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 121 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEInternalLane::drawGL(), GNEJunction::drawGL(), GNECrossing::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdRevertRestriction(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
std::vector< GUIGlID > GUIGlObject_AbstractAdd::getIDList () static inherited
Returns the list of gl-ids of all additional objects.
Definition at line 96 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GUISUMOViewParent::onCmdLocate().
GUIInductLoop & GUIInductLoop::MyWrapper::getLoop ()
Returns the detector itself.
Definition at line 202 of file GUIInductLoop.cpp.
References myDetector.
Referenced by getParameterWindow().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 135 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNEJunction::getAttribute(), GNELane::getAttribute(), GNENetElement::getParentName(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSign::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNERerouter::getParentName(), GNEDetector::getParentName(), GNEDetectorE3::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEPoly::moveGeometry(), GNEEdge::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
const std::vector< GUIGlObject_AbstractAdd * > & GUIGlObject_AbstractAdd::getObjectList () static inherited
Returns the list of all additional objects.
Definition at line 90 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GNEPOI::saveToFile().
GUIParameterTableWindow * GUIInductLoop::MyWrapper::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 124 of file GUIInductLoop.cpp.
References GUIParameterTableWindow::closeBuilding(), MSInductLoop::getCurrentLength(), MSInductLoop::getCurrentOccupancy(), MSInductLoop::getCurrentPassedNumber(), MSInductLoop::getCurrentSpeed(), Named::getID(), MSMoveReminder::getLane(), getLoop(), MSInductLoop::getTimeSinceLastDetection(), GUIParameterTableWindow::mkItem(), myDetector, and myPosition.
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEDetectorE3, GNEDetector, GNERerouter, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSign, GNEVaporizer, GUILane, GNELane, and GNENetElement.
Definition at line 115 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
GUIGLObjectPopupMenu * GUIDetectorWrapper::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 55 of file GUIDetectorWrapper.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 148 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEDetector::drawDetectorIcon(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNECrossing::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEAdditional::drawParentAndChildrenConnections(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, and GUIPerson.
Definition at line 127 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
MyWrapper& GUIInductLoop::MyWrapper::operator= (const MyWrapper &) private
Invalidated assignment operator.
void GUIGlObject_AbstractAdd::remove (GUIGlObject_AbstractAdd * o) static inherited
Removes an object.
Definition at line 83 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject::getFullName(), GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 262 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 141 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 271 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
Boundary GUIInductLoop::MyWrapper::myBoundary private
The detector's boundary.
Definition at line 190 of file GUIInductLoop.h.
Referenced by getCenteringBoundary(), and MyWrapper().
GUIInductLoop& GUIInductLoop::MyWrapper::myDetector private
The wrapped detector.
Definition at line 187 of file GUIInductLoop.h.
Referenced by getLoop(), and getParameterWindow().
Position GUIInductLoop::MyWrapper::myFGPosition private
The position in full-geometry mode.
Definition at line 193 of file GUIInductLoop.h.
Referenced by drawGL(), and MyWrapper().
double GUIInductLoop::MyWrapper::myFGRotation private
The rotation in full-geometry mode.
Definition at line 196 of file GUIInductLoop.h.
Referenced by drawGL(), and MyWrapper().
std::vector< GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjectList static protected inherited
The list of all addtional objects currently loaded.
Definition at line 78 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::getIDList(), GUIGlObject_AbstractAdd::getObjectList(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
std::map< std::string, GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjects static protected inherited
Map from names of loaded additional objects to the objects themselves.
Definition at line 75 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::get(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
double GUIInductLoop::MyWrapper::myPosition private
The position on the lane.
Definition at line 199 of file GUIInductLoop.h.
Referenced by getParameterWindow().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIInductLoop.h
GUIInductLoop.cpp