SUMO - Simulation of Urban MObility: GNEChange_Additional Class Reference
GNEChange_Additional Class Reference
#include <GNEChange_Additional.h>
Public Member Functions
GNEChange_Additional (GNEAdditional *additional, bool forward)
Constructor for creating/deleting an additional element.
virtual FXuint size () const
return actual size
~GNEChange_Additional ()
Destructor.
inherited from GNEChange
get undo Name
FXString undoName () const
return undoName
FXString redoName () const
get Redo name
void undo ()
undo action
void redo ()
redo action
Protected Attributes
bool myForward
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
GNENet * myNet
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Private Attributes
GNEAdditional * myAdditional
full information regarding the additional element that is to be created/deleted
GNEDetectorE3 * myE3Parent
pointer to E3 parent (used by Entry/exits)
std::vector< GNEEdge * > myEdgeChilds
list of Edge childs (used by Rerouters)
GNEEdge * myEdgeParent
pointer to edge (used by additionals with edge parent)
std::vector< GNEDetectorEntry * > myEntryChilds
list of Entry detectors child (used by E3 Detector)
std::vector< GNEDetectorExit * > myExitChilds
list of Exit detectors child used (used by E3 Detector)
GNELane * myLaneParent
pointer to lane (used by additionals with lane parent)
Detailed Description
A network change in which a additional element is created or deleted
Definition at line 55 of file GNEChange_Additional.h.
Constructor & Destructor Documentation
GNEChange_Additional::GNEChange_Additional (GNEAdditional * additional, bool forward)
Constructor for creating/deleting an additional element.
Parameters
[in] additional The additional element to be created/deleted
[in] forward Whether to create/delete (true/false)
Definition at line 54 of file GNEChange_Additional.cpp.
References GNEDetectorE3::myGNEDetectorEntrys, GNEDetectorE3::myGNEDetectorExits, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E3DETECTOR, and SUMO_TAG_REROUTER.
GNEChange_Additional::~GNEChange_Additional ()
Destructor.
Definition at line 87 of file GNEChange_Additional.cpp.
References GNEReferenceCounter::decRef(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNEViewNet::isTestingModeEnabled(), myAdditional, GNEChange::myNet, toString(), GNEReferenceCounter::unreferenced(), and WRITE_WARNING.
Member Function Documentation
void GNEChange_Additional::redo () virtual
redo action
Reimplemented from GNEChange.
Definition at line 209 of file GNEChange_Additional.cpp.
References GNELane::addAdditionalChild(), GNEEdge::addAdditionalChild(), GNEDetectorE3::addEntryChild(), GNEDetectorE3::addExitChild(), GNENet::deleteAdditional(), GNEAdditional::getEdge(), GNEAttributeCarrier::getID(), GNEAdditional::getLane(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNENet::insertAdditional(), GNEViewNet::isTestingModeEnabled(), myAdditional, myE3Parent, myEdgeChilds, myEdgeParent, myEntryChilds, myExitChilds, GNEChange::myForward, myLaneParent, GNEChange::myNet, GNELane::removeAdditionalChild(), GNEEdge::removeAdditionalChild(), GNEDetectorE3::removeEntryChild(), GNEDetectorE3::removeExitChild(), SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E3DETECTOR, SUMO_TAG_REROUTER, toString(), GNEDetectorE3::updateGeometry(), and WRITE_WARNING.
FXString GNEChange_Additional::redoName () const virtual
get Redo name
Reimplemented from GNEChange.
Definition at line 326 of file GNEChange_Additional.cpp.
References GNEAttributeCarrier::getTag(), myAdditional, GNEChange::myForward, and toString().
FXuint GNEChange::size () const virtual inherited
return actual size
Definition at line 53 of file GNEChange.cpp.
void GNEChange_Additional::undo () virtual
undo action
Reimplemented from GNEChange.
Definition at line 101 of file GNEChange_Additional.cpp.
References GNELane::addAdditionalChild(), GNEEdge::addAdditionalChild(), GNEDetectorE3::addEntryChild(), GNEDetectorE3::addExitChild(), GNENet::deleteAdditional(), GNEAdditional::getEdge(), GNEAttributeCarrier::getID(), GNEAdditional::getLane(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNENet::insertAdditional(), GNEViewNet::isTestingModeEnabled(), myAdditional, myE3Parent, myEdgeChilds, myEdgeParent, myEntryChilds, myExitChilds, GNEChange::myForward, myLaneParent, GNEChange::myNet, GNELane::removeAdditionalChild(), GNEEdge::removeAdditionalChild(), GNEDetectorE3::removeEntryChild(), GNEDetectorE3::removeExitChild(), SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E3DETECTOR, SUMO_TAG_REROUTER, toString(), GNEDetectorE3::updateGeometry(), and WRITE_WARNING.
FXString GNEChange_Additional::undoName () const virtual
return undoName
Reimplemented from GNEChange.
Definition at line 316 of file GNEChange_Additional.cpp.
References GNEAttributeCarrier::getTag(), myAdditional, GNEChange::myForward, and toString().
Field Documentation
GNEAdditional* GNEChange_Additional::myAdditional private
full information regarding the additional element that is to be created/deleted
Note
we assume shared responsibility for the pointer (via reference counting)
Definition at line 87 of file GNEChange_Additional.h.
Referenced by redo(), redoName(), undo(), undoName(), and ~GNEChange_Additional().
GNEDetectorE3* GNEChange_Additional::myE3Parent private
pointer to E3 parent (used by Entry/exits)
Definition at line 96 of file GNEChange_Additional.h.
Referenced by redo(), and undo().
std::vector<GNEEdge*> GNEChange_Additional::myEdgeChilds private
list of Edge childs (used by Rerouters)
Definition at line 105 of file GNEChange_Additional.h.
Referenced by redo(), and undo().
GNEEdge* GNEChange_Additional::myEdgeParent private
pointer to edge (used by additionals with edge parent)
Definition at line 93 of file GNEChange_Additional.h.
Referenced by redo(), and undo().
std::vector<GNEDetectorEntry*> GNEChange_Additional::myEntryChilds private
list of Entry detectors child (used by E3 Detector)
Definition at line 99 of file GNEChange_Additional.h.
Referenced by redo(), and undo().
std::vector<GNEDetectorExit*> GNEChange_Additional::myExitChilds private
list of Exit detectors child used (used by E3 Detector)
Definition at line 102 of file GNEChange_Additional.h.
Referenced by redo(), and undo().
bool GNEChange::myForward protected inherited
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
Definition at line 87 of file GNEChange.h.
Referenced by GNEChange_Junction::redo(), GNEChange_Selection::redo(), GNEChange_TLS::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), GNEChange_Junction::redoName(), GNEChange_Selection::redoName(), GNEChange_TLS::redoName(), GNEChange_Connection::redoName(), GNEChange_Lane::redoName(), redoName(), GNEChange_Edge::redoName(), GNEChange_Crossing::redoName(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), GNEChange_TLS::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), GNEChange_Junction::undoName(), GNEChange_Selection::undoName(), GNEChange_TLS::undoName(), GNEChange_Connection::undoName(), GNEChange_Lane::undoName(), undoName(), GNEChange_Edge::undoName(), and GNEChange_Crossing::undoName().
GNELane* GNEChange_Additional::myLaneParent private
pointer to lane (used by additionals with lane parent)
Definition at line 90 of file GNEChange_Additional.h.
Referenced by redo(), and undo().
GNENet* GNEChange::myNet protected inherited
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Definition at line 82 of file GNEChange.h.
Referenced by GNEChange_Junction::redo(), GNEChange_Selection::redo(), GNEChange_Lane::redo(), redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), GNEChange_Lane::undo(), undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), ~GNEChange_Additional(), GNEChange_Lane::~GNEChange_Lane(), and GNEChange_TLS::~GNEChange_TLS().
The documentation for this class was generated from the following files:
GNEChange_Additional.h
GNEChange_Additional.cpp