SUMO - Simulation of Urban MObility: GNENet Class Reference
GNENet Class Reference
A NBNetBuilder extended by visualisation and editing capabilities.
#include <GNENet.h>
Public Member Functions
void addExplicitTurnaround (std::string id)
add edge id to the list of explicit turnarounds
GNEEdge * addReversedEdge (GNEEdge *edge, GNEUndoList *undoList)
add reversed edge
bool addSRestrictedLane (SUMOVehicleClass vclass, GNEEdge &edge, GNEUndoList *undoList)
add restricted lane to edge
void changeEdgeEndpoints (GNEEdge *edge, const std::string &newSourceID, const std::string &newDestID)
modifies endpoins of the given edge
void computeAndUpdate (OptionsCont &oc)
recompute the network and update lane geometries
void computeEverything (GNEApplicationWindow *window, bool force=false)
void computeJunction (GNEJunction *junction)
GNEEdge * createEdge (GNEJunction *src, GNEJunction *dest, GNEEdge *tpl, GNEUndoList *undoList, const std::string &suggestedName="", bool wasSplit=false, bool allowDuplicateGeom=false)
creates a new edge (unless an edge with the same geometry already exists)
GNEJunction * createJunction (const Position &pos, GNEUndoList *undoList)
creates a new junction
void deleteAdditional (GNEAdditional *additional)
delete additional element previously inserted
void deleteConnection (GNEConnection *connection, GNEUndoList *undoList)
remove connection
void deleteCrossing (GNECrossing *crossing, GNEUndoList *undoList)
remove crossing
void deleteEdge (GNEEdge *edge, GNEUndoList *undoList)
removes edge
void deleteGeometryOrEdge (GNEEdge *edge, const Position &pos, GNEUndoList *undoList)
removes geometry when pos is close to a geometry node, deletes the whole edge otherwise
void deleteJunction (GNEJunction *junction, GNEUndoList *undoList)
removes junction and all incident edges
void deleteLane (GNELane *lane, GNEUndoList *undoList)
removes lane
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
void duplicateLane (GNELane *lane, GNEUndoList *undoList)
duplicates lane
void finishMoveSelection (GNEUndoList *undoList)
register changes to junction and edge positions with the undoList
bool flowExists (const std::string &flowID) const
Check if exist a flow with these ID.
std::string generateVaporizerID () const
generate an ID for vaporizers
GNEAdditional * getAdditional (SumoXMLTag type, const std::string &id) const
Returns the named additional.
std::string getAdditionalID (SumoXMLTag type, const GNELane *lane, const double pos) const
Returns the additional close to the given position.
std::vector< GNEAdditional * > getAdditionals (SumoXMLTag type=SUMO_TAG_NOTHING) const
get vector with additionals
FXApp * getApp ()
get pointer to the main App
const Boundary & getBoundary () const
returns the bounder of the network
std::set< GUIGlID > getGlIDs (GUIGlObjectType type=GLO_MAX)
const GNECalibratorFlow & getGNECalibratorFlow (const std::string &calibratorFlowID) const
Returns a reference to a calibrator flow finding in all calibrators of net.
const GNECalibratorRoute & getGNECalibratorRoute (const std::string &calibratorRouteID) const
Returns a reference to a calibrator route finding in all calibrators of net.
const GNECalibratorVehicleType & getGNECalibratorVehicleType (const std::string &calibratorVehicleTypeID) const
Returns a reference to a calibrator vehicle type finding in all calibrators of net.
NBNetBuilder * getNetBuilder () const
get net builder
int getNumberOfAdditionals (SumoXMLTag type=SUMO_TAG_NOTHING) const
Returns the number of additionals of the net.
ShapeContainer & getShapeContainer ()
get shape container
NBTrafficLightLogicCont & getTLLogicCont ()
returns the tllcont of the underlying netbuilder
GNEViewNet * getViewNet () const
get view net
SUMORTree & getVisualisationSpeedUp ()
Returns the RTree used for visualisation speed-up.
const SUMORTree & getVisualisationSpeedUp () const
Returns the RTree used for visualisation speed-up.
GNENet (NBNetBuilder *netBuilder)
Constructor.
void initGNEConnections ()
initialize GNEConnections
void insertAdditional (GNEAdditional *additional, bool hardFail=true)
Insert a additional element previously created in GNEAdditionalHandler.
bool isAdditionalsSaved () const
check if additional are saved
void joinSelectedJunctions (GNEUndoList *undoList)
void mergeJunctions (GNEJunction *moved, GNEJunction *target, GNEUndoList *undoList)
merge the given junctions edges between the given junctions will be deleted
void moveSelection (const Position &moveSrc, const Position &moveDest)
move all selected junctions and edges
bool netHasCrossings () const
check if net has crossings
void refreshAdditional (GNEAdditional *additional)
refreshes boundary information of an additional after a geometry update
void refreshElement (GUIGlObject *o)
refreshes boundary information for o and update
void removeExplicitTurnaround (std::string id)
remove edge id from the list of explicit turnarounds
bool removeRestrictedLane (SUMOVehicleClass vclass, GNEEdge &edge, GNEUndoList *undoList)
remove restricted lane
void removeSolitaryJunctions (GNEUndoList *undoList)
removes junctions that have no edges
void renameEdge (GNEEdge *edge, const std::string &newID)
updates the map and reserves new id
void renameJunction (GNEJunction *junction, const std::string &newID)
updates the map and reserves new id
void replaceJunctionByGeometry (GNEJunction *junction, GNEUndoList *undoList)
replace the selected junction by geometry node(s) and merge the edges
void requireRecompute ()
inform the net about the need for recomputation
bool restrictLane (SUMOVehicleClass vclass, GNELane *lane, GNEUndoList *undoList)
transform lane to restricted lane
GNEAdditional * retrieveAdditional (const std::string &idl, bool hardFail=true) const
Returns the named additional.
std::vector< GNEAdditional * > retrieveAdditionals (bool onlySelected=false)
return all additionals
std::vector< GNEAttributeCarrier * > retrieveAttributeCarriers (const std::set< GUIGlID > &ids, GUIGlObjectType type)
get the attribute carriers based on GlIDs
GNEEdge * retrieveEdge (const std::string &id, bool failHard=true)
get edge by id
std::vector< GNEEdge * > retrieveEdges (bool onlySelected=false)
return all edges
GNEJunction * retrieveJunction (const std::string &id, bool failHard=true)
get junction by id
std::vector< GNEJunction * > retrieveJunctions (bool onlySelected=false)
return all junctions
GNELane * retrieveLane (const std::string &id, bool failHard=true)
get lane by id
std::vector< GNELane * > retrieveLanes (bool onlySelected=false)
return all lanes
void reverseEdge (GNEEdge *edge, GNEUndoList *undoList)
reverse edge
bool revertLaneRestriction (GNELane *lane, GNEUndoList *undoList)
revert prevously restricted lane
bool routeExists (const std::string &routeID) const
Check if exist a route with these ID.
void save (OptionsCont &oc)
save the network
void saveAdditionals (const std::string &filename)
save additional elements of the network
void saveJoined (OptionsCont &oc)
save log of joined junctions (and nothing else)
void savePlain (OptionsCont &oc)
save plain xml representation of the network (and nothing else)
void setAdditionalSaved (bool value)
set manually the flag of additionals
void setViewNet (GNEViewNet *viewNet)
Set the viewNet to be notified of network changes.
GNEJunction * splitEdge (GNEEdge *edge, const Position &pos, GNEUndoList *undoList, GNEJunction *newJunction=0)
split edge at position by inserting a new junction
void splitEdgesBidi (const std::set< GNEEdge * > &edges, const Position &pos, GNEUndoList *undoList)
split all edges at position by inserting one new junction
void updateAdditionalID (const std::string &oldID, GNEAdditional *additional)
update additional ID in container
bool vehicleTypeExists (const std::string &vehicleTypeID) const
Check if exist a vehicle type with these ID.
~GNENet ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
const Boundary & getZBoundary () const
Returns the Z boundary (stored in the x() coordinate) values of 0 do not affect the boundary.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static const RGBColor selectedConnectionColor
color of selected connection
static const RGBColor selectedLaneColor
color of selected lane
static const RGBColor selectionColor
color of selection
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Types
internal GNE components
typedef std::map< std::string, GNEJunction * > GNEJunctions
typedef std::map< std::string, GNEEdge * > GNEEdges
typedef std::map< std::pair< std::string, SumoXMLTag >, GNEAdditional * > GNEAdditionals
Protected Member Functions
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
GNEAdditionals myAdditionals
map with the name and pointer to additional elements of net
bool myAdditionalsSaved
Flag to check if additionals must be saved.
GNEEdges myEdges
map with the name and pointer to edges of net
std::set< std::string > myExplicitTurnarounds
list of edge ids for which turn-arounds must be added explicitly
SUMORTree myGrid
the rtree which contains all GUIGlObjects (so named for historical reasons)
GNEJunctions myJunctions
map with the name and pointer to junctions of net
bool myNeedRecompute
whether the net needs recomputation
NBNetBuilder * myNetBuilder
The internal netbuilder.
GUIShapeContainer myShapeContainer
the container for additional pois and polygons
GNEViewNet * myViewNet
The viewNet to be notofied of about changes.
ID Suppliers for newly created edges and junctions
IDSupplier myEdgeIDSupplier
IDSupplier myJunctionIDSupplier
Private Member Functions
void deleteSingleEdge (GNEEdge *edge)
deletes a single edge
void deleteSingleJunction (GNEJunction *junction)
deletes a single junction
void initDetectors ()
Initialises the detector wrappers.
void initTLMap ()
Initialises the tl-logic map and wrappers.
void insertEdge (GNEEdge *edge)
inserts a single edge into the net and into the underlying netbuild-container
void insertJunction (GNEJunction *junction)
inserts a single junction into the net and into the underlying netbuild-container
GNEEdge * registerEdge (GNEEdge *edge)
registers an edge with GNENet containers
GNEJunction * registerJunction (GNEJunction *junction)
registers a junction with GNENet containers
void remapEdge (GNEEdge *oldEdge, GNEJunction *from, GNEJunction *to, GNEUndoList *undoList, bool keepEndpoints=false)
void reserveEdgeID (const std::string &id)
reserve edge ID (To avoid duplicates)
void reserveJunctionID (const std::string &id)
reserve junction ID (To avoid duplicates)
void update ()
notify myViewNet
Private Attributes
Boundary myZBoundary
the z boundary (stored in the x-coordinate), values of 0 are ignored
Static Private Attributes
static const double Z_INITIALIZED = 1
marker for whether the z-boundary is initialized
Friends
class GNEChange_Connection
class GNEChange_Edge
class GNEChange_Junction
declare friend class
Detailed Description
A NBNetBuilder extended by visualisation and editing capabilities.
Definition at line 88 of file GNENet.h.
Member Typedef Documentation
typedef std::map<std::pair<std::string, SumoXMLTag>, GNEAdditional*> GNENet::GNEAdditionals protected
Definition at line 532 of file GNENet.h.
typedef std::map<std::string, GNEEdge*> GNENet::GNEEdges protected
Definition at line 531 of file GNENet.h.
typedef std::map<std::string, GNEJunction*> GNENet::GNEJunctions protected
Definition at line 530 of file GNENet.h.
Constructor & Destructor Documentation
GNENet::GNENet (NBNetBuilder * netBuilder)
Constructor.
Parameters
[in] netbuilder the netbuilder which may already have been filled GNENet becomes responsible for cleaning this up
Definition at line 99 of file GNENet.cpp.
References Boundary::add(), NBNodeCont::getAllNames(), NBEdgeCont::getAllNames(), NBNetBuilder::getEdgeCont(), Boundary::getHeight(), NBNetBuilder::getNodeCont(), Boundary::getWidth(), GUIGlObjectStorage::gIDStorage, myEdges, myGrid, myNetBuilder, myZBoundary, registerEdge(), registerJunction(), NBNodeCont::retrieve(), NBEdgeCont::retrieve(), GUIGlObjectStorage::setNetObject(), NBNodesEdgesSorter::sortNodesEdges(), Boundary::ymin(), and Z_INITIALIZED.
GNENet::~GNENet ()
Destructor.
Definition at line 157 of file GNENet.cpp.
References myEdges, myJunctions, and myNetBuilder.
Member Function Documentation
void GNENet::addExplicitTurnaround (std::string id)
add edge id to the list of explicit turnarounds
Definition at line 1186 of file GNENet.cpp.
References myExplicitTurnarounds.
Referenced by GNEJunction::setLogicValid().
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 256 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
GNEEdge * GNENet::addReversedEdge (GNEEdge * edge, GNEUndoList * undoList)
add reversed edge
Parameters
[in] edge The edge of which to add the reverse
Returns
Return the new edge or 0
Definition at line 615 of file GNENet.cpp.
References createEdge(), createJunction(), NBEdge::getGeometry(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEAttributeCarrier::getID(), NBEdge::getInnerGeometry(), NBEdge::getLaneSpreadFunction(), GNEEdge::getNBEdge(), NBEdge::getPermissions(), GUISelectedStorage::getSelected(), NBEdge::getTotalWidth(), gSelected, isRailway(), LANESPREAD_RIGHT, PositionVector::move2side(), GNEUndoList::p_begin(), GNEUndoList::p_end(), PositionVector::reverse(), GNEEdge::setAttribute(), SUMO_ATTR_SHAPE, SUMO_TAG_EDGE, and toString().
Referenced by GNEViewNet::onCmdAddReversedEdge().
bool GNENet::addSRestrictedLane (SUMOVehicleClass vclass, GNEEdge & edge, GNEUndoList * undoList)
add restricted lane to edge
Parameters
[in] vclass vehicle class to restrict
[in] edge The edge in which insert restricted lane
[in] undoList The undolist in which to mark changes
Definition at line 503 of file GNENet.cpp.
References duplicateLane(), GNEEdge::getLanes(), and restrictLane().
Referenced by GNEViewNet::addRestrictedLane().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 185 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 194 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 175 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 235 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 204 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 247 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 217 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 226 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
void GNENet::changeEdgeEndpoints (GNEEdge * edge, const std::string & newSourceID, const std::string & newDestID)
modifies endpoins of the given edge
Definition at line 1155 of file GNENet.cpp.
References GNEEdge::getNBEdge(), GNEJunction::getNBNode(), NBEdge::reinitNodes(), requireRecompute(), retrieveJunction(), and update().
Referenced by GNEEdge::setAttribute().
void GNENet::computeAndUpdate (OptionsCont & oc)
recompute the network and update lane geometries
Definition at line 1574 of file GNENet.cpp.
References Boundary::add(), NBNetBuilder::compute(), OptionsCont::getBool(), GeoConvHelper::getFinal(), initGNEConnections(), OptionsCont::isSet(), myEdges, myExplicitTurnarounds, myGrid, myJunctions, myNeedRecompute, myNetBuilder, refreshElement(), and Boundary::reset().
Referenced by computeEverything(), GNELoadThread::run(), save(), saveJoined(), and savePlain().
void GNENet::computeEverything (GNEApplicationWindow * window, bool force = false)
Definition at line 983 of file GNENet.cpp.
References computeAndUpdate(), OptionsCont::getOptions(), myNeedRecompute, GNEApplicationWindow::setStatusBarText(), update(), and WRITE_MESSAGE.
Referenced by GNEApplicationWindow::onCmdComputeJunctions(), and GNEViewNet::setEditMode().
void GNENet::computeJunction (GNEJunction * junction)
Definition at line 1005 of file GNENet.cpp.
References NBTrafficLightLogicCont::computeSingleLogic(), NBNode::getControllingTLS(), GNEJunction::getNBNode(), OptionsCont::getOptions(), getTLLogicCont(), NBTrafficLightDefinition::setParticipantsInformation(), and NBTrafficLightDefinition::setTLControllingInformation().
Referenced by GNETLSEditorFrame::onCmdDefSwitch().
GNEEdge * GNENet::createEdge (GNEJunction * src, GNEJunction * dest, GNEEdge * tpl, GNEUndoList * undoList, const std::string & suggestedName = "", bool wasSplit = false, bool allowDuplicateGeom = false)
creates a new edge (unless an edge with the same geometry already exists)
Parameters
[in] src The starting junction
[in] dest The ending junction
[in] tpl The template edge from which to copy attributes (including lane attrs)
[in] undoList The undoList in which to mark changes
[in] suggestedName
[in] wasSplit Whether the edge was created from a split
[in] allowDuplicateGeom Whether to create the edge even though another edge with the same geometry exists
Returns
The newly created edge or 0 if no edge was created
Definition at line 251 of file GNENet.cpp.
References GNEEdge::getNBEdge(), GNEJunction::getNBNode(), IDSupplier::getNext(), NBNode::getOutgoingEdges(), GNEChange_Edge, myEdgeIDSupplier, myEdges, GNEUndoList::p_begin(), GNEUndoList::p_end(), requireRecompute(), reserveEdgeID(), retrieveEdge(), GNEJunction::setLogicValid(), SUMO_TAG_EDGE, toString(), NBEdge::UNSPECIFIED_OFFSET, and NBEdge::UNSPECIFIED_WIDTH.
Referenced by addReversedEdge(), GNEViewNet::onLeftBtnPress(), remapEdge(), replaceJunctionByGeometry(), reverseEdge(), and splitEdge().
GNEJunction * GNENet::createJunction (const Position & pos, GNEUndoList * undoList)
creates a new junction
Parameters
[in] position The position of the new junction
[in] undoList The undolist in which to mark changes
Returns
the new junction
Definition at line 240 of file GNENet.cpp.
References IDSupplier::getNext(), GNEChange_Junction, myJunctionIDSupplier, and myJunctions.
Referenced by addReversedEdge(), joinSelectedJunctions(), GNEViewNet::onLeftBtnPress(), and splitEdge().
void GNENet::deleteAdditional (GNEAdditional * additional)
delete additional element previously inserted
Parameters
[in] additional The additional element to remove
Definition at line 1275 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myAdditionals, myAdditionalsSaved, myGrid, SUMORTree::removeAdditionalGLObject(), toString(), and update().
Referenced by GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), and GNEChange_Edge::undo().
void GNENet::deleteConnection (GNEConnection * connection, GNEUndoList * undoList)
remove connection
Parameters
[in] connection The connection to be removed
[in] undoList The undolist in which to mark changes
Definition at line 415 of file GNENet.cpp.
References GNEConnection::getEdgeFrom(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEConnection::getNBConnection(), GNEConnection::getNBEdgeConnection(), GNEViewNet::getUndoList(), GLO_CONNECTION, GNEChange_Connection, gSelected, GNEJunction::invalidateTLS(), GUISelectedStorage::isSelected(), GNEJunction::markAsModified(), myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), requireRecompute(), SUMO_TAG_CONNECTION, and toString().
Referenced by GNEConnectorFrame::handleLaneClick(), and GNEDeleteFrame::removeAttributeCarrier().
void GNENet::deleteCrossing (GNECrossing * crossing, GNEUndoList * undoList)
remove crossing
Parameters
[in] crossing The crossing to be removed
[in] undoList The undolist in which to mark changes
Definition at line 433 of file GNENet.cpp.
References NBNode::Crossing::edges, GUIGlObject::getGlID(), GNECrossing::getNBCrossing(), GNECrossing::getParentJunction(), GLO_CROSSING, gSelected, GUISelectedStorage::isSelected(), GNEUndoList::p_begin(), GNEUndoList::p_end(), NBNode::Crossing::priority, requireRecompute(), and NBNode::Crossing::width.
Referenced by deleteJunction(), and GNEDeleteFrame::removeAttributeCarrier().
void GNENet::deleteEdge (GNEEdge * edge, GNEUndoList * undoList)
removes edge
Parameters
[in] edge The edge to be removed
[in] undoList The undolist in which to mark changes
Definition at line 336 of file GNENet.cpp.
References GNEEdge::getAdditionalChilds(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEEdge::getGNERerouters(), GNEEdge::getLanes(), GLO_EDGE, GNEChange_Edge, gSelected, GUISelectedStorage::isSelected(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEJunction::removeFromCrossings(), requireRecompute(), GNEJunction::setLogicValid(), SUMO_TAG_EDGE, and toString().
Referenced by deleteGeometryOrEdge(), deleteJunction(), deleteLane(), GNEViewNet::deleteSelectedEdges(), remapEdge(), replaceJunctionByGeometry(), reverseEdge(), and splitEdge().
void GNENet::deleteGeometryOrEdge (GNEEdge * edge, const Position & pos, GNEUndoList * undoList)
removes geometry when pos is close to a geometry node, deletes the whole edge otherwise
Parameters
[in] edge The edge to be removed
[in] pos The position that was clicked upon
[in] undoList The undolist in which to mark changes
Definition at line 532 of file GNENet.cpp.
References deleteEdge(), and GNEEdge::deleteGeometry().
Referenced by GNEDeleteFrame::removeAttributeCarrier().
void GNENet::deleteJunction (GNEJunction * junction, GNEUndoList * undoList)
removes junction and all incident edges
Parameters
[in] junction The junction to be removed
[in] undoList The undolist in which to mark changes
Definition at line 306 of file GNENet.cpp.
References deleteCrossing(), deleteEdge(), NBNode::getEdges(), GUIGlObject::getGlID(), GNEJunction::getGNECrossings(), GNEJunction::getNBNode(), GLO_JUNCTION, GNEChange_Junction, gSelected, GUISelectedStorage::isSelected(), myEdges, NODETYPE_PRIORITY, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEJunction::setAttribute(), SUMO_ATTR_TYPE, SUMO_TAG_JUNCTION, and toString().
Referenced by GNEViewNet::deleteSelectedJunctions(), joinSelectedJunctions(), mergeJunctions(), GNEDeleteFrame::removeAttributeCarrier(), removeSolitaryJunctions(), and replaceJunctionByGeometry().
void GNENet::deleteLane (GNELane * lane, GNEUndoList * undoList)
removes lane
Parameters
[in] lane The lane to be removed
[in] undoList The undolist in which to mark changes
Definition at line 382 of file GNENet.cpp.
References deleteEdge(), GNELane::getAdditionalChilds(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNELane::getIndex(), NBEdge::getLaneStruct(), GNEEdge::getNBEdge(), NBEdge::getNumLanes(), GNELane::getParentEdge(), GLO_LANE, gSelected, GUISelectedStorage::isSelected(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEJunction::removeFromCrossings(), requireRecompute(), GNEJunction::setLogicValid(), SUMO_TAG_LANE, and toString().
Referenced by GNEViewNet::deleteSelectedEdges(), GNEDeleteFrame::removeAttributeCarrier(), and removeRestrictedLane().
void GNENet::deleteSingleEdge (GNEEdge * edge) private
deletes a single edge
Definition at line 1525 of file GNENet.cpp.
References GNEReferenceCounter::decRef(), GUISelectedStorage::deselect(), NBEdgeCont::extract(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GUIGlObject::getMicrosimID(), GNEEdge::getNBEdge(), gSelected, myEdges, myGrid, myNetBuilder, SUMORTree::removeAdditionalGLObject(), GNEJunction::removeIncomingGNEEdge(), GNEJunction::removeOutgoingGNEEdge(), GNEEdge::setResponsible(), and update().
Referenced by GNEChange_Edge::redo(), and GNEChange_Edge::undo().
void GNENet::deleteSingleJunction (GNEJunction * junction) private
deletes a single junction
Definition at line 1512 of file GNENet.cpp.
References GNEReferenceCounter::decRef(), GUISelectedStorage::deselect(), NBNodeCont::extract(), GUIGlObject::getGlID(), GUIGlObject::getMicrosimID(), GNEJunction::getNBNode(), NBNetBuilder::getNodeCont(), gSelected, myGrid, myJunctions, myNetBuilder, SUMORTree::removeAdditionalGLObject(), GNEJunction::setResponsible(), and update().
Referenced by GNEChange_Junction::redo(), and GNEChange_Junction::undo().
void GNENet::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 211 of file GNENet.cpp.
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 154 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 284 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEDetectorE3::drawGL(), GNEEdge::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
void GNENet::duplicateLane (GNELane * lane, GNEUndoList * undoList)
duplicates lane
Parameters
[in] lane The lane to be duplicated
[in] undoList The undolist in which to mark changes
Definition at line 447 of file GNENet.cpp.
References GNELane::getIndex(), NBEdge::getLaneStruct(), GNEEdge::getNBEdge(), GNELane::getParentEdge(), GNEUndoList::p_begin(), GNEUndoList::p_end(), requireRecompute(), SUMO_TAG_LANE, and toString().
Referenced by addSRestrictedLane(), and GNEViewNet::onCmdDuplicateLane().
void GNENet::finishMoveSelection (GNEUndoList * undoList)
register changes to junction and edge positions with the undoList
Definition at line 1228 of file GNENet.cpp.
References GNEEdge::getAttribute(), GNEUndoList::p_begin(), GNEUndoList::p_end(), retrieveEdges(), retrieveJunctions(), GNEEdge::setAttribute(), and SUMO_ATTR_SHAPE.
Referenced by GNEViewNet::onLeftBtnRelease().
bool GNENet::flowExists (const std::string & flowID) const
Check if exist a flow with these ID.
Definition at line 1443 of file GNENet.cpp.
References GNECalibrator::flowExists(), getAdditionals(), and SUMO_TAG_CALIBRATOR.
Referenced by GNECalibrator::generateFlowID(), GNEAdditionalHandler::parseCalibratorFlow(), and GNECalibratorFlow::setFlowID().
std::string GNENet::generateVaporizerID () const
generate an ID for vaporizers
Definition at line 837 of file GNENet.cpp.
References myAdditionals, SUMO_TAG_VAPORIZER, and toString().
GNEAdditional * GNENet::getAdditional (SumoXMLTag type, const std::string & id) const
Returns the named additional.
Parameters
[in] type tag with the type of additional
[in] id The id of the additional to return.
Returns
The named additional, or 0 if don't exists
Definition at line 1331 of file GNENet.cpp.
References myAdditionals.
Referenced by GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVariableSpeedSign(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE2::isValid(), GNEBusStop::isValid(), GNEContainerStop::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSign::isValid(), GNERouteProbe::isValid(), GNERerouter::isValid(), GNEChargingStation::isValid(), GNEDetectorE3::isValid(), GNECalibrator::isValid(), GNEAdditionalHandler::parseAndBuildDetectorE3(), and GNECalibrator::setAttribute().
std::string GNENet::getAdditionalID (SumoXMLTag type, const GNELane * lane, const double pos) const
Returns the additional close to the given position.
Parameters
[in] type tag with the type of additional
[in] lane the lane of the additional to return.
[in] pos the position of the additional to return.
Returns
The additional id on the location, or "" if don't exists
Definition at line 1343 of file GNENet.cpp.
References myAdditionals, and POSITION_EPS.
std::vector< GNEAdditional * > GNENet::getAdditionals (SumoXMLTag type = SUMO_TAG_NOTHING) const
get vector with additionals
Parameters
[in] type type of additional to get. SUMO_TAG_NOTHING will get all additionals
Returns
vector with pointers to additionals.
Definition at line 1354 of file GNENet.cpp.
References myAdditionals, and SUMO_TAG_NOTHING.
Referenced by flowExists(), getGNECalibratorFlow(), getGNECalibratorRoute(), getGNECalibratorVehicleType(), routeExists(), GNEAdditionalFrame::SelectorParentAdditional::showListOfAdditionals(), and vehicleTypeExists().
FXApp * GNENet::getApp ()
get pointer to the main App
Definition at line 1041 of file GNENet.cpp.
References myViewNet.
const Boundary & GNENet::getBoundary () const
returns the bounder of the network
Definition at line 188 of file GNENet.cpp.
References myGrid.
Referenced by getCenteringBoundary().
Boundary GNENet::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 216 of file GNENet.cpp.
References getBoundary().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 109 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 121 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), deleteConnection(), deleteCrossing(), deleteEdge(), deleteJunction(), deleteLane(), deleteSingleEdge(), deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEInternalLane::drawGL(), GNEJunction::drawGL(), GNECrossing::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GUIPolygon::drawGL(), GNERouteProbe::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdRevertRestriction(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
std::set< GUIGlID > GNENet::getGlIDs (GUIGlObjectType type = GLO_MAX)
Definition at line 897 of file GNENet.cpp.
References GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_MAX, GLO_TLLOGIC, myAdditionals, myEdges, and myJunctions.
Referenced by GNESelectorFrame::getMatches(), GNESelectorFrame::onCmdInvert(), and GNEViewParent::onCmdLocate().
const GNECalibratorFlow & GNENet::getGNECalibratorFlow (const std::string & calibratorFlowID) const
Returns a reference to a calibrator flow finding in all calibrators of net.
Definition at line 1404 of file GNENet.cpp.
References GNECalibrator::flowExists(), getAdditionals(), GNECalibrator::getCalibratorFlow(), SUMO_TAG_CALIBRATOR, SUMO_TAG_VTYPE, and toString().
const GNECalibratorRoute & GNENet::getGNECalibratorRoute (const std::string & calibratorRouteID) const
Returns a reference to a calibrator route finding in all calibrators of net.
Definition at line 1378 of file GNENet.cpp.
References getAdditionals(), GNECalibrator::getCalibratorRoute(), GNECalibrator::routeExists(), SUMO_TAG_CALIBRATOR, SUMO_TAG_VTYPE, and toString().
const GNECalibratorVehicleType & GNENet::getGNECalibratorVehicleType (const std::string & calibratorVehicleTypeID) const
Returns a reference to a calibrator vehicle type finding in all calibrators of net.
Definition at line 1391 of file GNENet.cpp.
References getAdditionals(), GNECalibrator::getCalibratorVehicleType(), SUMO_TAG_CALIBRATOR, SUMO_TAG_VTYPE, toString(), and GNECalibrator::vehicleTypeExists().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 135 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), deleteSingleEdge(), deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNEJunction::getAttribute(), GNELane::getAttribute(), GNENetElement::getParentName(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSign::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNERerouter::getParentName(), GNEDetector::getParentName(), GNEDetectorE3::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEPoly::moveGeometry(), GNEEdge::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEInspectorFrame::onUpdCopyTemplate(), registerEdge(), registerJunction(), remapEdge(), GNEEdge::removeConnection(), replaceJunctionByGeometry(), retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
NBNetBuilder * GNENet::getNetBuilder () const
get net builder
Definition at line 1047 of file GNENet.cpp.
References myNetBuilder.
Referenced by GNEJunction::rebuildGNECrossings().
int GNENet::getNumberOfAdditionals (SumoXMLTag type = SUMO_TAG_NOTHING) const
Returns the number of additionals of the net.
Parameters
[in] type type of additional to count. SUMO_TAG_NOTHING will count all additionals
Returns
Number of additionals of the net
Definition at line 1366 of file GNENet.cpp.
References myAdditionals, and SUMO_TAG_NOTHING.
Referenced by GNEApplicationWindow::continueWithUnsavedAdditionalChanges(), and GNEAdditionalFrame::generateID().
GUIParameterTableWindow * GNENet::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 205 of file GNENet.cpp.
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEDetectorE3, GNEDetector, GNERerouter, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSign, GNEVaporizer, GUILane, GNELane, and GNENetElement.
Definition at line 115 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
GUIGLObjectPopupMenu * GNENet::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 195 of file GNENet.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildPopupHeader(), and GUIGlObject::buildPositionCopyEntry().
ShapeContainer & GNENet::getShapeContainer ()
get shape container
Definition at line 1252 of file GNENet.cpp.
References myShapeContainer.
Referenced by GNEApplicationWindow::onCmdOpenShapes(), and GNEDeleteFrame::removeAttributeCarrier().
NBTrafficLightLogicCont & GNENet::getTLLogicCont ()
returns the tllcont of the underlying netbuilder
Definition at line 1171 of file GNENet.cpp.
References NBNetBuilder::getTLLogicCont(), and myNetBuilder.
Referenced by GNEJunction::addTrafficLight(), computeJunction(), GNETLSEditorFrame::onCmdDefSwitch(), GNEJunction::removeTrafficLight(), and GNEJunction::setAttribute().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 148 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEDetector::drawDetectorIcon(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GNECrossing::drawGL(), GNEVaporizer::drawGL(), GUIContainer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNERerouter::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GNEEdge::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GNEConnection::drawGL(), GUIParkingArea::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEAdditional::drawParentAndChildrenConnections(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, and GUIPerson.
Definition at line 127 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
GNEViewNet * GNENet::getViewNet () const
get view net
Definition at line 1165 of file GNENet.cpp.
References myViewNet.
Referenced by GNEApplicationWindow::continueWithUnsavedAdditionalChanges(), GNEApplicationWindow::continueWithUnsavedChanges(), GNEJunction::drawGL(), GNEConnection::drawGL(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GNEApplicationWindow::onCmdOpenAdditionals(), GNEApplicationWindow::onCmdSaveAdditionals(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GNEApplicationWindow::onCmdSaveJoined(), GNEApplicationWindow::onCmdSaveNetwork(), GNEApplicationWindow::onCmdSavePois(), GNEChange_Junction::redo(), GNEChange_Selection::redo(), GNEChange_TLS::redo(), GNEChange_Lane::redo(), GNEChange_Connection::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), GNELane::setAttribute(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), GNEChange_TLS::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), GNELane::updateGeometry(), GNEJunction::updateShapesAndGeometries(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), and GNEChange_TLS::~GNEChange_TLS().
SUMORTree & GNENet::getVisualisationSpeedUp ()
Returns the RTree used for visualisation speed-up.
Returns
The visualisation speed-up
Definition at line 228 of file GNENet.cpp.
References myGrid.
Referenced by GNETLSEditorFrame::buildIinternalLanes(), GNEViewNet::onCmdNodeShape(), and GNEViewNet::removeCurrentPoly().
const SUMORTree & GNENet::getVisualisationSpeedUp () const
Returns the RTree used for visualisation speed-up.
Returns
The visualisation speed-up
Definition at line 234 of file GNENet.cpp.
References myGrid.
const Boundary & GNENet::getZBoundary () const
Returns the Z boundary (stored in the x() coordinate) values of 0 do not affect the boundary.
Definition at line 222 of file GNENet.cpp.
References myZBoundary.
void GNENet::initDetectors () private
Initialises the detector wrappers.
void GNENet::initGNEConnections ()
initialize GNEConnections
Definition at line 1564 of file GNENet.cpp.
References myEdges.
Referenced by computeAndUpdate(), and GNEViewNet::onCmdToogleShowConnection().
void GNENet::initTLMap () private
Initialises the tl-logic map and wrappers.
void GNENet::insertAdditional (GNEAdditional * additional, bool hardFail = true)
Insert a additional element previously created in GNEAdditionalHandler.
Parameters
[in] additional pointer to the additional element to add
[in] hardFail enable or disable exception if additional to insert is duplicated
Definition at line 1258 of file GNENet.cpp.
References SUMORTree::addAdditionalGLObject(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myAdditionals, myAdditionalsSaved, myGrid, toString(), and update().
Referenced by GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), and GNEChange_Edge::undo().
void GNENet::insertEdge (GNEEdge * edge) private
inserts a single edge into the net and into the underlying netbuild-container
Definition at line 1466 of file GNENet.cpp.
References NBNode::addIncomingEdge(), NBNode::addOutgoingEdge(), NBNetBuilder::getEdgeCont(), NBEdge::getFromNode(), GNEEdge::getNBEdge(), NBEdge::getToNode(), NBEdgeCont::insert(), myNetBuilder, and registerEdge().
Referenced by GNEChange_Edge::redo(), and GNEChange_Edge::undo().
void GNENet::insertJunction (GNEJunction * junction) private
inserts a single junction into the net and into the underlying netbuild-container
Definition at line 1459 of file GNENet.cpp.
References GNEJunction::getNBNode(), NBNetBuilder::getNodeCont(), NBNodeCont::insert(), myNetBuilder, and registerJunction().
Referenced by GNEChange_Junction::redo(), and GNEChange_Junction::undo().
bool GNENet::isAdditionalsSaved () const
check if additional are saved
Definition at line 1621 of file GNENet.cpp.
References myAdditionalsSaved.
Referenced by GNEApplicationWindow::continueWithUnsavedAdditionalChanges().
void GNENet::joinSelectedJunctions (GNEUndoList * undoList)
Definition at line 1053 of file GNENet.cpp.
References NBNodeCont::analyzeCluster(), createJunction(), deleteJunction(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), NBNetBuilder::getNodeCont(), myEdges, myNetBuilder, NODETYPE_TRAFFIC_LIGHT, GNEUndoList::p_begin(), GNEUndoList::p_end(), NBNodeCont::registerJoinedCluster(), remapEdge(), retrieveJunctions(), GNEJunction::setAttribute(), SUMO_ATTR_ID, SUMO_ATTR_TYPE, SUMO_TAG_JUNCTION, and toString().
Referenced by GNEApplicationWindow::onCmdJoinJunctions().
void GNENet::mergeJunctions (GNEJunction * moved, GNEJunction * target, GNEUndoList * undoList)
merge the given junctions edges between the given junctions will be deleted
Parameters
[in] moved The junction that will be eliminated
[in] target The junction that will be enlarged
[in] undoList The undo list with which to register changes
Definition at line 649 of file GNENet.cpp.
References deleteJunction(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), NBNode::getIncomingEdges(), GNEJunction::getNBNode(), NBNode::getOutgoingEdges(), NBNode::getPosition(), GNEJunction::move(), myEdges, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEJunction::registerMove(), remapEdge(), SUMO_TAG_JUNCTION, and toString().
Referenced by GNEViewNet::mergeJunctions().
void GNENet::moveSelection (const Position & moveSrc, const Position & moveDest)
move all selected junctions and edges
Note
: inner points of an edge will only be modified if the edge and its endpoints are selected
Definition at line 1198 of file GNENet.cpp.
References GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEEdge::moveGeometry(), retrieveEdges(), and retrieveJunctions().
Referenced by GNEViewNet::onMouseMove().
bool GNENet::netHasCrossings () const
check if net has crossings
Definition at line 1030 of file GNENet.cpp.
References NBNodeCont::begin(), NBNodeCont::end(), NBNetBuilder::getNodeCont(), and myNetBuilder.
void GNENet::refreshAdditional (GNEAdditional * additional)
refreshes boundary information of an additional after a geometry update
Note
only non removed additional will be refresh
Definition at line 825 of file GNENet.cpp.
References SUMORTree::addAdditionalGLObject(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myAdditionals, myGrid, SUMORTree::removeAdditionalGLObject(), and update().
Referenced by GNEVariableSpeedSign::commmitAdditionalGeometryMoved(), GNEDetector::commmitAdditionalGeometryMoved(), GNEStoppingPlace::commmitAdditionalGeometryMoved(), GNERerouter::commmitAdditionalGeometryMoved(), GNEDetectorE3::commmitAdditionalGeometryMoved(), GNEAdditional::commmitAdditionalGeometryMoved(), GNEVariableSpeedSign::updateGeometry(), GNEDetectorE1::updateGeometry(), GNERerouter::updateGeometry(), GNEChargingStation::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEDetectorE3::updateGeometry(), GNERouteProbe::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNECalibrator::updateGeometry(), GNEDetectorEntry::updateGeometryByParent(), and GNEDetectorExit::updateGeometryByParent().
void GNENet::refreshElement (GUIGlObject * o)
refreshes boundary information for o and update
Definition at line 817 of file GNENet.cpp.
References SUMORTree::addAdditionalGLObject(), myGrid, SUMORTree::removeAdditionalGLObject(), and update().
Referenced by GNEEdge::addConnection(), GNEEdge::addLane(), computeAndUpdate(), GNEPOI::move(), GNEPoly::moveGeometry(), GNEJunction::registerMove(), GNEEdge::remakeGNEConnections(), GNEEdge::removeConnection(), GNEEdge::removeLane(), GNECrossing::setAttribute(), GNEJunction::setAttribute(), and GNEEdge::setGeometry().
GNEEdge * GNENet::registerEdge (GNEEdge * edge) private
registers an edge with GNENet containers
Definition at line 1494 of file GNENet.cpp.
References Boundary::add(), SUMORTree::addAdditionalGLObject(), GNEJunction::addIncomingGNEEdge(), GNEJunction::addOutgoingGNEEdge(), GNEEdge::getBoundary(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GUIGlObject::getMicrosimID(), GNEReferenceCounter::incRef(), myEdges, myGrid, GNEEdge::setResponsible(), and update().
Referenced by GNENet(), and insertEdge().
GNEJunction * GNENet::registerJunction (GNEJunction * junction) private
registers a junction with GNENet containers
Definition at line 1477 of file GNENet.cpp.
References Boundary::add(), SUMORTree::addAdditionalGLObject(), GNEJunction::getBoundary(), GUIGlObject::getMicrosimID(), GNEJunction::getNBNode(), NBNode::getPosition(), GNEReferenceCounter::incRef(), myGrid, myJunctions, myZBoundary, GNEJunction::setResponsible(), update(), Position::z(), and Z_INITIALIZED.
Referenced by GNENet(), and insertJunction().
void GNENet::remapEdge (GNEEdge * oldEdge, GNEJunction * from, GNEJunction * to, GNEUndoList * undoList, bool keepEndpoints = false) private
Definition at line 673 of file GNENet.cpp.
References createEdge(), deleteEdge(), GNEEdge::getAttribute(), GUIGlObject::getMicrosimID(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, GNEEdge::setAttribute(), and SUMO_ATTR_SHAPE.
Referenced by joinSelectedJunctions(), and mergeJunctions().
void GNENet::removeExplicitTurnaround (std::string id)
remove edge id from the list of explicit turnarounds
Definition at line 1192 of file GNENet.cpp.
References myExplicitTurnarounds.
Referenced by GNEEdge::removeConnection().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 262 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
bool GNENet::removeRestrictedLane (SUMOVehicleClass vclass, GNEEdge & edge, GNEUndoList * undoList)
remove restricted lane
Parameters
[in] vclass vehicle class to restrict
[in] edge the edge in which remove sidewalk
[in] undoList The undolist in which to mark changes
Definition at line 518 of file GNENet.cpp.
References deleteLane(), and GNEEdge::getLanes().
Referenced by GNEViewNet::removeRestrictedLane().
void GNENet::removeSolitaryJunctions (GNEUndoList * undoList)
removes junctions that have no edges
Definition at line 1103 of file GNENet.cpp.
References deleteJunction(), NBNode::getEdges(), GNEJunction::getNBNode(), myJunctions, GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_JUNCTION, and toString().
Referenced by GNEApplicationWindow::onCmdCleanJunctions().
void GNENet::renameEdge (GNEEdge * edge, const std::string & newID)
updates the map and reserves new id
Definition at line 1142 of file GNENet.cpp.
References NBNetBuilder::getEdgeCont(), Named::getID(), GNEEdge::getLanes(), GNEEdge::getNBEdge(), myEdges, myNetBuilder, NBEdgeCont::rename(), and GNEEdge::setMicrosimID().
Referenced by GNEEdge::setAttribute().
void GNENet::renameJunction (GNEJunction * junction, const std::string & newID)
updates the map and reserves new id
Definition at line 1177 of file GNENet.cpp.
References Named::getID(), GNEJunction::getNBNode(), NBNetBuilder::getNodeCont(), myJunctions, myNetBuilder, NBNodeCont::rename(), and GUIGlObject::setMicrosimID().
Referenced by GNEJunction::setAttribute().
void GNENet::replaceJunctionByGeometry (GNEJunction * junction, GNEUndoList * undoList)
replace the selected junction by geometry node(s) and merge the edges
Definition at line 1120 of file GNENet.cpp.
References PositionVector::append(), NBNode::checkIsRemovable(), createEdge(), deleteEdge(), deleteJunction(), NBNode::getEdgesToJoin(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), NBEdge::getInnerGeometry(), GUIGlObject::getMicrosimID(), GNEEdge::getNBEdge(), GNEJunction::getNBNode(), NBNode::getPosition(), myEdges, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEEdge::setAttribute(), SUMO_ATTR_SHAPE, and toString().
Referenced by GNEViewNet::onCmdNodeReplace().
void GNENet::requireRecompute ()
inform the net about the need for recomputation
Definition at line 1024 of file GNENet.cpp.
References myNeedRecompute.
Referenced by changeEdgeEndpoints(), createEdge(), deleteConnection(), deleteCrossing(), deleteEdge(), deleteLane(), duplicateLane(), GNEJunction::invalidateShape(), and GNEViewNet::onCmdToogleShowConnection().
void GNENet::reserveEdgeID (const std::string & id) private
reserve edge ID (To avoid duplicates)
Definition at line 1552 of file GNENet.cpp.
References IDSupplier::avoid(), and myEdgeIDSupplier.
Referenced by createEdge().
void GNENet::reserveJunctionID (const std::string & id) private
reserve junction ID (To avoid duplicates)
Definition at line 1558 of file GNENet.cpp.
References IDSupplier::avoid(), and myJunctionIDSupplier.
bool GNENet::restrictLane (SUMOVehicleClass vclass, GNELane * lane, GNEUndoList * undoList)
transform lane to restricted lane
Parameters
[in] vclass vehicle class to restrict
[in] lane The lane to be transformed
[in] undoList The undolist in which to mark changes
Definition at line 459 of file GNENet.cpp.
References GNEEdge::getLanes(), GNEEdge::getNBEdge(), GNELane::getParentEdge(), NBEdge::getPermissions(), getVehicleClassNames(), GNELane::setAttribute(), SUMO_ATTR_ALLOW, SVC_PEDESTRIAN, and toString().
Referenced by addSRestrictedLane(), and GNEViewNet::restrictLane().
GNEAdditional * GNENet::retrieveAdditional (const std::string & idl, bool hardFail = true) const
Returns the named additional.
Parameters
[in] id The id of the additional to return.
[in] hardFail enable or disable exception if additional to insert is duplicated
Definition at line 1304 of file GNENet.cpp.
References myAdditionals.
Referenced by GNEAdditionalHandler::buildAdditional(), and GNEAdditionalHandler::parseAndBuildVariableSpeedSign().
std::vector< GNEAdditional * > GNENet::retrieveAdditionals (bool onlySelected = false)
return all additionals
Parameters
[in] onlySelected Whether to return only selected additionals
Definition at line 1319 of file GNENet.cpp.
References GLO_ADDITIONAL, gSelected, GUISelectedStorage::isSelected(), and myAdditionals.
Referenced by GNEViewNet::deleteSelectedAdditionals().
std::vector< GNEAttributeCarrier * > GNENet::retrieveAttributeCarriers (const std::set< GUIGlID > & ids, GUIGlObjectType type)
get the attribute carriers based on GlIDs
Parameters
[in] ids The set of ids for which to retrive the ACs
[in] type The GUI-type of the objects with the given ids
Exceptions
InvalidArgument if any given id does not match the declared type
Definition at line 847 of file GNENet.cpp.
References GUIGlObject::getMicrosimID(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, and GUIGlObjectStorage::unblockObject().
Referenced by GNEViewNet::onLeftBtnPress().
GNEEdge * GNENet::retrieveEdge (const std::string & id, bool failHard = true)
get edge by id
Parameters
[in] id The id of the desired edge
[in] failHard Whether attempts to retrieve a nonexisting edge should result in an exception
Exceptions
UnknownElement
Definition at line 743 of file GNENet.cpp.
References myEdges.
Referenced by GNEViewNet::addRestrictedLane(), GNEAdditionalHandler::buildAdditional(), GNEAdditional::changeEdge(), GNECalibratorRoute::checkEdgeRoute(), createEdge(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), GNEAdditional::getPopUpMenu(), GNEConnectorFrame::initTargets(), GNECrossing::isValid(), GNEVaporizer::isValid(), GNERouteProbe::isValid(), GNERerouter::isValid(), GNEEdge::isValid(), GNEJunction::markAsModified(), GNEJunction::move(), GNERerouterIntervalDialog::onCmdEditClosingReroute(), GNERerouterIntervalDialog::onCmdEditDestProbReroute(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAdditionalHandler::parseAndBuildRouteProbe(), GNEAdditionalHandler::parseAndBuildVaporizer(), GNEAdditionalHandler::parseCalibratorRoute(), GNEViewNet::removeRestrictedLane(), GNEViewNet::restrictLane(), GNEEdge::retrieveConnection(), retrieveLane(), GNECrossing::setAttribute(), GNERerouter::setAttribute(), GNECalibratorRoute::setEdges(), and GNEJunction::setLogicValid().
std::vector< GNEEdge * > GNENet::retrieveEdges (bool onlySelected = false)
return all edges
Parameters
[in] onlySelected Whether to return only selected edges
Definition at line 758 of file GNENet.cpp.
References GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), and myEdges.
Referenced by GNEAdditionalFrame::addAdditional(), GNEViewNet::addRestrictedLane(), GNEViewNet::deleteSelectedEdges(), finishMoveSelection(), GNETLSEditorFrame::handleMultiChange(), moveSelection(), GNEViewNet::onCmdRevertRestriction(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::removeRestrictedLane(), GNEAdditionalFrame::SelectorParentEdges::showList(), and GNEAdditionalFrame::SelectorParentEdges::updateUseSelectedEdges().
GNEJunction * GNENet::retrieveJunction (const std::string & id, bool failHard = true)
get junction by id
Parameters
[in] id The id of the desired junction
[in] failHard Whether attempts to retrieve a nonexisting junction should result in an exception
Exceptions
UnknownElement
Definition at line 730 of file GNENet.cpp.
References myJunctions.
Referenced by changeEdgeEndpoints(), GNEJunction::invalidateTLS(), GNEEdge::isValid(), GNEJunction::isValid(), GNETLSEditorFrame::onCmdOK(), GNEEdge::setAttribute(), and GNEJunction::setAttribute().
std::vector< GNEJunction * > GNENet::retrieveJunctions (bool onlySelected = false)
return all junctions
Parameters
[in] onlySelected Whether to return only selected junctions
Definition at line 805 of file GNENet.cpp.
References GLO_JUNCTION, gSelected, GUISelectedStorage::isSelected(), and myJunctions.
Referenced by GNEViewNet::deleteSelectedJunctions(), finishMoveSelection(), joinSelectedJunctions(), moveSelection(), and GNEConnectorFrame::onCmdSelectDeadStarts().
GNELane * GNENet::retrieveLane (const std::string & id, bool failHard = true)
get lane by id
Parameters
[in] id The id of the desired lane
[in] failHard Whether attempts to retrieve a nonexisting lane should result in an exception
Exceptions
UnknownElement
Definition at line 785 of file GNENet.cpp.
References SUMOXMLDefinitions::getEdgeIDFromLane(), GNEEdge::getLanes(), retrieveEdge(), SUMO_TAG_LANE, and toString().
Referenced by GNEAdditionalHandler::buildAdditional(), GNEAdditional::changeLane(), GNEAdditional::getPopUpMenu(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEVariableSpeedSign::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouterIntervalDialog::onCmdEditClosingLaneReroute(), GNEAdditionalHandler::parseAndBuildBusStop(), GNEAdditionalHandler::parseAndBuildCalibrator(), GNEAdditionalHandler::parseAndBuildChargingStation(), GNEAdditionalHandler::parseAndBuildContainerStop(), GNEAdditionalHandler::parseAndBuildDetectorE1(), GNEAdditionalHandler::parseAndBuildDetectorE2(), GNEAdditionalHandler::parseAndBuildDetectorEntry(), GNEAdditionalHandler::parseAndBuildDetectorExit(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), and GNEVariableSpeedSign::setAttribute().
std::vector< GNELane * > GNENet::retrieveLanes (bool onlySelected = false)
return all lanes
Parameters
[in] onlySelected Whether to return only selected lanes
Definition at line 770 of file GNENet.cpp.
References GLO_LANE, gSelected, GUISelectedStorage::isSelected(), and myEdges.
Referenced by GNEAdditionalFrame::addAdditional(), GNEViewNet::addRestrictedLane(), GNEViewNet::deleteSelectedEdges(), GNETLSEditorFrame::handleMultiChange(), GNEViewNet::onCmdDuplicateLane(), GNEViewNet::onCmdRevertRestriction(), GNEViewNet::removeRestrictedLane(), GNEViewNet::restrictLane(), GNEAdditionalFrame::SelectorParentLanes::showList(), and GNEAdditionalFrame::SelectorParentLanes::updateUseSelectedLanes().
void GNENet::reverseEdge (GNEEdge * edge, GNEUndoList * undoList)
reverse edge
Parameters
[in] edge The edge to be reversed
Definition at line 604 of file GNENet.cpp.
References createEdge(), deleteEdge(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEAttributeCarrier::getID(), NBEdge::getInnerGeometry(), GNEEdge::getNBEdge(), GNEUndoList::p_begin(), PositionVector::reverse(), GNEEdge::setAttribute(), SUMO_ATTR_SHAPE, SUMO_TAG_EDGE, and toString().
Referenced by GNEViewNet::onCmdReverseEdge().
bool GNENet::revertLaneRestriction (GNELane * lane, GNEUndoList * undoList)
revert prevously restricted lane
Parameters
[in] lane The lane to be unrestricted
[in] undoList The undolist in which to mark changes
Definition at line 485 of file GNENet.cpp.
References GNELane::isRestricted(), joinToString(), GNELane::setAttribute(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SumoVehicleClassStrings, SVC_BICYCLE, SVC_BUS, and SVC_PEDESTRIAN.
Referenced by GNEViewNet::onCmdRevertRestriction().
bool GNENet::routeExists (const std::string & routeID) const
Check if exist a route with these ID.
Definition at line 1417 of file GNENet.cpp.
References getAdditionals(), GNECalibrator::routeExists(), and SUMO_TAG_CALIBRATOR.
Referenced by GNECalibrator::generateRouteID(), GNEAdditionalHandler::parseCalibratorFlow(), GNEAdditionalHandler::parseCalibratorRoute(), GNECalibratorFlow::setRoute(), and GNECalibratorRoute::setRouteID().
void GNENet::save (OptionsCont & oc)
save the network
Parameters
[in] oc The OptionsCont which knows how and where to save
Definition at line 688 of file GNENet.cpp.
References computeAndUpdate(), myNetBuilder, and NWFrame::writeNetwork().
Referenced by GNEApplicationWindow::onCmdSaveNetwork().
void GNENet::saveAdditionals (const std::string & filename)
save additional elements of the network
Parameters
[in] filename name of the file in wich save additionals
Definition at line 697 of file GNENet.cpp.
References OutputDevice::close(), OutputDevice::getDevice(), myAdditionals, myAdditionalsSaved, and OutputDevice::openTag().
Referenced by GNEApplicationWindow::onCmdSaveAdditionals().
void GNENet::saveJoined (OptionsCont & oc)
save log of joined junctions (and nothing else)
Parameters
[in] oc The OptionsCont which knows how and where to save
Definition at line 717 of file GNENet.cpp.
References computeAndUpdate(), NBNetBuilder::getNodeCont(), myNetBuilder, and NWWriter_XML::writeJoinedJunctions().
Referenced by GNEApplicationWindow::onCmdSaveJoined().
void GNENet::savePlain (OptionsCont & oc)
save plain xml representation of the network (and nothing else)
Parameters
[in] oc The OptionsCont which knows how and where to save
Definition at line 710 of file GNENet.cpp.
References computeAndUpdate(), myNetBuilder, and NWWriter_XML::writeNetwork().
Referenced by GNEApplicationWindow::onCmdSaveAsPlainXML().
void GNENet::setAdditionalSaved (bool value)
set manually the flag of additionals
Definition at line 1627 of file GNENet.cpp.
References myAdditionalsSaved.
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 141 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 271 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
void GNENet::setViewNet (GNEViewNet * viewNet)
Set the viewNet to be notified of network changes.
Definition at line 724 of file GNENet.cpp.
References myViewNet.
GNEJunction * GNENet::splitEdge (GNEEdge * edge, const Position & pos, GNEUndoList * undoList, GNEJunction * newJunction = 0)
split edge at position by inserting a new junction
Parameters
[in] edge The edge to be split
[in] pos The position on which to insert the new junction
Returns
The new junction
Definition at line 540 of file GNENet.cpp.
References createEdge(), createJunction(), deleteEdge(), NBEdge::getGeometry(), GNEEdge::getGNEJunctionSource(), GUIGlObject::getMicrosimID(), GNEEdge::getNBEdge(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, GNEChange_Connection, PositionVector::nearest_offset_to_point2D(), GNEUndoList::p_begin(), GNEEdge::setAttribute(), PositionVector::splitAt(), SUMO_ATTR_SHAPE, SUMO_TAG_EDGE, toString(), and GNEEdge::wasSplit().
Referenced by GNEViewNet::onCmdSplitEdge(), and splitEdgesBidi().
void GNENet::splitEdgesBidi (const std::set< GNEEdge * > & edges, const Position & pos, GNEUndoList * undoList)
split all edges at position by inserting one new junction
Parameters
[in] edges The edges to be split
[in] pos The position on which to insert the new junction
Definition at line 593 of file GNENet.cpp.
References GNEUndoList::p_begin(), GNEUndoList::p_end(), splitEdge(), SUMO_TAG_EDGE, and toString().
Referenced by GNEViewNet::onCmdSplitEdgeBidi().
void GNENet::update () private
notify myViewNet
Definition at line 1544 of file GNENet.cpp.
References myViewNet.
Referenced by changeEdgeEndpoints(), computeEverything(), deleteAdditional(), deleteSingleEdge(), deleteSingleJunction(), insertAdditional(), refreshAdditional(), refreshElement(), registerEdge(), and registerJunction().
void GNENet::updateAdditionalID (const std::string & oldID, GNEAdditional * additional)
update additional ID in container
Note
this function is automatically called when user changes the ID of an additional
Definition at line 1290 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myAdditionals, myAdditionalsSaved, and toString().
Referenced by GNEAdditional::setAdditionalID().
bool GNENet::vehicleTypeExists (const std::string & vehicleTypeID) const
Check if exist a vehicle type with these ID.
Definition at line 1430 of file GNENet.cpp.
References getAdditionals(), SUMO_TAG_CALIBRATOR, and GNECalibrator::vehicleTypeExists().
Referenced by GNECalibrator::generateVehicleTypeID(), GNEAdditionalHandler::parseCalibratorFlow(), GNEAdditionalHandler::parseCalibratorVehicleType(), GNECalibratorFlow::setVehicleType(), and GNECalibratorVehicleType::setVehicleTypeID().
Friends And Related Function Documentation
friend class GNEChange_Connection friend
Definition at line 93 of file GNENet.h.
Referenced by deleteConnection(), and splitEdge().
friend class GNEChange_Edge friend
Definition at line 92 of file GNENet.h.
Referenced by createEdge(), and deleteEdge().
friend class GNEChange_Junction friend
declare friend class
Definition at line 91 of file GNENet.h.
Referenced by createJunction(), and deleteJunction().
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
GNEAdditionals GNENet::myAdditionals protected
map with the name and pointer to additional elements of net
Definition at line 542 of file GNENet.h.
Referenced by deleteAdditional(), generateVaporizerID(), getAdditional(), getAdditionalID(), getAdditionals(), getGlIDs(), getNumberOfAdditionals(), insertAdditional(), refreshAdditional(), retrieveAdditional(), retrieveAdditionals(), saveAdditionals(), and updateAdditionalID().
bool GNENet::myAdditionalsSaved protected
Flag to check if additionals must be saved.
Definition at line 560 of file GNENet.h.
Referenced by deleteAdditional(), insertAdditional(), isAdditionalsSaved(), saveAdditionals(), setAdditionalSaved(), and updateAdditionalID().
IDSupplier GNENet::myEdgeIDSupplier protected
Definition at line 546 of file GNENet.h.
Referenced by createEdge(), and reserveEdgeID().
GNEEdges GNENet::myEdges protected
map with the name and pointer to edges of net
Definition at line 539 of file GNENet.h.
Referenced by computeAndUpdate(), createEdge(), deleteJunction(), deleteSingleEdge(), getGlIDs(), GNENet(), initGNEConnections(), joinSelectedJunctions(), mergeJunctions(), registerEdge(), renameEdge(), replaceJunctionByGeometry(), retrieveEdge(), retrieveEdges(), retrieveLanes(), and ~GNENet().
std::set<std::string> GNENet::myExplicitTurnarounds protected
list of edge ids for which turn-arounds must be added explicitly
Definition at line 554 of file GNENet.h.
Referenced by addExplicitTurnaround(), computeAndUpdate(), and removeExplicitTurnaround().
SUMORTree GNENet::myGrid protected
the rtree which contains all GUIGlObjects (so named for historical reasons)
Definition at line 520 of file GNENet.h.
Referenced by computeAndUpdate(), deleteAdditional(), deleteSingleEdge(), deleteSingleJunction(), getBoundary(), getVisualisationSpeedUp(), GNENet(), insertAdditional(), refreshAdditional(), refreshElement(), registerEdge(), and registerJunction().
IDSupplier GNENet::myJunctionIDSupplier protected
Definition at line 547 of file GNENet.h.
Referenced by createJunction(), and reserveJunctionID().
GNEJunctions GNENet::myJunctions protected
map with the name and pointer to junctions of net
Definition at line 536 of file GNENet.h.
Referenced by computeAndUpdate(), createJunction(), deleteSingleJunction(), getGlIDs(), registerJunction(), removeSolitaryJunctions(), renameJunction(), retrieveJunction(), retrieveJunctions(), and ~GNENet().
bool GNENet::myNeedRecompute protected
whether the net needs recomputation
Definition at line 557 of file GNENet.h.
Referenced by computeAndUpdate(), computeEverything(), and requireRecompute().
NBNetBuilder* GNENet::myNetBuilder protected
The internal netbuilder.
Definition at line 526 of file GNENet.h.
Referenced by computeAndUpdate(), deleteSingleEdge(), deleteSingleJunction(), getNetBuilder(), getTLLogicCont(), GNENet(), insertEdge(), insertJunction(), joinSelectedJunctions(), netHasCrossings(), renameEdge(), renameJunction(), save(), saveJoined(), savePlain(), and ~GNENet().
GUIShapeContainer GNENet::myShapeContainer protected
the container for additional pois and polygons
Definition at line 551 of file GNENet.h.
Referenced by getShapeContainer().
GNEViewNet* GNENet::myViewNet protected
The viewNet to be notofied of about changes.
Definition at line 523 of file GNENet.h.
Referenced by deleteConnection(), getApp(), getViewNet(), setViewNet(), and update().
Boundary GNENet::myZBoundary private
the z boundary (stored in the x-coordinate), values of 0 are ignored
Definition at line 602 of file GNENet.h.
Referenced by getZBoundary(), GNENet(), and registerJunction().
const RGBColor GNENet::selectedConnectionColor static
color of selected connection
Definition at line 103 of file GNENet.h.
Referenced by GNEConnection::drawGL().
const RGBColor GNENet::selectedLaneColor static
color of selected lane
Definition at line 100 of file GNENet.h.
Referenced by GNELane::drawGL().
const RGBColor GNENet::selectionColor static
color of selection
Definition at line 97 of file GNENet.h.
Referenced by GNEViewNet::doPaintGL(), GNEEdge::drawGL(), GNELane::drawGL(), GNELane::drawMarkings(), and GNEJunction::setColor().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
const double GNENet::Z_INITIALIZED = 1 static private
marker for whether the z-boundary is initialized
Definition at line 605 of file GNENet.h.
Referenced by GNENet(), and registerJunction().
The documentation for this class was generated from the following files:
GNENet.h
GNENet.cpp