SUMO - Simulation of Urban MObility: GUIIconSubSys Class Reference
GUIIconSubSys Class Reference
#include <GUIIconSubSys.h>
Static Public Member Functions
static void close ()
close GUIIconSubSys
static FXIcon * getIcon (GUIIcon which)
returns a icon previously defined in the enum GUIIcon
static void initIcons (FXApp *a)
Initiate GUIIconSubSys.
Private Member Functions
GUIIconSubSys (FXApp *a)
constructor is private because is called by the static function init(FXApp* a)
~GUIIconSubSys ()
destructor
Private Attributes
FXIcon * myIcons [ICON_MAX]
vector with the icons
Static Private Attributes
static GUIIconSubSys * myInstance = 0
instance of GUIIconSubSys
Detailed Description
Definition at line 40 of file GUIIconSubSys.h.
Constructor & Destructor Documentation
GUIIconSubSys::GUIIconSubSys (FXApp * a) private
constructor is private because is called by the static function init(FXApp* a)
Definition at line 221 of file GUIIconSubSys.cpp.
References flag, flag_minus, flag_plus, ICON_ACCEPT, ICON_ADD, ICON_ALLOWROTATION, ICON_APP, ICON_APP_BREAKPOINTS, ICON_APP_FINDER, ICON_APP_SELECTOR, ICON_APP_TABLE, ICON_APP_TLSTRACKER, ICON_APP_TRACKER, ICON_BUSSTOP, ICON_CALIBRATOR, ICON_CAMERA, ICON_CANCEL, ICON_CHARGINGSTATION, ICON_CLEANJUNCTIONS, ICON_CLOSE, ICON_CLOSE_GAPS, ICON_CLOSING, ICON_COLORWHEEL, ICON_COMPUTEJUNCTIONS, ICON_CONNECTION, ICON_CONTAINERSTOP, ICON_CORRECT, ICON_CREATE_GRAPH, ICON_CROSSING, ICON_CUT_SWELL, ICON_DILATE, ICON_DLR, ICON_E1, ICON_E2, ICON_E3, ICON_E3ENTRY, ICON_E3EXIT, ICON_EDGE, ICON_EDITGRAPH, ICON_EDITVIEWPORT, ICON_EMPTY, ICON_ERASE_STAINS, ICON_ERODE, ICON_ERROR, ICON_EXT, ICON_EXTRACT, ICON_EYEDROP, ICON_FLAG, ICON_FLAG_MINUS, ICON_FLAG_PLUS, ICON_GREENEDGE, ICON_GREENPERSON, ICON_GREENVEHICLE, ICON_GRID1, ICON_GRID2, ICON_GRID3, ICON_JOINJUNCTIONS, ICON_JUNCTION, ICON_LAGGRVIEW, ICON_LANE, ICON_LANEBIKE, ICON_LANEBUS, ICON_LANEPEDESTRIAN, ICON_LOCATE, ICON_LOCATEADD, ICON_LOCATEEDGE, ICON_LOCATEJUNCTION, ICON_LOCATEPERSON, ICON_LOCATEPOI, ICON_LOCATEPOLY, ICON_LOCATETLS, ICON_LOCATEVEHICLE, ICON_LOCK, ICON_MANIP, ICON_MAX, ICON_MICROVIEW, ICON_MODEADDITIONAL, ICON_MODECONNECTION, ICON_MODECREATEEDGE, ICON_MODECROSSING, ICON_MODEDELETE, ICON_MODEINSPECT, ICON_MODEMOVE, ICON_MODESELECT, ICON_MODETLS, ICON_NETEDIT, ICON_NETEDITARROW, ICON_NO, ICON_OK, ICON_OPEN_ADDITIONALS, ICON_OPEN_BMP_DIALOG, ICON_OPEN_CONFIG, ICON_OPEN_NET, ICON_OPEN_SHAPES, ICON_OPENING, ICON_OPTIONS, ICON_PAINTBRUSH1X, ICON_PAINTBRUSH2X, ICON_PAINTBRUSH3X, ICON_PAINTBRUSH4X, ICON_PAINTBRUSH5X, ICON_PROHIBITION, ICON_RARIFY, ICON_RECENTERVIEW, ICON_REDO, ICON_RELOAD, ICON_REMOVE, ICON_REMOVEDB, ICON_REROUTER, ICON_RESET, ICON_ROUTEPROBE, ICON_RUBBER1X, ICON_RUBBER2X, ICON_RUBBER3X, ICON_RUBBER4X, ICON_RUBBER5X, ICON_SAVE, ICON_SAVEDB, ICON_SHOWTOOLTIPS, ICON_SKELETONIZE, ICON_START, ICON_STEP, ICON_STOP, ICON_SUMO, ICON_UNDO, ICON_VAPORIZER, ICON_VARIABLESPEEDSIGN, ICON_VCLASS_ARMY, ICON_VCLASS_AUTHORITY, ICON_VCLASS_BICYCLE, ICON_VCLASS_BUS, ICON_VCLASS_COACH, ICON_VCLASS_CUSTOM1, ICON_VCLASS_CUSTOM2, ICON_VCLASS_DELIVERY, ICON_VCLASS_EMERGENCY, ICON_VCLASS_EVEHICLE, ICON_VCLASS_HOV, ICON_VCLASS_IGNORING, ICON_VCLASS_MOPED, ICON_VCLASS_MOTORCYCLE, ICON_VCLASS_PASSENGER, ICON_VCLASS_PEDESTRIAN, ICON_VCLASS_PRIVATE, ICON_VCLASS_RAIL, ICON_VCLASS_RAIL_ELECTRIC, ICON_VCLASS_RAIL_URBAN, ICON_VCLASS_SHIP, ICON_VCLASS_TAXI, ICON_VCLASS_TRAILER, ICON_VCLASS_TRAM, ICON_VCLASS_TRUCK, ICON_VCLASS_VIP, ICON_WARNING, ICON_WINDOWS_CASCADE, ICON_WINDOWS_TILE_HORI, ICON_WINDOWS_TILE_VERT, ICON_YELLOWEDGE, ICON_YELLOWPERSON, ICON_YELLOWVEHICLE, ICON_YES, ICON_ZOOMSTYLE, manip, and myIcons.
Referenced by initIcons().
GUIIconSubSys::~GUIIconSubSys () private
destructor
Definition at line 407 of file GUIIconSubSys.cpp.
References ICON_MAX, and myIcons.
Member Function Documentation
void GUIIconSubSys::close () static
close GUIIconSubSys
Definition at line 428 of file GUIIconSubSys.cpp.
References myInstance.
Referenced by GNEApplicationWindow::~GNEApplicationWindow(), and GUIApplicationWindow::~GUIApplicationWindow().
FXIcon * GUIIconSubSys::getIcon (GUIIcon which) static
returns a icon previously defined in the enum GUIIcon
Parameters
[in] which GUIIcon enum
Definition at line 422 of file GUIIconSubSys.cpp.
References myIcons, and myInstance.
Referenced by GNEAdditionalFrame::AdditionalAttributeList::AdditionalAttributeList(), GUIGlObject::buildCenterPopupEntry(), GUIGlChildWindow::buildColoringToolBar(), GNEViewNet::buildEditModeControls(), GUIGlChildWindow::buildNavigationToolBar(), GUIGlChildWindow::buildScreenshotToolBar(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowManipulatorPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUIGlObject::buildShowTypeParamsPopupEntry(), GUIParameterTracker::buildToolBar(), GUIApplicationWindow::buildToolBars(), GNEDialog_AllowDisallow::buildVClass(), GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNEApplicationWindow::dependentBuild(), GUIApplicationWindow::dependentBuild(), GNEApplicationWindow::fillMenuBar(), GUIApplicationWindow::fillMenuBar(), GNEAttributeCarrier::getIcon(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GNEAdditionalDialog::GNEAdditionalDialog(), GNECalibratorDialog::GNECalibratorDialog(), GNEConnectorFrame::GNEConnectorFrame(), GNEDialog_About::GNEDialog_About(), GNEDialog_AllowDisallow::GNEDialog_AllowDisallow(), GNEDialog_Wizard::GNEDialog_Wizard(), GNEInspectorFrame::GNEInspectorFrame(), GNERerouterDialog::GNERerouterDialog(), GNERerouterIntervalDialog::GNERerouterIntervalDialog(), GNEViewParent::GNEViewParent(), GUIDialog_AboutSUMO::GUIDialog_AboutSUMO(), GUIDialog_AppSettings::GUIDialog_AppSettings(), GUIDialog_Breakpoints::GUIDialog_Breakpoints(), GUIDialog_EditViewport::GUIDialog_EditViewport(), GUIDialog_GLChosenEditor::GUIDialog_GLChosenEditor(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUIDialog_ViewSettings::GUIDialog_ViewSettings(), GUIParameterTableWindow::GUIParameterTableWindow(), GUIParameterTracker::GUIParameterTracker(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), GUIApplicationWindow::handleEvent_SimulationStep(), GUIParameterTableItem< T >::init(), GNEDeleteFrame::markAttributeCarrier(), GNEDialog_AllowDisallow::onCmdAccept(), GNERerouterIntervalDialog::onCmdChangeBeginEnd(), GNERerouterIntervalDialog::onCmdEditClosingLaneReroute(), GNERerouterIntervalDialog::onCmdEditClosingReroute(), GNERerouterIntervalDialog::onCmdEditDestProbReroute(), GNERerouterIntervalDialog::onCmdEditRouteProbReroute(), GUIDialog_ViewSettings::onCmdExportSetting(), GUIDialog_GLObjChooser::onCmdFilter(), GNESelectorFrame::onCmdHelp(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEAdditionalFrame::NeteditAttributes::onCmdHelp(), GUIDialog_ViewSettings::onCmdImportSetting(), GUIDialog_Breakpoints::onCmdLoad(), GNESelectorFrame::onCmdLoad(), GUIDialog_EditViewport::onCmdLoad(), GUIDialog_GLChosenEditor::onCmdLoad(), GUIDialog_ViewSettings::onCmdLoadDecals(), GUISUMOViewParent::onCmdLocate(), GNEViewParent::onCmdLocate(), GUISUMOViewParent::onCmdMakeSnapshot(), GNEViewParent::onCmdMakeSnapshot(), GNEApplicationWindow::onCmdOpenAdditionals(), GNEApplicationWindow::onCmdOpenConfiguration(), GUIApplicationWindow::onCmdOpenConfiguration(), GNEApplicationWindow::onCmdOpenForeign(), GNEApplicationWindow::onCmdOpenNetwork(), GUIApplicationWindow::onCmdOpenNetwork(), GNEApplicationWindow::onCmdOpenShapes(), GUIApplicationWindow::onCmdOpenShapes(), GNEDialog_AllowDisallow::onCmdReset(), GUIDialog_Breakpoints::onCmdSave(), GNESelectorFrame::onCmdSave(), GUIDialog_EditViewport::onCmdSave(), GUIDialog_GLChosenEditor::onCmdSave(), GUIParameterTracker::onCmdSave(), GNEApplicationWindow::onCmdSaveAdditionals(), GNEApplicationWindow::onCmdSaveAdditionalsAs(), GNEApplicationWindow::onCmdSaveAsNetwork(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GUIDialog_ViewSettings::onCmdSaveDecals(), GNEApplicationWindow::onCmdSaveJoined(), GNEApplicationWindow::onCmdSavePois(), GNEDialog_AllowDisallow::onCmdSelectAll(), GNEDialog_AllowDisallow::onCmdSelectOnlyNonRoad(), GUIDialog_GLObjChooser::onCmdToggleSelection(), GNEDialog_AllowDisallow::onCmdUnselectAll(), GNEDialog_AllowDisallow::onCmdValueChanged(), GUIApplicationWindow::openNewView(), GNECalibratorVehicleTypeDialog::setVClassLabelImage(), GNERerouterIntervalDialog::updateClosingLaneReroutesTable(), GNERerouterIntervalDialog::updateClosingReroutesTable(), GNEDeleteFrame::updateCurrentLabel(), GNERerouterIntervalDialog::updateDestProbReroutesTable(), GNECalibratorDialog::updateFlowTable(), GNERerouterDialog::updateIntervalTable(), GNERerouterIntervalDialog::updateRouteProbReroutesTable(), GNECalibratorDialog::updateRouteTable(), GNEVariableSpeedSignDialog::updateTable(), and GNECalibratorDialog::updateVehicleTypeTable().
void GUIIconSubSys::initIcons (FXApp * a) static
Initiate GUIIconSubSys.
Parameters
[in] a FOX Toolkit APP
Definition at line 415 of file GUIIconSubSys.cpp.
References GUIIconSubSys(), and myInstance.
Referenced by GNEApplicationWindow::GNEApplicationWindow(), and GUIApplicationWindow::GUIApplicationWindow().
Field Documentation
FXIcon* GUIIconSubSys::myIcons[ICON_MAX] private
vector with the icons
Definition at line 66 of file GUIIconSubSys.h.
Referenced by getIcon(), GUIIconSubSys(), and ~GUIIconSubSys().
GUIIconSubSys * GUIIconSubSys::myInstance = 0 static private
instance of GUIIconSubSys
Definition at line 63 of file GUIIconSubSys.h.
Referenced by close(), getIcon(), and initIcons().
The documentation for this class was generated from the following files:
GUIIconSubSys.h
GUIIconSubSys.cpp