SUMO - Simulation of Urban MObility: MSVehicle Class Reference
MSVehicle Class Reference
Representation of a vehicle in the micro simulation.
#include <MSVehicle.h>
Data Structures
struct DriveProcessItem
class Influencer
Changes the wished vehicle speed / lanes.
struct LaneQ
A structure representing the best lanes for continuing the current route starting at 'lane'.
class State
Container that holds the vehicles driving state (position+speed).
struct Stop
Definition of vehicle stop (position and duration)
class WaitingTimeCollector
Stores the waiting intervals over the previous seconds (memory is to be specified in ms.).
Public Types
enum ChangeRequest { REQUEST_NONE, REQUEST_LEFT, REQUEST_RIGHT, REQUEST_HOLD }
Requests set via TraCI.
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
void activateReminders (const MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
"Activates" all current move reminder
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
void addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
bool addTraciStop (MSLane *const lane, const double startPos, const double endPos, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, std::string &errorMsg)
bool addTraciStopAtStoppingPlace (const std::string &stopId, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, const SumoXMLTag stoppingPlaceType, std::string &errorMsg)
double computeAngle () const
compute the current vehicle angle
bool congested () const
void createDevice (const std::string &deviceName)
create device of the given type
void enterLaneAtInsertion (MSLane *enteredLane, double pos, double speed, double posLat, MSMoveReminder::Notification notification)
Update when the vehicle enters a new lane in the emit step.
void enterLaneAtLaneChange (MSLane *enteredLane)
Update when the vehicle enters a new lane in the laneChange step.
bool enterLaneAtMove (MSLane *enteredLane, bool onTeleporting=false)
Update when the vehicle enters a new lane in the move step.
bool executeMove ()
Executes planned vehicle movements with regards to right-of-way.
void fixPosition ()
repair errors in vehicle position after changing between internal edges
virtual double getArrivalPos () const
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
PositionVector getBoundingBox () const
get bounding rectangle
PositionVector getBoundingPoly () const
get bounding polygon
const MSCFModel & getCarFollowModel () const
Returns the vehicle's car following model definition.
MSCFModel::VehicleVariables * getCarFollowVariables () const
Returns the vehicle's car following model variables.
double getChosenSpeedFactor () const
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
const MSRouteIterator & getCurrentRouteEdge () const
Returns an iterator pointing to the current edge in this vehicles route.
double getDeltaPos (double accel)
calculates the distance covered in the next integration step given an acceleration and assuming the current velocity. (gives different results for different integration methods, e.g., euler vs. ballistic)
SUMOTime getDepartDelay () const
Returns the depart delay.
double getDepartPos () const
Returns this vehicle's real departure position.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
MSDevice * getDevice (const std::type_info &type) const
Returns a device of the given type if it exists or 0.
std::string getDeviceParameter (const std::string &deviceName, const std::string &key) const
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
double getDistanceToPosition (double destPos, const MSEdge *destEdge) const
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
const std::vector< MSLane * > & getFurtherLanes () const
const std::vector< double > & getFurtherLanesPosLat () const
const std::string & getID () const
Returns the name of the vehicle.
double getImpatience () const
Returns this vehicles impatience.
Influencer & getInfluencer ()
Returns the velocity/lane influencer.
const Influencer * getInfluencer () const
MSAbstractLaneChangeModel & getLaneChangeModel ()
const MSAbstractLaneChangeModel & getLaneChangeModel () const
int getLaneIndex () const
std::pair< const MSVehicle *const, double > getLeader (double dist=0) const
Returns the leader of the vehicle looking for a fixed distance.
double getMaxSpeed () const
Returns the maximum speed.
Stop & getNextStop ()
int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition)
const MSRoute & getRoute () const
Returns the current route.
double getSafeFollowSpeed (const std::pair< const MSVehicle *, double > leaderInfo, const double seen, const MSLane *const lane, double distToCrossing) const
compute safe speed for following the given leader
double getSpeedWithoutTraciInfluence () const
Returns the uninfluenced velocity.
double getTimeGapOnLane () const
Returns the time gap in seconds to the leader of the vehicle on the same lane.
SUMOVehicleClass getVClass () const
Returns the vehicle's access class.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
bool hasDeparted () const
Returns whether this vehicle has already departed.
bool hasDevice (const std::string &deviceName) const
check whether the vehicle is equiped with a device of the given type
bool hasInfluencer () const
bool hasValidRoute (std::string &msg, const MSRoute *route=0) const
Validates the current or given route.
int influenceChangeDecision (int state)
allow TraCI to influence a lane change decision
virtual bool isSelected () const
whether this vehicle is selected in the GUI
bool knowsEdgeTest (MSEdge &edge) const
void leaveLane (const MSMoveReminder::Notification reason, const MSLane *approachedLane=0)
Update of members if vehicle leaves a new lane in the lane change step or at arrival.
MSVehicle (SUMOVehicleParameter *pars, const MSRoute *route, const MSVehicleType *type, const double speedFactor)
Constructor.
void onDepart ()
Called when the vehicle is inserted into the network.
bool onFurtherEdge (const MSEdge *edge) const
whether this vehicle has its back (and no its front) on the given edge
void planMove (const SUMOTime t, const MSLeaderInfo &ahead, const double lengthsInFront)
Compute safe velocities for the upcoming lanes based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
double processNextStop (double currentVelocity)
Processes stops, returns the velocity needed to reach the stop.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false, bool addStops=true)
Replaces the current route by the given edges.
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)
Performs a rerouting using the given router.
bool resumeFromStopping ()
void setAngle (double angle)
Set a custom vehicle angle in rad.
virtual void setArrivalPos (double arrivalPos)
Sets this vehicle's desired arrivalPos for its current route.
void setChosenSpeedFactor (const double factor)
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
void setDeviceParameter (const std::string &deviceName, const std::string &key, const std::string &value)
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
void setTentativeLaneAndPosition (MSLane *lane, double pos, double posLat=0)
set tentative lane and position during insertion to ensure that all cfmodels work (some of them require veh->getLane() to return a valid lane) Once the vehicle is sucessfully inserted the lane is set again (see enterLaneAtInsertion)
void setVTDState (Position xyPos)
sets position outside the road network
const MSEdge * succEdge (int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
bool unsafeLinkAhead (const MSLane *lane) const
whether the vehicle may safely move to the given lane with regard to upcoming links
double updateFurtherLanes (std::vector< MSLane * > &furtherLanes, std::vector< double > &furtherLanesPosLat, const std::vector< MSLane * > &passedLanes)
update a vector of further lanes and return the new backPos
virtual ~MSVehicle ()
Destructor.
insertion/removal
void onRemovalFromNet (const MSMoveReminder::Notification reason)
Called when the vehicle is removed from the network.
interaction with the route
bool hasArrived () const
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0, bool addStops=true)
Replaces the current route by the given one.
bool willPass (const MSEdge *const edge) const
Returns whether the vehicle wil pass the given edge.
int getRoutePosition () const
void resetRoutePosition (int index)
const MSEdgeWeightsStorage & getWeightsStorage () const
Returns the vehicle's internal edge travel times/efforts container.
MSEdgeWeightsStorage & getWeightsStorage ()
state setter/getter
double getPositionOnLane () const
Get the vehicle's position along the lane.
double getLastStepDist () const
Get the distance the vehicle covered in the previous timestep.
double getPositionOnLane (const MSLane *lane) const
Get the vehicle's front position relative to the given lane.
double getBackPositionOnLane (const MSLane *lane) const
Get the vehicle's position relative to the given lane.
double getBackPositionOnLane () const
Get the vehicle's position relative to its current lane.
double getLateralPositionOnLane () const
Get the vehicle's lateral position on the lane.
double getRightSideOnLane () const
Get the vehicle's lateral position on the lane:
double getLateralOverlap () const
return the amount by which the vehicle extends laterally outside it's primary lane
double getRightSideOnEdge (const MSLane *lane=0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
double getCenterOnEdge (const MSLane *lane=0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
double getLatOffset (const MSLane *lane) const
Get the offset that that must be added to interpret myState.myPosLat for the given lane.
double getSpeed () const
Returns the vehicle's current speed.
double getPreviousSpeed () const
Returns the vehicle's speed before the previous time step.
double getAcceleration () const
Returns the vehicle's acceleration in m/s (this is computed as the last step's mean acceleration in case that a stop occurs within the middle of the time-step)
Other getter methods
double getSlope () const
Returns the slope of the road at vehicle's position.
Position getPosition (const double offset=0) const
Return current position (x/y, cartesian)
MSLane * getLane () const
Returns the lane the vehicle is on.
double getMaxSpeedOnLane () const
Returns the maximal speed for the vehicle on its current lane (including speed factor and deviation, i.e., not necessarily the allowed speed limit)
bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated)
bool isFrontOnLane (const MSLane *lane) const
Returns the information whether the front of the vehicle is on the given lane.
const MSEdge * getRerouteOrigin () const
Returns the starting point for reroutes (usually the current edge)
SUMOTime getWaitingTime () const
Returns the SUMOTime waited (speed was lesser than 0.1m/s)
SUMOTime getTimeLoss () const
Returns the SUMOTime lost (speed was lesser maximum speed)
SUMOTime getAccumulatedWaitingTime (SUMOTime t=MSGlobals::gWaitingTimeMemory) const
Returns the SUMOTime waited (speed was lesser than 0.1m/s) within the last t millisecs.
double getWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s)
double getAccumulatedWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s) within the last millisecs.
double getTimeLossSeconds () const
Returns the time loss in seconds.
double getAngle () const
Returns the vehicle's direction in radians.
Position getVelocityVector () const
Returns the vehicle's direction in radians.
strategical/tactical lane choosing methods
const std::vector< LaneQ > & getBestLanes () const
Returns the description of best lanes to use in order to continue the route.
void updateBestLanes (bool forceRebuild=false, const MSLane *startLane=0)
computes the best lanes to use in order to continue the route
const std::vector< MSLane * > & getBestLanesContinuation () const
Returns the best sequence of lanes to continue the route starting at myLane.
const std::vector< MSLane * > & getBestLanesContinuation (const MSLane *const l) const
Returns the best sequence of lanes to continue the route starting at the given lane.
int getBestLaneOffset () const
void adaptBestLanesOccupation (int laneIndex, double density)
update occupation from MSLaneChanger
vehicle stops definitions and i/o
bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0, bool collision=false)
Adds a stop.
bool replaceParkingArea (MSParkingArea *parkingArea, std::string &errorMsg)
replace the current parking area stop with a new stop with merge duration
MSParkingArea * getNextParkingArea ()
get the current parking area stop
bool hasStops () const
Returns whether the vehicle has to stop somewhere.
bool isStopped () const
Returns whether the vehicle is at a stop.
SUMOTime collisionStopTime () const
Returns the remaining time a vehicle needs to stop due to a collision. A negative value indicates that the vehicle is not stopping due to a collision (or at all)
bool isParking () const
Returns whether the vehicle is parking.
bool isRemoteControlled () const
Returns the information whether the vehicle is fully controlled via TraCI.
bool wasRemoteControlled (SUMOTime lookBack=DELTA_T) const
Returns the information whether the vehicle is fully controlled via TraCI within the lookBack time.
double nextStopDist () const
return the distance to the next stop or doubleMax if there is none.
bool isStoppedTriggered () const
Returns whether the vehicle is on a triggered stop.
bool isStoppedInRange (double pos) const
return whether the given position is within range of the current stop
Emission retrieval
double getCO2Emissions () const
Returns CO2 emission of the current state.
double getCOEmissions () const
Returns CO emission of the current state.
double getHCEmissions () const
Returns HC emission of the current state.
double getNOxEmissions () const
Returns NOx emission of the current state.
double getPMxEmissions () const
Returns PMx emission of the current state.
double getFuelConsumption () const
Returns fuel consumption of the current state.
double getElectricityConsumption () const
Returns electricity consumption of the current state.
double getHarmonoise_NoiseEmissions () const
Returns noise emissions of the current state.
Interaction with persons
void addPerson (MSTransportable *person)
Adds a passenger.
Interaction with containers
void addContainer (MSTransportable *container)
Adds a container.
void removeTransportable (MSTransportable *t)
removes a person or container
const std::vector< MSTransportable * > & getPersons () const
retrieve riding persons
const std::vector< MSTransportable * > & getContainers () const
retrieve riding containers
int getPersonNumber () const
Returns the number of persons.
int getContainerNumber () const
Returns the number of containers.
state io
void saveState (OutputDevice &out)
Saves the states of a vehicle.
void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)
Loads the state of this vehicle from the given description.
Static Public Member Functions
static int nextLinkPriority (const std::vector< MSLane * > &conts)
get a numerical value for the priority of the upcoming link
static bool overlap (const MSVehicle *veh1, const MSVehicle *veh2)
Protected Types
typedef std::vector< DriveProcessItem > DriveItemVector
Container for used Links/visited Lanes during lookForward.
Protected Member Functions
void adaptToLeader (const std::pair< const MSVehicle *, double > leaderInfo, const double seen, DriveProcessItem *const lastLink, const MSLane *const lane, double &v, double &vLinkPass, double distToCrossing=-1) const
void adaptToLeaders (const MSLeaderInfo &ahead, double latOffset, const double seen, DriveProcessItem *const lastLink, const MSLane *const lane, double &v, double &vLinkPass) const
void calculateArrivalParams ()
(Re-)Calculates the arrival position and lane from the vehicle parameters
void checkLinkLeader (const MSLink *link, const MSLane *lane, double seen, DriveProcessItem *const lastLink, double &v, double &vLinkPass, double &vLinkWait, bool &setRequest) const
checks for link leaders on the given link
void checkRewindLinkLanes (const double lengthsInFront, DriveItemVector &lfLinks) const
virtual void drawOutsideNetwork (bool)
register vehicle for drawing while outside the network
double estimateLeaveSpeed (const MSLink *const link, const double vLinkPass) const
estimate leaving speed when accelerating across a link
const MSLane * getBackLane () const
const Position getBackPosition () const
double getSpaceTillLastStanding (const MSLane *l, bool &foundStopped) const
const ConstMSEdgeVector getStopEdges () const
Returns the list of still pending stop edges.
void planMoveInternal (const SUMOTime t, MSLeaderInfo ahead, DriveItemVector &lfLinks, double &myStopDist) const
void removeApproachingInformation (DriveItemVector &lfLinks) const
unregister approach from all upcoming links
void setBlinkerInformation ()
void setEmergencyBlueLight (SUMOTime currentTime)
sets the blue flashing light for emergency vehicles
void updateOccupancyAndCurrentBestLane (const MSLane *startLane)
updates LaneQ::nextOccupation and myCurrentLaneInBestLanes
void updateState (double vNext)
updates the vehicles state, given a next value for its speed. This value can be negative in case of the ballistic update to indicate a stop within the next timestep. (You can call this a 'hack' to emulate reasoning based on accelerations: The assumed constant acceleration a within the next time step is then a = (vNext - vCurrent)/TS)
Protected Attributes
double myAcceleration
The current acceleration after dawdling in m/s.
bool myAmOnNet
Whether the vehicle is on the network (not parking, teleported, vaporized, or arrived)
bool myAmRegisteredAsWaitingForContainer
Whether this vehicle is registered as waiting for a container (for deadlock-recognition)
bool myAmRegisteredAsWaitingForPerson
Whether this vehicle is registered as waiting for a person (for deadlock-recognition)
double myAngle
the angle in radians (
int myArrivalLane
The destination lane where the vehicle stops.
double myArrivalPos
The position on the destination lane where the vehicle stops.
std::vector< std::vector< LaneQ > > myBestLanes
Position myCachedPosition
double myChosenSpeedFactor
A precomputed factor by which the driver wants to be faster than the speed limit.
SUMOTime myCollisionImmunity
amount of time for which the vehicle is immune from collisions
MSDevice_Transportable * myContainerDevice
The containers this vehicle may have.
MSRouteIterator myCurrEdge
Iterator to current route-edge.
std::vector< LaneQ >::iterator myCurrentLaneInBestLanes
double myDepartPos
The real depart position.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
std::vector< MSLane * > myFurtherLanes
The information into which lanes the vehicle laps into.
std::vector< double > myFurtherLanesPosLat
bool myHaveToWaitOnNextLink
MSLane * myLane
The lane the vehicle is on.
MSAbstractLaneChangeModel * myLaneChangeModel
const MSEdge * myLastBestLanesEdge
const MSLane * myLastBestLanesInternalLane
DriveItemVector myLFLinkLanes
int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This Vehicle's parameter.
MSDevice_Transportable * myPersonDevice
The passengers this vehicle may have.
const MSRoute * myRoute
This Vehicle's route.
int mySignals
State of things of the vehicle that can be on or off.
State myState
This Vehicles driving state (pos and speed)
double myStopDist
distance to the next stop or -1 if there is none
std::list< Stop > myStops
The vehicle's list of stops.
SUMOTime myTimeLoss
the time loss due to writing with less than maximum speed
const MSVehicleType * myType
This Vehicle's type.
SUMOTime myWaitingTime
The time the vehicle waits (is not faster than 0.1m/s) in seconds.
WaitingTimeCollector myWaitingTimeCollector
Static Protected Attributes
static std::vector< MSLane * > myEmptyLaneVector
static std::vector< MSTransportable * > myEmptyTransportableVector
static const SUMOTime NOT_YET_DEPARTED = SUMOTime_MAX
Private Member Functions
MSEdgeWeightsStorage & _getWeightsStorage () const
MSVehicle ()
invalidated default constructor
MSVehicle (const MSVehicle &)
invalidated copy constructor
MSVehicle & operator= (const MSVehicle &)
invalidated assignment operator
Private Attributes
MSCFModel::VehicleVariables * myCFVariables
The per vehicle variables of the car following model.
MSEdgeWeightsStorage * myEdgeWeights
Influencer * myInfluencer
An instance of a velocity/lane influencing instance; built in "getInfluencer".
Friends
class MSLaneChanger
the lane changer sets myLastLaneChangeOffset
class MSLaneChangerSublane
Move reminder structures
typedef std::vector< std::pair< MSMoveReminder *, double > > MoveReminderCont
Definition of a move reminder container.
MoveReminderCont myMoveReminders
Currently relevant move reminders.
Interaction with move reminders
void workOnMoveReminders (double oldPos, double newPos, double newSpeed)
Processes active move reminder.
void adaptLaneEntering2MoveReminder (const MSLane &enteredLane)
Adapts the vehicle's entering of a new lane.
Access to bool signals
enum Signalling {
VEH_SIGNAL_NONE = 0, VEH_SIGNAL_BLINKER_RIGHT = 1, VEH_SIGNAL_BLINKER_LEFT = 2, VEH_SIGNAL_BLINKER_EMERGENCY = 4,
VEH_SIGNAL_BRAKELIGHT = 8, VEH_SIGNAL_FRONTLIGHT = 16, VEH_SIGNAL_FOGLIGHT = 32, VEH_SIGNAL_HIGHBEAM = 64,
VEH_SIGNAL_BACKDRIVE = 128, VEH_SIGNAL_WIPER = 256, VEH_SIGNAL_DOOR_OPEN_LEFT = 512, VEH_SIGNAL_DOOR_OPEN_RIGHT = 1024,
VEH_SIGNAL_EMERGENCY_BLUE = 2048, VEH_SIGNAL_EMERGENCY_RED = 4096, VEH_SIGNAL_EMERGENCY_YELLOW = 8192
}
Some boolean values which describe the state of some vehicle parts.
enum LaneChangeMode { LC_NEVER = 0, LC_NOCONFLICT = 1, LC_ALWAYS = 2 }
modes for resolving conflicts between external control (traci) and vehicle control over lane changing. Each level of the lane-changing hierarchy (strategic, cooperative, speedGain, keepRight) can be controlled separately
enum TraciLaneChangePriority { LCP_ALWAYS = 0, LCP_NOOVERLAP = 1, LCP_URGENT = 2, LCP_OPPORTUNISTIC = 3 }
modes for prioritizing traci lane change requests
void switchOnSignal (int signal)
Switches the given signal on.
void switchOffSignal (int signal)
Switches the given signal off.
int getSignals () const
Returns the signals.
bool signalSet (int which) const
Returns whether the given signal is on.
Detailed Description
Representation of a vehicle in the micro simulation.
Definition at line 83 of file MSVehicle.h.
Member Typedef Documentation
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess inherited
Definition at line 80 of file SUMOVehicle.h.
typedef std::vector< DriveProcessItem > MSVehicle::DriveItemVector protected
Container for used Links/visited Lanes during lookForward.
Definition at line 1626 of file MSVehicle.h.
typedef std::vector< std::pair<MSMoveReminder*, double> > MSBaseVehicle::MoveReminderCont protected inherited
Definition of a move reminder container.
Definition at line 427 of file MSBaseVehicle.h.
Member Enumeration Documentation
enum MSVehicle::ChangeRequest
Requests set via TraCI.
Enumerator
REQUEST_NONE
vehicle doesn't want to change
REQUEST_LEFT
vehicle want's to change to left lane
REQUEST_RIGHT
vehicle want's to change to right lane
REQUEST_HOLD
vehicle want's to keep the current lane
Definition at line 222 of file MSVehicle.h.
enum MSVehicle::LaneChangeMode
modes for resolving conflicts between external control (traci) and vehicle control over lane changing. Each level of the lane-changing hierarchy (strategic, cooperative, speedGain, keepRight) can be controlled separately
Enumerator
LC_NEVER
LC_NOCONFLICT
LC_ALWAYS
Definition at line 1105 of file MSVehicle.h.
enum MSVehicle::Signalling
Some boolean values which describe the state of some vehicle parts.
Enumerator
VEH_SIGNAL_NONE
Everything is switched off.
VEH_SIGNAL_BLINKER_RIGHT
Right blinker lights are switched on.
VEH_SIGNAL_BLINKER_LEFT
Left blinker lights are switched on.
VEH_SIGNAL_BLINKER_EMERGENCY
Blinker lights on both sides are switched on.
VEH_SIGNAL_BRAKELIGHT
The brake lights are on.
VEH_SIGNAL_FRONTLIGHT
The front lights are on (no visualisation)
VEH_SIGNAL_FOGLIGHT
The fog lights are on (no visualisation)
VEH_SIGNAL_HIGHBEAM
The high beam lights are on (no visualisation)
VEH_SIGNAL_BACKDRIVE
The backwards driving lights are on (no visualisation)
VEH_SIGNAL_WIPER
The wipers are on.
VEH_SIGNAL_DOOR_OPEN_LEFT
One of the left doors is opened.
VEH_SIGNAL_DOOR_OPEN_RIGHT
One of the right doors is opened.
VEH_SIGNAL_EMERGENCY_BLUE
A blue emergency light is on.
VEH_SIGNAL_EMERGENCY_RED
A red emergency light is on.
VEH_SIGNAL_EMERGENCY_YELLOW
A yellow emergency light is on.
Definition at line 1067 of file MSVehicle.h.
enum MSVehicle::TraciLaneChangePriority
modes for prioritizing traci lane change requests
Enumerator
LCP_ALWAYS
LCP_NOOVERLAP
LCP_URGENT
LCP_OPPORTUNISTIC
Definition at line 1113 of file MSVehicle.h.
Constructor & Destructor Documentation
MSVehicle::MSVehicle (SUMOVehicleParameter * pars, const MSRoute * route, const MSVehicleType * type, const double speedFactor)
Constructor.
Parameters
[in] pars The vehicle description
[in] route The vehicle's route
[in] type The vehicle's type
[in] speedFactor The factor for driven lane's speed limits
Exceptions
ProcessError If a value is wrong
Definition at line 528 of file MSVehicle.cpp.
References MSAbstractLaneChangeModel::build(), MSCFModel::createVehicleVariables(), DEPART_LANE_GIVEN, DEPART_SPEED_GIVEN, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSEdge::EDGEFUNCTION_DISTRICT, MSVehicleType::getCarFollowModel(), MSVehicleType::getID(), MSVehicleType::getLaneChangeModel(), MSVehicleType::getMaxSpeed(), MSVehicleType::getVehicleClass(), SUMOVehicleParameter::id, myCFVariables, and myLaneChangeModel.
MSVehicle::~MSVehicle () virtual
Destructor.
Definition at line 575 of file MSVehicle.cpp.
References MSVehicleType::amVehicleSpecific(), MSAbstractLaneChangeModel::cleanupShadowLane(), myEdgeWeights, myFurtherLanes, myFurtherLanesPosLat, myInfluencer, myLaneChangeModel, myLFLinkLanes, MSBaseVehicle::myType, and removeApproachingInformation().
MSVehicle::MSVehicle () private
invalidated default constructor
MSVehicle::MSVehicle (const MSVehicle &) private
invalidated copy constructor
Member Function Documentation
MSEdgeWeightsStorage & MSVehicle::_getWeightsStorage () const private
Definition at line 705 of file MSVehicle.cpp.
References myEdgeWeights.
Referenced by getWeightsStorage().
void MSVehicle::activateReminders (const MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters
[in] reason The reason for changing the reminders' states
[in] enteredLane The lane, which is entered (if applicable)
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSBaseVehicle.
Definition at line 2699 of file MSVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by congested(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), and processNextStop().
void MSVehicle::adaptBestLanesOccupation (int laneIndex, double density)
update occupation from MSLaneChanger
Definition at line 3315 of file MSVehicle.cpp.
References myBestLanes.
Referenced by MSLaneChangerSublane::change(), and MSLaneChanger::change().
void MSVehicle::adaptLaneEntering2MoveReminder (const MSLane & enteredLane) protected
Adapts the vehicle's entering of a new lane.
All offsets already stored in "myOldLaneMoveReminderOffsets" are increased by the length that has been left. All still active move reminders from "myMoveReminders" are put into "myOldLaneMoveReminders" and the offset to the last lane is added to "myOldLaneMoveReminderOffsets" for each of these.
Move reminder from the given lane are set into "myMoveReminders".
"myLane" must still be the left lane!
Parameters
[in] enteredLane
See also
MSMoveReminder
MSLane::getMoveReminder
Definition at line 744 of file MSVehicle.cpp.
References MSBaseVehicle::addReminder(), MSLane::getLength(), MSLane::getMoveReminders(), myLane, and MSBaseVehicle::myMoveReminders.
Referenced by enterLaneAtMove(), and hasInfluencer().
void MSVehicle::adaptToLeader (const std::pair< const MSVehicle *, double > leaderInfo, const double seen, DriveProcessItem *const lastLink, const MSLane *const lane, double & v, double & vLinkPass, double distToCrossing = -1) const protected
Definition at line 1773 of file MSVehicle.cpp.
References MSVehicle::DriveProcessItem::adaptLeaveSpeed(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), getSafeFollowSpeed(), MIN2(), myLane, and SIMTIME.
Referenced by adaptToLeaders(), checkLinkLeader(), and estimateLeaveSpeed().
void MSVehicle::adaptToLeaders (const MSLeaderInfo & ahead, double latOffset, const double seen, DriveProcessItem *const lastLink, const MSLane *const lane, double & v, double & vLinkPass) const protected
Definition at line 1738 of file MSVehicle.cpp.
References adaptToLeader(), DEBUG_COND, getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), getLane(), MSLane::getLength(), MSVehicleType::getMinGap(), getPositionOnLane(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), myLane, MSVehicle::State::myPos, myState, SIMTIME, and MSLeaderInfo::toString().
Referenced by estimateLeaveSpeed(), and planMoveInternal().
void MSVehicle::addContainer (MSTransportable * container) virtual
Adds a container.
Parameters
[in] container The container to add
Reimplemented from MSBaseVehicle.
Definition at line 3458 of file MSVehicle.cpp.
References MSDevice_Transportable::addTransportable(), MSDevice_Transportable::buildVehicleDevices(), MSTransportable::getID(), myContainerDevice, MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, and myStops.
Referenced by MSTransportableControl::loadAnyWaiting(), and nextStopDist().
void MSVehicle::addPerson (MSTransportable * person) virtual
Adds a passenger.
Parameters
[in] person The person to add
Reimplemented from MSBaseVehicle.
Definition at line 3436 of file MSVehicle.cpp.
References MSDevice_Transportable::addTransportable(), MSDevice_Transportable::buildVehicleDevices(), MSTransportable::getID(), MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, myPersonDevice, and myStops.
Referenced by MSTransportableControl::boardAnyWaiting(), and nextStopDist().
void MSBaseVehicle::addReminder (MSMoveReminder * rem) inherited
Adds a MoveReminder dynamically.
Parameters
[in] rem the reminder to add
See also
MSMoveReminder
Definition at line 334 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by adaptLaneEntering2MoveReminder(), MESegment::addReminders(), enterLaneAtInsertion(), enterLaneAtLaneChange(), MSBaseVehicle::getDevices(), and processNextStop().
bool MSVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0, bool collision = false) virtual
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implements SUMOVehicle.
Definition at line 893 of file MSVehicle.cpp.
References MSLane::allowsVehicleClass(), SUMOVehicleParameter::Stop::awaitedContainers, MSVehicle::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, MSVehicle::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, MSVehicle::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, MSVehicle::Stop::chargingStation, MSVehicle::Stop::collision, SUMOVehicleParameter::Stop::containerstop, MSVehicle::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, MSVehicle::Stop::containerTriggered, DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_GIVEN, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, MSVehicle::Stop::duration, MSVehicle::Stop::edge, MSRoute::end(), SUMOVehicleParameter::Stop::endPos, MSVehicle::Stop::endPos, MSNet::getBusStop(), getCarFollowModel(), MSNet::getChargingStation(), MSNet::getContainerStop(), MSLane::getEdge(), Named::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSLane::getLength(), MSNet::getParkingArea(), MSVehicleType::getVehicleClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::hasDeparted(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSVehicle::Stop::lane, MIN2(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, myState, myStops, MSBaseVehicle::myType, SUMOVehicleParameter::Stop::parking, MSVehicle::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, MSVehicle::Stop::parkingarea, POSITION_EPS, MSVehicle::Stop::reached, SUMOVehicleParameter::Stop::startPos, MSVehicle::Stop::startPos, STOP_INDEX_END, STOP_INDEX_FIT, MSVehicle::Stop::timeToBoardNextPerson, MSVehicle::Stop::timeToLoadNextContainer, SUMOVehicleParameter::Stop::triggered, MSVehicle::Stop::triggered, SUMOVehicleParameter::Stop::until, and MSVehicle::Stop::until.
Referenced by addTraciStop(), addTraciStopAtStoppingPlace(), MSLane::handleCollisionBetween(), replaceParkingArea(), and replaceRoute().
void MSBaseVehicle::addStops (const bool ignoreStopErrors) inherited
Adds stops to the built vehicle.
This code needs to be separated from the MSBaseVehicle constructor since it is not allowed to call virtual functions from a constructor
Parameters
[in] ignoreStopErrors whether invalid stops trigger a warning only
Definition at line 455 of file MSBaseVehicle.cpp.
References SUMOVehicle::addStop(), MSRoute::getStops(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, SUMOVehicleParameter::stops, and WRITE_WARNING.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MEVehicle::getBlockTimeSeconds(), MSBaseVehicle::getCurrentRouteEdge(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::setChosenSpeedFactor().
bool MSVehicle::addTraciStop (MSLane *const lane, const double startPos, const double endPos, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, std::string & errorMsg)
schedule a new stop for the vehicle; each time a stop is reached, the vehicle will wait for the given duration before continuing on its route
Parameters
lane lane on wich to stop
startPos start position on the given lane at wich to stop
endPos end position on the given lane at wich to stop
duration waiting time duration
until time step at which the stop shall end
parking a flag indicating whether the traci stop is used for parking or not
triggered a flag indicating whether the traci stop is triggered or not
containerTriggered a flag indicating whether the traci stop is triggered by a container or not
Definition at line 3814 of file MSVehicle.cpp.
References addStop(), SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, Named::getID(), SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, myLane, MSBaseVehicle::myParameter, myStops, SUMOVehicleParameter::Stop::parking, POSITION_EPS, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_FIT, SUMOVehicleParameter::stops, SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and updateBestLanes().
Referenced by TraCI_Vehicle::setStop(), and signalSet().
bool MSVehicle::addTraciStopAtStoppingPlace (const std::string & stopId, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, const SumoXMLTag stoppingPlaceType, std::string & errorMsg)
schedule a new stop for the vehicle; each time a stop is reached, the vehicle will wait for the given duration before continuing on its route
Parameters
stopId bus or container stop id
duration waiting time duration
until time step at which the stop shall end
parking a flag indicating whether the traci stop is used for parking or not
triggered a flag indicating whether the traci stop is triggered or not
containerTriggered a flag indicating whether the traci stop is triggered by a container or not
stoppingPlaceType a flag indicating the type of stopping place
Definition at line 3850 of file MSVehicle.cpp.
References addStop(), SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSNet::getChargingStation(), MSNet::getContainerStop(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSNet::getParkingArea(), SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, myLane, MSBaseVehicle::myParameter, myStops, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_FIT, SUMOVehicleParameter::stops, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_PARKING_AREA, toString(), SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and updateBestLanes().
Referenced by TraCI_Vehicle::setStop(), and signalSet().
void MSBaseVehicle::calculateArrivalParams () protected inherited
(Re-)Calculates the arrival position and lane from the vehicle parameters
Definition at line 383 of file MSBaseVehicle.cpp.
References ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, Named::getID(), MSBaseVehicle::getID(), MSEdge::getLanes(), MSRoute::getLastEdge(), MSVehicleType::getVehicleClass(), MSEdge::isTaz(), MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::myType, RandHelper::rand(), toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::MSBaseVehicle(), replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::reroute(), and MSBaseVehicle::setChosenSpeedFactor().
void MSVehicle::checkLinkLeader (const MSLink * link, const MSLane * lane, double seen, DriveProcessItem *const lastLink, double & v, double & vLinkPass, double & vLinkWait, bool & setRequest) const protected
checks for link leaders on the given link
Definition at line 1809 of file MSVehicle.cpp.
References adaptToLeader(), getLane(), MSLink::getLeaderInfo(), MSLane::getLogicalPredecessorLane(), MSLink::isLeader(), MAX2(), MIN2(), myLane, and MSVehicle::DriveProcessItem::myVLinkWait.
Referenced by estimateLeaveSpeed(), and planMoveInternal().
void MSVehicle::checkRewindLinkLanes (const double lengthsInFront, DriveItemVector & lfLinks) const protected
Todo:
: documentation
XXX backward compatibility: why should partial occupators be treated differently here? XXX MAX2 redundant?
XXX spaceTillLastStanding should already be covered by getPartialOccupatorEnd()
XXX why not check BRAKELIGHT?
Definition at line 2492 of file MSVehicle.cpp.
References ACCEL2SPEED, MSVehicle::DriveProcessItem::availableSpace, MSCFModel::brakeGap(), DEBUG_COND, MSEdge::EDGEFUNCTION_INTERNAL, gDebugSelectedVehicle, getBackPositionOnLane(), MSLane::getBruttoVehLenSum(), getCarFollowModel(), MSLane::getEdge(), MSCFModel::getHeadwayTime(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSLink::getLane(), getLaneChangeModel(), MSLane::getLastAnyVehicle(), getLateralPositionOnLane(), MSVehicle::DriveProcessItem::getLeaveSpeed(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLink::getParallelLink(), MSEdge::getPurpose(), MSVehicle::Influencer::getRespectJunctionPriority(), MSAbstractLaneChangeModel::getShadowLane(), getSpaceTillLastStanding(), getSpeed(), MSLane::getVehicleNumber(), MSBaseVehicle::getVehicleType(), MSLink::getViaLane(), getWaitingTime(), MSGlobals::gUsingInternalLanes, MSVehicle::DriveProcessItem::hadVehicle, MSLink::hasFoes(), MSLink::havePriority(), MSLink::isCont(), isFrontOnLane(), MSAbstractLaneChangeModel::isOpposite(), MSEdge::isRoundabout(), MSLink::keepClear(), LINKSTATE_ALLWAY_STOP, MAX2(), MSVehicle::DriveProcessItem::myArrivalSpeed, MSVehicle::DriveProcessItem::myArrivalTime, myHaveToWaitOnNextLink, myInfluencer, myLane, MSVehicle::DriveProcessItem::myLink, MSVehicle::State::mySpeed, myState, MSLink::opened(), RandHelper::rand(), MSLink::setApproaching(), MSAbstractLaneChangeModel::setShadowApproachingInformation(), signalSet(), SIMTIME, and VEH_SIGNAL_BRAKELIGHT.
Referenced by planMove().
SUMOTime MSVehicle::collisionStopTime () const
Returns the remaining time a vehicle needs to stop due to a collision. A negative value indicates that the vehicle is not stopping due to a collision (or at all)
Definition at line 1121 of file MSVehicle.cpp.
References MAX2(), myCollisionImmunity, and myStops.
Referenced by MSLane::executeMovements(), MSLane::handleCollisionBetween(), and hasStops().
double MSVehicle::computeAngle () const
compute the current vehicle angle
Definition at line 828 of file MSVehicle.cpp.
References Position::angleTo2D(), DEBUG_COND, DEG2RAD, MSLane::geometryPositionAtOffset(), getBackPosition(), MSBaseVehicle::getID(), getLaneChangeModel(), getPosition(), getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), isParking(), myFurtherLanes, myFurtherLanesPosLat, myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, myStops, PositionVector::rotationAtOffset(), and SIMTIME.
Referenced by MSLaneChanger::continueChange(), enterLaneAtInsertion(), enterLaneAtLaneChange(), executeMove(), and getVelocityVector().
bool MSVehicle::congested () const inline
Returns true if vehicle's speed is below 60km/h. This is only relevant on highways. Overtaking on the right is allowed then.
Definition at line 624 of file MSVehicle.h.
References activateReminders(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), getLaneChangeModel(), leaveLane(), MSVehicle::State::mySpeed, myState, MSVehicle::State::pos(), MSVehicle::State::posLat(), setTentativeLaneAndPosition(), and MSVehicle::State::speed().
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::congested(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), and MSLCM_SL2015::informLeader().
void MSBaseVehicle::createDevice (const std::string & deviceName) inherited
create device of the given type
Definition at line 489 of file MSBaseVehicle.cpp.
References MSDevice_Routing::buildVehicleDevices(), MSBaseVehicle::getDevice(), MSBaseVehicle::hasDeparted(), MSBaseVehicle::hasDevice(), MSBaseVehicle::myDevices, MSBaseVehicle::myParameter, MSMoveReminder::NOTIFICATION_DEPARTED, and MSDevice_Routing::notifyEnter().
Referenced by TraCI_Vehicle::setParameter().
virtual void MSVehicle::drawOutsideNetwork (bool) inline protected virtual
register vehicle for drawing while outside the network
Reimplemented in GUIVehicle.
Definition at line 1496 of file MSVehicle.h.
Referenced by MSVehicle::Influencer::postProcessVTD().
void MSVehicle::enterLaneAtInsertion (MSLane * enteredLane, double pos, double speed, double posLat, MSMoveReminder::Notification notification)
Update when the vehicle enters a new lane in the emit step.
Parameters
[in] enteredLane The lane the vehicle enters
[in] pos The position the vehicle was inserted into the lane
[in] speed The speed with which the vehicle was inserted into the lane
[in] posLat The lateral position the vehicle was inserted into the lane
[in] notification The cause of insertion (i.e. departure, teleport, parking)
Definition at line 2816 of file MSVehicle.cpp.
References activateReminders(), MSBaseVehicle::addReminder(), computeAngle(), DEBUG_COND, getLaneChangeModel(), MSVehicleType::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getMoveReminders(), MSBaseVehicle::getVehicleType(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, Position::INVALID, MSAbstractLaneChangeModel::isOpposite(), M_PI, myAmOnNet, myAngle, MSVehicle::State::myBackPos, myCachedPosition, MSBaseVehicle::myDeparture, myFurtherLanes, myFurtherLanesPosLat, myLane, myLaneChangeModel, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::State::mySpeed, myState, MSBaseVehicle::myType, myWaitingTime, MSBaseVehicle::NOT_YET_DEPARTED, MSMoveReminder::NOTIFICATION_TELEPORT, MSBaseVehicle::onDepart(), SIMTIME, and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by congested(), and MSLane::incorporateVehicle().
void MSVehicle::enterLaneAtLaneChange (MSLane * enteredLane)
Update when the vehicle enters a new lane in the laneChange step.
Parameters
[in] enteredLane The lane the vehicle enters
Definition at line 2766 of file MSVehicle.cpp.
References activateReminders(), MSBaseVehicle::addReminder(), computeAngle(), DEBUG_COND, MSBaseVehicle::getEdge(), MSVehicleType::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getMoveReminders(), MSBaseVehicle::getVehicleType(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), myAmOnNet, myAngle, myCachedPosition, myFurtherLanes, myFurtherLanesPosLat, myLane, myLaneChangeModel, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), SIMTIME, toString(), and updateBestLanes().
Referenced by congested(), and MSAbstractLaneChangeModel::primaryLaneChanged().
bool MSVehicle::enterLaneAtMove (MSLane * enteredLane, bool onTeleporting = false)
Update when the vehicle enters a new lane in the move step.
Parameters
[in] enteredLane The lane the vehicle enters
[in] onTeleporting Whether the lane was entered while being teleported
Returns
Whether the vehicle's route has ended (due to vaporization, or because the destination was reached)
Definition at line 2732 of file MSVehicle.cpp.
References activateReminders(), adaptLaneEntering2MoveReminder(), MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), MSEdge::getPurpose(), hasArrived(), Position::INVALID, myAmOnNet, myCachedPosition, MSBaseVehicle::myCurrEdge, myLane, myLastBestLanesEdge, MSVehicle::State::myPos, myState, MSMoveReminder::NOTIFICATION_JUNCTION, and MSMoveReminder::NOTIFICATION_TELEPORT.
Referenced by MSVehicleTransfer::add(), MSVehicleTransfer::checkInsertions(), congested(), executeMove(), and TraCIServerAPI_Vehicle::processSet().
double MSVehicle::estimateLeaveSpeed (const MSLink *const link, const double vLinkPass) const inline protected
estimate leaving speed when accelerating across a link
Definition at line 1640 of file MSVehicle.h.
References adaptToLeader(), adaptToLeaders(), checkLinkLeader(), MSCFModel::estimateSpeedAfterDistance(), getBackLane(), getBackPosition(), MSVehicleType::getCarFollowModel(), getCarFollowModel(), MSLink::getLength(), MSCFModel::getMaxAccel(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MIN2(), and updateState().
Referenced by planMoveInternal().
bool MSVehicle::executeMove ()
Executes planned vehicle movements with regards to right-of-way.
This method goes through all DriveProcessItems in myLFLinkLanes in order to find a speed that is safe for all upcoming links.
Using this speed the position is updated and the vehicle is moved to the next lane (myLane is updated) if the end of the current lane is reached (this may happen multiple times in this method)
The vehicle also sets the lanes it is in-lapping into and informs them about it.
Returns
Whether the vehicle has moved to the next edge
Definition at line 1880 of file MSVehicle.cpp.
References ACCEL2SPEED, MSCFModel::brakeGap(), MSAbstractLaneChangeModel::changedToOpposite(), computeAngle(), DEBUG_COND, DELTA_T, DIST2SPEED, MSRoute::end(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), enterLaneAtMove(), gDebugSelectedVehicle, getBackLane(), MSVehicleType::getCarFollowModel(), getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLink::getDirection(), MSLane::getEdge(), MSVehicle::Influencer::getEmergencyBrakeRedLight(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), getLaneChangeModel(), getLateralOverlap(), getLateralPositionOnLane(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSLane::getOpposite(), MSLane::getOppositePos(), MSLink::getParallelLink(), getPositionOnLane(), MSVehicle::Influencer::getRespectJunctionPriority(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), getSpeed(), MSLink::getState(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLane(), MSLink::getViaLaneOrLane(), getWaitingTime(), MSLane::getWidth(), MSGlobals::gSemiImplicitEulerUpdate, MSGlobals::gUsingInternalLanes, hasArrived(), MSVehicle::Influencer::implicitSpeedVTD(), MSVehicle::Influencer::influenceSpeed(), Position::INVALID, isRemoteControlled(), MSEdge::isRoundabout(), isStopped(), MSEdge::isVaporizing(), MSVehicle::Influencer::isVTDControlled(), leaveLane(), LINKDIR_LEFT, LINKDIR_RIGHT, LINKSTATE_EQUAL, LINKSTATE_TL_RED, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, LINKSTATE_ZIPPER, max, MAX2(), MSCFModel::maxNextSpeed(), MIN2(), MSCFModel::moveHelper(), myAcceleration, myAngle, MSVehicle::State::myBackPos, myCachedPosition, myCollisionImmunity, MSBaseVehicle::myCurrEdge, myFurtherLanes, myFurtherLanesPosLat, myHaveToWaitOnNextLink, myInfluencer, myLane, MSVehicle::State::myLastCoveredDist, myLFLinkLanes, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, myState, myTimeLoss, MSBaseVehicle::myType, myWaitingTime, myWaitingTimeCollector, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_VAPORIZED, NUMERICAL_EPS, MSLink::opened(), MSLink::passedJunction(), MSVehicle::WaitingTimeCollector::passTime(), POSITION_EPS, MSAbstractLaneChangeModel::prepareStep(), MSVehicleControl::registerEmergencyStop(), setBlinkerInformation(), setEmergencyBlueLight(), SIMTIME, SUMO_const_haltingSpeed, SVC_EMERGENCY, switchOffSignal(), switchOnSignal(), TIME2STEPS, time2string(), toString(), TS, updateBestLanes(), updateFurtherLanes(), MSAbstractLaneChangeModel::updateShadowLane(), updateState(), VEH_SIGNAL_BRAKELIGHT, workOnMoveReminders(), and WRITE_WARNING.
Referenced by MSLane::executeMovements().
void MSVehicle::fixPosition ()
repair errors in vehicle position after changing between internal edges
Definition at line 3323 of file MSVehicle.cpp.
References getLaneChangeModel(), MSGlobals::gLaneChangeDuration, MSVehicle::State::myPosLat, and myState.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver().
double MSVehicle::getAcceleration () const inline virtual
Returns the vehicle's acceleration in m/s (this is computed as the last step's mean acceleration in case that a stop occurs within the middle of the time-step)
Returns
The acceleration
Reimplemented from MSBaseVehicle.
Definition at line 459 of file MSVehicle.h.
References getPosition(), getSlope(), and myAcceleration.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), and MSBatteryExport::write().
double MSVehicle::getAccumulatedWaitingSeconds () const inline
Returns the number of seconds waited (speed was lesser than 0.1m/s) within the last millisecs.
Returns
The time the vehicle was standing within the last t millisecs
Definition at line 580 of file MSVehicle.h.
References getAccumulatedWaitingTime(), and STEPS2TIME.
Referenced by GUIVehicle::getColorValue(), and GUIVehicle::getParameterWindow().
SUMOTime MSVehicle::getAccumulatedWaitingTime (SUMOTime t = MSGlobals::gWaitingTimeMemory) const inline
Returns the SUMOTime waited (speed was lesser than 0.1m/s) within the last t millisecs.
Parameters
[in] t specifies the length of the interval over which the cumulated waiting time is to be summed up (defaults to and must not exceed MSGlobals::gWaitingTimeMemory)
Returns
The time the vehicle was standing within the last t millisecs
Definition at line 559 of file MSVehicle.h.
References MSVehicle::WaitingTimeCollector::cumulatedWaitingTime(), and myWaitingTimeCollector.
Referenced by getAccumulatedWaitingSeconds().
double MSVehicle::getAngle () const inline virtual
Returns the vehicle's direction in radians.
Returns
The vehicle's current angle
Implements SUMOVehicle.
Definition at line 594 of file MSVehicle.h.
References myAngle.
Referenced by GUIVehicle::getAngle(), TraCI_Vehicle::getAngle(), MSTransportable::Stage_Driving::getAngle(), and MSLaneChangerSublane::startChangeSublane().
virtual double MSBaseVehicle::getArrivalPos () const inline virtual inherited
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implements SUMOVehicle.
Definition at line 270 of file MSBaseVehicle.h.
References MSBaseVehicle::myArrivalPos.
Referenced by MSLCM_SL2015::_wantsChangeSublane().
const MSLane * MSVehicle::getBackLane () const protected
Definition at line 2337 of file MSVehicle.cpp.
References myFurtherLanes, and myLane.
Referenced by estimateLeaveSpeed(), and executeMove().
const Position MSVehicle::getBackPosition () const protected
Definition at line 869 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::geometryPositionAtOffset(), getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), getLaneChangeModel(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), myFurtherLanes, myFurtherLanesPosLat, myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, MSBaseVehicle::myType, and toString().
Referenced by computeAngle(), estimateLeaveSpeed(), getBoundingBox(), and getBoundingPoly().
double MSVehicle::getBackPositionOnLane (const MSLane * lane) const virtual
Get the vehicle's position relative to the given lane.
Returns
The back position of the vehicle (in m from the given lane's begin)
Implements SUMOVehicle.
Definition at line 2403 of file MSVehicle.cpp.
References MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), getLaneChangeModel(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSVehicle::State::myBackPos, myFurtherLanes, myLane, MSVehicle::State::myPos, myState, MSBaseVehicle::myType, time2string(), and WRITE_WARNING.
Referenced by adaptToLeaders(), MSLaneChangerSublane::checkChangeSublane(), checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getLeader(), getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSLane::vehicle_position_sorter::operator()(), MSLane::vehicle_natural_position_sorter::operator()(), MSLane::safeInsertionSpeed(), MSDevice_SSM::updateEncounter(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
double MSVehicle::getBackPositionOnLane () const inline
Get the vehicle's position relative to its current lane.
Returns
The back position of the vehicle (in m from the current lane's begin)
Definition at line 399 of file MSVehicle.h.
References myLane.
Referenced by getBackPosition(), getLastStepDist(), and getPositionOnLane().
int MSVehicle::getBestLaneOffset () const
Definition at line 3305 of file MSVehicle.cpp.
References myBestLanes.
Referenced by MSLCM_LC2013::changed(), MSLCM_SL2015::changed(), and GUIVehicle::getColorValue().
const std::vector< MSVehicle::LaneQ > & MSVehicle::getBestLanes () const
Returns the description of best lanes to use in order to continue the route.
Returns
The LaneQ for all lanes of the current edge
Definition at line 2933 of file MSVehicle.cpp.
References myBestLanes.
Referenced by MSLane::appropriate(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChangerSublane::checkChangeHelper(), TraCI_Vehicle::getBestLanes(), MSEdge::getDepartLane(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
const std::vector< MSLane * > & MSVehicle::getBestLanesContinuation () const
Returns the best sequence of lanes to continue the route starting at myLane.
Returns
The bestContinuations of the LaneQ for myLane (see LaneQ)
Definition at line 3276 of file MSVehicle.cpp.
References myBestLanes, and myEmptyLaneVector.
Referenced by MSLane::appropriate(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), GUIVehicle::drawRouteHelper(), MSLane::executeMovements(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSLane::getCriticalLeader(), getLeader(), MSLaneChangerSublane::getLeaders(), TraCI_Vehicle::getNextTLS(), MSLane::getOppositeLeader(), MSLaneChanger::getRealLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), planMoveInternal(), setBlinkerInformation(), unsafeLinkAhead(), and updateBestLanes().
const std::vector< MSLane * > & MSVehicle::getBestLanesContinuation (const MSLane *const l) const
Returns the best sequence of lanes to continue the route starting at the given lane.
Returns
The bestContinuations of the LaneQ for the given lane (see LaneQ)
Definition at line 3285 of file MSVehicle.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), MSLane::getLinkCont(), MSEdge::getPurpose(), myBestLanes, and myEmptyLaneVector.
PositionVector MSVehicle::getBoundingBox () const
get bounding rectangle
Definition at line 3753 of file MSVehicle.cpp.
References PositionVector::append(), getBackPosition(), getPosition(), MSVehicleType::getWidth(), PositionVector::move2side(), MSBaseVehicle::myType, POSITION_EPS, and PositionVector::reverse().
Referenced by MSLane::detectCollisions(), GUIVehicle::drawAction_drawPersonsAndContainers(), getBoundingPoly(), and signalSet().
PositionVector MSVehicle::getBoundingPoly () const
get bounding polygon
Definition at line 3766 of file MSVehicle.cpp.
References getBackPosition(), getBoundingBox(), MSVehicleType::getGuiShape(), getPosition(), MSVehicleType::getWidth(), PositionVector::move2side(), MSBaseVehicle::myType, PositionVector::scaleRelative(), SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, and SVS_PASSENGER_WAGON.
Referenced by MSLane::detectCollisions(), GUIVehicle::drawAction_drawPersonsAndContainers(), and signalSet().
const MSCFModel& MSVehicle::getCarFollowModel () const inline
Returns the vehicle's car following model definition.
This is simply a wrapper around the vehicle type's car-following model retrieval for a shorter access.
Returns
The vehicle's car following model definition
Definition at line 796 of file MSVehicle.h.
References MSVehicleType::getCarFollowModel(), and MSBaseVehicle::myType.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), addStop(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), estimateLeaveSpeed(), executeMove(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getLeader(), getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getMissingRearGap(), MSLaneChanger::getRealLeader(), getRerouteOrigin(), getSafeFollowSpeed(), GUIVehicle::getTypeParameterWindow(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), planMoveInternal(), processNextStop(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
MSCFModel::VehicleVariables* MSVehicle::getCarFollowVariables () const inline
Returns the vehicle's car following model variables.
Returns
The vehicle's car following model variables
Definition at line 805 of file MSVehicle.h.
References myCFVariables.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel_SmartSK::_vsafe(), MSCFModel_SmartSK::followSpeed(), MSCFModel_PWag2009::followSpeed(), MSCFModel_Kerner::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_PWag2009::moveHelper(), MSCFModel_Wiedemann::moveHelper(), MSCFModel_IDM::moveHelper(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_SmartSK::updateMyHeadway().
double MSVehicle::getCenterOnEdge (const MSLane * lane = 0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
Returns
The lateral position of the vehicle (in m distance between center of vehicle and ride side of edge
Definition at line 3606 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::getCenterOnEdge(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), MSAbstractLaneChangeModel::getShadowLane(), MSLane::getWidth(), myFurtherLanes, myFurtherLanesPosLat, myLane, MSVehicle::State::myPosLat, and myState.
Referenced by MSLCM_SL2015::checkBlocking(), MSLane::detectCollisionBetween(), getLateralPositionOnLane(), getRightSideOnEdge(), and MSLCM_SL2015::keepLatGap().
double MSBaseVehicle::getChosenSpeedFactor () const inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 361 of file MSBaseVehicle.h.
References MSBaseVehicle::myChosenSpeedFactor.
Referenced by GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), and TraCI_Vehicle::getSpeedFactor().
double MSVehicle::getCO2Emissions () const
Returns CO2 emission of the current state.
Returns
The current CO2 emission
Definition at line 3388 of file MSVehicle.cpp.
References PollutantsInterface::CO2, PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by TraCI_Vehicle::getCO2Emission(), GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), and nextStopDist().
double MSVehicle::getCOEmissions () const
Returns CO emission of the current state.
Returns
The current CO emission
Definition at line 3394 of file MSVehicle.cpp.
References PollutantsInterface::CO, PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by TraCI_Vehicle::getCOEmission(), GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), and nextStopDist().
int MSVehicle::getContainerNumber () const
Returns the number of containers.
Returns
The number of contaiers on-board
Definition at line 3514 of file MSVehicle.cpp.
References SUMOVehicleParameter::containerNumber, myContainerDevice, MSBaseVehicle::myParameter, and MSDevice_Transportable::size().
Referenced by GUIVehicle::getParameterWindow(), MSTransportableControl::loadAnyWaiting(), nextStopDist(), processNextStop(), and MSXMLRawOut::writeVehicle().
const std::vector< MSTransportable * > & MSVehicle::getContainers () const
retrieve riding containers
Definition at line 3498 of file MSVehicle.cpp.
References MSDevice_Transportable::getTransportables(), myContainerDevice, and myEmptyTransportableVector.
Referenced by nextStopDist(), MSFCDExport::write(), and MSXMLRawOut::writeVehicle().
const MSRouteIterator& MSBaseVehicle::getCurrentRouteEdge () const inline virtual inherited
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implements SUMOVehicle.
Definition at line 193 of file MSBaseVehicle.h.
References MSBaseVehicle::addStops(), MSBaseVehicle::getAcceleration(), MSBaseVehicle::getSlope(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::onDepart(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::reroute().
Referenced by MSDevice_SSM::findSurroundingVehicles(), and TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
double MSVehicle::getDeltaPos (double accel)
calculates the distance covered in the next integration step given an acceleration and assuming the current velocity. (gives different results for different integration methods, e.g., euler vs. ballistic)
Parameters
[in] accel the assumed acceleration
Returns
distance covered in next integration step
Definition at line 1858 of file MSVehicle.cpp.
References ACCEL2SPEED, MSGlobals::gSemiImplicitEulerUpdate, MAX2(), MSVehicle::State::mySpeed, myState, and SPEED2DIST.
Referenced by updateState().
SUMOTime MSBaseVehicle::getDepartDelay () const inline virtual inherited
Returns the depart delay.
Implements SUMOVehicle.
Definition at line 254 of file MSBaseVehicle.h.
References SUMOVehicleParameter::depart, MSBaseVehicle::getDeparture(), and MSBaseVehicle::getParameter().
Referenced by GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIMEVehicle::getParameterWindow(), and GUIVehicle::getParameterWindow().
double MSBaseVehicle::getDepartPos () const inline virtual inherited
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implements SUMOVehicle.
Definition at line 262 of file MSBaseVehicle.h.
References MSBaseVehicle::myDepartPos.
Referenced by TraCI_Vehicle::getDistance().
SUMOTime MSBaseVehicle::getDeparture () const inline virtual inherited
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 249 of file MSBaseVehicle.h.
References MSBaseVehicle::myDeparture.
Referenced by MSBaseVehicle::getDepartDelay(), and MSVehicle::Influencer::postProcessVTD().
MSDevice * MSBaseVehicle::getDevice (const std::type_info & type) const virtual inherited
Returns a device of the given type if it exists or 0.
Implements SUMOVehicle.
Definition at line 432 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by MSBaseVehicle::createDevice(), GUIBaseVehicle::drawOnPos(), MSBaseVehicle::setChosenSpeedFactor(), and MSBatteryExport::write().
std::string MSBaseVehicle::getDeviceParameter (const std::string & deviceName, const std::string & key) const inherited
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 508 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by TraCI_Vehicle::getParameter().
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const inline virtual inherited
Returns this vehicle's devices.
Returns
This vehicle's devices
Implements SUMOVehicle.
Definition at line 303 of file MSBaseVehicle.h.
References MSBaseVehicle::activateReminders(), MSBaseVehicle::addContainer(), MSBaseVehicle::addPerson(), MSBaseVehicle::addReminder(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myDevices, and MSBaseVehicle::removeReminder().
double MSVehicle::getDistanceToPosition (double destPos, const MSEdge * destEdge) const
Compute distance that will be covered, if the vehicle moves to a given position on its route, starting at its current position.
Parameters
destPos position on the destination edge that shall be reached
destEdge destination edge that shall be reached
Returns
distance from the vehicles current position to the destination position, or a near infinite real value if the destination position is not contained within the vehicles route or the vehicle is not active
Definition at line 3331 of file MSVehicle.cpp.
References MSRoute::getDistanceBetween(), MSLane::getEdge(), MSLane::getLength(), getPositionOnLane(), isOnRoad(), max, MSBaseVehicle::myCurrEdge, myLane, and MSBaseVehicle::myRoute.
Referenced by MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), and nextStopDist().
const MSEdge * MSBaseVehicle::getEdge () const virtual inherited
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 148 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myCurrEdge.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), enterLaneAtLaneChange(), METriggeredCalibrator::execute(), MEVehicle::getAngle(), TraCI_Vehicle::getDrivingDistance(), TraCI_Vehicle::getDrivingDistance2D(), GUIMEVehicle::getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), MSBaseVehicle::getVClass(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), MELoop::teleportVehicle(), and TraCIServerAPI_Vehicle::vtdMap().
double MSVehicle::getElectricityConsumption () const
Returns electricity consumption of the current state.
Returns
The current electricity consumption
Definition at line 3424 of file MSVehicle.cpp.
References PollutantsInterface::compute(), PollutantsInterface::ELEC, MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by GUIVehicle::getColorValue(), TraCI_Vehicle::getElectricityConsumption(), GUIVehicle::getParameterWindow(), and nextStopDist().
double MSVehicle::getFuelConsumption () const
Returns fuel consumption of the current state.
Returns
The current fuel consumption
Definition at line 3418 of file MSVehicle.cpp.
References PollutantsInterface::compute(), PollutantsInterface::FUEL, MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by GUIVehicle::getColorValue(), TraCI_Vehicle::getFuelConsumption(), GUIVehicle::getParameterWindow(), and nextStopDist().
const std::vector<MSLane*>& MSVehicle::getFurtherLanes () const inline
Definition at line 683 of file MSVehicle.h.
References myFurtherLanes.
Referenced by MSAbstractLaneChangeModel::updateShadowLane().
const std::vector<double>& MSVehicle::getFurtherLanesPosLat () const inline
Definition at line 687 of file MSVehicle.h.
References myFurtherLanesPosLat, and onFurtherEdge().
Referenced by MSAbstractLaneChangeModel::updateShadowLane().
double MSVehicle::getHarmonoise_NoiseEmissions () const
Returns noise emissions of the current state.
Returns
The noise produced
Definition at line 3430 of file MSVehicle.cpp.
References HelpersHarmonoise::computeNoise(), MSVehicleType::getEmissionClass(), myAcceleration, myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by GUIVehicle::getColorValue(), TraCI_Vehicle::getNoiseEmission(), GUIVehicle::getParameterWindow(), and nextStopDist().
double MSVehicle::getHCEmissions () const
Returns HC emission of the current state.
Returns
The current HC emission
Definition at line 3400 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), PollutantsInterface::HC, myAcceleration, myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by GUIVehicle::getColorValue(), TraCI_Vehicle::getHCEmission(), GUIVehicle::getParameterWindow(), and nextStopDist().
const std::string & MSBaseVehicle::getID () const virtual inherited
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 120 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and MSBaseVehicle::myParameter.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptToLeader(), adaptToLeaders(), MSVehicleTransfer::add(), addTraciStopAtStoppingPlace(), MSBaseVehicle::calculateArrivalParams(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLCM_SL2015::changed(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLane::checkFailure(), MSVehicleTransfer::checkInsertions(), checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSDevice_SSM::closeEncounter(), computeAngle(), MSDevice_SSM::computeSSMs(), MSLaneChanger::continueChange(), MSLCM_SL2015::decideDirection(), MSLane::detectCollisionBetween(), MSDevice_SSM::Encounter::Encounter(), MSCalibrator::execute(), executeMove(), MSLane::executeMovements(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSLane::getPartialBehind(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSAbstractLaneChangeModel::getShadowLane(), MSDevice_SSM::getUpstreamVehicles(), MSLane::handleCollisionBetween(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MESegment::initialise(), MSPedestrianPushButton::isActiveForEdge(), MSLane::isInsertionSuccess(), leaveLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSLCM_LC2013::MSLCM_LC2013(), MSCalibrator::VehicleRemover::notifyEnter(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), planMove(), planMoveInternal(), MSAbstractLaneChangeModel::primaryLaneChanged(), processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSDevice_SSM::qualifiesAsConflict(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), TraCI_Vehicle::resume(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSBaseVehicle::saveState(), MSCalibrator::scheduleRemoval(), GUIVehicle::selectBlockingFoes(), MSBaseVehicle::setDeviceParameter(), MSLCM_SL2015::setOwnState(), MSLane::setPartialOccupation(), TraCIServer::setVTDControlled(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), updateBestLanes(), MSDevice_SSM::updateEncounter(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), MSDevice_SSM::writeOutConflict(), MSXMLRawOut::writeVehicle(), and MSDevice_SSM::Encounter::~Encounter().
double MSBaseVehicle::getImpatience () const virtual inherited
Returns this vehicles impatience.
Implements SUMOVehicle.
Definition at line 425 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getVehicleType(), SUMOVehicle::getWaitingTime(), MSGlobals::gTimeToImpatience, MAX2(), and MIN2().
Referenced by MSLCM_SL2015::checkBlockingVehicles(), checkRewindLinkLanes(), executeMove(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSBaseVehicle::getNumberReroutes(), GUIVehicle::getParameterWindow(), MSLCM_LC2013::informFollower(), MSLane::isInsertionSuccess(), MESegment::isOpen(), and GUIVehicle::selectBlockingFoes().
MSVehicle::Influencer & MSVehicle::getInfluencer ()
Returns the velocity/lane influencer.
If no influencer was existing before, one is built, first
Returns
Reference to this vehicle's speed influencer
Definition at line 3993 of file MSVehicle.cpp.
References myInfluencer.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLane::detectCollisionBetween(), TraCI_Vehicle::getSpeedMode(), MSLane::handleCollisionBetween(), influenceChangeDecision(), MSLCM_SL2015::keepLatGap(), TraCIServerAPI_Vehicle::processSet(), MSAbstractLaneChangeModel::setOwnState(), and TraCIServer::setVTDControlled().
const MSVehicle::Influencer * MSVehicle::getInfluencer () const
Definition at line 4002 of file MSVehicle.cpp.
References myInfluencer.
MSLane* MSVehicle::getLane () const inline virtual
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implements SUMOVehicle.
Definition at line 488 of file MSVehicle.h.
References myLane.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptToLeaders(), MSVehicleTransfer::add(), MSLaneChangerSublane::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSVehicleTransfer::checkInsertions(), checkLinkLeader(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSAbstractLaneChangeModel::congested(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSVTypeProbe::execute(), MSLane::executeMovements(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSCFModel_IDM::followSpeed(), TraCI_Vehicle::getAllowedSpeed(), GUIVehicle::getColorValue(), TraCI_Vehicle::getDistance(), MSLane::getFollowersOnConsecutive(), TraCI_Vehicle::getLaneID(), TraCI_Vehicle::getLaneIndex(), MSLaneChangerSublane::getLeaders(), TraCI_Vehicle::getNextTLS(), TraCI_Vehicle::getRoadID(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSAbstractLaneChangeModel::getShadowDirection(), MSVTKExport::getSpeed(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MSLCM_LC2013::informFollower(), MSLane::integrateNewVehicle(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSJunction::isLeader(), MSLCM_SL2015::keepLatGap(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_IDM::moveHelper(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), MSLCM_SL2015::prepareStep(), TraCIServerAPI_Vehicle::processSet(), MSVehicleTransfer::remove(), MSCalibrator::removePending(), MSLane::removeVehicle(), setBlinkerInformation(), MSLaneChangerSublane::startChangeSublane(), MSCFModel_IDM::stopSpeed(), MSLaneChangerSublane::updateChanger(), MSDevice_SSM::updateEncounter(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::updateShadowLane(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSQueueExport::writeLane(), and MSFullExport::writeVehicles().
MSAbstractLaneChangeModel & MSVehicle::getLaneChangeModel ()
Definition at line 2921 of file MSVehicle.cpp.
References myLaneChangeModel.
Referenced by MSVehicleTransfer::add(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), checkRewindLinkLanes(), computeAngle(), congested(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), enterLaneAtInsertion(), executeMove(), fixPosition(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), TraCI_Vehicle::getLaneChangeState(), GUIVehicle::getLastLaneChangeOffset(), getLatOffset(), MSLink::getLeaderInfo(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), TraCI_Vehicle::getParameter(), GUIVehicle::getParameterWindow(), getPosition(), MSAbstractLaneChangeModel::MSLCMessager::informLeader(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), isFrontOnLane(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel::moveHelper(), planMove(), planMoveInternal(), MSLaneChanger::registerUnchanged(), removeApproachingInformation(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), setBlinkerInformation(), TraCI_Vehicle::setParameter(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), updateBestLanes(), MSLaneChangerSublane::updateChanger(), and updateState().
const MSAbstractLaneChangeModel & MSVehicle::getLaneChangeModel () const
Definition at line 2927 of file MSVehicle.cpp.
References myLaneChangeModel.
int MSVehicle::getLaneIndex () const
Definition at line 3577 of file MSVehicle.cpp.
References MSLane::getEdge(), MSEdge::getLanes(), and myLane.
Referenced by MSLane::appropriate(), influenceChangeDecision(), and nextStopDist().
double MSVehicle::getLastStepDist () const inline
Get the distance the vehicle covered in the previous timestep.
Returns
The distance covered in the last timestep (in m)
Definition at line 382 of file MSVehicle.h.
References getBackPositionOnLane(), getPositionOnLane(), MSVehicle::State::lastCoveredDist(), and myState.
double MSVehicle::getLateralOverlap () const
return the amount by which the vehicle extends laterally outside it's primary lane
Definition at line 3681 of file MSVehicle.cpp.
References getLateralPositionOnLane(), MSBaseVehicle::getVehicleType(), MSLane::getWidth(), and myLane.
Referenced by MSLCM_SL2015::checkStrategicChange(), executeMove(), getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), planMoveInternal(), and MSAbstractLaneChangeModel::updateShadowLane().
double MSVehicle::getLateralPositionOnLane () const inline virtual
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Reimplemented from MSBaseVehicle.
Definition at line 407 of file MSVehicle.h.
References getCenterOnEdge(), getLateralOverlap(), getLatOffset(), getRightSideOnEdge(), getRightSideOnLane(), MSVehicle::State::myPosLat, and myState.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSVehicleTransfer::checkInsertions(), checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::continueChange(), executeMove(), MSLane::getCriticalLeader(), TraCI_Vehicle::getLateralLanePosition(), getLateralOverlap(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), GUIVehicle::getParameterWindow(), getPosition(), MSAbstractLaneChangeModel::getShadowLane(), MSLeaderInfo::getSubLanes(), MSLCM_SL2015::keepLatGap(), MSLane::loadState(), MSLane::vehicle_natural_position_sorter::operator()(), planMove(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), and MSXMLRawOut::writeVehicle().
double MSVehicle::getLatOffset (const MSLane * lane) const
Get the offset that that must be added to interpret myState.myPosLat for the given lane.
Definition at line 3638 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), myFurtherLanes, myFurtherLanesPosLat, myLane, MSVehicle::State::myPosLat, myState, SIMTIME, and toString().
Referenced by MSLane::getFirstVehicleInformation(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), and getLateralPositionOnLane().
std::pair< const MSVehicle *const, double > MSVehicle::getLeader (double dist = 0) const
Returns the leader of the vehicle looking for a fixed distance.
If the distance is not given it is calculated from the brake gap. The gap returned does not include the minGap.
Parameters
dist up to which distance to look for a leader
Returns
The leading vehicle together with the gap; (0, -1) if no leader was found.
Definition at line 3348 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), getBackPositionOnLane(), getBestLanesContinuation(), getCarFollowModel(), MSLane::getLeaderOnConsecutive(), MSLane::getLength(), MSVehicleType::getMinGap(), getPositionOnLane(), getSpeed(), MSLane::getVehiclesSecure(), MSBaseVehicle::getVehicleType(), myLane, and MSLane::releaseVehicles().
Referenced by TraCI_Vehicle::getLeader(), getTimeGapOnLane(), and nextStopDist().
double MSBaseVehicle::getMaxSpeed () const virtual inherited
Returns the maximum speed.
Returns
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 132 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), and MSBaseVehicle::myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSVehicle::Influencer::implicitDeltaPosVTD(), and MSVehicle::Influencer::implicitSpeedVTD().
double MSVehicle::getMaxSpeedOnLane () const inline
Returns the maximal speed for the vehicle on its current lane (including speed factor and deviation, i.e., not necessarily the allowed speed limit)
Returns
The vehicle's max speed
Definition at line 498 of file MSVehicle.h.
References MSVehicleType::getMaxSpeed(), MSLane::getVehicleMaxSpeed(), myLane, and MSBaseVehicle::myType.
Referenced by MSLCM_LC2013::informFollower(), MSCFModel_Rail::moveHelper(), MSCFModel_KraussX::moveHelper(), and MSCFModel::moveHelper().
MSParkingArea * MSVehicle::getNextParkingArea () virtual
get the current parking area stop
Implements SUMOVehicle.
Definition at line 1101 of file MSVehicle.cpp.
References myStops, MSVehicle::Stop::parkingarea, and MSVehicle::Stop::reached.
MSVehicle::Stop & MSVehicle::getNextStop ()
returns the next imminent stop in the stop queue
Returns
the upcoming stop
Definition at line 3987 of file MSVehicle.cpp.
References myStops.
Referenced by TraCI_Vehicle::getStopState(), MSLane::isInsertionSuccess(), TraCI_Vehicle::resume(), and signalSet().
double MSVehicle::getNOxEmissions () const
Returns NOx emission of the current state.
Returns
The current NOx emission
Definition at line 3406 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, PollutantsInterface::NO_X, and MSVehicle::State::speed().
Referenced by GUIVehicle::getColorValue(), TraCI_Vehicle::getNOxEmission(), GUIVehicle::getParameterWindow(), and nextStopDist().
int MSBaseVehicle::getNumberReroutes () const inline virtual inherited
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 292 of file MSBaseVehicle.h.
References MSBaseVehicle::getImpatience(), and MSBaseVehicle::myNumberReroutes.
Referenced by GUIBaseVehicle::drawGLAdditional(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), and MSBaseVehicle::replaceRouteEdges().
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const virtual inherited
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 126 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myParameter.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSTransportableControl::boardAnyWaiting(), GUIBaseVehicle::drawOnPos(), MSBaseVehicle::getDepartDelay(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartSpeed(), TraCI_Vehicle::getLine(), TraCI_Vehicle::getParameter(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), TraCI_Vehicle::getVia(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSTransportableControl::loadAnyWaiting(), TraCIServerAPI_Vehicle::processSet(), GUIBaseVehicle::setFunctionalColor(), TraCI_Vehicle::setParameter(), and METriggeredCalibrator::tryEmit().
int MSVehicle::getPersonNumber () const
Returns the number of persons.
Returns
The number of passengers on-board
Definition at line 3508 of file MSVehicle.cpp.
References MSBaseVehicle::myParameter, myPersonDevice, SUMOVehicleParameter::personNumber, and MSDevice_Transportable::size().
Referenced by MSTransportableControl::boardAnyWaiting(), GUIVehicle::getParameterWindow(), TraCI_Vehicle::getPersonNumber(), nextStopDist(), processNextStop(), and MSXMLRawOut::writeVehicle().
const std::vector< MSTransportable * > & MSVehicle::getPersons () const
retrieve riding persons
Definition at line 3488 of file MSVehicle.cpp.
References MSDevice_Transportable::getTransportables(), myEmptyTransportableVector, and myPersonDevice.
Referenced by nextStopDist(), MSFCDExport::write(), and MSXMLRawOut::writeVehicle().
double MSVehicle::getPMxEmissions () const
Returns PMx emission of the current state.
Returns
The current PMx emission
Definition at line 3412 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, PollutantsInterface::PM_X, and MSVehicle::State::speed().
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), TraCI_Vehicle::getPMxEmission(), and nextStopDist().
Position MSVehicle::getPosition (const double offset = 0) const virtual
Return current position (x/y, cartesian)
If the vehicle's myLane is 0, Position::INVALID.
Parameters
[in] offset optional offset in longitudinal direction
Returns
The current position (in cartesian coordinates)
See also
myLane
Implements SUMOVehicle.
Definition at line 777 of file MSVehicle.cpp.
References MSLane::geometryPositionAtOffset(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSNet::getInstance(), getLaneChangeModel(), MSEdge::getLanes(), getLateralPositionOnLane(), getPositionOnLane(), MSLane::interpolateLanePosToGeometryPos(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), isParking(), MSVehicle::Influencer::isVTDAffected(), PositionVector::move2side(), myCachedPosition, myInfluencer, myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, myStops, PositionVector::positionAtOffset(), and SUMO_const_laneWidth.
Referenced by computeAngle(), getAcceleration(), getBoundingBox(), getBoundingPoly(), TraCIServerAPI_Vehicle::getPosition(), GUIVehicle::getPosition(), TraCI_Vehicle::getPosition(), MSVTKExport::getPositions(), MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), TraCIServerAPI_Vehicle::processSet(), MSDevice_SSM::updateEncounter(), TraCIServerAPI_Vehicle::vtdMap(), and MSBatteryExport::write().
double MSVehicle::getPositionOnLane () const inline virtual
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implements SUMOVehicle.
Definition at line 375 of file MSVehicle.h.
References MSVehicle::State::myPos, and myState.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptToLeaders(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), computeAngle(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), executeMove(), MSLane::executeMovements(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), MSLaneChanger::getCloserFollower(), MSEdge::getDepartPosBound(), TraCI_Vehicle::getDistance(), getDistanceToPosition(), TraCI_Vehicle::getDrivingDistance(), TraCI_Vehicle::getDrivingDistance2D(), MSLane::getFirstAnyVehicle(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSEdge::getFreeLane(), TraCI_Vehicle::getLanePosition(), getLastStepDist(), MSLane::getLastVehicleInformation(), MSLane::getLeader(), getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getNettoOccupancy(), TraCI_Vehicle::getNextTLS(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIVehicle::getParameterWindow(), MSLane::getPartialBehind(), getPosition(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSLCM_LC2013::getRoundaboutAheadInfo(), getSlope(), MSVTKExport::getSpeed(), MSDevice_SSM::getUpstreamVehicles(), MSLane::handleCollisionBetween(), MSVehicleTransfer::loadState(), MSLane::loadState(), MSLane::VehPosition::operator()(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), planMove(), planMoveInternal(), MSCalibrator::remainingVehicleCapacity(), MSLane::safeInsertionSpeed(), GUIVehicle::selectBlockingFoes(), setBlinkerInformation(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
double MSVehicle::getPositionOnLane (const MSLane * lane) const
Get the vehicle's front position relative to the given lane.
Returns
The front position of the vehicle (in m from the given lane's begin)
Definition at line 2459 of file MSVehicle.cpp.
References getBackPositionOnLane(), MSVehicleType::getLength(), and MSBaseVehicle::myType.
double MSVehicle::getPreviousSpeed () const inline virtual
Returns the vehicle's speed before the previous time step.
Returns
The vehicle's speed before the previous time step
Reimplemented from MSBaseVehicle.
Definition at line 450 of file MSVehicle.h.
References MSVehicle::State::myPreviousSpeed, and myState.
const MSEdge * MSVehicle::getRerouteOrigin () const virtual
Returns the starting point for reroutes (usually the current edge)
This differs from *myCurrEdge only if the vehicle is on an internal edge or very close to the junction
Returns
The rerouting start point
Reimplemented from MSBaseVehicle.
Definition at line 809 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), MSRoute::end(), getCarFollowModel(), MSLane::getLength(), MSLane::getNextNormal(), MSBaseVehicle::myCurrEdge, myLane, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, and myState.
Referenced by isOnRoad(), and TraCIServerAPI_Vehicle::processSet().
double MSVehicle::getRightSideOnEdge (const MSLane * lane = 0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
Returns
The lateral position of the vehicle (in m distance between right side of vehicle and ride side of edge
Definition at line 3600 of file MSVehicle.cpp.
References getCenterOnEdge(), MSBaseVehicle::getVehicleType(), and MSVehicleType::getWidth().
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlockingVehicles(), and getLateralPositionOnLane().
double MSVehicle::getRightSideOnLane () const
Get the vehicle's lateral position on the lane:
Returns
The lateral position of the vehicle (in m distance between right side of vehicle and ride side of the lane it is on
Definition at line 3594 of file MSVehicle.cpp.
References MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), myLane, MSVehicle::State::myPosLat, and myState.
Referenced by getLateralPositionOnLane().
const MSRoute& MSBaseVehicle::getRoute () const inline virtual inherited
Returns the current route.
Returns
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 108 of file MSBaseVehicle.h.
References MSBaseVehicle::myRoute.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), GUIBaseVehicle::drawRoute(), MSEdge::getDepartLane(), TraCI_Vehicle::getDistance(), TraCI_Vehicle::getDrivingDistance(), TraCI_Vehicle::getDrivingDistance2D(), TraCI_Vehicle::getEdges(), TraCI_Vehicle::getRouteID(), MSLane::isInsertionSuccess(), MSVehicle::Influencer::postProcessVTD(), GUIBaseVehicle::setFunctionalColor(), TraCIServerAPI_Vehicle::vtdMap(), and TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
int MSVehicle::getRoutePosition () const
Definition at line 678 of file MSVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by TraCI_Vehicle::getRouteIndex(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), and TraCIServerAPI_Vehicle::vtdMap().
double MSVehicle::getSafeFollowSpeed (const std::pair< const MSVehicle *, double > leaderInfo, const double seen, const MSLane *const lane, double distToCrossing) const
compute safe speed for following the given leader
Definition at line 1838 of file MSVehicle.cpp.
References MSCFModel::followSpeed(), getCarFollowModel(), MSLane::getLength(), getSpeed(), MAX2(), POSITION_EPS, and MSCFModel::stopSpeed().
Referenced by adaptToLeader(), MSLane::getCriticalLeader(), and hasInfluencer().
int MSVehicle::getSignals () const inline
Returns the signals.
Returns
The signals' states
Definition at line 1140 of file MSVehicle.h.
References mySignals.
Referenced by TraCI_Vehicle::getSignalStates(), and MSFCDExport::write().
double MSVehicle::getSlope () const virtual
Returns the slope of the road at vehicle's position.
Returns
The slope
Reimplemented from MSBaseVehicle.
Definition at line 766 of file MSVehicle.cpp.
References getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), myLane, and PositionVector::slopeDegreeAtOffset().
Referenced by getAcceleration(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHCEmissions(), getNOxEmissions(), GUIVehicle::getParameterWindow(), getPMxEmissions(), TraCI_Vehicle::getSlope(), MSCFModel_Rail::maxNextSpeed(), MSCFModel_KraussPS::maxNextSpeed(), and MSCFModel_Rail::minNextSpeed().
double MSVehicle::getSpaceTillLastStanding (const MSLane * l, bool & foundStopped) const protected
Definition at line 2471 of file MSVehicle.cpp.
References MSLane::getLength(), MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMO_const_haltingSpeed.
Referenced by checkRewindLinkLanes(), and hasInfluencer().
double MSVehicle::getSpeed () const inline virtual
Returns the vehicle's current speed.
Returns
The vehicle's speed
Implements SUMOVehicle.
Definition at line 442 of file MSVehicle.h.
References MSVehicle::State::mySpeed, and myState.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSCFModel_Wiedemann::_v(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), GUIApplicationWindow::checkGamingEvents(), checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), executeMove(), MSLane::forceVehicleInsertion(), MSLane::freeInsertion(), GUIVehicle::getColorValue(), MSLane::getCriticalLeader(), MSLane::getLeader(), getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getMissingRearGap(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), getSafeFollowSpeed(), MSVTKExport::getSpeed(), TraCI_Vehicle::getSpeed(), getTimeGapOnLane(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSVehicleTransfer::loadState(), MSLane::loadState(), MSLink::maybeOccupied(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_PWag2009::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel_Wiedemann::moveHelper(), MSCFModel::moveHelper(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), planMove(), planMoveInternal(), MSAbstractLaneChangeModel::predInteraction(), MSAbstractLaneChangeModel::primaryLaneChanged(), processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
double MSVehicle::getSpeedWithoutTraciInfluence () const
Returns the uninfluenced velocity.
If no influencer exists (myInfluencer==0) the vehicle's current speed is returned. Otherwise the speed returned from myInfluencer->getOriginalSpeed().
Returns
The vehicle's velocity as it would without an influence
See also
Influencer::getOriginalSpeed
Definition at line 4008 of file MSVehicle.cpp.
References MSVehicle::Influencer::getOriginalSpeed(), myInfluencer, MSVehicle::State::mySpeed, and myState.
Referenced by TraCI_Vehicle::getSpeedWithoutTraCI(), and signalSet().
const ConstMSEdgeVector MSVehicle::getStopEdges () const protected virtual
Returns the list of still pending stop edges.
Implements MSBaseVehicle.
Definition at line 1353 of file MSVehicle.cpp.
References myStops.
Referenced by hasInfluencer().
double MSVehicle::getTimeGapOnLane () const
Returns the time gap in seconds to the leader of the vehicle on the same lane.
If the distance is too big -1 is returned. The gap returned takes the minGap into account.
Returns
The time gap in seconds; -1 if no leader was found or speed is 0.
Definition at line 3377 of file MSVehicle.cpp.
References getLeader(), getSpeed(), and MSBaseVehicle::getVehicleType().
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), and nextStopDist().
SUMOTime MSVehicle::getTimeLoss () const inline
Returns the SUMOTime lost (speed was lesser maximum speed)
Note
Intentional stopping does not count towards this time.
speedFactor is included so time loss can never be negative. The value is that of a driver who compares his travel time when the road is clear (which includes speed factor) with the actual travel time.
includes time lost due to low departSpeed and decelerating/accelerating for planned stops
Returns
The time the vehicle lost due to various effects
Definition at line 549 of file MSVehicle.h.
References myTimeLoss.
double MSVehicle::getTimeLossSeconds () const inline
Returns the time loss in seconds.
Definition at line 586 of file MSVehicle.h.
References myTimeLoss, and STEPS2TIME.
Referenced by GUIVehicle::getColorValue(), and GUIVehicle::getParameterWindow().
SUMOVehicleClass MSBaseVehicle::getVClass () const inline virtual inherited
Returns the vehicle's access class.
Returns
The vehicle's access class
Implements SUMOVehicle.
Definition at line 124 of file MSBaseVehicle.h.
References MSBaseVehicle::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getParameter(), MSBaseVehicle::myType, MSBaseVehicle::succEdge(), and SUMOVTypeParameter::vehicleClass.
Referenced by GUIVehicle::drawRouteHelper(), MSPedestrianPushButton::isActiveForEdge(), and MSBaseVehicle::reroute().
const MSVehicleType& MSBaseVehicle::getVehicleType () const inline virtual inherited
Returns the vehicle's type definition.
Returns
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 116 of file MSBaseVehicle.h.
References MSBaseVehicle::myType.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptToLeaders(), addStop(), MSLane::basePos(), MSTransportableControl::boardAnyWaiting(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), checkRewindLinkLanes(), MSLaneChanger::computeOvertakingTime(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawRailCarriages(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), enterLaneAtInsertion(), enterLaneAtLaneChange(), MEVehicle::estimateLeaveSpeed(), estimateLeaveSpeed(), executeMove(), MSLane::executeMovements(), MSLane::freeInsertion(), MEVehicle::getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSBaseVehicle::getImpatience(), getLateralOverlap(), MSLane::getLeader(), getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), getRightSideOnEdge(), getRightSideOnLane(), MSLeaderInfo::getSubLanes(), getTimeGapOnLane(), MESegment::getTimeHeadway(), TraCI_Vehicle::getTypeID(), TraCI_Vehicle::getVehicleType(), GUIBaseVehicle::getVType(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MESegment::hasSpaceFor(), MSLane::incorporateVehicle(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSLCM_SL2015::keepLatGap(), MSLane::lastInsertion(), MSLane::leftByLaneChange(), MSTransportableControl::loadAnyWaiting(), MESegment::loadState(), overlap(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), processNextStop(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), MSLaneChanger::registerUnchanged(), MESegment::removeCar(), MSLane::removeVehicle(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSBaseVehicle::saveState(), GUIVehicle::selectBlockingFoes(), GUIBaseVehicle::setFunctionalColor(), setTentativeLaneAndPosition(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), updateFurtherLanes(), MSLCM_SL2015::updateGaps(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
Position MSVehicle::getVelocityVector () const inline
Returns the vehicle's direction in radians.
Returns
The vehicle's current angle
Definition at line 602 of file MSVehicle.h.
References computeAngle(), myAngle, myState, setAngle(), and MSVehicle::State::speed().
Referenced by MSDevice_SSM::updateEncounter().
double MSVehicle::getWaitingSeconds () const inline
Returns the number of seconds waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Definition at line 570 of file MSVehicle.h.
References myWaitingTime, and STEPS2TIME.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), TraCI_Vehicle::getWaitingTime(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSPedestrianPushButton::isActiveForEdge(), MSEmissionExport::write(), MSQueueExport::writeLane(), and MSFullExport::writeVehicles().
SUMOTime MSVehicle::getWaitingTime () const inline virtual
Returns the SUMOTime waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Implements SUMOVehicle.
Definition at line 536 of file MSVehicle.h.
References myWaitingTime.
Referenced by checkRewindLinkLanes(), executeMove(), MSLane::executeMovements(), MSLink::getLeaderInfo(), and GUIVehicle::selectBlockingFoes().
const MSEdgeWeightsStorage & MSVehicle::getWeightsStorage () const
Returns the vehicle's internal edge travel times/efforts container.
If the vehicle does not have such a container, it is built.
Returns
The vehicle's knowledge about edge weights
Definition at line 693 of file MSVehicle.cpp.
References _getWeightsStorage().
Referenced by TraCI_Vehicle::getAdaptedTraveltime(), TraCI_Vehicle::getEffort(), MSNet::getEffort(), MSNet::getTravelTime(), and TraCIServerAPI_Vehicle::processSet().
MSEdgeWeightsStorage & MSVehicle::getWeightsStorage ()
Definition at line 699 of file MSVehicle.cpp.
References _getWeightsStorage().
bool MSVehicle::hasArrived () const virtual
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
Reimplemented from MSBaseVehicle.
Definition at line 607 of file MSVehicle.cpp.
References MSRoute::end(), isRemoteControlled(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, MSVehicle::State::myPos, MSBaseVehicle::myRoute, myState, myStops, and POSITION_EPS.
Referenced by enterLaneAtMove(), executeMove(), and MSLane::executeMovements().
bool MSBaseVehicle::hasDeparted () const virtual inherited
Returns whether this vehicle has already departed.
Implements SUMOVehicle.
Definition at line 287 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDeparture, and MSBaseVehicle::NOT_YET_DEPARTED.
Referenced by addStop(), MSBaseVehicle::createDevice(), MSLane::forceVehicleInsertion(), TraCI_Vehicle::getRouteIndex(), MEVehicle::loadState(), loadState(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::setArrivalPos().
bool MSBaseVehicle::hasDevice (const std::string & deviceName) const inherited
check whether the vehicle is equiped with a device of the given type
Definition at line 478 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by MSBaseVehicle::createDevice(), and TraCI_Vehicle::getParameter().
bool MSVehicle::hasInfluencer () const inline
Definition at line 1425 of file MSVehicle.h.
References adaptLaneEntering2MoveReminder(), getSafeFollowSpeed(), getSpaceTillLastStanding(), getStopEdges(), influenceChangeDecision(), loadState(), myInfluencer, nextLinkPriority(), saveState(), setBlinkerInformation(), setEmergencyBlueLight(), setVTDState(), and updateOccupancyAndCurrentBestLane().
Referenced by MSLane::detectCollisionBetween(), MSLane::handleCollisionBetween(), influenceChangeDecision(), MSLCM_SL2015::keepLatGap(), and MSAbstractLaneChangeModel::setOwnState().
bool MSVehicle::hasStops () const inline
Returns whether the vehicle has to stop somewhere.
Returns
Whether the vehicle has to stop somewhere
Definition at line 887 of file MSVehicle.h.
References collisionStopTime(), DELTA_T, isParking(), isRemoteControlled(), isStopped(), myStops, and wasRemoteControlled().
Referenced by MSLane::isInsertionSuccess(), and TraCI_Vehicle::resume().
bool MSBaseVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const virtual inherited
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implements SUMOVehicle.
Definition at line 306 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSVehicleType::getVehicleClass(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, and MSBaseVehicle::myType.
Referenced by MSBaseVehicle::getDevices(), MESegment::initialise(), TraCI_Vehicle::isRouteValid(), MSBaseVehicle::MSBaseVehicle(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::replaceRouteEdges().
int MSVehicle::influenceChangeDecision (int state)
allow TraCI to influence a lane change decision
Definition at line 4017 of file MSVehicle.cpp.
References MSLane::getEdge(), getInfluencer(), MSNet::getInstance(), getLaneIndex(), hasInfluencer(), MSVehicle::Influencer::influenceChangeDecision(), and myLane.
Referenced by MSLCM_LC2013::_wantsChange(), MSAbstractLaneChangeModel::cancelRequest(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLCM_SL2015::checkStrategicChange(), and hasInfluencer().
bool MSVehicle::isFrontOnLane (const MSLane * lane) const virtual
Returns the information whether the front of the vehicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Reimplemented from MSBaseVehicle.
Definition at line 2465 of file MSVehicle.cpp.
References getLaneChangeModel(), MSAbstractLaneChangeModel::getShadowLane(), and myLane.
Referenced by checkRewindLinkLanes(), MSLane::getFirstVehicleInformation(), MSLane::getFollowersOnConsecutive(), MSLink::getLeaderInfo(), MSLane::getLeadersOnConsecutive(), MSLane::getPartialBehind(), and isOnRoad().
bool MSVehicle::isOnRoad () const inline virtual
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Reimplemented from MSBaseVehicle.
Definition at line 510 of file MSVehicle.h.
References getRerouteOrigin(), isFrontOnLane(), and myAmOnNet.
Referenced by GUIApplicationWindow::checkGamingEvents(), MSDevice_SSM::findSurroundingVehicles(), TraCI_Vehicle::getAllowedSpeed(), TraCI_Vehicle::getBestLanes(), TraCI_Vehicle::getDistance(), getDistanceToPosition(), TraCI_Vehicle::getDrivingDistance(), TraCI_Vehicle::getDrivingDistance2D(), TraCI_Vehicle::getLaneChangeState(), TraCI_Vehicle::getLaneID(), TraCI_Vehicle::getLaneIndex(), TraCI_Vehicle::getLanePosition(), TraCI_Vehicle::getLateralLanePosition(), TraCI_Vehicle::getLeader(), TraCI_Vehicle::getNextTLS(), MSVTKExport::getPositions(), TraCI_Vehicle::getSlope(), MSVTKExport::getSpeed(), TraCI_Vehicle::isVisible(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Vehicle::vtdMap(), MSBatteryExport::write(), and MSQueueExport::writeLane().
bool MSVehicle::isParking () const virtual
Returns whether the vehicle is parking.
Returns
whether the vehicle is parking
Implements SUMOVehicle.
Definition at line 1127 of file MSVehicle.cpp.
References isStopped(), and myStops.
Referenced by MSVehicleTransfer::add(), computeAngle(), MSLane::executeMovements(), getPosition(), GUIVehicle::getStopInfo(), hasStops(), and TraCI_Vehicle::isVisible().
bool MSVehicle::isRemoteControlled () const virtual
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Reimplemented from MSBaseVehicle.
Definition at line 4037 of file MSVehicle.cpp.
References MSVehicle::Influencer::isVTDControlled(), and myInfluencer.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), executeMove(), hasArrived(), and hasStops().
virtual bool MSVehicle::isSelected () const inline virtual
whether this vehicle is selected in the GUI
Reimplemented in GUIVehicle.
Definition at line 810 of file MSVehicle.h.
bool MSVehicle::isStopped () const virtual
Returns whether the vehicle is at a stop.
Returns
Whether the vehicle has stopped
Implements SUMOVehicle.
Definition at line 1115 of file MSVehicle.cpp.
References myStops.
Referenced by MSLaneChanger::changeOpposite(), executeMove(), MSLane::executeMovements(), GUIVehicle::getStopInfo(), TraCI_Vehicle::getStopState(), hasStops(), MSLCM_LC2013::informLeader(), isParking(), isStoppedInRange(), isStoppedTriggered(), and resumeFromStopping().
bool MSVehicle::isStoppedInRange (double pos) const
return whether the given position is within range of the current stop
Definition at line 1139 of file MSVehicle.cpp.
References isStopped(), and myStops.
Referenced by MSVehicleControl::getWaitingVehicle(), and nextStopDist().
bool MSVehicle::isStoppedTriggered () const virtual
Returns whether the vehicle is on a triggered stop.
Returns
whether the vehicle is on a triggered stop
Implements SUMOVehicle.
Definition at line 1133 of file MSVehicle.cpp.
References isStopped(), and myStops.
Referenced by nextStopDist().
bool MSVehicle::knowsEdgeTest (MSEdge & edge) const
Referenced by nextStopDist().
void MSVehicle::leaveLane (const MSMoveReminder::Notification reason, const MSLane * approachedLane = 0)
Update of members if vehicle leaves a new lane in the lane change step or at arrival.
Definition at line 2872 of file MSVehicle.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSNet::getInstance(), myAmOnNet, MSBaseVehicle::myCurrEdge, myFurtherLanes, myFurtherLanesPosLat, MSBaseVehicle::myMoveReminders, MSVehicle::State::myPos, myState, myStops, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSMoveReminder::NOTIFICATION_PARKING, MSMoveReminder::NOTIFICATION_TELEPORT, resumeFromStopping(), SIMTIME, time2string(), and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), congested(), executeMove(), onRemovalFromNet(), MSAbstractLaneChangeModel::primaryLaneChanged(), and MSLane::removeVehicle().
void MSVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) virtual
Loads the state of this vehicle from the given description.
Implements SUMOVehicle.
Definition at line 4129 of file MSVehicle.cpp.
References SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), MSBaseVehicle::hasDeparted(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::State::mySpeed, myState, myWaitingTime, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, and SUMO_ATTR_STATE.
Referenced by hasInfluencer().
int MSVehicle::nextLinkPriority (const std::vector< MSLane * > & conts) static
get a numerical value for the priority of the upcoming link
Definition at line 3243 of file MSVehicle.cpp.
References MSLinkContHelper::getConnectingLink(), and MSLink::havePriority().
Referenced by hasInfluencer(), and updateBestLanes().
double MSVehicle::nextStopDist () const inline
return the distance to the next stop or doubleMax if there is none.
Definition at line 917 of file MSVehicle.h.
References addContainer(), addPerson(), getCO2Emissions(), getCOEmissions(), getContainerNumber(), getContainers(), getDistanceToPosition(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), getLaneIndex(), getLeader(), getNOxEmissions(), getPersonNumber(), getPersons(), getPMxEmissions(), getTimeGapOnLane(), isStoppedInRange(), isStoppedTriggered(), knowsEdgeTest(), myStopDist, processNextStop(), and removeTransportable().
Referenced by MSLaneChanger::changeOpposite().
void MSBaseVehicle::onDepart () virtual inherited
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 279 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), MSNet::getVehicleControl(), MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, and MSVehicleControl::vehicleDeparted().
Referenced by enterLaneAtInsertion(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessVTD(), and MESegment::receive().
bool MSVehicle::onFurtherEdge (const MSEdge * edge) const
whether this vehicle has its back (and no its front) on the given edge
Definition at line 3802 of file MSVehicle.cpp.
References myFurtherLanes.
Referenced by getFurtherLanesPosLat().
void MSVehicle::onRemovalFromNet (const MSMoveReminder::Notification reason)
Called when the vehicle is removed from the network.
Moves along work reminders and informs all devices about quitting. Calls "leaveLane" then.
Parameters
[in] reason why the vehicle leaves (reached its destination, parking, teleport)
Definition at line 598 of file MSVehicle.cpp.
References MSVehicleTransfer::getInstance(), leaveLane(), myLFLinkLanes, MSVehicleTransfer::remove(), and removeApproachingInformation().
Referenced by MSVehicleTransfer::add(), MSLane::detectCollisions(), MSLane::executeMovements(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), and MSCalibrator::removePending().
MSVehicle& MSVehicle::operator= (const MSVehicle &) private
invalidated assignment operator
static bool MSVehicle::overlap (const MSVehicle * veh1, const MSVehicle * veh2) inline static
Returns true if the two vehicles overlap.
Definition at line 614 of file MSVehicle.h.
References MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myPos, and myState.
void MSVehicle::planMove (const SUMOTime t, const MSLeaderInfo & ahead, const double lengthsInFront)
Compute safe velocities for the upcoming lanes based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
This method goes through the best continuation lanes of the current lane and computes the safe velocities for passing/stopping at the next link as a DriveProcessItem
Afterwards it checks if any DriveProcessItem should be discarded to avoid blocking a junction (checkRewindLinkLanes).
Finally the ApproachingVehicleInformation is registered for all links that shall be passed
Parameters
[in] t The current timeStep
[in] ahead The leaders (may be 0)
[in] lengthsInFront Sum of vehicle lengths in front of the vehicle
Definition at line 1363 of file MSVehicle.cpp.
References checkRewindLinkLanes(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), getLaneChangeModel(), getLateralPositionOnLane(), getPositionOnLane(), getSpeed(), myLane, myLFLinkLanes, myStopDist, planMoveInternal(), MSAbstractLaneChangeModel::resetChanged(), and STEPS2TIME.
void MSVehicle::planMoveInternal (const SUMOTime t, MSLeaderInfo ahead, DriveItemVector & lfLinks, double & myStopDist) const protected
Todo:
: documentation
Definition at line 1414 of file MSVehicle.cpp.
References MSVehicle::DriveProcessItem::adaptLeaveSpeed(), adaptToLeaders(), MSLeaderInfo::addLeader(), ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, MSCFModel::brakeGap(), checkLinkLeader(), MSLeaderInfo::clear(), CRLL_LOOK_AHEAD, DEBUG_COND, DELTA_T, DIST_TO_STOPLINE_EXPECT_PRIORITY, MSEdge::EDGEFUNCTION_INTERNAL, MSRoute::end(), estimateLeaveSpeed(), MSCFModel::estimateSpeedAfterDistance(), MSCFModel::freeSpeed(), gDebugFlag1, gDebugSelectedVehicle, getBestLanesContinuation(), getCarFollowModel(), MSLane::getEdge(), MSVehicle::Influencer::getEmergencyBrakeRedLight(), MSVehicle::Stop::getEndPos(), MSBaseVehicle::getID(), MSLane::getIncomingLanes(), MSNet::getInstance(), getLane(), getLaneChangeModel(), MSLane::getLastVehicleInformation(), getLateralOverlap(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxAccel(), MSCFModel::getMaxDecel(), MSCFModel::getMinimalArrivalSpeed(), MSCFModel::getMinimalArrivalSpeedEuler(), MSCFModel::getMinimalArrivalTime(), MSLane::getOpposite(), MSLane::getOppositeLeader(), MSLane::getParallelLane(), MSLink::getParallelLink(), getPositionOnLane(), MSEdge::getPurpose(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowLane(), getSpeed(), MSCFModel::getSpeedAfterMaxDecel(), MSLane::getVehicleMaxSpeed(), MSLane::getVehicleNumber(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSEdge::getWidth(), MSGlobals::gSemiImplicitEulerUpdate, MSGlobals::gUsingInternalLanes, MSVehicle::Influencer::influenceSpeed(), MSEdge::isInternal(), MSLane::isLinkEnd(), MSAbstractLaneChangeModel::isOpposite(), LINKDIR_LEFT, LINKDIR_RIGHT, LINKSTATE_TL_RED, LINKSTATE_TL_REDYELLOW, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, max, MAX2(), MSCFModel::maximumSafeStopSpeed(), MSCFModel::maxNextSpeed(), MIN2(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, myInfluencer, myLane, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, myState, myStops, NUMERICAL_EPS, POSITION_EPS, removeApproachingInformation(), SIMTIME, SPEED2DIST, STEPS2TIME, MSCFModel::stopSpeed(), MSLane::succLinkSec(), TIME2STEPS, and toString().
Referenced by planMove().
double MSVehicle::processNextStop (double currentVelocity)
Processes stops, returns the velocity needed to reach the stop.
Returns
The velocity in dependance to the next/current stop
Todo:
Describe more detailed
See also
Stop
MSStoppingPlace
MSStoppingPlace
Definition at line 1145 of file MSVehicle.cpp.
References activateReminders(), MSStopOut::active(), MSBaseVehicle::addReminder(), MSVehicleControl::addWaiting(), MSVehicle::Stop::awaitedContainers, MSVehicle::Stop::awaitedPersons, MSTransportableControl::boardAnyWaiting(), MSVehicle::Stop::busstop, MSVehicle::Stop::collision, MSVehicle::Stop::containerstop, MSVehicle::Stop::containerTriggered, DEBUG_COND, DELTA_T, MSVehicle::Stop::duration, MSVehicle::Stop::edge, MSVehicle::Stop::endPos, MSParkingArea::enter(), MSStoppingPlace::enter(), MSStoppingPlace::getBeginLanePosition(), MSParkingArea::getCapacity(), getCarFollowModel(), MSNet::getContainerControl(), getContainerNumber(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), MSVehicle::Stop::getEndPos(), Named::getID(), MSBaseVehicle::getID(), MSStopOut::getInstance(), MSNet::getInstance(), MSParkingArea::getLastFreePos(), MSStoppingPlace::getLastFreePos(), MSVehicleType::getLength(), MSVehicleType::getMinGap(), MSLane::getMoveReminders(), MSParkingArea::getOccupancy(), MSNet::getPersonControl(), getPersonNumber(), getSpeed(), MSDevice_Transportable::getTransportables(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSGlobals::gSemiImplicitEulerUpdate, MSNet::hasContainers(), MSNet::hasPersons(), MSNet::informVehicleStateListener(), MSVehicle::Stop::lane, MSTransportableControl::loadAnyWaiting(), MAX2(), myAmRegisteredAsWaitingForContainer, myAmRegisteredAsWaitingForPerson, myContainerDevice, MSBaseVehicle::myCurrEdge, myLane, myPersonDevice, MSVehicle::State::myPos, MSVehicle::State::mySpeed, myState, myStops, MSBaseVehicle::myType, MSMoveReminder::NOTIFICATION_PARKING_REROUTE, NUMERICAL_EPS, MSVehicle::Stop::parkingarea, MSVehicle::State::pos(), MSVehicle::Stop::reached, MSVehicleControl::registerOneWaitingForContainer(), MSVehicleControl::registerOneWaitingForPerson(), MSStoppingPlace::removeTransportable(), resumeFromStopping(), SIMTIME, MSVehicle::Stop::startPos, STOPPING_PLACE_OFFSET, MSCFModel::stopSpeed(), MSStopOut::stopStarted(), SUMO_const_haltingSpeed, MSVehicle::Stop::triggered, MSVehicleControl::unregisterOneWaitingForContainer(), MSVehicleControl::unregisterOneWaitingForPerson(), MSVehicle::Stop::until, MSNet::VEHICLE_STATE_STARTING_STOP, and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), MSVehicleTransfer::loadState(), MSLane::loadState(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel::moveHelper(), and nextStopDist().
void MSVehicle::removeApproachingInformation (DriveItemVector & lfLinks) const protected
unregister approach from all upcoming links
Definition at line 3688 of file MSVehicle.cpp.
References getLaneChangeModel(), and MSAbstractLaneChangeModel::removeShadowApproachingInformation().
Referenced by onRemovalFromNet(), planMoveInternal(), and ~MSVehicle().
void MSBaseVehicle::removeReminder (MSMoveReminder * rem) inherited
Removes a MoveReminder dynamically.
Parameters
[in] rem the reminder to remove
See also
MSMoveReminder
Definition at line 345 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices().
void MSVehicle::removeTransportable (MSTransportable * t)
removes a person or container
Definition at line 3478 of file MSVehicle.cpp.
References myContainerDevice, myPersonDevice, and MSDevice_Transportable::removeTransportable().
Referenced by nextStopDist().
bool MSVehicle::replaceParkingArea (MSParkingArea * parkingArea, std::string & errorMsg) virtual
replace the current parking area stop with a new stop with merge duration
Implements SUMOVehicle.
Definition at line 1031 of file MSVehicle.cpp.
References addStop(), SUMOVehicleParameter::Stop::awaitedContainers, MSVehicle::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, MSVehicle::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, MSVehicle::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSStoppingPlace::getLane(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, myLane, MSBaseVehicle::myParameter, myStops, SUMOVehicleParameter::Stop::parking, MSVehicle::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, MSVehicle::Stop::parkingarea, MSVehicle::Stop::reached, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::Stop::triggered, MSVehicle::Stop::triggered, SUMOVehicleParameter::Stop::until, MSVehicle::Stop::until, and updateBestLanes().
bool MSVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0, bool addStops = true) virtual
Replaces the current route by the given one.
It is possible that the new route is not accepted, if it does not contain the vehicle's current edge.
Parameters
[in] route The new route to pass
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 616 of file MSVehicle.cpp.
References MSRoute::addReference(), addStop(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), MSRoute::contains(), MSLane::getEdge(), MSRoute::getEdges(), MSNet::getInstance(), MSLane::getOutgoingLanes(), MSRoute::getStops(), MSNet::informVehicleStateListener(), MSEdge::isInternal(), MSBaseVehicle::myCurrEdge, myLane, myLastBestLanesEdge, myLastBestLanesInternalLane, MSBaseVehicle::myNumberReroutes, MSBaseVehicle::myRoute, myStops, MSRoute::release(), updateBestLanes(), MSNet::VEHICLE_STATE_NEWROUTE, and WRITE_WARNING.
Referenced by TraCIServerAPI_Vehicle::processSet().
bool MSBaseVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false, bool addStops = true) virtual inherited
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
[in] addStops Parameter for replaceRoute
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 214 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSBaseVehicle::addStops(), MSRoute::begin(), RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getColor(), MSRoute::getEdges(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getNumberReroutes(), MSBaseVehicle::getRerouteOrigin(), MSRoute::getStops(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), MSRoute::size(), toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::reroute().
void MSVehicle::replaceVehicleType (MSVehicleType * type)
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myType".
Parameters
[in] type The new vehicle type
See also
MSVehicle::myType
Definition at line 3572 of file MSVehicle.cpp.
References MSBaseVehicle::myType.
Referenced by TraCIServerAPI_Vehicle::processSet().
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) virtual inherited
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implements SUMOVehicle.
Definition at line 154 of file MSBaseVehicle.cpp.
References MSEdge::allowedLanes(), MSBaseVehicle::calculateArrivalParams(), SUMOAbstractRouter< E, V >::compute(), MSInsertionControl::descheduleDeparture(), MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, MSGlobals::gCheckRoutes, Named::getID(), MSBaseVehicle::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSRoute::getLastEdge(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::getVClass(), MSEdge::isTaz(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::replaceRouteEdges(), SUMOVehicleParameter::toTaz, SUMOVehicleParameter::via, and WRITE_WARNING.
Referenced by MSBaseVehicle::getCurrentRouteEdge(), and TraCIServerAPI_Vehicle::processSet().
void MSVehicle::resetRoutePosition (int index)
Definition at line 684 of file MSVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSCalibrator::execute().
bool MSVehicle::resumeFromStopping ()
resumes a vehicle from stopping
Returns
true on success, the resuming fails if the vehicle wasn't parking in the first place
Definition at line 3940 of file MSVehicle.cpp.
References MSStopOut::active(), MSLane::COLLISION_ACTION_WARN, MSLane::getCollisionAction(), MSLane::getEdge(), MSStopOut::getInstance(), MSNet::getInstance(), MSNet::getVehicleControl(), MSNet::informVehicleStateListener(), isStopped(), myAmRegisteredAsWaitingForContainer, myAmRegisteredAsWaitingForPerson, myCollisionImmunity, myLane, myStops, myWaitingTime, MSVehicleControl::removeWaiting(), MSStopOut::stopEnded(), TIME2STEPS, MSVehicleControl::unregisterOneWaitingForContainer(), MSVehicleControl::unregisterOneWaitingForPerson(), updateBestLanes(), and MSNet::VEHICLE_STATE_ENDING_STOP.
Referenced by MSLane::executeMovements(), leaveLane(), processNextStop(), TraCI_Vehicle::resume(), and signalSet().
void MSVehicle::saveState (OutputDevice & out) virtual
Saves the states of a vehicle.
Reimplemented from MSBaseVehicle.
Definition at line 4104 of file MSVehicle.cpp.
References MSRoute::begin(), OutputDevice::closeTag(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, MSBaseVehicle::myDevices, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, myState, myStops, myWaitingTime, MSBaseVehicle::saveState(), SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, SUMO_ATTR_STATE, toString(), OutputDevice::writeAttr(), and Parameterised::writeParams().
Referenced by hasInfluencer().
void MSVehicle::setAngle (double angle)
Set a custom vehicle angle in rad.
Definition at line 822 of file MSVehicle.cpp.
References myAngle.
Referenced by getVelocityVector(), MSVehicle::Influencer::postProcessVTD(), and MSLaneChangerSublane::startChangeSublane().
virtual void MSBaseVehicle::setArrivalPos (double arrivalPos) inline virtual inherited
Sets this vehicle's desired arrivalPos for its current route.
Implements SUMOVehicle.
Definition at line 276 of file MSBaseVehicle.h.
References MSBaseVehicle::hasArrived(), MSBaseVehicle::hasDeparted(), and MSBaseVehicle::myArrivalPos.
void MSVehicle::setBlinkerInformation () protected
Definition at line 3521 of file MSVehicle.cpp.
References getBestLanesContinuation(), getLane(), getLaneChangeModel(), MSLane::getLength(), MSLane::getLinkCont(), MSAbstractLaneChangeModel::getOwnState(), getPositionOnLane(), MSVehicle::Influencer::getSignals(), MSLane::getVehicleMaxSpeed(), LCA_LEFT, LCA_RIGHT, LCA_SUBLANE, LINKDIR_LEFT, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_TURN, myInfluencer, mySignals, MSVehicle::Influencer::setSignals(), MSLane::succLinkSec(), switchOffSignal(), switchOnSignal(), VEH_SIGNAL_BLINKER_LEFT, and VEH_SIGNAL_BLINKER_RIGHT.
Referenced by executeMove(), and hasInfluencer().
void MSBaseVehicle::setChosenSpeedFactor (const double factor) inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 368 of file MSBaseVehicle.h.
References MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getDevice(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::myChosenSpeedFactor, and MSBaseVehicle::saveState().
Referenced by TraCIServerAPI_Vehicle::processSet().
void MSBaseVehicle::setDeviceParameter (const std::string & deviceName, const std::string & key, const std::string & value) inherited
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 519 of file MSBaseVehicle.cpp.
References OutputDevice::closeTag(), MSMoveReminder::getDescription(), OutputDevice::getDeviceByOption(), MSBaseVehicle::getID(), MSNet::getInstance(), OptionsCont::getStringVector(), OptionsCont::isSet(), MSBaseVehicle::myDevices, OutputDevice::openTag(), STEPS2TIME, SUMO_ATTR_ID, SUMO_ATTR_TIME, toString(), and OutputDevice::writeAttr().
Referenced by TraCI_Vehicle::setParameter().
void MSVehicle::setEmergencyBlueLight (SUMOTime currentTime) protected
sets the blue flashing light for emergency vehicles
Definition at line 3560 of file MSVehicle.cpp.
References signalSet(), switchOffSignal(), switchOnSignal(), and VEH_SIGNAL_EMERGENCY_BLUE.
Referenced by executeMove(), and hasInfluencer().
void MSVehicle::setTentativeLaneAndPosition (MSLane * lane, double pos, double posLat = 0)
set tentative lane and position during insertion to ensure that all cfmodels work (some of them require veh->getLane() to return a valid lane) Once the vehicle is sucessfully inserted the lane is set again (see enterLaneAtInsertion)
Definition at line 3584 of file MSVehicle.cpp.
References MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myBackPos, myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, and myState.
Referenced by congested(), MSLane::freeInsertion(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSVehicleTransfer::loadState(), and TraCIServerAPI_Vehicle::processSet().
void MSVehicle::setVTDState (Position xyPos)
sets position outside the road network
Definition at line 4030 of file MSVehicle.cpp.
References myCachedPosition.
Referenced by hasInfluencer(), and MSVehicle::Influencer::postProcessVTD().
bool MSVehicle::signalSet (int which) const inline
Returns whether the given signal is on.
Parameters
[in] signal The signal to return the value of
Returns
Whether the given signal is on
Definition at line 1149 of file MSVehicle.h.
References addTraciStop(), addTraciStopAtStoppingPlace(), getBoundingBox(), getBoundingPoly(), getNextStop(), getSpeedWithoutTraciInfluence(), mySignals, resumeFromStopping(), unsafeLinkAhead(), and updateFurtherLanes().
Referenced by checkRewindLinkLanes(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBlueLight(), GUIVehicle::drawAction_drawVehicleBrakeLight(), and setEmergencyBlueLight().
const MSEdge * MSBaseVehicle::succEdge (int nSuccs) const virtual inherited
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 138 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSVehicleTransfer::add(), MSLane::appropriate(), MSVehicleTransfer::checkInsertions(), MESegment::getLink(), MSBaseVehicle::getVClass(), MSBaseVehicle::hasArrived(), MSPedestrianPushButton::isActiveForEdge(), MELoop::nextSegment(), TraCIServerAPI_Vehicle::processSet(), and MESegment::receive().
void MSVehicle::switchOffSignal (int signal) inline
Switches the given signal off.
Parameters
[in] signal The signal to mark as being switched off
Definition at line 1132 of file MSVehicle.h.
References mySignals.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), executeMove(), TraCIServerAPI_Vehicle::processSet(), setBlinkerInformation(), setEmergencyBlueLight(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
void MSVehicle::switchOnSignal (int signal) inline
Switches the given signal on.
Parameters
[in] signal The signal to mark as being switched on
Definition at line 1124 of file MSVehicle.h.
References mySignals.
Referenced by executeMove(), TraCIServerAPI_Vehicle::processSet(), setBlinkerInformation(), setEmergencyBlueLight(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSVehicle::unsafeLinkAhead (const MSLane * lane) const
whether the vehicle may safely move to the given lane with regard to upcoming links
Definition at line 3700 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), getBestLanesContinuation(), getCarFollowModel(), MSLane::getEdge(), MSVehicleType::getLength(), MSLane::getLength(), getPositionOnLane(), getSpeed(), MSBaseVehicle::getVehicleType(), MSEdge::isInternal(), MSLane::isLinkEnd(), LINKSTATE_ZIPPER, myLane, myLFLinkLanes, MSLane::succLinkSec(), and MSLink::ZIPPER_ADAPT_DIST.
Referenced by MSLaneChanger::checkChange(), and signalSet().
void MSVehicle::updateBestLanes (bool forceRebuild = false, const MSLane * startLane = 0)
computes the best lanes to use in order to continue the route
The information is rebuilt if the vehicle is on a different edge than the one stored in "myLastBestLanesEdge" or "forceRebuild" is true.
Otherwise, only the density changes on the stored lanes are adapted to the container only.
A rebuild must be done if the vehicle leaves a stop; then, another lane may become the best one.
If no starting lane ("startLane") is given, the vehicle's current lane ("myLane") is used as start of bect lanes building.
Parameters
[in] forceRebuild Whether the best lanes container shall be rebuilt even if the vehicle's edge has not changed
[in] startLane The lane the process shall start at ("myLane" will be used if ==0)
Definition at line 2939 of file MSVehicle.cpp.
References abs, MSEdge::allowedLanes(), MSVehicle::LaneQ::allowsContinuation, MSLane::allowsVehicleClass(), ARRIVAL_LANE_GIVEN, SUMOVehicleParameter::arrivalLaneProcedure, MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, MSEdge::clear(), MSVehicle::LaneQ::currentLength, DEBUG_COND, MSEdge::EDGEFUNCTION_INTERNAL, MSRoute::end(), gDebugSelectedVehicle, getBestLanesContinuation(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), getLaneChangeModel(), MSEdge::getLanes(), MSLane::getLength(), MSEdge::getLength(), MSLane::getLinkCont(), MSLane::getLogicalPredecessorLane(), MSLane::getNextNormal(), MSLane::getOpposite(), MSEdge::getPurpose(), MSVehicleType::getVehicleClass(), MSLane::isInternal(), MSVehicle::LaneQ::lane, MSVehicle::Stop::lane, MSVehicle::LaneQ::length, MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, myBestLanes, MSBaseVehicle::myCurrEdge, myCurrentLaneInBestLanes, myLane, myLastBestLanesEdge, myLastBestLanesInternalLane, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, myStops, MSBaseVehicle::myType, nextLinkPriority(), MSVehicle::LaneQ::nextOccupation, MSVehicle::LaneQ::occupation, POSITION_EPS, SIMTIME, MSVehicle::Stop::startPos, toString(), and updateOccupancyAndCurrentBestLane().
Referenced by addTraciStop(), addTraciStopAtStoppingPlace(), MSLaneChangerSublane::change(), MSLaneChanger::change(), enterLaneAtLaneChange(), executeMove(), MSLane::forceVehicleInsertion(), MSEdge::getDepartLane(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLane::loadState(), MSVehicle::Influencer::postProcessVTD(), replaceParkingArea(), replaceRoute(), and resumeFromStopping().
double MSVehicle::updateFurtherLanes (std::vector< MSLane * > & furtherLanes, std::vector< double > & furtherLanesPosLat, const std::vector< MSLane * > & passedLanes)
update a vector of further lanes and return the new backPos
Definition at line 2347 of file MSVehicle.cpp.
References DEBUG_COND, MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, SIMTIME, and toString().
Referenced by executeMove(), signalSet(), and MSAbstractLaneChangeModel::updateShadowLane().
void MSVehicle::updateOccupancyAndCurrentBestLane (const MSLane * startLane) protected
updates LaneQ::nextOccupation and myCurrentLaneInBestLanes
Definition at line 3259 of file MSVehicle.cpp.
References myBestLanes, and myCurrentLaneInBestLanes.
Referenced by hasInfluencer(), and updateBestLanes().
void MSVehicle::updateState (double vNext) protected
updates the vehicles state, given a next value for its speed. This value can be negative in case of the ballistic update to indicate a stop within the next timestep. (You can call this a 'hack' to emulate reasoning based on accelerations: The assumed constant acceleration a within the next time step is then a = (vNext - vCurrent)/TS)
Parameters
[in] vNext speed in the next time step
Definition at line 2290 of file MSVehicle.cpp.
References getDeltaPos(), getLaneChangeModel(), MSLane::getOpposite(), MSLane::getOppositePos(), MSGlobals::gSemiImplicitEulerUpdate, MSVehicle::Influencer::implicitDeltaPosVTD(), Position::INVALID, MSVehicle::Influencer::isVTDControlled(), MAX2(), myAcceleration, myCachedPosition, myInfluencer, myLane, MSVehicle::State::myLastCoveredDist, MSVehicle::State::myPos, MSVehicle::State::myPreviousSpeed, MSVehicle::State::mySpeed, myState, SPEED2ACCEL, and SPEED2DIST.
Referenced by estimateLeaveSpeed(), and executeMove().
bool MSVehicle::wasRemoteControlled (SUMOTime lookBack = DELTA_T) const
Returns the information whether the vehicle is fully controlled via TraCI within the lookBack time.
Definition at line 4043 of file MSVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSVehicle::Influencer::getLastAccessTimeStep(), and myInfluencer.
Referenced by hasStops(), and TraCI_Vehicle::isVisible().
bool MSVehicle::willPass (const MSEdge *const edge) const
Returns whether the vehicle wil pass the given edge.
Parameters
[in] The edge to find in the vehicle's current route
Returns
Whether the given edge will be passed by the vehicle
Todo:
Move to MSRoute?
Definition at line 672 of file MSVehicle.cpp.
References MSRoute::end(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by TraCIServerAPI_Vehicle::processSet().
void MSVehicle::workOnMoveReminders (double oldPos, double newPos, double newSpeed)
Processes active move reminder.
This method goes through all active move reminder, both those for the current lane, stored in "myMoveReminders" and those of prior lanes stored in "myOldLaneMoveReminders" calling "MSMoveReminder::notifyMove".
When processing move reminder from "myOldLaneMoveReminders", the offsets (prior lane lengths) are used, which are stored in "myOldLaneMoveReminderOffsets".
Each move reminder which is no longer active is removed from the container.
Parameters
[in] oldPos The position the vehicle had before it has moved
[in] newPos The position the vehicle has after it has moved
[in] newSpeed The vehicle's speed within this move
See also
MSMoveReminder
Definition at line 715 of file MSVehicle.cpp.
References MAX2(), and MSBaseVehicle::myMoveReminders.
Referenced by executeMove().
Friends And Related Function Documentation
friend class MSLaneChanger friend
the lane changer sets myLastLaneChangeOffset
Definition at line 87 of file MSVehicle.h.
friend class MSLaneChangerSublane friend
Definition at line 88 of file MSVehicle.h.
Field Documentation
double MSVehicle::myAcceleration protected
The current acceleration after dawdling in m/s.
Definition at line 1541 of file MSVehicle.h.
Referenced by executeMove(), getAcceleration(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), getNOxEmissions(), getPMxEmissions(), and updateState().
bool MSVehicle::myAmOnNet protected
Whether the vehicle is on the network (not parking, teleported, vaporized, or arrived)
Definition at line 1551 of file MSVehicle.h.
Referenced by enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), isOnRoad(), and leaveLane().
bool MSVehicle::myAmRegisteredAsWaitingForContainer protected
Whether this vehicle is registered as waiting for a container (for deadlock-recognition)
Definition at line 1557 of file MSVehicle.h.
Referenced by processNextStop(), and resumeFromStopping().
bool MSVehicle::myAmRegisteredAsWaitingForPerson protected
Whether this vehicle is registered as waiting for a person (for deadlock-recognition)
Definition at line 1554 of file MSVehicle.h.
Referenced by processNextStop(), and resumeFromStopping().
double MSVehicle::myAngle protected
the angle in radians (
Todo:
consider moving this into myState)
Definition at line 1562 of file MSVehicle.h.
Referenced by MSLaneChanger::continueChange(), enterLaneAtInsertion(), enterLaneAtLaneChange(), executeMove(), getAngle(), getVelocityVector(), and setAngle().
int MSBaseVehicle::myArrivalLane protected inherited
The destination lane where the vehicle stops.
Definition at line 446 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), and updateBestLanes().
double MSBaseVehicle::myArrivalPos protected inherited
The position on the destination lane where the vehicle stops.
Definition at line 443 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getArrivalPos(), MEVehicle::hasArrived(), hasArrived(), planMoveInternal(), resetRoutePosition(), MSBaseVehicle::setArrivalPos(), and updateBestLanes().
std::vector<std::vector<LaneQ> > MSVehicle::myBestLanes protected
Definition at line 1521 of file MSVehicle.h.
Referenced by adaptBestLanesOccupation(), GUIVehicle::drawBestLanes(), getBestLaneOffset(), getBestLanes(), getBestLanesContinuation(), updateBestLanes(), and updateOccupancyAndCurrentBestLane().
Position MSVehicle::myCachedPosition mutable protected
Definition at line 1570 of file MSVehicle.h.
Referenced by MSLaneChanger::continueChange(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), executeMove(), getPosition(), setVTDState(), MSLaneChangerSublane::startChangeSublane(), and updateState().
MSCFModel::VehicleVariables* MSVehicle::myCFVariables private
The per vehicle variables of the car following model.
Definition at line 1705 of file MSVehicle.h.
Referenced by getCarFollowVariables(), and MSVehicle().
double MSBaseVehicle::myChosenSpeedFactor protected inherited
A precomputed factor by which the driver wants to be faster than the speed limit.
Definition at line 416 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getChosenSpeedFactor(), and MSBaseVehicle::setChosenSpeedFactor().
SUMOTime MSVehicle::myCollisionImmunity protected
amount of time for which the vehicle is immune from collisions
Definition at line 1568 of file MSVehicle.h.
Referenced by collisionStopTime(), executeMove(), and resumeFromStopping().
MSDevice_Transportable* MSVehicle::myContainerDevice protected
The containers this vehicle may have.
Definition at line 1538 of file MSVehicle.h.
Referenced by addContainer(), GUIVehicle::drawAction_drawPersonsAndContainers(), getContainerNumber(), getContainers(), processNextStop(), and removeTransportable().
MSRouteIterator MSBaseVehicle::myCurrEdge protected inherited
Iterator to current route-edge.
Definition at line 413 of file MSBaseVehicle.h.
Referenced by addStop(), enterLaneAtMove(), executeMove(), MSBaseVehicle::getCurrentRouteEdge(), getDistanceToPosition(), MSBaseVehicle::getEdge(), MSBaseVehicle::getRerouteOrigin(), getRerouteOrigin(), getRoutePosition(), MEVehicle::hasArrived(), hasArrived(), MSBaseVehicle::hasValidRoute(), leaveLane(), MEVehicle::loadState(), loadState(), MEVehicle::moveRoutePointer(), planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), processNextStop(), replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), resetRoutePosition(), MEVehicle::saveState(), saveState(), MSBaseVehicle::succEdge(), updateBestLanes(), and willPass().
std::vector<LaneQ>::iterator MSVehicle::myCurrentLaneInBestLanes protected
Definition at line 1526 of file MSVehicle.h.
Referenced by updateBestLanes(), and updateOccupancyAndCurrentBestLane().
double MSBaseVehicle::myDepartPos protected inherited
The real depart position.
Definition at line 440 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getDepartPos(), loadState(), MSBaseVehicle::onDepart(), and saveState().
SUMOTime MSBaseVehicle::myDeparture protected inherited
The real departure time.
Definition at line 437 of file MSBaseVehicle.h.
Referenced by enterLaneAtInsertion(), MSBaseVehicle::getDeparture(), MSBaseVehicle::hasDeparted(), MEVehicle::loadState(), loadState(), MSBaseVehicle::onDepart(), MEVehicle::saveState(), and saveState().
std::vector<MSDevice*> MSBaseVehicle::myDevices protected inherited
The devices this vehicle has.
Definition at line 434 of file MSBaseVehicle.h.
Referenced by addContainer(), addPerson(), MSBaseVehicle::createDevice(), MSBaseVehicle::getDevice(), MSBaseVehicle::getDeviceParameter(), MSBaseVehicle::getDevices(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIBaseVehicle::GUIBaseVehicle(), MSBaseVehicle::hasDevice(), MSBaseVehicle::MSBaseVehicle(), saveState(), MSBaseVehicle::setDeviceParameter(), and MSBaseVehicle::~MSBaseVehicle().
MSEdgeWeightsStorage* MSVehicle::myEdgeWeights mutable private
Definition at line 1702 of file MSVehicle.h.
Referenced by _getWeightsStorage(), and ~MSVehicle().
std::vector< MSLane * > MSVehicle::myEmptyLaneVector static protected
Definition at line 1528 of file MSVehicle.h.
Referenced by getBestLanesContinuation().
std::vector< MSTransportable * > MSVehicle::myEmptyTransportableVector static protected
Definition at line 1529 of file MSVehicle.h.
Referenced by getContainers(), and getPersons().
std::vector<MSLane*> MSVehicle::myFurtherLanes protected
The information into which lanes the vehicle laps into.
Definition at line 1544 of file MSVehicle.h.
Referenced by computeAngle(), enterLaneAtInsertion(), enterLaneAtLaneChange(), executeMove(), getBackLane(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), getFurtherLanes(), getLatOffset(), GUIVehicle::getPreviousLane(), leaveLane(), onFurtherEdge(), and ~MSVehicle().
std::vector<double> MSVehicle::myFurtherLanesPosLat protected
Definition at line 1545 of file MSVehicle.h.
Referenced by computeAngle(), enterLaneAtInsertion(), enterLaneAtLaneChange(), executeMove(), getBackPosition(), getCenterOnEdge(), getFurtherLanesPosLat(), getLatOffset(), leaveLane(), and ~MSVehicle().
bool MSVehicle::myHaveToWaitOnNextLink protected
Definition at line 1559 of file MSVehicle.h.
Referenced by checkRewindLinkLanes(), and executeMove().
Influencer* MSVehicle::myInfluencer private
An instance of a velocity/lane influencing instance; built in "getInfluencer".
Definition at line 1709 of file MSVehicle.h.
Referenced by checkRewindLinkLanes(), executeMove(), getInfluencer(), getPosition(), getSpeedWithoutTraciInfluence(), hasInfluencer(), isRemoteControlled(), planMoveInternal(), setBlinkerInformation(), updateState(), wasRemoteControlled(), and ~MSVehicle().
MSLane* MSVehicle::myLane protected
The lane the vehicle is on.
Definition at line 1509 of file MSVehicle.h.
Referenced by adaptLaneEntering2MoveReminder(), adaptToLeader(), adaptToLeaders(), addTraciStop(), addTraciStopAtStoppingPlace(), checkLinkLeader(), checkRewindLinkLanes(), computeAngle(), GUIVehicle::drawAction_drawRailCarriages(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), executeMove(), getBackLane(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), getDistanceToPosition(), getLane(), getLaneIndex(), getLateralOverlap(), getLatOffset(), getLeader(), getMaxSpeedOnLane(), GUIVehicle::getParameterWindow(), getPosition(), getRerouteOrigin(), getRightSideOnLane(), getSlope(), influenceChangeDecision(), isFrontOnLane(), planMove(), planMoveInternal(), processNextStop(), replaceParkingArea(), replaceRoute(), resumeFromStopping(), GUIVehicle::selectBlockingFoes(), setTentativeLaneAndPosition(), unsafeLinkAhead(), updateBestLanes(), and updateState().
MSAbstractLaneChangeModel* MSVehicle::myLaneChangeModel protected
Definition at line 1511 of file MSVehicle.h.
Referenced by enterLaneAtInsertion(), enterLaneAtLaneChange(), getLaneChangeModel(), MSVehicle(), and ~MSVehicle().
const MSEdge* MSVehicle::myLastBestLanesEdge protected
Definition at line 1513 of file MSVehicle.h.
Referenced by enterLaneAtMove(), replaceRoute(), and updateBestLanes().
const MSLane* MSVehicle::myLastBestLanesInternalLane protected
Definition at line 1514 of file MSVehicle.h.
Referenced by replaceRoute(), and updateBestLanes().
DriveItemVector MSVehicle::myLFLinkLanes protected
Definition at line 1627 of file MSVehicle.h.
Referenced by GUIVehicle::drawAction_drawLinkItems(), executeMove(), onRemovalFromNet(), planMove(), GUIVehicle::selectBlockingFoes(), unsafeLinkAhead(), and ~MSVehicle().
MoveReminderCont MSBaseVehicle::myMoveReminders protected inherited
Currently relevant move reminders.
Definition at line 430 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::activateReminders(), activateReminders(), adaptLaneEntering2MoveReminder(), addContainer(), addPerson(), MSBaseVehicle::addReminder(), GUIBaseVehicle::GUIBaseVehicle(), leaveLane(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::removeReminder(), MEVehicle::updateDetectorForWriting(), MEVehicle::updateDetectors(), and workOnMoveReminders().
int MSBaseVehicle::myNumberReroutes protected inherited
The number of reroutings.
Definition at line 449 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getNumberReroutes(), replaceRoute(), and MEVehicle::replaceRoute().
const SUMOVehicleParameter* MSBaseVehicle::myParameter protected inherited
This Vehicle's parameter.
Definition at line 404 of file MSBaseVehicle.h.
Referenced by addStop(), MSBaseVehicle::addStops(), addTraciStop(), addTraciStopAtStoppingPlace(), MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::createDevice(), getContainerNumber(), MSBaseVehicle::getID(), MSBaseVehicle::getParameter(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), getPersonNumber(), planMoveInternal(), replaceParkingArea(), MSBaseVehicle::reroute(), MSBaseVehicle::saveState(), saveState(), updateBestLanes(), and MSBaseVehicle::~MSBaseVehicle().
MSDevice_Transportable* MSVehicle::myPersonDevice protected
The passengers this vehicle may have.
Definition at line 1535 of file MSVehicle.h.
Referenced by addPerson(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::getNumPassengers(), getPersonNumber(), getPersons(), processNextStop(), and removeTransportable().
const MSRoute* MSBaseVehicle::myRoute protected inherited
This Vehicle's route.
Definition at line 407 of file MSBaseVehicle.h.
Referenced by addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), GUIVehicle::drawRouteHelper(), executeMove(), getDistanceToPosition(), getRerouteOrigin(), MSBaseVehicle::getRoute(), getRoutePosition(), MEVehicle::hasArrived(), hasArrived(), MSBaseVehicle::hasValidRoute(), MEVehicle::moveRoutePointer(), MSBaseVehicle::MSBaseVehicle(), planMoveInternal(), replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), resetRoutePosition(), MEVehicle::saveState(), MSBaseVehicle::saveState(), saveState(), MSBaseVehicle::succEdge(), updateBestLanes(), willPass(), and MSBaseVehicle::~MSBaseVehicle().
int MSVehicle::mySignals protected
State of things of the vehicle that can be on or off.
Definition at line 1548 of file MSVehicle.h.
Referenced by getSignals(), setBlinkerInformation(), signalSet(), switchOffSignal(), and switchOnSignal().
State MSVehicle::myState protected
This Vehicles driving state (pos and speed)
Definition at line 1506 of file MSVehicle.h.
Referenced by adaptToLeaders(), addStop(), MSLaneChanger::changeOpposite(), checkRewindLinkLanes(), computeAngle(), congested(), MSLaneChanger::continueChange(), GUIVehicle::drawAction_drawRailCarriages(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), executeMove(), fixPosition(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), getCO2Emissions(), getCOEmissions(), getDeltaPos(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), getLastStepDist(), getLateralPositionOnLane(), getLatOffset(), getNOxEmissions(), getPMxEmissions(), getPosition(), getPositionOnLane(), getPreviousSpeed(), getRerouteOrigin(), getRightSideOnLane(), getSpeed(), getSpeedWithoutTraciInfluence(), getVelocityVector(), hasArrived(), leaveLane(), loadState(), overlap(), planMoveInternal(), processNextStop(), saveState(), setTentativeLaneAndPosition(), MSLaneChangerSublane::startChangeSublane(), updateFurtherLanes(), and updateState().
double MSVehicle::myStopDist protected
distance to the next stop or -1 if there is none
Definition at line 1565 of file MSVehicle.h.
Referenced by nextStopDist(), and planMove().
std::list<Stop> MSVehicle::myStops protected
The vehicle's list of stops.
Definition at line 1532 of file MSVehicle.h.
Referenced by addContainer(), addPerson(), addStop(), addTraciStop(), addTraciStopAtStoppingPlace(), collisionStopTime(), computeAngle(), getNextParkingArea(), getNextStop(), getPosition(), getStopEdges(), GUIVehicle::getStopInfo(), hasArrived(), hasStops(), isParking(), isStopped(), isStoppedInRange(), isStoppedTriggered(), leaveLane(), planMoveInternal(), processNextStop(), replaceParkingArea(), replaceRoute(), resumeFromStopping(), saveState(), and updateBestLanes().
SUMOTime MSVehicle::myTimeLoss protected
the time loss due to writing with less than maximum speed
Definition at line 1503 of file MSVehicle.h.
Referenced by executeMove(), getTimeLoss(), and getTimeLossSeconds().
const MSVehicleType* MSBaseVehicle::myType protected inherited
This Vehicle's type.
Definition at line 410 of file MSBaseVehicle.h.
Referenced by addStop(), MSBaseVehicle::calculateArrivalParams(), enterLaneAtInsertion(), executeMove(), getBackPosition(), getBackPositionOnLane(), getBoundingBox(), getBoundingPoly(), getCarFollowModel(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), MSBaseVehicle::getMaxSpeed(), getMaxSpeedOnLane(), getNOxEmissions(), getPMxEmissions(), getPositionOnLane(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::hasValidRoute(), processNextStop(), replaceVehicleType(), updateBestLanes(), and ~MSVehicle().
SUMOTime MSVehicle::myWaitingTime protected
The time the vehicle waits (is not faster than 0.1m/s) in seconds.
Definition at line 1496 of file MSVehicle.h.
Referenced by enterLaneAtInsertion(), executeMove(), getWaitingSeconds(), getWaitingTime(), loadState(), resumeFromStopping(), and saveState().
WaitingTimeCollector MSVehicle::myWaitingTimeCollector protected
Definition at line 1500 of file MSVehicle.h.
Referenced by executeMove(), and getAccumulatedWaitingTime().
const SUMOTime MSBaseVehicle::NOT_YET_DEPARTED = SUMOTime_MAX static protected inherited
Definition at line 454 of file MSBaseVehicle.h.
Referenced by enterLaneAtInsertion(), MSBaseVehicle::hasDeparted(), and MSVehicle::Influencer::postProcessVTD().
The documentation for this class was generated from the following files:
MSVehicle.h
MSVehicle.cpp