SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq Class Reference
NIImporter_DlrNavteq Class Reference
Importer for networks stored in Elmar's format.
#include <NIImporter_DlrNavteq.h>
Data Structures
class ConnectedLanesHandler
Imports prohibitions regarding connectivity.
class EdgesHandler
Importer of edges stored in unsplit elmar format.
class NamesHandler
Importer of street names in DLRNavteq's (aka elmar) format.
class NodesHandler
Importer of nodes stored in unsplit elmar format.
class ProhibitionHandler
Imports prohibitions regarding connectivity.
class TimeRestrictionsHandler
Importer of street names in DLRNavteq's (aka elmar) format.
class TrafficlightsHandler
Importer of traffic lights stored in DLRNavteq's (aka elmar) format.
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads content of the optionally given dlr-navteq (aka Elmar-fomat) folder.
Static Public Attributes
static const int GEO_SCALE = 5
scaling factor for geo coordinates (DLRNavteq format uses this to increase floating point precisions)
static const std::string UNDEFINED
magic value for undefined stuff
Static Protected Member Functions
static time_t readDate (const std::string &yyyymmdd)
static int readPrefixedInt (const std::string &s, const std::string &prefix, int fallBack=0)
static time_t readTimeRec (const std::string &start, const std::string &duration)
static double readVersion (const std::string &line, const std::string &file)
Detailed Description
Importer for networks stored in Elmar's format.
Definition at line 62 of file NIImporter_DlrNavteq.h.
Member Function Documentation
void NIImporter_DlrNavteq::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Loads content of the optionally given dlr-navteq (aka Elmar-fomat) folder.
If the option "dlr-navteq-prefix" is set, the file(s) stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "dlr-navteq-prefix" is not set, this method simply returns.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 72 of file NIImporter_DlrNavteq.cpp.
References OptionsCont::getBool(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), OptionsCont::getString(), NBNetBuilder::getTLLogicCont(), NBNetBuilder::getTypeCont(), OptionsCont::isDefault(), OptionsCont::isSet(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, LineReader::readAll(), readDate(), NBEdgeCont::recheckLaneSpread(), LineReader::setFile(), and WRITE_WARNING.
Referenced by NILoader::load().
time_t NIImporter_DlrNavteq::readDate (const std::string & yyyymmdd) static protected
Definition at line 677 of file NIImporter_DlrNavteq.cpp.
References TplConvert::_str2int(), and WRITE_ERROR.
Referenced by loadNetwork().
int NIImporter_DlrNavteq::readPrefixedInt (const std::string & s, const std::string & prefix, int fallBack = 0) static protected
Definition at line 643 of file NIImporter_DlrNavteq.cpp.
Referenced by readTimeRec().
time_t NIImporter_DlrNavteq::readTimeRec (const std::string & start, const std::string & duration) static protected
Definition at line 653 of file NIImporter_DlrNavteq.cpp.
References readPrefixedInt().
Referenced by NIImporter_DlrNavteq::TimeRestrictionsHandler::report().
double NIImporter_DlrNavteq::readVersion (const std::string & line, const std::string & file) static protected
Definition at line 160 of file NIImporter_DlrNavteq.cpp.
References TplConvert::_2double(), StringUtils::to_lower_case(), and toString().
Referenced by NIImporter_DlrNavteq::EdgesHandler::report(), and NIImporter_DlrNavteq::ProhibitionHandler::report().
Field Documentation
const int NIImporter_DlrNavteq::GEO_SCALE = 5 static
scaling factor for geo coordinates (DLRNavteq format uses this to increase floating point precisions)
Definition at line 78 of file NIImporter_DlrNavteq.h.
Referenced by NIFrame::checkOptions().
const std::string NIImporter_DlrNavteq::UNDEFINED static
magic value for undefined stuff
Definition at line 81 of file NIImporter_DlrNavteq.h.
Referenced by NIImporter_DlrNavteq::ProhibitionHandler::report().
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp