SUMO - Simulation of Urban MObility: MSContainer Class Reference
MSContainer Class Reference
#include <MSContainer.h>
Data Structures
class MSContainerStage_Driving
class MSContainerStage_Tranship
Public Types
typedef std::vector< MSTransportable::Stage * > MSTransportablePlan
the structure holding the plan of a transportable
enum StageType { WAITING_FOR_DEPART = 0, WAITING = 1, MOVING_WITHOUT_VEHICLE = 2, DRIVING = 3 }
Public Member Functions
void appendStage (Stage *stage)
Appends the given stage to the current plan.
virtual double getAngle () const
return the current angle of the transportable
const MSEdge * getArrivalEdge () const
returns the final arrival edge
double getArrivalPos () const
returns the final arrival pos
MSTransportable::Stage * getCurrentStage () const
Return the current stage.
std::string getCurrentStageDescription () const
Returns the current stage description as a string.
StageType getCurrentStageType () const
the current stage type of the transportable
SUMOTime getDesiredDepart () const
Returns the desired departure time.
const MSEdge & getDestination () const
Returns the current destination.
const MSEdge * getEdge () const
Returns the current edge.
virtual double getEdgePos () const
Return the position on the edge.
ConstMSEdgeVector getEdges (int next) const
Return the edges of the nth next stage.
const MSEdge * getFromEdge () const
Returns the departure edge.
const std::string & getID () const
returns the id of the transportable
const MSEdge & getNextDestination () const
Returns the destination after the current destination.
int getNumRemainingStages () const
Return the number of remaining stages (including the current)
int getNumStages () const
Return the total number stages in this persons plan.
const SUMOVehicleParameter & getParameter () const
virtual Position getPosition () const
Return the Network coordinate of the transportable.
virtual double getSpeed () const
the current speed of the transportable
StageType getStageType (int next) const
the stage type for the nth next stage
SUMOVehicle * getVehicle () const
The vehicle associated with this transportable.
const MSVehicleType & getVehicleType () const
virtual double getWaitingSeconds () const
the time this transportable spent waiting in seconds
bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
MSContainer (const SUMOVehicleParameter *pars, const MSVehicleType *vtype, MSTransportablePlan *plan)
constructor
virtual bool proceed (MSNet *net, SUMOTime time)
void removeStage (int next)
removes the nth next stage
void replaceVehicleType (MSVehicleType *type)
replace myVType
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setDeparted (SUMOTime now)
logs depart time of the current stage
void setSpeed (double speed)
sets the walking speed (ignored in other stages)
virtual void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
virtual ~MSContainer ()
destructor
Protected Attributes
const SUMOVehicleParameter * myParameter
the plan of the transportable
MSTransportablePlan * myPlan
the plan of the transportable
MSTransportablePlan::iterator myStep
the iterator over the route
const MSVehicleType * myVType
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
bool myWriteEvents
Whether events shall be written.
Static Protected Attributes
static const double ROADSIDE_OFFSET
the offset for computing positions when standing at an edge
Private Member Functions
MSContainer (const MSContainer &)
Invalidated copy constructor.
MSContainer & operator= (const MSContainer &)
Invalidated assignment operator.
Detailed Description
The class holds a simulated container together with its movement stages
Definition at line 68 of file MSContainer.h.
Member Typedef Documentation
typedef std::vector<MSTransportable::Stage*> MSTransportable::MSTransportablePlan inherited
the structure holding the plan of a transportable
Definition at line 377 of file MSTransportable.h.
Member Enumeration Documentation
enum MSTransportable::StageType inherited
Enumerator
WAITING_FOR_DEPART
WAITING
MOVING_WITHOUT_VEHICLE
DRIVING
Definition at line 62 of file MSTransportable.h.
Constructor & Destructor Documentation
MSContainer::MSContainer (const SUMOVehicleParameter * pars, const MSVehicleType * vtype, MSTransportablePlan * plan)
constructor
Definition at line 237 of file MSContainer.cpp.
MSContainer::~MSContainer () virtual
destructor
Definition at line 242 of file MSContainer.cpp.
MSContainer::MSContainer (const MSContainer &) private
Invalidated copy constructor.
Member Function Documentation
void MSTransportable::appendStage (Stage * stage) inherited
Appends the given stage to the current plan.
Definition at line 412 of file MSTransportable.cpp.
References MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by MSTransportable::getVehicle(), TraCIServerAPI_Person::processSet(), and MSTransportable::removeStage().
double MSTransportable::getAngle () const virtual inherited
return the current angle of the transportable
Reimplemented in GUIContainer.
Definition at line 386 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIPerson::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsTriangle(), GUIContainer::getAngle(), GUIPerson::getNaviDegree(), TraCIServerAPI_Person::processGet(), GUIPerson::setFunctionalColor(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
const MSEdge* MSTransportable::getArrivalEdge () const inline inherited
returns the final arrival edge
Definition at line 520 of file MSTransportable.h.
References MSTransportable::myPlan, and MSTransportable::replaceVehicleType().
Referenced by TraCIServerAPI_Person::processSet().
double MSTransportable::getArrivalPos () const inline inherited
returns the final arrival pos
Definition at line 515 of file MSTransportable.h.
References MSTransportable::myPlan.
Referenced by TraCIServerAPI_Person::processSet().
MSTransportable::Stage* MSTransportable::getCurrentStage () const inline inherited
Return the current stage.
Definition at line 459 of file MSTransportable.h.
References MSTransportable::myStep.
Referenced by GUIPerson::drawAction_drawWalkingareaPath(), GUIPerson::drawGLAdditional(), and MSEdge::transportable_by_position_sorter::operator()().
std::string MSTransportable::getCurrentStageDescription () const inline inherited
Returns the current stage description as a string.
Definition at line 454 of file MSTransportable.h.
Referenced by GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), and MSXMLRawOut::writeTransportable().
StageType MSTransportable::getCurrentStageType () const inline inherited
the current stage type of the transportable
Definition at line 442 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPerson::drawGLAdditional(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), MSPerson::getNextEdgePtr(), and GUIContainer::getPosition().
SUMOTime MSTransportable::getDesiredDepart () const inherited
Returns the desired departure time.
Definition at line 366 of file MSTransportable.cpp.
References SUMOVehicleParameter::depart, and MSTransportable::myParameter.
Referenced by MSTransportable::getVehicleType(), routeOutput(), MSPerson::routeOutput(), tripInfoOutput(), and MSPerson::tripInfoOutput().
const MSEdge& MSTransportable::getDestination () const inline inherited
Returns the current destination.
Definition at line 407 of file MSTransportable.h.
Referenced by GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), MSDevice_Transportable::notifyLeave(), and MSDevice_Transportable::notifyMove().
const MSEdge* MSTransportable::getEdge () const inline inherited
Returns the current edge.
Definition at line 417 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), GUIContainer::getPosition(), TraCIServerAPI_Person::processGet(), and MSTransportable::removeStage().
double MSTransportable::getEdgePos () const virtual inherited
Return the position on the edge.
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 376 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIContainer::getEdgePos(), GUIPerson::getEdgePos(), TraCIServerAPI_Person::processGet(), MSTransportable::removeStage(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
ConstMSEdgeVector MSTransportable::getEdges (int next) const inline inherited
Return the edges of the nth next stage.
Definition at line 464 of file MSTransportable.h.
References MSTransportable::Stage::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), MSTransportable::myPlan, MSTransportable::myStep, MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
Referenced by TraCIServerAPI_Person::processGet().
const MSEdge* MSTransportable::getFromEdge () const inline inherited
Returns the departure edge.
Definition at line 422 of file MSTransportable.h.
References MSTransportable::Stage::getAngle(), MSTransportable::Stage::getEdgePos(), MSTransportable::Stage::getPosition(), MSTransportable::Stage::getSpeed(), and MSTransportable::getWaitingSeconds().
Referenced by GUIContainer::getParameterWindow(), and GUIPerson::getParameterWindow().
const std::string & MSTransportable::getID () const inherited
returns the id of the transportable
Definition at line 361 of file MSTransportable.cpp.
References SUMOVehicleParameter::id, and MSTransportable::myParameter.
Referenced by MSTransportableControl::abortWaiting(), MSVehicle::addContainer(), MSVehicle::addPerson(), MSPerson::MSPersonStage_Walking::beginEventOutput(), MSContainer::MSContainerStage_Tranship::beginEventOutput(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Walking::endEventOutput(), MSContainer::MSContainerStage_Tranship::endEventOutput(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSTransportableControl::erase(), MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), TraCIServerAPI_Person::getSingularType(), MSPedestrianPushButton::isActiveForEdge(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), MSDevice_Transportable::notifyLeave(), MSPModel_Striping::by_xpos_sorter::operator()(), MSEdge::transportable_by_position_sorter::operator()(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSPModel_Striping::PState::PState(), MSContainer::MSContainerStage_Driving::routeOutput(), routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), MSPerson::routeOutput(), tripInfoOutput(), MSPerson::tripInfoOutput(), MSPModel_Striping::PState::walk(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
const MSEdge& MSTransportable::getNextDestination () const inline inherited
Returns the destination after the current destination.
Definition at line 412 of file MSTransportable.h.
References MSTransportable::myStep.
int MSTransportable::getNumRemainingStages () const inherited
Return the number of remaining stages (including the current)
Definition at line 402 of file MSTransportable.cpp.
References MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by MSTransportable::getEdges(), TraCIServerAPI_Person::processGet(), and TraCIServerAPI_Person::processSet().
int MSTransportable::getNumStages () const inherited
Return the total number stages in this persons plan.
Definition at line 407 of file MSTransportable.cpp.
References MSTransportable::myPlan.
Referenced by MSTransportable::getEdges(), and TraCIServerAPI_Person::processGet().
const SUMOVehicleParameter& MSTransportable::getParameter () const inline inherited
Definition at line 392 of file MSTransportable.h.
References MSTransportable::myParameter.
Referenced by MSTransportableControl::add(), GUIPerson::getParameterWindow(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Person::processSet(), GUIContainer::setFunctionalColor(), and GUIPerson::setFunctionalColor().
Position MSTransportable::getPosition () const virtual inherited
Return the Network coordinate of the transportable.
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 381 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by TraCIServerAPI_Person::getPosition(), GUIContainer::getPosition(), GUIPerson::getPosition(), TraCIServerAPI_Person::processGet(), and MSFCDExport::writeTransportable().
double MSTransportable::getSpeed () const virtual inherited
the current speed of the transportable
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 396 of file MSTransportable.cpp.
Referenced by GUIContainer::getSpeed(), GUIPerson::getSpeed(), TraCIServerAPI_Person::processGet(), and MSFCDExport::writeTransportable().
StageType MSTransportable::getStageType (int next) const inline inherited
the stage type for the nth next stage
Definition at line 447 of file MSTransportable.h.
References MSTransportable::Stage::getStageType(), MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by TraCIServerAPI_Person::processGet().
SUMOVehicle* MSTransportable::getVehicle () const inline inherited
The vehicle associated with this transportable.
Definition at line 501 of file MSTransportable.h.
References MSTransportable::appendStage(), MSTransportable::removeStage(), and MSTransportable::Stage::setSpeed().
Referenced by TraCIServerAPI_Person::processGet().
const MSVehicleType& MSTransportable::getVehicleType () const inline inherited
Definition at line 396 of file MSTransportable.h.
References MSTransportable::getDesiredDepart(), MSTransportable::myVType, and MSTransportable::Stage::setDeparted().
Referenced by MSStoppingPlace::addTransportable(), GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIContainer::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsTriangle(), GUIPerson::getCenteringBoundary(), MSPModel_Striping::PState::getImpatience(), MSPModel_Striping::PState::getLength(), MSPModel_Striping::PState::getMinGap(), MSPModel_Striping::getNextLaneObstacles(), TraCIServerAPI_Person::getSingularType(), MSPModel_Striping::PState::otherStripe(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Person::processSet(), MSStoppingPlace::removeTransportable(), GUIContainer::setFunctionalColor(), and GUIPerson::setFunctionalColor().
double MSTransportable::getWaitingSeconds () const virtual inherited
the time this transportable spent waiting in seconds
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 391 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and STEPS2TIME.
Referenced by MSTransportable::getFromEdge(), GUIContainer::getWaitingSeconds(), GUIPerson::getWaitingSeconds(), MSPedestrianPushButton::isActiveForEdge(), and TraCIServerAPI_Person::processGet().
bool MSTransportable::isWaiting4Vehicle () const inline inherited
Whether the transportable waits for a vehicle.
Definition at line 496 of file MSTransportable.h.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), GUIContainer::getColorValue(), and GUIPerson::getColorValue().
bool MSTransportable::isWaitingFor (const std::string & line) const inline inherited
Whether the transportable waits for a vehicle of the line specified.
Definition at line 491 of file MSTransportable.h.
MSContainer& MSContainer::operator= (const MSContainer &) private
Invalidated assignment operator.
bool MSContainer::proceed (MSNet * net, SUMOTime time) virtual
Implements MSTransportable.
Definition at line 247 of file MSContainer.cpp.
References MSTransportable::Stage::getEdge(), MSTransportable::myPlan, MSTransportable::myStep, MSEdge::removeContainer(), and MSTransportable::Stage::setArrived().
void MSTransportable::removeStage (int next) inherited
removes the nth next stage
Definition at line 421 of file MSTransportable.cpp.
References MSTransportable::appendStage(), MSTransportable::getEdge(), MSTransportable::getEdgePos(), MSNet::getInstance(), MSTransportable::myPlan, MSTransportable::myStep, and MSTransportable::proceed().
Referenced by MSTransportable::getVehicle(), and TraCIServerAPI_Person::processSet().
void MSTransportable::replaceVehicleType (MSVehicleType * type) inherited
replace myVType
Definition at line 450 of file MSTransportable.cpp.
References MSTransportable::myVType.
Referenced by MSTransportable::getArrivalEdge(), TraCIServerAPI_Person::getSingularType(), and TraCIServerAPI_Person::processSet().
void MSContainer::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 272 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSNet::getInstance(), OutputDevice::lf(), MSTransportable::myPlan, MSTransportable::myStep, OutputDevice::openTag(), SUMO_ATTR_DEPART, SUMO_ATTR_ID, SUMO_TAG_CONTAINER, time2string(), and OutputDevice::writeAttr().
void MSTransportable::setDeparted (SUMOTime now) inherited
logs depart time of the current stage
Definition at line 371 of file MSTransportable.cpp.
void MSTransportable::setSpeed (double speed) inherited
sets the walking speed (ignored in other stages)
Definition at line 442 of file MSTransportable.cpp.
References MSTransportable::myPlan.
Referenced by TraCIServerAPI_Person::processSet().
void MSContainer::tripInfoOutput (OutputDevice & os) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 262 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::myPlan, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Field Documentation
const SUMOVehicleParameter* MSTransportable::myParameter protected inherited
the plan of the transportable
Definition at line 532 of file MSTransportable.h.
Referenced by MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::getParameter(), and MSTransportable::~MSTransportable().
MSTransportablePlan* MSTransportable::myPlan protected inherited
the plan of the transportable
Definition at line 542 of file MSTransportable.h.
Referenced by MSTransportable::appendStage(), MSTransportable::getArrivalEdge(), MSTransportable::getArrivalPos(), MSTransportable::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), MSTransportable::getStageType(), MSTransportable::MSTransportable(), proceed(), MSPerson::proceed(), MSTransportable::removeStage(), routeOutput(), MSPerson::routeOutput(), MSTransportable::setSpeed(), tripInfoOutput(), MSPerson::tripInfoOutput(), and MSTransportable::~MSTransportable().
MSTransportablePlan::iterator MSTransportable::myStep protected inherited
the iterator over the route
Definition at line 545 of file MSTransportable.h.
Referenced by MSTransportable::appendStage(), MSTransportable::getCurrentStage(), MSTransportable::getEdges(), MSTransportable::getNextDestination(), MSTransportable::getNumRemainingStages(), MSTransportable::getStageType(), MSTransportable::MSTransportable(), proceed(), MSPerson::proceed(), MSTransportable::removeStage(), routeOutput(), and MSPerson::routeOutput().
const MSVehicleType* MSTransportable::myVType protected inherited
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
Definition at line 536 of file MSTransportable.h.
Referenced by GUIPerson::getTypeParameterWindow(), MSTransportable::getVehicleType(), and MSTransportable::replaceVehicleType().
bool MSTransportable::myWriteEvents protected inherited
Whether events shall be written.
Definition at line 539 of file MSTransportable.h.
const double MSTransportable::ROADSIDE_OFFSET static protected inherited
the offset for computing positions when standing at an edge
Definition at line 529 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getPosition(), and MSTransportable::Stage_Driving::getPosition().
The documentation for this class was generated from the following files:
MSContainer.h
MSContainer.cpp