SUMO - Simulation of Urban MObility: guisim_main.cpp File Reference
guisim_main.cpp File Reference
#include <config.h>
#include <version.h>
#include <ctime>
#include <signal.h>
#include <iostream>
#include <microsim/MSFrame.h>
#include <microsim/MSNet.h>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/FileHelpers.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/SystemFrame.h>
#include <utils/xml/XMLSubSys.h>
#include <gui/GUIApplicationWindow.h>
#include <utils/gui/windows/GUIAppEnum.h>
#include <utils/gui/settings/GUICompleteSchemeStorage.h>
#include <traci-server/TraCIServer.h>
Functions
int main (int argc, char **argv)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Felix Brack
Date
Tue, 20 Nov 2001
Version
Id
guisim_main.cpp 23637 2017-03-23 20:40:16Z behrisch
Definition in file guisim_main.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 64 of file guisim_main.cpp.
References MsgHandler::assignLock(), SystemFrame::close(), TraCIServer::close(), GUIApplicationWindow::dependentBuild(), MSFrame::fillOptions(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), gSchemeStorage, MsgHandler::inform(), XMLSubSys::init(), GUICompleteSchemeStorage::init(), GUIApplicationWindow::loadOnStartup(), MID_QUIT, OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), VERSION_STRING, and WRITE_ERROR.