SUMO - Simulation of Urban MObility: GNEChange_Junction Class Reference
GNEChange_Junction Class Reference
#include <GNEChange_Junction.h>
Public Member Functions
GNEChange_Junction (GNEJunction *junction, bool forward)
Constructor for creating/deleting a junction.
virtual FXuint size () const
return actual size
~GNEChange_Junction ()
Destructor.
inherited from GNEChange
get undo Name
FXString undoName () const
return undoName
FXString redoName () const
get Redo name
void undo ()
undo action
void redo ()
redo action
Protected Attributes
bool myForward
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
GNENet * myNet
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Private Attributes
GNEJunction * myJunction
full information regarding the junction that is to be created/deleted
Detailed Description
A network change in which a single junction is created or deleted
Definition at line 50 of file GNEChange_Junction.h.
Constructor & Destructor Documentation
GNEChange_Junction::GNEChange_Junction (GNEJunction * junction, bool forward)
Constructor for creating/deleting a junction.
constructor for creating a junction
Parameters
[in] junction The junction to be created/deleted
[in] forward Whether to create/delete (true/false)
Definition at line 49 of file GNEChange_Junction.cpp.
GNEChange_Junction::~GNEChange_Junction ()
Destructor.
Definition at line 57 of file GNEChange_Junction.cpp.
References GNEReferenceCounter::decRef(), GNEAttributeCarrier::getID(), GNENetElement::getNet(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNEViewNet::isTestingModeEnabled(), myJunction, toString(), GNEReferenceCounter::unreferenced(), and WRITE_WARNING.
Member Function Documentation
void GNEChange_Junction::redo () virtual
redo action
Reimplemented from GNEChange.
Definition at line 91 of file GNEChange_Junction.cpp.
References GNENet::deleteSingleJunction(), GNEAttributeCarrier::getID(), GNENetElement::getNet(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNENet::insertJunction(), GNEViewNet::isTestingModeEnabled(), GNEChange::myForward, myJunction, GNEChange::myNet, toString(), and WRITE_WARNING.
FXString GNEChange_Junction::redoName () const virtual
get Redo name
Reimplemented from GNEChange.
Definition at line 121 of file GNEChange_Junction.cpp.
References GNEChange::myForward, SUMO_TAG_JUNCTION, and toString().
FXuint GNEChange::size () const virtual inherited
return actual size
Definition at line 53 of file GNEChange.cpp.
void GNEChange_Junction::undo () virtual
undo action
Reimplemented from GNEChange.
Definition at line 71 of file GNEChange_Junction.cpp.
References GNENet::deleteSingleJunction(), GNEAttributeCarrier::getID(), GNENetElement::getNet(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GNENet::insertJunction(), GNEViewNet::isTestingModeEnabled(), GNEChange::myForward, myJunction, GNEChange::myNet, toString(), and WRITE_WARNING.
FXString GNEChange_Junction::undoName () const virtual
return undoName
Reimplemented from GNEChange.
Definition at line 111 of file GNEChange_Junction.cpp.
References GNEChange::myForward, SUMO_TAG_JUNCTION, and toString().
Field Documentation
bool GNEChange::myForward protected inherited
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
Definition at line 87 of file GNEChange.h.
Referenced by redo(), GNEChange_Selection::redo(), GNEChange_TLS::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), redoName(), GNEChange_Selection::redoName(), GNEChange_TLS::redoName(), GNEChange_Connection::redoName(), GNEChange_Lane::redoName(), GNEChange_Additional::redoName(), GNEChange_Edge::redoName(), GNEChange_Crossing::redoName(), undo(), GNEChange_Selection::undo(), GNEChange_TLS::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), undoName(), GNEChange_Selection::undoName(), GNEChange_TLS::undoName(), GNEChange_Connection::undoName(), GNEChange_Lane::undoName(), GNEChange_Additional::undoName(), GNEChange_Edge::undoName(), and GNEChange_Crossing::undoName().
GNEJunction* GNEChange_Junction::myJunction private
full information regarding the junction that is to be created/deleted
Note
we assume shared responsibility for the pointer (via reference counting)
Definition at line 83 of file GNEChange_Junction.h.
Referenced by redo(), undo(), and ~GNEChange_Junction().
GNENet* GNEChange::myNet protected inherited
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Definition at line 82 of file GNEChange.h.
Referenced by redo(), GNEChange_Selection::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), undo(), GNEChange_Selection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Lane::~GNEChange_Lane(), and GNEChange_TLS::~GNEChange_TLS().
The documentation for this class was generated from the following files:
GNEChange_Junction.h
GNEChange_Junction.cpp