SUMO - Simulation of Urban MObility: MSLinkContHelper Class Reference
MSLinkContHelper Class Reference
#include <MSLinkCont.h>
Static Public Member Functions
static MSLink * getConnectingLink (const MSLane &from, const MSLane &to)
Returns the link connecting both lanes Both lanes have to be non-internal; 0 may be returned if no connection exists.
static const MSEdge * getInternalFollowingEdge (const MSLane *fromLane, const MSEdge *followerAfterInternal)
Returns the internal lane that must be passed in order to get to the desired edge Returns 0 if no such edge exists.
static const MSLane * getInternalFollowingLane (const MSLane *fromLane, const MSLane *followerAfterInternal)
Detailed Description
Some helping functions for dealing with links.
Definition at line 59 of file MSLinkCont.h.
Member Function Documentation
MSLink * MSLinkContHelper::getConnectingLink (const MSLane & from, const MSLane & to) static
Returns the link connecting both lanes Both lanes have to be non-internal; 0 may be returned if no connection exists.
Definition at line 78 of file MSLinkCont.cpp.
References MSLink::getLane(), MSLane::getLinkCont(), and MSLink::getViaLaneOrLane().
Referenced by MSEdge::allowsLaneChanging(), NLDetectorBuilder::buildE2Detector(), MSLaneChanger::changeOpposite(), MSLink::computeParallelLink(), MSPModel_Striping::connectedDirection(), MSLCM_LC2013::distanceAlongNextRoundabout(), GUILane::drawGL(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawTLSLinkNo(), MSLane::getIncomingLinkState(), MSPModel_Striping::getNextLane(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSPModel_Striping::initWalkingAreaPaths(), MSLink::lastWasContMajor(), MSVehicle::nextLinkPriority(), and MSAbstractLaneChangeModel::updateShadowLane().
const MSEdge * MSLinkContHelper::getInternalFollowingEdge (const MSLane * fromLane, const MSEdge * followerAfterInternal) static
Returns the internal lane that must be passed in order to get to the desired edge Returns 0 if no such edge exists.
Definition at line 40 of file MSLinkCont.cpp.
References MSLane::getEdge(), MSLink::getLane(), MSLane::getLinkCont(), and MSLink::getViaLane().
const MSLane * MSLinkContHelper::getInternalFollowingLane (const MSLane * fromLane, const MSLane * followerAfterInternal) static
Definition at line 59 of file MSLinkCont.cpp.
References MSLink::getLane(), MSLane::getLinkCont(), and MSLink::getViaLane().
Referenced by MSPModel_Striping::getNextLane().
The documentation for this class was generated from the following files:
MSLinkCont.h
MSLinkCont.cpp