SUMO - Simulation of Urban MObility: MSLCM_SL2015 Class Reference
MSLCM_SL2015 Class Reference
A lane change model developed by J. Erdmann.
#include <MSLCM_SL2015.h>
Public Types
enum MyLCAEnum {
LCA_MNone = 0, LCA_AMBLOCKINGLEADER = 1 << 16, LCA_AMBLOCKINGFOLLOWER = 1 << 17, LCA_MRIGHT = 1 << 18,
LCA_MLEFT = 1 << 19, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE = 1 << 21, LCA_CHANGE_TO_HELP = 1 << 23, LCA_AMBACKBLOCKER = 1 << 26,
LCA_AMBACKBLOCKER_STANDING = 1 << 27
}
Public Member Functions
double _patchSpeed (const double min, const double wanted, const double max, const MSCFModel &cfModel)
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
void changed ()
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void cleanupShadowLane ()
bool debugVehicle () const
whether the current vehicles shall be debugged
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
double getAngleOffset () const
return the angle offset during a continuous change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
double getLateralSpeed () const
return the lateral speed of the current lane change maneuver
int getOwnState () const
std::string getParameter (const std::string &key) const
try to retrieve the given parameter from this device. Throw exception for unsupported key
const std::pair< int, int > & getSavedState (const int dir) const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< double > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
void * inform (void *info, MSVehicle *sender)
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
MSLCM_SL2015 (MSVehicle &v)
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
double patchSpeed (const double min, const double wanted, const double max, const MSCFModel &cfModel)
Called to adapt the speed in order to allow a lane change.
void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
void saveState (const int dir, const int stateWithoutTraCI, const int state)
void setNoShadowPartialOccupator (MSLane *lane)
void setOwnState (const int state)
void setParameter (const std::string &key, const std::string &value)
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
bool updateCompletion ()
void updateShadowLane ()
int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, double > &leader, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset (this is a wrapper around wantsChangeSublane). This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
int wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, double &latDist, int &blocked)
Called to examine whether the vehicle wants to change with the given laneOffset (using the sublane model) This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual ~MSLCM_SL2015 ()
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
Protected Types
typedef std::pair< double, int > Info
information regarding save velocity (unused) and state flags of the ego vehicle
Protected Member Functions
int _wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, double &latDist, int &blocked)
helper function for doing the actual work
bool amBlockingFollower ()
bool amBlockingFollowerNB ()
bool amBlockingFollowerPlusNB ()
bool amBlockingLeader ()
bool cancelRequest (int state)
whether the influencer cancels the given request
int checkBlocking (const MSLane &neighLane, double &latDist, int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, std::vector< CLeaderDist > *collectLeadBlockers=0, std::vector< CLeaderDist > *collectFollowBlockers=0, bool keepLatGapManeuver=false)
restrict latDist to permissible speed and determine blocking state depending on that distance
int checkBlockingVehicles (const MSVehicle *ego, const MSLeaderDistanceInfo &vehicles, double latDist, double foeOffset, bool leaders, LaneChangeAction blockType, std::vector< CLeaderDist > *collectBlockers=0) const
check whether any of the vehicles overlaps with ego
int checkStrategicChange (int ret, int laneOffset, const std::vector< MSVehicle::LaneQ > &preb, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &neighLeaders, int currIdx, int bestLaneOffset, bool changeToBest, int lcaCounter, double currentDist, double neighDist, double laDist, int roundaboutEdgesAhead, double latLaneDist, double &latDist)
compute strategic lane change actions
int computeSublaneShift (const MSEdge *prevEdge, const MSEdge *curEdge)
compute shift so that prevSublane + shift = newSublane
virtual bool congested (const MSVehicle *const neighLeader)
bool currentDistAllows (double dist, int laneOffset, double lookForwardDist)
bool currentDistDisallows (double dist, int laneOffset, double lookForwardDist)
StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
void informFollower (int blocked, int dir, const CLeaderDist &neighFollow, double remainingSeconds, double plannedSpeed)
decide whether we will try cut in before the follower or allow to be overtaken
void informFollowers (int blocked, int dir, const std::vector< CLeaderDist > &blockers, double remainingSeconds, double plannedSpeed)
call informFollower for multiple followers
double informLeader (int blocked, int dir, const CLeaderDist &neighLead, double remainingSeconds)
double informLeaders (int blocked, int dir, const std::vector< CLeaderDist > &blockers, double remainingSeconds)
void initLastLaneChangeOffset (int dir)
int keepLatGap (int state, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, int laneOffset, double &latDist, int &blocked)
check whether lateral gap requirements are met override the current maneuver if necessary
void msg (const CLeaderDist &cld, double speed, int state)
send a speed recommendation to the given vehicle
virtual bool predInteraction (const std::pair< MSVehicle *, double > &leader)
void saveBlockerLength (const MSVehicle *blocker, int lcaCounter)
save space for vehicles which need to counter-lane-change
void saveBlockerLength (double length)
reserve space at the end of the lane to avoid dead locks
int slowDownForBlocked (MSVehicle **blocked, int state)
compute useful slowdowns for blocked vehicles
void updateExpectedSublaneSpeeds (const MSLeaderInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
void updateGaps (const MSLeaderDistanceInfo &others, double foeOffset, double oldCenter, double gapFactor, double &surplusGapRight, double &surplusGapLeft, bool saveMinGap=false, double netOverlap=0)
check remaining lateral gaps for the given foe vehicles and optionally update minimum lateral gaps
Static Protected Member Functions
static LaneChangeAction getLCA (int state, double latDist)
compute lane change action from desired lateral distance
static CLeaderDist getLongest (const MSLeaderDistanceInfo &ldi)
get the longest vehicle in the given info
static CLeaderDist getSlowest (const MSLeaderDistanceInfo &ldi)
get the slowest vehicle in the given info
static bool overlap (double right, double left, double right2, double left2)
return whether the given intervals overlap
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
bool myCanChangeFully
whether the current lane changing meneuver can be finished in a single step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
bool myDontBrake
flag to prevent speed adaptation by slowing down
std::vector< double > myExpectedSublaneSpeeds
expected travel speeds on all sublanes on the current edge(!)
double myKeepRightProbability
double myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
const MSEdge * myLastEdge
expected travel speeds on all sublanes on the current edge(!)
double myLastLateralGapLeft
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
double myLastLateralGapRight
double myLateralspeed
The lateral offset during a continuous LaneChangeManeuver.
double myLeadingBlockerLength
double myLeftSpace
double myLookAheadSpeed
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
double myOrigLatDist
the complete lateral distance the vehicle wants to travel to finish its maneuver
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
int myPreviousState
lane changing state from the previous simulation step
std::map< int, std::pair< int, int > > mySavedStates
std::vector< MSLane * > myShadowFurtherLanes
std::vector< double > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
double mySpeedGainProbabilityLeft
a value for tracking the probability that a change to the left is beneficial
double mySpeedGainProbabilityRight
a value for tracking the probability that a change to the right is beneficial
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
std::vector< double > myVSafes
speed adaptation requests by ego and surrounding vehicles
user configurable model parameters (can be changed via TraCI)
double myStrategicParam
double myCooperativeParam
double mySpeedGainParam
double myKeepRightParam
double mySublaneParam
double myPushy
double myAssertive
derived parameters
const double myChangeProbThresholdRight
const double myChangeProbThresholdLeft
const double mySpeedLossProbThreshold
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCOutput
whether to record lane-changing
static const double NO_LATERAL_NEIGHBOR
Detailed Description
A lane change model developed by J. Erdmann.
Definition at line 44 of file MSLCM_SL2015.h.
Member Typedef Documentation
typedef std::pair<double, int> MSLCM_SL2015::Info protected
information regarding save velocity (unused) and state flags of the ego vehicle
Definition at line 209 of file MSLCM_SL2015.h.
Member Enumeration Documentation
enum MSLCM_SL2015::MyLCAEnum
Enumerator
LCA_MNone
LCA_AMBLOCKINGLEADER
LCA_AMBLOCKINGFOLLOWER
LCA_MRIGHT
LCA_MLEFT
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE
LCA_CHANGE_TO_HELP
LCA_AMBACKBLOCKER
LCA_AMBACKBLOCKER_STANDING
Definition at line 47 of file MSLCM_SL2015.h.
Constructor & Destructor Documentation
MSLCM_SL2015::MSLCM_SL2015 (MSVehicle & v)
Definition at line 104 of file MSLCM_SL2015.cpp.
MSLCM_SL2015::~MSLCM_SL2015 () virtual
Definition at line 128 of file MSLCM_SL2015.cpp.
References changed().
Member Function Documentation
double MSLCM_SL2015::_patchSpeed (const double min, const double wanted, const double max, const MSCFModel & cfModel)
helper function which contains the actual logic
Definition at line 242 of file MSLCM_SL2015.cpp.
References gDebugFlag2, MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getMinGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_COOPERATIVE, LCA_STRATEGIC, LCA_WANTS_LANECHANGE, MAX2(), MIN2(), myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, NUMERICAL_EPS, STEPS2TIME, and MSCFModel::stopSpeed().
Referenced by patchSpeed().
int MSLCM_SL2015::_wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, double & latDist, int & blocked) protected
helper function for doing the actual work
determine the leftmost and rightmost sublanes currently occupied
Definition at line 806 of file MSLCM_SL2015.cpp.
References abs, amBlockingFollowerPlusNB(), ARRIVAL_POSLAT_CENTER, ARRIVAL_POSLAT_DEFAULT, ARRIVAL_POSLAT_GIVEN, ARRIVAL_POSLAT_LEFT, ARRIVAL_POSLAT_RIGHT, ARRIVALPOS_LAT_THRESHOLD, SUMOVehicleParameter::arrivalPosLat, SUMOVehicleParameter::arrivalPosLatProcedure, MSVehicle::LaneQ::bestContinuations, MSCFModel::brakeGap(), MSAbstractLaneChangeModel::cancelRequest(), MSVehicle::Influencer::changeRequestRemainingSeconds(), checkBlocking(), checkStrategicChange(), currentDistAllows(), DELTA_T, MSEdge::EDGEFUNCTION_INTERNAL, GAIN_PERCEPTION_THRESHOLD, gDebugFlag2, MSBaseVehicle::getArrivalPos(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSBaseVehicle::getID(), Named::getIDSecure(), MSLane::getIndex(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getLane(), MSRoute::getLastEdge(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), getLongest(), MSBaseVehicle::getParameter(), MSVehicle::getPositionOnLane(), MSVehicleType::getPreferredLateralAlignment(), MSEdge::getPurpose(), MSLane::getRightmostSublane(), MSVehicle::getRightSideOnEdge(), MSLane::getRightSideOnEdge(), MSBaseVehicle::getRoute(), MSCFModel::getSecureGap(), getSlowest(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSEdge::getSubLaneSides(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSEdge::getWidth(), MSLeaderInfo::hasStoppedVehicle(), informFollowers(), informLeaders(), KEEP_RIGHT_ACCEPTANCE, KEEP_RIGHT_TIME, LATALIGN_ARBITRARY, LATALIGN_CENTER, LATALIGN_COMPACT, LATALIGN_LEFT, LATALIGN_NICE, LATALIGN_RIGHT, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_LEFT, LCA_MLEFT, LCA_MRIGHT, LCA_NONE, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_SUBLANE, LCA_TRACI, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_AHEAD_MIN_SPEED, LOOK_AHEAD_SPEED_MEMORY, LOOK_FORWARD_LEFT, LOOK_FORWARD_RIGHT, max, MAX2(), MIN2(), myCanChangeFully, myChangeProbThresholdLeft, myChangeProbThresholdRight, myCooperativeParam, myExpectedSublaneSpeeds, myKeepRightParam, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, myOrigLatDist, MSAbstractLaneChangeModel::myOwnState, myPreviousState, mySpeedGainProbabilityLeft, mySpeedGainProbabilityRight, mySpeedLossProbThreshold, myStrategicParam, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, RELGAIN_NORMALIZATION_MIN_SPEED, ROUNDABOUT_DIST_BONUS, saveBlockerLength(), SIMTIME, slowDownForBlocked(), SPEED_GAIN_MIN_SECONDS, STEPS2TIME, SUMO_const_laneWidth, toString(), MSLeaderDistanceInfo::toString(), TS, and URGENCY.
Referenced by wantsChange(), and wantsChangeSublane().
bool MSAbstractLaneChangeModel::alreadyChanged () const inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 338 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyChanged.
Referenced by MSLaneChanger::change().
bool MSLCM_SL2015::amBlockingFollower () inline protected
Definition at line 192 of file MSLCM_SL2015.h.
References LCA_AMBLOCKINGFOLLOWER, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_SL2015::amBlockingFollowerNB () inline protected
Definition at line 195 of file MSLCM_SL2015.h.
References LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_SL2015::amBlockingFollowerPlusNB () inline protected
Definition at line 198 of file MSLCM_SL2015.h.
References LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
Referenced by _wantsChangeSublane().
bool MSLCM_SL2015::amBlockingLeader () inline protected
Definition at line 189 of file MSLCM_SL2015.h.
References LCA_AMBLOCKINGLEADER, and MSAbstractLaneChangeModel::myOwnState.
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static inherited
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 63 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::sameDirection().
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected inherited
whether the influencer cancels the given request
Definition at line 257 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLCM_LC2013::_wantsChange(), _wantsChangeSublane(), and MSAbstractLaneChangeModel::setParameter().
void MSLCM_SL2015::changed () virtual
Implements MSAbstractLaneChangeModel.
Definition at line 776 of file MSLCM_SL2015.cpp.
References DEBUG_COND, MSVehicle::getBestLaneOffset(), MSBaseVehicle::getID(), LOOK_AHEAD_MIN_SPEED, myCanChangeFully, myDontBrake, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbabilityLeft, mySpeedGainProbabilityRight, MSAbstractLaneChangeModel::myVehicle, myVSafes, and SIMTIME.
Referenced by ~MSLCM_SL2015().
void MSAbstractLaneChangeModel::changedToOpposite () inherited
called when a vehicle changes between lanes in opposite directions
Definition at line 364 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myAlreadyChanged, and MSAbstractLaneChangeModel::myAmOpposite.
Referenced by MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::executeMove(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
int MSLCM_SL2015::checkBlocking (const MSLane & neighLane, double & latDist, int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, std::vector< CLeaderDist > * collectLeadBlockers = 0, std::vector< CLeaderDist > * collectFollowBlockers = 0, bool keepLatGapManeuver = false) protected
restrict latDist to permissible speed and determine blocking state depending on that distance
Definition at line 1624 of file MSLCM_SL2015.cpp.
References checkBlockingVehicles(), gDebugFlag2, MSVehicle::getCenterOnEdge(), MSLane::getEdge(), MSVehicle::getLane(), MSVehicleType::getMaxSpeedLat(), MSLane::getRightSideOnEdge(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSEdge::getWidth(), LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_BLOCKED_BY_LEFT_FOLLOWER, LCA_BLOCKED_BY_LEFT_LEADER, LCA_BLOCKED_BY_RIGHT_FOLLOWER, LCA_BLOCKED_BY_RIGHT_LEADER, LCA_BLOCKED_LEFT, LCA_BLOCKED_RIGHT, LCA_OVERLAPPING, MAX2(), MIN2(), myCanChangeFully, myOrigLatDist, myPushy, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, SPEED2DIST, and updateGaps().
Referenced by _wantsChangeSublane(), and keepLatGap().
int MSLCM_SL2015::checkBlockingVehicles (const MSVehicle * ego, const MSLeaderDistanceInfo & vehicles, double latDist, double foeOffset, bool leaders, LaneChangeAction blockType, std::vector< CLeaderDist > * collectBlockers = 0) const protected
check whether any of the vehicles overlaps with ego
Definition at line 1723 of file MSLCM_SL2015.cpp.
References MSCFModel::brakeGap(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSCFModel::getHeadwayTime(), MSBaseVehicle::getImpatience(), MSCFModel::getMaxDecel(), MSVehicle::getRightSideOnEdge(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLeaderInfo::getSublaneBorders(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), LCA_OVERLAPPING, MAX2(), MIN2(), myAssertive, MSLeaderInfo::numSublanes(), overlap(), and SUMO_const_haltingSpeed.
Referenced by checkBlocking().
int MSLCM_SL2015::checkStrategicChange (int ret, int laneOffset, const std::vector< MSVehicle::LaneQ > & preb, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & neighLeaders, int currIdx, int bestLaneOffset, bool changeToBest, int lcaCounter, double currentDist, double neighDist, double laDist, int roundaboutEdgesAhead, double latLaneDist, double & latDist) protected
compute strategic lane change actions
we urgently need to change lanes to follow our route
Definition at line 1892 of file MSLCM_SL2015.cpp.
References abs, MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, MSVehicle::congested(), currentDistDisallows(), MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicle::getPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), getSlowest(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSLeaderInfo::hasStoppedVehicle(), MSLeaderInfo::hasVehicles(), MSVehicle::influenceChangeDecision(), JAM_FACTOR, LCA_STAY, LCA_STRATEGIC, LCA_TRACI, LCA_URGENT, MSVehicle::LaneQ::length, MAX2(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbThresholdLeft, myLookAheadSpeed, mySpeedGainProbabilityRight, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSVehicle::LaneQ::occupation, SIMTIME, SUMO_const_haltingSpeed, SUMO_const_laneWidth, TS, and TURN_LANE_DIST.
Referenced by _wantsChangeSublane().
void MSAbstractLaneChangeModel::cleanupShadowLane () inherited
Definition at line 237 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::resetChanged(), and MSVehicle::~MSVehicle().
int MSLCM_SL2015::computeSublaneShift (const MSEdge * prevEdge, const MSEdge * curEdge) protected
compute shift so that prevSublane + shift = newSublane
Definition at line 746 of file MSLCM_SL2015.cpp.
References MSEdge::getLanes(), MSLane::getLinkCont(), max, and MSLeaderInfo::numSublanes().
Referenced by prepareStep().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual inherited
Definition at line 114 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::setParameter(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
bool MSLCM_SL2015::currentDistAllows (double dist, int laneOffset, double lookForwardDist) inline protected
Definition at line 204 of file MSLCM_SL2015.h.
References abs.
Referenced by _wantsChangeSublane().
bool MSLCM_SL2015::currentDistDisallows (double dist, int laneOffset, double lookForwardDist) inline protected
Definition at line 201 of file MSLCM_SL2015.h.
References abs.
Referenced by checkStrategicChange().
bool MSLCM_SL2015::debugVehicle () const virtual
whether the current vehicles shall be debugged
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 134 of file MSLCM_SL2015.cpp.
References DEBUG_COND.
MSLCM_SL2015::StateAndDist MSLCM_SL2015::decideDirection (StateAndDist sd1, StateAndDist sd2) const protected virtual
decide in which direction to move in case both directions are desirable
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 1823 of file MSLCM_SL2015.cpp.
References DEBUG_COND, MSAbstractLaneChangeModel::StateAndDist::dir, MSBaseVehicle::getID(), MSAbstractLaneChangeModel::StateAndDist::latDist, LCA_BLOCKED, LCA_CHANGE_REASONS, LCA_STAY, LCA_SUBLANE, LCA_WANTS_LANECHANGE, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::StateAndDist::sameDirection(), SIMTIME, MSAbstractLaneChangeModel::StateAndDist::state, and toString().
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE) inherited
Definition at line 201 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSVehicle::fixPosition(), MSAbstractLaneChangeModel::myAmOpposite, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSAbstractLaneChangeModel::updateShadowLane().
double MSAbstractLaneChangeModel::getAngleOffset () const inherited
return the angle offset during a continuous change maneuver
Definition at line 335 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::pastMidpoint(), and STEPS2TIME.
Referenced by MSAbstractLaneChangeModel::getLaneChangeDirection().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline inherited
return the direction of the current lane change maneuver
Definition at line 322 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::myLaneChangeDirection.
Referenced by MSLaneChanger::continueChange().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline inherited
Definition at line 303 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
double MSAbstractLaneChangeModel::getLateralSpeed () const inline inherited
return the lateral speed of the current lane change maneuver
Definition at line 333 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLateralspeed.
Referenced by MSLaneChanger::continueChange().
LaneChangeAction MSLCM_SL2015::getLCA (int state, double latDist) static protected
compute lane change action from desired lateral distance
Definition at line 1885 of file MSLCM_SL2015.cpp.
References LCA_CHANGE_REASONS, LCA_LEFT, LCA_NONE, and LCA_RIGHT.
Referenced by wantsChange(), and wantsChangeSublane().
CLeaderDist MSLCM_SL2015::getLongest (const MSLeaderDistanceInfo & ldi) static protected
get the longest vehicle in the given info
Definition at line 1590 of file MSLCM_SL2015.cpp.
References MSLeaderInfo::numSublanes().
Referenced by _wantsChangeSublane().
int MSAbstractLaneChangeModel::getOwnState () const inline inherited
Definition at line 152 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState, and MSAbstractLaneChangeModel::setOwnState().
Referenced by saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), and MSVehicle::setBlinkerInformation().
std::string MSLCM_SL2015::getParameter (const std::string & key) const virtual
try to retrieve the given parameter from this device. Throw exception for unsupported key
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 2283 of file MSLCM_SL2015.cpp.
References myAssertive, myCooperativeParam, myKeepRightParam, MSAbstractLaneChangeModel::myModel, myPushy, mySpeedGainParam, myStrategicParam, mySublaneParam, SUMO_ATTR_LCA_ASSERTIVE, SUMO_ATTR_LCA_COOPERATIVE_PARAM, SUMO_ATTR_LCA_KEEPRIGHT_PARAM, SUMO_ATTR_LCA_PUSHY, SUMO_ATTR_LCA_SPEEDGAIN_PARAM, SUMO_ATTR_LCA_STRATEGIC_PARAM, SUMO_ATTR_LCA_SUBLANE_PARAM, and toString().
const std::pair<int, int>& MSAbstractLaneChangeModel::getSavedState (const int dir) const inline inherited
Definition at line 158 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::mySavedStates.
Referenced by TraCI_Vehicle::getLaneChangeState().
int MSAbstractLaneChangeModel::getShadowDirection () const inherited
return the direction in which the current shadow lane lies
Definition at line 318 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, and MSAbstractLaneChangeModel::pastMidpoint().
Referenced by MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::getLaneChangeDirection(), and GUIVehicle::selectBlockingFoes().
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline inherited
Definition at line 295 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
const std::vector<double>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline inherited
Definition at line 299 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline inherited
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 283 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
Referenced by MSVehicle::checkRewindLinkLanes(), checkStrategicChange(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), MSVehicle::isFrontOnLane(), MSVehicle::planMoveInternal(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const inherited
return the shadow lane for the given lane
Definition at line 215 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, and SIMTIME.
CLeaderDist MSLCM_SL2015::getSlowest (const MSLeaderDistanceInfo & ldi) static protected
get the slowest vehicle in the given info
Definition at line 1607 of file MSLCM_SL2015.cpp.
References max, and MSLeaderInfo::numSublanes().
Referenced by _wantsChangeSublane(), and checkStrategicChange().
void * MSLCM_SL2015::inform (void * info, MSVehicle * sender) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 384 of file MSLCM_SL2015.cpp.
References DEBUG_COND, gDebugFlag2, MSBaseVehicle::getID(), MSNet::getInstance(), MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, and STEPS2TIME.
void MSLCM_SL2015::informFollower (int blocked, int dir, const CLeaderDist & neighFollow, double remainingSeconds, double plannedSpeed) protected
decide whether we will try cut in before the follower or allow to be overtaken
Definition at line 526 of file MSLCM_SL2015.cpp.
References ACCEL2SPEED, MSVehicle::congested(), CUT_IN_LEFT_SPEED_THRESHOLD, MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::getWaitingSeconds(), HELP_DECEL_FACTOR, HELP_OVERTAKE, LCA_AMBLOCKINGFOLLOWER, LCA_BLOCKED_BY_FOLLOWER, LCA_MLEFT, LCA_MRIGHT, LCA_RIGHT_IMPATIENCE, MAX2(), MAX_ONRAMP_LENGTH, msg(), MSAbstractLaneChangeModel::myAllowOvertakingRight, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, myVSafes, POSITION_EPS, SPEED2DIST, and STEPS2TIME.
Referenced by informFollowers().
void MSLCM_SL2015::informFollowers (int blocked, int dir, const std::vector< CLeaderDist > & blockers, double remainingSeconds, double plannedSpeed) protected
call informFollower for multiple followers
Definition at line 681 of file MSLCM_SL2015.cpp.
References informFollower().
Referenced by _wantsChangeSublane().
double MSLCM_SL2015::informLeader (int blocked, int dir, const CLeaderDist & neighLead, double remainingSeconds) protected
Definition at line 412 of file MSLCM_SL2015.cpp.
References ACCEL2SPEED, MSCFModel::brakeGap(), MSVehicle::congested(), MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), HELP_OVERTAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED_BY_LEADER, LCA_MLEFT, MAX2(), MIN2(), MIN_FALLBEHIND, msg(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, myVSafes, NUMERICAL_EPS, SPEED2DIST, STEPS2TIME, and MSCFModel::stopSpeed().
Referenced by informLeaders().
double MSLCM_SL2015::informLeaders (int blocked, int dir, const std::vector< CLeaderDist > & blockers, double remainingSeconds) protected
Definition at line 669 of file MSLCM_SL2015.cpp.
References MSVehicle::getSpeed(), informLeader(), MIN2(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by _wantsChangeSublane().
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static inherited
init global model parameters
Definition at line 56 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), MSAbstractLaneChangeModel::myAllowOvertakingRight, and MSAbstractLaneChangeModel::myLCOutput.
Referenced by MSAbstractLaneChangeModel::StateAndDist::sameDirection(), and MSFrame::setMSGlobals().
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected inherited
Definition at line 264 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSAbstractLaneChangeModel::primaryLaneChanged().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline inherited
return true if the vehicle currently performs a lane change maneuver
Definition at line 317 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
bool MSAbstractLaneChangeModel::isOpposite () const inline inherited
Definition at line 386 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAmOpposite.
Referenced by MSLCM_LC2013::_wantsChange(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtInsertion(), MSLink::getLeaderInfo(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSLCM_LC2013::informLeader(), and MSVehicle::planMoveInternal().
int MSLCM_SL2015::keepLatGap (int state, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, int laneOffset, double & latDist, int & blocked) protected
check whether lateral gap requirements are met override the current maneuver if necessary
XXX to be made configurable
Definition at line 2054 of file MSLCM_SL2015.cpp.
References checkBlocking(), gDebugFlag2, MSVehicle::getCenterOnEdge(), MSLane::getEdge(), MSVehicle::getInfluencer(), MSVehicle::getLane(), MSVehicle::Influencer::getLatDist(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), MSLane::getRightSideOnEdge(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSEdge::getWidth(), MSVehicle::hasInfluencer(), LCA_BLOCKED_LEFT, LCA_BLOCKED_RIGHT, LCA_COOPERATIVE, LCA_OVERLAPPING, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, MAX2(), MIN2(), MSAbstractLaneChangeModel::myLastLateralGapLeft, MSAbstractLaneChangeModel::myLastLateralGapRight, myPushy, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::NO_LATERAL_NEIGHBOR, NUMERICAL_EPS, toString(), and updateGaps().
Referenced by wantsChangeSublane().
void MSLCM_SL2015::msg (const CLeaderDist & cld, double speed, int state) protected
send a speed recommendation to the given vehicle
Definition at line 405 of file MSLCM_SL2015.cpp.
References MSAbstractLaneChangeModel::myVehicle.
Referenced by informFollower(), and informLeader().
bool MSLCM_SL2015::overlap (double right, double left, double right2, double left2) static protected
return whether the given intervals overlap
Definition at line 1815 of file MSLCM_SL2015.cpp.
References NUMERICAL_EPS.
Referenced by checkBlockingVehicles().
bool MSAbstractLaneChangeModel::pastMidpoint () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 309 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::remainingTime().
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::updateCompletion().
double MSLCM_SL2015::patchSpeed (const double min, const double wanted, const double max, const MSCFModel & cfModel) virtual
Called to adapt the speed in order to allow a lane change.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implements MSAbstractLaneChangeModel.
Definition at line 221 of file MSLCM_SL2015.cpp.
References _patchSpeed(), DEBUG_COND, gDebugFlag2, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, and toString().
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, double > & leader) protected virtual inherited
Definition at line 134 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), MSAbstractLaneChangeModel::myCarFollowModel, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::setParameter(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
void MSLCM_SL2015::prepareStep () virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 692 of file MSLCM_SL2015.cpp.
References computeSublaneShift(), MSLane::getEdge(), MSVehicle::getLane(), MSEdge::getLanes(), MSEdge::getSubLaneSides(), MSGlobals::gLateralResolution, LCA_STRATEGIC, LCA_WANTS_LANECHANGE, max, MAX2(), myCanChangeFully, myDontBrake, myExpectedSublaneSpeeds, myKeepRightProbability, myLastEdge, MSAbstractLaneChangeModel::myLastLateralGapLeft, MSAbstractLaneChangeModel::myLastLateralGapRight, myLeadingBlockerLength, myLeftSpace, myOrigLatDist, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbabilityLeft, mySpeedGainProbabilityRight, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSAbstractLaneChangeModel::NO_LATERAL_NEIGHBOR, and MSAbstractLaneChangeModel::prepareStep().
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction) inherited
called once when the vehicles primary lane changes
Definition at line 166 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), OutputDevice::closeTag(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getSpeed(), MSGlobals::gLateralResolution, MSAbstractLaneChangeModel::initLastLaneChangeOffset(), LCA_LEFT, LCA_RIGHT, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), MSAbstractLaneChangeModel::myLastLateralGapLeft, MSAbstractLaneChangeModel::myLastLateralGapRight, MSAbstractLaneChangeModel::myLCOutput, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::NO_LATERAL_NEIGHBOR, MSMoveReminder::NOTIFICATION_LANE_CHANGE, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, time2string(), toString(), and OutputDevice::writeAttr().
Referenced by MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::remainingTime () const inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 342 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and MSAbstractLaneChangeModel::myLaneChangeCompletion.
Referenced by MSAbstractLaneChangeModel::pastMidpoint().
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const inherited
Definition at line 354 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::resetChanged () inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 343 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSAbstractLaneChangeModel::updateCompletion(), and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by MSVehicle::planMove().
void MSLCM_SL2015::saveBlockerLength (const MSVehicle * blocker, int lcaCounter) protected
save space for vehicles which need to counter-lane-change
Definition at line 1516 of file MSLCM_SL2015.cpp.
References MSCFModel::brakeGap(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSAbstractLaneChangeModel::getOwnState(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MAX2(), myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, and toString().
Referenced by _wantsChangeSublane().
void MSLCM_SL2015::saveBlockerLength (double length) inline protected virtual
reserve space at the end of the lane to avoid dead locks
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 185 of file MSLCM_SL2015.h.
References MAX2(), and myLeadingBlockerLength.
void MSAbstractLaneChangeModel::saveState (const int dir, const int stateWithoutTraCI, const int state) inline inherited
Definition at line 162 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::mySavedStates.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), and MSAbstractLaneChangeModel::prepareStep().
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 375 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), and MSAbstractLaneChangeModel::setShadowApproachingInformation().
Referenced by MSVehicle::enterLaneAtLaneChange().
void MSLCM_SL2015::setOwnState (const int state) virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 204 of file MSLCM_SL2015.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), LCA_STAY, myCanChangeFully, myOrigLatDist, myPreviousState, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::setOwnState(), SIMTIME, and toString().
void MSLCM_SL2015::setParameter (const std::string & key, const std::string & value) virtual
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 2303 of file MSLCM_SL2015.cpp.
References TplConvert::_2double(), LCA_KEEPRIGHT, myAssertive, myCooperativeParam, myKeepRightParam, MSAbstractLaneChangeModel::myModel, myPushy, mySpeedGainParam, myStrategicParam, mySublaneParam, SUMO_ATTR_LCA_ASSERTIVE, SUMO_ATTR_LCA_COOPERATIVE_PARAM, SUMO_ATTR_LCA_PUSHY, SUMO_ATTR_LCA_SPEEDGAIN_PARAM, SUMO_ATTR_LCA_STRATEGIC_PARAM, SUMO_ATTR_LCA_SUBLANE_PARAM, and toString().
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const inherited
set approach information for the shadow vehicle
Definition at line 348 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline inherited
set the shadow lane
Definition at line 291 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 371 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow.
int MSLCM_SL2015::slowDownForBlocked (MSVehicle ** blocked, int state) protected
compute useful slowdowns for blocked vehicles
Definition at line 1480 of file MSLCM_SL2015.cpp.
References ACCEL2SPEED, MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, myVSafes, POSITION_EPS, STEPS2TIME, and SUMO_const_haltingSpeed.
Referenced by _wantsChangeSublane().
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction) inherited
start the lane change maneuver and return whether it continues
Definition at line 147 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLateralspeed, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::primaryLaneChanged(), MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::changeOpposite(), MSAbstractLaneChangeModel::resetChanged(), MSLaneChanger::startChange(), and MSLaneChangerSublane::startChangeSublane().
void MSAbstractLaneChangeModel::unchanged () inline inherited
Definition at line 272 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
bool MSAbstractLaneChangeModel::updateCompletion () inherited
Definition at line 193 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::pastMidpoint().
Referenced by MSLaneChanger::continueChange(), and MSAbstractLaneChangeModel::resetChanged().
void MSLCM_SL2015::updateExpectedSublaneSpeeds (const MSLeaderInfo & ahead, int sublaneOffset, int laneIndex) protected virtual
update expected speeds for each sublane of the current edge
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 1556 of file MSLCM_SL2015.cpp.
References MSLane::allowsVehicleClass(), MSCFModel::followSpeed(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanes(), MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSVehicle::getLane(), MSEdge::getLanes(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicleType::getVehicleClass(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MIN2(), MSAbstractLaneChangeModel::myCarFollowModel, myExpectedSublaneSpeeds, MSAbstractLaneChangeModel::myVehicle, and MSLeaderInfo::numSublanes().
void MSLCM_SL2015::updateGaps (const MSLeaderDistanceInfo & others, double foeOffset, double oldCenter, double gapFactor, double & surplusGapRight, double & surplusGapLeft, bool saveMinGap = false, double netOverlap = 0) protected
check remaining lateral gaps for the given foe vehicles and optionally update minimum lateral gaps
foe vehicle occupies full sublanes
Definition at line 2227 of file MSLCM_SL2015.cpp.
References gDebugFlag2, MSBaseVehicle::getID(), MSVehicleType::getMinGapLat(), MSVehicle::getSpeed(), MSLeaderInfo::getSublaneBorders(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLateralResolution, MSLeaderInfo::hasVehicles(), LATGAP_SPEED_THRESHOLD, MAX2(), MIN2(), MSAbstractLaneChangeModel::myLastLateralGapLeft, MSAbstractLaneChangeModel::myLastLateralGapRight, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSLeaderInfo::numSublanes(), POSITION_EPS, and SUMO_const_haltingSpeed.
Referenced by checkBlocking(), and keepLatGap().
void MSAbstractLaneChangeModel::updateShadowLane () inherited
Definition at line 273 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSLinkContHelper::getConnectingLink(), MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSLaneChangerSublane::startChangeSublane().
int MSLCM_SL2015::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, double > & leader, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) virtual
Called to examine whether the vehicle wants to change using the given laneOffset (this is a wrapper around wantsChangeSublane). This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 2331 of file MSLCM_SL2015.cpp.
References _wantsChangeSublane(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), getLCA(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), LCA_BLOCKED, LCA_CHANGE_TO_HELP, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_OVERLAPPING, LCA_SPEEDGAIN, LCA_STRATEGIC, LCA_SUBLANE, LCA_TRACI, LCA_URGENT, LCA_WANTS_LANECHANGE, myCanChangeFully, myOrigLatDist, MSAbstractLaneChangeModel::myVehicle, and STEPS2TIME.
int MSLCM_SL2015::wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, double & latDist, int & blocked) virtual
Called to examine whether the vehicle wants to change with the given laneOffset (using the sublane model) This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 140 of file MSLCM_SL2015.cpp.
References _wantsChangeSublane(), DEBUG_COND, gDebugFlag2, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), getLCA(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), gPrecision, keepLatGap(), LCA_BLOCKED, LCA_OVERLAPPING, LCA_WANTS_LANECHANGE, MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, and toString().
Field Documentation
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected inherited
whether overtaking on the right is permitted
Definition at line 461 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_wantsChange(), checkStrategicChange(), MSLCM_LC2013::informFollower(), informFollower(), MSLCM_LC2013::informLeader(), informLeader(), and MSAbstractLaneChangeModel::initGlobalOptions().
bool MSAbstractLaneChangeModel::myAlreadyChanged protected inherited
whether the vehicle has already moved this step
Definition at line 428 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::alreadyChanged(), MSAbstractLaneChangeModel::changedToOpposite(), and MSAbstractLaneChangeModel::resetChanged().
double MSLCM_SL2015::myAssertive protected
Definition at line 339 of file MSLCM_SL2015.h.
Referenced by checkBlockingVehicles(), getParameter(), and setParameter().
bool MSLCM_SL2015::myCanChangeFully protected
whether the current lane changing meneuver can be finished in a single step
Definition at line 322 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), checkBlocking(), prepareStep(), setOwnState(), and wantsChange().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected inherited
The vehicle's car following model.
Definition at line 439 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_wantsChange(), checkStrategicChange(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_LC2013::informLeader(), informLeader(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_LC2013::slowDownForBlocked(), slowDownForBlocked(), updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
const double MSLCM_SL2015::myChangeProbThresholdLeft protected
Definition at line 346 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), and checkStrategicChange().
const double MSLCM_SL2015::myChangeProbThresholdRight protected
Definition at line 345 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane().
double MSLCM_SL2015::myCooperativeParam protected
Definition at line 333 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), getParameter(), and setParameter().
bool MSLCM_SL2015::myDontBrake protected
flag to prevent speed adaptation by slowing down
Definition at line 319 of file MSLCM_SL2015.h.
Referenced by _patchSpeed(), changed(), and prepareStep().
std::vector<double> MSLCM_SL2015::myExpectedSublaneSpeeds protected
expected travel speeds on all sublanes on the current edge(!)
Definition at line 313 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), prepareStep(), and updateExpectedSublaneSpeeds().
double MSLCM_SL2015::myKeepRightParam protected
Definition at line 335 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), getParameter(), and setParameter().
double MSLCM_SL2015::myKeepRightProbability protected
Definition at line 300 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), and prepareStep().
double MSAbstractLaneChangeModel::myLaneChangeCompletion protected inherited
progress of the lane change maneuver 0:started, 1:complete
Definition at line 419 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::pastMidpoint(), MSAbstractLaneChangeModel::remainingTime(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::updateCompletion().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected inherited
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 422 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getLaneChangeDirection(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
const MSEdge* MSLCM_SL2015::myLastEdge protected
expected travel speeds on all sublanes on the current edge(!)
Definition at line 316 of file MSLCM_SL2015.h.
Referenced by prepareStep().
double MSAbstractLaneChangeModel::myLastLateralGapLeft protected inherited
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
Definition at line 452 of file MSAbstractLaneChangeModel.h.
Referenced by keepLatGap(), prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), and updateGaps().
double MSAbstractLaneChangeModel::myLastLateralGapRight protected inherited
Definition at line 453 of file MSAbstractLaneChangeModel.h.
Referenced by keepLatGap(), prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), and updateGaps().
double MSAbstractLaneChangeModel::myLateralspeed protected inherited
The lateral offset during a continuous LaneChangeManeuver.
Definition at line 425 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getLateralSpeed(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLCOutput static protected inherited
whether to record lane-changing
Definition at line 464 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::initGlobalOptions(), and MSAbstractLaneChangeModel::primaryLaneChanged().
double MSLCM_SL2015::myLeadingBlockerLength protected
Definition at line 302 of file MSLCM_SL2015.h.
Referenced by _patchSpeed(), _wantsChangeSublane(), changed(), informLeader(), prepareStep(), and saveBlockerLength().
double MSLCM_SL2015::myLeftSpace protected
Definition at line 303 of file MSLCM_SL2015.h.
Referenced by _patchSpeed(), _wantsChangeSublane(), changed(), informFollower(), informLeader(), prepareStep(), and saveBlockerLength().
double MSLCM_SL2015::myLookAheadSpeed protected
Definition at line 307 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), and checkStrategicChange().
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected inherited
the type of this model
Definition at line 442 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::decideDirection(), MSLCM_LC2013::getParameter(), getParameter(), MSAbstractLaneChangeModel::getParameter(), MSLCM_LC2013::setParameter(), setParameter(), MSAbstractLaneChangeModel::setParameter(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::wantsChange(), and MSAbstractLaneChangeModel::wantsChangeSublane().
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected inherited
Definition at line 449 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
double MSLCM_SL2015::myOrigLatDist protected
the complete lateral distance the vehicle wants to travel to finish its maneuver
Definition at line 328 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), checkBlocking(), prepareStep(), setOwnState(), and wantsChange().
int MSAbstractLaneChangeModel::myOwnState protected inherited
The current state of the vehicle.
Definition at line 415 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_patchSpeed(), _patchSpeed(), MSLCM_LC2013::_wantsChange(), _wantsChangeSublane(), MSLCM_DK2008::amBlockingFollower(), amBlockingFollower(), MSLCM_LC2013::amBlockingFollower(), MSLCM_DK2008::amBlockingFollowerNB(), amBlockingFollowerNB(), MSLCM_LC2013::amBlockingFollowerNB(), MSLCM_DK2008::amBlockingFollowerPlusNB(), amBlockingFollowerPlusNB(), MSLCM_LC2013::amBlockingFollowerPlusNB(), MSLCM_DK2008::amBlockingLeader(), amBlockingLeader(), MSLCM_LC2013::amBlockingLeader(), MSLCM_DK2008::changed(), MSLCM_LC2013::changed(), changed(), MSAbstractLaneChangeModel::getOwnState(), MSLCM_DK2008::inform(), MSLCM_LC2013::inform(), inform(), MSLCM_DK2008::patchSpeed(), MSLCM_DK2008::prepareStep(), MSLCM_LC2013::prepareStep(), prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::setOwnState(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected inherited
list of lanes where the shadow vehicle is partial occupator
Definition at line 445 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::setShadowPartialOccupator().
int MSLCM_SL2015::myPreviousState protected
lane changing state from the previous simulation step
Definition at line 325 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), and setOwnState().
double MSLCM_SL2015::myPushy protected
Definition at line 338 of file MSLCM_SL2015.h.
Referenced by checkBlocking(), getParameter(), keepLatGap(), and setParameter().
std::map<int, std::pair<int, int> > MSAbstractLaneChangeModel::mySavedStates protected inherited
Definition at line 416 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getSavedState(), and MSAbstractLaneChangeModel::saveState().
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected inherited
Definition at line 435 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
std::vector<double> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected inherited
Definition at line 436 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected inherited
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 431 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::setShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
double MSLCM_SL2015::mySpeedGainParam protected
Definition at line 334 of file MSLCM_SL2015.h.
Referenced by getParameter(), and setParameter().
double MSLCM_SL2015::mySpeedGainProbabilityLeft protected
a value for tracking the probability that a change to the left is beneficial
Definition at line 295 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), and prepareStep().
double MSLCM_SL2015::mySpeedGainProbabilityRight protected
a value for tracking the probability that a change to the right is beneficial
Definition at line 293 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), checkStrategicChange(), and prepareStep().
const double MSLCM_SL2015::mySpeedLossProbThreshold protected
Definition at line 347 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane().
double MSLCM_SL2015::myStrategicParam protected
Definition at line 332 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), getParameter(), and setParameter().
double MSLCM_SL2015::mySublaneParam protected
Definition at line 336 of file MSLCM_SL2015.h.
Referenced by getParameter(), and setParameter().
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected inherited
The vehicle this lane-changer belongs to.
Definition at line 412 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_patchSpeed(), _patchSpeed(), MSLCM_LC2013::_wantsChange(), _wantsChangeSublane(), MSAbstractLaneChangeModel::cancelRequest(), MSLCM_LC2013::changed(), changed(), checkBlocking(), checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::congested(), decideDirection(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSLCM_LC2013::inform(), inform(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), informFollower(), MSLCM_LC2013::informLeader(), informLeader(), informLeaders(), keepLatGap(), msg(), MSLCM_LC2013::MSLCM_LC2013(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), patchSpeed(), MSAbstractLaneChangeModel::predInteraction(), prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), setOwnState(), MSAbstractLaneChangeModel::setOwnState(), MSLCM_LC2013::slowDownForBlocked(), slowDownForBlocked(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), updateExpectedSublaneSpeeds(), updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_LC2013::wantsChange(), wantsChange(), wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector<double> MSLCM_SL2015::myVSafes protected
speed adaptation requests by ego and surrounding vehicles
Definition at line 310 of file MSLCM_SL2015.h.
Referenced by _patchSpeed(), changed(), checkStrategicChange(), inform(), informFollower(), informLeader(), prepareStep(), and slowDownForBlocked().
const double MSAbstractLaneChangeModel::NO_LATERAL_NEIGHBOR static protected inherited
Definition at line 466 of file MSAbstractLaneChangeModel.h.
Referenced by keepLatGap(), prepareStep(), and MSAbstractLaneChangeModel::primaryLaneChanged().
The documentation for this class was generated from the following files:
MSLCM_SL2015.h
MSLCM_SL2015.cpp