SUMO - Simulation of Urban MObility: GUITextureSubSys Class Reference
GUITextureSubSys Class Reference
#include <GUITextureSubSys.h>
Static Public Member Functions
static void close ()
close GUITextureSubSys
static GUIGlID getTexture (GUITexture which)
returns a texture previously defined in the enum GUITexture
static void initTextures (FXApp *a)
Initiate GUITextureSubSys for textures.
static void resetTextures ()
Reset textures.
Private Member Functions
GUITextureSubSys (FXApp *a)
constructor private because is called by the static function init(FXApp* a
~GUITextureSubSys ()
destructor
Private Attributes
FXApp * myApp
to Fox App
std::map< GUITexture, std::pair< bool, GUIGlID > > myTextures
vector with the Gifs
Static Private Attributes
static GUITextureSubSys * myInstance = 0
instance of GUITextureSubSys
Detailed Description
Definition at line 41 of file GUITextureSubSys.h.
Constructor & Destructor Documentation
GUITextureSubSys::GUITextureSubSys (FXApp * a) private
constructor private because is called by the static function init(FXApp* a
Definition at line 72 of file GUITextureSubSys.cpp.
References GNETEXTURE_E1, GNETEXTURE_E2, GNETEXTURE_E3, GNETEXTURE_E3SELECTED, GNETEXTURE_EMPTY, GNETEXTURE_EMPTYSELECTED, GNETEXTURE_ENTRY, GNETEXTURE_EXIT, GNETEXTURE_LANEBIKE, GNETEXTURE_LANEBUS, GNETEXTURE_LANEPEDESTRIAN, GNETEXTURE_LOCK, GNETEXTURE_LOCKSELECTED, GNETEXTURE_NOTMOVING, GNETEXTURE_NOTMOVINGSELECTED, GNETEXTURE_REROUTER, GNETEXTURE_REROUTERSELECTED, GNETEXTURE_ROUTEPROBE, GNETEXTURE_ROUTEPROBESELECTED, GNETEXTURE_TLS, GNETEXTURE_VAPORIZER, GNETEXTURE_VAPORIZERSELECTED, GNETEXTURE_VARIABLESPEEDSIGN, GNETEXTURE_VARIABLESPEEDSIGNSELECTED, and myTextures.
Referenced by initTextures().
GUITextureSubSys::~GUITextureSubSys () private
destructor
Definition at line 102 of file GUITextureSubSys.cpp.
Member Function Documentation
void GUITextureSubSys::close () static
close GUITextureSubSys
Definition at line 214 of file GUITextureSubSys.cpp.
References myInstance.
Referenced by GNEApplicationWindow::~GNEApplicationWindow().
GUIGlID GUITextureSubSys::getTexture (GUITexture which) static
returns a texture previously defined in the enum GUITexture
Parameters
[in] GUITexture code of texture to use
Definition at line 114 of file GUITextureSubSys.cpp.
References GUITexturesHelper::add(), GNETexture_E1, GNETEXTURE_E1, GNETexture_E2, GNETEXTURE_E2, GNETexture_E3, GNETEXTURE_E3, GNETexture_E3Selected, GNETEXTURE_E3SELECTED, GNETexture_Empty, GNETEXTURE_EMPTY, GNETexture_EmptySelected, GNETEXTURE_EMPTYSELECTED, GNETexture_Entry, GNETEXTURE_ENTRY, GNETexture_Exit, GNETEXTURE_EXIT, GNETexture_LaneBike, GNETEXTURE_LANEBIKE, GNETexture_LaneBus, GNETEXTURE_LANEBUS, GNETexture_LanePedestrian, GNETEXTURE_LANEPEDESTRIAN, GNETexture_Lock, GNETEXTURE_LOCK, GNETexture_LockSelected, GNETEXTURE_LOCKSELECTED, GNETexture_NotMoving, GNETEXTURE_NOTMOVING, GNETexture_NotMovingSelected, GNETEXTURE_NOTMOVINGSELECTED, GNETexture_Rerouter, GNETEXTURE_REROUTER, GNETexture_RerouterSelected, GNETEXTURE_REROUTERSELECTED, GNETexture_RouteProbe, GNETEXTURE_ROUTEPROBE, GNETexture_RouteProbeSelected, GNETEXTURE_ROUTEPROBESELECTED, GNETexture_TLS, GNETEXTURE_TLS, GNETexture_Vaporizer, GNETEXTURE_VAPORIZER, GNETexture_VaporizerSelected, GNETEXTURE_VAPORIZERSELECTED, GNETexture_VariableSpeedSign, GNETEXTURE_VARIABLESPEEDSIGN, GNETexture_VariableSpeedSignSelected, GNETEXTURE_VARIABLESPEEDSIGNSELECTED, myApp, myInstance, and myTextures.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEJunction::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSign::drawGL(), GNERouteProbe::drawGL(), GNERerouter::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), and GNEAdditional::drawLockIcon().
void GUITextureSubSys::initTextures (FXApp * a) static
Initiate GUITextureSubSys for textures.
Parameters
[in] a FOX Toolkit APP
Definition at line 107 of file GUITextureSubSys.cpp.
References GUITextureSubSys(), and myInstance.
Referenced by GNEApplicationWindow::GNEApplicationWindow().
void GUITextureSubSys::resetTextures () static
Reset textures.
Note
Necessary to avoid problems with textures (ej: white empty)
Definition at line 204 of file GUITextureSubSys.cpp.
References GUITexturesHelper::clearTextures(), myInstance, and myTextures.
Referenced by GNEApplicationWindow::closeAllWindows(), and GNEViewNet::doPaintGL().
Field Documentation
FXApp* GUITextureSubSys::myApp private
to Fox App
Definition at line 69 of file GUITextureSubSys.h.
Referenced by getTexture().
GUITextureSubSys * GUITextureSubSys::myInstance = 0 static private
instance of GUITextureSubSys
Definition at line 72 of file GUITextureSubSys.h.
Referenced by close(), getTexture(), initTextures(), and resetTextures().
std::map<GUITexture, std::pair<bool, GUIGlID> > GUITextureSubSys::myTextures private
vector with the Gifs
Definition at line 75 of file GUITextureSubSys.h.
Referenced by getTexture(), GUITextureSubSys(), and resetTextures().
The documentation for this class was generated from the following files:
GUITextureSubSys.h
GUITextureSubSys.cpp