# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    bld.env.append_value("LIB", ["boost_system", "boost_filesystem", "boost_serialization"])

    module = bld.create_ns3_module('roff', ['core'])
    module.source = [
    	'helper/roff-helper.cc',
        'model/ROFFNode.cc',
        'model/ROFFHeader.cc',
        'model/ROFFApplication.cc',
        'model/NeighborTable.cc',
        'model/NBTEntry.cc',
        'model/PositionRankingMap.cc',
        'model/PositionRankingKey.cc',
        'model/Edge.cc'
        ]

    module_test = bld.create_ns3_module_test_library('roff')
    module_test.source = [
        'test/roff-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'roff'
    headers.source = [
        'helper/roff-helper.h',
        'model/ROFFNode.h',
        'model/ROFFHeader.h',
        'model/ROFFApplication.h',
        'model/NeighborTable.h',
        'model/NBTEntry.h',
        'model/PositionRankingMap.h',
        'model/PositionRankingKey.h',
        'model/Edge.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

