# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('fb-vanet-urban', ['fast-broadcast'])
    obj.source = 'fb-vanet-urban.cc'

    obj = bld.create_ns3_program('fb-vanet-3d', ['fast-broadcast'])
    obj.source = 'fb-vanet-3d.cc'

